### ISSUE TITLE
China - no more deaths recorded in the last 24 hours?

### ISSUE THREAD

**Issue by Shane073** [CSSEGISandData/COVID-19#100]
So has China reported no more deaths in the last 24 hours?

**Comment by CSSEGISandData** [comment]
It does not seem like there has been any deaths reported from China since the last update based on the current case data and yesterdays case data.

**Comment by Shane073** [comment]
Do you get your data on China from here? http://www.nhc.gov.cn/yjb/pqt/new_list.shtml

**Comment by CSSEGISandData** [comment]
The current list of sources can be found In the README.md file at the root directory level of this repository.

**Comment by Shane073** [comment]
I have gone through four of the sources you have listed on the README.md file and they all have different data to what you have here on Github for the 21st Feb. 

You have zero deaths increase from the 20th Feb (2236) to 21st Feb (2236). 

All these other sources have an increase of 109. Which would take the count from 2236 to 2345.

![CCD - Data - 22 2 20](https://user-images.githubusercontent.com/36460101/75087164-f9a1bf00-5590-11ea-8b5a-f2c6a4dbbc8c.png)
![NHC Data - 22 2 20](https://user-images.githubusercontent.com/36460101/75087165-fb6b8280-5590-11ea-87e5-f0cd163c01ee.png)
![ncov - dxy - data - 22 2 20](https://user-images.githubusercontent.com/36460101/75087167-fd354600-5590-11ea-8c5c-8acf0c33c378.png)
![BNO NEWS - Data - 22 2 20](https://user-images.githubusercontent.com/36460101/75087172-03c3bd80-5591-11ea-87ef-bf177f63f781.png)

**Comment by Shane073** [comment]
Here is the data that you have for 20th and the 21st.

I am sorry, I am just confused as to why you would have the same counts for the 20th and 21st, when the sources you use for your data from have different counts.

What am I missing? 

![github - data - 22 2 20](https://user-images.githubusercontent.com/36460101/75087263-230f1a80-5592-11ea-9ea9-b23c5f1a5fa9.png)
