### ISSUE TITLE
Data issues - reported deaths

### ISSUE THREAD

**Issue by Shane073** [CSSEGISandData/COVID-19#101]
Thanks for answering my earlier question in relation to this issue. I just saw on http://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm they have a different total as to the reported 2236 deaths for China in the latest data release. 

Why does the latest data release have a total of 2236? Was China late to release their data before you did your update?

Can we please can an update to reflect the latest correct count?

**Comment by CSSEGISandData** [comment]
The dashboard will be updated as new reports are released. The data within this repo is updated once a day around 12 am UTC (7pm EST).
