### ISSUE TITLE
Data Issues : Please take a look : Error Report Attached

### ISSUE THREAD

**Issue by irshadk** [CSSEGISandData/COVID-19#1013]
I think the latest data published has issues. Please take a look. 

I have published the error report below.

DATA_ERR::CONFIRMED::Japan,::1/23/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::Japan,::2/7/20::ERR_MARGIN  -20
DATA_ERR::CONFIRMED::Japan,::3/16/20::ERR_MARGIN  -14
DATA_ERR::CONFIRMED::Australia,Queensland::1/31/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::Australia,Queensland::2/2/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::Australia,From Diamond Princess::2/29/20::ERR_MARGIN  -8
DATA_ERR::CONFIRMED::Lebanon,::3/16/20::ERR_MARGIN  -11
DATA_ERR::CONFIRMED::Bahrain,::3/13/20::ERR_MARGIN  -6
DATA_ERR::CONFIRMED::Azerbaijan,::3/16/20::ERR_MARGIN  -8
DATA_ERR::CONFIRMED::Australia,Northern Territory::3/6/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Washington::3/18/20::ERR_MARGIN  -62
DATA_ERR::CONFIRMED::US,Grand Princess::3/16/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Nevada::3/18/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::Cruise Ship,Diamond Princess::3/6/20::ERR_MARGIN  -10
DATA_ERR::CONFIRMED::China,Guizhou::3/18/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::France,Saint Barthelemy::3/9/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Bennington County, VT::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Carver County, MN::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Charlotte County, FL::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Cherokee County, GA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Collin County, TX::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Jefferson County, KY::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Jefferson Parish, LA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Shasta County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Spartanburg County, SC::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Harrison County, KY::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Johnson County, IA::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Berkshire County, MA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Davidson County, TN::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Douglas County, OR::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Fresno County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Harford County, MD::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Hendricks County, IN::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Hudson County, NJ::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Johnson County, KS::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Kittitas County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Manatee County, FL::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Marion County, OR::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Okaloosa County, FL::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Polk County, GA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Riverside County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Shelby County, TN::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,St. Louis County, MO::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Suffolk County, NY::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Ulster County, NY::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Volusia County, FL::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Fairfax County, VA::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Rockingham County, NH::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Washington, D.C.::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Montgomery County, PA::3/10/20::ERR_MARGIN  -5
DATA_ERR::CONFIRMED::US,Alameda County, CA::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Broward County, FL::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Lee County, FL::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Pinal County, AZ::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Rockland County, NY::3/10/20::ERR_MARGIN  -4
DATA_ERR::CONFIRMED::US,Saratoga County, NY::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Charleston County, SC::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Clark County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Cobb County, GA::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Davis County, UT::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,El Paso County, CO::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Honolulu County, HI::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Jackson County, OR ::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Jefferson County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Kershaw County, SC::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Klamath County, OR::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Madera County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Pierce County, WA::3/10/20::ERR_MARGIN  -4
DATA_ERR::CONFIRMED::US,Tulsa County, OK::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Douglas County, CO::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Providence County, RI::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Chatham County, NC::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Delaware County, PA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Douglas County, NE::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Fayette County, KY::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Marion County, IN::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Middlesex County, MA::3/10/20::ERR_MARGIN  -7
DATA_ERR::CONFIRMED::US,Nassau County, NY::3/10/20::ERR_MARGIN  -17
DATA_ERR::CONFIRMED::US,Ramsey County, MN::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Washoe County, NV::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Wayne County, PA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Yolo County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Santa Clara County, CA::3/10/20::ERR_MARGIN  -38
DATA_ERR::CONFIRMED::US,Clark County, NV::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Fort Bend County, TX::3/10/20::ERR_MARGIN  -6
DATA_ERR::CONFIRMED::US,Grant County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Santa Rosa County, FL::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Williamson County, TN::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,New York County, NY::3/10/20::ERR_MARGIN  -19
DATA_ERR::CONFIRMED::US,Montgomery County, MD::3/10/20::ERR_MARGIN  -4
DATA_ERR::CONFIRMED::US,Suffolk County, MA::3/10/20::ERR_MARGIN  -8
DATA_ERR::CONFIRMED::US,Denver County, CO::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Summit County, CO::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Bergen County, NJ::3/10/20::ERR_MARGIN  -4
DATA_ERR::CONFIRMED::US,Harris County, TX::3/10/20::ERR_MARGIN  -6
DATA_ERR::CONFIRMED::US,San Francisco County, CA::3/10/20::ERR_MARGIN  -9
DATA_ERR::CONFIRMED::US,Contra Costa County, CA::3/10/20::ERR_MARGIN  -9
DATA_ERR::CONFIRMED::US,Orange County, CA::3/10/20::ERR_MARGIN  -4
DATA_ERR::CONFIRMED::US,Norfolk County, MA::3/10/20::ERR_MARGIN  -6
DATA_ERR::CONFIRMED::US,Maricopa County, AZ::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Wake County, NC::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Westchester County, NY::3/10/20::ERR_MARGIN  -98
DATA_ERR::CONFIRMED::US,Grafton County, NH::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Hillsborough, FL::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Placer County, CA::3/10/20::ERR_MARGIN  -7
DATA_ERR::CONFIRMED::US,San Mateo, CA::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Sonoma County, CA::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,Umatilla, OR::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Fulton County, GA::3/10/20::ERR_MARGIN  -5
DATA_ERR::CONFIRMED::US,Washington County, OR::3/10/20::ERR_MARGIN  -8
DATA_ERR::CONFIRMED::US,Snohomish County, WA::3/10/20::ERR_MARGIN  -31
DATA_ERR::CONFIRMED::US,Humboldt County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::CONFIRMED::US,Sacramento County, CA::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,San Diego County, CA::3/10/20::ERR_MARGIN  -3
DATA_ERR::CONFIRMED::US,San Benito, CA::3/10/20::ERR_MARGIN  -2
DATA_ERR::CONFIRMED::US,Los Angeles, CA::3/10/20::ERR_MARGIN  -14
DATA_ERR::CONFIRMED::US,King County, WA::3/10/20::ERR_MARGIN  -83
DATA_ERR::CONFIRMED::US,Cook County, IL::3/10/20::ERR_MARGIN  -7
DATA_ERR::CONFIRMED::Montenegro,::3/18/20::ERR_MARGIN  -1

DATA_ERR::RECOVERED::Italy,::2/24/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::Egypt,::3/15/20::ERR_MARGIN  -6
DATA_ERR::RECOVERED::Austria,::3/17/20::ERR_MARGIN  -5
DATA_ERR::RECOVERED::Iceland,::3/16/20::ERR_MARGIN  -8
DATA_ERR::RECOVERED::Andorra,::3/13/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Washington::3/18/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,California::3/18/20::ERR_MARGIN  -6
DATA_ERR::RECOVERED::US,Massachusetts::3/18/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,New Jersey::3/18/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Illinois::3/18/20::ERR_MARGIN  -2
DATA_ERR::RECOVERED::US,Maryland::3/18/20::ERR_MARGIN  -3
DATA_ERR::RECOVERED::US,Arizona::3/18/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Kentucky::3/18/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Wisconsin::3/18/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::Korea, South,::3/8/20::ERR_MARGIN  -17
DATA_ERR::RECOVERED::Cruise Ship,Diamond Princess::2/23/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::China,Heilongjiang::2/11/20::ERR_MARGIN  -2
DATA_ERR::RECOVERED::China,Guangxi::2/12/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::China,Hainan::2/15/20::ERR_MARGIN  -4
DATA_ERR::RECOVERED::China,Guizhou::2/6/20::ERR_MARGIN  -3
DATA_ERR::RECOVERED::China,Shanxi::2/3/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::China,Hong Kong::2/21/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::China,Ningxia::2/9/20::ERR_MARGIN  -2
DATA_ERR::RECOVERED::US,Santa Clara County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Suffolk County, MA::3/10/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Maricopa County, AZ::3/10/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,San Diego County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,King County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::RECOVERED::US,Cook County, IL::3/10/20::ERR_MARGIN  -2

DATA_ERR::DEATHS::Iceland,::3/16/20::ERR_MARGIN  -5
DATA_ERR::DEATHS::US,Lee County, FL::3/10/20::ERR_MARGIN  -1
DATA_ERR::DEATHS::US,Grant County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::DEATHS::US,Santa Rosa County, FL::3/10/20::ERR_MARGIN  -1
DATA_ERR::DEATHS::US,Placer County, CA::3/10/20::ERR_MARGIN  -1
DATA_ERR::DEATHS::US,Snohomish County, WA::3/10/20::ERR_MARGIN  -1
DATA_ERR::DEATHS::US,King County, WA::3/10/20::ERR_MARGIN  -17

**Comment by NewAlexandria** [comment]
Can you please open a PR with data changes and clearly referenced backup for each change?  Sometimes it's easier to open multiple PRs in order tomato validation easier and more atomic.

**Comment by irshadk** [comment]
Closing this issue as a new format is coming soon for the dataset. see here  #1250 

One can still got and download the existing errors here https://www.aydan.info/
