### ISSUE TITLE
Russia 1 death, 5 recovered as of March 19th

### ISSUE THREAD

**Issue by soulseekah** [CSSEGISandData/COVID-19#1024]
https://www.gazeta.ru/social/2020/03/19/13011649.shtml

**Comment by chrisdane** [comment]
Death count of Russia is missing, despite increasing number of confirmed cases, just as everywhere else: https://github.com/chrisdane/COVID-19/tree/mybranch/r_plots#Russia

Russian people need to know to slow down virus spread!
