### ISSUE TITLE
One day lag / Accelerate update frequency

### ISSUE THREAD

**Issue by mploux** [CSSEGISandData/COVID-19#1025]
Hello,
It seems the csv files are being updated with a one day lag.
On this website we have more up to date data: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
Is it possible to accelerate the update frequency ?

Thanks a lot for open source data !

**Comment by avatorl** [comment]
There is no real analytical sense in 'live' updates. It's not weather. Country reports data daily (mostly) in different time.  We need full 24h data to be able to compare it with previous days. 

I would prefer if @CSSEGISandData will improve quality control rather than update frequency. March 12 bug still not fixed by today...

**Comment by yetzt** [comment]
(Also a note to data users: "Days" are somewhat meaningless on global data with different time zones. All we have is point-in-time data on a fixed interval)

**Comment by stefanbschneider** [comment]
I would still appreciate more frequent updates. I'm using these numbers for a web application and it's always slightly outdated.

**Comment by yetzt** [comment]
@stefanbschneider [Arcgis](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) is more up to date.

**Comment by stefanbschneider** [comment]
That's my point. They seem to have more up-to-date data for their dashboard.

But if I wanted to use that data in my application, I'd have to scrape it off their dashboard - not very nice. That's why I'm hoping for more frequent updates of this repo.

**Comment by tkothe** [comment]
did you notice there is a branch `web-data`? I assume that's where the data lives that's shown in the dashboard. And that branch is not publicly accessible. Obviously I am only speculating here...

**Comment by stefanbschneider** [comment]
Oh, I didn't notice. In fact the branch *is public* and it contains the up-to-date data! It's updated every hour or so! I guess this closes this issue :)

https://github.com/CSSEGISandData/COVID-19/tree/web-data

**Comment by tkothe** [comment]
Nice @stefanbschneider ! that's what I call a good cooperation on open source 😄 . I was only trying to find the same file as in `master` branch (https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) and that does not exist.

Greetings from Prague. Probably to my home country, judging by your name 😉

**Comment by mploux** [comment]
@stefanbschneider Nice ! Closing the issue, thanks !
