### ISSUE TITLE
Double: Aruba

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#1028]
Once as *Aruba*, once as *Aruba, Netherlands* [in Arcgis](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

Every day all the Territories that are in one Data Source without dependency and in the other with Dependency get doubled up. It's really time to implement measures against this.

**Comment by JiPiBi** [comment]
I did not find  this issue in time series ?....

**Comment by yetzt** [comment]
its probably not in the time series yet. it's in arcgis at the moment which to my understanding is the data source for this repository.

**Comment by yetzt** [comment]
Aruba has been deduplified in Arcgis, closing.
