### ISSUE TITLE
Missing recovered data

### ISSUE THREAD

**Issue by dataguy2020** [CSSEGISandData/COVID-19#1034]
Maryland has 3 confirmed recovery cases. This was reported within the past week. There  have been 85 total cases. Last evening there was 1 death which I am sure will be updated today. The number of active cases for the state of Maryland as of last night was 81.

**Comment by kraftaa** [comment]
yeah, the same problem for the US in total. In time series all cumulative `recovered` cases came to 0 for Mar 18th.

**Comment by mikebrowntsbod** [comment]
this continues to be an issue. it should probably be looked at as this will help those on the front lines as well
