### ISSUE TITLE
Mainland China + China

### ISSUE THREAD

**Issue by v0ku** [CSSEGISandData/COVID-19#1035]
Hi, 

I've just started to work with the dataset. What is the difference between Mainland China and China?

**Comment by JiPiBi** [comment]
No difference , for some countries they changed the name some days ago

**Comment by Bost** [comment]
@JiPiBi (unrelated to this issue) I've noticed you react to quite a number of issues regarding the numbers & quality of the dataset. Would you be interested in https://github.com/CSSEGISandData/COVID-19/issues/957#issuecomment-601147437 ? Read please also the rest of the discussion. This might be something for you.

**Comment by JiPiBi** [comment]
@Bost 
very honored by the proposal , but it you don't already know , please look at these sites that are much more strongly linked to the data that I am , but if I can help , why not :
-https://coronadatascraper.com/#sources
- https://github.com/opencovid19-fr/data
- https://github.com/pcm-dpc/COVID-19

**Comment by Bost** [comment]
@JiPiBi Thanks for the links. I had NO CLUE they even exist! For the reasons... well, have a look at the issue I created in these projects. (See above) Could you comment on it please?
