### ISSUE TITLE
CSV format issues

### ISSUE THREAD

**Issue by Fazmin** [CSSEGISandData/COVID-19#1042]
There are extra commas at the end of China and Iran data rows. Its not a major issue, when reading the data directly from the CSV this might cause errors.

**Comment by appastair** [comment]
Could you please point to an example where you're seeing this? :male_detective:  
I feel like they might be columns for a day or date with no case data yet.

**Comment by Fazmin** [comment]
Thank you for the fast response.
![screenshot 29](https://user-images.githubusercontent.com/1432117/77084988-11c0fe80-69d6-11ea-98be-449830f617dc.jpg)
See attached screenshot - Its visible when you open it raw.
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by Fazmin** [comment]
Here I have pointed with an arrow.
![screenshot 30](https://user-images.githubusercontent.com/1432117/77085295-7ed49400-69d6-11ea-9152-c03c37f9e13c.jpg)

Thank you.

**Comment by mkitti** [comment]
@Fazmin, note the the first column is `Province/State`. For those rows, the `Province/State` is empty. The second column is `Country/Region` and is correctly set to "China" or "Iran". The comma at the beginning of the row is correct.

**Comment by appastair** [comment]
:point_up: :grinning:  There's just no string-delimiter so it looks odd.
![image](https://user-images.githubusercontent.com/1825171/77086019-4031ee80-6a55-11ea-958e-9ece7e7bcd31.png)

**Comment by Fazmin** [comment]
Thank you for clarifying this. Once I posted the last message I realized and was too late.  Also my R application fails to parse the data due to the apostrophe "Cote d'Ivoire". Its all fixed. Thank you for your prompt response.

**Comment by mkitti** [comment]
I would maybe talk to the R folks. Python/Pandas seems to handle the file just fine.

**Comment by Fazmin** [comment]
Thank you mkitti. I figured it out.

**Comment by mkitti** [comment]
I recommend closing this issue if you have figured it out. Thanks.
