### ISSUE TITLE
South Korea - no data after March 9

### ISSUE THREAD

**Issue by RodBarnes** [CSSEGISandData/COVID-19#1059]
As said in the title: there is no data for South Korea since March 9th in the data files under csse_covid_19_data\csse_covid_19_daily_reports.

This, despite the fact, that the dashboard appears to show more current data.  At least, the counts on the dashboard are 8565 confirmed, 1540 recovered, and 91 dead.  But the data in 03-09-2020.csv has 7478 confirmed, 118 recovered, and 53 deaths.  So, not sure why the disconnect.

**Comment by JeroenKools** [comment]
The row for South Korea was renamed to Korea, South.
