### ISSUE TITLE
Invalid/Wrong information/numbers for Slovenia

### ISSUE THREAD

**Issue by dynamiccontent** [CSSEGISandData/COVID-19#1072]
Hello,
Can you please use the official Slovenian government website https://www.gov.si/en/topics/coronavirus-disease-covid-19/ for Slovenian numbers. Current numbers displayed on gisanddata.maps.arcgis.com are incorrect.

If you want more detailed information by Slovenian regions (only in Slovenian language unfortunately)
https://www.nijz.si/sl/dnevno-spremljanje-okuzb-s-sars-cov-2-covid-19

gisanddata.maps.arcgis.com numbers:
Slovenia
Confirmed: 286
Deaths: 1
Recovered: 0 
Active: 285

gov.si numbers (official Slovenian government website)
19 March 2020, 14:00:
9,860 people tested
319 confirmed coronavirus infections
1 death case

Thanks.

**Comment by JeroenKools** [comment]
Is it actually *wrong* or just a couple hours behind? This data gets updated daily.

**Comment by dynamiccontent** [comment]
It looks like it's updating. Just delay.
