### ISSUE TITLE
District of Columbia vs Washington, D.C.

### ISSUE THREAD

**Issue by christophGeoHealthCentre** [CSSEGISandData/COVID-19#1086]
District of Columbia 
and
Washington, D.C.
are two lines in today's dataset
data possibly counted twice

**Comment by Sleekery** [comment]
They switched from city/county level data for the US to state level data between 3/9/20 to 3/10/20. You have to aggregate the counties through 3/9/20 by state. Filter by commas, split by commas, take the US postal codes, and map to state names.
