### ISSUE TITLE
Allow for NOT and MULTIPLE user-selected regions

### ISSUE THREAD

**Issue by ciscorucinski** [CSSEGISandData/COVID-19#109]
Currently, we can only select a single region to see the data for it. It would be nice to see multiple regions such as just `Japan`, `Other`, and `South Korea` at once. Also, it would be nice to see all data points besides `Mainland of China` or `Hubei`.

Currently, these types of operations are not available but would be valuable

**Comment by CSSEGISandData** [comment]
Good suggestion. We tested multiple selection before, but it significantly slowed down the performance. More features are under development now. Thanks!
