### ISSUE TITLE
Github CSV to Google Sheets

### ISSUE THREAD

**Issue by CWrecker** [CSSEGISandData/COVID-19#11]
I have a pretty intensive set of calculations I have already setup on my old google sheets file. Is there a way to continue to update my google sheets with the new file released twice a day from this repository?

**Comment by ciscorucinski** [comment]
As a workaround for now, 
 1. Go to the RAW cvs files
 2. Copy the text 
 3. Create a new tab in your spreadsheet
 4. Paste the values into A1. 
 5. The floating `paste formatting` dialog will appear and you can select `split text to columns`

**Comment by CWrecker** [comment]
`=ImportData("https://raw.githubusercontent.com/CSSEGISandData/2019-nCoV/master/daily_case_updates/02-10-2020_1030.csv") `
Works fine in a google sheets. Actually quite well. However, It's not feasible to copy a new URL in each day. I'm looking for a way to update this automatically. I think a single file with the latest data (updated in addition to the new file added - with the same name) might be a good idea. It would make a lot of things easier for people trying to work with the data.

**Comment by ciscorucinski** [comment]
`=IMPORTHTML("https://github.com/CSSEGISandData/2019-nCoV/tree/master/daily_case_updates","table", 1)`

Gets the table from the Github repo. The value you want is the 2nd to the last one.  Retrieve it and use your `ImportData(...)` function.

**Comment by CWrecker** [comment]
Hmm, interesting method to this. I'm surprised there isn't an easier way, or at least that we know of.

**Comment by ciscorucinski** [comment]
The maintainers could provide a solution to make it easier, but I think this is the easiest solution that doesn't involve a git API

Throw this in a script
```
function reverse(collection) {
  if (typeof collection != "object") {
    return collection
  }
  return collection.reverse()
}
```

then use the following and the cell you want is always `B2` `=reverse(IMPORTHTML("https://github.com/CSSEGISandData/2019-nCoV/tree/master/daily_case_updates","table", 1))`

**Comment by CWrecker** [comment]
Yup, that’s exactly what I did

**Comment by Phoenixxl** [comment]
Quote:
"A maximum of 50 IMPORTDATA calls are supported on a single spreadsheet."
That's the not too distant future at this rate.

I think I'm just going to git clone with a script on update, hygiene check the data, stick it in a mysql database then use that for data. 

If there's a 4th bout of enlightenment it will be easier to catch and adapt.

**Comment by CWrecker** [comment]
This is indeed a concern. Got clone may be the way to go

**Comment by ciscorucinski** [comment]
The 50 max limit was for the old Google Sheets, the newer one has no such limitation.

https://stackoverflow.com/a/50868154/2333021

**Comment by Phoenixxl** [comment]
Well, if that's true, great. I'm still putting in the extra effort.
I got the info from the current sheets help though...
![image](https://user-images.githubusercontent.com/850031/74247614-9be6ba80-4ce6-11ea-9130-e08034d06263.png)

**Comment by ciscorucinski** [comment]
Interesting. Technically, my link was for ImportRange which alos had that limit before. Maybe it is just for ImportData then
