### ISSUE TITLE
Are the "Confirmed Cases" independent from the "Recovered" people?

### ISSUE THREAD

**Issue by Noah134** [CSSEGISandData/COVID-19#110]
Sorry if this is not the right place for this but I just wanted to ask if the number of recovered people are not independently determined, so that the confirmed number of currently infected people equals to:
I=C-R
when
I ∈ "Currently Infected", C ∈ "Confirmed Cases", R ∈ "Recovered"

I know that the data-sources that this project is using are different, and that it probably is not easy to find out how exactly the data is collected but I just wanted to know if it is sufficient for an estimate of the number of currently infected people.

**Comment by AaronWard** [comment]
Confirmed cases are not taking recoveries or deaths into account, it is just a count for every cases that someone has been confirmed to have the virus. 

`Currently infected = (confirmed cases - (recoveries + deaths))` would look something like [this](https://github.com/AaronWard/covid-19-analysis/blob/master/reports/images/currently_infected_bar.jpg)
