### ISSUE TITLE
Population Count

### ISSUE THREAD

**Issue by Ramesh-X** [CSSEGISandData/COVID-19#1106]
It is better to have population count of a country/region to get an idea on how badly the virus is spreading wrt the population.
I think that information is needed to be their in the system.

Thanks..

**Comment by calterras** [comment]
Sorry, I have just opened an issue in the same  line with no time to read yours.

**Comment by Ramesh-X** [comment]
@calterras I will just close this one and link in your issue. Your one is more informative..

**Comment by calterras** [comment]
thanks!

i pasted your text as a comment
