### ISSUE TITLE
Raw version of archived files not current

### ISSUE THREAD

**Issue by bjornkallerud** [CSSEGISandData/COVID-19#1114]
The Raw versions of the .csv files in csse_covid_19_data/csse_covid_19_time_series are not up to date with the observations that are in the main file. For example, the data in [the confirmed cases file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv) go through 19 March 2020, but the data in the [raw version](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv) go only through 7 March. Is it possible to keep the raw files as current as the main page so it is easy to pull?

Thank you for this resource!

**Comment by jianmingyong** [comment]
It seems like you need to clear your cache? It seems latest to me when I click on it.

**Comment by JiPiBi** [comment]
In the raw version, list of the columns : 
`Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,2/1/20,2/2/20,2/3/20,2/4/20,2/5/20,2/6/20,2/7/20,2/8/20,2/9/20,2/10/20,2/11/20,2/12/20,2/13/20,2/14/20,2/15/20,2/16/20,2/17/20,2/18/20,2/19/20,2/20/20,2/21/20,2/22/20,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20`

So where is your issue ?

**Comment by bjornkallerud** [comment]
I apologize - clearing cache worked.
