### ISSUE TITLE
Error with read.table in R

### ISSUE THREAD

**Issue by JJ** [CSSEGISandData/COVID-19#1129]
![Captura de pantalla de 2020-03-20 20-35-18](https://user-images.githubusercontent.com/500/77205273-cf421380-6af4-11ea-860c-f9f558d9f450.png)
The ' in Cote d'Ivoire causes errors when reading it with data.table in R. Here's a small trick that fixes that:

```R
raw.world.confirmed <- getURL("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
raw.world.confirmed <- str_replace_all(raw.world.confirmed, '\'', '')
world.confirmed <- read.table(text = raw.world.confirmed, sep=',',head=T)
```

**Comment by dhmacq** [comment]
What kind of errors?

I have no trouble with
   read.csv('time_series_19-covid-Confirmed.csv' , stringsAsFactors=FALSE)
(after having copied the file to my local HD using git pull)

**Comment by JJ** [comment]
> What kind of errors?
> 
> I have no trouble with
> read.csv('time_series_19-covid-Confirmed.csv' , stringsAsFactors=FALSE)
> (after having copied the file to my local HD using git pull)

Sorry, forgot to add the capture. The ' messed with the rest. I was using read.table, not read.csv. Maybe I should have used that; anyway, that fixes it.

**Comment by bevanward** [comment]
@JJ can be closed now? Lots of old issues makes it time consuming to get through the list of data issues - thanks
