### ISSUE TITLE
Please review Mainland China Confirmed Case Number in Time Series File

### ISSUE THREAD

**Issue by tranquyphi** [CSSEGISandData/COVID-19#113]
Many Provinces have the same number of confirmed cases on 02-22 and 02-23?
Date 02-22 the total of confirmed case of Mainland China (line 2 to line 32) is 76922.
Date 02-23 the total of confirmed case of Mainland China (line 2 to line 32) is 76938.
So new cases is 76938-76922=16 ???

**Comment by Shane073** [comment]
I asked the same thing a couple of days ago in relation to the deaths recorded. https://github.com/CSSEGISandData/COVID-19/issues/100#issue-569248294

**Comment by dawenx** [comment]
I'm pretty sure this is the effect of their "cutoff time" for a day, sometime Hubei (the epi center) has updated data around 0am UTC (8AM GMT +8) and sometime it has not. See detailed discussion in #60

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We are currently updating this repository daily around 12 AM UTC (7 PM EST). There may be discrepancies from the data in this repository and the data you see on the dashboard (updated real-time) due to this difference in update time.
