### ISSUE TITLE
Clicking Iran shows data for Australia

### ISSUE THREAD

**Issue by baryluk** [CSSEGISandData/COVID-19#1138]
On Desktop version, clicking on `Iran` in the list on the left, centres the map on Australia, and shows the right side panel (cases / deaths) for Australia, not Iran.

Desktop version, Firefox, 60.8.0esr, Linux.

**Comment by baryluk** [comment]
It also happens for some other countries. Guadeloupe -> Belarus; Martinique -> Jordan, Belarus -> Guyana; Serbia -> Singapore.

Sometimes fully refreshing the page, fixes some of them.

**Comment by QualityMeasurement** [comment]
@5:08 Mountain Daylight Time, I am not seeing this bug for Iran, nor the other errors referenced above. In terms of this issue, I do not see any errors.

**Comment by baryluk** [comment]
I can't reproduce the issue with the Iran anymore. But it still occurs for other countries. It also started happening for United Kingdom, it shows data for Serbia.

**Comment by baryluk** [comment]
I.e. Clicking on United Kingdom in the left pane, retrieves the data using this URL when looking at the Network console in Firefox:

`https://services9.arcgis.com/N9p5hsImWXAccRNI/arcgis/rest/services/Z7biAeD8PAkqgmWhxG2A/FeatureServer/1/query?f=json&where=(Confirmed > 0) AND (Country_Region='Serbia')&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Confirmed desc,Country_Region asc,Province_State asc&outSR=102100&resultOffset=0&resultRecordCount=250&cacheHint=true`

That is clearly wrong.

**Comment by QualityMeasurement** [comment]
2020-03-22 @ 1252 Mountain Daylight Time: The error observed by @baryluk is not reproducible. I am showing appropriate values for the UK (cases = 5,071 | deaths = 234 (233 in UK, UK and 1 in Cayman Islands, UK) | Recovered = 67 (65 in UK, UK and 2 in Gibraltar, UK)

![Isuue1138__DashboardSnapshot_20200322_1252_MountainDaylightTime](https://user-images.githubusercontent.com/13632843/77258034-93ff2c00-6c3d-11ea-976e-73f17676624a.PNG)

**Comment by CSSEGISandData** [comment]
This issue may happen when the system is updating. Please try to clear the cache and refresh the page. Thanks!

**Comment by baryluk** [comment]
Still not fixed. This is easy to reproduce by opening the website, and waiting few hours, then clicking on some other country:

![qatar-portugal](https://user-images.githubusercontent.com/110322/80746559-9a70a580-8b11-11ea-9f1c-4a473f815d43.png)
![south-korea-kenya](https://user-images.githubusercontent.com/110322/80746565-9cd2ff80-8b11-11ea-8e90-c1ea4f18574d.png)
![ukraine-turkey](https://user-images.githubusercontent.com/110322/80746566-9d6b9600-8b11-11ea-974e-d8cfd11996b4.png)

I don't know what exactly, but there is some mapping in the code that is resolved dynamically to some id, or row id, obj id, and it is not stable. The bug is in the UI itself somewhere, because the network requests do put stable names in the HTTP query, it just is filled wrong.
