### ISSUE TITLE
Add France region

### ISSUE THREAD

**Issue by j3r3m067** [CSSEGISandData/COVID-19#1143]
You can add geographic zone as like : https://mapthenews.maps.arcgis.com/apps/opsdashboard/index.html#/5e09dff7cb434fb194e22261689e2887
With source data: 

https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde (click on « Afficher » to show the table )

**Comment by jtene001** [comment]
I don't read French, so I'm not sure, but I don't see full time series data for confirmed cases, deaths and recoveries. They would need this.

**Comment by j3r3m067** [comment]
I don’t find a data with details, so you can close this issue 
(Otherwise I was found map for Germany by lander: https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/)

**Comment by j3r3m067** [comment]
Hello
The french government has been created a platform with all data you need to know to build a map with a certificate data.
You can use it to build area zone

https://www.gouvernement.fr/info-coronavirus/carte-et-donnees
