### ISSUE TITLE
Incorrect data Colombia 03/20/2020

### ISSUE THREAD

**Issue by pedrurrego** [CSSEGISandData/COVID-19#1147]
The Colombian government confirmed 145 cases at 9:00 (COT) on 03/20/2020

[https://d2jsqrio60m94k.cloudfront.net/CORONAVIRUS%20(COVID-19)_files/200320_post_coronavirus_9am_baja.jpg](url)

![image](https://user-images.githubusercontent.com/45640285/77217321-89368100-6aef-11ea-8b59-e714470bf903.png)

**Comment by CSSEGISandData** [comment]
Thanks @pedrurrego
