### ISSUE TITLE
Can we limit the number of times we change the folder structure?

### ISSUE THREAD

**Issue by ryanwoconnor** [CSSEGISandData/COVID-19#115]
I am trying to depend on this data, but because of the fact that the folder structure has changed, the automated tools I have setup to analyze the data have broken. I had a similar issue when this was in a Google Sheet and the formats of the data (headings, value format, and sheet names) were constantly changing.  

1. Can we please notify people when changes are coming that may break their processes? 
2. Can we also limit any major structural changes to the data so that people can depend on it?

This is a public repository and people are trying to rely on it, but those types of changes make it difficult/impossible. 

Thank you,
Ryan

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We will be continuing on with the current data structure in this repository, while keeping changes minimal. We will notify users in the read me of this repo for any major data structure changes before they occur.
