### ISSUE TITLE
France incorrect data

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#1161]
For France , the data for confirmed  are wrong , because the official value 12612 is an aggregation of all the territories 

Official values :
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde
Date | Province | State | Cases
-- | -- | -- | --
20/03/2020 | France | France | 12612
20/03/2020 | Auvergne-Rhône-Alpes | France | 1101
20/03/2020 | Bourgogne-Franche-Comté | France | 770
20/03/2020 | Bretagne | France | 346
20/03/2020 | Centre-Val de Loire | France | 219
20/03/2020 | Corse | France | 168
20/03/2020 | Grand Est | France | 3006
20/03/2020 | Hauts-de-France | France | 759
20/03/2020 | Ile-de-France | France | 3818
20/03/2020 | Normandie | France | 287
20/03/2020 | Nouvelle-Aquitaine | France | 432
20/03/2020 | Occitanie | France | 537
20/03/2020 | Pays de la Loire | France | 190
20/03/2020 | Provence-Alpes-Côte d’Azur | France | 826
20/03/2020 | Guadeloupe | France | 51
20/03/2020 | Saint-Barthélémy | France | 3
20/03/2020 | Saint-Martin | France | 4
20/03/2020 | Guyane | France | 15
20/03/2020 | Martinique | France | 32
20/03/2020 | Mayotte | France | 7
20/03/2020 | La Réunion | France | 38

so the territories = provinces beginning at Guadeloupe are counted twice in the dataset : they are added to 12612 : so 12612 must be corrected to 12459 in the confirmed

And FYI  the total recoveries is officialy 1587  instead of 12 , but dont know if it is interesting for someone here .....

Current dataset timeseries date  : 20th of March  for confirmed:
Province/State | Country/Region | 3/20/20
-- | -- | --
France | France | 12612
St Martin | France | 4
Saint Barthelemy | France | 3
French Polynesia | France | 11
French Guiana | France | 15
Mayotte | France | 6
Guadeloupe | France | 45
Reunion | France | 28
New Caledonia | France | 2

**Comment by jcavfen9** [comment]
> And FYI the total recoveries is officialy 1587 instead of 12 , but dont know if it is interesting for someone here ....

Hi, I'm interested :-). Where did you get the number of "Recovered" in France. May be I'm wrong but I don't see it on the "[Santé Publique France](https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde)" website. Other question if I may. Is there a French open data source with more details : for instance by "departments", by class of age, by severity?
Best regards.

**Comment by carlodef** [comment]
@JiPiBi I'm trying to correct the wrong numbers for France in pull request #1237

**Comment by JiPiBi** [comment]
@carlodef   
Please can you explain what you did, you were modifying the values in the time series and you proposed your modifications to the maintainers of the site 
Does that mean that 
- they accept your modifications by this process
- you have to make modifications everyday if they go on with the same type of issue ?

**Comment by carlodef** [comment]
@JiPiBi I fixed manually the wrong values in files `csse_covid_19_daily_reports/*-*-2020.csv`, and in files `csse_covid_19_time_series/time_series_19-covid-{Confirmed,Deaths}.csv`, and submitted these corrections as a pull request (#1237). It doesn't mean that the maintainers of this repository accept the modifications.

**Comment by JiPiBi** [comment]
Great 
Have you noticed that any of your modifications were fixed in the master ?

**Comment by JiPiBi** [comment]
One remark  : I read the compared data (red vs green and green being the proposed value ? ) and I have a doubt about your values : the following is from sante publique for the 21th


Date | Province | State | Cases
-- | -- | -- | --
21/03/2020 | Auvergne-Rhône-Alpes | France | 1266
21/03/2020 | Bourgogne-Franche-Comté | France | 903
21/03/2020 | Bretagne | France | 359
21/03/2020 | Centre-Val de Loire | France | 254
21/03/2020 | Corse | France | 173
21/03/2020 | Grand Est | France | 3089
21/03/2020 | Hauts-de-France | France | 791
21/03/2020 | Ile-de-France | France | 4695
21/03/2020 | Normandie | France | 345
21/03/2020 | Nouvelle-Aquitaine | France | 521
21/03/2020 | Occitanie | France | 611
21/03/2020 | Pays de la Loire | France | 234
21/03/2020 | Provence-Alpes-Côte d’Azur | France | 1041
21/03/2020 | Guadeloupe | France | 56
21/03/2020 | Saint-Barthélémy | France | 3
21/03/2020 | Saint-Martin | France | 5
21/03/2020 | Guyane | France | 18
21/03/2020 | Martinique | France | 37
21/03/2020 | Mayotte | France | 11
21/03/2020 | La Réunion | France | 47
21/03/2020 | France | France | 14459

Be aware that the last line France is the total of all above 
But in CSSE the line France,France is only mainland France 
So France, France should be 14282 in CSSE data (but the french site has the same values than these above ) 


For the 22 th


22/03/2020 | Auvergne-Rhône-Alpes | France | 1431
-- | -- | -- | --
22/03/2020 | Bourgogne-Franche-Comté | France | 1178
22/03/2020 | Bretagne | France | 397
22/03/2020 | Centre-Val de Loire | France | 291
22/03/2020 | Corse | France | 183
22/03/2020 | Grand Est | France | 3395
22/03/2020 | Hauts-de-France | France | 936
22/03/2020 | Ile-de-France | France | 5283
22/03/2020 | Normandie | France | 462
22/03/2020 | Nouvelle-Aquitaine | France | 612
22/03/2020 | Occitanie | France | 671
22/03/2020 | Pays de la Loire | France | 270
22/03/2020 | Provence-Alpes-Côte d’Azur | France | 1372
22/03/2020 | Guadeloupe | France | 58
22/03/2020 | Saint-Barthélémy | France | 3
22/03/2020 | Saint-Martin | France | 6
22/03/2020 | Guyane | France | 19
22/03/2020 | Martinique | France | 44
22/03/2020 | Mayotte | France | 14
22/03/2020 | La Réunion | France | 64
22/03/2020 | France | France | 16018

**Comment by JiPiBi** [comment]
Martinique is now include . Improvment ! 
Old values will never be cured , but now there are not crucial to understand the epidemic , the more important are hospitalized and ICU
