### ISSUE TITLE
Germany: increasingly incorrect data

### ISSUE THREAD

**Issue by TG9541** [CSSEGISandData/COVID-19#1165]
# Issue
Since 13/Mar/2020 case and death count data from CSSE differ more and more from the official data [daily situation reports published by the RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html), the archive is [here](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Archiv.html).

# Supporting data:
The following diagram shows the RKI data compared to the [CSSE time series data](https://github.com/CSSEGISandData/COVID-19/blob/02be34e5ec0409835f79f61a547b2b42f2c6dfd7/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv) published by @Ryan_Lau:

![image](https://user-images.githubusercontent.com/5466977/77224026-04387f80-6b62-11ea-9ecf-ba4b53ee3881.png)

Here is the data in tabular form (dCases is the increment, DC-Error is the difference between increments reported by RKI and those in the CSSE CSV file): 

Date | Cases RKI | dCases RKI | Cases Lau | dCases Lau | DC-Error
-- | -- | -- | -- | -- | --
03/04/20 | 262 | 0 | 262 | 0 | 0
03/05/20 | 400 | 138 | 482 | 220 | 82
03/06/20 | 639 | 239 | 670 | 188 | -51
03/07/20 | 795 | 156 | 799 | 129 | -27
03/08/20 | 902 | 107 | 1040 | 241 | 134
03/09/20 | 1139 | 237 | 1176 | 136 | -101
03/10/20 | 1296 | 157 | 1457 | 281 | 124
03/11/20 | 1567 | 271 | 1908 | 451 | 180
03/12/20 | 2369 | 802 | 2078 | 170 | -632
03/13/20 | 3062 | 693 | 3675 | 1597 | 904
03/14/20 | 3795 | 733 | 4585 | 910 | 177
03/15/20 | 4838 | 1043 | 5795 | 1210 | 167
03/16/20 | 6012 | 1174 | 7272 | 1477 | 303
03/17/20 | 7156 | 1144 | 9257 | 1985 | 841
03/18/20 | 8198 | 1042 | 12327 | 3070 | 2028
03/19/20 | 10999 | 2801 | 15320 | 2993 | 192
03/20/20 | 13957 | 2958 | 19848 | 4528 | 1570

The difference in the number of reported deaths was low until 15/Mar/2020 from when on it increased:

![image](https://user-images.githubusercontent.com/5466977/77224373-4adba900-6b65-11ea-9e99-8fce6da1c59f.png)
 
Here is again the data in tabular form (dCases is the increment, DC-Error is the difference between increments reported by RKI and those in the CSSE CSV file):

Date | Deaths RKI | dDeaths RKI | Deaths Lau | dDeaths Lau | DD-Error
-- | -- | -- | -- | -- | --
03/04/20 | 0 | 0 | 0 | 0 | 0
03/05/20 | 0 | 0 | 0 | 0 | 0
03/06/20 | 0 | 0 | 0 | 0 | 0
03/07/20 | 0 | 0 | 0 | 0 | 0
03/08/20 | 0 | 0 | 0 | 0 | 0
03/09/20 | 2 | 2 | 2 | 2 | 0
03/10/20 | 2 | 0 | 2 | 0 | 0
03/11/20 | 3 | 1 | 3 | 1 | 0
03/12/20 | 5 | 2 | 3 | 0 | -2
03/13/20 | 5 | 0 | 7 | 4 | 4
03/14/20 | 8 | 3 | 9 | 2 | -1
03/15/20 | 12 | 4 | 11 | 2 | -2
03/16/20 | 13 | 1 | 17 | 6 | 5
03/17/20 | 12 | -1 | 24 | 7 | 8
03/18/20 | 12 | 0 | 28 | 4 | 4
03/19/20 | 20 | 8 | 44 | 16 | 8
03/20/20 | 31 | 11 | 67 | 23 | 12

# Method:
Official data was transferred manually from the official RKI pages mentioned before, and manually copied into a spreadsheet (LibreOffice Version: 5.1.6.2 Build ID: 1:5.1.6~rc2-0ubuntu1~xenial10). Time series data from 02be34e was likewise copied  into the same spreadsheet and turned into the attached tables and diagrams.

# Discussion
News media often refer to the CSSE data without questioning its accuracy. This might create credibility problems for the official source. If your source isn't the RKI and you have reason to believe that your source is more accurate, then please state the source and the rationale.

**Comment by JiPiBi** [comment]
perhaps could read this thread #1008

**Comment by coezbek** [comment]
I am getting also confused a lot by looking at various data sources. For instance, looking at NRW.

Data from today (21.03. 13:44) from the state web page (https://www.mags.nrw/coronavirus-fallzahlen-nrw): 6.740
Data from [archive.org from 17.03. 9:45](https://web.archive.org/web/20200318063327/https://www.mags.nrw/coronavirus-fallzahlen-nrw): 3.060
Data from [archive.org from 18.03. 10:10](https://web.archive.org/web/20200318100749/https://www.mags.nrw/coronavirus-fallzahlen-nrw): 3.838
Data from RKI today (21.03. 13:47, https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html): 3.542 

This means that the RKI data published on the 21st of March is actually data from 18th of March midnight (approx) or there is some other really strange effect.

**Comment by TG9541** [comment]
@coezbek as the death count was reduced from 13 to 12 I think that RKI tries to consolidate data but I get the point that discussing observing exponential growth when the time of different observations is inconsistent is a bit pointless.

**Comment by TG9541** [comment]
[Robert Koch-Institut: COVID-19-Dashboard] explains how data is collected and consolidated. The method looks sound but validation an publishing imposes a delay. Other methods may be faster, but then these sources should explain how initial errors are handled corrected.

**Comment by yetzt** [comment]
It's not wrong data as such, the difference originates in delays. Since there is no uniform *time of report* transmitted, it makes efforts to compare data quality futile. 

On the whole, local health authorities often report changes way prior to RKI, this is why media relies on gathering data from state and local autorities (*Landesgesundheuitsbehörden* and such) instead of waiting on RKI. 

The data is not *incorrect* but more up to date than the data source you are relying on.

**Comment by TG9541** [comment]
I'm closing this because there certainly is no meaningful way to improve presenting data. The problem is that observation credibility is pitted against temporal resolution.
