### ISSUE TITLE
Feature Request: Use a colormap instead of big red dots

### ISSUE THREAD

**Issue by sgpearse** [CSSEGISandData/COVID-19#117]
Using red dots of increasing size to represent confirmed cases is problematic.  The red dot representing cases reported in Wuhan occludes most of China.  Using a single dot-size with a color scale would fix this problem by de-cluttering the map.

I recommend a discrete sequential colormap like the one shown below.  This is derived from the "thermal" colormap Matplotlib's cmocean module.  Note that "thermal" is continuous by default, not discreet.  The map below has been discretized into seven bins.

I can provide a lookup table to this colormap, or another suitable sequential map if needed.

https://matplotlib.org/cmocean/

![thermal](https://user-images.githubusercontent.com/9522770/75177258-0b9b7300-56f3-11ea-8e3a-b51260446cac.png)

**Comment by ciscorucinski** [comment]
I agree that the dots could be revamped.
1. When zoomed out far enough, then the Wuhan dot overwhelms the map. That could be reduced in size.
2. A more linear scale for the dots would more visually represent the spread of Covid-19. Right now, the South Korean dot is just 2 - 4 times smaller even though the number of cases are magnitudes smaller.

These two changes should help clear up the map better. Color could be used for another data point; however, it seems like a more simple UI is preferred.

**Comment by sgpearse** [comment]
@ciscorucinski I agree that linearizing the scale would help,  but this is still a misleading visualization.  The problem is that the current legend is visualizing **point-data** with a geospatial perimeter.  The perimeter we're seeing has no spatial meaning.

The image below shows the blast radii of an atomic bomb.  This an appropriate use of visualizing scalar data with spatial information.

![image](https://user-images.githubusercontent.com/9522770/75182953-b4030480-56fe-11ea-96b2-da7a8e9389a1.png)

**Comment by redman684** [comment]
I agree the dots are misleading. Depending on the zoom, the Italian dot varies from the size of a single person to covering the whole of Europe. The size of a tiny village would be the most realistic for the number currently infected. Even when you would consider the threat level, a dot the size of a city would be realistic. The dot size currently is almost always much, much too big.

On the other hand, when dots start overlapping, they hide each other and the China infection can look about 4 times the size of the Italian infection, while there are 100 times as much cases.
It dosn't help that the dots layer as a whole is transparent, as it suggest there is no overlap: Where 20 dots overlap, the resulting color and opacity is identical to where there is no overlap

I don't think color coding would be the solution and it would still quickly color entire countries red.

**Comment by CSSEGISandData** [comment]
Thank you for the ideas. We will keep them in mind when building out future capabilities.

**Comment by sgpearse** [comment]
@CSSEGISandData, Thank you for providing this service and for fixing this.  Marking as closed.
