### ISSUE TITLE
Interactive map - Italy has lost a confirmed case?

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#120]
What's wrong with the one on the card? I just checked if there was a bigger increase compared to when I last checked 4 hours ago. 

What I noticed right away was Italy. About 4 hours ago there were 230 confirmed and now all of a sudden there should be 229 confirmed.

Have the Italian authorities officially withdrawn a number of people or has there been a mistake in the system?

On the screenshots you can see the time and the difference.

![Bildschirmfoto vom 2020-02-25 01-18-33](https://user-images.githubusercontent.com/49625256/75203181-c36d6680-576d-11ea-8197-172897017fa2.png)
![qw](https://user-images.githubusercontent.com/49625256/75203186-c49e9380-576d-11ea-9ba0-38491c722676.png)

**Comment by Trainax** [comment]
There was a mistake.

The patient was in the hospital of Manerbio, but he was from Pontevico. So he was accidentally counted twice (in Manerbio and in Pontevico). Now the mistake has been cleared

**Comment by iceweasel1** [comment]
@Trainax All right. Thanks for the feedback. I hereby close the issue.
