### ISSUE TITLE
Data for USA does not load 

### ISSUE THREAD

**Issue by brendanofallon** [CSSEGISandData/COVID-19#1200]
Most data for the US is not displaying, and most of the charts say "No Data" when the US is selected. Other countries appear normal, see screenshot below

<img width="1609" alt="Screen Shot 2020-03-21 at 4 52 39 PM" src="https://user-images.githubusercontent.com/425575/77238343-c1dc6600-6b94-11ea-9c63-1b1c239829c1.png">

**Comment by dhmacq** [comment]
Try refreshing the web page. Worked for me. The "Last Updated" timestamp in the lower left corner will change to a newer date-time.

**Comment by brendanofallon** [comment]
It works as of today (3/22)
