### ISSUE TITLE
ok i admit i am a rookie....so ignore my ignorance.   i am trying to load this data to powerbi.  Everything i have tried does not work.  anyone willing to give me some simple steps on data load.  i think it is straight forward but just don't know the correct data query.  is it json or api or what.  what do enter.  once i get the data i good to go.  thanks for the help

### ISSUE THREAD

**Issue by MNagle10** [CSSEGISandData/COVID-19#1201]

**Comment by aureq** [comment]
Hi,

How about you write your problem and some steps you've performed in the body of this issue rather than the subject please? Maybe with enough information someone might be able to help you.

**Comment by ivanMSC** [comment]
Use the raw address of the dataset you want to load from web, for example https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

Then you do all that power query magic, like unpivoting this disastrous database.

**Comment by aureq** [comment]
You probably also want to edit the subject... ;-) Like "Raw data source and PowerBI" or something similar.

**Comment by PhilbyD** [comment]
You can view a full youtube on exactly how to setup the import settings for this dataset into Power Bi below.

https://www.youtube.com/watch?v=4vfAz7XDuH0

**Comment by DMiradakis** [comment]
As suggested above by @ivanMSC , simply use three Web Connectors and feed each of them the raw data URL for the CSV files. That's what I've done, and I am working on my own report right now.

**Comment by jcavfen9** [comment]
If you want to download automatically the data sets on your computer, you can use "[GitHup Desktop](https://desktop.github.com/)" that is very easy to use.

**Comment by MNagle10** [comment]
All - thank you for your quick responses...You guys are the fastest I have seen for any community help board!!!!!!!

**Comment by skr47ch** [comment]
Here's what I've done.
1. Import the three file from web import.
2. Promote headers.
3. Unpivot other columns (done by selecting everything other than date)
4. Change type

Create two reference tables and change source to other two file, so you don't need to repeat the steps.

Now, to combine, use Summarize (I am not interested in state level, so I've not selected it)-
JHU CSSE Combined = 
DISTINCT(
UNION( 
    SUMMARIZE( 'JHU CSSE Confirmed', 'JHU CSSE Confirmed'[Country], 'JHU CSSE Confirmed'[Date] ),
    SUMMARIZE( 'JHU CSSE Deaths', 'JHU CSSE Deaths'[Country], 'JHU CSSE Deaths'[Date] ), 
    SUMMARIZE( 'JHU CSSE Recovered', 'JHU CSSE Recovered'[Country], 'JHU CSSE Recovered'[Date] )
)
)


Further, I've created a new column to fix country names and such to match with my custom shape map.

Country / Region = 
SWITCH( 
    'JHU CSSE Combined'[Country],
    "Cruise Ship", "International Conveyance",
    "Others", "International Conveyance",
    "Iran (Islamic Republic of)", "Iran",
    "Republic of Korea", "South Korea",
    "Korea, South", "South Korea",
    "Hong Kong SAR", "Hong Kong",
    "Taipei and environs", "Taiwan",
    "Taiwan*", "Taiwan",
    "occupied Palestinian territory", "Palestine",
    "Russian Federation", "Russia",
    "Viet Nam", "Vietnam",
    "Macao SAR", "Macau",
    "Repulic of Moldova", "Moldova",
    "Congo (Kinshasa)", "Democratic Republic of the Congo",
    "Czechia", "Czech Republic",
    "Saint Vincent and the Grenadines", "St. Vincent and the Grenadines",
    "Holy See", "Vatican City",
    "Cote d'Ivoire", "Ivory Coast",
    "Tanzania", "United Republic of Tanzania",
    "Congo (Brazzaville)", "Republic of the Congo",
    "The Gambia", "Gambia",
    "Gambia, The", "Gambia",
    "Bahamas", "The Bahamas",
    "Bahamas, The", "The Bahamas",
    "Cabo Verde", "Cape Verde",
    'JHU CSSE Combined'[Country] 
)

**Comment by ripstaur** [comment]
OK, this used to work for me, but something has changed. Now when I enter the url, everything seems to work OK, but the table that loads has what looks like metadata in column 1, and nothing in the rest of the columns. Anyone know why this would be happening?
