### ISSUE TITLE
Total Confirmed counter

### ISSUE THREAD

**Issue by sabpic** [CSSEGISandData/COVID-19#1245]
Hello,
I'm facing an issue regarding "Total confirmed cases".
If I compare the dashboard's count
![image](https://user-images.githubusercontent.com/17746600/77253907-f49e6100-6c5d-11ea-82fd-e5945de2d35c.png)
at 
![image](https://user-images.githubusercontent.com/17746600/77253917-07b13100-6c5e-11ea-85d0-9573a42d637f.png)
with content of time series file time_series_19-covid-Confirmed.csv, the counter seems to be wrong.
By making a sum at column 3/21/20, the correct total seem to be 304524.

Could you please tell me if there is something wrong in my data analysis ?

Thanks in advance for your support.
Regards
Sabatino

**Comment by dhmacq** [comment]
I think you should assume the dashboard is updated more frequently than the files. (Whether that's enough to account for the size of the difference you are seeing, I don't know.)

**Comment by sabpic** [comment]
Hi @dhmacq ,

thanks for your reply.
I have supposed (according with dashboard's notes)  that opsdashboard was built on the same dataset.
Let's wait a confirmation about that. 

Regards
S

**Comment by dhmacq** [comment]
My own interpretation is that the dashboard _is_ built on the same dataset as the files, but that the dataset (and therefore the dashboard) changes multiple times per day as new data is received, whereas the github files are published (updated) only once per day.

(Of course, I have no information about the means by which this is accomplished, nor have I seen explicit documentation, but no other interpretation makes sense to me. I have an example in my comment on #1154.)
