### ISSUE TITLE
New Global Files with Inconsistent Column Schemas

### ISSUE THREAD

**Issue by ei-JoanneT** [CSSEGISandData/COVID-19#1264]
The downloaded data failed to pass a csv test in Alteryx due to different column schemas. Error message reads as: "Too many fields in record # 32"

Is anyone experiencing similar issues?

**Comment by souzapd** [comment]
Yes. There are duplicate fields for an assortment of British and French overseas territories. I'm cleaning these up with a script, but I'd hope the schema is consistent for the next update.

**Comment by ei-JoanneT** [comment]
> Yes. There are duplicate fields for an assortment of British and French overseas territories. I'm cleaning these up with a script, but I'd hope the schema is consistent for the next update.

Thanks for confirming. Don't have a script readily available now so I will probably use the old version of time series and hoping for the update too.

**Comment by bevanward** [comment]
@ei-JoanneT I think we’ll have an iso country code in the new format once it is complete too. This must just be an initial test.

**Comment by ei-JoanneT** [comment]
> @ei-JoanneT I think we’ll have an iso country code in the new format once it is complete too. This must just be an initial test.

Got it! Thanks! Was trying to update my process asap so my report doesn't get caught when the structure is actually changed. Maybe a little too soon to do that lol

**Comment by bevanward** [comment]
I’m keen too!! The iso country code hopefully will constrain the duplication and result in cleaner data however concerned how they are going to deal with the province level reporting. Fingers crossed

**Comment by ei-JoanneT** [comment]
> I’m keen too!! The iso country code hopefully will constrain the duplication and result in cleaner data however concerned how they are going to deal with the province level reporting. Fingers crossed

Retweet, we will see I guess :)
