### ISSUE TITLE
last update time

### ISSUE THREAD

**Issue by billyburgoa** [CSSEGISandData/COVID-19#1268]
I searched in the issues thread if any body asked to have access to last udpated time of time series. Is it possible to provide that information? or Is this available somewhere?

**Comment by bevanward** [comment]
If I understand you correctly - the date/time utc of each update is available back in the daily files. For example look at:
[https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv](url)
So to compile you may as well process through the daily files and build it up. The issue will likely be the changed location names, etc!!
