### ISSUE TITLE
Funny? Not funny ?

### ISSUE THREAD

**Issue by jschvartz** [CSSEGISandData/COVID-19#1286]
Since 03-18 a line appears in daily reports:
US 	US 	2020-03-22T20:43:03 	1 	0 	178 	37.0902 	-95.7129
The location points somewhere in Kansas, a russian labeled place: Китайский ресторан
Which translates to:  "Chinese restaurant"
I'll let you juge if it is a funny joke or not ....
Thanks for your work, in any case !!
Cheers.

**Comment by chrisdane** [comment]
Russia also does not report their deaths: https://github.com/chrisdane/COVID-19/tree/mybranch/r_plots#Russia

Russian people need to know! Atm, every 2-3 days the number of deaths doubles in most european countries. Its very likely the same in Russia.
