### ISSUE TITLE
questionable choices

### ISSUE THREAD

**Issue by DataEnthusiast84** [CSSEGISandData/COVID-19#130]
I hope I'm not boring but I go back to rephrase a previous request:

Is it possible to have the summary of cases in a single file? It seems absurd to me that the data is published with individual reports. Where did the concept of data accessibility go?

**Comment by Cammeritz** [comment]
If it bothers you so much then why don't you write a script that allows users to combine all data into a single file

**Comment by CSSEGISandData** [comment]
Thanks for your suggestion. We will consider it in our future update. Thanks!
