### ISSUE TITLE
Extract, curve-fit a logistic function and transpose JHU-CSSE's Covid-19 cases data per country/region

### ISSUE THREAD

**Issue by cyclaero** [CSSEGISandData/COVID-19#1302]
Hello, I programmed a command line tool in C destined to FreeBSD, macOS or Linux for extracting, curve-fitting and transposing the JHU-CSSE's Covid-19 cases data per country/region.

I uploaded this project to my GitHub repository and it comes with a BSD-License, see https://github.com/cyclaero/xcssecovid/
 I wrote up a BLog post showing use cases of this tool and the curve-fitting results for Germany, Italy and Brazil.
German BLog-post: https://obsigna.com/articles/1584931539.html
English Translation: https://www.translatetheweb.com/?from=de&to=en&a=https://obsigna.com/articles/1584931539.html

**Comment by klartext** [comment]
Hey, C-programming, nice. :-)
C-programming is a rare case these days.

**Comment by cyclaero** [comment]
This is not really an issue, therefore there is nor reason to keep it open.
