### ISSUE TITLE
Schema accident or feature?

### ISSUE THREAD

**Issue by dtorre** [CSSEGISandData/COVID-19#1328]
Is this new schema intentional or a bug? Fields like "Admin2" and "FIPS" seems like a mistake. (?)

**Comment by dtorre** [comment]
FWIW - the first commit works...

curl -o 2020-03-23.csv https://raw.githubusercontent.com/CSSEGISandData/COVID-19/d2264eafadcde070ca0d0f4d77891d1947c69caa/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv

**Comment by yetzt** [comment]
the've announced to change it in the time series #1250 but its also in the daily reports now. #1326

**Comment by piccolbo** [comment]
Search FIPS code. It's a federal govt standard. Not sure what Admin2 is.

**Comment by yetzt** [comment]
Admin2 is probably the secondary administrative division, eg counties and independent cities.

**Comment by rmunjuluri** [comment]
It appears that the FIPS code maps to the Admin2, which is the County Name...
from....
https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697

**Comment by dtorre** [comment]
Thanks everyone for helping better understand these new fields.

Looks like I have work to do to on my end to accommodating the new changes.
