### ISSUE TITLE
Add provinces of Iran

### ISSUE THREAD

**Issue by saeedesmaili** [CSSEGISandData/COVID-19#133]
I have the numbers of each province in Iran for confirmed cases for 25th and 26th Feb. The source is  "The Islamic Republic News Agency" (https://www.irna.ir/). 
Can I edit the data and add these provinces? Is this the file that should be updated with new rows for each province of Iran? ```time_series_19-covid-Confirmed.csv```

**Comment by saeedesmaili** [comment]
sources:
https://www.irna.ir/photo/83689063
https://www.irna.ir/news/83684109
https://www.irna.ir/news/83685618
https://www.irna.ir/news/83687071
https://www.irna.ir/news/83688413

**Comment by CSSEGISandData** [comment]
Thanks! We may add more details for Iran in the future update.
