### ISSUE TITLE
New data structure time series data: Recovered cases are missing

### ISSUE THREAD

**Issue by GregFrei** [CSSEGISandData/COVID-19#1332]
The deprecation warning in the Time Series Data states that the 3 old files shouldn't be used anymore, and that 2 new files will be updated from now on. However, those 2 files only contain confirmed cases and deaths. Is there going to be a file containing the recovered cases?

**Comment by sibblegp** [comment]
Yep, my analysis of the data is failing

**Comment by GregFrei** [comment]
Nevermind, #1250 mentioned that recoveries won't be collected anymore.
