### ISSUE TITLE
Request for update - The first case in Greece (1)

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#134]
Hello, everybody,

**Greece** is still missing from the dashboard. The **first case** was officially confirmed by the Greek Ministry of Health.

**Source: "Greek Ministry of Health"**

https://www.moh.gov.gr/articles/ministry/grafeio-typoy/press-releases/6718-enhmerwsh-diapisteymenwn-syntaktwn-ygeias-apo-ton-ekproswpo-toy-ypoyrgeioy-ygeias-gia-to-neo-koronoio-kathhghth-swthrh-tsiodra

It concerns a 38-year-old Greek woman. Her state of health is very good so far. She is in a clinic in Thessaloniki.

**Comment by CSSEGISandData** [comment]
Thanks for the link. We have updated the database.
