### ISSUE TITLE
The new Recovered file is Missing

### ISSUE THREAD

**Issue by samscodes** [CSSEGISandData/COVID-19#1344]
Hello,according to the readme information ,the past 3 data sources of Confirmed, Recovered and Deaths  and now replaced with only the global Confirmed and Deaths. Will their be an update for the global Recovered data file anytime soon? 
Thank you in Advance.

**Comment by ma7555** [comment]
No more updates for the recovered data as stated in their new announcemnt

**Comment by kingwatam** [comment]
It doesn't make any sense to not update time series recovered cases, when that information is still available daily reports and the interactive map. 

And recovery data in the US went from 17 to 0 (which are now deprecated for some reason), what caused that?

**Comment by cipriancraciun** [comment]
@samscodes In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
