### ISSUE TITLE
PLEASE put individual US states back into time series data

### ISSUE THREAD

**Issue by cortical-iv** [CSSEGISandData/COVID-19#1348]
I did a code sprint this weekend, and now my application is basically broken because the individual US states are gone from the time series data. Please add individual US states to `time_series_covid19_confirmed_global.csv` to minimize the catastrophic breaking of many applications that rely on your very useful data. 

I did some analysis to explain the disease numbers to people, and now it doesn't work: I took an entire weekend to make this code on a weekend off for a code sprint, and I just don't know when I will have time to get back in there and fix this.

Please please please add US states back in.

**Comment by karlhschro** [comment]
Yes, PLEASE!

**Comment by joaolcorreia** [comment]
@CSSEGISandData the data was already messed up, but consistently messed up, now adding columns with a different level of granularity!?.

Revert and run the old script to process the data using the old rules (I bet on an R script no one can understand but you), if you want to add a new format create another feed that you will have to QA but continue with the old.

This causes less disruption to everyone who is already using the feed and lets you incrementally do whatever you want to do.

On the new structure think about NOT mixing dimensions (cities and counties and cruise ships), and NOT adding columns that represent the same thing for different time periods.

Makes sense? Come on ... you can do it!

**Comment by WorldCup82** [comment]
> I did a code sprint this weekend, and now my application is basically broken because the individual US states are gone from the time series data. Please add individual US states to `time_series_covid19_confirmed_global.csv` to minimize the catastrophic breaking of many applications that rely on your very useful data.
> 
> I did some analysis to explain the disease numbers to people, and now it doesn't work: I took an entire weekend to make this code on a weekend off for a code sprint, and I just don't know when I will have time to get back in there and fix this.
> 
> Please please please add US states back in.

Same here. What a waste of a weekend. 
Only thing I can see is to import the daily data and add each county/place for each state.. what a mess

**Comment by dhmacq** [comment]
Gee, did _anyone_ read #1250, where they clearly stated that new US  files with state and county level data will be provided?

**Comment by Lrakotoson** [comment]
And yet the [MAIN application](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) still has access to the old divisions. Not fair.

That's not just for the United States, but for many others.
**Besides, there is no more data for the "recovery" ones either.**

It's sad since it seems like a monopoly attempt knowing that yours still has access to the old data but the other small applications can't, and yet I saw some of them all put @CSSEGISandData as a source of data to redirect to Johns Hopkins University.

**Comment by Lrakotoson** [comment]
> 
> 
> And yet the [MAIN application](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) still has access to the old divisions. Not fair.
> 
> That's not just for the United States, but for many others.
> **Besides, there is no more data for the "recovery" ones either.**
> 
> It's sad since it seems like a monopoly attempt knowing that yours still has access to the old data but the other small applications can't, and yet I saw some of them all put @CSSEGISandData as a source of data to redirect to Johns Hopkins University.

My bad,
Have to work on the recovered cases as well, no big deal

**Comment by okarim-gh** [comment]
> Gee, did _anyone_ read #1250, where they clearly stated that new US files with state and county level data will be provided?

Oh thanks. Would have been more obvious in the readme file but good that you clues us in.

**Comment by dhmacq** [comment]
> > Gee, did _anyone_ read #1250, where they clearly stated that new US files with state and county level data will be provided?
> 
> Oh thanks. Would have been more obvious in the readme file but good that you clues us in.

Yeah, readme would have been good.

**Comment by cortical-iv** [comment]
> 
> 
> Gee, did _anyone_ read #1250, where they clearly stated that new US files with state and county level data will be provided?

It was buried in the issues. It should have been put in the main part of the repo.

**Comment by ZGainsforth** [comment]
> #1250

Well, let's cut a little slack for some folks who are at least making the data available!

I would recommend that the US data and global data files should be written first, and only *then* deprecate the old format.  Ideally, give a couple days between changing the format and deprecating so that folks have a chance to update dependent code.

**Comment by cortical-iv** [comment]
Closed: moving my analysis to start using:
 https://covidtracking.com

They are just more serious developers.

It has real developers behind it. Took just about 1 1/2 hours to port my app over to theirs. Would take someone really good with pandas about 30 minutes. :)

**Comment by owahltinez** [comment]
I also moved my data source for US states to https://covidtracking.com. If you are interested in consistent, worldwide data (including US states) you can check out my project: https://github.com/open-covid-19/data
