### ISSUE TITLE
🛑 Missing values for Thailand, Singapore, Others on 24th of Feb 🛑

### ISSUE THREAD

**Issue by AaronWard** [CSSEGISandData/COVID-19#135]
I wrote about this before but got ignored.

@CSSEGISandData Can you fix the problem for the 24th? There is no listings for thailand, singapore and "others" on the 24th. 

```python
countries_23 = set(df[df.date == '2020-02-23'].country)
countries_24 = set(df[df.date == '2020-02-24'].country)
check_these = countries_23.difference(countries_24)
```

```bash
{'Others', 'Singapore', 'Thailand'}
```

```python
df.groupby(['date']).confirmed.sum()
```

```
2020-02-23    78783
2020-02-24    78458      <---- confirmed cases decreases
2020-02-25    79429
Name: confirmed, dtype: int64
```

**Comment by CSSEGISandData** [comment]
We have checked the data on the 24th and the data for these countries are present.

**Comment by AaronWard** [comment]
@CSSEGISandData 

How come the confirmed counts for the "other" locations get changed in later dates. 
For example, the 22nd it was reported that 2 people were confirmed in `Lackland, TX (From Diamond Princess)` then it changes to 0 in on the 24th. I have also added other examples...

<hr>


 | confirmed | country | deaths | datetime | province | recovered | date | file_date
-- | -- | -- | -- | -- | -- | -- | --
2 | US | 0 | 2020-02-22 17:13:24 | Lackland, TX (From Diamond Princess) | 0 | 2020-02-22 | 2020-02-23
0 | US | 0 | 2020-02-24 23:33:02 | Lackland, TX (From Diamond Princess) | 0 | 2020-02-24 | 2020-02-24




 | confirmed | country | deaths | datetime | province | recovered | date | file_date
-- | -- | -- | -- | -- | -- | -- | --
 | 11 | US | 0 | 2020-02-22 23:03:09 | Omaha, NE (From Diamond Princess) | 0 | 2020-02-22 | 2020-02-23
 |0 | US | 0 | 2020-02-24 23:33:02 | Omaha, NE (From Diamond Princess) | 0 | 2020-02-24 | 2020-02-24


confirmed | country | deaths | datetime | province | recovered | date | file_date
-- | -- | -- | -- | -- | -- | -- | --
| 5 | US | 0 | 2020-02-22 17:13:24 | Travis, CA (From Diamond Princess) | 0 | 2020-02-22 | 2020-02-23
0 | US | 0 | 2020-02-24 23:33:02 | Travis, CA (From Diamond Princess) | 0 | 2020-02-24 | 2020-02-24



<br>

Why are locations that hypothetically have **zero** cases even being listed on the sheets? it makes absolutely no sense.
