### ISSUE TITLE
Time series data for Mar 23 Data is incorrect.

### ISSUE THREAD

**Issue by dbl007** [CSSEGISandData/COVID-19#1355]
Time series data for Mar 23 Data is incorrect. 
It number is the same as Mar 22 data.

**Comment by mpodell** [comment]
Look at the readme.md:

The files below will no longer be updated. With the release of the new data structure, we are updating our time series tables to reflect these changes. Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data. <br><br>
time_series_19-covid-Confirmed.csv	<br>
time_series_19-covid-Deaths.csv	<br>
time_series_19-covid-Recovered.csv

**Comment by c1au6i0** [comment]
If you are looking for the data of each U.S. state, they can be find in the `COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/` folder

It doesn't seem that `time_series_covid19_confirmed_global.csv` includes each U.S. state data.

**Comment by mpodell** [comment]
True, state level data is missing from global.csv. It does seem an error, though, since Canadian provinces, Australian states and Chinese provinces / mega-cities are listed.

**Comment by dbl007** [comment]
Thks.
