### ISSUE TITLE
Daily report at 23 Mart is incorrect at US - why 0 recovered

### ISSUE THREAD

**Issue by surrsoft** [CSSEGISandData/COVID-19#1356]
File root:\csse_covid_19_data\csse_covid_19_daily_reports\03-23-2020.csv

**Comment by aquilesC** [comment]
This was warned and explained in #1250

**Comment by theronrr** [comment]
https://github.com/ulklc/covid19-timeseries/blob/master/report/country/US.csv

**Comment by cipriancraciun** [comment]
@surrsoft In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
