### ISSUE TITLE
Is recovery data gone after March 23 with new format?

### ISSUE THREAD

**Issue by PSY-github** [CSSEGISandData/COVID-19#1359]

**Comment by ivanMSC** [comment]
Yes. Let's get the hell out of here.

**Comment by aquilesC** [comment]
This was warned and explained in #1250

**Comment by cipriancraciun** [comment]
@PSY-github In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
