### ISSUE TITLE
Request for Update - Confirmed case in Brazil 

### ISSUE THREAD

**Issue by kauannavs** [CSSEGISandData/COVID-19#136]
Hello, everybody,
According R7 a newspaper from brazil. Brazil has the first confirmed case of the virus.

> https://noticias.r7.com/jr-24h/boletim-jr-24h/videos/primeiro-caso-de-coronavirus-no-brasil-e-confirmado-em-sao-paulo-26022020

**Comment by jesobreira** [comment]
Confirmed by [ECDC](https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases)

**Comment by ScrimForever** [comment]
Please, add São Paulo , State of case
