### ISSUE TITLE
A mess

### ISSUE THREAD

**Issue by YoannParis** [CSSEGISandData/COVID-19#1361]
I totally understand it's a difficult job you guys, are doing. But to be honest, i've never seen a university acting like you are doing. 
Your data files have been a mess from the beginning, you were unable to maintain it in order and never listen the warnings and advices the members of the community have written here, day after day.
And now, you do not try to improve, you just stop to publish the time series in the middle of this world crisis. A shame.

**Comment by ivanMSC** [comment]
Agreed. Absolutely disgusting. I encourage everyone to find an alternative repository. There are plenty out there.  The one I will be using now is https://github.com/ulklc/covid19-timeseries. Great if you only care about top level administrative regions (Countries) with ISO codes.

**Comment by c1au6i0** [comment]
> The Johns Hopkins University hereby disclaims any and all representations and warranties with respect to the Website, including accuracy, fitness for use, and merchantability

They don't have  to maintain the repository or keep the data it in a format  that you or anyone else likes, or even share the data. They are providing this freely. Not sure why people feel so easily entitled.

**Comment by iandoug** [comment]
@c1au6i0 ... because they have become the global "official" source. With great power comes great responsibility.

**Comment by dhmacq** [comment]
> Agreed. Absolutely disgusting. I encourage everyone to find an alternative repository. There are plenty out there. The one I will be using now is https://github.com/ulklc/covid19-timeseries. Great if you only care about top level administrative regions (Countries) with ISO codes.

And Johns Hopkins is one of their sources, according to their README.md

**Comment by ivanMSC** [comment]
@dhmacq Because JHU is performing the tests on everyone on earth, right?

**Comment by YoannParis** [comment]
> > The Johns Hopkins University hereby disclaims any and all representations and warranties with respect to the Website, including accuracy, fitness for use, and merchantability
> 
> They don't have to maintain the repository or keep the data it in a format that you or anyone else likes, or even share the data. They are providing this freely. Not sure why people feel so easily entitled.

So, what the point to post data and talk in the media as THE source if they are not able to maintain a correct .csv file 2 following days ?
