### ISSUE TITLE
JHU needs to include a time_series_covid19_recovered.csv file.

### ISSUE THREAD

**Issue by ngerstein** [CSSEGISandData/COVID-19#1364]
Many of us are understandably upset with the new data format. It's unclear why March 23 data matches March 22 data in the time_series file for all regions save for the US counties. If they want us to go to the _global files for the most up-to-date data, they should include a time_series_covid19_recovered.csv file, rather than make us go to the daily reports data for the most recent recovered values...

**Comment by mortenbache** [comment]
Agree, where is the recovered time series now?

**Comment by aangelopoulos** [comment]
Agree. This is a very important time series for use in estimating the time-lag. Why not keep updating it?

**Comment by ExpDev07** [comment]
Agreed. This [seriously messed up my API](https://github.com/ExpDev07/coronavirus-tracker-api). Suddenly I have to show 0 because the indexing doesn't match with the new files, causing locations to show numbers not belonging to them.

**Comment by ngerstein** [comment]
Hopefully they will realize their mistake and correct it. We could try calling them out on twitter? @HopkinsMedicine. I didn't see a contact email for the dashboard anywhere...

**Comment by horrypong** [comment]
Strongly agree! For many countries (like South Korea, China and others) the active cases (i.e. confirmed - death - recovered) is more meaningful than no. of confirmed case. Please provide the time series of recovered as well.

**Comment by cipriancraciun** [comment]
@ngerstein In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.

**Comment by ngerstein** [comment]
@cipriancraciun certainly, it looks like a recovered_global file has been included starting 3/26 by JHU.
