### ISSUE TITLE
Kosovo, where are the data of Kosovo

### ISSUE THREAD

**Issue by YoannParis** [CSSEGISandData/COVID-19#1380]
Weird, after the mess with Taiwan data, i thought you have learnt that some new countries are real countries.
To delete the data of Kosovo is not respectful for the citizens of Kosovo and for the 31 who are sick there.

I knew you receive money from China, but i didn't know you are also friend with Serbia. And guess who, in Europe, has the best relationship with China ? Serbia !  Amazing isn't it ?

**Comment by dende** [comment]
> I knew you receive money from China

Who receives money from China?

**Comment by rmunjuluri** [comment]
I believe the issue is that Taiwan and Kosovo do not have ISO3 codes and the so the merges can potentially drop these rows. Need fixing

**Comment by CSSEGISandData** [comment]
Kosovo is listed in our report now. Thanks!
