### ISSUE TITLE
23rd of March data messed al attributes names

### ISSUE THREAD

**Issue by GermanCM** [CSSEGISandData/COVID-19#1382]
Dear team, no problem with adding new column names to the daily CSVs, but would it be possible at least to keep the same attributes with the same names?
`Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key'],
      dtype='object')
"['Longitude', 'Province/State', 'Latitude', 'Last Update', 'Country/Region'] not in index"`

**Comment by 00lex** [comment]
And please add new date at the end. My whole script breaks every update

**Comment by avatorl** [comment]
@CSSEGISandData Thanks for your hard work. But when you share the data with the world could you please keep data structure consistent? Honestly it's the worst data management I've seen in my life. You already have at least 3 totally different formats of CSV files for the same data. And was there any reason to rename existing fields? And renaming 'Long' into 'Long_' is totally crazy.

**Comment by 00lex** [comment]
I’ve decided to make my script more solid against changes. Hope this works

**Comment by GermanCM** [comment]
> I’ve decided to make my script more solid against changes. Hope this works.
> 
> Please just don’t change the comma separator and the column names

Indeed, but many column names already changed since yesterday, so there is no other option than making robust scripts for any other likely modification...

**Comment by GermanCM** [comment]
Finally used the time series data format source, although still some issues on some countries...
