### ISSUE TITLE
Time Series - Recovered Data

### ISSUE THREAD

**Issue by hrmartins** [CSSEGISandData/COVID-19#1392]
Hi,

Regarding the time series data, you have in the read.me:

"Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data."

What about the Recovered Data?

Is there any updated data? sorry for the question but we have a lot of reports with this data. :(

Best regards,

**Comment by s-slavchev** [comment]
Hi, 
@hrmartins is right, recovered timeseries data is much needed

All best

**Comment by micder** [comment]
Yes,
it's very importante to make predictions

**Comment by theronrr** [comment]
https://github.com/ulklc/covid19-timeseries/blob/master/report/country/US.csv

**Comment by cipriancraciun** [comment]
@hrmartins In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
