### ISSUE TITLE
3/23 CSV format changed but csse_covid_19_data README is not updated

### ISSUE THREAD

**Issue by texadactyl** [CSSEGISandData/COVID-19#1398]
Specifically, two mysterious columns were added: FIPS, Admin2.
Do they have a function?

Sorry to complain but my Python code was surprised.  (=:
I'll adjust.

**Comment by jankyupeblik** [comment]
Please see #1397, and more generally remember to always check your input for sanity.

**Comment by texadactyl** [comment]
I always do a sanity check.
The format and ordering of the columns changed.

- Two columns were inserted in the front.
- The 3 usual count columns were moved.
- A new "active" column was added.
- A new "combined key" column was added.

It was a surprise.  Nothing to do with data sanity.  Changes not documented.

**Comment by yetzt** [comment]
yes, us states were removed, county/city ased data was added and columns renamed. see #1326 #1250

**Comment by jankyupeblik** [comment]
> I always do a sanity check.
> The format and ordering of the columns changed.

Indeed. You weren't checking number of columns. You weren't checking names of columns. You weren't checking expected data for columns.

It was a surprise, but to avoid this situation in the future, check your input.

**Comment by texadactyl** [comment]
I saw them.  Thanks.  Appreciated.

_Issue reports_ on github are not documentation; they are for bug reporting and enhancement requests.  When design changes take place (E.g. an interface file format), the github project version is normally updated with visible documentation changes (E.g. README).  That's the normal github practice and software development practice.

Thanks again for furnishing the issue references.

**Comment by jankyupeblik** [comment]
> _Issue reports_ on github are not documentation

Agreed.

**Comment by texadactyl** [comment]
@jankyupeblik @yetzt -

Sorry to be a bother.  You lot at JHU must be up to your eyeballs in various work.

What I've been doing is extracting the data from the CSVs and storing it in a database with a Python program.  Subsequently, run adhoc SQL queries from a command line executable and using some fixed query Python programs.  

I have been using sqlite3 to-date but it could easily be MySQL, Oracle, or any other database product as a platform.

**Comment by yetzt** [comment]
@texadactyl i'm not from JHU. i'm also annoyed and just trying to help #1326

**Comment by texadactyl** [comment]
```<3``` looks like an ice cream cone to me.  (-:
