### ISSUE TITLE
27 cases in Germany? 1 too many in the dashboard (currently "only" 26)

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#141]
I don't know how you come up with 27 cases in Germany. Currently there are **26 cases** and no more, no less. There were 3 new cases in the federal state of North Rhine-Westphalia. So there are 5 in this state and 26 in **Germany**. > CC: #126 

**Source: "Ministry of Labour, Health and Social Affairs of North Rhine-Westphalia"**
https://www.mags.nrw/pressemitteilung/drei-neue-corona-faelle-nordrhein-westfalen

What source do you have for the 27th case?

![Bildschirmfoto vom 2020-02-27 01-26-08](https://user-images.githubusercontent.com/49625256/75400913-dfedd800-5900-11ea-8d31-981603fbeba6.png)

**Comment by LeoniePhiline** [comment]
27 cases: https://www.bundesgesundheitsministerium.de/coronavirus.html

**Comment by iceweasel1** [comment]
26

![Bildschirmfoto vom 2020-02-27 17-25-31](https://user-images.githubusercontent.com/49625256/75463510-38b38400-5986-11ea-9d18-5b263ed409a2.png)

**Comment by iceweasel1** [comment]
Yeah, just now on German television on a news show. Nice the source JHU indicated (top right). ;-)
![Bildschirmfoto vom 2020-02-27 18-51-45](https://user-images.githubusercontent.com/49625256/75471451-93eb7380-5992-11ea-9847-3a36c8996a4b.png)
