### ISSUE TITLE
Iran recovered 49 likely incorrect

### ISSUE THREAD

**Issue by scungy** [CSSEGISandData/COVID-19#142]
Hi, Iran has reported 49 recovered cases on 26 Feb, when their first infection was only 7 days ago (19 Feb). And they had only accumulated 49 confirmed cases 4 days ago (22 Feb).

This seems unlikely. Most other countries are only reporting recovered cases after at least 3 weeks after confirmation.

**Comment by CSSEGISandData** [comment]
Could be. Some pre print paper estimates the number could be much higher.
