### ISSUE TITLE
U.S. State Breakdown Missing

### ISSUE THREAD

**Issue by kondis** [CSSEGISandData/COVID-19#1426]
Is there a plan to reintroduce the state by state raw counts to the new time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv sources? Provincial breakdowns seam to exist on these sources for most other countries.

**Comment by MEM-TEK** [comment]
State breakdown for cities and counties is in the daily_reports data. JHU has made it easy to sort this data for each US state.

**Comment by jadraketx** [comment]
Perhaps I'm missing something, but it looks like county level data in the US in the daily_reports data is not reported for 03-10 and later. We're working on modeling the spread at the county level in Texas and it would be extremely helpful to access the updated data displayed on the dashboard currently. Any suggestions?

**Comment by jdtsmith** [comment]
See also #1428.

**Comment by kondis** [comment]
It looks like separate CSVs are coming with a more granular U.S. data breakdown that is separate from the new global breakdowns, as I understand the following.

https://github.com/CSSEGISandData/COVID-19/issues/1250#issue-585788363
