### ISSUE TITLE
Will JSU explain why it will no longer report active and recovered cases?

### ISSUE THREAD

**Issue by MEM-TEK** [CSSEGISandData/COVID-19#1430]
Will JSU explain why it will no longer report active and recovered cases? Both are very important metrics to track.

**Comment by timday** [comment]
There's a comment from them on (IIRC) the issue on the data change that "No reliable data source reporting recovered cases for many countries, such as the US."

See https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-603255860 for a possible workround for active cases.

**Comment by ulklc** [comment]
Hi @MEM-TEK ,
You can check alternative source: https://github.com/ulklc/covid19-timeseries

Who is not providing recovery information anymore. But some dashboards are working as report based data collecting. example:
https://ncov.dxy.cn/ncovh5/view/pneumonia
https://www.worldometers.info/coronavirus/
https://bnonews.com/index.php/2020/03/the-latest-coronavirus-cases/

But data might be not reliable

**Comment by cipriancraciun** [comment]
@MEM-TEK In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.
