### ISSUE TITLE
Field name inconsistency.

### ISSUE THREAD

**Issue by sagarp2901** [CSSEGISandData/COVID-19#1436]
Could we please make the field names consistent between time series and daily reports?
For example: Time series has Country/Region and Daily reports have Country_Region.

Also, field names like Longitude have been changed to Long_, Latitude to Lat which is kind of inconsistent.

**Comment by jonisapp** [comment]
Yes, it's a lot of daily work to maintain and not very professionnal

**Comment by Hikmer** [comment]
Everything is now broken...can we just roll it all back and say that the new data idea was a horrible idea?
