### ISSUE TITLE
in 03-23-2020.csv collumn names changed format

### ISSUE THREAD

**Issue by leotuni** [CSSEGISandData/COVID-19#1447]
If you check for example 03-08-2020.csv, it is spelled  'Last Update', while in 03-23-2020.csv  it is Last_Update.

03-23-2020.csv: FIPS | Admin2 | Province_State | Country_Region | Last_Update | Lat | Long_

03-08-2020.csv: Province/State | Country/Region | Last Update | Confirmed | Deaths | Recovered | Latitude | Longitude

Probably it is better formatted as Last_Update

**Comment by CSSEGISandData** [comment]
Thanks @leotuni - has been corrected.
