### ISSUE TITLE
Tableau Viz based on CSSEGISanData/COVID-19

### ISSUE THREAD

**Issue by 3verse** [CSSEGISandData/COVID-19#145]
Hi Everyone,
I've updated a public Tableau Viz available here:

[https://public.tableau.com/profile/salvatore1114#!/vizhome/wdctest/COVID-19StatusUpdate
](https://public.tableau.com/profile/salvatore1114#!/vizhome/wdctest/COVID-19StatusUpdate
)
This is based on the data available on this repository - I've set up a process to regularly pull and merge all daily reports and made it available as a tableau Web Data Connector.

The visualisation can be downloaded as well as edited offline, the data connector is also publicly available if you'd like to use it.

I'd be interested in hearing your thoughts about it as well as if you guys want to use a link to this one as a backup for peak traffic times I wouldn't mind, feel free to use it.

All best and keep up the good work,
Sal

**Comment by omaldonado60** [comment]
Hi, thanks for sharing.
This viz show progress by country. Maybe you can do it better,
Cheers!
https://public.tableau.com/profile/omar.maldonado.a.#!/vizhome/AvanceCovid19/Covid-19

**Comment by jcavfen9** [comment]
Hi Tableau users,

Here is my contribution. I try to work to show-up forecasts anf trends:
https://public.tableau.com/views/Coronavirus2019-nCoVstats/Coronavirus2019-nCoV?:display_count=y&:origin=viz_share_link

Best regards,
Jean-Paul

**Comment by 3verse** [comment]
> Hi Tableau users,
> 
> Here is my contribution. I try to work to show-up forecasts anf trends:
> https://public.tableau.com/views/Coronavirus2019-nCoVstats/Coronavirus2019-nCoV?:display_count=y&:origin=viz_share_link
> 
> Best regards,
> Jean-Paul

HI Jean-Paul, 
Many thanks for sharing, it's a really interesting view on the data.
Nice take on the recovery rates, my latest updates were focusing on fatality rates but good to add the positive side to this too.

Kind regards,
Sal

**Comment by 3verse** [comment]
Updated my public tableau visualisation with a few more views - please feel free to feedback if anything you'd like to add or contribute to: [https://public.tableau.com/profile/salvatore1114#!/vizhome/wdctest/CoronavirusCOVID-19Dashboard-DailyUpdates](https://public.tableau.com/profile/salvatore1114#!/vizhome/wdctest/CoronavirusCOVID-19Dashboard-DailyUpdates
)
