### ISSUE TITLE
"Recovered" and "Active" columns of daily report all 0's for US location for March 23

### ISSUE THREAD

**Issue by mtholder** [CSSEGISandData/COVID-19#1450]
See https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv for commit e748b6d8a55e4a88371af56b129ababe1712522d

Thanks for all the hard work on this project and the data sharing!

**Comment by joaopedrosantos** [comment]
Read [https://github.com/CSSEGISandData/COVID-19/issues/1250](#1250 )

**Comment by mtholder** [comment]
thanks for the pointer. closing this.
