### ISSUE TITLE
Confirmed cases changes to 0 after 24th of Feb 🤦🏻‍♂️

### ISSUE THREAD

**Issue by AaronWard** [CSSEGISandData/COVID-19#146]
@CSSEGISandData 

How come the confirmed counts for the "other" locations get changed in later dates. 
For example, the 22nd it was reported that 11 people were confirmed in `Omaha, NE (From Diamond Princess)` then it changes to 0 in on the 24th. I have also added other examples...

<hr>

 | confirmed | country | deaths | datetime | province | recovered | date | file_date
-- | -- | -- | -- | -- | -- | -- | --
2 | US | 0 | 2020-02-22 17:13:24 | Lackland, TX (From Diamond Princess) | 0 | 2020-02-22 | 2020-02-23
0 | US | 0 | 2020-02-24 23:33:02 | Lackland, TX (From Diamond Princess) | 0 | 2020-02-24 | 2020-02-24

 | confirmed | country | deaths | datetime | province | recovered | date | file_date
-- | -- | -- | -- | -- | -- | -- | --
 | 11 | US | 0 | 2020-02-22 23:03:09 | Omaha, NE (From Diamond Princess) | 0 | 2020-02-22 | 2020-02-23
 |0 | US | 0 | 2020-02-24 23:33:02 | Omaha, NE (From Diamond Princess) | 0 | 2020-02-24 | 2020-02-24

confirmed | country | deaths | datetime | province | recovered | date | file_date
-- | -- | -- | -- | -- | -- | -- | --
| 5 | US | 0 | 2020-02-22 17:13:24 | Travis, CA (From Diamond Princess) | 0 | 2020-02-22 | 2020-02-23
0 | US | 0 | 2020-02-24 23:33:02 | Travis, CA (From Diamond Princess) | 0 | 2020-02-24 | 2020-02-24

<br>

Why are locations that hypothetically have **zero** cases even being listed on the sheets? it makes absolutely no sense. 

Can you please change it back to `others : diamond princess cruise ship` and stop assigning states to them. If the infected are reported to go back to their home country just deduct them from the others count and add the delta value to the country they travel to.

**Comment by CSSEGISandData** [comment]
We grouped all US cases repatriated from Diamond Princess as "Unassigned location (From Diamond Princess), US".

**Comment by dawenx** [comment]
@CSSEGISandData I suggest to visit all days that have repatriated cases to make it consistent. Thanks!

**Comment by AssureHSC** [comment]
Or, group them a country level, as previous. The repatriated cases are no longer in Japan. 

![2020-02-29_14-43-04](https://user-images.githubusercontent.com/61626466/75609883-3d9e4200-5b04-11ea-9aab-a0bda9fa068d.png)

**Comment by CSSEGISandData** [comment]
For privacy concern, we don't know the exact location of cases repatriated from the Diamond Princess. Putting the dot in any place in the US will upset local residents. We therefore have to leave the dot in Japan. Once we got further information, we will update its location. Thanks!
