### ISSUE TITLE
March23 US data are all blank

### ISSUE THREAD

**Issue by rahzan** [CSSEGISandData/COVID-19#1461]
file:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
I'm sorry if this is superfluous and surely you are aware, the column March-23rd is all blank for most/all US regions. This is not the case in the _global_ file which has only one entry for the US. 
As of March24th-1200PT/1500ET

**Comment by caesarsol** [comment]
And all other countries' data is just duplication of March 22!

**Comment by chfritz** [comment]
I assume this is because it will no longer be updated. See https://github.com/CSSEGISandData/COVID-19/commit/6eab8cc908dff4d44b631053582ad4311f50ebcb#diff-d8d7e83375208bde5ddd848c622cc062.

**Comment by meldehi** [comment]
chfritz Thankf for pointing this out

**Comment by Bmr55** [comment]
#1250 explains this

**Comment by rahzan** [comment]
If I understand, #1250 states there be a NEW TABLE "...will be named time_series_covid19_confirmed_US.csv", which I don't see yet. Also that site will stop reporting recovery case data, unfortunately. Seems: the _global_file is the file to go with, and we might see a separate _US_ file with county level data.

**Comment by Bmr55** [comment]
Yes, that is correct.  Unfortunately, we are still waiting on the US files. It's unclear when they will be uploading those. I hope they add them during today's update at 11:59PM UTC.

**Comment by thomasgravina** [comment]
Can we close this issue then? It is gonna help reduce the noise in the `Issues` tab.

**Comment by rahzan** [comment]
Yes
