### ISSUE TITLE
United States - Recovered

### ISSUE THREAD

**Issue by cptrguru** [CSSEGISandData/COVID-19#1462]
After the new format on 03-23-2020, no recovered cases are included for the United States.

**Comment by Bmr55** [comment]
#1250 states they will no longer provide recovered cases.

**Comment by JeroenKools** [comment]
I've been deriving a proxy for recoveries in [my model](https://github.com/JeroenKools/covid19) that works like this:

* Keep track of how long cases have been active. For example, if you have 10 new cases on day 1, 12 new cases on day 2 and 15 on day 3, case duration history for day 3 would be `15, 12, 10`. I use a case duration history of 21 days based on [this source](https://www.mdpi.com/2077-0383/9/2/538).
* Distribute recorded deaths for the day over currently active cases according to the distribution in the source above:
![onset to death distribution](https://www.mdpi.com/jcm/jcm-09-00538/article_deploy/html/images/jcm-09-00538-g001.png)
So, multiply the above *onset to death* distribution by the case duration history to get deaths per case duration for the current day. Subtract those from the active cases.
* Iterate through each day in the data doing this, adding new cases on the left side and shifting the rest of the history to the right each day. If active cases reach day 21 without dying, consider them recovered, and add them to the total recovered.

**Comment by cptrguru** [comment]
> #1250 states they will no longer provide recovered cases.

The time series data is a different dataset from the csse_covid_19_daily_reports, which is where this issue is surfacing.

**Comment by cptrguru** [comment]
JeroenKools, sincerely appreciate the reply and info!

**Comment by Bmr55** [comment]
> > #1250 states they will no longer provide recovered cases.
> 
> The time series data is a different dataset from the csse_covid_19_daily_reports, which is where this issue is surfacing.

This comment in #1250 states it also applies to daily reports:

>  No recovered cases will be reported in the daily reports and the time series tables.

_Originally posted by @CSSEGISandData in https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-602258106_

**Comment by JiPiBi** [comment]
But for the moment **recovered** remain in daily reports , aren't they ?  (+ **active** , even if not necessarry )
