### ISSUE TITLE
Chicago coordinates seem wrong

### ISSUE THREAD

**Issue by zimrick** [CSSEGISandData/COVID-19#147]
The location of Chicago, IL in the time series file seems wrong.
The correct coordinates should be somewhere around `41.8781, 87.6298`.

<img width="528" alt="Screenshot 2020-02-27 at 15 13 48" src="https://user-images.githubusercontent.com/7160099/75453183-cb96f300-5973-11ea-8243-ba316fa946ae.png">

**Comment by CSSEGISandData** [comment]
We have updated the coordinates in the time series tables to reflect what the dashboard is currently showing.
