### ISSUE TITLE
Add recovered statistics in time series

### ISSUE THREAD

**Issue by gtkChop** [CSSEGISandData/COVID-19#1472]
According to the depreciation warning, there is no data available for recovered cases (only confirmed and deaths). Is this for a reason? or Can we add a new CSV for recovered "time_series_covid19_recovered_global.csv"?

**Comment by fezde** [comment]
Completely agree... Would love to see it back

**Comment by Bmr55** [comment]
> Is this for a reason? 

This comment in #1250 gives the reason:

> No reliable data source reporting recovered cases for many countries, such as the US.

 _Originally posted by @CSSEGISandData in https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-602271179_

**Comment by gtkChop** [comment]
@Bmr55 Thanks for pointing to an issue.
