### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by desaian** [CSSEGISandData/COVID-19#1473]
Anybody understand why I keep getting a parsing error with this small bit of code?

#1Read selected CSV data
# Load the Pandas libraries with alias 'pd' 
import pandas as pd
# Access https csv Data from Github for Deaths.csv
url = 'https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv'
deaths = pd.read_csv(url, sep=",")
Washington = data.loc[2878]

**Comment by thomasgravina** [comment]
Does not seem related to an issue with the repository. Might be wise to delete to avoid unnecessary noise in the `Issues` tab of this repo.

**Comment by joaopedrosantos** [comment]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv

The url is not a csv file.. try

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv

and this is not the place to ask these questions regarding py

**Comment by desaian** [comment]
Thanks
