### ISSUE TITLE
Start above 500 cases unifying all countries

### ISSUE THREAD

**Issue by rodrigoKulb** [CSSEGISandData/COVID-19#1475]
Hello guys, I made a graph with a start above 500 cases unifying all countries below the link:

http://rodrigo-kulb.com.br/corona.php?b=Inicio

**Comment by stucho** [comment]
Hi Rodrigo,

what about an english explanation and an english website?

Muitas saudações

**Comment by thomasgravina** [comment]
This is not about an issue related to the repository, please delete to avoid unnecessary noise in the `Issues` tab of this repo.

**Comment by rodrigoKulb** [comment]
Ok @thomasgravina no problem!
