### ISSUE TITLE
March23 data are all WRONG

### ISSUE THREAD

**Issue by stucho** [CSSEGISandData/COVID-19#1476]
The data are from the previous day.

**Comment by thomasgravina** [comment]
This is a duplicate issue, which has been mentioned many time. Might be wise to delete it to avoid unnecessary noise in the `Issues` tab.

**Comment by stucho** [comment]
Yes...it would be wise. Why do blame me for that??

**Comment by thomasgravina** [comment]
Not blaming - sorry if it seemed like it.

**Comment by cortical-iv** [comment]
> Yes...it would be wise. Why do blame me for that??

I would blame you because it means you didn't bother to look at the other 100 threads about the same thing that were opened today.
