### ISSUE TITLE
Argentina, incorrect data 'recovered'

### ISSUE THREAD

**Issue by SoyDiego** [CSSEGISandData/COVID-19#1477]
In Argentina there are 56 recovered as of today but it shows 3 only. 
How can it be corrected? Thank you

**Comment by billyburgoa** [comment]
They are not providing this information since 2 days ago and they won't do it in a future. Reason: Inaccurate information.

**Comment by SoyDiego** [comment]
> They are not providing this information since 2 days ago and they won't do it in a future. Reason: Inaccurate information.

Thanks for your reply. The information is correct if you visit the website: 
https://www.argentina.gob.ar/coronavirus/informe-diario you have the daily report.

Do you know how often the information is updated? I searched for it but couldn't find it. GMT Time?
Thanks again!

**Comment by billyburgoa** [comment]
Take a look to the daily reports in which you will find the date and time that the information has been updated ( https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv ). 

In my case, I am updating the information of my country manually using a reliable source. I've created some files in a json format and I update them when the info has changed.
 
In a general view, I noticed that the info for latinamerican countries is updated between 23 to 00 GMT everyday.

**Comment by SoyDiego** [comment]
> Take a look to the daily reports in which you will find the date and time that the information has been updated ( https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv ).
> 
> In my case, I am updating the information of my country manually using a reliable source. I've created some files in a json format and I update them when the info has changed.
> 
> In a general view, I noticed that the info for latinamerican countries is updated between 23 to 00 GMT everyday.

Thanks!
