### ISSUE TITLE
A lot of incorrect data

### ISSUE THREAD

**Issue by PedroDKE** [CSSEGISandData/COVID-19#1479]
I'm reading a lot of issues about incorrect data, how is it that 

1) this has still not been fixed?(around 11/03 and 12/03 there have been 0 new cases for a lot of countries such as Italy,Belgium,Spain,...) While official instances did report them.
2) the website also by JHU does seem to have correct data, but this github rep does not? 

Any idea when this issue will be fixed?

**Comment by sgt101** [comment]
I've done a pull request for the UK data - there are several repeated values, I am seeing this influence fit on infographics in places like the NYTimes, this is really very very bad. Why the hell is this not being fixed?

**Comment by lasleandro** [comment]
I agree.. The website seems to be correct, but they cant fix the repo data... so simple...

**Comment by JiPiBi** [comment]
@sgt101 
if your PR is accepted , pls let us know : perhaps this method could be  more efficient than writing issues  :-(
