### ISSUE TITLE
Seattle coordinates seem wrong

### ISSUE THREAD

**Issue by zimrick** [CSSEGISandData/COVID-19#148]
The location of Seattle, WA in the time series file seems wrong.
The correct coordinates should be somewhere around `47.6062, 122.3321`.

<img width="596" alt="Screenshot 2020-02-27 at 16 59 02" src="https://user-images.githubusercontent.com/7160099/75461037-7b735d00-5982-11ea-9cab-7f5103ba21fd.png">

**Comment by CSSEGISandData** [comment]
The coordinates in the time series table is only a reference. We adjusted them in the dashboard.

**Comment by CSSEGISandData** [comment]
we have updated the time series tables with the latest coordinates from the dashboard.
