### ISSUE TITLE
French Polynesia cases inflated

### ISSUE THREAD

**Issue by djlohman** [CSSEGISandData/COVID-19#1482]
The latest version of this file lists the number of cases in French Polynesia at 19874, but independent news sources put the number around 25.  Have these data been entered incorrectly?

https://www.rnz.co.nz/international/pacific-news/412465/french-polynesian-covid-19-cases-climb-to-23

**Comment by JiPiBi** [comment]
See #1440

**Comment by thomasgravina** [comment]
As highlighted by @JiPiBi , this issue is a duplicate; please close ticket.
