### ISSUE TITLE
...._US.csv

### ISSUE THREAD

**Issue by CalvinParis** [CSSEGISandData/COVID-19#1505]
When will        time_series_covid19_confirmed_US.csv, time_series_covid19_deaths_US.csv, time_series_covid19_testing_US.csv   be available ?

**Comment by Siphon880gh** [comment]
I second this. I am saddened that they stopped reporting state level information. This really matters in US because the states' demographics are scattered. You can't treat the entire US as a homogenous population.

**Comment by darthshittius** [comment]
Oh no! I was scraping data from 'time_series_19-covid-Confirmed.csv' and also the (recovered and deaths versions) to analyse the spread in California, but now I see the data doesn't appear to be updated in the past few days.. :(

**Comment by JumpyJenny** [comment]
We **really** need the state data back again!

**Comment by Siphon880gh** [comment]
They don't care. There was another issue made for county level information like Los Angeles within California. They stopped county level reporting on 3/10/20
https://github.com/CSSEGISandData/COVID-19/issues/495

Now it appears they stopped state level reporting on 3/24/20

**Comment by rks125** [comment]
You can still get time series data for after 3/22 using the file I created here in this case #1496 

To create this, I took the last older schema version of the time series data and combined it with the newer daily data (which includes US states).   I maintained the old schema so your scripts or applications should still work.

I did this to bridge the gap between them fixing this or until you modify your app to the new format.

**Comment by davidbau** [comment]
For anybody doing USA by-state time series visualization in Javascript, here is an example of doing this aggregation in javascript.  It automatically loads and sums as many individual days as needed, starting 3/23 so can hold us over until the new time series appears. Maybe somebody will find it helpful.

https://github.com/davidbau/covid-19-chart/blob/faf6470009ed20b26b02c81f9a1ab9e41362a1a8/index.html#L151-L348

(This is what's used for the visualization in https://covid19chart.org/)

**Comment by itsgorain** [comment]
Is there a reason why the US state-level data dried up all at once?

**Comment by Siphon880gh** [comment]
John Hopkins University stopped reporting US state-level information since 3/24/20. So good luck.

**Comment by PySimpleGUI** [comment]
+1 the request for time series for US by state

[My code](https://github.com/PySimpleGUI/PySimpleGUI-COVID19) currently uses the single time series data file that has worldwide data.  

[This site's time series graph by state](https://covid19chart.org/#/?top=53) is able to show time series by state by reading each of the individual [daily reports](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) and aggregating the data.  
![image](https://user-images.githubusercontent.com/46163555/77895167-610ff600-7244-11ea-9041-88023c18ddeb.png)

It is quite inefficient as each time the report runs it's reading each data file.

- [ ] Maybe someone could automate the creation of the US Time Series By State CSV using the individual files and then posting the results on their GitHub?

**Comment by rks125** [comment]
> +1 the request for time series for US by state
> 
> [My code](https://github.com/PySimpleGUI/PySimpleGUI-COVID19) currently uses the single time series data file that has worldwide data.
> 
> [This site's time series graph by state](https://covid19chart.org/#/?top=53) is able to show time series by state by reading each of the individual [daily reports](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) and aggregating the data.
> ![image](https://user-images.githubusercontent.com/46163555/77895167-610ff600-7244-11ea-9041-88023c18ddeb.png)
> 
> It is quite inefficient as each time the report runs it's reading each data file.
> 
> * [ ]  Maybe someone could automate the creation of the US Time Series By State CSV using the individual files and then posting the results on their GitHub?

I have been providing exactly what you are looking for, for the past 5 days. I provide a state level CSV and county level CSV in the time series format. You can choose to use if you like. 

https://www.soothsawyer.com/john-hopkins-time-series-data-confirmed-case-csv-after-march-22-2020/?github=pysimplegui

**Comment by PySimpleGUI** [comment]
> I have been providing exactly what you are looking for, for the past 5 days. I provide a state level CSV and county level CSV in the time series format. You can choose to use if you like.

Yea, I saw a post about that, but it is missing historical data which is really important for the analysis I'm doing and the types of visualizations I'm providing.

If you add the historical info I'm certainly interested so lemme know if that happens at some point.

**Comment by rks125** [comment]
@PySimpleGUI, it has all the historical data from John Hopkins. I’m not sure what other data you are searching for?

**Comment by PySimpleGUI** [comment]
OH!  OH!!  Nevermind!! I got it wrong... Sorry about that.  Totally misunderstood.

This is fantastic. I'll be writing another program for this dataset then.  Thank you for doing this and getting the word out about it.

I'll need to aggregate the country data into my own state totals I would assume.  I didn't see anything that was only states.  Not a big deal as that's what I do for the worldwide stuff too (sum up the provinces).

**Comment by rks125** [comment]
@PySimpleGUI, if you are trying to total up countries, I have just been grouping by country in my query. The way the data is setup by John Hopkins is the total of all rows is “accurate”; there is no overlap. So, you generally want to group by what you are after. For example, if you want country data the group by that column. 

I also provide a US county level (along with all other country data) version of the file if for some reason you want to go down to that level. However, there were a period of dates mid-March where John Hopkins did not provide county data.
