### ISSUE TITLE
How to get daily time series Recovered numbers now (after 3/23/2020)?

### ISSUE THREAD

**Issue by KeulRalf** [CSSEGISandData/COVID-19#1512]
We love your service and your data!! We use it for demo and education purposes.

With the recent change and depreciation of daily data series I see we can still access daily time series for confirmed and deaths here as they include data for timestamp 3/24/20220
time_series_covid19_confirmed_global.csv
time_series_covid19_deaths_global.csv

What about recovered? Any chance we get those?
We found the most valid KPI is active = confirmed-deaths- recovered and I currently see no chance to get it.

Can you please provide those.
Really appreciate you doing a great job on the data side!
Thank you so much
Ralf

**Comment by osrodas007** [comment]
> We love your service and your data!! We use it for demo and education purposes.
> 
> With the recent change and depreciation of daily data series I see we can still access daily time series for confirmed and deaths here as they include data for timestamp 3/24/20220
> time_series_covid19_confirmed_global.csv
> time_series_covid19_deaths_global.csv
> 
> What about recovered? Any chance we get those?
> We found the most valid KPI is active = confirmed-deaths- recovered and I currently see no chance to get it.
> 
> Can you please provide those.
> Really appreciate you doing a great job on the data side!
> Thank you so much
> Ralf

Hope we can get access soon!

**Comment by ttobis** [comment]
I have the same question. 
IS there a plan to add file  csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv in the near future?

**Comment by cipriancraciun** [comment]
@KeulRalf In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.

**Comment by KeulRalf** [comment]
Thank you for the support. To clean things up I'm closing this one and refer to [#1282](https://github.com/CSSEGISandData/COVID-19/issues/1282) which consolidates the discussion on recovered.
