### ISSUE TITLE
Issue with the last three rows of the data

### ISSUE THREAD

**Issue by rehanzfr** [CSSEGISandData/COVID-19#1519]
It seems that something with "Recovered" is present in the last three rows of confirmed and Death CSVs. Moreover, whether reporting on Recovered data is still in progress or deprecated after changing the names to new?

**Comment by lkounadis** [comment]
Yeah that seems like it shouldnt be there. could you please fix?

**Comment by auf-rd** [comment]
There are lots of errors/wrong numbers revealed at every new dataset published. 
But as a statistician i have never seen a clean dataset...

**Comment by DavidMulder0** [comment]
Yeah, the `Recovered, Canada` one threw me for a loop as well.

**Comment by rehanzfr** [comment]
Issue is resolved 8 hours ago.
