### ISSUE TITLE
1st confirmed case in New Zealand

### ISSUE THREAD

**Issue by UXVirtual** [CSSEGISandData/COVID-19#152]
Are you able to update the data to include a now confirmed case in Auckland, New Zealand on 28th Feb. Here is the link to the source announcement from New Zealand's Ministry of Health: https://www.health.govt.nz/news-media/media-releases/single-case-covid-19-confirmed-new-zealand and here is the official status page for up-to-date figures: https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus

**Comment by CSSEGISandData** [comment]
Thanks! That case has been added to our database.
