### ISSUE TITLE
Data for India not updating (time series)

### ISSUE THREAD

**Issue by InnoCentCoder5497** [CSSEGISandData/COVID-19#1530]
The data for India is not updated for the time series report, data does not contain updated columns for March 24, 2020.
Also state wise data for Indian cases is present at: https://www.mohfw.gov.in/

Please include.

**Comment by Bmr55** [comment]
If you are referring to 
`time_series_19-covid-Confirmed.csv`
It has been deprecated. Please read #1250

**Comment by InnoCentCoder5497** [comment]
> 
> 
> If you are referring to
> `time_series_19-covid-Confirmed.csv`
> It has been deprecated. Please read #1250

Ok Thanks.
