### ISSUE TITLE
Comma inside Strings causing troubles while parsing

### ISSUE THREAD

**Issue by aseemsavio** [CSSEGISandData/COVID-19#1536]
There are commas inside strings eg. **"Korea, South", "Kitsap, WA", "Solano, CA"** inside the following files: **time_series_covid19_confirmed_global.csv** and **time_series_covid19_deaths_global.csv** under County/Region. This is causing serious troubles while parsing the files programmatically.

**Comment by JiPiBi** [comment]
Pls what are your tools ?
No issue like that with python and pandas

**Comment by peterdrier** [comment]
@aseemsavio  Sorry, but this is CSV 101 level stuff.  If it's quoted, it's not a separator.  That's in the definition for CSV.  Find better tools or improve your code.
