### ISSUE TITLE
column names for daily reports are inconsistently labelled

### ISSUE THREAD

**Issue by davidlyon3** [CSSEGISandData/COVID-19#1539]
==> 03-20-2020.csv <==
Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude

==> 03-21-2020.csv <==
Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude

==> 03-22-2020.csv <==
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key

==> 03-23-2020.csv <==
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key

==> 03-23-2020.csv <==
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key

Who's creating these files???

**Comment by nguinasso** [comment]
It appears the starting March 22 they changed the format to allow US county reports. (added Admin2 column). The also changed the periods in the column names to underscores. 
Somebody please modify the COVID-19/csse_covid_19_data/README.md data file and tell us whether they plan to change the older data to this format.

**Comment by Lucas-Czarnecki** [comment]
I've created a tidy repo that updates JHU data while keeping a consistent naming schema. You can find it [HERE](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE) if you are still bothered by this issue. 

Consider closing this issue as a way to help JHU from being overwhelmed with these requests.
