### ISSUE TITLE
Is Github Data Up-To-Date?

### ISSUE THREAD

**Issue by GnubiBORED** [CSSEGISandData/COVID-19#154]
Just discovered now this github but i see that isnt up to date or that dasboard takes info before or from other sittes no? For example now in dashboard you can see in spain 25  cases total, 2 recovered 23 existing, and i cannot find that info inside last csv from github data.

Am i looking wrong or?

**Comment by emmanio** [comment]
Looks like the dashboard takes info from: ```https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/2/query?f=json&where=Confirmed%20%3E%200&outFields=*&orderByFields=Confirmed%20desc```

that will give you the latest data if you pop it into postman.

**Comment by GnubiBORED** [comment]
Is that a api? seems so, you know what it is for get docs?

**Comment by timmmGZ** [comment]
probably not up to date, since some countries' offcial data are fake too...

**Comment by CSSEGISandData** [comment]
In readme, we mention that the Github daily report is maintained once a day, and the dashboard is updating about every 15 min. Thanks.
