### ISSUE TITLE
03-24-2020.csv has records for 2/23/20 ????

### ISSUE THREAD

**Issue by davidlyon3** [CSSEGISandData/COVID-19#1545]
Why does the file in the daily updates for 2/23/20 ????

  |   | Qinghai | China | 2/23/20 11:19 | 35.7452 | 95.9956 | 18 | 0 | 18 | 0 | Qinghai, China
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | Tibet | China | 2/23/20 11:19 | 31.6927 | 88.0924 | 1 | 0 | 1 | 0 | Tibet, China

**Comment by StateCenterKid** [comment]
I believe that is the last date that the record changed, you will see several cases like this in the dataset.  I've resorted to using the datetime that the file was created as the date for each record.

**Comment by peterdrier** [comment]
The column is called Last Update.  One might infer that it's the time in which the data for that row was most recently updated...  If data isn't updated every day, because maybe it hasn't changed in Tibet, then it wouldn't shock me to see a date from a previous day.
