### ISSUE TITLE
Recovered-Data 

### ISSUE THREAD

**Issue by bumbeishvili** [CSSEGISandData/COVID-19#1546]
Can't you just copy yesterday's recovered data from Worldometers and mention them as a source?

https://www.worldometers.info/coronavirus/

They have sources listed

**Comment by cipriancraciun** [comment]
@bumbeishvili In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.

**Comment by bumbeishvili** [comment]
I will

Regarding issue mentioned in this ticket - I started doing it by myself

https://github.com/bumbeishvili/covid19-daily-data

I guess I will no longer be using this repo, I can't count how many times I had to modify code.
