### ISSUE TITLE
Tenerife data missing?

### ISSUE THREAD

**Issue by redman684** [CSSEGISandData/COVID-19#155]
AFAIK there are now 4 confirmed cases on Tenerife, but the map shows none.
Maybe these are added to the count for Spain? Although Tenerife is a Spanish island, it is 1300-2100 km from Spain and on a different continent.

**Comment by PaFiK1999** [comment]
Also 3 confirmed cases in Denmark

**Comment by redman684** [comment]
My issue was not so much about missing data for a country (I don't know how recent the Denmark cases are, I believe 1 day when PaFiK1999 commented?), but more that data for Tenerife (4 days after contamination at the time I opened the issue) probably is in the databases somewhere, but displayed as part of the (mainland) Spanish cases.

**Comment by PaFiK1999** [comment]
My apologies for misreading :)

**Comment by CSSEGISandData** [comment]
We have grouped those cases in with Spain's confirmed case count.
