### ISSUE TITLE
Issue in the data in time_series_covid19_confirmed_global.csv

### ISSUE THREAD

**Issue by mustafasaifee42** [CSSEGISandData/COVID-19#1554]
The data is **3/21/202** instead of **3/21/20**. Can you please change it to **3/21/20**

**Comment by seedjay1** [comment]
What he means is change it to 3/21/20.

 :)

**Comment by mwargan** [comment]
Confirmed this is an issue. Though needs to be changed to 3/21/20

**Comment by ODrying** [comment]
@CSSEGISandData Problem with date. 3/21/202 - should be 3/21/20

**Comment by mneira10** [comment]
The issue seems to have been solved. Thanks!

**Comment by mustafasaifee42** [comment]
Closing this since solved
