### ISSUE TITLE
The map can prefer city names over country names

### ISSUE THREAD

**Issue by redman684** [CSSEGISandData/COVID-19#156]
When zooming, for several countries the country name disappears while city/state names remain. And at both higher and lower zoom levels the country names is shown.
At certain zoom levels Italy can be shown as "Milan" and "Rome", while the label "Italy" is missing. Zoom out further and is shows only "Italy".
The UK can show "London", "Birmingham" and even "Leeds", but not "United Kingdom".
The USA has a zoom level where only the names of the state are shown, while one zoom level higher and lower "United States" is shown.

**Comment by CSSEGISandData** [comment]
Good suggestion, but this is a baseman issue, out of our scope. One workaround is to switch to another basemap on the upper right corner of the map. Thanks!
