### ISSUE TITLE
Better Data Source Alternatives?

### ISSUE THREAD

**Issue by Headline** [CSSEGISandData/COVID-19#1580]
Hello everyone,

I'm looking for an alternative to source data from that is consistent and non-breaking. I was excited to build graphs using their data; but since the recent breakage and at least an hour and a half of wasted time I have realized that their daily report information that they switched us to is poorly organized and formidably inconsistent.

I expected Johns Hopkins CSSE to be able to design a system such that it allows parsing to be a trivial task, but it seems this project has failed. If anyone knows any better sources please let me know!

**Comment by jesusmcaro2** [comment]
https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/ 

You'll see a "Download Data" link in the middle of the article.

**Comment by gjbdebug** [comment]
Headline: took the words out of my mouth.
jesusmcaro2: Thank you.

**Comment by ExpDev07** [comment]
I totally agree on the parsing part. While I'm happy that they added back recoveries, the indexing does not match (in confirmed and deaths, Norway is on line/index 177, however, in recovered, it's on 175). Also, in recoveries, while not visible, the `Province/State`` key-name has a leading ``\ufeff`` (``\ufeffProvince/State``), again, breaking parsers.

**Comment by mvanmidd** [comment]
https://coronadatascraper.com/ provides better data, with a more active developer community. They also provide a variety of format, including a "JHU-like" CSV.

**Comment by mdibenigno** [comment]
This one also seems promising... https://covidtracking.com/

**Comment by Fredo-XVII** [comment]
You could also try datahub.io/core/covid-19.  There data is based on jhu
but it's cleaned up and combined.

**Comment by sagarkulkarny** [comment]
> https://coronadatascraper.com/ provides better data, with a more active developer community. They also provide a variety of format, including a "JHU-like" CSV.

This is a really good source for global data. Thank you @mvanmidd

**Comment by muneneg** [comment]
I am currently using https://data.world/covid-19-data-resource-hub/covid-19-case-counts/
Pros:
- You can be able to transform the data using a query.
- Gives you a live link to your query results.
- Can connect with Python, R and Tableau.

**Comment by JordanMarr** [comment]
> https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/
> 
> You'll see a "Download Data" link in the middle of the article.

I created a report using this link last night, and today's version has a stray "," at the end of the header row that broke my report already.

**Comment by jmoldon** [comment]
I moved my scripts to use the data from this repo a couple of days ago:

https://github.com/ulklc/covid19-timeseries
for the moment I'm happy with it. Thank you for the other suggestions posted in this issue.
