### ISSUE TITLE
Data issues on 23rd March 2020 and missing  on 25th March 2020 Recovered CSV

### ISSUE THREAD

**Issue by samscodes** [CSSEGISandData/COVID-19#1589]
Hello guys , 
thank you for the work you put in, to provide us with this data without any cost to us. 
I just wanted to inform you that their is some data issue on 23-March-2020  where the previous day Recovered value is repeated from 22-March-2020 throughout all countries. And on 25-22-2020 the recovered value is missing.

Also if its possible may you guys load back the US , States Names and data back to the current files as everything was working perfectly with the old files that contained the US States names and data?

Thank in Advance.

**Comment by sorxrob** [comment]
Whoever manages the data of this repo is useless.

**Comment by bumbeishvili** [comment]
I started my own data building because they will no longer provide recovered data

Check it here

https://github.com/bumbeishvili/covid19-daily-data

**Comment by sorxrob** [comment]
> I started my own data building because they will no longer provide recovered data
> 
> Check it here
> 
> https://github.com/bumbeishvili/covid19-daily-data

Hi, this data is ready to use for production? thanks

**Comment by bumbeishvili** [comment]
I am using it here - http://coronavirus.davidb.dev/

Please also read the description, I changed some country names, in the long plan I want to add ISO country codes, instead of relying on country names

**Comment by sorxrob** [comment]
> I am using it here - http://coronavirus.davidb.dev/
> 
> Please also read the description, I changed some country names, in the long plan I want to add ISO country codes, instead of relying on country names

Oh, saw this on reddit. nice job

**Comment by sorxrob** [comment]
> I am using it here - http://coronavirus.davidb.dev/
> 
> Please also read the description, I changed some country names, in the long plan I want to add ISO country codes, instead of relying on country names

So this is fully worldometer based right?

**Comment by bumbeishvili** [comment]
@sorxrob data before 23 March is based on this repo, data after 23 March is based on Wolrdometers
