### ISSUE TITLE
Diamond Princess data changed?

### ISSUE THREAD

**Issue by gpn01** [CSSEGISandData/COVID-19#159]
Checking confirmed cases, the numbers for the US cases that are flagged as from Diamond Princess but at specified locations have gone down to zero from 24th Feb.

![image](https://user-images.githubusercontent.com/33544819/75554158-b5e80300-5a31-11ea-943a-e5e5bf23983b.png)

**Comment by whimsql** [comment]
Just a thought... maybe they have recovered? 
It does seem weird that all 18 recovered overnight.

**Comment by gpn01** [comment]
I did check the recovered (and Deaths) data too.  Nothing there although there was one recovered that went away for a few days!
![image](https://user-images.githubusercontent.com/33544819/75567479-87762200-5a49-11ea-8d24-5b375da7a27f.png)

**Comment by AssureHSC** [comment]
The US repatriated cases appear to have been moved back to Japan... 

![2020-02-29_14-43-04](https://user-images.githubusercontent.com/61626466/75609930-b7cec680-5b04-11ea-8d54-859770326d27.png)

I think that these cases should be shown either at the physical locations in USA or as a group at country level.

**Comment by CSSEGISandData** [comment]
Those cases were merged to "Unassigned Location (From Diamond Princess), US". Thanks!
