### ISSUE TITLE
Crowdsourcing data collection -- calling for volunteers

### ISSUE THREAD

**Issue by dawenx** [CSSEGISandData/COVID-19#160]
I really like and appreciate what @iceweasel1 is doing for Germany: whenever there's news update, a post is added, e.g., https://github.com/CSSEGISandData/COVID-19/issues/126#issuecomment-592561745 

Just a thought: maybe we can have a couple volunteers, one for each country, especially for South Korea, Italy, Iran, etc. We can use this issue for future updates, or open different issues, one for a country. Note that this does not meant to replace getting data from the official channel, but as we all known, the official channel sometime is quite slow.

What do you all think? Any volunteer for those 3 countries I mentioned? For other countries?

**Comment by CSSEGISandData** [comment]
We will ask for volunteers when necessary, but not at this moment. Thanks for promoting it.
