### ISSUE TITLE
Israeli confirmed case number isn't precise

### ISSUE THREAD

**Issue by ronikar** [CSSEGISandData/COVID-19#1601]
Your dataset doesn't match with the data provided by the `Israeli Health MInistry`

**Comment by navmedvideos** [comment]
Coronavirus Live Stream - Real-time counter, Maps, and worldwide stats.

https://www.youtube.com/watch?v=qTbR2UKTQQc

**Comment by ronikar** [comment]
@navmedvideos I am looking for open source dataset :(
