### ISSUE TITLE
Direct link to graph images if anyone wants.

### ISSUE THREAD

**Issue by w3goodies** [CSSEGISandData/COVID-19#1613]
https://corona.dnsforfamily.com/graph.png?c={2-Letter-Country-Code}

For example: 
https://corona.dnsforfamily.com/graph.png?c=CN

Images are updated each day once.
I am using this for my Telegram channel. If anyone also wants to use it, they can go ahead.

**Comment by DavidAWest** [comment]
@w3goodies Thanks for sharing this.  You might consider giving the charts a title and label the vertical axis.  "New Cases Reported" or something like that.  People might be led to believe this is the cumulative total otherwise.

**Comment by w3goodies** [comment]
@DavidAWest Thanks for the suggestion. I updated the chart labels to: "Confirmed cases per day" and "Deaths per day" to clarify to users that the data is not cumulative.
