### ISSUE TITLE
csse_covid_19_daily_reports/02-21-2020.csv contains incorrect data for Ashland, NE

### ISSUE THREAD

**Issue by alurpal** [CSSEGISandData/COVID-19#162]
The 2-21-20 csv is showing 11 confirmed for Ashland, NE, US:

"Ashland, NE",US,2020-02-21T23:23:06,11,0,0

It's unfortunate that this is not the actual dataset used by the dashboard.

**Comment by CSSEGISandData** [comment]
Those cases were merged to "From DP, US". Thanks

**Comment by alurpal** [comment]
Thanks for all your work on this!
