### ISSUE TITLE
Please Update data. Should be accurate.

### ISSUE THREAD

**Issue by web-sys1** [CSSEGISandData/COVID-19#1625]
Coronavirus cases has increased up at 493,650. Death toll rise to 22,202.

![screencapture-www-worldometers-info-coronavirus-1585237102326](https://user-images.githubusercontent.com/61905565/77666543-c2587080-6f89-11ea-9da0-5c67c9d0d9e3.png)

**Comment by web-sys1** [comment]
https://www.worldometers.info/coronavirus/

**Comment by peterdrier** [comment]
The data files are updated every night around 0 UTC.  Your opening an issue isn't so much helpful.  If you had a particular point where you knew the data was wrong, that might help.. But saying the aggregate is wrong, please update..  Well, you're likely to get ignored.

**Comment by web-sys1** [comment]
close issue
