### ISSUE TITLE
Which time series file location to download?  

### ISSUE THREAD

**Issue by cgarai** [CSSEGISandData/COVID-19#1626]
What is the correct url to download from?  When I go to

COVID-19/csse_covid_19_data/csse_covid_19_time_series/
and copy the link for a series such as:

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

I get errors when reading with Python/Pandas.  

If I instead click on the above link and then click the RAW button I get this url:
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Python/pandas doesn't seem to have a problem with it.  

What is the difference between these two files?
Thanks,
Chris

**Comment by skr47ch** [comment]
First one is the gihub page.
Second one is the csv file embedded in the page. You don't want the whole page, just the csv.

Don't be fooled be the .csv extension

**Comment by cgarai** [comment]
I just figured that out.  Sorry for the dumb question and thanks for the prompt answer!
