### ISSUE TITLE
Is it ok to develop a WordPress plugin based on your data?

### ISSUE THREAD

**Issue by muhammedmagdi** [CSSEGISandData/COVID-19#1634]
Hi,
I would like to ask about if it is ok to develop premium WordPress plugin that use the data from Johns Hobkins and present it in different visualizations like maps and charts.
I am asking because it is mentioned on Github repo that the data shouldn't be used in commercial purposes but when I asked some developers, they said that the university means the data itself shouldn't be used as a product for commercial purposes and what I will do is manipulation on this data to have different visualizations. So is this permitted?
Another question please, it is mentioned on Github repo that Worldometers is one of the data sources that the university use, I actually tried to contact Worldometers a lot to ask them about the permission of scrapping the data from their site but no response.
After I have seen Worldometers as one of the sources that the university use in Github repo, I feel a little bit in the safe side if I am scrapping the live data from them. Can you please confirm that?
Thanks a lot!

**Comment by nguyandy** [comment]
Hi @muhammedmagdi,
I'm not going to provide an answer for your question, but provide insight on this data set instead.

I develop https://trackthevirus.info/ or previously https://covid19.nguy.dev.
This started off as a fun little side project for me that ended up blowing up and  getting lots of traffic. I provide in-depth charts and analysis tools for the data that Johns Hopkins provides. I have received much support in words and in monetary donations for the work that I've done, that being said, I feel very lucky to be given the opportunity to work on a project that provides me with a personal feeling of purpose and fulfillment. 

However if I had to chance to go back, I don't think I would do it again, at least with Johns Hopkins data set. They consistently and continuously, without fail, update, change, alter, or make mistakes when reporting the data. 

What started as a side project now seems like a full time job. Always, constantly having to make changes and fix when they suddenly to decide to do something different. 

If you reach a large amount of users, you have the responsibility to provide consistent, credible and  accurate data. Unfortunately, JHU is unable to do this at the time.

Please don't misunderstand my post. JHU is doing a great service by providing this dataset, I am grateful for work they have done, and the data that they provide. But the dataset is simply unreliable, and at the end of the day, YOU are the one that will be responsible for cleaning up their mess.
