### ISSUE TITLE
Do 'confirmed cases' discount recoveries and deaths?

### ISSUE THREAD

**Issue by visez** [CSSEGISandData/COVID-19#165]
Quick question: is the number of confirmed cases for a given day the number of people infected on that day, or is it simply the total number of cases until that day?

**Comment by StarterCraft** [comment]
The first option.

**Comment by CSSEGISandData** [comment]
Existing cases = total confirmed - total recovered - total deaths. Hope that helps

**Comment by visez** [comment]
Thank you - that clarifies it for me
