### ISSUE TITLE
US state data

### ISSUE THREAD

**Issue by john-h-carson-jr** [CSSEGISandData/COVID-19#1651]
Where has the US state data moved to? and is county data somewhere accessible?

**Comment by bfosten** [comment]
The raw U.S. state data is still in [csse_covid_19_data/csse_covid_19_daily_reports](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports), but it's not as easily accessible as it used to be.

To help ensure that it's always easily accessible, we've set up a new repo, [CovidAPI](https://github.com/coviddata/covid-api). It provides the data from this Johns Hopkins repo but provides it in a stable format that includes daily statistics by states/provinces (see [Regions](https://github.com/coviddata/covid-api#regions)). It also includes data for counties and cities (see [Places](https://github.com/coviddata/covid-api#places)).

**Comment by jcampos8782** [comment]
See the only pinned issue on this repo:
https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by cipriancraciun** [comment]
I have built a derived dataset based on JHU dataset, where (among other fixes and features) I also aggregate the data for US at both state and country level, and merge everything in a single dataset for easy usage:

* https://github.com/cipriancraciun/covid19-datasets
* I have described it in this issue #1281 or the readme in the repo above;

(I try as much as possible not to change the format too much, mainly I only add new rows and columns.)

**Comment by john-h-carson-jr** [comment]
Thank you very much! I've built a solution in R.

John H. Carson Jr, PhD
Senior Statistician


1435 Garrison Street, Suite 201
Lakewood, CO 80215
Phone: (720) 746-1803 x 1028
Fax: (720) 746-1605
Mobile: 419-721-4173


*Confidentiality Statement This message is intended only for the use of the
addressee and may contain information that is privileged and confidential.
If you are not the intended recipient, dissemination of this communication
is prohibited. If you have received this communication in error, please
erase all copies of the message and its attachments and notify us
immediately.*

**Comment by cipriancraciun** [comment]
@john-h-carson-jr if you've successfully used the derived dataset (or any other dataset), and in order to help the JHU team, would you consider closing this issue.
