### ISSUE TITLE
Number of deaths on Diamond Princess File 02-28-2020.csv

### ISSUE THREAD

**Issue by MerliMomo** [CSSEGISandData/COVID-19#166]
Good Morning
Thankyou for all the work you are doing. I have noticed the Deaths on Diamond Princess have dropped from 4 to 1 in today's csv file 02-28-2020.csv. What happened to the other 3 deaths?

**Comment by CSSEGISandData** [comment]
Sorry, that's a typo. It has been updated in the dashboard. Will be updated in the csv file.
