### ISSUE TITLE
Death Time series cumulative or per day?

### ISSUE THREAD

**Issue by Mopholo** [CSSEGISandData/COVID-19#1678]
Looking at some countries the data seems to accumulate, in others it seems to be per day.

Even in the US dataset the first two columns to register deaths have a 1 followed by a 1 in the next column, so clearly not cumulative, but by the end it clearly shows total deaths in the last column. 

This dataset seems to be riddled with errors and seems to be unreliable at present, other than total deaths in the last column, but I am not even sure about that. 

Looking at previous datasets these numbers were not cumulative, nor should they be in my opinion 

What the heck is going on?

**Comment by cipriancraciun** [comment]
The confirmed, deaths and recovered values are cumulative.  (I.e. for that location by that date the total number of reported cases/deaths/recoveries is that given value;  thus if the value for two consecutive days is the same, nothing new was reported.)

Indeed there are inconsistencies in the data, sometimes the number goes down (i.e. the delta becomes less than zero).

**Comment by Mopholo** [comment]
Yeah figured that out about 1 second after posting, I should ban myself from early morning github issues, I will just wait for the us files and calculate daily’s myself
