### ISSUE TITLE
Error in the system - Azerbaijan is listed twice

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#168]
A mistake has crept in. Azerbaijan is displayed twice. I don't know if it'll be counted twice.

![dfsdf](https://user-images.githubusercontent.com/49625256/75599816-dacb8d00-5aa8-11ea-87ef-7089632387ad.PNG)

**Comment by CSSEGISandData** [comment]
Thanks! We have removed the duplicate in the dashboard. CSV file will be updated as well. Thanks!

**Comment by iceweasel1** [comment]
Wonderful. Always happy to. I close the issue.

**Comment by jrevillas** [comment]
@CSSEGISandData I think #167 would fix the CSV files.
