### ISSUE TITLE
Covid19 - Detailed global -country - region - county Covid 19 incident patient data - where?

### ISSUE THREAD

**Issue by mdiga04** [CSSEGISandData/COVID-19#1681]
Most of the Covid19 data (outside US and China) seem to be at the country level. Is there any data source available with higher granularity data global -country - region - county. Monitoring the incidence at the county (not only country) level could give a lot of insights. 
Is there any organization / entity collecting this granular data level?

**Comment by JiPiBi** [comment]
see #1677 , some sites give more data for their own country and at a region level

**Comment by cipriancraciun** [comment]
I have built a derived dataset based on JHU dataset, where (among other fixes and features) I also aggregate the data for US at both state and country level, and merge everything in a single dataset for easy usage:

* https://github.com/cipriancraciun/covid19-datasets
* I have described it in this issue #1281 or the readme in the repo above;

(I try as much as possible not to change the format too much, mainly I only add new rows and columns.)

**Comment by mdiga04** [comment]
Thanks a lot to both. I still did not see higher (needed) granularity at region or county level (except US and China). Any link to a repository with that kind of data is highly valued.

**Comment by JiPiBi** [comment]
Look at #1677

**Comment by cipriancraciun** [comment]
@mdiga04 the major issue with such a dataset is that none of the large health organizations (WHO, CDC, ECDC) do not provide such a dataset, and unfortunately the countries themselves don't publish this either.

As an exercise try to find an official document listing all the numbers for Italy, at least by region and date.  (I've just superficially checked their ministry of health site, and besides a PDF with the current situation, nothing is in machine readable format.)

Thus unless people are willing to help in building such a dataset, it will not exist.

(BTW, some countries, like unfortunately my own country Romania, have made a policy of not publishing any numbers except at country level.) :(

**Comment by JiPiBi** [comment]
@cipriancraciun
 have you read the data in the sites linked in #1677 ?

**Comment by cipriancraciun** [comment]
@JiPiBi I was just inspecting it and I've replied on the other issue.

**Comment by oltdaniel** [comment]
@mdiga04 There are dozens of sources that have not a single upfate interval time nor format. So merging all into one requires much manual work and result in commit delays.

**Comment by JiPiBi** [comment]
Perhaps,  WHO will before the next pandemics, propose a common data scheme  to be applied in the datasets all over the world......

**Comment by mdiga04** [comment]
@JiPiBi - I completely agree. It seems that this pandemic took everyone by surprise (WHO, governments, epidemiologists etc.) That is the big surprise. Unless this is done on purpose which I hope is not the case. 
In the meantime I was only asking myself what the community can do.

**Comment by oltdaniel** [comment]
@mdiga04 I think this issue is resolved. Please close.

**Comment by mdiga04** [comment]
Issue is far from solved - if you understand it. But I will close it.
