### ISSUE TITLE
Covid-19 related Zoom meetups

### ISSUE THREAD

**Issue by yaniv256** [CSSEGISandData/COVID-19#1695]
Post if you know of one.

**Comment by yaniv256** [comment]
Interested in exploring the #covid19 daily updated data from #johnshopkins? Join the Twin Cities Deep Learning Study Group Zoom meetup, today at 6 pm CDT.

https://www.meetup.com/Twin-Cities-Deep-Learning-Study-Group/events/269640013/

**Comment by oltdaniel** [comment]
@yaniv256 Please close now. This is no relevant to the raw data provided here. PLEASE CLOSE NOW.
