### ISSUE TITLE
Use ISO 3166-1 alpha-3 country codes

### ISSUE THREAD

**Issue by nc-at-sp** [CSSEGISandData/COVID-19#17]
https://unstats.un.org/unsd/tradekb/knowledgebase/country-code

It will make data overlay into other systems much easier, especially when correlating with travel document information.

**Comment by CWrecker** [comment]
Yup, I have implemented a conversion too. If you would like the source code let me know.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We have agreed on our current data structure. Thank you for the suggestion and sorry for the inconvenience.
