### ISSUE TITLE
China summary missing

### ISSUE THREAD

**Issue by mortenbache** [CSSEGISandData/COVID-19#1702]
As the only country(?) China has no "blank" in provinces summarizing the country. Could this please be made, otherwise there is no consistency.

**Comment by cipriancraciun** [comment]
Although I'm not affiliated with the JHU team, I assume that the JHU conceived these datasets as inputs for others, thus the least duplication of data is actually useful as it keeps things simpler to check.

Moreover given there are already opened several issues on the topic of data summarization, like #1681, would you consider closing this ticket and following the other one.  (This would help the JHU team, as they are already swamped in tickets.)

----

That being said, I have built a derived dataset based on JHU dataset, where (among other fixes and features) I also aggregate the data for China, US and all the other countries, and merge everything in a single dataset for easy usage:

* https://github.com/cipriancraciun/covid19-datasets
* I have described it in this issue #1281 or the readme in the repo above;

(I try as much as possible not to change the format too much, mainly I only add new rows and columns.)

**Comment by mortenbache** [comment]
Thanks, I tried to find it before opening a ticket. I echo your frustrations about molding this data set into something useful. Man, it is a lot of work.
