### ISSUE TITLE
No Confirmed Cases/Deaths US Data:  COVID-19 time_series data (03/27/20)

### ISSUE THREAD

**Issue by Anna1077** [CSSEGISandData/COVID-19#1704]
In a recent response, it was reported that recovered cases will no longer be reported.  Will we have access to confirmed cases and deaths?  I tried to pull the data today twice (once at around 8am Mountain time and then at around 12:15pm).  Both data files show no data for US.  Any information on this will be greatly appreciated?  Thanks

**Comment by cipriancraciun** [comment]
In order to keep things tidy, and help the JHU team (which are swamped by tickets), would you consider closing this issue, and following #1282 which already has some discussion on the topic, and lists to at least a 10+ other duplicate items.

**Comment by Anna1077** [comment]
In looking at that thread I see lots of reference to "recovered" cases.  My inquiry is not however on recovered cases, but rather "confirmed" cases which are 2 different data sets, so I do not want my question to get lost in that thread which seems focused to "recovered cases".

**Comment by cipriancraciun** [comment]
OK, for the combined datasets issue, how about #1681?

If you are referring to the `time_series` vs `daily_reports` datasets, I could also point you to #1509.

(In any case, there are countless issues opened, perhaps another one already holds the answer you are searching for?)

**Comment by Anna1077** [comment]
Thank you.  I went to some referenced here (for those looking, please see below) and will also check out the ones you have referenced, so closing this thread.  Thanks
https://github.com/CSSEGISandData/COVID-19/issues/1281
https://github.com/CSSEGISandData/COVID-19/issues/1692

https://github.com/cipriancraciun/covid19-datasets
