### ISSUE TITLE
Switzerland cases missing

### ISSUE THREAD

**Issue by AtomicNicos** [CSSEGISandData/COVID-19#171]
Missing cases in Switzerland, current number is 21 instead of 8 today, and yesterday was 14.

[Link](https://www.swissinfo.ch/eng/covid-19_switzerland-confirms-second-coronavirus-case/45582788)

**Comment by CSSEGISandData** [comment]
Our current data is 18. Will update once got any official report. Thanks.

**Comment by zdavatz** [comment]
The data only for Zürich (Switzerland) can be found here: https://opendata.swiss/dataset?q=covid&sort=score+desc%2C+metadata_modified+desc
