### ISSUE TITLE
Incorrect deaths reported in Australia

### ISSUE THREAD

**Issue by StormBurpee** [CSSEGISandData/COVID-19#1715]
Hi you've reported 212 deaths in NSW today, I believe you may have meant to do that for recoveries.

**Comment by Gromaxius** [comment]
Australia / States / Deaths
Apparently the latest daily increments have been erroneously been filled into the database as deaths. Total number of deaths: officially 14.

**Comment by StormBurpee** [comment]
For what it's worth I've been trying to keep my site here https://track-coronavir.us/countries/Australia manually updated whilst the fields have been entered incorrectly.

**Comment by Gromaxius** [comment]
Thanks mate! My best wishes to you.Cheers, OA.

    On Saturday, 28 March 2020, 07:49:24 pm AEDT, Storm Burpee <notifications@github.com> wrote:  
 
 


For what it's worth I've been trying to keep my site here https://track-coronavir.us/countries/Australia manually updated whilst the fields have been entered incorrectly.

**Comment by BenAveling** [comment]
"Of the 3,635 confirmed cases in Australia, 14 have died from COVID-19"

https://www.health.gov.au/news/health-alerts/novel-coronavirus-2019-ncov-health-alert/coronavirus-covid-19-current-situation-and-case-numbers

**Comment by jodal2** [comment]
Are the errors only for Australia? I had been relying on this source. The number of Australian deaths is way overstated: 460 instead of 14

**Comment by tobiasl-sportsbet** [comment]
@jodal2 It looks to be. I went through a number of the deaths for sub-national districts, mostly in the US, and they look fine.

**Comment by StormBurpee** [comment]
This looks like this has been corrected now. Closing.
