### ISSUE TITLE
Number columns ordered as string

### ISSUE THREAD

**Issue by VitorOSilva** [CSSEGISandData/COVID-19#1719]
The "Infected per million" and "Death per million" columns are been ordered as string so where order by descending, pex, the "Death per million" column returns like this:

Slovenia 4
Belgium 30

Testcase: Order "Infected per million" and "Death per million".

![2020-03-28_1249](https://user-images.githubusercontent.com/29599199/77823515-a4a71a80-70f3-11ea-9223-df170fbe50fb.png)
![image](https://user-images.githubusercontent.com/29599199/77823532-c0122580-70f3-11ea-8190-ad02c629ea95.png)

**Comment by cipriancraciun** [comment]
Where have you got the screenshots from?

(To my knowledge in this repository, the mentioned data does not exist, neither the visualizations.)

**Comment by VitorOSilva** [comment]
Hi,
I got it from here "https://epidemic-stats.com/" the redirect it to here thought you're the ones managing the site.

Thanks
