### ISSUE TITLE
Is there a issue in reading the updated csv's pulling up only html tags

### ISSUE THREAD

**Issue by prakmyl** [CSSEGISandData/COVID-19#1722]
![image](https://user-images.githubusercontent.com/6130871/77825616-6b40d000-7130-11ea-9dd8-d885397ba6a5.png)

getting the data just as per the attached screenshot

trying to read the data from the below url. all worked fine until the changes

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by prakmyl** [comment]
if i try read the data with header i get the following error

ParserError: Error tokenizing data. C error: Expected 1 fields in line 33, saw 2

**Comment by mskymoore** [comment]
Would be useful to know what pd is.  My code is written in python and all I had to do was change the urls, but the separator between the fields is a comma(","), not a tab("\t").

This is how I'm pulling the csv:

`a_csv_file = csv.DictReader(requests.get(csv_url).iter_lines(decode_unicode=True))`
`for row in a_csv_file:`
`...`

**Comment by skr47ch** [comment]
Use this -
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

This is raw csv

**Comment by Lucas-Czarnecki** [comment]
@prakmyl as skr47ch mentioned, you'll need to use the raw csv. You can find it here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

![JohnsHopkins_RAW2](https://user-images.githubusercontent.com/62263095/77828529-a1a32e80-70e1-11ea-8ebb-11c1583fd852.png)


**For R-users:** 
`library(readr)`
`csse_time28 <-read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"))`

**Comment by prakmyl** [comment]
Thanks all for your inputs

> @prakmyl Would be useful to know what pd is. My code is written in python and all I had to do was change the urls, but the separator between the fields is a comma(","), not a tab("\t").
> 
> This is how I'm pulling the csv:
> 
> `a_csv_file = csv.DictReader(requests.get(csv_url).iter_lines(decode_unicode=True))`
> `for row in a_csv_file:`
> `...`


> @prakmyl Would be useful to know what pd is. My code is written in python and all I had to do was change the urls, but the separator between the fields is a comma(","), not a tab("\t").
> 
> This is how I'm pulling the csv:
> 
> `a_csv_file = csv.DictReader(requests.get(csv_url).iter_lines(decode_unicode=True))`
> `for row in a_csv_file:`
> `...`


i am using pandas library in python to read the data, which is referred as pd

**Comment by prakmyl** [comment]
Thanks all for your inputs.. it worked for me when i used as raw. Have a great day and stay safe

**Comment by UjashLeuva** [comment]
@prakmyl Hey, How you did it? I am the same thing but got the same error on line 33 in python.

**Comment by prakmyl** [comment]
> @prakmyl Hey, How you did it? I am the same thing but got the same error on line 33 in python.

r'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
url_Death = r'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv'
url_Recovered = r'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'

try this that should fix used raw option as suggested that fixed
