### ISSUE TITLE
Hospitalizations and COVID test counts??

### ISSUE THREAD

**Issue by paolinic03** [CSSEGISandData/COVID-19#1725]
Hello fellow Data Scientists and Enthusiasts,

Would anyone know where I could find accurate and public data sources for US hospitalizations and testing counts related to COVID-19? I want to stop reporting these metrics I.e confirmed, active, recovered etc and report actual metrics that are reliable and could actually help us better understand the rate of infection and issues related to healthcare capacity.

Thank you in advance.

**Comment by rks125** [comment]
You might be looking for this:
https://covidtracking.com/

I pull their data directly from their google sheet so my data refreshes daily.

**Comment by oltdaniel** [comment]
@paolinic03 This repo is for worldwide data. And finding this kind of data for each country is hard. So on, this reuest would be denied. Please close, as there are no sources for worldwide cases with this type do not exist.
