### ISSUE TITLE
[Solution] Streaming the JHU Data

### ISSUE THREAD

**Issue by Mrc0113** [CSSEGISandData/COVID-19#1726]
It's awesome that JHU is providing this data and updating the repo throughout the day. Thank you JHU for doing this! 

If you would like to consume this data as a stream and filter which events you would like to receive you can check out this repo to learn more. It allows you to subscribe to events using open standards like mqtt, jms or amqp

https://github.com/SolaceLabs/jhu-covid19-stream-processors

**Comment by oltdaniel** [comment]
@Mrc0113 An issue is hee for an issue, not for ads or guest links. Please close now.

**Comment by Mrc0113** [comment]
Thanks for your concern and good point re: issues being for issues. I was initially following the pattern set by other issues in this repo that provide _Solutions_ that could be useful to the technical community trying to help out during this pandemic, but agree that is indeed not generally the proper use of a github issue.

This is definitely not meant to be an ad. The data streams are available for free and allow users to subscribe using open standards & apis to the same JHU data provided in this repo but in a more efficient way without having to poll JHU's Web Feature Service over and over again.  

That said, I'm closing this issue and have opened a PR. 
https://github.com/CSSEGISandData/COVID-19/pull/1912
