### ISSUE TITLE
Graph of percantage growth of Confirmed cases

### ISSUE THREAD

**Issue by CzarnyHetman** [CSSEGISandData/COVID-19#1733]
Hi,

I would like to issue an suggestion to add additional graph to the dashboard.
Right now there are Confirmed and Daily Increase tabs, what would be very useful would be to have additional graph called "Percentage Increase" or "Daily Percentage Increase" or "Daily Rate". This graph would show the procentage based on the formula:

percentage increase = ( (Daily Increase of this day ) / ( Confirmed from previous day) ) * 100 [%]

![Graph_with_Percentage_Increase](https://user-images.githubusercontent.com/57686355/77832737-7861bd00-7138-11ea-9bf3-aea8f5645ccf.png)

^ Yellow line on this example graph can give more understandable overview of the situation than both blue and red lines, because it tells if the exponential curve speeds up or slows down.

Thank You for all your excelent work.

**Comment by oltdaniel** [comment]
@CzarnyHetman This is not an issue. Close now as this is not an issue.

**Comment by CzarnyHetman** [comment]
@oltdaniel Well, there is no such feature, and i think it would be rather useful. Where should i put this suggestion then?

**Comment by oltdaniel** [comment]
@CzarnyHetman This is a data only repository. There are dozens of visualizations out there, like mine https://oltdaniel.at/2020/covid-19-analysis.html . @CSSEGISandData Just provides the data and their dashboard. That is more than enough work.
