### ISSUE TITLE
Why did you idiots change the schema. I know its not a big deal but seriously . .  WTF?

### ISSUE THREAD

**Issue by domsooch** [CSSEGISandData/COVID-19#1739]

**Comment by rks125** [comment]
You can use this if you like. I try to maintain the schema. I’ve been updating for 5 days. 

https://www.soothsawyer.com/john-hopkins-time-series-data-confirmed-case-csv-after-march-22-2020/?github=schema

**Comment by domsooch** [comment]
sorry guys keep up the good work.
