### ISSUE TITLE
Northern Ireland has disappeared from the dashboard

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#174]
What happened to Northern Ireland? It was on the table until just now. Now I can't find it. But now I see "new" the country "Ireland".

What did you mean by Northern Ireland all this time? Has it just been touched up now?
![fgdf](https://user-images.githubusercontent.com/49625256/75616295-9646fc80-5b4f-11ea-9935-b84503721556.PNG)

**Comment by CSSEGISandData** [comment]
Its case was merged into the UK.
