### ISSUE TITLE
Tianjin 2 cases disappeared in the dashboard

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#176]
Near Tianjin I had seen the number 138 5 hours ago. Now it's 136 again. Where did the two cases go?
![fdgdgdf](https://user-images.githubusercontent.com/49625256/75616660-31da6c00-5b54-11ea-8a08-a649441ed8e4.PNG)

**Comment by dawenx** [comment]
Probably a mistake 2 hours ago, Tianjin’s number is 136.

**Comment by iceweasel1** [comment]
Ahh okay. It could be.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We have updated the dashboard to reflect the proper value.
