### ISSUE TITLE
There is no US data in latest updates 3.29.2020

### ISSUE THREAD

**Issue by clarity7764** [CSSEGISandData/COVID-19#1763]
Not seeing any US data in the latest updates in the file 'time_series_covid19_confirmed_global.'

**Comment by johnorjias** [comment]
Just switch to using this https://coronadatascraper.com/#timeseries-jhu.csv <https://coronadatascraper.com/#timeseries-jhu.csv>
Thats what I did

**Comment by roboticsrun** [comment]
what is the benefit of switching to that? johnorjias

**Comment by texadactyl** [comment]
@clarity7764 
There is no 03-29-2020.csv daily report file yet.  Nor, is there a time series column for 3/29.
That data will not be ready until later in the day on 3/29 (today).

**Comment by clarity7764** [comment]
The data that exists in the file that I mentioned does not contain US data,
I’m looking for the historical data at the moment.

**Comment by texadactyl** [comment]
The daily report files up through 03-28-2020 have all of the historical data, including the US states.

**Comment by clarity7764** [comment]
Ok. I’m assuming in the future the US data will be back in the historical
file?

**Comment by texadactyl** [comment]
Okay, I do not know what you mean by "historical file".  

The following subdirectory within this github project contains all of the daily reports: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

To use this data, you must accumulate whatever data you are interested in by file date (USA format mm-dd-yyy).  I don't know how you wish to analyze the data.

Alternatively, you could use the files in time series folder.

**Comment by johnorjias** [comment]
All the areas are still there, all the us states, counties etc. everything that was lost from the 24th on in CSSEGI.

**Comment by isaacew** [comment]
I have also noticed that the data for the US states are no longer available. I really wish you would bring that back. It is no longer being published in the new format.

**Comment by rks125** [comment]
I have been maintaining the time series format with both US state and county level detail for the past five days. 

https://www.soothsawyer.com/john-hopkins-time-series-data-confirmed-case-csv-after-march-22-2020/?GitHub=6

**Comment by texadactyl** [comment]
@rks125 
I've noticed that the data up-to-date. I download the daily reports regularly and extract the CSV files to a local database which I process with Python programs.  I see no issues.  You lot are doing the best you can with the spotty data that you receive, as far as I can tell.

**Comment by oltdaniel** [comment]
It is updated, please close as the data in https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv#L227 is updated.

**Comment by clarity7764** [comment]
Great! It's closed.

**Comment by isaacew** [comment]
It’s still US state data. This shouldn’t be closed. You should put the states data back in.

**Comment by texadactyl** [comment]
@isaacew 
See https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv

What do you think is missing?

**Comment by isaacew** [comment]
Problem resolved. Thank you for the link. I’ll use that from now on. 

Thank you!

-Isaac
