### ISSUE TITLE
Total USA data missing in "Total Deaths" tab without selecting USA from left pane

### ISSUE THREAD

**Issue by sreejvij** [CSSEGISandData/COVID-19#1765]
Total USA data is missing in "Total Deaths" tab without selecting USA from left pane.
Is this intentional?

![image](https://user-images.githubusercontent.com/36736380/77856359-3c9c2580-7214-11ea-80c3-ab50de5f3a04.png)

**Comment by oltdaniel** [comment]
@sreejvij If you select the US it will take a moment to load. The Data exists currently, but may be deleayed (be 0) if it is currently updated (2am german timezone). Please close as it is too old.
