### ISSUE TITLE
Merge Massachusetts counties (duke, duke and nantucket, nantucket

### ISSUE THREAD

**Issue by d76d30dbl** [CSSEGISandData/COVID-19#1766]
Duplicate Counties

Duke County
Duke County and Nantucket
Nantucket

the middle one roughly translates to Nantuck, Marthas Vinyard and nearby, smaller, Islands
that should be sufficient

**Comment by oltdaniel** [comment]
@d76d30dbl Please provide detailed links or close the issues or lose the issue of the latest commit resolved your issue.

**Comment by d76d30dbl** [comment]
Awareness was my only desire ---- that is done.
