### ISSUE TITLE
Additional data of people with positive test 

### ISSUE THREAD

**Issue by aerijman** [CSSEGISandData/COVID-19#1767]
Is there a way to get information about people that got tested positive living with children? And if so, what is their mortality rate?

**Comment by oltdaniel** [comment]
@aerijman The data here is on the dat a that will be collected here. This is a wolrld dat collection. with many different sources, Finding special cases of how the COVID-19 virus affected the patient is very difficult across that many countries. Please close this issue and find or combine data sources in order ton identify our application nees.

**Comment by aerijman** [comment]
I will close it. Please, let me know if I have access to the source data.
Thank you!
