### ISSUE TITLE
as viruses obviously don't ask for borders

### ISSUE THREAD

**Issue by designerfuzzi** [CSSEGISandData/COVID-19#177]
the csv files contain longitude and latitude which helps to sort out data by contry.
But as ( in example ) in Europe cities and traffic is bound kinda close to each other, the more data is collected under one longitude & latitude the less informal the data will be. In my opinion this is still helpful information but is there any source or possibility to get long&lat per case.

ps: started developing a csv parser sorting out data by longitude and latitude ranges to show a map via iOS app. The main goal is to display data in a way that actually could help people focus to help each other than banning whole countries out of their feared viewpoints.

**Comment by iceweasel1** [comment]
The longitude and latitude are only given roughly. An exact delimitation is of course very interesting and beautiful. On the other hand it might be as it is good.

JHU @CSSEGISandData made a comment 10 hours ago. In the end it is also about privacy. That is also correct again.

You can read it here: https://github.com/CSSEGISandData/COVID-19/issues/146#issuecomment-592956126

**Comment by designerfuzzi** [comment]
privacy sure.
the lat/long doesnt have to be per street/house..
They could be set for the next public health care office in charge or to the city hall of the next town in charge. This would actually be very helpful instead of increasing spreaded invalid data that only comes back to one number - mortality per country.

protecting privacy is not not that difficult and also given by law in germany. There is no discussion about that, but as excuse stamping the whole data not useful to people.. its only increasing panic as seen last days.
The last increase and outbreak in germany is actually happen because people where not informed well enough from what origin coming/meeting up someone they should take care watching their own symptoms and trigger help early when they match the symptom descriptions of covid-19.

The lack of precision is more a good reason to opt out here and go for local press releases.

**Comment by iceweasel1** [comment]
Ich sehe gerade, du kommst ja auch aus Deutschland. ;-)

Seit Beginn mit Bayern führe ich eine Liste wo ich jeden Fall von Deutschland eintrage. Außer der fortlaufenden Fallnummer das Datum, Bundesland, Landkreis. Je nachdem wenn aus einer offiziellen Pressemitteilung verfügbar, ergänze ich Spalten dahinter noch die Stadt, das Geschlecht und das Alter. Als letzte Spalte, eben wenn auch aus einer PM hervorgehen kann, ob es mit einem Fall X (Kontaktperson) in Verbindung steht. Die allerletzte Spalte ist die Quellen-Spalte. Dort hab ich den Link zum Gesundheitsministerium-Bundesland X, oder Landkreis/Stadt/Krankenhaus. Je nachdem.

Was hier in Deutschland mehr als lächerlich ist, ist der komplette Behördenschimmel. Ein teil der bis jetzt betroffenen Bundesländer bekommt es teilweise "gut" hin. Die andere Hälfte ist zum Heulen. Da muss man sich von den Landkreisen, teils sogar von der betroffenen Stadt von deren Webseite die Information als Verifizierung ziehen. Manche schießen den Vogel vollstens ab in dem nur in Facebook oder Twitter als Erstes die Bestätigung verkündet wird. Auf der Webseite selbst überhaupt nichts oder Tage später.

Entweder hätten alle 16 Bundesländer, die jeweiligen Gesundheitsministerien, ausschließlich die offiziellen Bestätigungen kommuniziert um im Nachgang als Anweisung dann die Landkreise/Städte. Aber so wie es immer noch läuft, kocht jeder sein eigenes Süppchen.

Das RKI vom Bundesgesundheitsministerium beauftragt schießt sowieso den Vogel ab.

**Comment by iceweasel1** [comment]
Längen- und Breitengrad reicht ja auf den Landkreis. Ich ergänze die Liste mit beiden Spalten. Dann haben wir für hier eine saubere Liste.

**Comment by designerfuzzi** [comment]
danke @iceweasel1 
yes being in Berlin. 

i hope (and think) the officials in germany have an intern database backed from german health-medical-care system, which we can't access for obvious safety reasons cause it has much more data then needed for a public-info map. And indeed that does not mean it is always used properly to keep the community at least at minimum warned levels, which is why we read news and make our own csv's. I was looking up if something useful is published at robert-koch-institute but could not find something.

Have seen your shared CSV i will try to support your database sticking to your data-layout for the visual i'd like to create. Meanwhile created a short list myself, from news tonight to have a starting point using lat/long, kreis/region.

Again, Thanks a lot for your answer.
