### ISSUE TITLE
Update for Alberta, Canada for 29th March 2020

### ISSUE THREAD

**Issue by sjetha** [CSSEGISandData/COVID-19#1773]
Total Cases Confirmed: 661
Total Deaths: 3
Total Confirmed Recoveries: 73

Source: https://www.alberta.ca/release.cfm?xID=6995496444280-A170-CFA9-FE8A1EFC9B1B348C

**Comment by oltdaniel** [comment]
The data here is https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv#L37 and is combined by multiple sources. Please close this issue, as this data exists and is just not macthed in the second with your source but with more official sources by @CSSEGISandData .
