### ISSUE TITLE
Multiple data points showing up at 0 degrees Lat/0 degrees Long on dashboard map 

### ISSUE THREAD

**Issue by finleydc** [CSSEGISandData/COVID-19#1785]
Dashboard: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Multiple data points have 0/0 Lat/Long as their location, so they are plotted in the East Atlantic off the coast of Africa.  As of 1630 EDT US time, there were about 37 reports overlayed at this location--many US states and some nations.  Not evident if these records are being included in tallies of their assigned principalities.

**Comment by oltdaniel** [comment]
@finleydc Please provide exact data links in this GitHub repo in order to indetify this issue. If this data issue doesn't affect the current version, please close this one the keep the amount of issues small.

**Comment by finleydc** [comment]
Sorry, this report was against data posted on GitHub at 
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data; 
The data has some missing fields that, when plotted on a map, show records of COVID cases out in the ocean, not in the nation that reported the data.  This is NOT a bug with GitHub code or the website itself.
