### ISSUE TITLE
Louisiana (unassigned) coordinates of the coast of West Africa

### ISSUE THREAD

**Issue by tautme** [CSSEGISandData/COVID-19#1789]
![image](https://user-images.githubusercontent.com/15580867/77966822-70755a80-72a9-11ea-8b24-1fc245dc8cd4.png)

https://github.com/CSSEGISandData/COVID-19/issues/1710

This is from `csse_covid_19_data/csse_covid_19_daily_reports/03-29-2020.csv`

**Comment by MEM-TEK** [comment]
The same location shows for unassigned in FL and KY.

**Comment by MEM-TEK** [comment]
Unassigned cases for several states are reported with geographic coordinates of 0 lat, 0 long. It is a temporary location until the true locations for these cases are determined.

**Comment by tautme** [comment]
@MEM-TEK Thanks for explanation. I missed the 0,0 obvious mistake.
