### ISSUE TITLE
Data are not updated.

### ISSUE THREAD

**Issue by airsompoke** [CSSEGISandData/COVID-19#1793]
It seems that the daily reported data in CSV files have not been updated since 29 March 2020. Could you recheck and update?

**Comment by paulosssantos** [comment]
No updates so far.
JHU Dashboard (https://coronavirus.jhu.edu/map.html) is updated but not here.

**Comment by oltdaniel** [comment]
@airsompoke Please close. Due to manual work, updates can be delayed as can be observed in the commits log.
