### ISSUE TITLE
US DATA TOTALLY WRONG

### ISSUE THREAD

**Issue by GerardoRTobar** [CSSEGISandData/COVID-19#1796]
There are some numericals mismatches with the Data provided so far of the US. 

Even though a commit was made like half hour ago allegedly making some adjustments, it just doesn't fit the data provided before.

**Comment by GerardoRTobar** [comment]
If the latest commit was supposed to make the numbers be in a cumulative sense, then the sum of the confirmed cases up to now for the US according to the CSV would be around 143K, which is not like the data being shown in your online dashboard, and also for the data reported so far (allegedly being aroun 163K).

I need to know also if the first columns are just a summary by State, because the number I provided above (the 143K the CSV says) IS INCLUDING that "by State" data along with the summation of every county.

**Comment by CSSEGISandData** [comment]
Well, the discrepancy between GitHub files and the dashboard is because of different updating frequency. Dashboard is updating at least once in an hour and the GitHub files once a day.

**Comment by GerardoRTobar** [comment]
No. I found out it’s because US files are one day behind
