### ISSUE TITLE
Changing date formats?

### ISSUE THREAD

**Issue by baradhili** [CSSEGISandData/COVID-19#1798]
Hi Guys - notice that date formats keep changing.. it makes a mess of my data loads - can you keep to a standard format? ideally yyyy-mm-dd so that its easy to load... otherwise its a hassle to have to manually clean

**Comment by baradhili** [comment]
but otherwise - keep up the great work :)

**Comment by CSSEGISandData** [comment]
Hello! We are still following the format, MM/DD/YYYY HH:mm:ss, such as "2020-03-30 22:52:45" in daily reports. Thanks!

**Comment by baradhili** [comment]
Sorry.. but in your time series you aren't it varies... I'm looking at time_series_covid19_confirmed_global.csv
