### ISSUE TITLE
How are transferred individuals counted?

### ISSUE THREAD

**Issue by ciscorucinski** [CSSEGISandData/COVID-19#18]
There are special flights out of Wuhan and Japan will let some individuals off of the cruise ship. So how are those transferred individuals counted in the data? 

Let's say a cruise ship passenger has the virus and is allowed off the ship, but they die after. Is that a cruise ship death or a Japan death?

**Comment by JHale716** [comment]
Good question. Also too we know of one other infection that has come off a cruise ship, which hasn't been subject to a full 14 day quarantine either. I think it was in Hong Kong, so is being counted in their data presently.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We are counting cruise ship cases as those who tested positive on the cruise ship. It does not include people who tested positive upon their return home.
