### ISSUE TITLE
Data for South Korea, Japan inconsistent with WHO daily situation report

### ISSUE THREAD

**Issue by hfwang2016** [CSSEGISandData/COVID-19#180]
Can you please clarify the data source for these two countries? It seems that there are some inconsistencies with the WHO daily situation reports. 

The confirmed cases for South Korea on 2/25 is 144 in your data, and the WHO reported 214 on that day. https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200225-sitrep-36-covid-19.pdf?sfvrsn=2791b4e0_2

For Japan , there are negative numbers for the daily confirmed cases on 2/7/2020: -20, and 1/23/2020: -1

**Comment by CSSEGISandData** [comment]
Time difference. We are reporting in GMT+0. Thanks
