### ISSUE TITLE
"Recovered" as a Province_State of the US and Canada?

### ISSUE THREAD

**Issue by greg-minshall** [CSSEGISandData/COVID-19#1800]
hi.  a daily user.  i wonder if you could explain the "Recovered" state/province that has shown up the las week or so (for Canada and the US)?

for 03-30-2020.csv, there are entries in the Recovered *column* for other US states, though mostly in (the also mysterious) state of "US".  in Canada, on two other provinces have non-zero -- but very small -- values in the Recovered column.

cheers.

**Comment by boogheta** [comment]
Noticed the same thing, I wanted to propose à PR to remove all occurences, but I'm not sure whether it is intentional or not... In the mean time I will simply filter these out from the time series data I download

**Comment by greg-minshall** [comment]
@boogheta thanks, and for pointing out the duplicates!

**Comment by oltdaniel** [comment]
@greg-minshall As duplicates have been pointed out, close this one,

**Comment by greg-minshall** [comment]
(sorry, i thought this *had* been closed!)

**Comment by boogheta** [comment]
The pull request wasn't merged yet, so it was logically not closed, not sure why it should
