### ISSUE TITLE
Incorrect coordinates for Aleutians West, Alaska

### ISSUE THREAD

**Issue by bsdunx** [CSSEGISandData/COVID-19#1801]
The coordinates for Aleutians West, Alaska are currently pointing inside Canada. I'm not sure the preferred coordinates used by the US government since various searches pull up different values.
[USGS waterdata](https://waterdata.usgs.gov/nwis/nwismap/?site_no=1529761775&agency_cd=USGS) gives latitude `51°52'35 N"` longitude `176°39'17 W"` converted to decimal `51.876389 -176.654722` respectively.

**Comment by CSSEGISandData** [comment]
Thanks @bsdunx - fixed in latest.
