### ISSUE TITLE
Minimalist Dashboard: bit.ly/covid19db

### ISSUE THREAD

**Issue by zubair0** [CSSEGISandData/COVID-19#1802]
### I made a minimalist dashboard that lets you track the spread of covid-19 without getting scared with bright red colours everyone seems to be using.

Added WHO defined regions to it too.

Will be adding more advanced statistics and charts to it later too. So do check back.

Here: [http://bit.ly/covid19db](http://bit.ly/covid19db )

![Screenshot 2020-03-31 at 1 15 06 PM](https://user-images.githubusercontent.com/22931760/78003286-dae1d580-7351-11ea-8a12-9891e923dd79.png)
![Screenshot 2020-03-31 at 1 15 17 PM](https://user-images.githubusercontent.com/22931760/78003292-dddcc600-7351-11ea-862c-8235fa9da14a.png)

#576

**Comment by oltdaniel** [comment]
@zubair0 This is not an real issue for the data provided by this repo. Please close now.
