### ISSUE TITLE
Hourly updated aggregated dataset

### ISSUE THREAD

**Issue by QuantApp** [CSSEGISandData/COVID-19#1806]
We have created an aggregated dataset with hourly updates from various data sources including the John Hopkins dataset.

Please read
https://github.com/QuantApp/CoFlows-Covid19

**Comment by mmonfort2908** [comment]
I've tried this out and it works pretty well. Takes the best features from a number of sources and pulls it together. You can see a bit more about it here - https://medium.com/prosperity-advisers-dna/application-getting-more-up-to-date-numbers-f7cb14e0854e

In that article there's a link to the app I built with it

**Comment by oltdaniel** [comment]
@QuantApp If you look into the recent commits you will see, it involves a lot of manual work publishing the data on GitHub or adding it to the dashboard. A daily update is not considered and only the interval of commits in this repo will lead the updates. So please consider opening an personal repo and close this issue.

**Comment by QuantApp** [comment]
@oltdaniel this post was to share our work with the community! You guys are doing an amazing work. Thanks
