### ISSUE TITLE
Incorrect text 

### ISSUE THREAD

**Issue by Chizkiyahu** [CSSEGISandData/COVID-19#1817]
Instead of country/state, It says admin0/admin1/admin2
![Screen Shot 2020-03-31 at 19 21 59](https://user-images.githubusercontent.com/37312901/78050500-fadebc80-7384-11ea-8af2-741b3bec9824.png)

**Comment by oltdaniel** [comment]
@Chizkiyahu This is an issue that does not affect this GitHub repo. Please contact them per Mail, and not here, as this is only abuot the raw data. Please close.
