### ISSUE TITLE
Data Missing 

### ISSUE THREAD

**Issue by piyushzope** [CSSEGISandData/COVID-19#1822]
COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv
COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

22nd March data is missing in both the Confirmed and Deaths CSV File

**Comment by oltdaniel** [comment]
@piyushzope Its a CSV file and the column with the date of the 22nd march exists in both files. Please close here.

**Comment by piyushzope** [comment]
Thanks for the update. It got refreshed after 15 mins when I posted it.

**Comment by oltdaniel** [comment]
@piyushzope Please close this issue if resolved.
