### ISSUE TITLE
terquedad y humanidad/COVID_19

### ISSUE THREAD

**Issue by tecnoorganico** [CSSEGISandData/COVID-19#1825]
https://www.linkedin.com/posts/google-cloud_how-google-cloud-is-helping-during-covid-activity-6650789743242076161-Kpl_

**Comment by oltdaniel** [comment]
@tecnoorganico Please close this issue. No context tho this repo, nor an actual issue.

**Comment by tecnoorganico** [comment]
> https://www.linkedin.com/posts/google-cloud_how-google-cloud-is-helping-during-covid-activity-6650789743242076161-Kpl_
