### ISSUE TITLE
US Files

### ISSUE THREAD

**Issue by Breadknot** [CSSEGISandData/COVID-19#1830]
Table is too large and unreadable.
![Image](https://user-images.githubusercontent.com/60681223/78081296-39bd4400-737e-11ea-8640-4f94a813e0f6.png)

**Comment by ralucaandreeaoman** [comment]
do you happen to have recoveries for us only? thank you.

**Comment by bevanward** [comment]
@Breadknot you can simply save the results to CSV and use that way. Being larger it saves you from having to click on raw. Can you close this issue as there are many issues remaining open which are resolved. Thanks
