### ISSUE TITLE
Wrong date from Dominican Republic

### ISSUE THREAD

**Issue by gredow** [CSSEGISandData/COVID-19#1837]
Isn't almost all (if not all) dates wrong about Dominican Republic, since data from this country published today about 10:00 a.m. is from yesterday at 06:00 p.m. and the same everyday.

**Comment by oltdaniel** [comment]
@gredow Please link the exact line in a commit in order to resolve the issue. Else please close this issue to keept hings nice an clean. They fix wrong formats after automated updates, Manualy fixes require some time.

**Comment by gredow** [comment]
I’m sorry. I’m not a git hub expert nor a native English speaker. But from my understanding in this file: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv when in the 4/1/2020 column  in Dominican Republic row is written 1284, that’s an incorrect information, since that number represents the confirmed cases in this country on 03/31/2020, according to the Ministry of Public Health of Dominican Republic. The web page (https://www.msp.gob.do/web/?page_id=6682) from the ministry is not working property by the time I’m writing this, but in its Facebook page is posted the bulletin: https://www.facebook.com/SaludPublicaRD/photos/pcb.2817877591659058/2817877474992403/?type=3&theater. Now, the situation is the same from the column 03/19/2020 with 34 confirmed cases, but that represents the day 03/18/2020, according to the first bulletin from the Ministry of Public Health of Dominican Republic.
Sorry if I misunderstood the information from the file or if I can’t express myself correctly so you can understand what I mean.

**Comment by oltdaniel** [comment]
@gredow This repo "estimates" the cases by using differente sources, This will result in "higher" (more accurate or less accurate) numbers in the stats. Choose the source by your personal needs. This repo updates dailby by estimating with different sources. Else close this issue.

**Comment by gredow** [comment]
I don't have any problem using the data, since I'm aware of the situation and I do the corrections before using it. My only intention here is to help to make the data more acurate to others. But I feel you don't even care to check if what I'm saying is correct or not. Maybe because I'm from one insignificant country or other reason, but I think that's not cool of you.
