### ISSUE TITLE
Thank you to the team

### ISSUE THREAD

**Issue by YoannParis** [CSSEGISandData/COVID-19#1838]
I posted few issues here in the past few weeks, to complain about the data files when you were always changing the order of the coutries, the countries names, etc.

Since 3 days now, you have updated the data, taking care of keeping the same order and just added news countries at the end of the list. So, i have to say 👍 

THANK YOU !

**Comment by oltdaniel** [comment]
@YoannParis Say thank you by email not by issue. Please close. Issues indicated a negative thing or feature request for something missing. Not specially something positive.
