### ISSUE TITLE
03-31-2020 daily report doesn't show data

### ISSUE THREAD

**Issue by KMcodingK** [CSSEGISandData/COVID-19#1841]
Hello, the data just disappear from the map, at 03-30-2020 daily report it was working well but 03-31-2020 daily report just the data just gone , how to solve this ?

**Comment by aravindnc** [comment]
Seems working fine here. BTW, How are you pulling the data ?

**Comment by KMcodingK** [comment]
Im pulling the data into html BTW it was working yeasterday before updating , but after new update the data just disapper idk the new update has any new changes ?

**Comment by aravindnc** [comment]
Are you automatically generating the CSV filename. May I know how you are pulling the data.

**Comment by KMcodingK** [comment]
yes am generating the filename automatically by using this code 

`var today = new Date();
    var dd = String(today.getDate()).padStart(2, '0');
    var dd2 = String(today.getDate() - 1).padStart(2, '0');
    var mm = String(today.getMonth() + 1).padStart(2, '0');
    var yyyy = today.getFullYear();

    today = mm + '-' + dd + '-' + yyyy;
    today2 = mm + '-' + dd2 + '-' + yyyy;

    var cl = [];
    var textfile = d3.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/" + today + ".csv", function (data) {
        //console.log(data);
        cl = data;

        if (cl == null) {
            var newtextFile = d3.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/" + today2 + ".csv", function (data) {
                cl = data;
                executable(cl);
            });
        } else {
            executable(cl);
        }

        function executable(commentlist) {
            for (var i = 0; i < commentlist.length; i++) {
                var lat = commentlist[i]['Lat'];
                var lng = commentlist[i]['Long_'];
                var popupText = "الولاية: " + commentlist[i]['Province_State'] + "<br/>" + "الدولة: " + commentlist[i]['Country_Region'] + "<br/>" + "الحالات المؤكدة: " + commentlist[i]['Confirmed'] +
                    "<br/>" + "الوفيات: " + commentlist[i]['Deaths'] + "<br/>" + "المتعافين: " + commentlist[i]['Recovered'] + "<br/>" + "آخر تحديث: " + commentlist[i]['Last_Update'];
`

**Comment by aravindnc** [comment]
Thats the issue,
today.getDate() - 1
Today is 01, so today.getDate()-1 becomes 00.

Sot today2 becomes **04-00-2020.csv** Which inturn gets 404 while accessing.

**Comment by KMcodingK** [comment]
thank you for your reply, how can i change it to moment js ? could you change in the code i used please ?

**Comment by Galvantua** [comment]
I'm having the same issue, but only for the US reports: I see data all the way until 3/30, but no data for 3/31. I'm using google sheets IMPORTDATA() and it works fine for the global files.

**Comment by KMcodingK** [comment]
Allright , the 04-01-2020.csv now is working well and the data is showen up , @aravindnc thank you for your reply and your help ❤
