### ISSUE TITLE
Tests performed per day

### ISSUE THREAD

**Issue by Makmoer** [CSSEGISandData/COVID-19#1844]
Thank you very much for the effort you guys put in to create these datasets and for sharing it. Is it perhaps possible to get the number of tests performed per day per country as well? It forms a direct relation to the number of positive cases. The fewer tests performed the fewer number of new cases identified.

Thank you.

**Comment by Makmoer** [comment]
Please ignore, I see you will release this in a few days. Thanks

**Comment by Borg19l71** [comment]
Close the issue.

**Comment by QualityMeasurement** [comment]
@Makmoer Do you need assistance with closing this issue given your resolution?

**Comment by oltdaniel** [comment]
@Makmoer Please close, to clean up issues.
