### ISSUE TITLE
why column recovered empty?

### ISSUE THREAD

**Issue by aghussb** [CSSEGISandData/COVID-19#1845]
why in file cases time column recovered empty?

**Comment by oltdaniel** [comment]
@aghussb The are multiple file s in this repo, which file do you mean? And the reovered cases are updated daily in the timeseries file.

**Comment by aghussb** [comment]
in this https://github.com/CSSEGISandData/COVID-19/blob/web-data/data/cases_time.csv

**Comment by oltdaniel** [comment]
@aghussb I think you should stay in the master branch. Better data format and made for the public, not the dashboard in the backend. https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data . Please close.

**Comment by aghussb** [comment]
okeyy
