### ISSUE TITLE
beta

### ISSUE THREAD

**Issue by MZPIGGEE81** [CSSEGISandData/COVID-19#1851]

**Comment by oltdaniel** [comment]
@MZPIGGEE81 Please close, as no context given. The data format often changes, due to different sources and differnent reported data every day. @CSSEGISandData do their best job to keep everything clean and are currently the best source we can use.

**Comment by MZPIGGEE81** [comment]
echo "# Kermit" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/MZPIGGEE81/Kermit.git
git push -u origin master
