### ISSUE TITLE
Log to see dashboard?

### ISSUE THREAD

**Issue by omaldonado60** [CSSEGISandData/COVID-19#186]
![image](https://user-images.githubusercontent.com/8164823/75637497-a02b3700-5c05-11ea-8b5d-a7a94397e1a7.png)

**Comment by eamoses** [comment]
You might be using the incorrect link, try this one: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by CSSEGISandData** [comment]
That's a temp system hiccup. It should be back now.

**Comment by omaldonado60** [comment]
Thanks! It's OK now
