### ISSUE TITLE
conflicts after pull

### ISSUE THREAD

**Issue by klartext** [CSSEGISandData/COVID-19#187]
I cloned the repo some hours ago. Later I did a pull. After that I got conflicts.
I cloned the repo again, to see what has happened.
The last commit from the first clone was f0f9bf8b2f0b9d0e7e217bd76497714030b7853a.
It's not available anymore in the new clone.
So I assume, you did a commit --amend on data that was already published.
That's a NoNo!
So, please don't do that.
Just add a new commit, when the data has already been published, instead of rewriting the history.
If you don't know, what I'm talking about, please consult the literature on git usage (e.g. J. Loeliger) or other available ressources. And next time just add a bugfixing commit (update to the update).

**Comment by CSSEGISandData** [comment]
There were some issue with the repo and are now fixed. Sorry for the inconvenience and the late reply.
