### ISSUE TITLE
Do US county recovered cases work properly?

### ISSUE THREAD

**Issue by andrewfader** [CSSEGISandData/COVID-19#1872]
"Recovered: the number of recovered cases." For Cook County IL, Maricopa AZ, and Suffolk MA, I had a nonzero number for recovered cases that then went down back to 0. Does this mean it was an error, that the person didn't actually recover but died or is still sick, or does it mean that I should be adding up the cumulative values for these fields instead of taking the last one as a total?

**Comment by jukent** [comment]
I think you have to add the cumulative values. Each days' recovered cases are how many people recovered on that day. Similar for confirmed cases.

**Comment by andrewfader** [comment]
@jukent are you sure? If that's the case... the numbers don't seem right for the confirmed cases. E.g. last few for NYC:     [ 8] 21873,
      [ 9] 25573,
      [10] 29776,
      [11] 33768,
      [12] 37453,
      [13] 43119
If we summed those, the number would exceed the state totals and city numbers being reported currently

**Comment by andrewfader** [comment]
Or take the latest number for the UK "25150" matches the numbers reported here: https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public so at least it does not seem to be a cumulative addition for that confirmed number

**Comment by jukent** [comment]
Oh you're right. I was having a different error that made the values for NYC too low originally.

**Comment by andrewfader** [comment]
But still not sure, why some locations had a non-zero "recovered" value and now it has gone down to 0. It does not seem to be 0 internationally. Is there any info about how that number is calculated, e.g., is it a # of days since infection and healthy?

**Comment by jukent** [comment]
I'm not sure. I hope someone can answer this.

**Comment by jspanos71** [comment]
The recovered number was moved to a "Recovered" location. I do not know why, but look for it there.

**Comment by andrewfader** [comment]
So no more county level recovery stats.

**Comment by Llaves** [comment]
jspanos71 wrote:
> The recovered number was moved to a "Recovered" location. I do not know why, but look for it there.

Where is this other location? All the entries in the recovery and active columns for US counties are zero, yet they are non-zero for many foreign countries/regions

**Comment by HallidayDW** [comment]
Quoting from the "Coronavirus COVID-19 Global Cases by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU)" website:
> Recovered cases outside China are estimates based on local media reports, and may be substantially lower than the true number.

I've also seen claims that there are no "authoritative" or "reliable" sources of Recovered data (at least «outside China»).

Unfortunately, I see no comments, concerning "Recovered" cases on the CDC website. So I don't know if they simply have no way to track such (yet, don't they track to Death?), or if they have yet to decide what criteria to use for "Recovered", or if they are simply being highly conservative, by not making any statements until they are more certain.

Of course, this then calls into question the Blood and Plasma donations of claimed "Recovered" individuals!
