### ISSUE TITLE
Australian Data Issue - times series data does not match up to dashboard

### ISSUE THREAD

**Issue by superblackguy** [CSSEGISandData/COVID-19#1878]
HI 

First of all really appreciate the work done here to consolidate this information!

I noticed in comparing the Australian/New South Wales number of total cases that there is a differences in the data in the "time_series_covid19_confirmed_global.csv" vs the dashboard as highlighted below:

Github data:

![image](https://user-images.githubusercontent.com/55696124/78195316-0fc56800-74cb-11ea-8f0a-75d7d64d6d7e.png)

Dashboard:

![image](https://user-images.githubusercontent.com/55696124/78195498-7a76a380-74cb-11ea-9f2b-a2d3c565ca62.png)

**Comment by oltdaniel** [comment]
@superblackguy The timeseries data is only updated once a day on GitHub at 2am (german time) and is not live with the dashboard data. It is as it is, so not really an issue. Please close.

**Comment by superblackguy** [comment]
Yes I realise this but it's been like this for the last two days. Should I still close it?
