### ISSUE TITLE
Date inconsistency again

### ISSUE THREAD

**Issue by InTEGr8or** [CSSEGISandData/COVID-19#188]
Today's date column is labeled `3/01/20`.

Dates should be _either_ like last months `2/1/20` _or_ `03/01/20`.

Either a two digit day _and_ a two digit month with leading zeros, or omit the leading zeros on _both_ the day and the month.

It doesn't ANY sense to remove the leading zeros from the month and retain them on the day, and it requires unnecessary and cumbersome additional conditional code.

Isn't there some tool you could use when outputting to make sure this is _never_ reintroduced?

**Comment by InTEGr8or** [comment]
Looks like it was fixed while my code was still broken. Now that my code is fixed, the date format is updated.

Thanks!

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238
