### ISSUE TITLE
Country Data - US confirmed cases and deaths are 0

### ISSUE THREAD

**Issue by autoabend** [CSSEGISandData/COVID-19#1880]
country | confirmed | deaths | recovered | active
China | 82,361 | 3,316 | 76,405 | 2,640
India | 1,998 | 58 | 148 | 1,792
US | 0 | 0 | 8,536 | 0

**Comment by mikehumphrey** [comment]
@enshengdong @hongru94 @arthurzhang434

**Comment by ryanwoconnor** [comment]
Same as #1882 and #1881
