### ISSUE TITLE
No US data in 4/1 daily report?

### ISSUE THREAD

**Issue by climbbike** [CSSEGISandData/COVID-19#1881]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv

**Comment by ryanwoconnor** [comment]
Same as #1882

**Comment by therealcyberlord** [comment]
Yes, hopefully this is not an April 1st thing. Stay safe guys.

**Comment by ErandM50** [comment]
When will the County data get updated? Are they released with a 1 day lag now?
Also the number for US in the time series file, does it include US territories such as Guam etc.?

**Comment by amalic** [comment]
Can you close this issue. The ohter one has many more comments!
https://github.com/CSSEGISandData/COVID-19/issues/1882

**Comment by climbbike** [comment]
see #1882
