### ISSUE TITLE
US data is missing from daily data file April 1st.  SOLVED!

### ISSUE THREAD

**Issue by JuanPufleau** [CSSEGISandData/COVID-19#1882]
US data is missing from daily data file April 1st.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv

**Comment by amalic** [comment]
Can confirm!
see: https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs

**Comment by joshpritch** [comment]
US data is missing from the app as well

**Comment by ryanwoconnor** [comment]
Why is this data missing? People rely on this.

**Comment by rmoyers58** [comment]
Yes the US data is missing

**Comment by icarlitoss** [comment]
Thanks for posting this. A quick alternative (until we wait for this fix) at this source:
http://dash-coronavirus-2020.herokuapp.com/

**Comment by judecalvillo** [comment]
Can confirm that US data is missing and affecting the dashboard...

![jhu_coronavirus_dash_screenshot](https://user-images.githubusercontent.com/10369337/78198147-82d3cd80-743c-11ea-879a-4f00c44f9815.jpg)

**Comment by mashranga** [comment]
US data missing !! But why !! Updating the dashboard?

**Comment by oltdaniel** [comment]
I think they are currently entering the data, as e.g. deaths is not entered for now on https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 .

**Comment by sailorsails** [comment]
Looks like it is back up
![Screen Shot 2020-04-01 at 20 20 51](https://user-images.githubusercontent.com/42578748/78198360-60e74480-7456-11ea-9f8a-a66e636531d7.png)

**Comment by amalic** [comment]
Instead of the state/province the only US line in the dataset says "Recovered" despite having a Recovered column.

**Comment by oltdaniel** [comment]
@sailorsails Well CDN sucks of arcgics, I still have 712 with cache disabled. 😆 
@amalic Something we need to live with. It is still the most "official" data source we could get. @CSSEGISandData does still a good job about collecting, and medium at publishing.

**Comment by judecalvillo** [comment]
> Looks like it is back up
> ![Screen Shot 2020-04-01 at 20 20 51](https://user-images.githubusercontent.com/42578748/78198360-60e74480-7456-11ea-9f8a-a66e636531d7.png)

Oh, interesting. When I click 'US' on the left, to subset the other visuals, the dash appears to revert. Probably just a cache issue.

**Comment by KrishnaAgarwal05** [comment]
Data is still missing from the daily report files for 04/1. Would appreciate if someone can look into it.

**Comment by amalic** [comment]
> @amalic Something we need to live with. It is still the most "official" data source we could get.

I know. GitHub issues are to me just feedback. I hope my comment didn't sound offensive.

**Comment by oltdaniel** [comment]
@KrishnaAgarwal05 I find it more unusual that the automated update for the timeseries isn't out yet. Normally it comes 5mins later than the daily report automated update, so still waiting for it at 2am in the morning... 🤣

**Comment by octopicorn** [comment]
Both US and Canada data are missing from Daily report file 2020-04-01:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv#L60

Every previous file had a row for each US county. Where did this go?

A breaking change here is that the word "Recovered" appears as the `Province_State` value. This will throw off any code looking to this column for matching with states in US and Canada. That is why "Recovered" appears mysteriously in dashboard.

**Comment by amalic** [comment]
Canada is there, at least the total

**Comment by amalic** [comment]
> Both US and Canada data are missing from Daily report file 2020-04-01:

Canada data is in the file

**Comment by octopicorn** [comment]
@amalic line 59, it has "Recovered" as a Province, with values 0 for Confirmed and Deaths.
You are correct that province rows are filled in above.

**Comment by amalic** [comment]
@CSSEGISandData

**Comment by k7nixen** [comment]
I am sorry but you guys should stay in academia and outsource this or any technical effort. I have been creating a new ETL job every week because of nonstop changes in the data format, file logic changes. And now the complete file is missing.

**Comment by oltdaniel** [comment]
@octopicorn @amalic @k7nixen Each commit here needs to be reviewd by each developer to verify their needs to their application. I personally stay awakw during night and verify the commits to finally convert them to my data format at https://c.oltdaniel.at . They (@CSSEGISandData) do an aazing work here, as collecting the data is extremly hard, due to countries not reporting enough or not having an reliable data source to collect the data from. For us as developers, using this datasource here, we have the task of putting it into a finaly beauty of data format.

**Comment by amalic** [comment]
@CSSEGISandData @hongru94 @enshengdong  @arthurzhang434 
You might want to take a look at this

**Comment by octopicorn** [comment]
@oltdaniel nice work with your data vis.  appreciate your focus on the commits. i can' timagine having to manage this work, there are 1000+ issues and 192 PRs currently!

yes, i'm just here to help report the issue. very grateful for the excellent reference work of collecting this info.  i just turned off my data feed for 2020-04-01 until the US data comes back.

this file is created by an automatic process, i think, so some breaking change must have happened upstream

**Comment by joshpritch** [comment]
Is there any data source that tracks recoveries by state on a daily basis?

**Comment by amalic** [comment]
> I personally stay awake during night and verify the commits to finally convert them to my data format at https://c.oltdaniel.at . They (@CSSEGISandData) do an aazing work here

I am also staying awake since a couple of days to make sure, it gets updated properly. Switched today even to a different strategy using Google Apps Script.

I totally agree about the work they do, as long as the data format does not change. I don't mind having additional columns added, but renaming or replacing columns is not ideal since the file we are using is to us an API.

**Comment by amalic** [comment]
> Is there any data source that tracks recoveries by state on a daily basis?

This one does for a couple of countries, e.g. USA, Canada, China

**Comment by DinsdalePiranha85** [comment]
No Time-Series update (Global OR USA) either.

**Comment by joshpritch** [comment]
> > Is there any data source that tracks recoveries by state on a daily basis?
> 
> This one does for a couple of countries, e.g. USA, Canada, China when it works properly.

Maybe I'm blind but this report shows 0 for all US rows. I must be missing something obvious.

**Comment by octopicorn** [comment]
Just as reference point, the Daily Report file from 2020-03-31 had 2436 rows
Today's has only 257 rows. All the county rows are gone.

**Comment by amalic** [comment]
> > > Is there any data source that tracks recoveries by state on a daily basis?
> > 
> > 
> > This one does for a couple of countries, e.g. USA, Canada, China when it works properly.
> 
> Maybe I'm blind but this report shows 0 recoveries for all US rows. I must be missing something obvious.

It does. Recovered is now a US state/province

**Comment by amalic** [comment]
> Just as reference point, the Daily Report file from 2020-03-31 had 2436 rows
> Today's has only 257 rows. All the county rows are gone.

That's not correct. see https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit#gid=0

Only US is missing

**Comment by joshpritch** [comment]
> > > > Is there any data source that tracks recoveries by state on a daily basis?
> > > 
> > > 
> > > This one does for a couple of countries, e.g. USA, Canada, China when it works properly.
> > 
> > 
> > Maybe I'm blind but this report shows 0 recoveries for all US rows. I must be missing something obvious.
> 
> It does. Recovered is now a US state/province

Yes I see that. I just meant is there a data source that breaks the Recovered number down by county or state?

**Comment by amalic** [comment]
> > > > > Is there any data source that tracks recoveries by state on a daily basis?
> > > > 
> > > > 
> > > > This one does for a couple of countries, e.g. USA, Canada, China when it works properly.
> > > 
> > > 
> > > Maybe I'm blind but this report shows 0 recoveries for all US rows. I must be missing something obvious.
> > 
> > 
> > It does. Recovered is now a US state/province
> 
> Yes I see that. I just meant is there a data source that breaks the Recovered number down by county or state?

There are other data sets, but you need to register to access them. This is the only openly available that I am aware of.

**Comment by andyquinterom** [comment]
My best advice, for now, is to limit your data to March 31st. I have set my data visualization web app to only go up to March 31st. You can download the data in a more "friendly" format through this link: https://users.indexmic.com/corona/ 
I'll inform you if anything changes.

**Comment by oltdaniel** [comment]
@amalic I currently work issue by issue until I will fell asleep to reduce the issue work for @CSSEGISandData. Willing to help?

**Comment by tienthanhdhcn** [comment]
If you only care about the state level, please see my backup here https://www.dropbox.com/s/zzbmmelywsxnh28/04-01-2020.csv

**Comment by ebwinters** [comment]
how is a top public research institution releasing this data? If you don't have the data, that's fine, but you realize when you have thousands of users, you can't just introduce breaking changes with no warning.

**Comment by rkrinjeck** [comment]
Is a file/data update coming or in the works?  The JHU Dashboard is working, so I'm assuming that you have the correct data.  We just need an update.

**Comment by oltdaniel** [comment]
@ebwinters Put yourself into this position. No country prepared for such an event in this time with this tech. The reports happen in an unregular basis and different dates. It is extremly difficult to put al into one format. @CSSEGISandData does an amazing and difficult job.

**Comment by ebwinters** [comment]
@oltdaniel I'm simply pointing out, at some point once you have a lot of users relying on your data, there is an understanding that breaking changes are not made. I completely understand technical difficulties, which would lead to data being delayed, but the types of changes JHU has been making can have a huge impact on developers and the people using their projects.

**Comment by d-huck** [comment]
I have an automated script to update my data visualization and I have had to come back and check why my script breaks almost every single day for the last week. I shouldn't have to tweak my code every few days because the data keeps getting dropped or changed. I understand this is released free of charge, but there are people relying on this data.

**Comment by oltdaniel** [comment]
@ebwinters I agree, but this source is the best one we have. We need the ope source people that belive in small scripts and throwing time in this to upgade this data format. Yes, @CSSEGISandData can do a better job, but we need to split the time we put into this. So we need different layers with different reliabilty of data formats. I personally convert the data each day to https://c.oltdaniel.at to use it for my application.

**Comment by KrishnaAgarwal05** [comment]
Data has been updated

**Comment by amalic** [comment]
Works! 

see:https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs

**Comment by octopicorn** [comment]
@KrishnaAgarwal05 excellent, thank you so much

**Comment by JuanPufleau** [comment]
I'll leave the Issue open for a while longer, so people who experienced problems can now see it's been resolved. 

I'll close it later today.

**Comment by cjtexas** [comment]
Harris County Texas' FIPS column is still blank!
![image](https://user-images.githubusercontent.com/2301100/78275635-79e40a00-74d7-11ea-8b74-d68ff471ff10.png)
