### ISSUE TITLE
csse_covid_19_daily_reports/04-01-2020.csv missing data?

### ISSUE THREAD

**Issue by jredner** [CSSEGISandData/COVID-19#1884]
Hi, I don't see any data from US in this report for 4/1/2020.  Is this expected?  Thank you for your help and for providing this data.

04-01-2020:
alisa:COVID-19 jredner$ cat csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv  | grep US
,,Recovered,US,2020-04-01 23:08:29,0.0,0.0,0,0,8536,0,"Recovered, US"

03-31-2020: 
alisa:COVID-19 jredner$ cat csse_covid_19_data/csse_covid_19_daily_reports/03-31-2020.csv  | grep US
45001,Abbeville,South Carolina,US,2020-03-31 23:43:56,34.22333378,-82.46170658,4,0,0,0,"Abbeville, South Carolina, US"
22001,Acadia,Louisiana,US,2020-03-31 23:43:56,30.295064899999996,-92.41419698,39,1,0,0,"Acadia, Louisiana, US"
51001,Accomack,Virginia,US,2020-03-31 23:43:56,37.76707161,-75.63234615,7,0,0,0,"Accomack, Virginia, US"
16001,Ada,Idaho,US,2020-03-31 23:43:56,43.4526575,-116.24155159999998,195,3,0,0,"Ada, Idaho, US"

**Comment by jredner** [comment]
closing duplicate issue

**Comment by oltdaniel** [comment]
@jredner Please write a note, on why to re-open. https://github.com/CSSEGISandData/COVID-19/issues/1882 notices the missing US data enough.
