### ISSUE TITLE
Why are the global files not being updated?

### ISSUE THREAD

**Issue by GerardoRTobar** [CSSEGISandData/COVID-19#1886]
Are you guys going to stop updating the files time_series_covid19_confirmed_global.csv, time_series_covid19_deaths_global.csv and time_series_covid19_recovered_global.csv?

I also see no update for the US files.

**Comment by oltdaniel** [comment]
@GerardoRTobar Yes, not updated yet. I wait for it as well, as the updates normally happen 5minutes apart in the last days. As you can observe on the [dashboard](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) they are currently manually inserting the data, So we need to wait.

**Comment by GerardoRTobar** [comment]
@oltdaniel  Thanks a lot! As you say, the update for the daily report was made 1 hour ago, but I use the other data source. I think we all do. By this time they have usually done the update

**Comment by GerardoRTobar** [comment]
@oltdaniel they haven't said anything about not updating tthe files anymore, have them?

**Comment by oltdaniel** [comment]
@GerardoRTobar They are pretty quite on GitHub anyways. So I guess no. I review the issues each by each to reduce the amount and make @CSSEGISandData less work.

**Comment by fadeyifemi** [comment]
> @oltdaniel Thanks a lot! As you say, the update for the daily report was made 1 hour ago, but I use the other data source. I think we all do. By this time they have usually done the update

The daily report was "updated", but the US data in it seems to be messed up... #1881

**Comment by GerardoRTobar** [comment]
But do you know something about the files in time series? Are they still gonna update it?

**Comment by oltdaniel** [comment]
@fadeyifemi The daily report is pretty much not interesting if you use the time series files. Would be nice if an update comes soon.

**Comment by fadeyifemi** [comment]
@oltdaniel Oh yeah, I understand that. I was just pointing that out to indicate the problems tonight might be more wider spread because the daily update seems to be having a serious problem as well.

**Comment by amalic** [comment]
Close this issue since it's a duplicate!

**Comment by fadeyifemi** [comment]
@amalic , which issue number are you saying this is a duplicate of?

**Comment by GerardoRTobar** [comment]
Ok, but before can someone explain? I don't understand why is it a duplicate. The only other issue referenced here mentions only US DAILY data, but I am asking about the global time series and for us too,

**Comment by oltdaniel** [comment]
@GerardoRTobar Hasn't been updated yet at all.

**Comment by GerardoRTobar** [comment]
That's why I had the bad feeling of it not being updated anymore. Is not normal that by this time they haven't done it yet

**Comment by maisonml** [comment]
This is an urgent issue, can someone from the team please provide an update on when the data would be made available?

**Comment by amalic** [comment]
> @amalic , which issue number are you saying this is a duplicate of?

Was already mentioned by yourself:
https://github.com/CSSEGISandData/COVID-19/issues/1882

**Comment by amalic** [comment]
Timeseries have been retired. Check the README.MD file

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by GerardoRTobar** [comment]
No. Wait. The readme mentions that the older timeseries (time_series_19-covid-Confirmed.csv, time_series_19-covid-Deaths.csv and time_series_19-covid-Recovered.csv) were retired.

And it mentions that they will be substituted by new timeseries, called time_series_covid19_confirmed_global.csv, time_series_covid19_deaths_global.csv and time_series_covid19_recovered_global.csv.

Those were functional until today. They haven't mentioned anything about retiring these ones too.

**Comment by bevanward** [comment]
@amalic - the original were replaced with time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv the versions without _global.csv are the depreciated versions. My guess is they are still organising data these will be updated soon. Getting hard to know the specifics of what is happening

**Comment by just2610** [comment]
the readme.md is clear: **Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data.**  these files have not been updated. Is this because of a problem once the us time series files were added?

the deprecated files are:
time_series_19-covid-Confirmed.csv 
time_series_19-covid-Deaths.csv 
time_series_19-covid-Recovered.csv

**Comment by fadeyifemi** [comment]
> Timeseries have been retired. Check the README.MD file

Read closelier. The readme is pretty clear that only 2 specific file formats were retired; replaced by 3 other ones.

**Comment by jredner** [comment]
additionally, the US data mentioned by just2610 is missing 3/31 and 4/1

**Comment by amalic** [comment]
> I also see no update for the US files.

Which US files?

**Comment by jspanos71** [comment]
The time series files seem to be compiled from the daily file. I imagine something broke with the daily file (which is why it is missing US data) and so the time series have not been updated yet. Please be patient while they work on the issue.

**Comment by oltdaniel** [comment]
@GerardoRTobar That changes is a few days old. You need to keep up to date here every commit.

**Comment by amalic** [comment]
> @GerardoRTobar That changes is a few days old. You need to keep up to date here every commit.

Just imagine everybody would just create an issue. Including the duplicates that were already deleted and all the comments there would be ~50 issues for the same problem.

**Comment by ManchesterWuer** [comment]
Really hope  @CSSEGISandData guys can update the time series files soon.

**Comment by GerardoRTobar** [comment]
I am not really following you two, guys @amalic and @oltdaniel. Of course I know that change is old, but is amalic who referenced me to it. That's why I explained him that the readme mentions OLDER FILES. NOT THE FILES THAT WERE BEING UPDATED UP TO YESTERDAY, WHICH ARE THE ONES I AM ASKING FOR.

**Comment by fadeyifemi** [comment]
Don't know what amalic was on about. But FYI, daily data file was fixed 8 minutes ago (https://github.com/CSSEGISandData/COVID-19/issues/1882#issuecomment-607577817), so the separate problem here might be getting attention relatively soon.

**Comment by GerardoRTobar** [comment]
Thanks for your information. I'll be expecting the timeseries to be updated too. 

IF not, i guess I will have to make a new script by myself to load every daily file as a time series...

**Comment by agentdanger** [comment]
Confirming daily file was fixed.  Was there a note or indication that the global time series we no longer being supported?  Hopefully they'll get attention.

**Comment by amalic** [comment]
also those global files were fixed one minute ago

**Comment by ManchesterWuer** [comment]
Just noticed the time_series_covid19_confirmed_global.csv, time_series_covid19_deaths_global.csv, time_series_covid19_recovered_global.csv are just updated!

**Comment by agentdanger** [comment]
confirming, thanks.

**Comment by oltdaniel** [comment]
@GerardoRTobar Files updated. Please close.

**Comment by GerardoRTobar** [comment]
Thanks everyone who had the patience. Closing the thread.
