### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Croisened** [CSSEGISandData/COVID-19#1889]
COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/

These files are missing over 1K rows of data beginning 3/31.   It would appear that once some US data gets added it wipes out all the rest?  It's very incomplete the last 2 days.

If you go back to 3/30 and before you can see this file was well over 3,400 rows and now after all updates its way less and appears to be missing much of what was previously available.

**Comment by ryanwoconnor** [comment]
I am also looking for an answer to this. I have several projects relying on that data. Can someone tell me what is going on? This data has changed so frequently in almost every way possible. Can we please get a steady, reliable structure? I have to keep coding around all of these changes and it's causing quite a bit of headaches. Please think of the people downstream before you make changes. 

Thank you,
Ryan

**Comment by oltdaniel** [comment]
@Croisened Would be nice if you would provide exact links to the files affected with the lines. We could not determine this issue in the current data. If not relevant today, it is fixed already please close.

**Comment by Croisened** [comment]
Sure, look at this file (today's): COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv

Compared to this file:  COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/03-30-2020.csv

I basically use the raw feed and it just seems to be missing much data (like over 1,00 rows if you compare the days) and several lat,longs not populated such as New York on line 2000 in today's file as one example.  --idk
