### ISSUE TITLE
Direct link to graph images if anyone wants.

### ISSUE THREAD

**Issue by w3goodies** [CSSEGISandData/COVID-19#1890]
https://corona.dnsforfamily.com/graph.png?c={2-Letter-Country-Code}

**For example:**
https://corona.dnsforfamily.com/graph.png?c=CN
https://corona.dnsforfamily.com/graph.png?c=US
https://corona.dnsforfamily.com/graph.png?c=IT
https://corona.dnsforfamily.com/graph.png?c=IR

- Images are updated each day, once.
- Graphs are available for all the countries (mostly).
- Graph shows stats for last 14days that includes confirmed cases and deaths per day.

I made this for my Telegram channel (https://t.me/CoronaNotify) so if anyone else wants to use it, then please go ahead.

**Comment by oltdaniel** [comment]
@w3goodies This is not an issue, as it doesn not affect the satus of any file in this repo. PLEASE CLOSE:
