### ISSUE TITLE
US timeseries: Incorrect death numbers for NJ counties 2020-03-31

### ISSUE THREAD

**Issue by vsec03** [CSSEGISandData/COVID-19#1897]
In the US timeseries dataset, death numbers for New Jersey counties 2020-03-31 are incorrect. Many counties have a decease in number of deaths from March 30 to March 31. E.g. Bergen county has 23 deaths on March 30, but only 4 deaths on March 31.

**Comment by codecae** [comment]
I've been supplementing my dataset using rollups from the nytimes dataset 

  |   |   | date | Values |   |  
-- | -- | -- | -- | -- | -- | --
  |   |   | 30-Mar |   | 31-Mar |  
state | county | fips | Sum of cases | Sum of deaths | Sum of cases | Sum of deaths
New Jersey | Atlantic | 34001 | 30 | 0 | 31 | 0
  | Bergen | 34003 | 2482 | 41 | 2909 | 53
  | Burlington | 34005 | 178 | 5 | 202 | 5
  | Camden | 34007 | 200 | 1 | 228 | 3
  | Cape   May | 34009 | 15 | 0 | 15 | 0
  | Cumberland | 34011 | 12 | 1 | 18 | 1
  | Essex | 34013 | 1564 | 36 | 1900 | 47
  | Gloucester | 34015 | 89 | 1 | 114 | 2
  | Hudson | 34017 | 1314 | 11 | 1606 | 16
  | Hunterdon | 34019 | 79 | 0 | 97 | 0
  | Mercer | 34021 | 249 | 0 | 268 | 1
  | Middlesex | 34023 | 1123 | 20 | 1277 | 24
  | Monmouth | 34025 | 1030 | 15 | 1140 | 21
  | Morris | 34027 | 720 | 13 | 841 | 21
  | Ocean | 34029 | 874 | 12 | 1022 | 18
  | Passaic | 34031 | 1091 | 9 | 1294 | 11
  | Salem | 34033 | 3 | 0 | 12 | 1
  | Somerset | 34035 | 349 | 14 | 413 | 14
  | Sussex | 34037 | 113 | 3 | 132 | 3
  | Union | 34039 | 1213 | 15 | 1418 | 24
  | Warren | 34041 | 68 | 2 | 76 | 2

Hope this helps.
