### ISSUE TITLE
Fujian a case disappeared again

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#190]
The last number at Fujian was 297. Now I see that the number was minimized by 1 again. Is there a reason for this?
![dssdf](https://user-images.githubusercontent.com/49625256/75702134-2eaac180-5cb5-11ea-925e-52561b3c1586.PNG)

**Comment by CSSEGISandData** [comment]
The dashboard has been updated to the correct confirmed case count. Sorry for the inconvenience.
