### ISSUE TITLE
Coronavirus disease (COVID-19) outbreak - situation update for Europe (coming up)

### ISSUE THREAD

**Issue by web-sys1** [CSSEGISandData/COVID-19#1907]
Europe has reached over +523000 cases, 35651 deaths and 88764 recoveries, according to Berliner Morgenpost as of April 2, 2020; while COVID-19 situation in the WHO European Region takes every 24 hours to get updated at same 10:00 (CET).

![screencapture-interaktiv-morgenpost-de-corona-virus-karte-infektionen-deutschland-weltweit-1585838202598](https://user-images.githubusercontent.com/61905565/78262151-d7dd1580-7508-11ea-90dd-baf38c719810.png)
Can be found [here](https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/)

 <br>

![screencapture-who-maps-arcgis-com-apps-opsdashboard-index-html-1585838414954](https://user-images.githubusercontent.com/61905565/78262347-18d52a00-7509-11ea-91b7-f0c351e999de.png)
Can be found [here](https://who.maps.arcgis.com/apps/opsdashboard/index.html#/ead3c6475654481ca51c248d52ab9c61)

It's important to mention this notice.

**Comment by cipriancraciun** [comment]
@web-sys1 it's unclear to me what this issue is actually asking or proposing.

Could you please reformulate or elaborate?  Are you saying you have an alternative data-source for Europe?

**Comment by web-sys1** [comment]
> Are you saying you have an alternative data-source for Europe?

Yes. I saw that is alternative data-source for the entire continent as I will mention here. CSSEGISandData doesn't have this.

**Comment by cipriancraciun** [comment]
@web-sys1 apparently the "data-source" you've mentioned seems to focus mainly on Germany, for the rest of the countries doesn't seem to go deeper than country level.

Also, based on their attribution, they already seem to be using JHU, among other sources:
> Datenquellen: Johns Hopkins University CSSE (internationale Daten von WHO, CDC (USA), ECDC (Europa), NHC, DXY (China) und Meldungen der deutschen Behörden (Robert-Koch-Institut sowie Landes- und Kreisgesundheitsbehörden).

But regardless, what is the URL to a machine-readable data format for the "data-source" you've mentioned?  (I've tried looking at the network requests it makes, but there are around ~250 requests...)

**Comment by web-sys1** [comment]
Just wait a moment.

**Comment by web-sys1** [comment]
For more information regarding this data-source about Europe region, please visit http://www.euro.who.int/en/health-topics/health-emergencies/coronavirus-covid-19

**Comment by web-sys1** [comment]
I've found another relevant data source: https://qap.ecdc.europa.eu/public/extensions/COVID-19/COVID-19.html

**Comment by cipriancraciun** [comment]
@web-sys1 OK, but neither of the pointed sources provide any of the following:
* machine readable format;  (i.e. XML, JSON, TSV, Excel, anything that doesn't require human screen-scraping;)
* more depth than country level;

**Comment by web-sys1** [comment]
I found from Arcgis Feature Server:

https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/EURO_COVID19_Current_v3/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&maxRecordCountFactor=4&orderByFields=CasesTotal%20DESC&outSR=102100&resultOffset=0&resultRecordCount=8000&cacheHint=true&quantizationParameters=%7B%22mode%22%3A%22view%22%2C%22originPosition%22%3A%22upperLeft%22%2C%22tolerance%22%3A1.0583354500042326%2C%22extent%22%3A%7B%22xmin%22%3A-4561232.646001%2C%22ymin%22%3A3681101.399999%2C%22xmax%22%3A8301267.085001%2C%22ymax%22%3A13119061.110001%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D%7D

**Comment by web-sys1** [comment]
I will retieve more if needed.

**Comment by cipriancraciun** [comment]
@web-sys1 first let me say that I'm really interested in finding a data-source for Europe that has a deeper level than country level, thus I'm not trying to find problems in your proposal.  :)

However try to look at the JSON you've pointed and try to identify a rule based on which that data can be processed into something useful.  It provides no per-date values, no recovered values, no deeper levels, etc.  For example I extract what seems to be the record for Germany:
~~~~
    {
      "attributes": {
        "WHO_CODE": "DEU",
        "LastCaseDate": 1585785600000,
        "LastDeathDate": 1585785600000,
        "CasesTotal": 73522,
        "CasesN1": 73522,
        "CasesN2": 67366,
        "CasesN3": 36508,
        "CasesN4": 10295,
        "CasesN5": 1567,
        "DeathsTotal": 872,
        "DeathsN1": 872,
        "DeathsN2": 732,
        "DeathsN3": 198,
        "DeathsN4": 35,
        "DeathsN5": 3,
        "LAT": null,
        "LON": null,
        "ObjectId": 14
      },
      "geometry": {
        "x": 5404019,
        "y": 6102288
      }
    },
~~~~

**Comment by web-sys1** [comment]
Same problem. COVID-19 situation in the WHO European Region has no 'recovered' included.

**Comment by web-sys1** [comment]
Also on mobile got same issue. No recovered value. Link:
https://who.maps.arcgis.com/apps/opsdashboard/index.html#/10a2438e6e2e4092a8e02772c42f0f2b

joi, 2 apr. 2020, 19:08 Ciprian Dorin Craciun <notifications@github.com> a
scris:

**Comment by web-sys1** [comment]
Doing that.. Please hold.

**Comment by web-sys1** [comment]
I think that Map Filtering (that could filter number of countries per continent) is an priority.

**Comment by web-sys1** [comment]
UPDATE April 08, 2020 – Changes in the [webpage ](https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/) has to come up. Number of new cases largely the same.
2 × The total number doubles in 12.5 days.
![screencapture-interaktiv-morgenpost-de-corona-virus-karte-infektionen-deutschland-weltweit-1586325283340](https://user-images.githubusercontent.com/61905565/78749627-4b52ad00-7977-11ea-83c6-c6f5a5d288ec.png)

**Comment by web-sys1** [comment]
**UPDATE April 12, 2020**
![screencapture-www-worldometers-info-coronavirus-1586677960073](https://user-images.githubusercontent.com/61905565/79063798-82dd9400-7cac-11ea-8c79-0ed146050cfc.png)

https://www.worldometers.info/coronavirus/#c-europe%22

**Comment by web-sys1** [comment]
Close #1907 after almost four months since it has been opened.
