### ISSUE TITLE
U.S. time series data: Why year format keeps changing??  YYYY to YY then back to YYYY

### ISSUE THREAD

**Issue by pybokeh** [CSSEGISandData/COVID-19#1909]
Not sure if I'm going crazy, but one day, the date format is m/d/YYYY and then its m/d/YY format.  Anybody else noticing this?

**Comment by kondis** [comment]
You're not going crazy. I just had to update my date formatter to fix the parsing of these data. It was working with yyyy yesterday. Maybe it's because the admin realized that the global format is yy and chose to match this, but I'm speculating.

**Comment by pybokeh** [comment]
@kondis Thanks!  Glad to hear it wasn't just me.  I had to change my parsing code too, twice this week.  I wish it was just consistent, but yeah I guess I can add more exception code to my script to account for either format.

**Comment by Lucas-Czarnecki** [comment]
@pybokeh You are not crazy. I noticed the same today. If you're interested, I started a repository to address these kinds of inconsistencies [HERE](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE).  

Consider closing this issue as JHU is probably overwhelmed with them. :)

**Comment by pybokeh** [comment]
@Lucas-Czarnecki Good to know.  I have already added a try/catch clause in my script to account for the different year format, so I think I am good to go now.  It was just odd that they would switch formats, back and forth like that.
