### ISSUE TITLE
Indonesia is listed twice

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#191]
See headline.

![sdasd](https://user-images.githubusercontent.com/49625256/75703096-16d43d00-5cb7-11ea-8ce7-e9aae34dca8f.PNG)

**Comment by dawenx** [comment]
Looks like one version has a typo in spelling. I thought @CSSEGISandData gets data from ESRI or some backend API automatically every 15 minutes, wondering why a typo like this could happen. Some manual curation as well maybe?

**Comment by klartext** [comment]
The second entry has an indentation. Maybe just a blank that has not been stripped away? There is already a pull request for removing extra spaces: https://github.com/CSSEGISandData/COVID-19/pull/167

**Comment by CSSEGISandData** [comment]
Sorry for the late response. The dashboard has been updated to remove the duplicate country. Thank you!
