### ISSUE TITLE
Incorrect data for Arizona/US

### ISSUE THREAD

**Issue by 30213n124thln** [CSSEGISandData/COVID-19#1919]
The data is still incorrect. Please review where. Email sent.  It went off the tracks on 4/1
![AZ State](https://user-images.githubusercontent.com/52870643/78311667-4f5d7580-7506-11ea-9ab6-83018740b65a.JPG)
![AZ Worldometers](https://user-images.githubusercontent.com/52870643/78311670-52586600-7506-11ea-81f5-8289df5f8f74.JPG)
![AZ ncov2019 live](https://user-images.githubusercontent.com/52870643/78311679-571d1a00-7506-11ea-99b8-693f179d68b2.JPG)

**Comment by amalic** [comment]
Are all three sites using the same timezone?

E.g. Daily updates of this dataset here is based on UTC time/date.

**Comment by virendrapatel62** [comment]
Data Of Us recovered Cases not showing

**Comment by 30213n124thln** [comment]
> Are all three sites using the same timezone?
> 
> E.g. Daily updates of this dataset here is based on UTC time/date.

I download the data as soon as it is available each day - 5PM (GMT -7) Arizona time. Screenshots were from about 15 minutes later. This was day 2 of the inconsistency, I noticed the discrepancy on 4/1.
