### ISSUE TITLE
Incorrect data for New Hampshire/US

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#1920]
Total number of cases 
03 / 31 -> 367
04 / 01 -> 316

Difference: -51 cases

see: my [Google Spreadsheet](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit#gid=140936829)

**Comment by jkbishay** [comment]
Can confirm that the data in csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv is incorrect for New Hampshire and a few other states like Tennessee as well.

Specifically, New Hampshire is missing 3 counties: Hillsborough, Manchester, and Nashua.

**Comment by cdelargy** [comment]
Hillsborough county (line 1776) is incorrect, appended with 0 when should be >99
@jkbishay Manchester and Nashua are not counties in NH, they are cities.

**Comment by cdelargy** [comment]
Reporting from https://www.nh.gov/covid19/index.htm shows Hillsborough county broken into 3 components sub-sections, which sum to 163 (57+63+43).

**Comment by cdelargy** [comment]
Added https://github.com/CSSEGISandData/COVID-19/pull/1937/commits/31c7df5bf660257c1b74792c400ca6ab932e44c7 to fix
