### ISSUE TITLE
Jordan & Portugal - Mix-up between two countries

### ISSUE THREAD

**Issue by issaqandil** [CSSEGISandData/COVID-19#193]
There is a mix-up between two countries. I clicked on Jordan in the Map, it's showing me Portugal results. 

See attached.. 

[https://ibb.co/vYwrPrc](url)

**Comment by MI-LA01** [comment]
@issaqandil  : I can't see the screenshot supplied in your link. 

![Uploading Screen Shot 2020-03-02 at 9.45.00 PM.png…]()

**Comment by yabasha** [comment]
Jordan confirmed one case on 2nd of March 2020, which is not available in `csse_covid_19_daily_reports`

**Comment by issaqandil** [comment]
@MI-LA01 not sure why the link is not working. But the screenshot you kindly provided shows the problem. Portugal in Europe as you know but Jordan is in the middle east. The map shows Portugal in the middle east 😊

**Comment by MI-LA01** [comment]
+1 @issaqandil : Yes, my post was just to confirm what you said with the supplied screenshot.

**Comment by MI-LA01** [comment]
@issaqandil : fyi : this was fixed.

**Comment by issaqandil** [comment]
@MI-LA01 Great thank you!
