### ISSUE TITLE
Deaths US file adds population

### ISSUE THREAD

**Issue by KenneySnell** [CSSEGISandData/COVID-19#1989]
Confirmed US file for 4/4/2020 has 85 columns.
Deaths US file for 4/4/2020 has 86 columns

Can you put population in the confirmed file?

Thank you,

Kenney

**Comment by ehitchman** [comment]
Agreed here!  Definitely a nice to have.

If the population file and source can be made available separately, that would be great too!  Thank you!

**Comment by victcebesp** [comment]
Hey @KenneySnell! From where did you get the recovered cases in the US? It looks like there is not US recovered files here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
Thank you!!

**Comment by Lucas-Czarnecki** [comment]
Hey @KenneySnell,  based on what I've seen from JHU CSSE they are unlikely to make these kinds of changes as data are organized with the [dashboard ](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) in mind. 

If you are in need of a single file containing all three variables, I maintain a tidy repo that may be of interest to you [HERE ](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE). The time-series data [HERE ](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE/tree/master/COVID-19_CLEAN/csse_covid_19_time_series_cleaned) may be what you are after.

@victcebesp Unfortunately, JHU is no longer providing recovery data on the US. For more information on why see #1831 or #1250. 

@KenneySnell as this is more of a request than an issue, please consider closing this issue to help the folks at JHU from getting overwhelmed.

**Comment by KenneySnell** [comment]
> Hey @KenneySnell! From where did you get the recovered cases in the US? It looks like there is not US recovered files here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
> Thank you!!



> Hey @KenneySnell! From where did you get the recovered cases in the US? It looks like there is not US recovered files here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
> Thank you!!

MY mistake.  There is no recovered data file at this time.
