### ISSUE TITLE
Updates on Romania

### ISSUE THREAD

**Issue by itsmeczaharia** [CSSEGISandData/COVID-19#199]
Hello,

One of the patients has recovered. There is one more case confirmed.

[Source](https://www.digi24.ro/stiri/actualitate/informatii-oficiale-despre-coronavirus-ministerul-de-interne-26-de-persoane-sunt-in-carantina-2077-sunt-monitorizate-la-domiciliu-1266261)

TL;DR
Confirmed: 4
Deaths: 0
Recovered: 1
Existing: 3

**Comment by alexei** [comment]
Not yet! While the hospital officials said the second test was negative, the Ministry of Health said they were gonna do a third test and so far they haven’t given any updates on that case. See http://www.ms.ro/2020/02/28/buletin-informativ-28-02-2020-ora-1600/

In the meantime, they announced a 4th case today, see http://www.ms.ro/2020/03/03/al-patrulea-caz-de-infectare-cu-noul-coronavirus-in-romania/

**Comment by alexei** [comment]
Btw @CSSEGISandData do you accept PRs? We can help out. I’ve learned to not rely on newspapers for data as they oftentimes do not mention any source. So do you accept info from the Ministry of Health, or just WHO?

**Comment by alexei** [comment]
Ministry of Health announced earlier today the first patient tested negative and was discharged. Thus there are now 3 cases.

Details http://www.ms.ro/2020/03/04/buletin-informativ-04-03-2020-ora-1000/

**Comment by alexei** [comment]
Two new cases confirmed today:
16 years old from Timiș County
http://www.ms.ro/2020/03/04/al-cincilea-caz-de-infectare-cu-noul-coronavirus-a-fost-confirmat/
71 years old from Suceava
http://www.ms.ro/2020/03/04/s-a-confirmat-al-saselea-caz-de-infectare-cu-noul-coronavirus-in-romania/
