### ISSUE TITLE
Duplicate data for Washington County, Utah

### ISSUE THREAD

**Issue by Dinh-Nguyen-UEH** [CSSEGISandData/COVID-19#1999]
Duplicate observation for Washington County, Utah, US

```
fips_code	last_update	confirmed   deaths
49053	04/03/2020	21	   1
49053	04/03/2020	2	   0
49053	04/03/2020	22	   1
49053	04/03/2020	3	   0
```

**Comment by CSSEGISandData** [comment]
Thank you for finding this issue. We have removed the duplicate value and the changes will be reflected on the dashboard as well as todays daily data update.

**Comment by Dinh-Nguyen-UEH** [comment]
Hi,

I just checked the data for Washington, Utah, and the problem persists. The duplication of data happens not only for Washington, Utah but also many other counties across the U.S. 

I found out about this problem by cleaning the raw data a few days ago ([https://www.hapri.ueh.edu.vn/datacovid19](https://www.hapri.ueh.edu.vn/datacovid19)).

Is there any way I can send you you the complete list of errors?

Example for Washington County, Utah. You can see the number not only duplicate for one date but also jump up and down mysteriously between  dates.
```
county_code	last_update	case_confirmed	case_deaths
49053	        23/03/2020	5	0
49053	        24/03/2020	5	0
49053	        25/03/2020	5	0
49053	        26/03/2020	8	0
49053	        27/03/2020	9	0
49053	        28/03/2020	13	0
49053	        29/03/2020	8	1
49053	        30/03/2020	15	1
49053	        31/03/2020	14	1
49053	        01/04/2020	14	1
49053	        02/04/2020	18	1
49053	        03/04/2020	21	1
49053	        03/04/2020	2	0
49053	        04/04/2020	22	1
49053	        04/04/2020	3	0
49053	        05/04/2020	22	1
49053	        05/04/2020	5	0
49053	        06/04/2020	5	0
49053	        06/04/2020	26	1
49053	        07/04/2020	31	1
```
