### ISSUE TITLE
Non-printable characters at beginning of daily report file

### ISSUE THREAD

**Issue by coder-mike** [CSSEGISandData/COVID-19#2001]
When I look at the hex dump of `COVID-19\csse_covid_19_data\csse_covid_19_daily_reports\03-13-2020.csv`, I see some non-printable characters at the beginning of the file.

![image](https://user-images.githubusercontent.com/2261100/78508602-6aacd700-77cb-11ea-8675-a273f41bd1a9.png)

**Comment by timdestan** [comment]
I believe that's a [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark).

**Comment by coder-mike** [comment]
Thanks, I learned something new today! I wonder why some of the files have it and others not.
