### ISSUE TITLE
France numbers are still incorrect for the 4th and therefore for the 5th also....

### ISSUE THREAD

**Issue by loulouOz** [CSSEGISandData/COVID-19#2005]

**Comment by alfkoehn** [comment]
According to source [1] and [2], we have the following numbers (Ref. [3] requires adding together all territorial regions but seems to end up with very similar values):

- confirmed cases: 70478
- deaths: 8078 (5889 + 2189)


[1] https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-04-05.yaml
[2] https://www.gouvernement.fr/info-coronavirus/carte-et-donnees
[3] https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200405-sitrep-76-covid-19.pdf?sfvrsn=6ecf0977_2

**Comment by FrenchGu** [comment]
@alfkoehn FYI : direct access to the iframe embedded in [2] : https://dashboard.covid19.data.gouv.fr/

**Comment by cvilou** [comment]
I confirm, French official data are: https://www.gouvernement.fr/info-coronavirus/carte-et-donnees
70 478 persons not 93780.
Is it a Trump fake new?

**Comment by jgrosseo** [comment]
+1

**Comment by FrenchGu** [comment]
According to Le Monde french journal, @CSSEGISandData 's count for France confirmed cases 4/4/20 includes the 22,361 **potential** cases listed in the nursing home (as well as a double count of cases in the ultra-marine territories) which are not considered in [french official data](https://dashboard.covid19.data.gouv.fr/). They also announce they will now use official french Santé Publique France data instead of JHU data for France confirmed cases and deaths.  

Source : https://www.lemonde.fr/planete/live/2020/04/05/coronavirus-aux-etats-unis-trump-annonce-une-periode-qui-va-etre-vraiment-horrible_6035613_3244.html?highlight=1187488818

**Comment by vandonr** [comment]
Changing the way contaminations are counted like this in the middle of the series, even if it makes more sense, really makes the whole data unusable as there is a big jump in the count that corresponds to nothing "real".
If there is a change to apply to the way contaminations are counted, it should be applied retrospectively to the whole series or not at all.

**Comment by RomaricGravet** [comment]
@vandonr  Moreover, this change are argued only with press article and rumor. You find only estimation made by journalist or no specialist people. @CSSEGISandData  if you need change the definition of case, even if you do it in retrospect, please made this change with solid argument from the scientific community.

**Comment by jgrosseo** [comment]
> 
> 
> According to Le Monde french journal, @CSSEGISandData 's count for France confirmed cases 4/4/20 includes the 22,361 **potential** cases listed in the nursing home (as well as a double count of cases in the ultra-marine territories) which are not considered in [french official data](https://dashboard.covid19.data.gouv.fr/). They also announce they will now use official french Santé Publique France data instead of JHU data for France confirmed cases and deaths.
> 
> Source : https://www.lemonde.fr/planete/live/2020/04/05/coronavirus-aux-etats-unis-trump-annonce-une-periode-qui-va-etre-vraiment-horrible_6035613_3244.html?highlight=1187488818

I think it makes sense to count suspected cases, too, in general. But is it not done for many countries. Could one make a separate series  so that one can choose which numbers to use?

**Comment by mykiimike** [comment]
> I think it makes sense to count suspected cases, too, in general. But is it not done for many countries. Could one make a separate series so that one can choose which numbers to use?

Who is right actually ?

**Comment by cedricbellet** [comment]
As it stands, the numbers are misaligned with WHO, ECDC and the French authorities, so @CSSEGISandData needs to be fixed. Note as well that the https://coronavirus.jhu.edu/map.html labels these numbers as *confirmed* cases.

**Comment by vandonr** [comment]
> As it stands, the numbers are misaligned with WHO, ECDC and the French authorities, so @CSSEGISandData needs to be fixed. Note as well that the https://coronavirus.jhu.edu/map.html labels these numbers as _confirmed_ cases.

same for https://aatishb.com/covidtrends/ and several other tools relying on this data I suppose

**Comment by JiPiBi** [comment]
Till end of March , the French informations were based on hospitals informations only .

The potential cases in France are as @jgrosseo  said , there were obtained by aggregation of symptomatic people recorded in nursing houses, but they were not all tested ( mainly by the lack of tests....).
In these nursing houses, France also aggrated also about 2200 dead people

The 2  values could increase with exhaustive informations coming from the 7000 institutions, where there is about 750 000 oldies , and certainly going on to increase with the time.

The people that are maintained at home with mild covid symptoms are not tested and not considered as confirmed too. 

These cases will be probably included in some weeks in the surmortalities values,  that are a bit longer to obtain (in which you will also find deaths in hospitals) 

Even Italy says now that all deaths are not correctly counted ....

In every country , the real values (surmortalities ) have to be obtained

**Comment by JiPiBi** [comment]
But now to measure the peek of the epidemic , please consider important to obtain the values of **new** hospitalized people and **new** ICU . Not only the evolution of occupied beds

**Comment by martinedoesgis** [comment]
In adding to the nursing homes issue that could "explain" part of the additional 25k cases, there are also a huge differences in the numbers in France Overseas Territories as pointed out here : https://www.lemonde.fr/planete/live/2020/04/05/coronavirus-aux-etats-unis-trump-annonce-une-periode-qui-va-etre-vraiment-horrible_6035613_3244.html?highlight=1187488818

**Comment by JiPiBi** [comment]
@martinedoesgis  The nursing homes values are not a real issue but it is difficult to understand if you count them or not as confirmed , the same for people not sufficiently sick to be hospitalyzed and that are not tested and counted in confirmed.

To go on the issue of nursing homes , I read for my region than you must add to the numbers of deaths in hospital , 2/3 of the 1st value for deaths in EMS or nursing homes. 
So if the ratio is the same for the whole country , you must add 4000 deaths compared to about 6000 deaths in the hospitals . So for the moment 10000 . To be confirmed.

For the issue in the overseas , it has been pointed out to this site and to worldometers several times, but without results as almost all issues , the value on the France row is the aggregation of Mainland France with almost all France territories , but in the time series , you also find the separate values. 
Only Nouvelle Caledonie and Polynesie Francaise , are not aggegated with France row

**Comment by martinedoesgis** [comment]
@JiPiBi  : Yes for the nursing homes cases, the exact words used by the government are "Confirmed or Possible" so you can't really what proportion of them are confirmed or not ...

Also, it's hard to know if the confirmed cases in the nursing homes are new cases or were already included in the total. For the deaths, it's clear that they were not counted (hence the mortality peak) but for the total cases you can find both interpretations even in some french news papers (some are writing "70000 including nursing homes", others are writing "90000 including nursing homes"). I watched again the official video report video were those cases were announced and the government never said "new cases", they say that as of today there is XXX cases in nursing homes, so maybe it's just the detail of the cases, but not new ones ?

**Comment by JiPiBi** [comment]
@martinedoesgis 
The official site SPF . I think you can read freanch , look at the small lines under the values 

![image](https://user-images.githubusercontent.com/44967630/78584341-5d7a0180-7838-11ea-85e1-0323fc61c704.png)
It's quite clear , even if the number of confirmed cases is not the main issue , because it is obviuosly underestimated

**Comment by martinedoesgis** [comment]
Well it doesn't really say if the 22361 are part of the 70478 or not .. they just say that the 22361 are in the nursing homes.
Same for the difference between **Hospitalizations** and **Hospitalizations in Reanimation**. Are the ones in **Reanimations** counted in the total of **Hospitalization** ?  By only using this picture you can't really tell and different interpretations are possible, hence the possible misunderstanding and differences in the french news papers.

**Comment by JiPiBi** [comment]
Believe me , all these cases are in EMS , and they are not confirmed (mainly suspected) and are out of the hospitals , so they are not counted because the tests were made mainly till now in the hospitals.  

Yes reanimations which are in the hospitals are in hospitalyzed .

I follow these informations for several weeks .

The latests news about deaths on TV now are 6494 in hospital  + 2417 in EMS (hope that the updating is exhaustive, but not sure )

**Comment by JiPiBi** [comment]
Read too this recent link about the new strategy for EMS 

https://www.lemonde.fr/planete/live/2020/04/06/coronavirus-l-attestation-numerique-pour-les-deplacements-doit-etre-disponible-lundi_6035676_3244.html?highlight=1187532329

**Comment by martinedoesgis** [comment]
Well I'm not saying one is right or the other is wrong, just that they are different possible understandings:

- Either you add those 20000 to the 70000 but in that case you mix Confirmed and Suspected cases (which is not ideal + it creates a huge peak in the data like what happened in China at some points). This is apparently the choice of JHU, which is debatable. 

- Either you consider that those 20000 are part of the 70000 (which is once again what you can read on some sources, see here : https://www.linternaute.com/actualite/guide-vie-quotidienne/2462477-direct-coronavirusen-france-833-deces-de-plus-le-bilan-du-jour/#evolution-situation-france this phrasing that is really ambigious : 
"Le ministre de la Santé Olivier Véran a pris la parole lors du point presse quotidien du ministère : il a fait état d'un bilan de "6494 victimes depuis le 1er mars" liées à la pandémie de coronavirus. Ces dernières 24 heures, le bilan s'est alourdi de 863 décès. On compte "6494 cas (5 889 hier) et 2417 en Ehpad", a-t-il détaillé. Le nombre de cas de contamination au Covid-19 confirmés dans l'Hexagone a grimpé à 74390 contre 70478 hier."

**Comment by FrenchGu** [comment]
@martinedoesgis it is obvious that the 20k are not part of the 70k detected cases. 
The 70k were all really tested at the hospital and are all confirmed. 
No testing or little testing were performed in the nursing homes that’s why they are called « confirmed or suspected », but counts from nursing homes are only available for a couple days. 
So only your first question remains : should this 20k count from nursing homes be added to the total confirmed and detected cases from hospital ? This question concerns JHU but also French authorities. 
I would say they should not be added because as we know confirmed cases are far away from reality, by sticking with the same kind of data (true detected cases at the hospitals), the way the curve behave is a good indicator of how things go. Introducing new parameters now makes the curve irrevelant and useless.

**Comment by jgrosseo** [comment]
I submitted the proposal to have suspected cases as addition as separate issue from France because it is general --> #2041. Please upvote if you agree.

**Comment by SebSic** [comment]
@FrenchGu : it is unclear how "Sante publique France" counts cases in ESMS (nursing homes). In the declaration form, there are 2 definitions of cases : 
Possible case COVID-19: fever (or feeling of fever) with respiratory signs (such as cough, shortness of breath or tightness in the chest) OR other clinical picture compatible with Covid-19 as determined by the physician, among residents or members of staff of an EMS/EHPAD.

Confirmed case COVID-19: Any person, symptomatic or not, with a sample confirming infection with SARS-CoV-2 among residents or members of staff of an EMS/EHPAD. 

It is unclear the 20k cases there are only confirmed or both possible/confirmed
France is increasing (finally) the diagnosis capability and in the next days, a major screening will occur in nursing homes, then i guess only confirmed cases will be counted.

**Comment by JiPiBi** [comment]
Last informations 06/04/2020 from SPF quite unclear on deaths numbers ...

There is now a value in ESMS cell (cell bottom right) and  this number is different from the delta between Total deaths and Deaths in hospitals (cell bottom left) ..

![image](https://user-images.githubusercontent.com/44967630/78650048-a83e5c80-78be-11ea-8504-7a400c46f6f8.png)

**Comment by JiPiBi** [comment]
@SebSic 

Agree that is unclear if ESMS cases are confirmed or suspected, but I think that the cell bottom right is so fresh and answer to questions asked for a week , that you have to consider it as separated from the previous informations so the now 23620 case (before 22361 )  are not included in the confirmed cases (cell bottom left) 
But I recognized the communication is not good at all and it is pointed out in discussions channels in France

**Comment by SebSic** [comment]
I found the answer in the last situation point from SPF : ESMS cases counted are both probable and confirmed cases.
From ESMS specific epidemiological surveillance we have for april 6th : 23.620 cases - 3.079 death (those cases and deaths can be possible or confirmed imo).
My guess is only confirmed cases and deaths from ESMS surveillance are counted in Sante publique france "74.390 confirmed cases and 8.911 death" (for 6th of april)

**Comment by SebSic** [comment]
Other news : From the 8.911 deaths (at 2020/04/06) there are 2.417 death counted from ESMS (nusing homes) and 6.494 from hospitals.

**Comment by JiPiBi** [comment]
@SebSic  
yes, your values are the same that the ones  in  my picture above , but there is an issue about the  difference between 2417 and 3019 deaths  .

Maybe an explanation , but to be confirmed : ESMS is a generic term that contains boths old people (EPHAD)  and younger people (like ADAPEI if you heard of this name in France)   so the difference 3019- 2417 could be younger people . Questions are asked in France . Wait and see .

**Comment by JiPiBi** [comment]
If interested you can also see + 478 in ICU for last 24 hours , than means that 478 new people are put in ICU , to be compared to the + 94  in ICU between the 2 pictures above that corresponds to the number of occupied beds in ICU.  
But no news given about  fate of the 478-94 out of ICU for yesteray : dead or alive ..... Politic values ?

**Comment by JiPiBi** [comment]
The last one
![image](https://user-images.githubusercontent.com/44967630/78707343-c5038000-7910-11ea-95fe-e820f982ee7e.png)

I was confirmed today that the death values in ESMS is included in global death values : on the 4047 deaths for ESMS , 810 died in hospitals . So the 10328 is the global known value for the moment

**Comment by cedricbellet** [comment]
Who is the decision maker here? it's been 4 days, I can't see anyone in disagreement with fixing, and a couple of PRs in queue, yet nothing has changed in the data

**Comment by JiPiBi** [comment]
@cedricbellet 
Very good question :-)

**Comment by JiPiBi** [comment]
Précisions made now for deaths
![image](https://user-images.githubusercontent.com/44967630/78843177-61597f80-7a02-11ea-860d-38218341eba2.png)

**Comment by FrenchGu** [comment]
It seems like data have been corrected on JHU main graph but not in github's time_series_covid19_confirmed_global.csv
<img width="252" alt="JHU France" src="https://user-images.githubusercontent.com/63185707/78877322-f5523800-7a50-11ea-9f63-10ed1530b8bf.png">
![France-Github](https://user-images.githubusercontent.com/63185707/78877334-fb481900-7a50-11ea-8521-0e86e93fcba6.jpg)

**Comment by lucasiscovici** [comment]
Hello, 
Mistakes -> https://www.worldometers.info/coronavirus/country/france/

**Comment by JiPiBi** [comment]
![image](https://user-images.githubusercontent.com/44967630/78930218-07a99180-7aa4-11ea-9056-1bf768a690b3.png)

**Comment by JiPiBi** [comment]
Firsts informations about confirmations in ESMS  =
![image](https://user-images.githubusercontent.com/44967630/78937682-337f4400-7ab1-11ea-9ef7-36046b8d6235.png)

**Comment by cipriancraciun** [comment]
It appears the JHU team itself opened an issue on this topic #2094 

I would suggest contributing a summary of your findings there.

**Comment by alfkoehn** [comment]
Fixed: https://github.com/CSSEGISandData/COVID-19/issues/2094#issue-597470646 (this issue can be closed)
