### ISSUE TITLE
Data from a couple of countries seems to be missing in April 5th daily updates

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#2007]
Following countries show the same numbers as the day before:
- Japan
- Uruguay
- Congo (Kinshasa)
- Argentinia

there might be more

**Comment by alfkoehn** [comment]
Numbers from France are too high, see here: https://github.com/CSSEGISandData/COVID-19/issues/2005#issuecomment-609581242

**Comment by blisx264** [comment]
A lot of cases where nations are late or do not report and data is carried. over.. it's been occuring since data gathering started.

**Comment by amalic** [comment]
@blisx264 Are you part of the team collecting and aggregating the data?
