### ISSUE TITLE
Chicago new location or duplicate in 20200303 update?

### ISSUE THREAD

**Issue by ChrisPariso** [CSSEGISandData/COVID-19#202]
In today's data update, Cook County, Il now has two entries, one with lat/long "41.8781, -87.6298" (which has been in the data all along), and one with the lat/long "41.7377, -87.6976" (new in this update). As of 3/2/2020, both locations are listed as having 4 confirmed cases, 2 recoveries, and 0 fatalities.

This appears to be a duplicate record caused by a new lat/long pair, but I wanted to confirm before filtering it out of my analysis. If it is a duplicate, and not a new location, which coordinate pair will be used going forward? Thanks,

**Comment by CSSEGISandData** [comment]
We have updated the time series to reflect the correct value. Thank you.

**Comment by ChrisPariso** [comment]
Beautiful - thank you for the quick turnaround!
