### ISSUE TITLE
US recovered time-series is not available.

### ISSUE THREAD

**Issue by mehdihadi** [CSSEGISandData/COVID-19#2029]
Hi, 
Thanks for providing this nice repository.
I am developing a dashboards using your time-series data. This dashboard can produce dynamic map and needs all data for recovered, deaths and confirmed. For US the dashboard now produce only one dynamic point.
Why time-series data for "recovered cases" of US is not available? I tried to use daily data but there are several mistakes in name of provinces and also Lat and Long is not available in data sets of initial weeks.
If it is possible provide the series of recovered cases for US too. 
Regards.

**Comment by Lucas-Czarnecki** [comment]
JHU decided to stop providing data on recoveries in the US as there are "No reliable data source reporting recovered cases for many countries, such as the US."  See #1250

It is disappointing... I know. 

Please close this issue to help the folks at JHU from getting swamped with issues.

**Comment by mehdihadi** [comment]
Thanks Lucas for your answer, 
I hope Corona ends as soon as possible so we don't need statistics more.
