### ISSUE TITLE
Data discrepancy between John Hopkins interactive map and data in github files

### ISSUE THREAD

**Issue by ElsVK** [CSSEGISandData/COVID-19#2048]
The John Hopkins interactive map at https://coronavirus.jhu.edu/map.html refers to the files in this github repository yet the data shown on the map are different than the data in the cvs files. e.g. Belgium shows 2.035 deaths on the map (which is the correct official number) but the github file https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv shows 1.632 deaths to date. Why is there a discrepancy between the data? Is github not updated at the same frequency as the interactive map? Is the map using another data source?

**Comment by Mahks** [comment]
@Lucas-Czarnecki 

The URL I am using is https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

What is the URL for the web-data you mention?

**Comment by Lucas-Czarnecki** [comment]
@Mahks The data are organized differently in the **web-data** branch than the **master**. You can find a link to the web-data folder [HERE](https://github.com/CSSEGISandData/COVID-19/tree/web-data). 

You can find a raw url link to time series data on global deaths [HERE](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_time.csv)

**Comment by ElsVK** [comment]
Thanks a lot for your input, much appreciated. It was (at least to me) not clear that the data in this branch should be used rather than the master. Thanks!

Groetjes, Els
________________________________

**Comment by Lucas-Czarnecki** [comment]
No worries, happy to help :). Keep in mind both branches can be used. There are pros and cons to both. 

Cheers, 
LS

**Comment by Mahks** [comment]
@Lucas-Czarnecki Thanks for that URL. 

I was using "https://api.github.com/repos/CSSEGISandData/COVID-19/commits?path=csse_covid_19_data/csse_covid_19_time_series
to check if the data had changed.

I can't seem to find the equivalent commit data for /web-data/data/cases_time.csv
Or, if there is no commit info for an automated update, is there some other way to test for a change?

I also noticed that cases_time.csv is not updated as often as cases.csv, any idea why?
