### ISSUE TITLE
Add Japan Ministry of Health in data sources

### ISSUE THREAD

**Issue by tineko** [CSSEGISandData/COVID-19#206]
I think you should add the Japan Ministry of Health (https://www.mhlw.go.jp/index.html) in your data source. It hosts a page in English with an update table of cases within Japan.

**Comment by benmus** [comment]
Hello world

**Comment by benmus** [comment]
يحتاج إلي بعض الأدوات المهمة بشكل احترافي
https://www.mhlw.go.jp/index.html

**Comment by hailush** [comment]
[SampleTest.xlsx](https://github.com/CSSEGISandData/COVID-19/files/4297354/SampleTest.xlsx)

**Comment by ochomba** [comment]
Well done keep it up

**Comment by CSSEGISandData** [comment]
Thank you for the source. We will keep it in mind!

**Comment by prinudickson** [comment]
Hi Guys, 
I can assist. 
I am not exactly sure about the requirements.
