### ISSUE TITLE
Data for 4/7/2020 for Illinois is incorrect

### ISSUE THREAD

**Issue by hackerlikecomputer** [CSSEGISandData/COVID-19#2069]
The daily file for 4/7 shows Illinois having 12,271 cases. The actual number is 13,549.

**Comment by psynwavez** [comment]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-07-2020.csv

yes, cook county 4/6 and 4/7 have not changed

**Comment by nearridge** [comment]
Any idea why this discrepancy has occurred and not been corrected?

**Comment by agentdanger** [comment]
This should be updated now.

**Comment by agentdanger** [comment]
@hackerlikecomputer , please close this issue.
