### ISSUE TITLE
Wrong location of country

### ISSUE THREAD

**Issue by mkmdivy** [CSSEGISandData/COVID-19#2075]
Some of Long and Lat of countries are wrong

Congo (Brazzaville),Congo (Kinshasa) are located same
Mauritania locates in Niger

**Comment by yetzt** [comment]
Mauritania has the longitudinal hemisphere mixed up, Brazzaville and Kinshasa are really close to each other on the map though.

**Comment by mkmdivy** [comment]
The city Brazaville and Kinshasa are right next to each other but here they used term Congo (Brazaville) and Congo (Kinshasa) to indicate country Republic of Congo and DRC respectively. Since the confirmed case is not only limited those two capital cities it needs to be corrected I guess.

**Comment by CSSEGISandData** [comment]
Naming of countries is consistent with short-form naming scheme deployed by the US State Department.

**Comment by mkmdivy** [comment]
It is nothing about name of countries, location of country is wrong.

longitude and latitude of Congo (Kinshasa) and Mauritania locates not in its country.
