### ISSUE TITLE
France: again wrong value for confirmed cases (April 09 - 2020-04-09)

### ISSUE THREAD

**Issue by alfkoehn** [CSSEGISandData/COVID-19#2084]
Number in database here: 112950

Number in other data sources [1,2]: 82048

30902 cases too much, like yesterday where we also had 30920 cases too much.

I guess this is still due to also including potential cases, see the discussion here: https://github.com/CSSEGISandData/COVID-19/issues/2005

[1] https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-04-08.yaml
[2] https://dashboard.covid19.data.gouv.fr/

**Comment by joaopedrosantos** [comment]
It's 83k now at the dashboard.

**Comment by alfkoehn** [comment]
Fixed: https://github.com/CSSEGISandData/COVID-19/issues/2094#issue-597470646
