### ISSUE TITLE
Spain disappeared

### ISSUE THREAD

**Issue by martinedoesgis** [CSSEGISandData/COVID-19#2091]
Currently (15:37 UTC/GMT) Spain is not displayed on the map anymore :

![image](https://user-images.githubusercontent.com/34961989/78913228-b2935e80-7a56-11ea-9962-fb108464a5d6.png)

**Comment by louchios** [comment]
Seems to be back up.
![spain](https://user-images.githubusercontent.com/14114900/78925599-53871700-7a61-11ea-8ff6-a9f31b2a1e2e.png)
