### ISSUE TITLE
State of Illinois Deaths Not Updated 4/9/2019 (time_series_covid19_deaths_US.csv)

### ISSUE THREAD

**Issue by agentdanger** [CSSEGISandData/COVID-19#2100]
The state of Illinois in the U.S. is reporting 528 deaths according to the official state count.    The file time_series_covid19_deaths_US.csv is only recording 462 deaths, which is the same as yesterday.  That doesn't seem correct.

source:  https://coronavirus.illinois.gov/s/

**Comment by paolinic03** [comment]
Seems there is an issue with New York as well. April 6th is showing -253 deaths for that day and is throwing off entire cumulative and daily death counts for the entire US aggregate as the state is the epicenter.

**Comment by agentdanger** [comment]
I don't mind helping keep the Illinois data updated, if it needs to be.  Let me know how/if I can help.

**Comment by agentdanger** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/2060#issuecomment-611844988

Per the comment linked above, it looks like IL is providing a JSON with daily updates.  https://www.dph.illinois.gov/sitefiles/COVIDHistoricalTestResults.json

**Comment by SamPriolo** [comment]
This is the second time in 3 days this happened to Illinois.  I am beginning to think its intentionally left unresolved :)

**Comment by just2610** [comment]
Is there anything I can do to help? the data from the file for confirmed cases for Illinois is 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/41932947/79050934-dd043800-7c5f-11ea-8c31-8917bfd55883.png">

while the Illinois state website has 

<img width="247" alt="image" src="https://user-images.githubusercontent.com/41932947/79050967-13da4e00-7c60-11ea-8b69-1c85ff7601f6.png">

**Comment by agentdanger** [comment]
Confirming that this is now fixed.  Nice job!
