### ISSUE TITLE
France: April 9, data of confirmed cases wrong

### ISSUE THREAD

**Issue by alfkoehn** [CSSEGISandData/COVID-19#2105]
The data here says: 117749

Number in other data sources [1,2]: 86334

This is due to also taking into account potential cases in nursing homes here; discussions see [3], and an official comment from the data maintainer of this site see here [4].

[1] https://dashboard.covid19.data.gouv.fr/
[2] https://github.com/opencovid19-fr/data/blob/master/ministere-sante/2020-04-09.yaml
[3] https://github.com/CSSEGISandData/COVID-19/issues/2005
[4] https://github.com/CSSEGISandData/COVID-19/issues/2094

**Comment by cipriancraciun** [comment]
As you've observed this topic is already discussed on issue #2094 

Therefore in order to help the JHU team and keep things tidy, please consider closing this issue, and following and contributing to #2094

**Comment by alfkoehn** [comment]
> As you've observed this topic is already discussed on issue #2094
> 
> Therefore in order to help the JHU team and keep things tidy, please consider closing this issue, and following and contributing to #2094

The correct numbers were not given there, this is why I opened a new issue, but still, you are probably right
