### ISSUE TITLE
Colorado Data

### ISSUE THREAD

**Issue by just2610** [CSSEGISandData/COVID-19#2125]
Attached from Colorado DoH

<img width="388" alt="image" src="https://user-images.githubusercontent.com/41932947/79051696-39695680-7c64-11ea-84ca-797b83e258fe.png">

From the JH dataset, total cases:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/41932947/79051721-63227d80-7c64-11ea-8e7e-27b39ff463f1.png">

and for deaths:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/41932947/79051746-80574c00-7c64-11ea-9120-3135b606532b.png">

Not sure why these discrepancies have crept in. Would you pls do a clean up?

**Comment by jjbenes** [comment]
Hard to compare exponentials when we don't know exactly what time data were captured.
USAFacts  uses the same source you are using (https://covid19.colorado.gov/case-data) but the numbers are also different. They have 6324 listed on 4/10. At this moment, the CO website says 6510 cases through 4/9 (not 4/10), though the data was updated at 4pm on 4/10.

JHU: 6202
USAFacts: 6324 (supposedly from colorado.gov)
colorado.gov: 6510

From USAFacts
![Screen Shot 2020-04-11 at 1 53 10 PM](https://user-images.githubusercontent.com/62985029/79054696-e52a8c00-7bfb-11ea-9b7d-664879b4d24d.png)

colorado.gov
![Screen Shot 2020-04-11 at 1 57 01 PM](https://user-images.githubusercontent.com/62985029/79054743-5d914d00-7bfc-11ea-8230-06136ee5c3ce.png)

**Comment by just2610** [comment]
@jjbenes fair point. DoH data does move about. Is it possible to do a clean up with the DoH data after a few days and update the records on the GitHub? There are a range of issues, no doubt, but having diverging data sets is probably a worse outcome.
