### ISSUE TITLE
Germany showing lower number of total fatalities than previous day

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#2126]
see: [Google Sheet](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?usp=drivesdk)

**Comment by jcandy** [comment]
I can verify.  Last entry should (apparently) be 2871 not 2736
https://interaktiv.tagesspiegel.de/lab/karte-sars-cov-2-in-deutschland-landkreise/

**Comment by cgicgi** [comment]
Come on - it's easter. People tend to rise from the death on that day.

**Comment by jcandy** [comment]
It would be nice if this could get fixed and the issue closed.
