### ISSUE TITLE
Complete numerical errors in the dashboard?

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#213]
67.217 what?

Deaths & Recovered no more countries?

![dfsdf](https://user-images.githubusercontent.com/49625256/75824741-588ee180-5da4-11ea-81f5-d6cbbac5cdce.PNG)
![fgh](https://user-images.githubusercontent.com/49625256/75824743-59277800-5da4-11ea-9987-b73cd7d2dfa8.PNG)

Nice, it's magic. ;-)

**Comment by iceweasel1** [comment]
By the way, Germany has 218 (currently) confirmed cases the successor publishers are with sources. There are about 19 more that have already been confirmed internally, but are still waiting for the ministry's approval.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. If you are seeing issues with the dashboard you may need to clear your browser cache and refresh the page. The current status of the dashboard appears to be normal.
