### ISSUE TITLE
Global total confirmed no longer displaying accurately

### ISSUE THREAD

**Issue by bluef00ted** [CSSEGISandData/COVID-19#214]
The total worldwide confirmed is incorrect for both Desktop and Mobile links. It's displaying 67,217 even after I close browser and reload it. It should be approximately 91,000+. Did something happen?

Even when selecting 'Mainline China' which currently says 80,151, the 'Total Confirmed' goes back to the 67,217 number. 

This is similar to issue # [213](https://github.com/CSSEGISandData/COVID-19/issues/213) and [73](https://github.com/CSSEGISandData/COVID-19/issues/73) but a much greater discrepancy. Sorry if this is duplicate.

**Comment by dawenx** [comment]
probably some technical hiccup, pretty it will be corrected soon. you can check other sites for now.

**Comment by iceweasel1** [comment]
@bluef00ted Typed faster than looked at. ;-) 
Check this out: http://ncov.bii.virginia.edu/dashboard/

**Comment by bluef00ted** [comment]
Thanks @iceweasel1. I've had the University of Virginia bookmarked for a while now -- it's really well done and I love the time slider feature!

I'm impressed by the talent making both the CSSE and Virginia sites possible! I'm able to do my own simple stats like a rolling 10-day average of the death and recovery rates and see the rate of increase which isn't something you get (easily) from CDC or WHO for a non-researcher like myself.

We all owe CSSE a great deal! Thank  you!

**Comment by Fgazzelloni** [comment]
I found a gap of less than 19 000 between the 16 and the 17 of February, the table changed slightly, starting displaying just confirmed infections. Checking the data on git for both days can be found as a confirmed those ones considered by the WHO just suspected.
Sources: 
- https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200216-sitrep-27-covid-19.pdf?sfvrsn=78c0eb78_4
- https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200217-sitrep-28-covid-19.pdf?sfvrsn=a19cf2ad_2
