### ISSUE TITLE
daily_reports/04-12-2020.csv has wrong FIPS codes for some counties

### ISSUE THREAD

**Issue by ayanez17** [CSSEGISandData/COVID-19#2152]
"FIPS codes for counties in Alabama, Alaska, Arizona ... through Connecticut are all missing the leading zero in the FIPS. For example the FIPS code for Autauga, Alabama is 01001, but is recorded in the CSV as 1001." - @bbgvisualjournalist

https://github.com/CSSEGISandData/COVID-19/issues/2144#issuecomment-612711772

**Comment by CSSEGISandData** [comment]
Alfredo,

Thank you.  I believe this is corrected in the latest commit.  If it is still in error, please let me know.

**Comment by ayanez17** [comment]
Thanks!
