### ISSUE TITLE
100,000 confirmed cases in Okaloosa, FL (population 200,000)?

### ISSUE THREAD

**Issue by PeterDowdy** [CSSEGISandData/COVID-19#2166]
This line looks like it got an extra 100000 added to the confirmed column: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-13-2020.csv#L1813

**Comment by GerardoRTobar** [comment]
Wait so it is correct or incorrect?

**Comment by PeterDowdy** [comment]
This is incorrect.

**Comment by PeterDowdy** [comment]
Issue being resolved in https://github.com/CSSEGISandData/COVID-19/issues/2167
