### ISSUE TITLE
US Data incorrect for 2020-04-13 in time_series_covid19_confirmed_global.csv

### ISSUE THREAD

**Issue by BJReplay** [CSSEGISandData/COVID-19#2169]
In COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv the US has a figure of 682619 for 2020-04-03 (4/13/20 in the file).

This is clearly incorrect.

**Comment by BJReplay** [comment]
Root cause appears to be identified in https://github.com/CSSEGISandData/COVID-19/issues/2167 but not yet fixed in time series data.

**Comment by zoutpiel** [comment]
They just updated time series data but US still shows 682k.

**Comment by BJReplay** [comment]
> They just updated time series data but US still shows 682k.

Now fixed!
