### ISSUE TITLE
Data sourced for US deaths?

### ISSUE THREAD

**Issue by sdun2020** [CSSEGISandData/COVID-19#217]
I love the chart and have been following it since mid January! 

Where are you pulling your data source for # of US deaths? As of now, there should be 9 deaths (both in Washington state). See link below from WA dept of health website. Currently, your chart only show 7.

https://www.doh.wa.gov/Emergencies/Coronavirus

**Comment by arik-so** [comment]
Why did the US numbers go down by so much with today's update? Cases are down from 101 to 28, and deaths are down from 6 to 1. Recoveries went from 7 to 0.

**Comment by CSSEGISandData** [comment]
Sorry for the delay. We have updated the dashboard to reflect the latest case counts.
