### ISSUE TITLE
France showing 6514 fewer Reported cases in April 14th daily update than previous day

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#2188]
see [comment](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?disco=AAAAJafLkZ0) in my Google Sheet.

**Comment by just2610** [comment]
France showing **negative 6,514**. worldometer shows 6524 positive ... please fix..this error is more than 10% of total new cases

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/41932947/79286665-e4437400-7ef3-11ea-8e4b-5fb5eba320b2.png">

**Comment by gsjennings** [comment]
France confirmed numbers went down to 130,253 from 136,779 in JH data today. This seems unlikely.

**Comment by just2610** [comment]
Saw a fresh update to the dataset was done a few minutes ago. France still in error..

**Comment by zubair0** [comment]
Same issue is there in the daily reports file as well.
