### ISSUE TITLE
Luxembourg is showing 2 fatalities less in April 14th daily update file than previous day

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#2189]
see [comment](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?disco=AAAAJafLkZ4) in my Google Sheet.

**Comment by alfkoehn** [comment]
the number of deaths included in this database agrees with the official number from the Luxembourg government [1], so maybe the number from the day before yesterday was wrong.

https://msan.gouvernement.lu/en/dossiers/2020/corona-virus.html

**Comment by amalic** [comment]
Could also be possible
