### ISSUE TITLE
Maryland and New Hampshire showing fewer Reported cases in daily update file from April 14th

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#2191]
See [comment-1](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?disco=AAAAJafLkaM) and [comment-2](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?disco=AAAAJafLkaQ) in my Google Sheet.

**Comment by TracyVargo** [comment]
And Maryland's reported total deaths dropped to 227 from 262. Something weird happened somewhere.
