### ISSUE TITLE
Kentucky and Maryland showing fewer Fatalities in daily update file from April 14th than the day before

### ISSUE THREAD

**Issue by amalic** [CSSEGISandData/COVID-19#2192]
See [comment-1](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?disco=AAAAJafLkac) and [comment-2](https://docs.google.com/spreadsheets/d/15OKNhZosR9xb0gShWtKw0P2toEN5AabZfp6kfnsVEKs/edit?disco=AAAAJafLkag) in my Google Sheet.

**Comment by just2610** [comment]
Worldometers shows 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/41932947/79294481-de0bc280-7f08-11ea-9456-b9f2c952d60e.png">
