### ISSUE TITLE
Last Update column question

### ISSUE THREAD

**Issue by Shane073** [CSSEGISandData/COVID-19#222]
Trying to understand the "Last Update" column.

Does the "Last Update" column report the last actual update of data, or the last case reported?

Some random rows below:

Hubei	Mainland China	2020-03-03T11:43:02	- Last update 12 hours ago?
Afghanistan		                2020-02-24T23:33:02  	- No update since 24th Feb?
Tibet	Mainland China	2020-02-12T06:43:02  	- No update since 12th Feb?
Vietnam			                2020-02-25T08:53:02	- No update since 25th Feb?
Greece			                2020-03-01T23:23:02	- No update since 1st March?
Qinghai	Mainland China	2020-02-21T04:43:02	- No update since 21st Feb?

So are these dates/times above when the last case was diagnosed for that country, or was it the last time that country provided an update?

Thanks for your help.

**Comment by Shane073** [comment]
@CSSEGISandData when you have a spare moment can you answer the above question please?

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. The last update column is the last time that countries case count changed (e.g. If country x went from 10 confirmed cases to 20 confirmed cases today, the last update time would be updated to todays date).
