### ISSUE TITLE
All data for Russia is shown only in one point

### ISSUE THREAD

**Issue by omgthatsjackie** [CSSEGISandData/COVID-19#2221]
There is only one point for all infected Russians, however they are in different cities. Please fix it so we can see the data by cities-)

![Annotation 2020-04-15 235224](https://user-images.githubusercontent.com/61295047/79387350-362bde80-7f74-11ea-9469-26c554149e28.jpg)

**Comment by codeyourdream** [comment]
Currently checking the possible ways to get the data by regions (and for Moscow separately).
It's available in various Internet resources, but haven't found it in a proper format anywhere on the official websites.

**Comment by mstrokin** [comment]
Here's the Python script for fetching this data from Yandex (Which gets its data from official sources)

https://github.com/grwlf/COVID-19_plus_Russia/blob/master/python3/src/covid19ru/fetch.py

**Comment by grwlf** [comment]
See also https://github.com/CSSEGISandData/COVID-19/issues/1262
