### ISSUE TITLE
Tennessee & Colorado New Cases 15/4 incorrect

### ISSUE THREAD

**Issue by just2610** [CSSEGISandData/COVID-19#2225]
Here's the worldometer data
<img width="639" alt="image" src="https://user-images.githubusercontent.com/41932947/79400944-4ebee780-7fba-11ea-84a2-0c2323acafe3.png">

Here's the summary from the dataset
<img width="520" alt="image" src="https://user-images.githubusercontent.com/41932947/79401014-73b35a80-7fba-11ea-89f6-23b3a55efae5.png">

Colorado shows 6 and Tennessee as 0...

Pls do correct.

**Comment by whimsql** [comment]
confirmed...TN feed did not update. 
4/14 and 4/15 are showing the same number of confirmed cases.
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-14-2020.csv

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-15-2020.csv

4/15 should be somewhere in the neighborhood of 6,079 for TN.

TN releases their numbers once a day here: 
https://www.tn.gov/health/cedep/ncov.html

screenshot from 4/15
![image](https://user-images.githubusercontent.com/41055788/79454536-66e23700-7fb9-11ea-87a9-e8da977f9f90.png)
