### ISSUE TITLE
Negative value for France 4/14/20 infection

### ISSUE THREAD

**Issue by aslamiqbal** [CSSEGISandData/COVID-19#2235]
date 4/14/20, value -6.5k
![negative value](https://user-images.githubusercontent.com/2275744/79411985-1fae7300-7fc6-11ea-8d2e-ae66e66a822b.png)

**Comment by alfkoehn** [comment]
This has already been discussed, see e.g. https://github.com/CSSEGISandData/COVID-19/issues/2202#issue-600039146, so no need to open a new issue (i.e. you can close this one).

**Comment by aslamiqbal** [comment]
duplicate
