### ISSUE TITLE
France time series data large errors on 4/4 and 4/7

### ISSUE THREAD

**Issue by Aureuum** [CSSEGISandData/COVID-19#2237]
France time series data are only correct through 4/3.
The error on 4/4 is of the order of 22k and on 4/7 about 7k excess.
Check with Wikipedia's page about France.
Would appreciate if you correct this.
Thanks.

**Comment by alfkoehn** [comment]
This has been fixed, see https://github.com/CSSEGISandData/COVID-19/issues/2094#issue-597470646 (issue can be closed)

**Comment by Aureuum** [comment]
Thank you, yes, I'll close it.
