### ISSUE TITLE
Official source for Sweden

### ISSUE THREAD

**Issue by 0x9fff00** [CSSEGISandData/COVID-19#224]
Here is the official source by the Public Health Agency of Sweden (Under “Antal fall i Sverige”): https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/aktuellt-epidemiologiskt-lage/

As of 4 March 10:13 CET there were 32 cases, there is also a 33rd case in Skåne that hasn’t been added yet.

**Comment by CSSEGISandData** [comment]
Thank you for the source! We will keep it in mind.
