### ISSUE TITLE
Major discrepancy with official data for EU/Sweden for daily deaths number

### ISSUE THREAD

**Issue by PavelGorbanj** [CSSEGISandData/COVID-19#2241]
As per official data from The Public Health Agency of Sweden's [report](https://www.arcgis.com/sharing/rest/content/items/b5e7488e117749c19881cce45db13f7e/data)
 (that's direct link to Excel data referred from agencie's [website](https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/bekraftade-fall-i-sverige)), Apr 14th had 31 deaths, and 15th - 6 (see tab with daily deaths "Antal avlidna per dag").

In your time [series data](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) CSV and sample daily [reports](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-14-2020.csv) CSV for 14th shows +114 deaths, and for 15th +170 that drastically differs from official 31 and 6 respectively.

As many others are using data from you datasource, can you please make corrections?

At the same time, cumulative amout of deaths as of today seems to be correct (official 1203) so I believe the issue is with daily breakdown.

Just in case ECDC data is the same as yours and contains the same distortion, https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

One can verify if www.folkhalsomyndigheten.se is official source by checkin reference to it from government's https://www.gov.se/myndigheter-med-flera/folkhalsomyndigheten/

**Comment by PavelGorbanj** [comment]
Root cause of the discrepancy in daily numbers is that Public Health Agency of Sweden constantly changes old data. For example, if to compare data from their excel for 17th vs 16th, then one will find that in newest file they've added +20 deaths for 1st week of April, and +120 for Apr 1-15.

**Comment by ahnt** [comment]
Stupid question, but do you have the daily files they bring out, basically they should have one file per day, and I would love to get all the files?
Cheers Arend

**Comment by PavelGorbanj** [comment]
Have no idea
