### ISSUE TITLE
Update for India

### ISSUE THREAD

**Issue by abhasdudeja** [CSSEGISandData/COVID-19#225]
Add per Union Ministry of Health, India, there are a total of 28 confirmed positive cases of covid-2019, after a group of 16 Italians and an Indian driver from Jaipur are now confirmed to have been infected with coronavirus.
`https://infographics.channelnewsasia.com/covid-19/map.html`
You can use this source to update your data.

**Comment by CSSEGISandData** [comment]
Thank you. Data updated.
