### ISSUE TITLE
Nearly 3k deaths in New York City?

### ISSUE THREAD

**Issue by albertid** [CSSEGISandData/COVID-19#2255]
The difference between yesterday and today seems off.

**Comment by lmirny** [comment]
Looks like the correct number of fatalities today should be 12192 
https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Fatalities?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n
