### ISSUE TITLE
Official source for Brazil.

### ISSUE THREAD

**Issue by GuilhermeMorais** [CSSEGISandData/COVID-19#226]
Hello Guys,

   Below you can find the official information regarding the virus by State in Brazil:
     [Official Web Site for Corona Virus](http://plataforma.saude.gov.br/novocoronavirus/)
  In the first table, you will find all the information you need.

**Comment by darkmoonzika** [comment]
hello 3 case confirmed
https://brasil.estadao.com.br/ao-vivo/coronavirus-no-brasil

**Comment by CSSEGISandData** [comment]
Thank you for the recommendation. We will look into adding a more granular level for other countries in the future.
