### ISSUE TITLE
Only 4 recoveries in Australia/NewSouthWales since 13 Feb

### ISSUE THREAD

**Issue by benflips** [CSSEGISandData/COVID-19#2263]
Must be incorrect (they have 2897 cases), and appears to be at odds with the numbers on the COVID-19 Dashboard. (Thanks for all your hard work, by the way; it's an incredibly important resource).

**Comment by antbytes** [comment]
April 17 stats blow it out of the water !

**Comment by benflips** [comment]
Yeah, miracle day! I feel sorry for those poor folks who had it since Feb though :-(

NSW has some reporting improvements to make, apparently.

Excuse the brevity: sent from my phone.

On 18 Apr 2020, at 13:43, antbytes <notifications@github.com<mailto:notifications@github.com>> wrote:


April 17 stats blow it out of the water !
