### ISSUE TITLE
Case Data reported incorrectly for Illinois

### ISSUE THREAD

**Issue by ChatsHD** [CSSEGISandData/COVID-19#2268]
NY Times GitHub reported 

04/08/2020 | Illinois | 17 | 15078
04/09/2020 | Illinois | 17 | 16422

Current Dataset reported 04-09-2020 as 1

**Comment by agentdanger** [comment]
This should be good to go now.  Check it out.

**Comment by agentdanger** [comment]
@ChatsHD , please close this issue.  It's solid now.

**Comment by ChatsHD** [comment]
Apologies on the late reply. Closed
