### ISSUE TITLE
April 18 Data Not Yet Updated

### ISSUE THREAD

**Issue by just2610** [CSSEGISandData/COVID-19#2276]
The data for Apr 18 has not yet been refreshed. Just checking in to prompt someone to check the automated script.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/41932947/79675135-d81f2580-8217-11ea-9765-67d2912fed32.png">

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/41932947/79676411-80cd8500-8218-11ea-9b0a-064b87b204dc.png">

**Comment by Lucas-Czarnecki** [comment]
Same thing is true for the daily reports.

**Comment by marceloctorres** [comment]
It is true

**Comment by just2610** [comment]
@marceloctorres just checked the global timeseries for confirmed and deaths. last date is still April 17

**Comment by cptrguru** [comment]
Bump.

Still no daily data at 1 hour past normal upload time.

**Comment by cnehring2306** [comment]
Confirm. Still no data.

**Comment by gezhao** [comment]
Yeah no data for 4/18 in daily reports

**Comment by gezhao** [comment]
Really appreciate your work, great team...your data was organized pretty well usually...

**Comment by ash** [comment]
It appeared in daily files now.

**Comment by Lucas-Czarnecki** [comment]
Daily report is up. The rest is probably on its way

**Comment by Niketsoni** [comment]
Did anyone see the change in data formatting?

**Comment by agentdanger** [comment]
The time series still hasn't been updated.  Well past the normal upload time.

**Comment by cptrguru** [comment]
> Did anyone see the change in data formatting?

Yeah, whoever is in charge of this project obviously has never worked in I.T.  Data consistency and professionalism isn't in their repertoire.  I've spent a ton of hours just putting in coding exceptions to this point due to their lack of discipline.

I've already started a new set of code to change to https://covidtracking.com/api, who has the right idea.  Their numbers are slightly behind, but very consistent and verified sources.

**Comment by agentdanger** [comment]
Confirmed that the time series global file is still 3 hours old and contains yesterday's data.

**Comment by Lucas-Czarnecki** [comment]
The daily report has just been updated (again). It has been restored to JHU's prior data format. Looks good.

**Comment by chuckcerrillo** [comment]
> The daily report has just been updated (again). It has been restored to JHU's prior data format. Looks good.

Thanks for the heads up man. I was about to pull out my hair thinking I had to reformat on my end.

**Comment by GerardoRTobar** [comment]
THey just updated the data right now!

**Comment by agentdanger** [comment]
Confirmed, updated.

**Comment by Lucas-Czarnecki** [comment]
No worries @chuckcerrillo . If you ever need it, I maintain a stable repo of JHU's data [HERE](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE). Data format does not change.

**Comment by just2610** [comment]
All looking good. New York data looks off - new deaths of 540. Could be a one time catch up.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/41932947/79677861-01e04880-8228-11ea-994e-5a0b0d043f01.png">

**Comment by chuckcerrillo** [comment]
> No worries @chuckcerrillo . If you ever need it, I maintain a stable repo of JHU's data [HERE](https://github.com/Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE). Data format does not change.

You are a legend! Thanks for this mate!

**Comment by just2610** [comment]
Thanks to the team - see that they have also corrected historical records - see errata file. Kudos to you guys for all the hard work.
