### ISSUE TITLE
4/19 Daily Report Not Yet Updated

### ISSUE THREAD

**Issue by ei-JoanneT** [CSSEGISandData/COVID-19#2290]
The daily report for Apr 19 has not yet been updated. Is there any data change that I miss?
![image](https://user-images.githubusercontent.com/51304426/79703703-67115980-827b-11ea-985b-62527823d6d5.png)

**Comment by cnehring2306** [comment]
I was just about to ask the same question.....

**Comment by cptrguru** [comment]
It was the same way yesterday.  They were about an hour and a half late on 4/18.  Be prepared for data format changes again... it tends to be par for course when they run late.

**Comment by TrungMC** [comment]
The Time series does have 19/4. I'm converting my charts to use the time series

**Comment by cptrguru** [comment]
Daily just landed.  Woot!

**Comment by blisx264** [comment]
Australia Duplicated.

**Comment by Lucas-Czarnecki** [comment]
Everything looks good, except for us state-level data (csse_covid_19_daily_reports_us), which has not been uploaded yet.  #2292
