### ISSUE TITLE
No new data for Australia for 3 days now

### ISSUE THREAD

**Issue by jamesbelsey** [CSSEGISandData/COVID-19#2301]
There have been no updates to the data for Australia for 3 days now. This is across all states and territories. Is there an issue with the way this data is captured?

**Comment by blisx264** [comment]
There have been duplicates along the way, this is the first 3 day series that needs correction, our data is being updated but not in the series

**Comment by BJReplay** [comment]
@jamesbelsey this should be OK to close now - they seem to have fixed things.

**Comment by jamesbelsey** [comment]
@BJReplay Done, thanks for the reminder.
