### ISSUE TITLE
Australia numbers not updated since 19th Apr

### ISSUE THREAD

**Issue by dayalpetit** [CSSEGISandData/COVID-19#2302]
Time series data sets (confirmed/recovered/deaths) have same numbers for Australia since 18th April, could someone advise if i'm missing something?

**Comment by zoutpiel** [comment]
Yes this is a problem - not accurate

**Comment by stefancaspersz** [comment]
what's going on?

**Comment by zoutpiel** [comment]
> what's going on?

Australian state numbers haven't been updated, but there are definitely new cases

**Comment by stefancaspersz** [comment]
yes - definitely more cases and deaths too:
https://www.health.gov.au/news/health-alerts/novel-coronavirus-2019-ncov-health-alert/coronavirus-covid-19-current-situation-and-case-numbers

**Comment by blisx264** [comment]
https://covid-19-au.com/ - Monash Uni Victoria has been collecting independently.

**Comment by ralph-holland** [comment]
Will some body be able to look into restoring the processing for the Australian numbers please?

I have confirmed that at least the Known Case and Death numbers are making the WHO sitreps.

**Comment by dayalpetit** [comment]
These are the latest confirmed numbers as per health.gov.au

Australian Capital Territory | 104
New South Wales | 2,971
Northern Territory | 27
Queensland | 1,024
South Australia | 437
Tasmania | 202
Victoria | 1,336
Western Australia | 546
Total | 6,647

**Comment by simonk83** [comment]
Yep, I'm thinking of switching to this API unless anyone has any better suggestions: https://rapidapi.com/Gramzivi/api/covid-19-data

**Comment by blisx264** [comment]
Hard to understand why our data would not be valuable for best best scenarios, I guess we'll have to wait and see. A valid response to the situation would be appreciated sooner than later

**Comment by blisx264** [comment]
https://covid-19-au.com/

Im going to back date my data from the Monash team right now. They're on github too

**Comment by chuckcerrillo** [comment]
> https://covid-19-au.com/
> 
> Im going to back date my data from the Monash team right now. They're on github too

Can you share link to their repo?

**Comment by simonk83** [comment]
Here it is Chuck:

https://github.com/covid-19-au/covid-19-au.github.io

**Comment by chuckcerrillo** [comment]
> Here it is Chuck:
> 
> https://github.com/covid-19-au/covid-19-au.github.io

cheers

**Comment by BenAveling** [comment]
There's been a jump in the number of Australian cases - to 6661. I assume that's the right number for the day but we still have a few missing days, meaning new cases appear to go flat then suddenly spike up.

date      confirmed      deaths      delta_confirmed      delta_deaths:

2020-04-18      6547 67 25 1 5
2020-04-19      6547 67 0 0 4
2020-04-20      6547 67 0 0 5
2020-04-21      6547 67 0 0 4
2020-04-22      6547 67 0 0 5
2020-04-23      6661 75 114 8 4

Be good if someone could backfill the missing days.

**Comment by dayalpetit** [comment]
It is a relief now the data has been fixed, closing this issue. Thanks JHU team for updating it.
