### ISSUE TITLE
Other country data mingle with US

### ISSUE THREAD

**Issue by angelovescio** [CSSEGISandData/COVID-19#2311]
You have China and the UK, amongst others in your US Daily reports for 4/18 and 4/19. Please correct it

**Comment by joshterrill** [comment]
@angelovescio I can create a pull request and submit it for the repo owner to fix, just to make sure I'm looking at the same thing you are, you're talking about this in 4/18 and 4/19's data, starting at line 60?

https://github.com/joshterrill/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-18-2020.csv#L60

 https://github.com/joshterrill/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/04-19-2020.csv#L60

**Comment by angelovescio** [comment]
Yes, that was it. Thank you.
