### ISSUE TITLE
County/ City Names for US Caess

### ISSUE THREAD

**Issue by chrisleboa** [CSSEGISandData/COVID-19#232]
Hi all, 
   Thank you for your effort and time in making this information available and up to date. I was trying to parse the US data to the county level and am finding that some f the data is listed as cities while other data is provided on the city level.  For California in particular the singular Berkeley case should be a part of  Alameda County. I was wondering if you would be add USA cases with consistency as to the county or city level that they are from or if you need help making  a script for that.   
    Thanks again

**Comment by CSSEGISandData** [comment]
Thank you for your input! We are working to change all of the city locations to their appropriate counties.
