### ISSUE TITLE
Australia: No updates for 5 days!

### ISSUE THREAD

**Issue by zoutpiel** [CSSEGISandData/COVID-19#2321]
Folks, can anyone advise if this is going to be fixed? 
Most states have not had any updated data for 5 days so all reporting has become redundant.

**Comment by BJReplay** [comment]
And also https://github.com/CSSEGISandData/COVID-19/issues/2301.  But no response to those, hard to know if the team is aware of this, what the root cause is, and if there is anything we can do to assist.

**Comment by zoutpiel** [comment]
> And also #2301. But no response to those, hard to know if the team is aware of this, what the root cause is, and if there is anything we can do to assist.

Yes exactly - once they travel down the list without response you wonder if being resolved!

**Comment by joshterrill** [comment]
I agree, I wonder if there's anything that the community can do to lend a hand with getting some of this cleaned up and updated. I just tweeted them asking, we'll see if they respond.

**Comment by thomas-jeffery** [comment]
yes, would be good to sort this out

**Comment by ralph-holland** [comment]
I have now been forced to give up on JHU as a data feed and switched to manual processing of the Monash University dashboard so I can calculate Growth Factor - sad. 
All I wanted was a live feed so I can automate it at my dashboard, instead I am manually processing again.

https://covid-19-au.com

**Comment by blisx264** [comment]
> I have now been forced to give up on JHU as a data feed and switched to manual processing of the Monash University dashboard so I can calculate Growth Factor - sad.
> All I wanted was a live feed so I can automate it at my dashboard, instead I am manually processing again.
> 
> https://covid-19-au.com

It might be a matter of priority for the US, there's surely going to be a lot of pressure on the team and they've done a good job to date. Ill update my tables directly from .gov.au departments and the Monash team, have been on it since day one as well.

**Comment by joshterrill** [comment]
It appears that the data on their dashboard is correct, it’s just this exported data in github has some issues with it.

**Comment by blisx264** [comment]
> It appears that the data on their dashboard is correct, it’s just this exported data in github has some issues with it.

Nup, seems like Australian time series not updated .

**Comment by CaptDaags** [comment]
Data set still not updated as of 22/04/2020. Its now pretty useless.

**Comment by BenAveling** [comment]
There are a couple of alternatives mentioned in #2302 - I'd check those out before going back to doing things manually. 

If we do have to go manual, we should think about forking this repository and adding the Australian data to it. I'd rather that didn't happen, but if it's what we have to do, better to do it and share the effort rather than each doing it for ourselves.

**Comment by CSSEGISandData** [comment]
We have located the issue in our sourcing and have manually updated the time series table.

**Comment by BJReplay** [comment]
I can't re-open this, but the recovered data is still unchanged since 18 April, with another 1000 recovered since that date.  I'm going to open a new issue (since that's all I can do), but mention this issue so hopefully it gets noticed quickly.
