### ISSUE TITLE
US NJ counties - half are not updated on 04-21-2020.csv

### ISSUE THREAD

**Issue by rahmatiangit** [CSSEGISandData/COVID-19#2326]
Following not-updated counties have the same infection count for 04-21-2020.csv and 04-20-2020.csv .  note the alphabetic order..

**updated**
----------
Atlantic
Bergen
Burlington
Camden
Cape
Cumberland
Essex
Gloucester
Hudson

**not updated**
------------
Mercer
Middlesex
Monmouth
Morris
Ocean
Passaic
Salem
Somerset
Sussex
Union
Warren

Big thanks for collecting all the data (even with some errors here and there)

**Comment by rahmatiangit** [comment]
This issue is fixed and should be closed

**Comment by lojic** [comment]
@rahmatiangit if you opened the issue, and you feel it's fixed, you should be able to close it yourself. This will help reduce clutter in open issues.
