### ISSUE TITLE
Corrupt data France 22th  lower than 21th

### ISSUE THREAD

**Issue by mendes-jom** [CSSEGISandData/COVID-19#2336]
I just noticed on today  time_series_covid19_confirmed_global.csv
For line 184:
Province/State | Country/Region | Lat          | Long    | 4/21/20 | 4/22/20
                       | France                | 46.2276 | 2.2137 | 158050 | 155860
Value for  the 22th is lower  than for the 21th..
Thanks for checking

**Comment by yetzt** [comment]
thats what happens since @CSSEGISandData decided to include speculative data.

**Comment by traut21** [comment]
No need to open a new issue - search for France first
https://github.com/CSSEGISandData/COVID-19/issues/2340
