### ISSUE TITLE
Confirmed cases in France decreased?

### ISSUE THREAD

**Issue by ManchesterWuer** [CSSEGISandData/COVID-19#2340]
The number of confirmed cases of France in 4/22/20 is lower than that in 4/21/20，is there a reason？

**Comment by ash** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/2226

**Comment by WildH0g** [comment]
I don't know, they've been having issues with France for a while now and they can't seem to fix it. I might have to switch to a different dataset as reliable figures for France are extremely important to me.

**Comment by JiPiBi** [comment]
French authorities regognized that there have been issues in the nursing homes cases , counted twice. 
But as JHU takes into account confirmed and suspected , the values in French official dashboard is different

![image](https://user-images.githubusercontent.com/44967630/80100704-9d4b2380-8570-11ea-925c-f7fc287afab2.png)

**Comment by ManchesterWuer** [comment]
@JiPiBi I got it, so there has been counting issue. Thanks.

**Comment by ManchesterWuer** [comment]
@WildH0g Maybe other data sources can help you, such as ECDC.

**Comment by yetzt** [comment]
As it was stated many times, @CSSEGISandData counts *probable* cases as *confirmed* cases for france. Those are speculative and decreased, so their total for france decreased as well, resulting in a negative number of new cases. 

![Screenshot](https://imgur.com/xVC2vCO.png)
