### ISSUE TITLE
Australian data is not getting updated from 19th

### ISSUE THREAD

**Issue by 007muditha** [CSSEGISandData/COVID-19#2341]
The data set of Australia seems to be not updating from 19th April. 
It says Recovered, Confirmed and death counts are 0 for last 4 days but the actual numbers have risen from around 150.

**Comment by benjaminburges** [comment]
I can also confirm that this is occurring.

The sum of cases has been 6547 since 18/04/2020.
The sum of deaths has been 67 since 18/04/2020.

**Comment by thepost** [comment]
Yep, I have had to update it manually over the past few days. Curious as to why, as it seems like the JH CSSE dashboard is still being updated.

**Comment by NightDragon1** [comment]
> 
> 
> Yep, I have had to update it manually over the past few days. Curious as to why, as it seems like the JH CSSE dashboard is still being updated.

Would you like to share a update for us?

**Comment by thepost** [comment]
> > Yep, I have had to update it manually over the past few days. Curious as to why, as it seems like the JH CSSE dashboard is still being updated.
> 
> Would you like to share the data with us?

I've been updating to [this spreadsheet](https://docs.google.com/spreadsheets/d/1w7KqWPsNcpLcCKOkvBNG8a2nwCN5QO3yDyCdcvW38cc/edit#gid=503876971&range=A133). I'm not part of the contribution team for this repo.

**Comment by BJReplay** [comment]
Tagging duplicate issues https://github.com/CSSEGISandData/COVID-19/issues/2301, https://github.com/CSSEGISandData/COVID-19/issues/2302, https://github.com/CSSEGISandData/COVID-19/issues/2321 in the hope that the contribution team notice one of these issues, and ask for help if needed in fixing this data.

**Comment by NightDragon1** [comment]
> I've been updating to [this spreadsheet](https://docs.google.com/spreadsheets/d/1w7KqWPsNcpLcCKOkvBNG8a2nwCN5QO3yDyCdcvW38cc/edit#gid=503876971&range=A133). I'm not part of the contribution team for this repo.

No, but you could create a pull request toward it ;)

**Comment by jspanos71** [comment]
Not much point in submitting a PR.  They do not seem to accept them or respond to issues.

**Comment by NightDragon1** [comment]
> Not much point in submitting a PR. They do not seem to accept them or respond to issues.

No - but but all others using the data could apply your fix.

**Comment by thepost** [comment]
I'm confused. This doesn't solve the problem raised in the ticket, which is that the data from their own [dashboard here](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) (this is a public site, anyone can access it) is not getting updated to their CSV everyday. 

I have no idea where they're extracting the data from to the CSV. This is going to be a continual problem, until the data source is corrected, it's not resolved from 1 PR.

**Comment by NightDragon1** [comment]
I asked you if you would share your fix/data with us. Even if they don't take care of or merge it into the data itself, everyone else downloading the data here can apply your patch to the base and use it.

I think your correction - even if not merged - is better than no correction at all.

**Comment by rsheptolut** [comment]
I've had to switch to the Our World In Data's dataset because of this https://github.com/owid/covid-19-data

**Comment by BJReplay** [comment]
@007muditha this should be OK to close now.

**Comment by 007muditha** [comment]
@BJReplay  I was waiting till the Recovered counts to get corrected. Verified and closing the issue. Thank you for the update.
