### ISSUE TITLE
Population column missing

### ISSUE THREAD

**Issue by CyrilEstok** [CSSEGISandData/COVID-19#2342]
Only yesterday, there was a 'Population' column both in time_series_covid19_confirmed_US.csv and time_series_covid19_deaths_US.csv

I cannot find it anymore, could you take a look where it dissapeared?

**Comment by jspanos71** [comment]
I save copies of the files each day and there was not (and has not been) a population column in the time series **confirmed** file (US or Global).  There is a population column in the UID_ISO_FIPS_LookUp_Table and in the time series **deaths** US (only).
