### ISSUE TITLE
MISSING RECOVERY FIGURES FOR US STATES/COUNTIES

### ISSUE THREAD

**Issue by gcamp-hearst** [CSSEGISandData/COVID-19#2345]
Is anyone else missing recovery rates at the national/county levels for the US? 

Not seeing in:

Cases_time.csv
Cases.csv
Cases_state.csv (missing following):

Province_State | Recovered
-- | --
Alabama |  
American Samoa |  
California |  
Colorado |  
Connecticut |  
Florida |  
Georgia |  
Illinois |  
Indiana |  
Kansas |  
Louisiana |  
Massachusetts |  
Mississippi |  
Missouri |  
Nebraska |  
Nevada |  
New Jersey |  
North Carolina |  
Ohio |  
Oregon |  
Pennsylvania |  
Puerto Rico |  
Washington |  
Wisconsin |  

Wondering if next commit will fix? Thoughts?

**Comment by atz** [comment]
See #2339

**Comment by cancerousname69** [comment]
#2339 does already cover the issue. There is no need to open another issue for the exact same thing. Please close this issue and check the existing issues beforehand.
