### ISSUE TITLE
Automated time series data not available?

### ISSUE THREAD

**Issue by agentdanger** [CSSEGISandData/COVID-19#2349]
Did we change the cadence of automated updates today?  I usually have new data by 7pm CST.

**Comment by just2610** [comment]
Every time errata is fixed, I've noted that the update is delayed. Errata.csv was updated a couple of hours back:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/41932947/80161846-3d9e5800-8604-11ea-9047-463175089f77.png">

and the daily files are still showing data as of the 22 of April

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/41932947/80161908-67577f00-8604-11ea-9414-5e84b71471bc.png">

Please can the team look at this...

**Comment by Lucas-Czarnecki** [comment]
It's a reoccurring issue. See, for example, #2290. Daily reports are also affected. 

Based on past experience, data should be up later today.

**Comment by agentdanger** [comment]
Thanks, @Lucas-Czarnecki .  I'll close this once the data is available.  Prefer the reliability; but understand it's a process that doesn't necessarily follow our expectations every time.

**Comment by agentdanger** [comment]
Is this issue being actively tracked, or can I go to sleep?

**Comment by just2610** [comment]
@agentdanger not sure of that. hopefully the excellent team at JH are tracking this.

**Comment by GerardoRTobar** [comment]
What is happening up to this time @CSSEGISandData ??

**Comment by ebwinters** [comment]
something with the errata file probably throws off the pipeline. In my experience using this data, the new files will be online before midnight EST

**Comment by agentdanger** [comment]
Sigh...  I'll wait.  Thanks, @ebwinters

**Comment by maisonml** [comment]
@CSSEGISandData Can someone from the team please provide an update on this? Thank you.

**Comment by nuezj** [comment]
Is there any update regarding the lack of automated data of April 23?

**Comment by JieChangke** [comment]
@CSSEGISandData Anyone tracking this issue?  ask for all buddies waiting now, thank you :)

**Comment by agentdanger** [comment]
Since working with this data, this is the longest I've waited for an update.  Just saying.

**Comment by GerardoRTobar** [comment]
Same. I think the longest they have taken is 1h30min of delay. I think we should not expect any update for today anymore...

**Comment by agentdanger** [comment]
Agreed, hopefully we improve in the future.  Not sure how important we are in the scheme of things but JHU has analyst who are using this data to try to make a difference.  The ladies and gents doing these updates are appreciated; hopefully your users adding value to this data are appreciated as well.

**Comment by CSSEGISandData** [comment]
Apologies for the delay.  Job should go at or near midnight EST.

**Comment by dianelos** [comment]
I am also waiting. Incidentally I am putting up enriched spreadsheets ready to play with at www.pandemic-data.org

**Comment by prabindh** [comment]
Another eager user waiting for the data. My analysis at - https://colab.research.google.com/drive/1wY2puKXbvL3quvFAmkItJEg364hL3z6k#scrollTo=nNeu9XcwcbVc

**Comment by osrodas007** [comment]
Thank you for your response! Be waiting for data!

**Comment by agentdanger** [comment]
@CSSEGISandData is this the new cadence of automated updates?  I'll adjust my code and expectation accordingly.  midnight EST.

**Comment by dgoo2308** [comment]
Just updated, thanks

**Comment by lossyrob** [comment]
@CSSEGISandData thank you for the free service!

**Comment by Lucas-Czarnecki** [comment]
Thank you :)
