### ISSUE TITLE
Daily reports not in sync with Dashboard

### ISSUE THREAD

**Issue by mauro-gobbi** [CSSEGISandData/COVID-19#235]
Hello, I noticed that the daily report values are not in sync with your dashboard, for example now (March 4, 2020, 8:00 PM CET), the global number of confirmed cases is:
-  92,844 according to the CSV files in this git repo;
- 94,251 according to your dashboard (https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

**Comment by Shane073** [comment]
The CSV files get updated daily. The 92844 was from the last update which was nearly 20 hours ago.

The dashboard is live data. Gets updated more often.

**Comment by ogyalcin** [comment]
Hello,

Great dataset! Thanks a lot for all your efforts!

May I ask where the live dashboard receives the data from?

**Comment by mauro-gobbi** [comment]
> The CSV files get updated daily. The 92844 was from the last update which was nearly 20 hours ago.
> 
> The dashboard is live data. Gets updated more often.

Thanks for the quick reply! And thanks for providing this great service!
I'm also interested to know from what sources the dashboard receives inputs (before the WHO publishes their daily report).

**Comment by Shane073** [comment]
Data sources are listed here. https://github.com/CSSEGISandData/COVID-19

Yeah, they are doing a good job. It is nice to have the data accessible.

**Comment by ogyalcin** [comment]
@Shane073 Thanks for pointing out the data sourced page :) I haven't noticed it before.

**Comment by CSSEGISandData** [comment]
This repository is updated daily around 12 AM UTC ( 7 PM EST). The dashboard is updated at real-time. Due to the differences in update time, there may be discrepancies in the data from this repository and the dashboard.
