### ISSUE TITLE
Skipped day for Mexico Series

### ISSUE THREAD

**Issue by mariorz** [CSSEGISandData/COVID-19#2354]
A day was skipped for the Mexico series.
The published series for confirmed cases is now:
`8772,   9501,   11633`
The correct (official) count of confirmed cases for the last 3 days is:
`9501,   10544,   11633`

This repo had been lagging the data published in Mexico for around 23 hours, the automated update for today should be including the cases reported by Mexico's Secretaría de Salud for April 22, [official document](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/CTD/Documents/CTD/202004/20200422.pdf).  However, the values added today correspond to the values published on the 23th, [official doc](https://github.com/carranco-sga/Mexico-COVID-19/blob/master/CTD/Documents/CTD/202004/20200423.pdf).

The same mistake also applies for the other series in Mexico.

**Proposed Solution**
Mexico's Secretaría de Salud has now been publishing its daily data at 7pm sharp, before this repo's automated update, so if the value for the 22 is added to the series we can end up with an improved lag time going forward.

**Comment by mariorz** [comment]
Not sure where you are getting the time series for Mexico currently, but I publish a repo with time series for each state in Mexico derived from the daily oficial database update.

**Comment by CSSEGISandData** [comment]
Adjusted. See #2388
