### ISSUE TITLE
Delayed update to UK cases

### ISSUE THREAD

**Issue by przemyslawpluta** [CSSEGISandData/COVID-19#236]
As per [gov.uk](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#number-of-cases) UK cases are reported each day at 14:00 GMT which as of 4 March stand at **85** but dashboard was not updated until 19:33 GMT

**Comment by CSSEGISandData** [comment]
We've updated the data. Thanks for the info.
