### ISSUE TITLE
Inconsitencies in time_series_covid19_confirmed_US.csv

### ISSUE THREAD

**Issue by tbrewer-healthmap** [CSSEGISandData/COVID-19#2362]
Hi, 
I might be understanding it wrong, but it seems that the time series is a cumulative count, while ~800 rows have trailing zeroes or values that go up and down.

**Comment by jspanos71** [comment]
I wouldn't think of it as a cumulative count, but more of a historical count.  The counts are the total reported as of the date and may go up or down.  For example, this table is the daily count for "Unassigned" Florida.  The count here should go down as the correct county for each confirmed case is established.  They do not always go back and fix the prior dates by reducing the unassigned count and increasing the count in the correct place. Though this would create the best data, it is probably nearly an impossible task to do so.
![image](https://user-images.githubusercontent.com/3599357/80253820-9d662480-863f-11ea-9169-fce8cd13e835.png)

**Comment by tbrewer-healthmap** [comment]
Hi @jspanos71, thanks for the clarification!  I wasnt' really sure what those "Unassigned things were there for either =)
