### ISSUE TITLE
error in french cases on 4/22/20

### ISSUE THREAD

**Issue by guckmal** [CSSEGISandData/COVID-19#2365]
error in french cases on 4/22/20:
Number of (cumulative) cases decreases:
```
date | 4/21/20 | 4/22/20 | 4/23/20
cases | 158050 | 155860 | 158183
delta | 2775 | -2190 | 2323
```

**Comment by traut21** [comment]
No need to open a new issue - search for France first
https://github.com/CSSEGISandData/COVID-19/issues/2340

**Comment by guckmal** [comment]
oh sorry...
I see , at the end of #2340 it is mentioned that:
>  ... @CSSEGISandData counts probable cases as confirmed cases for france. 
>   Those are speculative and decreased, so their total for france decreased as well, 
>   resulting in a negative number of new cases.

but neverthless it is not logic to have in a cumulative variable a decrease.
