### ISSUE TITLE
Serbia data stale

### ISSUE THREAD

**Issue by vanjagenije** [CSSEGISandData/COVID-19#2368]
Serbia data has not been updated since Monday. Why?

**Comment by s0me0ne-unkn0wn** [comment]
Still no updates :(

**Comment by gandroul** [comment]
Still no updates :(

**Comment by iborko** [comment]
Numbers for Serbia are not updated for almost 7 days now. :(
Can we help somehow?

**Comment by amalic** [comment]
Anyone looking into this?

**Comment by CSSEGISandData** [comment]
Hello! The update for Serbia was delayed. Now it's back to normal. Thanks!
