### ISSUE TITLE
Daily Report Schedule Update

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#2369]
Greetings,
We want to make everyone aware of an update to the release schedule for the daily products. In the past, we have tried to push updates to the repository at approximately 00:00 UTC every day. In order to accommodate reporting across the lower 48 states of the United States, we are moving this update forward in time to occur between 03:30 and 04:00 UTC (23:30 – 00:00 EDT). 
Thank you for your understanding,
The JHU Team

**Comment by Lucas-Czarnecki** [comment]
Thank you for everything you do, and for letting us know!

**Comment by just2610** [comment]
Thank you ... keep up the great work.

**Comment by cptrguru** [comment]
Sincerely appreciate you posting the new scheduled time.  This will save a lot of time on waiting around for hours and wondering when the update will finally post.

**Comment by samscodes** [comment]
Thank you for letting us now, 
I just wanted to ask if it possible to keep the same update time at  00:00 UTC every day for all other countries expect USA or just have two refresh time the first at  00:00 UTC every day and the second between 03:30 and 04:00 UTC (23:30 – 00:00 EST). This will really be great for people focusing on other countries data expect USA.

**Comment by TrungMC** [comment]
Is it possible that you do two releases? One for the world at 00:00 UTC as before (with US as 1 line for the whole country) and the other for US detail at later time? Your data is invaluable not only to the US but the whole world and many countries start the day at 0:00 UTC.  3-4 UTC means half a working day has passed and the value of the data decreases.

**Comment by MEM-TEK** [comment]
Los Angeles County appears to have switched from 12 noon to 8pm local time for their daily report updates. This may be due to at least one lab which is still reporting backlogs of test results, and not reporting in a timely fashion. JHU's switch to reporting between 03:30 and 04:00 UTC (23:30 – 00:00 EDT) makes sense. Note that reporting time is EDT, not EST.

**Comment by jamescowens** [comment]
This is great, but since you shifted the update, you have an inconsistency in the daily file labels. You either have to have a gap day from 4/22 (reporting just before midnight) to 4/24 (reporting at ~3:30 AM), or define the early morning run at 3:30 AM to be for the previous day.

**Comment by jamescowens** [comment]
I am going to change my filter to add another version to have the daily file to actually be the report for the day before the dates in the file, which would also correspond to the label on the file.

**Comment by osrodas007** [comment]
Thank you for everything you do, and for letting us know!

**Comment by jamescowens** [comment]
My approach seems to work correctly...

**Comment by jamescowens** [comment]
This is related so I am putting it on here. The web-data "HEAD" file which is the intraday update, has dates which (for today for example) are a day off. The file should have nothing in it earlier than 4/24 at 0:00, and yet there are many records that are marked 4/23/2020  12:00:00 AM. This causes my filter to reject the records with 4/23, because I do not allow records with an earlier modified date to override records with a later date and the same key. This needs to be fixed. The update date time of any record in the cases.csv should not be earlier than any record in the daily file that has been committed and posted I think.

**Comment by cptrguru** [comment]
@CSSEGISandData The new process has not fired off to create the daily report data file.

**Comment by cptrguru** [comment]
> @CSSEGISandData The new process has not fired off to create the daily report data file.

30 minutes later and still no data.

**Comment by just2610** [comment]
@CSSEGISandData hopefully this completes soon

**Comment by cptrguru** [comment]
> @CSSEGISandData The new process has not fired off to create the daily report data file.

1 hour past target time and still no data reports.

**Comment by maisonml** [comment]
@CSSEGISandData Can someone from the team update on this? 04/24 data is not available yet. Its 1 AM EST, pushes were supposed to happen by 12 AM EST.

**Comment by ILOFI** [comment]
@CSSEGISandData when would 04/24 data of timeseries be updated?

**Comment by w3goodies** [comment]
The devs on this project are doing great work but I think they should be more clear on the timing as it effects lots of automated apps. They said update will occur "between" 03:30 and 04:00, so 04:00 UTC is already the max time. I think the same happened yesterday? Anyways, they should create a larger gap in both time range if they are unsure of updates, so that those apps that uses data just to automatically email/sms/tweet are not affected by sending incorrect data or if they use data validation then no data will be sent. Websites with live graphs won't be affected as such as these kinds of app due to inconsistency in the max update time.

**Comment by cptrguru** [comment]
> @CSSEGISandData The new process has not fired off to create the daily report data file.

1.5 hours past stated target time and still no data.

**Comment by advaithasabnis** [comment]
Is there an alternative source of data that some of you are using?

**Comment by cptrguru** [comment]
> Is there an alternative source of data that some of you are using?

@advaithasabnis  Recommend https://covidtracking.com/api.  They are slightly behind on their data, but FAR more reliable and in a consistent data format.

**Comment by TrungMC** [comment]
I've followed JHU data from beginining when the data was still on google sheet.  Back at the time, data is captured twice a day (which creates some problem for me) and there is still near realtime data. Then once a day at probably 0 UTC which is 7am in my timezone which is perfect.  Around 8am mytime, I used to get data from China NHC and SouthKorea's CDC.  Though US accounts for 1/3 of the cases, I think the world has more use of JHU data and should be prioritze.

Now that the whole world has to wait for the US data which the world doesn't care much (such as county level information). And the wait time is now like half a day. For 1 day old, we can use ECDC or NewYork times data source. 

Please consider update the world data as per previous time and US data whenever it's available.

**Comment by steveped** [comment]
Thank you for providing this, but please develop a better understanding of alternate git branches and ensure that any changes are robustly tested before pushing to `master`. Researchers and governments all round the world have been relying on this data source, and your inability to manage the repository intelligently is causing numerous headaches

**Comment by cptrguru** [comment]
> @CSSEGISandData The new process has not fired off to create the daily report data file.

2 hours past target and still no data reports.

**Comment by advaithasabnis** [comment]
> @advaithasabnis Recommend https://covidtracking.com/api. They are slightly behind on their data, but FAR more reliable and in a consistent data format.

Thanks @cptrguru! I definitely need something more reliable.

**Comment by advaithasabnis** [comment]
Anything for global data?

**Comment by cptrguru** [comment]
> Anything for global data?

Not for that collection of data, only U.S., unfortunately.

For world data I watch Worldometers and Newsbreak:
https://www.worldometers.info/coronavirus/#countries
https://www.newsbreak.com/topics/coronavirus?s=a4&pd=00fLBbS6
...but, the problem with these sites are you will have to scrape the data.  :-/

**Comment by cptrguru** [comment]
> @CSSEGISandData The new process has not fired off to create the daily report data file.

2.5 hours and no data.

**Comment by Lucas-Czarnecki** [comment]
Data are now up

**Comment by cptrguru** [comment]
Daily reports confirmed to now be available.

**Comment by Lucas-Czarnecki** [comment]
Everything looks good. Thx JHU CSSE!

**Comment by jamescowens** [comment]
In the 4-24-2020 daily file, the NY entries other than NYC have not been updated since 4/23...

36059,Nassau,New York,US,2020-04-23 00:00:00,40.74066522,-73.58941873,32765,1518,0,31247,"Nassau, New York, US"

for example. Please fix.

**Comment by KatharinaKanns** [comment]
thank you for all that work. "last update" is now a day later - will that constantly be like this?

**Comment by juancri** [comment]
Please, remember to update the README files

**Comment by CSSEGISandData** [comment]
README files have been updated for this issue. Thanks everyone!
