### ISSUE TITLE
Australian recovery data is still out of date since April 18.

### ISSUE THREAD

**Issue by BJReplay** [CSSEGISandData/COVID-19#2370]
As noted in https://github.com/CSSEGISandData/COVID-19/issues/2321, there was a issue for all Australian data for about a week.  

In comment https://github.com/CSSEGISandData/COVID-19/issues/2321#issuecomment-619250935 to this issue, @CSSEGISandData noted that they had "located the issue in our sourcing and have manually updated the time series table."

Compared to https://covid-19-au.com/ which sources data from a number of sources (see below) or https://www.worldometers.info/coronavirus/country/australia/ which both show increasing recoveries, the JHU data doesn't show those recoveries (and therefore all stats that depend on case status ratios).

Official sources below.

If we can help in any way, please let the community know.

Thanks

AU data sources:

- State of New South Wales NSW Ministry of Health https://www.health.nsw.gov.au
- The State of Queensland (Queensland Health) https://www.health.qld.gov.au/.
- The Government of South Australia, SA Health https://www.sahealth.sa.gov.au.
- Australian Capital Territory Government, ACT Health  https://www.covid19.act.gov.au/home.
- Government of Tasmania. at https://www.tas.gov.au/
- Victoria State Government, Department of Health and Human Services https://www.dhhs.vic.gov.au/
- Northern Territory Government https://nt.gov.au/
- Government of Western Australia, Department of Health https://ww2.health.wa.gov.au/Home

**Comment by CSSEGISandData** [comment]
Hi
Thank you for bringing this to our attention. This was an issue that was missed and we apologize. Our next update will contain the correct recovered data for the Australian territories and we will work to correct the time series for recovered cases. Thank you for your patience.

**Comment by BJReplay** [comment]
Thanks so much for your work on this project!
