### ISSUE TITLE
24-04-2020 Updateds are still not updated 

### ISSUE THREAD

**Issue by samscodes** [CSSEGISandData/COVID-19#2371]
Any updates on when they will update 24-04-2020 data?

**Comment by maisonml** [comment]
@CSSEGISandData Can someone from the team update on this? 04/24 data is not available yet. Its 1 AM EST, pushes were supposed to happen by 12 AM EST.

**Comment by John-Sin** [comment]
Still waiting for 4/24 update almost 2-hours beyond posted new update schedule.   Previous  00:00 UTC schedule was working just fine -- can we go back to that?   This change is unreliable and not working.

**Comment by BrianRuizy** [comment]
I was wondering why my web-app was returning 404 error. Seems to be an issue with new scheduling, as stated here #2369. Perhaps end-users should have some more robust exception handling in place for any situation as such. 

My current method is just grabbing the .csv of the previous day. But, is there a Python, or GitHub API way to get the filename of the last updated file in the directory, I.e. _.../csse_covid_19_daily_reports/_?

**Comment by jishnub** [comment]
Seems fixed now after 45909bb3a381a26f7426c2e0e2d00afa9f6ea265

**Comment by dcinzona** [comment]
> My current method is just grabbing the .csv of the previous day. But, is there a Python, or GitHub API way to get the filename of the last updated file 

I have a cron job that runs every 5 minutes checking a cloned copy of this repository for changes, then kicks off a job to build the JSON versions of the CSVs.

Then I push those JSON files to my repo, which is what my app uses. 

Works fairly well.
