### ISSUE TITLE
04-23 and 04-24 Covid data looks incorrect.  Missing records bad dates.  Daily Report

### ISSUE THREAD

**Issue by PanamaMike** [CSSEGISandData/COVID-19#2381]
The dates in the 04-23 are 04-24
the dates in the 04-24 are 04-25
I manually updated the dates to the corresponding file date, the totals aren't adding up when compared to numbers on the John Hopkins dashboard.  Number are much lower.

**Comment by econ-erik** [comment]
Hey @PanamaMike it's likely attributable to the change in update times mentioned in the ReadMe as of April 23rd. With the update now happening between UTC 3:30 and 4:00, it often means the dates will show up as the next day -- it used to be 23:59 UTC. My guess is that some of the date math will have to be updated with the shift in update times. You could try using local time for each region based on the latitude and longitude to adjust the UTC to local time.   The lutz package in R has tz_lookup_coords() which is useful in such applications.

**Comment by traut21** [comment]
I use it for my charts for https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic

Unfortunately, JHU does not reply to the issues here about incorrect data for France

**Comment by PanamaMike** [comment]
> Hey @PanamaMike it's likely attributable to the change in update times mentioned in the ReadMe as of April 23rd. With the update now happening between UTC 3:30 and 4:00, it often means the dates will show up as the next day -- it used to be 23:59 UTC. My guess is that some of the date math will have to be updated with the shift in update times. You could try using local time for each region based on the latitude and longitude to adjust the UTC to local time. The lutz package in R has tz_lookup_coords() which is useful in such applications.

I think you're right as to why they have the incorrect date, based on when it runs.  There are 3 issues.
1:  There is a gap in data (time) between the 23rd and 24th.  When they made the change, they should take into account data captured between 12:00 UTC and 3:00 UTC for the 23rd.
2:  The data is published the next calendar day, but the data should be for the previous calendar day, the last_update timestamp should reflect when the data was captured, not when it was reported.  I can't hold them to it since they didn't define it clearly.
3:  The totals are wrong.  I don't know what's causing the issues, but compared to what JH is reporting as well as what I see on the news, the data is different.

Bring me to the final question, why aren't we all seeing the same data?  Why is JH clearly using a different data set?

**Comment by PanamaMike** [comment]
> I use it for my charts for https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic
> 
> Unfortunately, JHU does not reply to the issues here about incorrect data for France

**Comment by PanamaMike** [comment]
@ldemaz There're multiple issue related to the dates.  
1:  Majority of records are dated for the actual calendar date, when they should be for the day the data represents.  Example 04/27/2020 for 04/26/2020 records. 
2:  The majority of New York county data, excluding New York City and Unassigned, are dated the day before the actual date.  The time is 00:00, indicating midnight.  In the same file with 04/27/2020 records, we find 04/25/2020 New York county records.  
3:  There are a handful of records from a variety of dates that are duplicates of past records.  I've seen a couple from 2/23/2020 and other dates from China and other locations.

**Comment by PanamaMike** [comment]
Accidentally closed.

**Comment by PanamaMike** [comment]
Issues related to alignment of dates has been resolved.  Note the record date is still set for the current published date and not the actual data event date which would be the previous day.
