### ISSUE TITLE
Mexico data wrong in time series

### ISSUE THREAD

**Issue by jairgs** [CSSEGISandData/COVID-19#2388]
time_series_covid19_confirmed_global.csv has the entry for mexico duplicated for two days. 
How it is:
11633 for 4/23/20
How it should be:
10544 for 4/23/20

Besides, the data have one day lag so the data you have for x day should be on x-1 day.

**Comment by JesusCoyotzi** [comment]
I was just about to report this same issue
Last two days for Mexico are repeated.

**Comment by felipec** [comment]
I wrote a script the fix the issue. But I'm not sure if I should send a pull request or the fix the issue from other sources.

Anyway, will try to send a pull request soon.

**Comment by CSSEGISandData** [comment]
Adjusted. Thank you for bringing this to our attention.
