### ISSUE TITLE
Announcement: Some Known Issue in Dashboard

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#239]
Hello! We are testing new features in the dashboard. It may look weird for a while. No panic and be patient. Thanks!

**Comment by dawenx** [comment]
wow, i cannot believe you guys are using a live production site (w/ so many users) for testing... 

for those who wants to check the latest covid-19 data in their testing, feel free to check out other dashboards/tools mentioned in #7

**Comment by dawenx** [comment]
looks like it's back now, can you share with you what are the new features other than a different default extent which looks familiar?

![Screenshot_2020-03-04 COVID-19 Surveillance Dashboard](https://user-images.githubusercontent.com/26723038/75942479-7457bd80-5e60-11ea-8bc4-091faa6f72ef.png)
![Screenshot_2020-03-04 Coronavirus COVID-19 (2019-nCoV)(1)](https://user-images.githubusercontent.com/26723038/75942491-7b7ecb80-5e60-11ea-8a90-595f8e94b192.png)

**Comment by dawenx** [comment]
Oh boy...
![Screenshot_2020-03-04 Coronavirus COVID-19 (2019-nCoV)(2)](https://user-images.githubusercontent.com/26723038/75943227-6c008200-5e62-11ea-932c-121391108c7a.png)

**Comment by ronwab** [comment]
Your stats dont look right!

**Comment by CommanderBlop** [comment]
2 million infected doesn't look right to me. I was scared as hell to see 2m people got infected in Italy on site.

**Comment by Sashie** [comment]
yeah it shows me the same total value, obviously things are half broken atm

**Comment by dawenx** [comment]
@CommanderBlop don't worry, those 2M+ people are gone now.

![Screenshot_2020-03-04 Coronavirus COVID-19 (2019-nCoV)(3)](https://user-images.githubusercontent.com/26723038/75943873-3f4d6a00-5e64-11ea-9307-7ee20ceea875.png)

**Comment by Sashie** [comment]
yea that happened just after i made my first post xD

**Comment by iceweasel1** [comment]
hahaha

**Comment by CSSEGISandData** [comment]
Another technical upgrade leading to lots of confusion and panic. It says 2.6 mi infected ppl. That's not a real number. Esri and our IT team are working on recovering the system now.

**Comment by Sashie** [comment]
clearly it was a boo boo, but either way, great work on this resource to all working on it ^.^

**Comment by dawenx** [comment]
@CSSEGISandData  how come you guys don't have a development system for testing before a rolling out? thanks for giving sites mentioned in #7 some traffic though

**Comment by Shane073** [comment]
@CSSEGISandData as @dawenx said, don't you have a development site for testing? Considering the sensitivity of the information, not really best practice to be doing this on a live site. It has Total Confirmed 2,647,665 for me at the moment.

**Comment by CSSEGISandData** [comment]
The system is back. Hope it won't be a headline in the news tomorrow (joking). 
RE testing: We do have a staging env, but no staging env could perfectly mimic an environment with hundreds of thousands of clicks every second. We will try to avoid such a man-made tech failure next time.

**Comment by iceweasel1** [comment]
Big Data-Crash. Check your recovering system. Whatever country I click on the left side, all countries you click on one by one are displayed completely wrong. 

For example Germany. I click on Germany, it says 706 Confirmed. The location is shown in Tokyo and there are 6 dead and 10 healed.

Click on South Korea. South Korea is shown with 3 Confimed and the point on the map says that South Korea is in Georgia.

America is shown in Liechtenstein on the map. No casualties, no healing, 1 case of infection.

And so on.

No matter what you click on, everything is completely wrong.

![ger](https://user-images.githubusercontent.com/49625256/75949369-50b76600-5ea6-11ea-9366-6c910d461320.PNG)
![us](https://user-images.githubusercontent.com/49625256/75949371-51e89300-5ea6-11ea-9e42-7d40ec8d8333.PNG)
![sk](https://user-images.githubusercontent.com/49625256/75949373-51e89300-5ea6-11ea-9c65-3202241acc06.PNG)

**Comment by designerfuzzi** [comment]
not complaining about tiny mistakes that happen on the fly while improving. It could also be marked as "under contruction" and that way telling the visitors that this is not just a script-machine, there are real people working on it. 
The other thoughts i have when looking at the graphics, the higher the numbers become.. the big numbers remind me on a shooter game score. I would make those big numbers-letters a little bit less prominent in size (half the size they have now) and this way give the real data more space.

**Comment by iceweasel1** [comment]
I'm not complaining about it. I wanted to give the JHU the important clue. If it came across a little differently in that language, I'm sorry.

**Comment by designerfuzzi** [comment]
i meant myself.. :) but "wo gehobelt wird, da fallen Späne!" <3
