### ISSUE TITLE
Missing deaths value for New York, New York for April 24

### ISSUE THREAD

**Issue by lojic** [CSSEGISandData/COVID-19#2391]
https://github.com/CSSEGISandData/COVID-19/blob/d65b1a73cb64ad5aa9779ec8299a2a440bd9fdb8/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv#L1865

New York, New York is missing a value for deaths for April 24.

**Comment by lojic** [comment]
The error appears to have been introduced in commit: 0fa65c7f62580a4e1f7ef32659d1257bc8924ad8

**Comment by lojic** [comment]
![Screen Shot 2020-04-25 at 8 02 18 PM](https://user-images.githubusercontent.com/57366/80293723-be0da780-872f-11ea-830c-ba90e4662d06.png)

**Comment by ArturoGallettiLopez** [comment]
Data for NY, NY is in 4/25 but still missing for 4/24 in the update.
