### ISSUE TITLE
Recovered Cases of "Victoria, Australia" and "Northern Territory, Australia"

### ISSUE THREAD

**Issue by mbahram** [CSSEGISandData/COVID-19#2392]
Daily reports: Recovered cases of "Victoria, Australia" and "Northern Territory, Australia" seems to be wrong. "Victoria, Australia" drops to 133 from 1172 and "Northern Territory, Australia" from 9 to 0

**Comment by benflips** [comment]
These are likely typos.  I'm guessing they should be: 1330 and 10.  But that would be a guess, else I would PR the corrections..  These are fairly major errors.  See active case calculation from http://au.covid19forecast.science.unimelb.edu.au/

![image](https://user-images.githubusercontent.com/8161516/80305760-7bac9f00-87f1-11ea-90ce-b0091c09518b.png)

**Comment by benflips** [comment]
Thanks folks.  Looks to be corrected now, as well as some general going-over of the Australian data.  Much appreciated.  You can probably close this one @mbahram.
