### ISSUE TITLE
4/24 deaths for NY, NY are still missing

### ISSUE THREAD

**Issue by NetworkTest** [CSSEGISandData/COVID-19#2398]
Unclear why issue #2391 was closed. Deaths for New York, NY are given for 4/25 but are still missing for 4/24. 

With the missing data point cumulative deaths appear to decrement for a day, and absent some external factor like misreporting (which was not the case here) that should never happen.

**Comment by NetworkTest** [comment]
Fixed about 5 hours ago. The 4/24 cumulative death toll for New York, New York now shows as 16,190. Thanks.

**Comment by CSSEGISandData** [comment]
Lots of moving parts to track, thanks for keeping us attentive!

**Comment by NetworkTest** [comment]
On 4/26/20 9:17 AM, CSSEGISandData wrote:
> Lots of moving parts to track, thanks for keeping us attentive!

I've just closed this; the missing data is now in place.

Thanks VERY much for providing this invaluable data set.

dn
