### ISSUE TITLE
Confirmed timeseries decreasing for Williamsburg, VA

### ISSUE THREAD

**Issue by deepyaman** [CSSEGISandData/COVID-19#2411]
See https://github.com/CSSEGISandData/COVID-19/blob/8a92419283594053dcafa91e70adeda84c5d44b6/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv#L2958

We're not sure how to interpret this, as there are many possible explanations, e.g.:

* Mistakenly reporting current active cases instead of cumulative cases
* Case count correction (Should previous values in the curve be updated in this case? Also, why has it been adjusted downward multiple times?)

Also see https://github.com/CSSEGISandData/COVID-19/issues/2089

**Comment by CSSEGISandData** [comment]
@deepyaman This is generally a result of revisions to reporting by public health departments.  This is not atypical in this outbreak.  The current curve for Williamsburg from the VDH is below and reflects these decreases:
![image](https://user-images.githubusercontent.com/60674295/87606251-80824000-c6c8-11ea-8482-36f8f1fcaed0.png)
