### ISSUE TITLE
How is US testing rate and hospitalization rate calculated?

### ISSUE THREAD

**Issue by therealcyberlord** [CSSEGISandData/COVID-19#2413]
Is it out of 100,000 people?

**Comment by Lucas-Czarnecki** [comment]
(Total # of people hospitalized * 100) / Total # of confirmed cases

**Comment by CSSEGISandData** [comment]
US Testing Rate: = total test results per 100,000 persons. The "total test results" are equal to "Total test results (Positive + Negative)" from Covid Tracking Project.
US Hospitalization Rate (%): = Total number hospitalized / Number confirmed cases. The "Total number hospitalized" is the "Hospitalized – Cumulative" count from Covid Tracking Project. The "hospitalization rate" and "Total number hospitalized" is only presented for those states which provide cumulative hospital data.
