### ISSUE TITLE
Quick fix needed for France data

### ISSUE THREAD

**Issue by yo-ni** [CSSEGISandData/COVID-19#2414]
There is some data in the daily cases (and thus the total) to fix a bit:

april 12th: 26.8K (correct value: 1613)
april 16th: 12.5K (correct value: 2641)
april 22nd: -2.2K (correct value: 1827)

As stated here in the France government page here https://www.gouvernement.fr/info-coronavirus/carte-et-donnees

**Comment by traut21** [comment]
There is no need to open yet another Issue for France - we have plenty already.

https://github.com/CSSEGISandData/COVID-19/issues/2270 is open for many days now - but JHU people don't mind about any reactions here.

**Comment by yo-ni** [comment]
@traut21 okay noted !
