### ISSUE TITLE
Actual Graph error on Confirmed Cases (Orange)

### ISSUE THREAD

**Issue by issaqandil** [CSSEGISandData/COVID-19#242]
The actual confirmed cases graph/chart is still showing 80.4K while the actual number is 95.4K. It stopped changing for a while now. 

<img width="1677" alt="Screenshot 2020-03-05 at 07 55 11" src="https://user-images.githubusercontent.com/55758479/75959825-e3600100-5eb6-11ea-9984-001dcacff59b.png">

**Comment by Shane073** [comment]
Hey @issaqandil. Orange on the graph is for mainland China only. Yellow is other locations only. Nothing on the graph for total combined. So the 80.4k +15k get to 95k total confirmed cases.

**Comment by issaqandil** [comment]
Oh so sorry didn't notice that. my bad. 

Issa
