### ISSUE TITLE
Apr 27: Deaths for Lincoln, Missouri are incorrect

### ISSUE THREAD

**Issue by lojic** [CSSEGISandData/COVID-19#2421]
https://github.com/CSSEGISandData/COVID-19/blob/bda67e3db0e8dca4540297633d431a8021c035c8/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv#L1546

The Lincoln County, MO health department lists [1 death](https://lchdmo.org/covid19-testing), not 41 deaths.

**Comment by lojic** [comment]
I just noticed that the [Lincoln County Health Dept.](https://lchdmo.org/covid19-testing) lists the number of recovered as 41, so maybe they added that field and broke the scraper?

**Comment by lojic** [comment]
I just pulled down the Apr 28 file, and the value for Apr 27 is still incorrect.
<img width="441" alt="Screen Shot 2020-04-28 at 11 06 32 PM" src="https://user-images.githubusercontent.com/57366/80557462-008bea00-89a5-11ea-9ff0-d4028084a5ef.png">

**Comment by CSSEGISandData** [comment]
@lojic I apologize for not responding earlier.  This issue was resolved.
