### ISSUE TITLE
Apr 27: Reported cases incorrect for Granville, NC

### ISSUE THREAD

**Issue by lojic** [CSSEGISandData/COVID-19#2423]
https://github.com/CSSEGISandData/COVID-19/blob/bda67e3db0e8dca4540297633d431a8021c035c8/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv#L1935

[Granville Public Health](https://gvph.org/covid-19/) lists 130 cases, not 240.

**Comment by lojic** [comment]
I'm not sure what source you're using for North Carolina county data, but there is a good summary page here for confirmed cases and deaths:

https://www.ncdhhs.gov/divisions/public-health/covid19/covid-19-nc-case-count#by-counties

**Comment by lojic** [comment]
@CSSEGISandData any update on this? I opened a couple issues (this and #2421) about 7 hours ago. I provided links to the specific lines in error, and I provided links to health department websites for the accurate counts.

Have you thought about open sourcing the scraping code to allow crowdsourcing of fixes when website changes break the scrapers?

**Comment by lojic** [comment]
I just pulled the Apr 28 file, and the value for Apr 27 is still incorrect.
<img width="229" alt="Screen Shot 2020-04-28 at 11 08 18 PM" src="https://user-images.githubusercontent.com/57366/80557536-37fa9680-89a5-11ea-9d16-30d4fd0ec6d9.png">

**Comment by CSSEGISandData** [comment]
Thanks @lojic
