### ISSUE TITLE
Missing data in time_series_covid19_recovered_global (UK)

### ISSUE THREAD

**Issue by ossimoro666** [CSSEGISandData/COVID-19#2432]
I did not find in time_series_covid19_recovered_global.csv the last data of recovered for UK.
The last data updated is on 4/13/2020.

Thanks,
Pietro

**Comment by capahaddock** [comment]
Same issue mentioned before. 
https://github.com/CSSEGISandData/COVID-19/issues/2316

The official data sources in the UK (apparently) do not show recovery data.
https://coronavirus.data.gov.uk/
https://www.gov.uk/government/publications/national-covid-19-surveillance-reports

worldometers.info shows 'NA' for recovered data for the UK.

Go figure...
