### ISSUE TITLE
Multiple updates for same county on same date

### ISSUE THREAD

**Issue by anushabhide** [CSSEGISandData/COVID-19#2433]
Hi Team,

We would want to know the refresh schedules of this data.

Also we could see few fips having multiple updates for same Last_update column value. So how do we decide which data is corresponding to which date.

Have attached a screenshot of sample data here.

![image(46)](https://user-images.githubusercontent.com/4541043/80592031-5c558200-8a3c-11ea-8988-45f2dcdd57ef.png)

**Comment by CSSEGISandData** [comment]
Please refer to this [post](https://github.com/CSSEGISandData/COVID-19/issues/2369) for further information on the update frequency. Thanks!
