### ISSUE TITLE
April 27: Incorrect amount of total cases for Ontario, Canada and Japan

### ISSUE THREAD

**Issue by jaaanko** [CSSEGISandData/COVID-19#2434]
Ontario, Canada should be at **15,381** instead of 15,970.

Japan should be at **13,613** instead of 14,153.

Sources:

[Gov. of Canada website](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html)
[NHK](https://www3.nhk.or.jp/news/special/coronavirus/)

**Comment by CSSEGISandData** [comment]
@jaaanko artifact of variable rates at sourcing
