### ISSUE TITLE
Data entry error for Lincoln County Missouri

### ISSUE THREAD

**Issue by hwallMO** [CSSEGISandData/COVID-19#2436]
The number of deaths on 4/27 was entered as 41, but should have been 1. See the line for deaths below.

84029113.0,US,USA,840,29113.0,Lincoln,Missouri,US,39.05345619,-90.95588181,"Lincoln, Missouri, US",59013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,41,1

**Comment by lojic** [comment]
@hwallMO I already opened #2421 for this problem, so you might want to close yours as it's a duplicate.
