### ISSUE TITLE
Spain data- Confirmed cases

### ISSUE THREAD

**Issue by kentiwary** [CSSEGISandData/COVID-19#2448]
1) Spain data does not add to dashboard, including historic.
2) Spain Cumulative cases for Apr30th is 23k less than Apr29.

**Comment by mbahram** [comment]
Looking at the time series, the numbers for Spain is very different from Daily reports. Big discrepancy!!!

**Comment by CSSEGISandData** [comment]
Hello

We have changed sources for Spain to align with the official numbers. The drop in cases from April 23rd to April 24th is consistent with the official numbers released by the Spanish government.
April 23rd: https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_84_COVID-19.pdf
