### ISSUE TITLE
Dashboard says "Not fully configured"

### ISSUE THREAD

**Issue by dscho** [CSSEGISandData/COVID-19#2449]
Apologies if this is the wrong place to report this problem!

Currently, when I try to access https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6, I see this:

![image](https://user-images.githubusercontent.com/127790/80808965-01996300-8bc1-11ea-94b5-ec994ef960e4.png)

**Comment by CSSEGISandData** [comment]
We are investigating.

**Comment by dscho** [comment]
Thank you so much for all you do! I very much appreciate your work.
