### ISSUE TITLE
csse_covid_19_time_series inconsistent with csse_covid_19_daily_reports

### ISSUE THREAD

**Issue by raffg** [CSSEGISandData/COVID-19#2453]
In the [README](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/README.md) for the time series data, it is stated "All data are from the daily case report." However, the time series data has received updates (see, for example, Serbia update in commit [23c7966](https://github.com/CSSEGISandData/COVID-19/commit/23c79662b4b42fb98ea39b89617af52280b3e989)) which have not been added to the daily reports data.

Which data source is the ground truth? The README implies the daily reports is, but now the time series is updated and daily reports is lagging.

**Comment by CSSEGISandData** [comment]
Thank you for your comment. You are correct that our README is out of date. We are manually updating the time series when historical issues are identified, but have chosen to maintain the daily reports as raw file outputs from our dashboard. The time series is as close as we have to the ground truth. We will adjust the README file to reflect this. Please accept our apologies.

**Comment by tko** [comment]
Currently there doesn't seem to be time series including recovered count on US state level; they are in the global daily reports, but not in the time series. Should there be a separate time series for US like there is for confirmed and deaths?
