### ISSUE TITLE
Negative delta / corruption in confirmed case graph on dashboard

### ISSUE THREAD

**Issue by ffwd-txnx** [CSSEGISandData/COVID-19#2454]
Two days ago:

![image](https://user-images.githubusercontent.com/23231202/80837046-b4d47d00-8bfe-11ea-924e-7ec4a671cfb3.png)

Just now:

![image](https://user-images.githubusercontent.com/23231202/80837063-bf8f1200-8bfe-11ea-8916-d7c9b94c310f.png)

**Comment by CSSEGISandData** [comment]
We are aware of this issue, working on fixing it these days. This anomaly only happens to the curve. Thanks!

**Comment by ffwd-txnx** [comment]
This has seemingly been fixed, so closing.
