### ISSUE TITLE
Lithuania confirmed went negative

### ISSUE THREAD

**Issue by raffg** [CSSEGISandData/COVID-19#2467]
Country/Region | 4/25/2020 | 4/26/2020 | 4/27/2020 | 4/28/2020 | 4/29/2020 | 4/30/2020 | 5/1/2020 | 5/2/2020
-- | -- | -- | -- | -- | -- | -- | -- | --
Lithuania | 1426 | 1438 | 1449 | 1344 | 1375 | 1385 | 1399 | 1406

On 4/28, the confirmed count for Lithuania lost 105 cases. Is this an adjustment or a error?

**Comment by ffwd-txnx** [comment]
This was an adjustment in official government data. Articles in Lithuanian:

* https://www.lrt.lt/naujienos/lietuvoje/2/1168155/lietuvoje-tik-5-nauji-koronaviruso-atvejai-patikslintas-bendras-ligos-atveju-skaicius-1344
* https://www.delfi.lt/sveikata/sveikatos-naujienos/lietuvoje-patvirtinti-5-nauji-koronaviruso-atvejai.d?id=84154115

(Official ministry page inaccessible ATM.)

In short, repeat tests for known cases got mixed up in batches of new, not yet confirmed cases.

On that day, they switched from reporting case numbers by adding up "new cases" as reported by the labs to a print-out from the health system registry.

At least that's how the officials described it.

OK to close. :)
