### ISSUE TITLE
Confirmed Cases by Country/Region Data Missing in Dashboard

### ISSUE THREAD

**Issue by przemyslawpluta** [CSSEGISandData/COVID-19#247]
![dash](https://user-images.githubusercontent.com/221250/76005982-b980fb80-5f03-11ea-8589-dae953ca49d3.jpg)

**Comment by CSSEGISandData** [comment]
For any issues with the dashboard that have not been addressed in the read me or on the issues page by us, please try clearing out your browser cache and refreshing the page!
