### ISSUE TITLE
WHO COVID-19 Situation report updates

### ISSUE THREAD

**Issue by kohint** [CSSEGISandData/COVID-19#2470]
I am Daniel Koh, a Research Assistant at the Graduate School of Public Health, Seoul National University.
Our team is grateful for your work and if the WHO situation report CSV
(https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv) 
is updated, it would be very helpful for our research dealing with this crisis.
Also, could I get access to (https://github.com/CSSEGISandData/COVID-19/upload/master/who_covid_19_situation_reports/who_covid_19_sit_rep_pdfs)
upload the updated situation reports since I have all the files downloaded.

**Comment by CSSEGISandData** [comment]
Sorry for letting you wait (we were preparing for the finals...). We just updated the WHO reports. Check it out.
