### ISSUE TITLE
Daily Report and Time Series differs for Spain data (starting April 24)

### ISSUE THREAD

**Issue by Fussballexperte** [CSSEGISandData/COVID-19#2483]
On 04/24 the confirmed count in the time series for Spain drops by around 10k, whereas it increases in the daily report. This inconsistency goes on for several days.

Current data for Spain in both time series and daily report differs a lot from other sources like Wordometer.

**Comment by traut21** [comment]
JHU does not mind about the official numbers, but thinks, they have better guesses of their own.
The drop in official numbers, which happened several times by now, is not well explained by the Spanish government. Once, they reverted from probable causes to tested cases only. But the second time?

**Comment by CSSEGISandData** [comment]
As explained in the README file, the daily reports are not updated when issues are identified. We recommend you check Errata.csv to see where we have altered the time series table. The time series table is the most accurate source of our historical data.

@traut21 The single instance of a drop in cases is consistent with the reports published by the Spanish government.

See:
March 23rd - https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_84_COVID-19.pdf
March 24th - https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_85_COVID-19.pdf

**Comment by traut21** [comment]
today is yet another drop in deaths
