### ISSUE TITLE
Spain data is not correct in global confirmed

### ISSUE THREAD

**Issue by esotanc** [CSSEGISandData/COVID-19#2491]
Hi!

In the COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

the Spain data in not correct from April 24 till May 07 (there is a case number fall:

**213024 | 202990** | 205905 ...

**Comment by CSSEGISandData** [comment]
Hello

Please see issues #2448 and #2483. Our drop is consistent with the official data released by the Spanish government. We have been unable to verify why this drop occured, which is quite frustrating, but we are making the decision to follow the national government.
