### ISSUE TITLE
Inconsistent data for Spain and other countries

### ISSUE THREAD

**Issue by GerardoRTobar** [CSSEGISandData/COVID-19#2492]
In the Confirmed Cases Time Series for Apr 23 to Apr 24, Spain seems to have -10,034 new cases (if we just use the formula of new_cases_day(n) = day(n) - day(n-1) given that the data is cumulative on date.

Also, for the same reason, there appears to be some errors in France Confirmed Cases, specifically in Apr 21 to Apr 22, and Apr 28 to Apr 29.

The same applies for the recovered time series for United Kingdom in April 13 to April 14 recovered time series. 

Taking into consideration that the time series is a cumulative data set, any given day should have at least the same cases as the prior day, or more. It should never be less than the prior day.

Thanks for your time.

**Comment by GerardoRTobar** [comment]
@CSSEGISandData

**Comment by GerardoRTobar** [comment]
Or at least could you explain why does that happen, if is not an error

**Comment by CSSEGISandData** [comment]
Hello

For Spain, please see issues #2491, #2455, #2462, and #2448. France data is consistent with the reports from the French Health Ministry, which on occasion has shown decreases in probable cases.

CSSE
