### ISSUE TITLE
Lesotho is missing a UID

### ISSUE THREAD

**Issue by sollyucko** [CSSEGISandData/COVID-19#2509]
Lesotho appears to have been added to the web-data branch in commit 668c70eddcb0d6ac51b2ce8bf0d0285c26ea97d8, but does not have a UID, which caused our data analysis to error. It appears that it should be 426, [according to Wikipedia](https://en.wikipedia.org/wiki/Country_codes:_L#_Lesotho). Could this get fixed ASAP?

**Comment by CSSEGISandData** [comment]
Thanks! Lesotho was added to our UID table.
