### ISSUE TITLE
WHO Data mismatch for Feb 21st Hubei 

### ISSUE THREAD

**Issue by melissawm** [CSSEGISandData/COVID-19#251]
On `20200221-sitrep-32-covid-19.pdf` the number of Cumulative confirmed cases for the Hubei province in China is **62662**, while the `who_covid_19_sit_rep_time_series.csv` file lists **66262** confirmed cases for the same date, same province. I suspect this is a typo...

**Comment by CSSEGISandData** [comment]
That's a typo. We will fix it. Thanks for pointing it out.

**Comment by CSSEGISandData** [comment]
The error has been fixed. Thanks for your support!
