### ISSUE TITLE
Somebody messed up your data

### ISSUE THREAD

**Issue by Anonymous-Coward** [CSSEGISandData/COVID-19#2510]
I don't know about other countries. Official data for Romania can be found here: https://datelazi.ro. Not at all the same with what you currently have.

The data was OK until yesterday.

My assumption is another country's data was saved as Romania's. The sequence from the beginning, when we had below 10 new confirmed cases a day, does not match at all.

**Comment by CSSEGISandData** [comment]
@Anonymous-Coward Where is the issue? The case and death counts displayed on the dashboard are identical to your source, as are the time series files.

**Comment by Anonymous-Coward** [comment]
Sorry to have bothered you unnecessarily. I first looked at the map, saw some bad data there, then went to git and didn't read the files properly - they contain sums of cases by day, not daily cases. After a cache clear and reload the site shows the correct data again.
