### ISSUE TITLE
Ayuda - Help

### ISSUE THREAD

**Issue by fsalce** [CSSEGISandData/COVID-19#2512]
Hola!, Estoy intentando aprender R usando estos datos.

Quisiera pedir ayuda con dos cosas que no se hacer, en casos de ser posibles

1. ¿Cómo crear una serie de tiempo diaria como la que se proporcionan aquí?
2. ¿Se puede vincular R (Rstudio) a Github para actualizar la base de datos diariamente de forma automatica o con algún comando?, y así solamente reproducir el Script

--------------------------------------------

Hi, I'm trying to learn R's using this data.

I would like to ask for help with two things I don't know how to do, if possible

1. How do you create a daily time series like the one provided here?
2. Can you link R (Rstudio) to Github to update the database daily automatically or with some command, and then just play the Script

Gracias - Thanks

**Comment by smriti241** [comment]
I want to resolve the issue

**Comment by smriti241** [comment]
> stockprices <- data.frame(prices=c(1.1,2.2,3.3),
               timestamps=c('2011-01-05 11:00','2011-01-05 12:00','2011-01-05 13:00'))
> stockprices
  prices       timestamps
1    1.1 2011-01-05 11:00
2    2.2 2011-01-05 12:00
3    3.3 2011-01-05 13:00

**Comment by smriti241** [comment]
https://www.youtube.com/watch?v=E2d91v1Twcc
This will help for your second query

**Comment by smriti241** [comment]
Did this help?
