### ISSUE TITLE
Number of recoveries too low in France?

### ISSUE THREAD

**Issue by syntakker** [CSSEGISandData/COVID-19#2521]
For France, the number of recoveries seems too low. For May 14 the numbers are:
- Cases: 178,994
- Recovered: 59,719
- Deaths: 27,428

However, for April 14, the number of cases is already at 130,365. Assuming that the majority of cases recover or die within 4 weeks, the sum of recovered and deaths should be around those 130,000 cases.
(Data taken from https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

**Comment by CSSEGISandData** [comment]
We don't disagree with your logic, but our posted numbers are consistent with those reported by the French government: https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA

For the explanation of why our number for France, France is slightly different, please see #2459.

**Comment by syntakker** [comment]
Sorry for contradicting, the number cited on this site is not the number of recovered patients. In the sections "Données hospitalières", "retours à domicile" is the number of people that have been hospitalized and have left the hospital, i.e., this is the number of recoveries only among people who underwent treatment in a hospital.
