### ISSUE TITLE
Protect Yourself From Coronavirus 

### ISSUE THREAD

**Issue by Orantesamo** [CSSEGISandData/COVID-19#2528]
Mask are great to wear . You can add an extra protection by wearing a cloth mask to the classic mask. You wear it double.
![20200510_193409](https://user-images.githubusercontent.com/64379267/82104187-ddbb3e80-96e3-11ea-9a34-78ccdba44024.jpg)

**Comment by Orantesamo** [comment]
We always have to be alert went we go out to public places.  We  need to protect ourselves.

**Comment by Lucas-Czarnecki** [comment]
This is not an issue relevant to JHU's data. Please close.

**Comment by Orantesamo** [comment]
Sorry mr.
 Lukas. I am taking the class.  It is a project for me to get credit for my class.

**Comment by Orantesamo** [comment]
I closed it. If it shows again contact github.
