### ISSUE TITLE
Feature Req: Visual Data over Time

### ISSUE THREAD

**Issue by ladris** [CSSEGISandData/COVID-19#253]
Would it be possible to incorporate a slider to visualize the data over time?

For example, if I want the information to display the previous x report for comparison to y's current report, or to have it slideshow from x date to current to animate the data for a time-frame or see the spread/growth in an area to  determine projected detection path or spread vector. (With the understanding that it's displaying data based on testing, not necessarily real-time infection spread)

**Comment by aleksandar-jovicic** [comment]
Already suggested in #76

**Comment by CSSEGISandData** [comment]
Thank you for the suggestion. There were similar requests for this and we are keeping them in mind when we build out future capabilities!
