### ISSUE TITLE
French total cases diminishing

### ISSUE THREAD

**Issue by Quentin38500** [CSSEGISandData/COVID-19#2534]
Someone can explain me why French total confirmed is lower on **5/16/20** than **5/15/20** ? It would say that 177207 - 177319 = **-112 new cases** : it's impossible ! Same between **5/12/20** and **5/13/20** ! If @CSSEGISandData could make a correction ?
However thanks a lot for you great work !

**Comment by Quentin38500** [comment]
> thats because they count possible cases as confirmed cases. 

Ok thanks @yetzt ! I don't really speak very good English and I didn't understand well their operation.

**Comment by yetzt** [comment]
see #2459
