### ISSUE TITLE
Something is incorrect with the data for Spain

### ISSUE THREAD

**Issue by jpmieville** [CSSEGISandData/COVID-19#2535]
The data from Spain shows a sharp fall on the cumulative cases sees the figure on the following link. 

[https://github.com/jpmieville/COVID-19_data_analyis/blob/master/spain.png](https://github.com/jpmieville/COVID-19_data_analyis/blob/master/spain.png)

**Comment by BenAveling** [comment]
Something very strange happened at 24/4. Cases drop by about 10,000. 

Not immediately clear if it was too high before or too low after or some combination of both.

![image](https://user-images.githubusercontent.com/4499276/82139055-8eeae180-9868-11ea-9538-d9f10297029c.png)

**Comment by BenAveling** [comment]
See issue #2522

**Comment by jpmieville** [comment]
Thank you for the feedback
