### ISSUE TITLE
Why there is so many invalid data for US?

### ISSUE THREAD

**Issue by dprojects** [CSSEGISandData/COVID-19#2539]
Why there is so many invalid data for US?
https://github.com/dprojects/covid-19-data-test/blob/master/indexHopkins.html

Here is the tool output (mind-blowing):
![screen](https://raw.githubusercontent.com/dprojects/covid-19-data-test/master/screen2.png)

The Recovered file will be added for US also? Why there is no such file for US?

**Comment by CSSEGISandData** [comment]
@dprojects Thank you.  Public health departments often have to revise reporting which can cause numbers to drop.
