### ISSUE TITLE
Fix name for "Belgium" in WHO situation report timeseries data

### ISSUE THREAD

**Issue by jmcastagnetto** [CSSEGISandData/COVID-19#254]
In the file https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv, the country "**Belgium**" is misspelled as "Belgiun"

Ref: Line 82 in https://github.com/CSSEGISandData/COVID-19/commit/37e53a697fd3e3c204f8ba0e4e9fcd1ad807039c

**Comment by CSSEGISandData** [comment]
Thank you for the notification! We have updated the table to fix the typo!
