### ISSUE TITLE
UK deaths are incorrect the true figure is 44,094 - hospitals + care home data

### ISSUE THREAD

**Issue by ayumi-cloud** [CSSEGISandData/COVID-19#2541]
Your stats for UK deaths are completely wrong! Here are some links to prove it: 

- https://www.dailymail.co.uk/news/article-8335421/UPDATE-1-UK-COVID-19-death-toll-nears-43-000-official-data.html

- https://metro.co.uk/2020/05/19/uk-death-toll-now-44000-according-ons-figures-12724403/ 

- https://www.itv.com/news/2020-05-19/almost-10-000-coronavirus-related-care-home-deaths-in-england-and-wales/ 

- https://www.mirror.co.uk/news/uk-news/breaking-uk-coronavirus-death-toll-22049711

You can go to the UK government website here: https://www.ons.gov.uk/

The total UK deaths as of 19th May 2020 is **44094**. Please post correct data and not incorrect data!

----

> At least 44,000 people have now been killed by COVID-19 in the UK, devastating statistics confirmed today.

> And more than 11,000 victims - around a quarter of the total number of coronavirus victims - were care home residents in England and Wales.

> The Office for National Statistics figures, which was released today, has lumped almost 10,000 extra fatalities on top of the Department of Health's official count of 34,796 yesterday. The DH count only includes patients who have tested positive for the virus.

> Data shows the number of people dying with the virus each week has dropped again - but the ongoing crisis in care homes means there are still more deaths than would be expected in an average year.

> Britain's status as the worst-hit country in Europe is underlined by the figures, with Italy so far recording 32,000 deaths, by comparison. Only the US has recorded more deaths, with 90,000 victims.

> ONS data, which only covers England and Wales, confirmed 39,071 people had died with the coronavirus in all settings by May 8. The figures include patients whose death was suspected to be from COVID-19.

> At least 1,211 further people were known to have died in English hospitals between May 9 and May 17, according to the NHS, taking the England and Wales total to 40,282.

> In addition, National Records of Scotland - the equivalent of the ONS north of the border - counted 3,213 deaths by May 10, and Northern Ireland's Statistics Agency, NISRA, added 599 up to May 13.  

> This takes the total for the UK to at least 44,094. But the actual number, taking into account more recent counts from Scotland and Northern Ireland, will be even higher.

**Comment by Fuzzygoat** [comment]
Hi, you can only go off the official figures. Currently that would seem to be [https://coronavirus.data.gov.uk/](url) Whilst I appreciated that many more deaths might have occured, the official data has to be your ground truth.

**Comment by ayumi-cloud** [comment]
@Fuzzygoat Maybe you don't understand UK Datasets, let me explain to you!

Your link in your comment is showing `Public Health UK` which `only shows the number of deaths in UK hospitals!` - The data doesn't include deaths outside hospitals and ICU stats.

Here is how the UK deals with it's data:

### Public Health UK Dataset

- https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public

- https://www.gov.uk/government/publications/covid-19-track-coronavirus-cases

The above data does **NOT** show information about deaths outside hospitals and ICU cases!

### UK ICU Reports Dataset

- https://www.icnarc.org/Our-Audit/Audits/Cmp/Reports

The above information gives reports on all ICU cases in UK! The ICNARC is a goverment website dealing with **ICU Statistics**.

Here is an example of a report (as of today): https://www.icnarc.org/DataServices/Attachments/Download/5fc93a39-1098-ea11-9125-00505601089b

### UK Deaths Dataset

- https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases

The above information gives reports of deaths at care homes, hospitals and outside hospitals deaths. The ONS is a government website and stands for: **Office of National Statistics**

### Conclusion

Your website data is totally wrong and a waste of time for scientific people needing correct data stats.

**Comment by Fuzzygoat** [comment]
@ayumi-cloud So what your saying is that the UK reporting is a mess and there is no single source of definitive numbers?

**Comment by ayumi-cloud** [comment]
@Fuzzygoat 

Yes, please use multiple data sources when counting the UK stats.

**Comment by Fuzzygoat** [comment]
@ayumi-cloud So you certain there is no duplication between these sources, we can just take each one and add them up?

**Comment by ayumi-cloud** [comment]
@Fuzzygoat 

UK Data as of yesterday would be like this:

- Hospitals Deaths: 35,704 (dated 19th May)
- Total Deaths (Hospital and outside hospital): 44,094 (dated 19th May)

- Number of Confirmed Cases: 248,293
(UK only counts confirmed cases in hospitals not outside)

Total ICU Admissions: 8,699
ICU Cases with outcomes: 6,860
ICU cases with ongoing: 1,839
(ICU Stats are weekly and are dated 15th May)

Hope that helps you.

**Comment by ericleigh007** [comment]
I don't think CSSE should just add them up.  I think a bit of humility and a little professionalism is in order.  This effort that CSSE has embarked on is sort of thankless job and the ways of reporting data, being all different, with different standards and methods, makes the job a n**2 problem.  I applaud their efforts, even though I'm sure the tabulation of data at all levels has errors.  I'm also sure they are doing their best to keep up with each country's idiosyncrasies.

According to what I read on the UK government site being used here, the data contains not only hospital deaths but this.
*deaths of people who have had a positive test result for COVID-19 confirmed by a Public Health or NHS laboratory*  
That would seem to NOT exclude people who died outside of hospital who were proven to have COVID-19 by lab tests.  As the method is by confirmation at a lab, one could expect the data to lag realtime by days or even weeks.

Take a look at the public data set again.

@ayumi-cloud   Are you like, an official government person?

**Comment by CSSEGISandData** [comment]
@ayumi-cloud we have been aware of this issue for some time, but the ONS data cannot easily be integrated into our pipeline without disrupting the temporality of our data. ONS releases data with a significant time delay and as a single data release once per week. Implementing those would disrupt the linearity of the deaths time series data and prevent any useful analysis of the trends in deaths over space and time in the UK, as we would see spike in deaths once per week that actually represent the deaths two to three weeks prior. We would like to capture this data but it would lose its usefulness and would have knock on effects of weakening our cases and recovered statistics.

@ericleigh007 thank you for your kind words.

**Comment by Fuzzygoat** [comment]
@CSSEGISandData Totally agree, I was aware of the mismatch in the numbers reported bue to the way that the UK collects, records and reports its data. As you mentioned I think the temporal integrity of almost compete data is more important than 100% accurate data that jumps around with no definable underlying cause. @ericleigh007 no offence intended, I was referring to the summation of data, not the actual people who have unfortunately died.

**Comment by ayumi-cloud** [comment]
If anyone from The UK reads this issue and wants covid-19 deaths data for town and city level they can use the ONS embed data, found here: https://www.ons.gov.uk/visualisations/dvc811/msoamap/index.html
