### ISSUE TITLE
Spain Recovered has dropped to 0

### ISSUE THREAD

**Issue by raffg** [CSSEGISandData/COVID-19#2543]
on 05/19/2020, in time_series_covid19_recovered_global.csv, Spain is reported has having 0 recovered. It should be at least the previous day's value, 150376.

**Comment by benflips** [comment]
...which has caused active cases to appear to go through the roof, for Spain, and all Europe:
![image](https://user-images.githubusercontent.com/8161516/82403907-8bd33980-9a92-11ea-8734-340b903cef24.png)

http://covid19forecast.science.unimelb.edu.au/

**Comment by benflips** [comment]
While we are on the subject of Spain...  it also appears to have -10k new cases on the 24 April.

![image](https://user-images.githubusercontent.com/8161516/82404315-92ae7c00-9a93-11ea-8592-ddcedfc48253.png)

**Comment by chasenakamura** [comment]
Aw man

![Spain Oops 5-19](https://user-images.githubusercontent.com/65649602/82419015-808ff780-9a19-11ea-9f75-8c55f2d4f49c.png)

**Comment by yetzt** [comment]
this is probably because JHU publishes spain as provinces only, but the recovery number is only available for the whole of spain: https://cnecovid.isciii.es/covid19/

**Comment by GregFrei** [comment]
Dafuq?!

![image](https://user-images.githubusercontent.com/45398614/82430473-a3f48a00-9a8d-11ea-96bf-1fc3d22c1f40.png)

**Comment by AIAIAIDavid** [comment]
The drop in the Spanish confirmed cases on 23/04 is explained here:

https://github.com/CSSEGISandData/COVID-19/issues/2522

No clue what happens today with recovered.
