### ISSUE TITLE
Missing Data from DE, FR & IT since one week

### ISSUE THREAD

**Issue by MartinLemke** [CSSEGISandData/COVID-19#2544]
Sice 14th may 2020 there are no data for Germany, Italy and Spain in COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports.

**Comment by yetzt** [comment]
they're published on district level now, you have to summarize them programmatically

**Comment by MartinLemke** [comment]
Thank You. This feature is new! So I must update my program.
