### ISSUE TITLE
Sudden decrease in recovered?

### ISSUE THREAD

**Issue by briancpark** [CSSEGISandData/COVID-19#2547]
I used the recent timeseries database for my data visualizations here: https://github.com/briancpark/COVID-19-Visualizations

But I'm getting weird numbers? Recovered is suddenly spiked down, leading to a spike up in active cases. Is anyone else getting the same results, or is my code for processing the `.csv` files wrong?

![COVID19_worldwide](https://user-images.githubusercontent.com/46528046/82477647-b82a9c80-9b0a-11ea-91ea-7a2dd5fd6d6e.png)

![COVID19_worldwide_active](https://user-images.githubusercontent.com/46528046/82477654-ba8cf680-9b0a-11ea-81a3-4e26e6a41436.png)

**Comment by raffg** [comment]
Spain recovered numbers went to 0. See [#2543](https://github.com/CSSEGISandData/COVID-19/issues/2543). They have since been corrected.
