### ISSUE TITLE
Column shift in COVID-19-master\csse_covid_19_data\csse_covid_19_daily_reports

### ISSUE THREAD

**Issue by MartinLemke** [CSSEGISandData/COVID-19#2551]
The Province_State data are filled into the column Admin2 after the US dates. In file 05-19-2020.csv at line 2982; see screenshot.
![jhu-colshift](https://user-images.githubusercontent.com/63868574/82501160-18164880-9af5-11ea-8496-02d68a3bb8bb.png)

**Comment by Lucas-Czarnecki** [comment]
The data from JHU appears to be in order. I believe the problem has to do with how you are opening the csv file on your end. Are you opening it as a comma-delimited file? Do you have other delimiters selected (e.g., space, tabs, etc.) when opening the file?

**Comment by MartinLemke** [comment]
I opened it with libre office for visualization, later I'll open and process it by PHP script.

OK, I will check, what you sayed. Thank you.
