### ISSUE TITLE
Do we use Slack already? Where can I find the channel?

### ISSUE THREAD

**Issue by ChristophGer** [CSSEGISandData/COVID-19#256]

**Comment by ChristophGer** [comment]
Addressed https://twitter.com/1of7dot5billion/status/1235741352564006912

**Comment by klartext** [comment]
Oh no.
Why should we use slack? See no reason for that.

**Comment by CSSEGISandData** [comment]
We currently do not have a publicly open slack channel for this repository.

**Comment by klartext** [comment]
Just for the record: there is also rocket chat, so there is no need for a closed platform like slack.

https://github.com/RocketChat/Rocket.Chat

**Comment by ChristophGer** [comment]
thanks
