### ISSUE TITLE
Inconsistency in Saratoga and Schenectady NY

### ISSUE THREAD

**Issue by Temtesb** [CSSEGISandData/COVID-19#2564]
The data for April 22 seems to be inappropriately high.  

![image](https://user-images.githubusercontent.com/25267268/82730282-7e08f880-9ccc-11ea-8064-e770565a054f.png)

**Comment by d76d30dbl** [comment]
This blip is not in my 21-May Series.
Are you building your own time series one day at a time?   that could give you such a problem.
Suggest you load complete time series daily as it contains fixes to known flaws in previous days' data.

**Comment by Temtesb** [comment]
I was using this base: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports
and then appending the dates.  Shifted to: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv
and it looks like it resolved the problem.  Thanks for the heads up, issue resolved.
