### ISSUE TITLE
Ongoing issue with data for Benin

### ISSUE THREAD

**Issue by dot26** [CSSEGISandData/COVID-19#2575]
It dropped from 339 to 135 for cases confirmed, and now even the recovered cases number has dropped.

**Comment by CSSEGISandData** [comment]
Hello

Sorry for the delay. We have looked into this issue and will not be making adjustments to our data. The discrepancy comes from the government of Benin including cases diagnosed by PCR and rapid diagnostic tests (antigen tests) until May 19th ([source 1](https://www.gouv.bj/actualite/671/), [source 2](https://www.gouv.bj/actualite/684/)). They do not provide the breakdown prior to this date.
