### ISSUE TITLE
In This Day of UNICODE, Why Remove "Latin Characters"?

### ISSUE THREAD

**Issue by HallidayDW** [CSSEGISandData/COVID-19#2577]
The 05-26-2020 UID/ISO/FIPS LookUp Table is accompanied by the notation "remove Latin characters".

This brings up a (potentially) sore issue that I have been seeing for _Months_: the _removal_ of Latin _accents_ from Names that are _properly_ spelled with Latin _accents_!

Why is this "necessary", in this day and age of UNICODE Character Sets?

Such was "necessary" back in the ancient ASCII days, where accented characters simply couldn't be represented.

However, we are no longer living under such "stilted" and limited character sets!

_**If**_ there are, actually, systems out there that simply cannot handle such extended character sets, then _**please**_ provide a Mapping File, back to the _proper_ Latin Character Spellings! So those of us that care, can have the proper _spellings_!

**Comment by CSSEGISandData** [comment]
@HallidayDW understand - artifact of some downstream processing.  Agree that it's suboptimal.
