### ISSUE TITLE
WHO Time Series Data:  Date format for 4/19/2020 is in an inconsistent format

### ISSUE THREAD

**Issue by sfairgrieve** [CSSEGISandData/COVID-19#2579]
In the file:  `who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv`

The header currently looks like this:

```
...,4/17/2020,4/18/2020,19-Apr,4/20/2020,4/21/2020,...
```

Obviously this is not a huge deal, but it throws off code using this file.  

Thanks for your hard work in compiling this repo/data!  It has been tremendously useful!

**Comment by CSSEGISandData** [comment]
Thanks @sfairgrieve
