### ISSUE TITLE
New York counties zero recorded

### ISSUE THREAD

**Issue by hamedkhe** [CSSEGISandData/COVID-19#2581]
Hello, 
I got the county data through raw links for both confirmed and death cases.
Death:"https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"
Confirmed: "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"
There is no record of confirmed and death cases for  Kings, Bronx and Queens counties of New York. 
I get data from these links. These links have an issue or the data not recorded. If data did not record, is it possible we encounter same issues for 
different counties.

**Comment by d76d30dbl** [comment]
county: New York contains combined count for NYC boroughs.
All others are 0.
If you need the borough data, you could also pull down the appropriate data from 
https://github.com/nychealth/coronavirus-data
where there is files grouping data by several criteria.

Yes-- there are other states that are combining data into one reporting bucket (Rhode Island, for one)

**Comment by hamedkhe** [comment]
Thank you for respond and providing the alternative data source for NY.
