### ISSUE TITLE
Improbable daly cases in several EU countries

### ISSUE THREAD

**Issue by nikkalita** [CSSEGISandData/COVID-19#2582]
Calculate daily cases by subtracting the cumulatives between successive days and odd features become apparent including 
- France has 26,843 new cases on 12 Apr though less than 4,000 either side
- Spain, France, UK have negative new cases on several days
Is this perhaps due to changes in reporting methods ?

**Comment by Ericdmmiller** [comment]
Same problems in the reporting of deaths.

It might be a simple error, or a change in reporting methodology, or the dead are literally coming back to life to seek revenge.

It's probably one of those three things.

**Comment by traut21** [comment]
Spain has changed the count system, once again

**Comment by nikkalita** [comment]
Well, at least its not zombies.

Clap Responsibly,

Nicholas (Nik) Kalita

Facebook <https://www.facebook.com/Nicholas.Kalita>

Fight Niks Cancer <https://www.gofundme.com/manage/fight-niks-cancer>

Chondrosarcoma Care And Support Group
<https://www.facebook.com/groups/ChondrosarcomaCareAndSupport/>
