### ISSUE TITLE
Consistency between US time-series files

### ISSUE THREAD

**Issue by afergmaroon** [CSSEGISandData/COVID-19#2583]
Normally the 3000+ counties/categories in the two US time-series csv files are in sync, but since May 20th the confirmed-cases entries for Dukes and Nantucket, MA and Kansas City, MO appear in rows 3253 and 3254 while they still appear at their original rows 3149 and 3150 in the deaths file.

**Comment by d76d30dbl** [comment]
I can't offer a reason for this, but
the  lack of sync appears to be that the "Confirmed Cases" file is sorted on the UID column while the "Deaths" file is sorted on FIPS then UID. 

Suggest you sort the data the way you want it as a first step until (if) this gets addressed.    

You need to remain sensitive to new county or county-like entities being inserted and/or removed as occurred in first couple months and that later time-series files may fix  prior day errors.

keep at it...
