### ISSUE TITLE
Error in Spain death cases?

### ISSUE THREAD

**Issue by bob1494** [CSSEGISandData/COVID-19#2594]
The number of deaths decreased between 24th and 25th of May. The number of deaths decreased from (28752) to (26834). 

Is this an error - since the number of deaths is cumulative for other countries-?

![spain deaths](https://user-images.githubusercontent.com/66203415/83350476-0d558200-a345-11ea-96bc-23af74ff763b.png)

**Comment by jeannechaverot** [comment]
Hello, I have the same issue with other countries such as France, Switzerland, and Kazakhstan.

**Comment by ObliviousMonkey** [comment]
See this [El País](https://english.elpais.com/society/2020-05-26/spanish-health-ministry-lowers-coronavirus-death-toll-by-nearly-2000.html) article (EN):

>The discrepancy has been attributed to the elimination of duplicate records and the fact that regions had reported suspected Covid-19 fatalities as confirmed cases.

Same thing is going on in France where data is being consolidated, and I'm guessing in a lot of other countries now that the wave is slowly receding.
