### ISSUE TITLE
fuck you COVID-19!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by lovetingyuan** [CSSEGISandData/COVID-19#26]

**Comment by CWrecker** [comment]
And the point of this is?

**Comment by PenelopeFudd** [comment]
Lost a loved one.

**Comment by chinaman12345** [comment]
BLOCK CHINAMAN FROM EVERYCOUNTRY TO ENTER! 
PROBLEM SOLVED!!
HAVE A GREAT DAY!

**Comment by PenelopeFudd** [comment]
That won't solve it.  It could happen in any country.  See MERS, which comes from bats and/or camels in the middle east, kills about one-third of those infected, and is still killing people to this day: https://en.wikipedia.org/wiki/Middle_East_respiratory_syndrome

**Comment by Fromalaska49** [comment]
@CSSEGISandData I believe there is a need to monitor the issues and pull requests in this repo

**Comment by dawenx** [comment]
@CSSEGISandData i suggest this issue should be closed if not deleted, thanks.
