### ISSUE TITLE
Missing UID because Sakha (Yakuti(y)a) Republic is inconsistently spelled

### ISSUE THREAD

**Issue by sollyucko** [CSSEGISandData/COVID-19#2603]
The location is spelled as "Sakha (Yakutiya) Republic, Russia" in https://github.com/CSSEGISandData/COVID-19/blob/web-data/data/cases.csv, but spelled as "Sakha (Yakutia) Republic, Russia" in https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv. The difference is very minor ("Yakutiya" vs "Yakutia") but it causes the UID lookup to fail and return an empty value, which causes my data processing to fail.

The cases.csv entry was added in commit d9cccd69b9e4d416b252516ff4d05c8b9d4f3d84, and the UID_ISO_FIPS_LookUp_Table.csv entry was introduced in commit b844f57ad469fbc5ad64a74c07c9774e6c82d2da.

Could you please fix one of them? [According to Wikipedia](https://en.wikipedia.org/wiki/Sakha), either spelling is acceptable.

Related: https://github.com/CSSEGISandData/COVID-19/issues/2509

**Comment by Lucas-Czarnecki** [comment]
Agreed, this is an issue that should be fixed. More specifically, the issue appears to be with the Lookup Table's `Combined_Key`, (which refers to Yakutiya as **"Sakha (Yakutia) Republic, Russia"**). Whereas, the Lookup Table's `Province_State` refers to the same place differenty (i.e., **"Sakha (Yakutiya) Republic"**). The way JHU refers to Yakutiya is, however, consistent across the Lookup table as well as the web-data and the daily reports as far as the `Province_State` variable is concerned. 

I've seen this issue occur before and I would wager it will come up again. I build around it by always recreating `Combined_Key` according to relevant string values.

**Comment by CSSEGISandData** [comment]
Corrected.  Apologies for the typo.

**Comment by Lucas-Czarnecki** [comment]
Thank you! Y'all are rock stars. :)
