### ISSUE TITLE
Wrong data for Russia from 06/01/2020

### ISSUE THREAD

**Issue by vladchel** [CSSEGISandData/COVID-19#2604]
In the time series: 414328 confirmed and 4849 deaths. The correct data: 414878 and 4855. See стопкоронавирус.рф (screenshot attached) and other daily reports for Russia.

![стопкоронавирус.рф](https://user-images.githubusercontent.com/21196770/83479478-22035880-a4b2-11ea-8c6e-c1250e922f93.png)

**Comment by vladchel** [comment]
Recovered is wrong too: 175514 (in the time series) vs. 175877 (correct).

**Comment by vladchel** [comment]
For 6/2/2020 wrong data again: 423186 in time_series_covid19_confirmed_global.csv and 423741 is correct value.

The reason in publishing data for separate regions of Russia in daily reports and calculating time series as a sum of all regions. Sum for Russia in Confirmed column in csse_covid_19_data/csse_covid_19_daily_reports/06-02-2020.csv is 423186 (the same as the wrong result in time series). Looks like data for some region(s) are absent or incorrect.

Please add a value to time series from the official source - not as sum from the incomplete source.

**Comment by CSSEGISandData** [comment]
@vladchel Thank you and sorry for the confusion.  A clarification for the difference is posted in the [data modification record](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md).
