### ISSUE TITLE
Duplicate FIPS?

### ISSUE THREAD

**Issue by eilmrein** [CSSEGISandData/COVID-19#2605]
Lines 513 and 514 of the UID_ISO_FIPS_Lookup_Table.csv file contain the same UID: 80410. Should UID be unique?

**Comment by bobromeo** [comment]
Imo YES

**Comment by eilmrein** [comment]
So, can I rely on it getting fixed?

**Comment by CSSEGISandData** [comment]
Apologies for the duplication.  It's been corrected.
