### ISSUE TITLE
Oklahoma: Large Discrepency in Daily Report

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#2608]
Daily Report for Confirmed on 6/1/2020 is 6913 versus OK Dept of Health 6573.
Deaths: 350 vs 334

https://coronavirus.health.ok.gov/
![OK DoH](https://user-images.githubusercontent.com/62083925/83535860-80cfce80-a4c0-11ea-851c-5d9ed3c4c93e.PNG)

**Comment by CSSEGISandData** [comment]
@DavidViral Thank you for reporting.
