### ISSUE TITLE
Include EU in the global time series

### ISSUE THREAD

**Issue by Xubor** [CSSEGISandData/COVID-19#2612]
Please include row for the European Union in the "global" time series datasets.
That will automatically enable to compare EU in many applications using your data with other big states like India, China, Russia and US - regional powers with complex internal structure. EU member states are also coordinating their policies on the covid-19 outbreak and have common outer border policy, so it makes sense to create aggregated data.

Data for the EU should be calculated analytically as a sum for its member states, as in https://en.wikipedia.org/wiki/Member_state_of_the_European_Union#Current_members 

The geographical center of the EU is at 49°50′44″N 9°54′22″E according to https://en.wikipedia.org/wiki/Geographical_midpoint_of_Europe#2020-present

**Comment by vladchel** [comment]
In this case total sum for all data in a day will be calculated twice for the entire Europe and all countries in it. Just make a sum for all EU countries yourself.

**Comment by winwiz1** [comment]
Google made JHU data available as a public BigQuery dataset. You can write SQL that returns EU-wide counts, then use [BigQuery Console](https://console.cloud.google.com/bigquery) to query the dataset and save the results to a disk file. Alternatively use [Covid-19 Query Tool](https://covid.winwiz1.com), it will remember the selection of countries and allow you to get the numbers from the same dataset for each country, no SQL needed. Then you can save results and import it to Excel or other software to do sums, perform comparisons etc.

**Comment by Xubor** [comment]
I can easily calculate data for the EU myself. But in many _other applications_ using this dataset there in no easy way to introduce data for "the EU". If the EU could be added here, it will solve this problem for all applications.
