### ISSUE TITLE
Recovered for Sweden is 0 as of 2/6

### ISSUE THREAD

**Issue by luckehal** [CSSEGISandData/COVID-19#2618]
Recovered for Sweden went to 0 on 2'nd of June (it was 4971 on 1'st of June).
On the 3'rd of June figure is still 0.

**Comment by yetzt** [comment]
[Folkhälsomyndigheten](https://www.folkhalsomyndigheten.se/the-public-health-agency-of-sweden/communicable-disease-control/covid-19/statistics/) does not provide this data.

**Comment by luckehal** [comment]
Where did it come from before (1/6 and earlier) then? The dataset had data for recovered for SE then.

**Comment by yetzt** [comment]
the [sources](https://github.com/CSSEGISandData/COVID-19/blob/master/README.md) do not specify.

**Comment by luckehal** [comment]
Here is another site that reports that info. Source unknown, https://platz.se/coronavirus/

**Comment by luckehal** [comment]
![Screenshot_20200604_235655_com android chrome~2](https://user-images.githubusercontent.com/23380165/83814892-74fe2b00-a6bf-11ea-861d-0691610175b6.jpg)

**Comment by CSSEGISandData** [comment]
@luckehal and @yetzt Thank you both for the issue and the discussion.  We added comments to the [data readme](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md) and modded the recovered time series.
