### ISSUE TITLE
france confirmed cases for June 3 is down significantly

### ISSUE THREAD

**Issue by kalmenk** [CSSEGISandData/COVID-19#2619]
there's an issue with data for France for June 3. It shows confirmed cases (cumulative) down almost 40% from the previous day.

**Comment by yetzt** [comment]
> Decrease in confirmed cases due to a change in calculation method.
> Since June 2, patients who test positive are only counted once.
— translated from [french covid dashboard](https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA)

also note that thats the cases presented by jhu as *confirmed* cases for france are not all actuallly confirmed cases, but do include probable cases. (#2459) thats why jhu reports 188802 cases for france while actual france reports 151677 cases for france.

**Comment by CSSEGISandData** [comment]
@kalmenk I'm sorry for the error in reporting yesterday.  It was quickly corrected and the data should be correct if you pull files again.

@yetzt thank you for linking to the explanation

**Comment by btklein** [comment]
I appreciate your response @yetzt for going a bit deeper than a quick ‘commit’ about discrepancy issues. I mentioned my thoughts a bit deeper for us as a community to try and do our best to provide appropriate controls over data changes and reasoning behind the accepted changes in #2617 

In the time of my writing these two comments, it appears @CSSEGISandData is getting around to answering these associated issues, thank you!

Best to all, keep up the support in this fight against the virus!

**Comment by kalmenk** [comment]
thanks all and stay safe!
