### ISSUE TITLE
Mistaken number of recovered for Chile

### ISSUE THREAD

**Issue by alexanderhetz** [CSSEGISandData/COVID-19#2622]
The numbers listed for 6/2/2020 and 6/3/2020 seem to be the number of active cases, not recovered.

**Comment by CSSEGISandData** [comment]
@alexanderhetz Thank you, modifications have been made to the pipeline and current files based on the description in the [data modification record](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md).
