### ISSUE TITLE
Dent County (FIPS 29065) and Douglas County (29067) missing from Missouri data

### ISSUE THREAD

**Issue by troymartinhughes** [CSSEGISandData/COVID-19#2625]
As reported on the state of Missouri's COVID-19 dashboard (http://mophep.maps.arcgis.com/apps/MapSeries/index.html?appid=8e01a5d8d8bd4b4f85add006f9e14a9d), both of these counties have cases, yet they are consistently missing (for at least several days) from the JHU Daily Updates.

**Comment by CSSEGISandData** [comment]
Thanks @troymartinhughes
