### ISSUE TITLE
Hubei confirmed cases shifted after 2/22/20

### ISSUE THREAD

**Issue by wzmli** [CSSEGISandData/COVID-19#263]
In time_series_19-covid-Confirmed.csv, Hubei confirmed cases on 2/22/20 and 2/23/20 are the same.
All entries after 2/22/20 seem to be shifted by one day.

**Comment by CSSEGISandData** [comment]
We have checked this entry in our data and have confirmed that the data is correct. We have no control over the reports coming out of China. We have seen strange reporting like the case when Hubei released 15,000 new confirmed cases after a change in their reporting criteria. This may very well be another strange occurrence in their reporting.
