### ISSUE TITLE
Brazil Recovered drops to 0 for June 5

### ISSUE THREAD

**Issue by BJReplay** [CSSEGISandData/COVID-19#2630]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv shows Brazil Recovered = 0 for 2020-06-05

**Comment by youyanggu** [comment]
Also Brazil had 0 deaths for June 5

**Comment by cyclaero** [comment]
In addition the total case count is the same as the day before
