### ISSUE TITLE
Switch from integer to floating point format for counts in time_series_*_US.csv files

### ISSUE THREAD

**Issue by 5LarryPeranich7** [CSSEGISandData/COVID-19#2631]
Today's data in time_series_covid19_confirmed_US.csv and time_series_covid19_deaths_US.csv is in floating point instead of integer format.  In particular, the numbers end in ".0".  All prior count values were in integer format.

**Comment by CSSEGISandData** [comment]
Thanks @5LarryPeranich7 .  Should be fixed.
