### ISSUE TITLE
Inconsistency in data of Pakistan in time_series_covid19_confirmed_global.csv

### ISSUE THREAD

**Issue by AlyNaRahim** [CSSEGISandData/COVID-19#2633]
Errors in time_series_covid19_confirmed_global.csv Pakistan Data 

1. The value of number of cases drops to zero on 5/16/20 
2. Total confirm cases on 6/5/20 is 93983 but 89249 is reported in the data

Reference: http://covid.gov.pk/

**Comment by CSSEGISandData** [comment]
@AlyNaRahim unfortunate consequence of shift in reporting schedule at source conflicting with timing of update.
