### ISSUE TITLE
Brazil's numbers are missing on the world map.

### ISSUE THREAD

**Issue by Karlomanio** [CSSEGISandData/COVID-19#2637]
The map still shows individual cities and number of infected, but the totals for the country are missing.  They should follow the US as number 2.
![image](https://user-images.githubusercontent.com/16403966/83955710-b1df3480-a81b-11ea-8feb-e20e54edef82.png)

**Comment by CSSEGISandData** [comment]
@Karlomanio thanks for pointing this out.  The issue is resolved now.
