### ISSUE TITLE
FIPS codes in Lookup Table are 5 digits at the state and county-level

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#2638]
FIPS codes in JHU's Lookup table have been problematic for awhile (e.g., see #2530). In the past, leading zeros were truncated such that FIPS codes for states such as Alabama were single rather than two digits (e.g., 1 rather than 01). Similarly, at the county-level places such as Autauga, Alabama were four rather than five digits (e.g., 1001 rather than 01001).

(To be clear, FIPS codes are supposed to be 2 digits at the state-level and 5 digits at the county-level).

Most recently, a new commit d2b54366f6c92227fc3071045bc1b2d1331d14ff has added leading zeros such that all US locations have a five-digit FIPS code. This commit has fixed the issue at the county-level (e.g., Autauga Alabama is now 01001). **FIPS codes at the state-level, however, continue to be incorrect (e.g., Alabama is now 00001) - affecting more states than before.**

**Comment by CSSEGISandData** [comment]
Thanks @Lucas-Czarnecki.  Latest merge should resolve.
