### ISSUE TITLE
Inconsistence with case definition change in WHO time series csv 

### ISSUE THREAD

**Issue by wzmli** [CSSEGISandData/COVID-19#264]
Confirmation definition changed on Feb 14th WHO situation report 25 was done properly for Hubei China (which is fine). 
However, the "Clinically diagnosed" addition was added on Feb 17th for Mainland China in the csv.
When you compare the number of confirmed cases between Hubei and Mainland China for Feb 14, 15, 16, Hubei currently has higher numbers compared to Mainland China in the csv.

**Comment by hongru94** [comment]
Hi, for Feb 14, 15 and 16, Hubei's confirmed cases include both lab-confirmed and Clinically diagnosed. For mainland China, the total cases only contain the lab-confirmed cases. You could refer to the pdf in who_covid_19_sit_rep_pdfs for more detailed information.
