### ISSUE TITLE
Beckham, Oklahoma, US June 3-6 Confirmed are lower than June 1-2?

### ISSUE THREAD

**Issue by ceejay12** [CSSEGISandData/COVID-19#2640]
Beckham is showing 10 cases as of June 1 &2 but is now at 7 cases.

**Comment by CSSEGISandData** [comment]
@ceejay12 I believe this is a result of revision of data by state health department.  This is consistent with reporting from other sources.  Downward revision like this are not atypical as health departments review and revise their case logs.
