### ISSUE TITLE
Michigan Total Cases Grossly Different than State's Report

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#2641]
Daily Report for June 7 has 64413 Confirmed Cases vs 58870 confrimed cases by michigan.gov

JH June 7 Daily Report shows confirmed plus probable cases for June 7, but prior days only shows confirmed cases giving a huge blip for June 7. 

![image](https://user-images.githubusercontent.com/62083925/83993022-31562c00-a920-11ea-9f12-8dc6d88d4121.png)

https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html

**Comment by Location-Artistry** [comment]
Yes I'm seeing this problem too.  Not sure how to record these 'new' probables.  Additionally Michigan changed their reporting page to an angular based app, and it is breaking all of the scrapers.  They are offering downloads in Excel, which is not helpful.

**Comment by dsheldon** [comment]
This is a big jump. For clarification

The main [Michigan dashboard](https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html) reports both confirmed and probables, which is apparently new:
![Michigan](https://user-images.githubusercontent.com/5331486/84059484-b37a3b00-a988-11ea-98e4-c61ed2eac528.png)

The [twitter announcements](https://twitter.com/MichiganHHS) report only confirmed:
![image](https://user-images.githubusercontent.com/5331486/84059389-86c62380-a988-11ea-9b7d-f3e984f25462.png)

Prior JHU data matches the numbers on the twitter announcements (confirmed only), so this looks like a massive jump. 

Which numbers does JHU plan to track?

(Apparently #2642 is a dup.)

**Comment by Jelfff** [comment]
This is likely related.
For June 7 JHU data shows 5901 cumulative "unassigned" cases for Michigan.
The cumulative count for Michigan "unassigned" cases for prior days has been vastly lower.

**Comment by CSSEGISandData** [comment]
Probable cases and deaths are a recent addition to the Michigan data.  We are using both laboratory confirmed and probable cases as reported by the state.
