### ISSUE TITLE
Implausible Recovered Cases

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#2643]
If recovered cases and number of deaths are added up, they should be at most equal to the number of confirmed cases. in spain there are several severe discrepancies in this regars as of right now:

* cantabria: +168
* ceuta: +4
* extremadura: +183
* galicia: +668
* melilla: +5
* murcia: +712
* pais vasco: +4042

also:
* diamond princess (canada): +1
* nova scotia (canada): +1
* northern marianas (us): +11

please do employ sanity checks on your data.

**Comment by TweepCoding** [comment]
Same issue

**Comment by CSSEGISandData** [comment]
Consistent with and dependent on data from Ministerio de Sanidad.

**Comment by yetzt** [comment]
how is this possibly consitent when there are more people healed than infected?
