### ISSUE TITLE
Chile missing fatalities are not added

### ISSUE THREAD

**Issue by aerdem4** [CSSEGISandData/COVID-19#2645]
According to news, Chile has added probable deaths. It is missing from the Chile data.
A news source: https://www.europeworldnews.com/chile-records-649-deaths-the-highest-number-of-victims-in-a-single-day-after-the-calculations-have-been-corrected/

**Comment by aerdem4** [comment]
Maybe it can be added today. Total fatalities clearly increased to 2264:
https://www.gob.cl/coronavirus/cifrasoficiales/#resumen

**Comment by CSSEGISandData** [comment]
@aerdem4 Thank you for being on top of this.  It should come online soon when the [Ministerio de Salud dashboard](https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/) is updated.
