### ISSUE TITLE
What's the plan to handle countries (like Brazil) that stop publishing data?

### ISSUE THREAD

**Issue by gfairchild** [CSSEGISandData/COVID-19#2646]
I'm a member of the COVID-19 forecasting team at Los Alamos (see our website [here](https://covid-19.bsvgateway.org/)), and we're using your data in our models. It's been tremendously helpful!

As I'm sure many on the @CSSEGISandData team are aware, [Brazil just stopped publishing its data](https://www.theguardian.com/world/2020/jun/07/brazil-stops-releasing-covid-19-death-toll-and-wipes-data-from-official-site), and it even went so far as to wipe all data from its official website.

This likely won't be a one-off, and we're wondering what your team has planned for how to handle this situation. When a country stops publishing data, will you continue to provide that country's counts as zeroes? Or perhaps NaNs? Will you remove the country?

Thanks! Any information you can provide on your plans for handling this situation will help us.

**Comment by CSSEGISandData** [comment]
@gfairchild Brazil is still publishing their data at https://covid.saude.gov.br/, but the Ministry of Health did change their form for reporting (delta vs. cumulative, recoveries nationally vs. regionally).  Fortunately we don't have to visit the issue today, but I agree that it will have to be visited.
