### ISSUE TITLE
Recovered cases US API don´t works 

### ISSUE THREAD

**Issue by camilo-17** [CSSEGISandData/COVID-19#2648]
Hello everyone, 

I use this URL to get the data: 

`https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?f=json&where=(Confirmed>0)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Deaths%20desc%2CCountry_Region%20asc%2CProvince_State%20asc`

But all the data with Country_Region: US not show values for recovered cases

**Comment by gsjennings** [comment]
I have been just calculating my own recovered based on Confirmed cases 28 days ago minus deaths today. This is an estimate that a number of city governments I have been tracking are using. If you need help setting up a formula to do this automatically, I can share with you.

**Comment by Nanditdhania** [comment]
Hey Camilo, did you find any workaround for this issue?

**Comment by CSSEGISandData** [comment]
@camilo-17 and @Nanditdhania , maybe this?

`https://services1.arcgis.com/0MSEUqKaxRlEPj5g/ArcGIS/rest/services/ncov_cases2_v1/FeatureServer/3/query?f=json&where=(Confirmed%3E0)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Deaths%20desc%2CCountry_Region%20asc%2CProvince_State%20asc`
