### ISSUE TITLE
Implausibly large increase in recovered cases in Brazil for 2020-06-08

### ISSUE THREAD

**Issue by BJReplay** [CSSEGISandData/COVID-19#2650]
In https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv Brazil Recoveries jump by 94,305 on 8 June, up from an average of 12,000 per day over the last week.

**Comment by CSSEGISandData** [comment]
Transition to subnational recovery sourcing [[1](https://github.com/CSSEGISandData/COVID-19)].
