### ISSUE TITLE
Chile June 5 recoveries - implausibly large increase

### ISSUE THREAD

**Issue by kalmenk** [CSSEGISandData/COVID-19#2651]
data shows 78,053 new recoveries in Chile on June 5th which is implausibly large as their average is about 2,000 per day.

**Comment by kalmenk** [comment]
also 627 new deaths on June 8th in Chile which is way higher than their daily average.

**Comment by CSSEGISandData** [comment]
@kalmenk as noted in the [data modification records](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md), Chile changed reporting methodology on the 5th.  This accounts for the spike.

**Comment by kalmenk** [comment]
thanks for the update
