### ISSUE TITLE
Michigan Confirm Cases Unchanged beginning 6/6/20

### ISSUE THREAD

**Issue by jcshipman2** [CSSEGISandData/COVID-19#2653]
I've noticed the county level confirmed case and death figures have been unchanged for all counties in Michigan since 6/6/20. What is happening?

![image](https://user-images.githubusercontent.com/66682437/84155620-897f5200-aa36-11ea-8601-46f73b2f87ef.png)

**Comment by zurdibus** [comment]
yeah counties are static since 6/5, on 6/7 Unassigned jumped 5901 and now the total numbers are about 5300 too high.  I think mighican.gov/coronavirus changed their format around that time but I have no idea how these numbers are pulled from michigan.

**Comment by jcshipman2** [comment]
> yeah counties are static since 6/5, on 6/7 Unassigned jumped 5901 and now the total numbers are about 5300 too high. I think mighican.gov/coronavirus changed their format around that time but I have no idea how these numbers are pulled from michigan.

It's the "probable" cases. Covidtracking.com figure for Michigan also jumped on 6/5 or so; the jump was due to probable cases. On that same date, their usual 6:30ish PM screenshot that they post from Michigan's website changed completely to one that included probable cases.

**Comment by CSSEGISandData** [comment]
@jcshipman2 @zurdibus There is a jump on the 5th due to the inclusion of probable cases but there is stale data for Michigan as well.  I am working to correct and will close this issue when I push the update.  My apologies for the delay.
