### ISSUE TITLE
2020-06-10 Daily Report: Peru cases used for deaths

### ISSUE THREAD

**Issue by youyanggu** [CSSEGISandData/COVID-19#2655]
See image below, I think it is self-explanatory. The deaths column is wrong - there are not 200k deaths in Peru!

<img width="553" alt="Screen Shot 2020-06-10 at 12 30 05 AM" src="https://user-images.githubusercontent.com/1267035/84227163-a86efa00-aab1-11ea-9949-dffe2c3d0c73.png">

**Comment by jtene001** [comment]
Based on the download, it appears that deaths and confirmed cases may be reversed for Peru.
I get 198,165 deaths and 4,040 new cases today.

**Comment by williamjieh** [comment]
Please fix this issue ASAP

**Comment by vishivish18** [comment]
Yes, it seems Peru columns are wrong
![Screen Shot 2020-06-10 at 10 19 49 AM](https://user-images.githubusercontent.com/3650542/84228209-0debd680-ab04-11ea-8747-37c1114d39ae.png)

**Comment by vishivish18** [comment]
Yes it seems Peru columns are wrong
https://coronalogy.xyz/world
Below are the yesterday's and today's dataframe for Peru
![Screen Shot 2020-06-10 at 10 19 49 AM](https://user-images.githubusercontent.com/3650542/84228401-8ce10f00-ab04-11ea-82ba-f741b015eb8c.png)

![Screen Shot 2020-06-10 at 10 21 38 AM](https://user-images.githubusercontent.com/3650542/84228356-73d85e00-ab04-11ea-8c22-f750ad79521c.png)

**Comment by J9E** [comment]
Peru's deaths seem to be **5,571** according to the data on JHU's site here: https://coronavirus.jhu.edu/map.html 
Please correct it asap in the csv file.

**Comment by youyanggu** [comment]
To the developers: it wouldn't hurt to have a simple assert to catch cases like this. For example:

`assert country.daily_deaths < 5000`

You can always have a whitelist to skip outlier cases (although I have yet to see any country report more than 5000 deaths in one day).

**Comment by CSSEGISandData** [comment]
Error propagated from Interior Ministry.  Corrected now.  My apologies.

**Comment by vishivish18** [comment]
Thanks for the fix @CSSEGISandData , it was a scary, VERY scary bug.
