### ISSUE TITLE
Spike in Deaths

### ISSUE THREAD

**Issue by sinsatbir** [CSSEGISandData/COVID-19#2656]
Huge spike in deaths as 202912 deaths seen in data on 09th June, 20, amounting total to .6 million deaths (.2 million above form 08th June, 2020)
![Screenshot](https://user-images.githubusercontent.com/10520072/84227603-7934a900-ab02-11ea-8f0d-a612e4adce45.jpg)

**Comment by AmalVijayan** [comment]
The death count of Peru is not actually the death count, its the active cases count

**Comment by youyanggu** [comment]
See #2655

**Comment by J9E** [comment]
Peru's deaths seem to be **5,571** according to the data on JHU's site here: https://coronavirus.jhu.edu/map.html
Please correct it asap in the csv file.

**Comment by CSSEGISandData** [comment]
Apologies.  Error is corrected.

**Comment by sinsatbir** [comment]
Thank-you Sir, keep up the great work.
