### ISSUE TITLE
Peru Deaths for 2020-06-09 are wrong

### ISSUE THREAD

**Issue by paulsjones** [CSSEGISandData/COVID-19#2658]
Looks like the case count got swapped into the time series file for the most recent date period (June 9th, 2020). As of 11:20 PM Pacific Time, the file shows 204K deaths (which happens to match the number of confirmed cases).

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

![image](https://user-images.githubusercontent.com/8229115/84233698-abfd8380-aaa7-11ea-8092-f50e7fded217.png)

**Comment by MatthieuHernandez** [comment]
The death count of Peru in time_series_covid19_deaths_global.csv is not actually the death count, its the active cases count. See [#2655](https://github.com/CSSEGISandData/COVID-19/issues/2655).

**Comment by CSSEGISandData** [comment]
@paulsjones @MatthieuHernandez Apologies.  Corrected now in latest merge.
