### ISSUE TITLE
How many places are in the wrong location?

### ISSUE THREAD

**Issue by Sashie** [CSSEGISandData/COVID-19#266]
Um.. Calgary, Alberta, Canada is in Canada not Russia

![Untitled](https://user-images.githubusercontent.com/17128178/76059668-0c859d80-5f5a-11ea-8d8c-e94ea754d7f9.png)

**Comment by SlowFox71** [comment]
Seems to be a wrong sign in the longitude.

**Comment by Sashie** [comment]
Someone fixed that one but I'll leave this open for now in case there are others that are found later ^.^

**Comment by CSSEGISandData** [comment]
We have taken note of the issue and are investigating. A quick fix for issues related to this, is to either refresh your browser, clear the browser cache, or open the dashboard in an incognito window. Sorry for the inconvenience.
