### ISSUE TITLE
Peru figure for deaths is wrong (2020/06/10)

### ISSUE THREAD

**Issue by brunoscherrer** [CSSEGISandData/COVID-19#2661]
The value for deaths (5000+) seems to be replaced by the value for cases (200000+).

**Comment by CSSEGISandData** [comment]
@brunoscherrer Thanks.  It's corrected in latest merge, if you pull the latest you should find the correct data.  My apologies for the earlier error.

**Comment by ManchesterWuer** [comment]
@CSSEGISandData Thank you for the update, it saved my day's work.

**Comment by brunoscherrer** [comment]
thanks!
