### ISSUE TITLE
Wrong moving avg line chart on dashboard on coronavirus.jhu.edu/data/new-cases-50-states

### ISSUE THREAD

**Issue by tcm-cchen** [CSSEGISandData/COVID-19#2662]
The chart line on https://coronavirus.jhu.edu/data/new-cases-50-states/texas, here is Texas, it's not a 5 day moving average, it's actually a 3 day moving average.

**Comment by CSSEGISandData** [comment]
Greetings @tcm-cchen, you are correct.  The 3-day average is noted on the page.
