### ISSUE TITLE
Issues with data from Brazil Ministry of Health

### ISSUE THREAD

**Issue by laurahel** [CSSEGISandData/COVID-19#2668]
Hi,

It is across the news that the Brazil Ministry of Health is not a reliable source of data anymore, given they are not reporting the correct numbers.

We would like to suggest using another source for Brazil. We have other websites reporting the numbers correctly. Here is one good example: https://brasil.io/covid19/

And here is the API to extract the data: https://github.com/turicas/covid19-br/blob/master/api.md

Thanks.

**Comment by CSSEGISandData** [comment]
Thanks @laurahel
