### ISSUE TITLE
Readme for csse_covid_19_data has incorrect and confusing documentation

### ISSUE THREAD

**Issue by crackernutter** [CSSEGISandData/COVID-19#2669]
For example: 
When documenting fields and field descriptions for daily reports:

> Incidence_Rate: Admin2 + Province_State + Country_Region.
> Case-Fatality Ratio (%): = confirmed cases per 100,000 persons.
> US Testing Rate: = total test results per 100,000 persons. The "total test results" is equal to "Total test results (Positive + Negative)" from COVID Tracking Project.

The definitions for incidence rate and case fatality ratio is incorrect, and from looking at the CSVs in the daily reports (the ones with the US counties), I don't even see a US Testing Rate attribute.  The new fields seem to be limited to Incidence_Rate and Case-Fatality_Ratio.

**Comment by troymartinhughes** [comment]
Agree. These issues all previously reported two weeks ago (https://github.com/CSSEGISandData/COVID-19/issues/2597) with no corrections provided by JHU.

**Comment by CSSEGISandData** [comment]
Hello @crackernutter! The definition of "Incidence_Rate" has been corrected. Thanks for your feedback.
