### ISSUE TITLE
Question about "Unassigned" and "Out of" in US Data

### ISSUE THREAD

**Issue by ripstaur** [CSSEGISandData/COVID-19#2672]
Each state has some "unassigned" cases and deaths, and some that are listed as "Out of [state name]" Where do these numbers come from?

**Comment by troymartinhughes** [comment]
@ripstaur I've posted an analysis here (https://www.linkedin.com/pulse/county-less-covid-19-how-unassigned-out-state-counties-troy-hughes/) that describes out of state and unassigned cases, as well as the issues these can pose to analysis.

**Comment by CSSEGISandData** [comment]
@ripstaur and @troymartinhughes I agree that it would be best to be able to localize every case, however as noted, when states do not provide information that allows us to localize data we are unable to independently provide spatial resolution.
