### ISSUE TITLE
Error in St. Landry - Louisiana county confirmed cases in time series data 

### ISSUE THREAD

**Issue by GiorgiLomaia** [CSSEGISandData/COVID-19#2673]
St. Landry confirmed cases in the time series data contains error, as the cases drop on April 4th compared to April 3rd. Total confirmed cases go from 68 to 45, which is not possible since this is cumulative data.

**Comment by CSSEGISandData** [comment]
Health departments often revise numbers downward in response to revisions to individual cases.  You can see that the numbers in the time series are consistent with local reporting at the time: [April 3](https://kpel965.com/april-3-louisiana-covid-19-update/) vs [April 4](https://kpel965.com/april-4-louisiana-covid-19-update/).
