### ISSUE TITLE
India Confimed Cases data for 10-Jun is incorrect

### ISSUE THREAD

**Issue by SidKumarSingh** [CSSEGISandData/COVID-19#2675]
India's Total Confirmed Cases data in the Time Series (Global) file is 276,583 - a change of 437 only. The actual official figure as per MoHFW is 286,579 - a change of 10,433. Please check and update.

UPDATE: It seems the script that fetched data ran before the MoHFW website ran its daily update so the numbers reflecting are for yesterday (i.e. cases as of 09-June)

**Comment by SidKumarSingh** [comment]
Seems the script that fetched data ran before the MoHFW website ran its daily update so the numbers reflecting are for yesterday (i.e. cases as of 09-June)

**Comment by vishivish18** [comment]
Any update on this ?

**Comment by vishivish18** [comment]
@CSSEGISandData @SidKumarSingh 
Any idea whether this will be fixed or should we do it manually in that case?

**Comment by SidKumarSingh** [comment]
> 
> 
> @CSSEGISandData @SidKumarSingh
> Any idea whether this will be fixed or should we do it manually in that case?

Not sure. We don't have access to the load script. And the script seems to be using runtime as timestamp rather than the time quoted by MoHFW on their website. I have my own script to scrape this data from the website and that also pulls the timestamp. You can check it in my repo

**Comment by SidKumarSingh** [comment]
@vishivish18 Seems the script picked today's data correctly. I have manually corrected data for yesterday in the time series file and created a pull request. Hopefully @CSSEGISandData will merge it so that order is restored

**Comment by vishivish18** [comment]
yes @SidKumarSingh , thanks for the info, I too updated my DB manually for my tracker https://coronalogy.xyz/world

**Comment by CSSEGISandData** [comment]
Sorry for the inconvenience. We ran into some technical difficulties last night, but we have adjusted the time series data and resolved all the issues.
