### ISSUE TITLE
README TRANSLATION

### ISSUE THREAD

**Issue by tina1296** [CSSEGISandData/COVID-19#2677]
Hello, I am a college student contributing in an open source project.
The README of your project does not have a Korean translation, so it may be difficult for Korean GitHub users to contribute more actively. I would like to help Korean GitHub users who want to contribute more to the project by translating the README.
Can I translate your company's README into Korean? I will wait for your answer.

**Comment by Lucas-Czarnecki** [comment]
I can't imagine JHU objecting as it would defeat the open science philosophy of making data public on GitHub. I would go ahead. Just make sure to comply with their Terms of Use in their first README file.

**Have fun!** (don't forget to close this issue).
