### ISSUE TITLE
UK data haywire on dashboard

### ISSUE THREAD

**Issue by jtene001** [CSSEGISandData/COVID-19#2682]
Looking at the dashboard at 3:49 eastern time June 11:

It seems that UK cases have jumped from 291,588 last night to 584,263 now, and deaths have gone from 41,213 last night to 82,642 now. Suspiciously close to a doubling. Maybe someone should check the data – or send major relief to our British friends.

**Comment by yetzt** [comment]
yep, they publisheing uk total as well as england, wales, northern ireland and scotland, and then adding all of them together, effectively counting everything twice.

![jhu are stupid](https://imgur.com/mP8HZhU.png)

i made so many posts about best practices, but they do not appear to bestow any manure.

**Comment by jtene001** [comment]
Well, I'm certainly happy that 41,000 people didn't die in the last 12 hours.

**Comment by yetzt** [comment]
i hope @CSSEGISandData is aware and will fix it in a few days.

**Comment by jtene001** [comment]
It appears they fixed it.

**Comment by yetzt** [comment]
yeah, they fixed the nimbers, but the coordinates are still broken. they mised up east and west in the longitude. 

![fucked up longitude](https://imgur.com/CRuRyXW.png)

**Comment by CSSEGISandData** [comment]
@jtene001 @yetzt Geo will be updated in the next pull.  Temporary jump on handover from national to subnational data.

**Comment by jtene001** [comment]
thanks

**Comment by CSSEGISandData** [comment]
@jtene001 no problem, thanks for the notice.  Going to close.
