### ISSUE TITLE
Assign Crimea and Sevastopol areas to Russia

### ISSUE THREAD

**Issue by ivanbilibin** [CSSEGISandData/COVID-19#2684]
Crimea and Sevastopol areas are marked as a part of Ukraine. Unfortunately this is not true anymore. Please correct the corresponding entries.

https://en.wikipedia.org/wiki/Republic_of_Crimea

Please note, that Ukraine [does not](https://covid19.rnbo.gov.ua) officially publish the Covid numbers for Crimea, but the Russia [does](https://стопкоронавирус.рф/information/). By labeling those data as Ukrainian, you effectively mislead the public.

**Comment by ivanbilibin** [comment]
#540

**Comment by ivanbilibin** [comment]
#1262 #2221

**Comment by Lucas-Czarnecki** [comment]
I strongly disagree. The majority of UN nations do not recognize Crimea as part of Russia. I, therefore, do not see any reason for JHU to change its approach. 

JHU references https://covid19.rnbo.gov.ua/ as its source of data on Ukraine. But if there is more to this story (e.g., how data are collected on said site) then an updated README should suffice.

**Comment by CSSEGISandData** [comment]
@ivanbilibin @Lucas-Czarnecki a description of this issues is provided in the June 5th data modification record of the Readme.  I'm copying it here:

"June 5, As noted in the disclaimer for the dashboard, the geographic designations in this data have been designed to be consistent with public guidance from the US State Department. This does not imply the expression of any opinion whatsoever on the part of JHU concerning the legal status of any country, area or territory or of its authorities. In implementing subnational data for the Russian Federation and the Ukraine, data for the Crimean Peninsula has been apportioned in line with this guidance. This adjustment explains a difference in national totals for both the Russian Federation and Ukraine relative to alternate reporting."
