### ISSUE TITLE
Some locations are not showing on the map

### ISSUE THREAD

**Issue by kelvinelove** [CSSEGISandData/COVID-19#269]
Some locations with confirmed infections are not showing on the map, for example, India, South Africa etc as shown on this screenshot.

![image](https://user-images.githubusercontent.com/8897257/76075646-07e6d680-5fa6-11ea-8c6a-39600ca3c239.png)

They are, however part of the statistics on the other widgets. I've tried multiple refreshes but the error still persists.

**Comment by CSSEGISandData** [comment]
Any issues you may be experiencing with the dashboard try clearing your browser cache and refreshing the page. If issues are still persisting, check the issues page or read me page of this repository for status updates on the dashboard.
