### ISSUE TITLE
USA State Daily Reports includes data from other countries

### ISSUE THREAD

**Issue by darlose04** [CSSEGISandData/COVID-19#2693]
The latest update to the USA State Daily Report data (06-11-20.csv) includes the data from hundreds of provinces/states from countries other than the United States. This seems like it would have been done in error, since this data has been specific to US states/territories up until the 06-10-20.csv.

**Comment by CSSEGISandData** [comment]
Thank you for catching this issue. This may have been a result of some technical issues last night that have now been resolved.
