### ISSUE TITLE
Remove non-US locations from US-only daily reports.

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#2694]
A recent commit 6e9880c5d46e4298e4ecfb2c5238496d24683a65 has corrected an issue by removing non-US locations from US daily reports for 06-11-2020.csv. 

Just a heads up. While you are at it. The same issue (see #2305) also affects two other US daily files:

   * 04-18-2020.csv
   * 04-19-2020.csv

**Comment by CSSEGISandData** [comment]
Thanks for the catch again! We have updated the files to include only US state data.
