### ISSUE TITLE
Russian data?

### ISSUE THREAD

**Issue by jtene001** [CSSEGISandData/COVID-19#2695]
Seems strange to me that Russian new cases consistently hover at slightly below 10,000 cases per day. This is especially suspicious given the Kremlin's proclivity toward controlling information. 

Is there anything in place to determine whether these reports can be trusted at all?

**Comment by Lucas-Czarnecki** [comment]
Unfortunately, no. But I think you are right. It would be in the public interest to have disclaimers on data integrity. I can understand if JHU is reluctant, but would strongly support such an effort.
