### ISSUE TITLE
St. Louis, Missouri, US Confirmed Case Count is Not Changing

### ISSUE THREAD

**Issue by blarson** [CSSEGISandData/COVID-19#2696]
Comparing `\csse_covid_19_data\csse_covid_19_daily_reports\06-06-2020.csv` to `\csse_covid_19_data\csse_covid_19_daily_reports\06-11-2020.csv`, the Confirmed Case Count for St. Louis, Missouri, US did not change.  

The [county website](https://stlcorona.com/resources/covid-19-statistics1/), however, indicates at the time this issue was created that 155 confirmed cases were added in the county over that time frame.

Strangely, the Deaths count and Active case count have changed.  This leads me to believe that this is not just a lag in reporting, but an error in an upstream data source.

![Comparison](https://user-images.githubusercontent.com/11714445/84542767-bb571980-acbf-11ea-9f84-17f662dc601a.png)

**Comment by CSSEGISandData** [comment]
@blarson resolved
