### ISSUE TITLE
India data for 12 June 2020 is the same as 11 June 2020

### ISSUE THREAD

**Issue by mkapoorisid** [CSSEGISandData/COVID-19#2697]
India data for 12 June 2020 is the same as 11 June 2020

**Comment by vishivish18** [comment]
@CSSEGISandData Yes there is delta of 0. Continuous second day with data missing for INDIA. I think it has something to do with your script timing/execution for India.

**Comment by vishivish18** [comment]
@CSSEGISandData Any update on this, India's entry has not been updated since 2 days now. You may verify this PR #2700  It seems to have fixed it.

**Comment by SidKumarSingh** [comment]
Had manually edited the file but it didn't get merged. And today's update again has T-1 data. Basically, my guess is the script is running before MoHFW updates their website so the data is lagging by a day. So if you see the number under 13 June it's actually the total case count that was updated on 12 June. I am planning to modify my India crawler to update the numbers for India before loading to my dashboard

**Comment by SidKumarSingh** [comment]
@mkapoorisid @vishivish18 Updated my Python script to accommodate for this in case you are interested

**Comment by CSSEGISandData** [comment]
@mkapoorisid @vishivish18 @SidKumarSingh Thank you all for your help and patience.  I have updated the data in the time series files to remove the data lag.  We also have pushed the daily update time forward by 1 hour which should hopefully pick up the MoHFW daily update.  I hope this resolves the issue.
