### ISSUE TITLE
time_series_covid19_confirmed_US.csv sort order for 06-12-2020

### ISSUE THREAD

**Issue by RobertClemenzi** [CSSEGISandData/COVID-19#2698]
Is the new time_series_covid19_confirmed_US.csv data format for 06-12-2020 an error or permanent?
The initial records are different and records that used to appear grouped at the end of the file are now after each state. As a result, there is no longer a one-to-one correspondence between the US confirmed and deaths files. This appears to be a sort order difference.

**Comment by CSSEGISandData** [comment]
@RobertClemenzi resolved in latest merge.
