### ISSUE TITLE
change in format of U.S. state/county confirmed time series  ?????

### ISSUE THREAD

**Issue by markserlin** [CSSEGISandData/COVID-19#2701]
Why on earth would you change the format of the time series spreadsheet that has US county/state confirmed data.   Please return it to the format you have been using all along.  CHANGING THE FORMAT OF THE SOURCE DATA  THIS FAR INTO IT IS CRAZY.

**Comment by CSSEGISandData** [comment]
@markserlin Resolved in latest merge.
