### ISSUE TITLE
Fort Bend, Texas 2020-06-13

### ISSUE THREAD

**Issue by huyunwei** [CSSEGISandData/COVID-19#2706]
The reported confirmed cases was 2,385 on Jun 13th, and no update on Jun 14th. 1point3acres report contains a typo yesterday '2358'. 
Same typo in the JHU time series.

**Comment by CSSEGISandData** [comment]
@huyunwei This is not a typo.  If you look at the [data from the Texas Department of Health and Human Services](https://dshs.texas.gov/coronavirus/TexasCOVID19DailyCountyFatalityCountData.xlsx), you will see that the Texas Department of Health and Human Services reported 2358 cases for Fort Bend County Texas on 6/13, and 2385 cases for Fort Bend on 6/14.
