### ISSUE TITLE
Consistency in Format

### ISSUE THREAD

**Issue by MehranDHN** [CSSEGISandData/COVID-19#271]
It's very important to keep the consistency of data source. Until last night each record in CSV Format  was separated by **\r\n** (CR/LF) . Today I realize it's already changed to **\n**.

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238

**Comment by CSSEGISandData** [comment]
We have noted the issue and will look into a solution. Thank you. Closing this issue because of duplicate.
