### ISSUE TITLE
recoveries: UK, Sweden, Netherlands, US States

### ISSUE THREAD

**Issue by m-kovalsky** [CSSEGISandData/COVID-19#2714]
Is recovered case data available for the UK, Sweden or Netherlands? And also would be great for the US States - currently it's just for the US as a whole with no state breakdown. Thanks

**Comment by NaKo91** [comment]
For the UK, Sweden, Netherlands I couldn't find any data.
Concerning the US, the dashboard has a chart about deaths/recoveries for every single state.

![Unbenannt2](https://user-images.githubusercontent.com/66752944/85054351-30cd5900-b19c-11ea-911d-20bf5cbeed2e.JPG)

**Comment by m-kovalsky** [comment]
@NaKo91 thanks, but the data in the files in github don't have US State recovered case data.

**Comment by HallidayDW** [comment]
The "recovered case data", "in the files on GitHub" for the US States, is found in the /csse_covid_19_daily_reports_us.

Unfortunately, it is not in a time series form, only in single day "snapshots", as @NaKo91 showed from the dashboard.

**Comment by m-kovalsky** [comment]
ah i see. why does the data for each state and each day repeat a bunch of times?
also, it shows the recovered amount (which also repeats) and this doesn't match the sum of all the states' recoveries.

**Comment by HallidayDW** [comment]
@m-kovalsky:

"the data for each state and each day", in the /csse_covid_19_daily_reports_us, are _all_ cumulative values, just as they are for the time series files.

So, data "repeat[ing]", day after day, simply shows no change.

I've been "reconciling" the /csse_covid_19_daily_reports_us files with the /csse_covid_19_daily_reports (global) files, with the global and US Time Series files.

While there are discrepancies, they are typically in the tenths of a percent, and easily attributable to the asynchronous nature of the data reporting.

(Note: I give very little "weight" to the "Recovered, US" numbers in the  /csse_covid_19_daily_reports_us [when present] and the /csse_covid_19_daily_reports. The needed information is already encoded within the global and US Time Series files.

However, I will note that, every now and then, the Time Series numbers need to be adjusted upward, by a few tenths of a percent.)

**Comment by m-kovalsky** [comment]
@HallidayDW scratch that on the repeating values - it was an issue on my data intake process. 

For more recent dates, the recovery numbers tie between the overall US numbers in the worldwide files and the US state data. However, for dates closer to Apr 12 the numbers don't reconcile.

Thanks for looking into this.
