### ISSUE TITLE
Spanish daily cases not working

### ISSUE THREAD

**Issue by lmbigdata** [CSSEGISandData/COVID-19#2715]
Hi,

Spanish daily cases are not working properly.

For example, dashboard is reporting for 14/06/20 323 daily cases

and font website is reporting 48
https://www.rtve.es/noticias/20200616/mapa-del-coronavirus-espana/2004681.shtml

Thanks for your work!

**Comment by CSSEGISandData** [comment]
Hello

Please see sources from the Spanish government:
[June 13th](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_135_COVID-19.pdf)
[June 14th](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_136_COVID-19.pdf)

The difference between the two days is 323. The rtve source captures the previous 24 hours, which does not capture the full cases diagnosed in a day once you pass midnight of the day of interest.

CSSE
