### ISSUE TITLE
Brazoria County, Texas new cases incorrect...

### ISSUE THREAD

**Issue by sanoanalytics** [CSSEGISandData/COVID-19#2716]
show 631 should be 31 see below link from county health department
https://www.brazoriacountytx.gov/departments/health-department/brazoria-county-coronavirus-map

**Comment by CSSEGISandData** [comment]
@sanoanalytics Thank you.  Unfortunately the uptick in the total is coming from the state of Texas's data and is consistent in both their [data file](https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx) and on their dashboard: ![image](https://user-images.githubusercontent.com/60674295/84915347-aba64f00-b08a-11ea-8076-826e606094db.png)  It is currently unclear exactly why there is such a change in reporting from the state for Brazoria.

**Comment by NaKo91** [comment]
The additional cases date back to outbreaks in prisons that have not been reported until now. 

![Unbenannt](https://user-images.githubusercontent.com/66752944/84921700-1c6a5d00-b0c5-11ea-8ffa-8946d92b47db.JPG)

**Comment by CSSEGISandData** [comment]
Thanks @NaKo91.  Closing this as I believe the reporting from the state site is the correct reflection of the cases in Brazoria per state guidance.
