### ISSUE TITLE
The visualisation of china covers entire asia, the visualisation can be normalized in the dashboard.

### ISSUE THREAD

**Issue by pavanvamsi3** [CSSEGISandData/COVID-19#272]

**Comment by ciscorucinski** [comment]
Is this just an issue with the farthest 2 or 3 zoom levels? And what do you mean by "normalized in the dashboard"?

**Comment by CSSEGISandData** [comment]
The size of the points on the map are determined by the number of confirmed cases. Please reference the legend on the dashboard for the number ranges we are using to determine sizing. The point sizes are adjusted as you zoom into a country while maintaining the correct size based on case counts.
