### ISSUE TITLE
ERRONEOUS data for Brazoria, Texas in time_series_covid19_confirmed_US.csv

### ISSUE THREAD

**Issue by sanoanalytics** [CSSEGISandData/COVID-19#2720]
on 6/16 implied new case is 631 - that is incorrect

**Comment by avdeveloper** [comment]
what's your source?

**Comment by CSSEGISandData** [comment]
Addressed previously in #2716.  Anderson and Brazoria County Texas do not to reflect cases in the prison populations located in the county in their current data.  The State of Texas Department of Health Services gave public notice of the change both on their dashboard, noted by @NaKo91 above, as well as here: https://twitter.com/TexasDSHS/status/1273005182306181124?s=20.  This is covers #2719 as well.
