### ISSUE TITLE
Chile case data for 6/17

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#2722]
Hello all,

On June 17th, Chile added an additional 31,412 to their national count beyond the new confirmed cases for that day. These cases represent historical infections that were not previously included in the national reporting. At this time, the dates of diagnosis for these 31k cases have not been released and we are unable to allocate them throughout our time series. We are monitoring the situation and will reallocate the cases if the necessary information becomes publicly available.
[(Source 1)](https://twitter.com/ministeriosalud/status/1273285031985725440)
[(Source 2)](https://actualidad.rt.com/actualidad/356945-chile-casos-confirmados-coronavirus-fallecidos-pandemia)

**Comment by Lucas-Czarnecki** [comment]
Thank you, but please do not include RT as a credible source. It is kremlin state-operated propaganda and recognized as such by the US Department of Justice.
