### ISSUE TITLE
England, Wales, Scotland, NorthernIreland:  Is this work in progress?

### ISSUE THREAD

**Issue by psa0000** [CSSEGISandData/COVID-19#2724]
I see the UnitedKingdom now has separate data for England, Wales, Scotland, NorthernIreland but almost all the data is zeros. Is this "work in  progress" and, if so, when will is be completed?
Thanks

**Comment by CSSEGISandData** [comment]
@psa0000 we are working on it and hope to have something soon.

**Comment by psa0000** [comment]
thanks
Peter
