### ISSUE TITLE
North Carolina, Mississippi, Louisiana state not updated

### ISSUE THREAD

**Issue by wpoust** [CSSEGISandData/COVID-19#2727]
The **county** _and_ **state** data for **North Carolina, Mississippi, Louisiana** have not been updated for 6-19-2020.

[State](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/06-19-2020.csv)

[County](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/06-19-2020.csv)

**Comment by prichterich** [comment]
The North Carolina dashboard shows 1,652 cases for 6/19, so please check and update this.

The Mississippi dashboard has not updated since June 17 and states "technical problems".
The Louisiana dashboard has an undated, but presumably recent, note that 1,655 "duplicate" cases were removed.
