### ISSUE TITLE
Country and State Tags have Changed

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#2728]
In the Global time series the text for the Country and Province names were previously ended with an empty space character.  The 6-19-2020 reports truncated the space character.  Some apps will no longer recognize the new names.

**Comment by CSSEGISandData** [comment]
Hello,

Can you be more specific for which global timeseries file you are encountering this issue? And is this in reference to column names or entries themselves?

**Comment by DavidViral** [comment]
I am referring to the entries
I discovered that the change comes from the way in which I download the data.  Previously I dragged my mouse over the table of data and did a copy of the data - those entries had a blank character at the end of the string.  But if I first select the Raw data  then Select All and Copy the data, there is no trailing blank character.




    On Sunday, June 21, 2020, 10:50:52 AM EDT, CSSEGISandData <notifications@github.com> wrote:  
 
 


Hello,

Can you be more specific for which global timeseries file you are encountering this issue? And is this in reference to column names or entries themselves?
