### ISSUE TITLE
Spain: implausible deaths data.

### ISSUE THREAD

**Issue by santids** [CSSEGISandData/COVID-19#2729]
Spain has gone from zero deaths to a thousand deaths in a single day (6/19/20), doesn't look possible.

I'm looking at the file `csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv`.

| date                |   Spain |
|:--------------------|--------:|
| 2020-05-26 00:00:00 |   27117 |
| 2020-05-27 00:00:00 |   27117 |
| 2020-05-28 00:00:00 |   27119 |
| 2020-05-29 00:00:00 |   27121 |
| 2020-05-30 00:00:00 |   27125 |
| 2020-05-31 00:00:00 |   27127 |
| 2020-06-01 00:00:00 |   27127 |
| 2020-06-02 00:00:00 |   27127 |
| 2020-06-03 00:00:00 |   27128 |
| 2020-06-04 00:00:00 |   27133 |
| 2020-06-05 00:00:00 |   27134 |
| 2020-06-06 00:00:00 |   27135 |
| 2020-06-07 00:00:00 |   27136 |
| 2020-06-08 00:00:00 |   27136 |
| 2020-06-09 00:00:00 |   27136 |
| 2020-06-10 00:00:00 |   27136 |
| 2020-06-11 00:00:00 |   27136 |
| 2020-06-12 00:00:00 |   27136 |
| 2020-06-13 00:00:00 |   27136 |
| 2020-06-14 00:00:00 |   27136 |
| 2020-06-15 00:00:00 |   27136 |
| 2020-06-16 00:00:00 |   27136 |
| 2020-06-17 00:00:00 |   27136 |
| 2020-06-18 00:00:00 |   27136 |
| **2020-06-19 00:00:00** |   **28315** |

**Comment by CSSEGISandData** [comment]
@santids If you look at the sitreps from the Spanish government for [June 17](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_139_COVID-19.pdf), [June 18](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_140_COVID-19.pdf), and [June 19](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov-China/documentos/Actualizacion_141_COVID-19.pdf) as an example of the series, you will see that this was the reporting.
