### ISSUE TITLE
Discrepancies in Dashboard Data 

### ISSUE THREAD

**Issue by HaroldFoppele** [CSSEGISandData/COVID-19#2731]
Can anyone explain why the daily cases in the Dashboard for the last 4 month are average 110K/day, yet the total confirmed is "only" 8,8M.
Should be over 12M over the last 4 month only !
The numbers do not add up.

**Comment by lilyclemson** [comment]
Other data Discrepancies include country level data such as US and state level such as Ohio.

**Comment by HaroldFoppele** [comment]
In short : **Messy**

**Comment by HaroldFoppele** [comment]
Why is this closed ?
