### ISSUE TITLE
NC, MS, OR, RI state and county data not updated for 6-21

### ISSUE THREAD

**Issue by wpoust** [CSSEGISandData/COVID-19#2732]
[State](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/06-21-2020.csv) and [county](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/06-21-2020.csv) data for North Carolina, Mississippi, Oregon, and Rhode Island is the same for 6/21 as it was for 6/20.  

Specifically, I checked the confirmed cases and deaths were the same and obviously in error.

**Comment by troymartinhughes** [comment]
Agreed. Mississippi cases and deaths were not updated on 6-18, 6-19, 6-20, or 6-21, as shown below.
![28_MS_daily_cases_with_moving_average_WKND](https://user-images.githubusercontent.com/63983760/85273192-23c99780-b432-11ea-9c99-bf303219b170.png)

However, these numbers are consistent with the MS State Dept of Health which is reporting issues on their website (https://msdh.ms.gov/msdhsite/_static/14,0,420.html).
![missing_miss_screenshot](https://user-images.githubusercontent.com/63983760/85274097-57f18800-b433-11ea-83bd-e2818aa51b70.jpg)

**Comment by prichterich** [comment]
OR and RI update only Monday - Friday, but not on weekends.
MS stopped reporting on 6/16.
But NC reports 1,412 cases for 6/21 (https://covid19.ncdhhs.gov/dashboard), so the data need to be updated.
