### ISSUE TITLE
Data is stale for Sweden since 18th of June.

### ISSUE THREAD

**Issue by cthiebaud** [CSSEGISandData/COVID-19#2735]
"date": "2020-6-17",
      "confirmed": 54562,
      "deaths": 5041,
      "recovered": 0
 
     "date": "2020-6-18",
      "confirmed": 56043,
      "deaths": 5053,
      "recovered": 0
 
     "date": "2020-6-19",
      "confirmed": 56043,
      "deaths": 5053,
      "recovered": 0
 
     "date": "2020-6-20",
      "confirmed": 56043,
      "deaths": 5053,
      "recovered": 0
 
     "date": "2020-6-21",
      "confirmed": 56043,
      "deaths": 5053,
      "recovered": 0
 
which differs from what https://www.worldometers.info/coronavirus/ is reporting.

**Comment by CSSEGISandData** [comment]
@cthiebaud My apologies.  I am in the process of correcting now.
