### ISSUE TITLE
In the US Map, missing Washington County is missing on dropdown

### ISSUE THREAD

**Issue by Karlomanio** [CSSEGISandData/COVID-19#2741]
I can find this county everywhere in Texas, except i can't find it in the dropdown that shows the list of counties and displays the case growth graph. 

See screenshot
![image](https://user-images.githubusercontent.com/16403966/85494907-2dbcd900-b59f-11ea-872e-bca986f9f451.png)

**Comment by CSSEGISandData** [comment]
@Karlomanio this has been resolved so I'm closing the issue.  Thanks.
