### ISSUE TITLE
California hospitalization data

### ISSUE THREAD

**Issue by lijun99** [CSSEGISandData/COVID-19#2742]
California hospitalization data are missing, e.g., from COVID-19/csse_covid_19_data/csse_covid_19_daily_reports_us/xxx.csv. The data can be found at the California Public Health dashboard https://public.tableau.com/views/COVID-19PublicDashboard/Covid-19Hospitals?%3Aembed=y&%3Adisplay_count=no&%3AshowVizHome=no.

**Comment by bkungfoo** [comment]
Numerous other states are also missing hospitalization numbers. Here's a list of them:

'Alaska', 'American Samoa', 'California', 'Delaware', 'Diamond Princess', 'District of Columbia', 'Grand Princess', 'Guam', 'Illinois', 'Iowa', 'Louisiana', 'Michigan', 'Missouri', 'Nevada', 'North Carolina', 'Northern Mariana Islands', 'Pennsylvania', 'Puerto Rico', 'Texas', 'Vermont', 'Virgin Islands', 'West Virginia'

**Comment by NetworkTest** [comment]
For hospitalization as well as other data, JHU CSSE does not provide a data source. I have noticed discrepancies between the state HHS / DPH data and the public-health office for Ventura County, where I live. 

It would be VERY helpful to know which source(s) JHU uses for the nation's most populous state.
