### ISSUE TITLE
400:Invalid Request on raw data directory level

### ISSUE THREAD

**Issue by tcreid** [CSSEGISandData/COVID-19#2744]
Hi, We have a report script (PowerBI) that accesses the directory URL below and then appends the file name...the directory is no longer reachable on its own (i.e. 400: Invalid Request when using a browser).    This just happened in the last few days.

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/

Any ideas?

Thanks

**Comment by CSSEGISandData** [comment]
@tcreid I have no idea what would cause a change in behavior; we haven't changed anything in the repository settings.  I will say that if you are trying to get to the directory listing you could try the github api for [repository contents](https://developer.github.com/v3/repos/contents/).  I think the following would get you the same data:

`curl -k https://api.github.com/repos/CSSEGISandData/COVID-19/contents/csse_covid_19_data/csse_covid_19_daily_reports`

**Comment by tcreid** [comment]
Hi - Ok thank you for the quick response, we will check out the api option...

Take Care, Tim.
