### ISSUE TITLE
Delayed Update for 06-24-2020

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#2746]
Hey @CSSEGISandData, 

Just a friendly flag. Your automated update for daily reports and time-series (in csse_covid_19_data) has not published any new data for 06-24-2020. (Data are typically expected between 04:45 and 05:15 GMT).

**Comment by puf17640** [comment]
Yes! Please fix this @CSSEGISandData.

**Comment by cnehring2306** [comment]
Up to now no update available :-(

**Comment by lorint** [comment]
All the best to those working to bring yesterday's numbers to light.  An incredibly important time to have clarity.

**Comment by anastasiiako** [comment]
Hope there will be an update soon! 
Thank you in advance for fixing this!

**Comment by MARCPIER** [comment]
Still no news?

**Comment by Skorpio21** [comment]
Lot of people around the world is using these files as a source for different projects. The impact of a delay like this is huge. I kindly request to increase the efforts for the fix of this. Thanks a lot for your dedication!

**Comment by CleHou** [comment]
Hello, thank you for all the work you are doing. Good luck for the fix and stay safe!

**Comment by lewinmadrid** [comment]
Would also appreciate any update. We use it for our WMS service. https://gis.genasys.com/

**Comment by Skorpio21** [comment]
In our case, we use these files to inform the people through [https://corona.virus-data.com/index_alt.php?lang=en](https://corona.virus-data.com/index_alt.php?lang=en)

**Comment by bjarkimg** [comment]
no update?

* https://coronatracker.org/ *

**Comment by PeterNCarr** [comment]
An ETA would be useful so people can reschedule resources and timescales etc.
Good luck fixing the issue and keep up the good work.

**Comment by cnehring2306** [comment]
> Would also appreciate any update. We use it for our WMS service. https://gis.genasys.com/

Great tool, will use it on my website. Thanks for the link :-)

**Comment by steveped** [comment]
Already Fri 26th in some parts of the world & no data from Wed 24th. We do appreciate your work, but this seems unacceptably tardy. Can you please post an explanatory note to help us understand?

**Comment by puf17640** [comment]
As @steveped says, the work and effort is enormously appreciated, but this is indeed unacceptable. I am a core member of the [Open Disease API](https://github.com/disease-sh), we are lucky that our service is made to withstand such errors but we would really like to be able to serve **up-to-date** data. If such things are going to happen more often, we need to overthink this repository as a quality source of data.

Thanks alot to anyone working on fixing this problem!

**Comment by steveped** [comment]
> As @steveped says, the work and effort is enormously appreciated, but this is indeed unacceptable. I am a core member of the [Open Disease API](https://github.com/disease-sh), we are lucky that our service is made to withstand such errors but we would really like to be able to serve **up-to-date** data. If such things are going to happen more often, we need to overthink this repository as a quality source of data.
> 
> Thanks alot to anyone working on fixing this problem!

Hi @puf17640. An alternate source I've found is https://covid.ourworldindata.org/data/owid-covid-data.json but there is no recovered cases time series. Given the series of issues that this repo seems to have had, I'm migrating things over where I can now.

**Comment by CSSEGISandData** [comment]
All - I'm very sorry for the delay.  There was a processing error in the push.  We are working to resolve now.  Should be up shortly.  Again, my apologies.

**Comment by lorint** [comment]
> ... working to resolve now.

Thank you so kindly for these efforts.  Your work is making a huge difference in this effort around the globe.

With love,
-Lorin from UK.

**Comment by eolson3260** [comment]
Joining the many others to express our appreciation for the data you provide us each day in a timely manner (early mornings).  At a standstill now, praying for your (the data's) speed recovery;-) 

From the hot spot of Florida:-(

**Comment by puf17640** [comment]
> All - I'm very sorry for the delay.  There was a processing error in the push.  We are working to resolve now.  Should be up shortly.  Again, my apologies.

awesome! hope you can fix it soon! could you give us an update on how things are going so we can estimate when our services can deliver the data again?

**Comment by PCFarese** [comment]
Thanks for your prompt response to these request.  I do notice that there are some data irregularities, for example Russia is about double what World-O-meter has: 14,270 vs.  7,176.  Are you aware of any potential issue here and looking into a bugfix?

**Comment by PCFarese** [comment]
All looks fixed now, thanks!!

**Comment by CSSEGISandData** [comment]
All.  There were a few issues with the US data in the initial update (formatting), but I believe those have all been resolved.  Thank you all for your patience.

**Comment by bjarkimg** [comment]
> > As @steveped says, the work and effort is enormously appreciated, but this is indeed unacceptable. I am a core member of the [Open Disease API](https://github.com/disease-sh), we are lucky that our service is made to withstand such errors but we would really like to be able to serve **up-to-date** data. If such things are going to happen more often, we need to overthink this repository as a quality source of data.
> > Thanks alot to anyone working on fixing this problem!
> 
> Hi @puf17640. An alternate source I've found is https://covid.ourworldindata.org/data/owid-covid-data.json but there is no recovered cases time series. Given the series of issues that this repo seems to have had, I'm migrating things over where I can now.

Reoverd is easy.. average about 22 days from confirmed case, after that we have the other category...

**Comment by KatharinaKanns** [comment]
It's available - many thanks to all of your efforts!

**Comment by Lucas-Czarnecki** [comment]
Thank you to everyone at JHU CSSE for resolving this problem. Everything appears to be working.
