### ISSUE TITLE
June 24  Update ?   Come on!!!

### ISSUE THREAD

**Issue by John-Sin** [CSSEGISandData/COVID-19#2747]
Why can't there be a consistent update time everyday?    Updates keep getting pushed back later and later ....then delayed at random on any given day.    This is very frustrating -- we're trying to get our reports!   Forget India -- we can catch up with it tomorrow.   These whimsical delays cause many of us to lose sleep.

**Comment by Lucas-Czarnecki** [comment]
While I understand your frustrations, I am sure they are also losing sleep. Keep in mind they maintain this repository as a public service.

**Comment by John-Sin** [comment]
Lucas,

Thanks for correcting me.   You were absolutely right -- I felt like a jerk
afterwards and immediately closed it

John Sinclair.

**Comment by Lucas-Czarnecki** [comment]
Hey John, 

No worries. Everyone makes mistakes, but not everyone corrects them. Kudos for the latter. 

All the best, 
Lucas
