### ISSUE TITLE
I hope Trump didn't stop you from updating files!

### ISSUE THREAD

**Issue by sanoanalytics** [CSSEGISandData/COVID-19#2749]

**Comment by jpacerqueira** [comment]
I have rely on this public dataset to inform my public about progression of COVID19. Please let us know if the daily updates are with some delays, or if you'll stop updating this datasets.

**Comment by donkc10** [comment]
Any word on when the daily reports will be updated?  I also use this data each day.

**Comment by CSSEGISandData** [comment]
@jpacerqueira I'm very sorry for the delay.  There was a processing error in the push.  We are manually rerunning now.  Should be resolved shortly.

**Comment by jpacerqueira** [comment]
No worries, I'll inform in my portal, about the delay. Please keep up, doing your excellent  work, informing with the truth on COVID19. Your fantastic work, has been referenced in all my reports, as you as the point of truth for this pandemic. Find here https://fuelbigdata.com/blog my point of publications

**Comment by lorint** [comment]
> We are manually rerunning now.

Thank you so much for this daily resource!

With love,
Lorin from UK
https://emotery.com/covid_info.html

**Comment by jpacerqueira** [comment]
Thanks again for your update

 With Best Regards,
     joao@fuelbigdata.com - https://fuelbigdata.com/blog
    Joao Pedro A. Cerqueira.

**Comment by CSSEGISandData** [comment]
All.  Apologies again for the delay.  I think all of the updates are in and the daily should be good to pull.

**Comment by MaximNN** [comment]
Dear CSSEGISandDATA, 

As we rely on your regular covid-19 time series updates in our organization, could you kindly clarify if today's delay was a one-off event and you will publish data as before (on time), or there will be further delays / bugs / problems?

Appreciate your reply. 

Kind regards,
Maxim

**Comment by CSSEGISandData** [comment]
@MaximNN It was purely the consequence of a multiple abnormal events happening in concert.  It is neither systemic or planned and our intent is to continue to publish between 04:45 and 05:15 GMT as described in #2708.  That said, I cannot guarantee that we will never have an issue that will introduce a delay - I can say that such delays are unintentional and we are working hard to avoid them.

**Comment by MaximNN** [comment]
> @MaximNN It was purely the consequence of a multiple abnormal events occurring in concert. It was neither systemic nor planned and our intent is to continue to publish between 04:45 and 05:15 GMT as described in #2708. That said, I cannot guarantee that we will never have an issue that will introduce a delay. I can say though that such delays are unintentional and we are working hard to avoid them.

Dear CSSEGISandDATA, 

Many thanks for clarification and appreciate your efforts in this in any event.

Regards,
Maxim
