### ISSUE TITLE
Color blind friendly

### ISSUE THREAD

**Issue by jorgeperezrojas** [CSSEGISandData/COVID-19#275]
Thank you so much for the visualization, it is awesome. It would be even better if you change a bit the colors to make them more color blind friendly. I'm color blind so I cannot give you a precise advice on what to do, I can only say that I'm having a bit of trouble following the charts, so I assume that you are using difficult colors for people like me. But there are plenty of places with good resources about what palettes are better than others.

Thanks again, you are doing really a service for everyone.

**Comment by klartext** [comment]
If you ask for a feature and already know there are good ressources to address your problem, it would make sense to add a list of ressources here, IMO. I would assume the people who organize that repository here have enough other tasks that eat up their time. If you make it easier to pick up your ideas, the chance is better they will do it.

Also I wonder, why even though you are color blind, you can't give advices... especially as a Associate Professor in the computer science area. Is that result of a professor's attitude, to wish for something to be done, but let others do the work? ;-)

**Comment by 2fst4u** [comment]
> If you ask for a feature and already know there are good ressources to address your problem, it would make sense to add a list of ressources here, IMO. I would assume the people who organize that repository here have enough other tasks that eat up their time. If you make it easier to pick up your ideas, the chance is better they will do it.
> 
> Also I wonder, why even though you are color blind, you can't give advices... especially as a Associate Professor in the computer science area. Is that result of a professor's attitude, to wish for something to be done, but let others do the work? ;-)

I'm not sure what this response is supposed to achieve. This site is open to the world and not everyone here is capable of contributing to a project like this.

I can attest to the parent post, the colours used for the graph are horrible for those of us with red-green colourblindness. The colours used are literally the hardest for us to distinguish.

**Comment by klartext** [comment]
The orignal issue-opener who seem to know parts of the answers (or at least where to find them) did not provided these information, and just asks others to do this. "This site is open to the world and not everyone here is capable of contributing to a project like this." does not make sense.
From the original issue: "But there are plenty of places with good resources about what palettes are better than others."
So, there are plenty of sources, ok - and which?
A bit strange not to mention them, imo.
So I see no reason why you jumped on this.

BTW: I'm not color blind but also think the colors are a bad choice. So I support this issue, but I have no ideas, which palettes to use. I assume people with color-blindness will now better where to look for that. And the opener of this issue mentioned already that such ressources exist. So what I was asking for is: the issue opener should provide the links to the ressources. Just ignore my sarcasm from my last post and anything is fine.

**Comment by zacanger** [comment]
Some resources:

* [Chrome extension that simulates different types of color blindness](https://chrome.google.com/webstore/detail/colorblinding/dgbgleaofjainknadoffbjkclicbbgaa?hl=en)
* [Accessible color combinations checker](https://webaim.org/resources/contrastchecker/)
* [Accessible color palette builder](https://toolness.github.io/accessible-color-matrix/)

The biggest issue that I see is the use of red, yellow, green, and orange, which all wind up looking almost the same according to the simulator.

**Comment by CSSEGISandData** [comment]
Thank you for the suggestion. We will keep that in mind when we build out future capabilities.

**Comment by klartext** [comment]
FYI:
Metasurface-based contact lenses for color vision deficiency
https://www.osapublishing.org/ol/abstract.cfm?uri=ol-45-6-1379

**Comment by jorgeperezrojas** [comment]
> Thank you for the suggestion. We will keep that in mind when we build out future capabilities.

Thank you for your time and effort.
