### ISSUE TITLE
ERROR with some of your date format 

### ISSUE THREAD

**Issue by samscodes** [CSSEGISandData/COVID-19#2753]
Found a date error on your latest data, this is the example of the date format error 6/24/20_1 .
The error can be found on the Confirmed_US and Deaths_US Files. Example try to filter using this states American Samoa and Guam, . Now we have this error
![error](https://user-images.githubusercontent.com/22851138/85726795-04c84f80-b729-11ea-85f7-68177f5704cf.PNG)

**Comment by CSSEGISandData** [comment]
@samscodes Apologies.  There was an error in the process last night and the recovery introduced a column duplication in the US data files.  It's been resolved in the latest merge.
