### ISSUE TITLE
06-24-2020.csv: Last_update is June 24 instead of June 25 for 100 IOWA records ..

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#2756]
.. and 1 West Virginia record
And Antigua and Barbuda ?!?

Is there no update for June 25, or is it June 25 but the Last_date is wrong ?

**Comment by CSSEGISandData** [comment]
@bobromeo updated in latest commit.

**Comment by crismat1957** [comment]
it seems still June 24 for Iowa. Same data as yesterday

**Comment by CSSEGISandData** [comment]
@crismat1957 If you mean on the UI, then this should correct on the next UI refresh time.  if the time says 12:54 PM (EDT) or later, the correct data should be in.  If it's somethings else (e.g. duplicated data record), please provide additional details.

**Comment by bobromeo** [comment]
@CSSEGISandData At this time the data has not changed, only the record numbers !?!
Iowa is now scattered between 6 - 3062 and West Virginia is now on rec 2810 and Antigua on 3612

When filtering on 2020-06-24 you get all the 102 records, with a Last_Date that are wrong.
