### ISSUE TITLE
Feature Layer not working

### ISSUE THREAD

**Issue by louchios** [CSSEGISandData/COVID-19#2757]
https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c

![layer not working](https://user-images.githubusercontent.com/14114900/85746945-77efa880-b6cc-11ea-9b4b-143d0eeb7006.png)

Thank you.

**Comment by CSSEGISandData** [comment]
@louchios I'm not sure exactly what the issue was, but I just checked and it looks ok now:

![image](https://user-images.githubusercontent.com/60674295/85789799-35928f80-b6fd-11ea-847e-2e74f63a4f46.png)
