### ISSUE TITLE
IOWA again same data as yesterday

### ISSUE THREAD

**Issue by mathematics12** [CSSEGISandData/COVID-19#2759]

**Comment by CSSEGISandData** [comment]
@mathematics12 I believe you mean the data on the dashboard is stale, correct?  We were able to resolve this a few minutes ago and the change will propagate to the UI hopefully in the next 10-15 minutes.

**Comment by CSSEGISandData** [comment]
![image](https://user-images.githubusercontent.com/60674295/85769322-e0984e80-b6e7-11ea-9a39-9b9a8f0bc35c.png)
I'm going to close because based on the description I believe this is resolved
