### ISSUE TITLE
Data analysis topic: Does a country's death rate correlate with their diet?

### ISSUE THREAD

**Issue by rahmatiangit** [CSSEGISandData/COVID-19#2760]
Here is my take using Johns Hopkins data & Wikipedia, that a plant-based diet lowers the chance of death from Covid_19.

https://www.aiprophet.app/vegan

**Comment by traut21** [comment]
Of course it does. Not breathing helps as well. 

"% of death" appears to be a most precise and helpful number ... not ...  - do you understand how it is computed?

BTW, where's India on this chart?

**Comment by rahmatiangit** [comment]
- breathing -- ???
- % of death from covid-19 -- is reported death / reported infections * 100
- India -- no vegan data is published by Wikipedia, they are mostly vegetarian and love dairy

btw, when I repeated the t-test with vegetarians only from the same countries, the t-test failed, meaning no relation between %vegetarians and %death

Thanks for your questionas
