### ISSUE TITLE
New Jersey Probable Deaths - June 25th

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#2763]
NJ began reporting probable deaths today and the record for the 25th will reflect these 1854 deaths not previously reported.  Additional information can be found in the [transcript](https://nj.gov/governor/news/news/562020/approved/20200625a.shtml) of the state's June 25th coronavirus briefing.

**Comment by NaKo91** [comment]
As every probable death logically is preceded by a probable case, did you also add that to the NJ's total cases?

**Comment by jtene001** [comment]
Is it appropriate to assign nearly 2000 deaths to a date that they are clearly not attributable to? Not to mention the fact that it renders data visualization nearly useless - especially with respect to comparative plots.

**Comment by lojic** [comment]
It's utterly ridiculous to assign all these new deaths to a single day. Pro-rate them over the last N days.

**Comment by jtene001** [comment]
This is an extremely important issue that needs to be resolved. I would anticipate that many more jurisdictions will add probable deaths in the future. Data is supposed to convey information. Assigning these deaths arbitrarily to the date of the decision to report undermines the informativeness of the data.

**Comment by NaKo91** [comment]
Here's how Worldometers usually handles such issues:
"We have allocated the additional deaths (and an equivalent number of probable cases as every probable death is the outcome of a probable case) over New Jersey's historical time series proportionally, based on the existing daily new death percentage increases."

**Comment by victorlin** [comment]
This is an artifact of data reporting and reminds us that there is a lot of context lost when aggregating reports to a few numbers every day.

A similar issue on a larger scale is when China retrospectively reported 13,332 _clinically confirmed_ cases on Feb 13, 2020. [[source]]

Distributing the numbers across history might seem reasonable, but it adds another layer of encryption over the original data. If anything, there should be annotations in the summary making note of any data reporting anomalies. Then, it would be up to consumers to take note of the differences and adjust accordingly.

[source]: https://www.who.int/news-room/detail/13-02-2020-remarks-by-dr-michael-ryan-executive-director-who-health-emergencies-programme-at-media-briefing-on-covid-19-on-13-february-2020

**Comment by CSSEGISandData** [comment]
Hello all

We have spoken with the New Jersey Department of Health. There will be a release of the dates for these probable deaths in the next few weeks and we will properly distribute the cases when the data is available. 

In the interim, we recommend you apply your own smoothing algorithms if they are necessary for your modeling efforts. We do not believe that it is appropriate to make a sweeping decision as to the most pertinent method for smoothing the data.

CSSE team

**Comment by DavidAWest** [comment]
19 days ago, the NJ DoH told you that they would release dates for the probable deaths and you indicated that you would distribute them properly.  This does not appear to have been done.

Is there at least a date range during which these deaths occurred?

**Comment by CSSEGISandData** [comment]
Hello @DavidAWest 

Apologies for not seeing this sooner. They NJ DOH is waiting for internal approval to publish the probable death curve. We do not have a date range. We are tracking this very closely.

**Comment by CSSEGISandData** [comment]
Hello all,

Thank you for your patience. The time series has been updated and the changes should be reflected on the dashboard in the near future.
