### ISSUE TITLE
States potentially abusing/manupilating records

### ISSUE THREAD

**Issue by ladris** [CSSEGISandData/COVID-19#2764]
Came across an article about Florida:

[https://www.theguardian.com/us-news/2020/jun/26/florida-governor-ron-desantis-republican-coronavirus](url)

TL;DR for article, Florida is **alleged** (take with a grain of salt) to have ordered their medical personnel to alter reportings or remove records to bring them in line with demonstrating a decrease over time to emulate them having peaked and being on a downward trend for daily new cases/overall cases.

What kind of mechanism is in place for data sourcing that protects the current known records if the sources are indeed being ordered to manipulate their data? Obviously they can't modify the data stored here, but what about sourcing data before it reaches here?

**Comment by rahmatiangit** [comment]
Manipulating data is a bad short term solution to show a decrease over time.   People may risk more - as they see the downward infection numbers - causing the real (suppressed) number of infections to go even higher and higher exponentially.

Not sure if there are any protection mechanism in place - but COVID-19 is touching too many numbers, testing labs, sick leaves/employers, insurance, hospitals, funeral services,..   all these numbers are in some kind of correlation.

If a state has to fake the numbers , it is a much better strategy to show 2x the real numbers to cause people to be on the defensive side :) but it probably wastes a lot of resources..

**Comment by ladris** [comment]
Part of it is that we have a national holiday approaching and they want to increase tourism for it, so they need the bad numbers to disappear.

**Comment by brazirl** [comment]
First, don't believe everything you read in the Guardian. Second, in order for the governor to manipulate data, he would have to go through the state's administrative bureaucracy where surely somebody would make a stink about it. What's happened in my state (PA) is that the health department has re-categorized some data to align it with the CDC definitions, not because the governor ordered it.

**Comment by ladris** [comment]
Right, which is why I bolded and annotated the allegedly. It was less concern about whether or not the claim was true, and more about data integrity since something as heinous as manipulating data for profit hadn't originally crossed my mind as a factor to have to consider.

Also, I wouldn't so much say it can't be done or ordered, firing and threatening funding is a powerful weapon, but instead I would say it couldn't be done without a whistleblower somewhere popping up post fact.
