### ISSUE TITLE
@CSSEGISandData At this time the data has not changed, only the record numbers !?!

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#2767]
@CSSEGISandData At this time the data has not changed, only the record numbers !?!
Iowa is now scattered between 6 - 3062 and West Virginia is now on rec 2810 and Antigua on 3612

When filtering on 2020-06-24 you get all the 102 records, with a Last_Date that are wrong.

When checking the update you can see that for 33 Iowa records the Confirmed is changed, not the Last_Date.

_Originally posted by @bobromeo in https://github.com/CSSEGISandData/COVID-19/issues/2756#issuecomment-650111792_

**Comment by mathematics12** [comment]
I don't see Iowa data...it is not there
