### ISSUE TITLE
Query to this table broken

### ISSUE THREAD

**Issue by brazirl** [CSSEGISandData/COVID-19#2774]
Today, my query to the table "time_series_covid19_confirmed_global.csv" is broken.  All that is returned is "Adjusting due to issue with probable cases. Please see data modification records for explanation." Any help?

**Comment by CSSEGISandData** [comment]
Hello

How are you pulling the query? Your query is only returning the extended description of the most recent commit.

**Comment by brazirl** [comment]
It's working today. Thanks.
