### ISSUE TITLE
Texas cases not updated

### ISSUE THREAD

**Issue by courtneycnn** [CSSEGISandData/COVID-19#2775]
Hi, the numbers for Texas have not properly updated - showing just over 4,000 cases yesterday when in reality there were 5,357. Can we please get this updated? https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83

**Comment by CSSEGISandData** [comment]
@courtneycnn – thank you for reaching out.  The thing to know is that our reporting does not exactly match the reporting from the state's health department.  Our reporting is based on a composition of both the state's data, as well as the data from some of the counties that tend to lead the state in update time (e.g. Bexar).  This leads to differences in the quantity and magnitude of increases over time.  For example, on the 22nd, we reported a jump of 4846 cases vs. the state's reporting of 3280 new cases (driven primarily by our data being ahead on Harris County), whereas on the 28th we reported a jump of 4258 new cases vs. 5357 cases from the state (driven by the Harris County data coming generally into alignment over the course of the week).  However, if you look over the whole period from the 21st through the 28th you will see that we reported an increase of 37208 cases vs. 37122 in the state's data alone.  So it's fundamentally an issue of data distribution and alignment over time.
