### ISSUE TITLE
US Confirmed count on JH Dashboard doesn't match the sum of state level data in this CSV

### ISSUE THREAD

**Issue by instantaphex** [CSSEGISandData/COVID-19#2778]
How is the dashboard getting the US confirmed count?  I tried adding up all the state numbers from the state level CSV in this repo and it doesn't add up to what I see on https://coronavirus.jhu.edu/map.html.  Is there something I'm missing?

**Comment by CSSEGISandData** [comment]
@instantaphex The data in this csv is a daily snapshot, where the data on the dashboard itself is generally updated hourly.
