### ISSUE TITLE
Delay in correct June 29 Daily

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#2783]
The initial daily product generation at 0605 GMT (7634e51) and it's replacement at 0610 (fcba3721) had to be regenerated due to upstream errors.  The current version tagged at 0821 GMT (cc0382ad) resolves the issues and should be consistent.  Apologies for the delay.

**Comment by wpoust** [comment]
In the [csse_covid_19_daily_reports_us/06-29-2020.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/06-29-2020.csv) file, the FIPS column was entered as a decimal.  

Previously, it has been an integer.

**Comment by fcenedes** [comment]
Hello in 06-28-2020.csv, the active column is now a decimal/float rather than an integer.

**Comment by CSSEGISandData** [comment]
@wpoust @fcenedes Thank you both.  Corrected in latest (41b5a101).
