### ISSUE TITLE
June 29. New York city same data as yesterday

### ISSUE THREAD

**Issue by runrun12** [CSSEGISandData/COVID-19#2785]
New York City has the same data as yesterday and also the Last_Update file is not updated.

**Comment by Marcbrig** [comment]
Is this an issue?  I'm seeing different data for NY today vs yesterday.  393304 today vs. 392539 yesterday.

**Comment by bobromeo** [comment]
It is a small issue, but should be corrected, so one doesn't have to guess.

**Comment by runrun12** [comment]
I am not talking about NY. I am talking about NY City. The data is the same as yesterday

**Comment by Marcbrig** [comment]
Ah, ok.  I was looking at NY as an aggregate.  thanks for the clarification.

**Comment by wellsangels** [comment]
It looks like NYC data will be [updated the afternoon of 6/30](https://www1.nyc.gov/site/doh/covid/covid-19-data.page)

**Monday Data to Be Released on Tuesday**

The data release for Monday, June 29 will be included in the Tuesday, June 30 posting. Please check back on this page on Tuesday afternoon for the data from those two days.
