### ISSUE TITLE
Data missing on 24 June

### ISSUE THREAD

**Issue by sammy-faisal** [CSSEGISandData/COVID-19#2787]
Why is there no data for most countries on 24 June? will this be corrected?

**Comment by CSSEGISandData** [comment]
@sammy-faisal Greetings.  Could you provide some additional details on what you're seeing?

**Comment by sammy-faisal** [comment]
Sorry for not being clear, there seems to be an issue with the data for most countries in 24 June file, as a random snapshot, in Slovakia for example the reported Confirmed cases in the file are 1607, while the correct number is around 23, Slovenia is showing that the confirmed cases are  1541 while the correct number is around 6 and so on.
![Screen Shot 2020-07-01 at 1 10 28 PM](https://user-images.githubusercontent.com/63261119/86233392-00bf8600-bb9e-11ea-8f07-c68bf9746b5a.png)
