### ISSUE TITLE
What is your source of data for North Carolina cases and deaths?

### ISSUE THREAD

**Issue by lojic** [CSSEGISandData/COVID-19#2788]
I don't see a data source listed for North Carolina counties for cases and deaths. Where are you getting the data for this?

**Comment by CSSEGISandData** [comment]
@lojic It's a little buried.  From the README:
North Carolina City of Greenville GIS: https://www.arcgis.com/apps/opsdashboard/index.html#/7aeac695cafa4065ba1505b1cfa72747

**Comment by lojic** [comment]
I did notice that link, but since it said, "City of Greenville", I assumed it was for the City of Greenville i.e. just one locality. It does seem to have complete data, but in a rather inconvenient format. Are you scraping the page, or do you have a more direct data feed?
