### ISSUE TITLE
A reference for "the official designations used by the U.S. Department of State"?

### ISSUE THREAD

**Issue by HallidayDW** [CSSEGISandData/COVID-19#2791]
I don't see where y'all have provided any sort of reference for "the official designations used by the U.S. Department of State".

What document(s) are y'all referencing for this "official designations used by the U.S. Department of State"?

**Comment by ladris** [comment]
i would have to imagine [https://www.state.gov/independent-states-in-the-world](url)

**Comment by HallidayDW** [comment]
While I appreciate the link, @ ladris, I’m not so sure that webpage quite qualifies as “official designations used by the U.S. Department of State”.

Besides, if that is what JHU CSSE are referring to, they are not in compliance with those designations, in a number of instances!

**Comment by ladris** [comment]
That might be because it was a shorthand list in and of itself that follows https://nsgreg.nga.mil/genc/discovery

**Comment by HallidayDW** [comment]
@ladris:

Still, «if that is what JHU CSSE are referring to, they are not in compliance with those designations, in a number of instances!»
