### ISSUE TITLE
Should be 1 extra index to house global sums

### ISSUE THREAD

**Issue by IWasBorg** [CSSEGISandData/COVID-19#2795]
Of all global time series CSVs, there is none that displays the sum of all countries/region into a single global representative. Should JHU include 1 extra index referred to as "World" to sum them all? If not, how to sum them all? It's easy to sum Afghanistan to Zimbabwe, but I don't know whether or not to sum outlying areas after Zimbabwe too

Thanks

**Comment by HallidayDW** [comment]
@IWasBorg:

I have been summing over all rows, in the Global Time Series, for quite a while, and obtain compatible results to multiple sources.

From what I've seen, JHU seems to be doing an admirable job of avoiding multiple counting, within the Daily Reports and Time Series files.

Adding a "World", "to sum them all", or other sub-totals, would break this!

(I have been doing my own sums, for various subsets of the data, for quite some time.)

However, there _are_ discrepancies between the files.

These discrepancies, on the other hand, appear to be reasonably consistent with the asynchronous nature of the data reporting process: so, a little difference in reporting times can lead to small discrepancies in reported values.
