### ISSUE TITLE
Discrepancy for Greenville, SC

### ISSUE THREAD

**Issue by joshmiller83** [CSSEGISandData/COVID-19#2797]
If you chart the data in Greenville SC, the data shows a big gap (no new cases) between June 2 and June 7th.

![image](https://user-images.githubusercontent.com/1440242/86273228-eab1c580-bb9d-11ea-9c18-28a6c434a804.png)

The data in question is here:

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

The line that begins with "84045045,US,USA,840,45045.0,Greenville,South Carolina,US,34.89502264,-82.37295012,"Greenville, South Carolina,"

Date | Number in CSV | New Cases | Reported New Cases | Reference
-- | -- | -- | -- | --
6/2/20 | 1751 | 61 | 65 | https://www.dhec.sc.gov/news-releases/south-carolina-announces-latest-covid-19-update-june-2-2020
6/3/20 | 1751 | 0 | 51 | https://www.dhec.sc.gov/news-releases/south-carolinians-reminded-take-actions-limit-spread-covid-19-latest-covid-19-update
6/4/20 | 1751 | 0 | 56 | https://www.dhec.sc.gov/news-releases/south-carolina-announces-latest-covid-19-update-june-4-2020
6/5/20 | 1934 | 183 | 77 | https://www.dhec.sc.gov/news-releases/south-carolina-announces-latest-covid-19-update-june-5-2020
6/6/20 | 1934 | 0 | 80 | https://www.dhec.sc.gov/news-releases/south-carolina-announces-latest-covid-19-update-june-6-2020
6/7/20 | 2060 | 126 | 57 | https://www.dhec.sc.gov/news-releases/south-carolina-announces-latest-covid-19-update-june-7-2020
  |   |   |   |  
  | subtotal | 370 | 386 |  

There's a discrepancy of 16 cases, which is may be fixed later on in the data. But more importantly, in my opinion, is the clear "skipping" of new cases.

I've hand edited the csv line to include the referenced data (shown above) in the following line:

```
84045045,US,USA,840,45045,Greenville,South Carolina,US,34.89502264,-82.37295012,"Greenville, South Carolina, US",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,7,12,17,19,31,39,50,50,51,57,71,88,106,129,154,174,183,186,204,214,214,254,308,325,339,346,373,400,436,447,486,492,498,498,536,558,557,564,609,649,661,689,722,730,749,757,788,796,803,835,869,912,933,946,971,981,996,1021,1058,1095,1116,1145,1155,1180,1200,1231,1286,1300,1344,1364,1382,1461,1469,1619,1690,1755,1806,1862,1939,2019,2076,2175,2222,2371,2492,2624,2779,2920,3011,3072,3143,3306,3413,3536,3670,3768,3822,4072,4198,4391,4546,4741,4895,5009
```

**Comment by CSSEGISandData** [comment]
Thanks @joshmiller83, I really appreciate your thorough analysis.  Verified and corrections should be merged in.

**Comment by joshmiller83** [comment]
Wow! Same day fixes??! 

This is now reflected in my data set (which is powered by a different service that consumes your data set). Thank you!

![image](https://user-images.githubusercontent.com/1440242/86374117-33c35180-bc52-11ea-95ef-4dfad3a65c1c.png)
