### ISSUE TITLE
Data Discrepancy on 24 June

### ISSUE THREAD

**Issue by sammy-faisal** [CSSEGISandData/COVID-19#2806]
There seems to be an issue with the data for most countries in 24 June file, as a random snapshot, in Slovakia for example the reported Confirmed cases in the file are 1607, while the correct number is around 23, Slovenia is showing that the confirmed cases are 1541 while the correct number is around 6 and so on.

![Screen Shot 2020-07-01 at 1 10 28 PM](https://user-images.githubusercontent.com/63261119/86348216-07b2cb00-bc68-11ea-879f-b14ae859c40a.png)

**Comment by CSSEGISandData** [comment]
@sammy-faisal Our numbers are in line with both the WHO and ECDC reporting around the same time.
