### ISSUE TITLE
Missouri data for most counties has been missing for days?

### ISSUE THREAD

**Issue by ccooper444** [CSSEGISandData/COVID-19#2807]
Why is Missouri data not feeding through anymore?  There are only updates for a small few counties in the past 5 days or so.

**Comment by CSSEGISandData** [comment]
@ccooper444 working issue.  Will post update.

**Comment by runrun12** [comment]
When will be updated? Thanks

**Comment by CSSEGISandData** [comment]
@runrun12 just merged
