### ISSUE TITLE
The wrong data displayed at Apr06 about Taiwan

### ISSUE THREAD

**Issue by SeigfriedHung** [CSSEGISandData/COVID-19#2812]
Dear Sir,

I may find wrong data display on COVID-19 map from https://covid-19.nchc.org.tw/. 
And the website shows that the data repository is from here. So I let this issue here.

I find a abnormal rise up data on the following picture. The data indicate that Taiwan have "Active: 333496, Confirmed:267215, Recovered:19815, Deaths: 14138" at Apr, 6. I check these data of Apr, 5 and Apr, 7. there are just about hundreds or less.
It isn't reasonable about the abnormal rise up data.

Apr, 6
![COVID19_Map_Taiwan_Apr6](https://user-images.githubusercontent.com/67768401/86425451-d265b600-bd17-11ea-9bbc-a40fa22a1d6f.JPG)

Apr, 5
![COVID19_Map_Taiwan_Apr5](https://user-images.githubusercontent.com/67768401/86425461-d7c30080-bd17-11ea-9bdf-61179b0a905b.JPG)

Apr, 7
![COVID19_Map_Taiwan_Apr7](https://user-images.githubusercontent.com/67768401/86425483-e4475900-bd17-11ea-82e3-fe76b2567d8d.JPG)

when I find these data of Apr, 6 in the another web (https://systems.jhu.edu/, JHU CSSE) as shown as follow,
![JHU_CSSE_COVID19_Map_Taiwan](https://user-images.githubusercontent.com/67768401/86425492-e90c0d00-bd17-11ea-99be-e25eddaf8d9b.JPG)

It's seems correct. 

If someone can fix this or transfer to whom can help this, I'll be appreciated.

Thanks all your effort for against COVID-19.

Thanks in advance

Seigfried Hung

**Comment by SeigfriedHung** [comment]
I just wrote a letter to someone who responsible for the project about the website.(https://covid-19.nchc.org.tw/)
Wish they can fix this issue, thank you.

**Comment by CSSEGISandData** [comment]
@SeigfriedHung I'm going to close this issue since it appears to be a problem with a website using the data rather than with the data itself.  Thank you.
