### ISSUE TITLE
United Kingdom new cases July 2, 2020

### ISSUE THREAD

**Issue by MaximNN** [CSSEGISandData/COVID-19#2813]
UK confirmed cases for July 2 are lower than cases for July 1. This is a mistake.

**Comment by vk4tdi** [comment]
No, not wrong. The UK has changed its counting method so each person that tests positive is only counted once. Details on the UK Gov website: https://coronavirus.data.gov.uk/#category=nations&map=case

> The methodology for reporting positive cases changed on 2 July 2020 to remove duplicates within and across pillars 1 and 2, to ensure that a person who tests positive is only counted once. Due to this change, and a revision of historical data in pillar 1, the cumulative total for positive cases is 30,302 lower than if you added the daily figure to yesterday’s total.
> 
> Numbers of lab-confirmed positive cases throughout this website now include those identified by testing in all settings (pillars 1 and 2).

Please update the UK historical data based on the new method. WorldOMeter has new data available.
https://www.worldometers.info/coronavirus/country/uk/

**Comment by MaximNN** [comment]
> No, not wrong. The UK has changed its counting method so each person that tests positive is only counted once. Details on the UK Gov website: https://coronavirus.data.gov.uk/#category=nations&map=case
> 
> > The methodology for reporting positive cases changed on 2 July 2020 to remove duplicates within and across pillars 1 and 2, to ensure that a person who tests positive is only counted once. Due to this change, and a revision of historical data in pillar 1, the cumulative total for positive cases is 30,302 lower than if you added the daily figure to yesterday’s total.
> > Numbers of lab-confirmed positive cases throughout this website now include those identified by testing in all settings (pillars 1 and 2).
> 
> Please update the UK historical data based on the new method. WorldOMeter has new data available.
> https://www.worldometers.info/coronavirus/country/uk/

Thanks a lot, vk4tdi! Should you the time series be updated to aling methodological approach across time periods? Otherwise data before the July 2 is misleading, i.e. includes double counting.

**Comment by vk4tdi** [comment]
> Should you the time series be updated to aling methodological approach across time periods?
Yes, I think it would be best if the data team at JHU did update the historic data, since it looks to be made available. 
They don't have a lot of option when a country suddenly "finds" cases or deaths and adds them, but that is not the case here.

**Comment by MaximNN** [comment]
Exactly! Specifically, I am calculating "daily new cases" by substracting cumulative cases for July 1 from cum. cases for July 2 - and I get negative result...

**Comment by CSSEGISandData** [comment]
Hello

We are aware of the issue and working on a fix.

**Comment by lorint** [comment]
Looks like this update made it into a025f279bbf93da0c50cff09c8b8ad9b831c0305.  Thank you, @CSSEGISandData!
