### ISSUE TITLE
Ohio & Illinois daily report data not updated for 07-02-2020.csv

### ISSUE THREAD

**Issue by wpoust** [CSSEGISandData/COVID-19#2815]
The daily report data, [07-02-2020.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/07-02-2020.csv), shows the same Confirmed, Deaths, and PeopleTested for Ohio and Illinois as the previous day.

**Comment by CSSEGISandData** [comment]
@wpoust Unfortunately, as of now (7/3 0832 EDT), the data on the Ohio and Illinois Department of Public Health reporting end points has not been updated since the 1st.  Will update if possible.
