### ISSUE TITLE
JHU Canada case totals 1,871 higher than Government of Canada totals

### ISSUE THREAD

**Issue by glarose13** [CSSEGISandData/COVID-19#2817]
[Government of Canada COVID19 Tracking ](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html#a1)
as of July 2:
JHU Canada total: 106,643
Govt of Canada:    104,772
Diff 1,871

On April 13, 2020, JHU numbers equaled Govt of Canada numbers.

**Comment by ssoftcheck** [comment]
honestly they will probably never correct this. I am going to try to make a correct version of the data this week. I will send them a pr but who knows what will happen.

**Comment by CSSEGISandData** [comment]
Hello

Our case total is higher as we source directly from the provinces, which are more real-time than that reported by the national government.

CSSE

**Comment by ssoftcheck** [comment]
how is it that [Ontario is reporting 35,948](https://www.publichealthontario.ca/en/data-and-analysis/infectious-disease/covid-19-data-surveillance/covid-19-data-tool)
![image](https://user-images.githubusercontent.com/12905725/86659687-0d861480-bfb8-11ea-8680-ad67f4b2cf57.png)
and you are reporting 37,775?

Or [Alberta reports 8,389](https://www.alberta.ca/stats/covid-19-alberta-statistics.htm)
![image](https://user-images.githubusercontent.com/12905725/86660560-d7956000-bfb8-11ea-9c1a-b872a11376ca.png)
and you report 8,259?

Recent QC, BC, and SK look correct. Without checking all, it seems the big discrepancy is Ontario.

**Comment by glarose13** [comment]
Public Health Agency of Canada (PHAC) compiles the numbers from the provinces for reporting purposes.  While the provinces publish their cases counts on a daily schedule (for example Ontario publishes every day at 10:30am EDT), PHAC sums the provincial numbers and publishes at 7:00pm EDT on [PHAC site](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html#a1). On some days, there may be a lag for BC and AB case counts.  I have not witnessed this myself since mid-March. We appreciate the incredible work JHU has done to provide detailed case counts from around the world.

**Comment by ssoftcheck** [comment]
JIC anyone comes upon this issue, PHAC now has data that updates at 7pm, which is not as real-time but it is correct
