### ISSUE TITLE
United Kingdom Case Discrepancy

### ISSUE THREAD

**Issue by yandax** [CSSEGISandData/COVID-19#2823]
Between 2020-07-01 and 2020-07-02, the number of confirmed cases in the United Kingdom (sum of all entries with Country_Region = "United Kingdom") dropped from 314,992 to 285,268. Is there some explanation for this sudden drop in cases?

Thanks

**Comment by Pinpin-u1111** [comment]
They had an "unknown" prrovince_state with 116,237 cases on July, the 1st that counted no more cases on July, the 2nd and only about 83,000 haven been re-attrributed to the  province_state "England". I don't  know why

**Comment by CSSEGISandData** [comment]
@yandax @Pinpin-u1111 Previous discussion was here: #2813.  Summary was change in reporting by the UK.  We have revised our reporting in line with https://coronavirus.data.gov.uk/#category=nations&map=rate.

![image](https://user-images.githubusercontent.com/60674295/86518088-732da180-bdfc-11ea-854d-bf7d1cded68b.png)
