### ISSUE TITLE
07-03-2020.csv (daily_reports): 2 records with Last_date 2020-07-03

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#2824]
Records 2664 (Utah) + 3798 (Chile)

**Comment by CSSEGISandData** [comment]
@bobromeo This is not unexpected behavior.  It is an artifact of data being held back as we investigate reporting.

**Comment by bobromeo** [comment]
@CSSEGISandData is the file updated after investigation ?
