### ISSUE TITLE
NSW Australian numbers exceed health department updates

### ISSUE THREAD

**Issue by blisx264** [CSSEGISandData/COVID-19#2830]
https://www.health.nsw.gov.au/Infectious/covid-19/Pages/recent-case-updates.aspx

Current state confirmed cases = 3230 
Data jumped from 3211 to 3405 on 3rd July...

**Comment by runrun12** [comment]
They take the information for other sources:

https://covidlive.com.au/

**Comment by amacali** [comment]
Hello. Switched to Federal Health department (instead of state).

A total of 189 historic #COVID19Aus cases reported in crew members on board the Ruby Princess have been reclassified as Australian cases and are now included in NSW totals reported by the Commonwealth Department of Health.

Ongoing variance of 189 cases and 189 recoveries

**Comment by blisx264** [comment]
> Hello. Switched to Federal Health department (instead of state).
> 
> A total of 189 historic #COVID19Aus cases reported in crew members on board the Ruby Princess have been reclassified as Australian cases and are now included in NSW totals reported by the Commonwealth Department of Health.
> 
> Ongoing variance of 189 cases and 189 recoveries

Thanks for the "heads up", I'll check again today...

**Comment by blisx264** [comment]
> Hi. I think they take the information from other sources:
> 
> https://covidlive.com.au/

Thanks... Monash are doing a good job :)

**Comment by CSSEGISandData** [comment]
Thanks @amacali

**Comment by blisx264** [comment]
Confirmed : https://www.health.gov.au/news/health-alerts/novel-coronavirus-2019-ncov-health-alert/coronavirus-covid-19-current-situation-and-case-numbers . Tks :)

**Comment by amacali** [comment]
Welcome team. 
I run and manage COVID LIVE, so if you notice any issues with Australian data you're welcome to ping me
