### ISSUE TITLE
The Global Time series don't add up correctly.

### ISSUE THREAD

**Issue by h21k12** [CSSEGISandData/COVID-19#2834]
Hi,

If the Global time series supposed to add up then there can't be less cases one day than the day before, but there are almost 200 days where the cases is less than the day before. Then one of the two days must have wrong data

Here is a link so you can see what I mean [issues](https://issue.bss.design/)

**Comment by CSSEGISandData** [comment]
@h21k12 Thank you for your analysis.  I'm closing this issue as I don't think it should be characterized as the time series not adding up correctly, it is better described as an issue of source reporting modifying over time.  In an ideal world these data series would be monotonic, but in reality measurement errors and other uncertainties introduce noise into the data.  We do our best to verify and correct our data and appreciate analysis such as yours as a part of that process.
