### ISSUE TITLE
MA data did not update on July 1st 

### ISSUE THREAD

**Issue by roxyshuwang** [CSSEGISandData/COVID-19#2835]
Hi there 

Thank you so much for putting together the COVID dataset 
I noticed that there were no updates for MA between Jun 30th and July 1st 

Jun 30th file (https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/06-30-2020.csv)
Jun 1st file (https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/07-01-2020.csv)
Both day have 108882 as total confirmed cases. 

This is different from what is currently show on the JHU web. 
https://coronavirus.jhu.edu/data/state-timeline/new-confirmed-cases/massachusetts/50 

Could we update the data on github as well 

Thank you

**Comment by d76d30dbl** [comment]
Massachusetts celebrated have no new confirmed cases on May 30.   They reported 0.
