### ISSUE TITLE
Number of confirmed cases in Australia for New Soutch Wales and Victoria off for July 3

### ISSUE THREAD

**Issue by mwmenache** [CSSEGISandData/COVID-19#2837]
The number of confirmed cases in Australia for New South Wales and Victoria is off for July 3 in time_series_covid19_confirmed_global.csv.
In this file:
- The number of cases in Victoria is the same on July 2 and July 3, meaning no new confirmed cases on that day 
- The number of cases in New South Wales rose from 3211 to 3405, meainining 194 new confirmed cases on that day
This is illustrated below:
![image](https://user-images.githubusercontent.com/62164091/86682082-8f6f4f80-c043-11ea-928a-96e330047bd6.png)

As a result the trends for these  states look incorrect:
![image](https://user-images.githubusercontent.com/62164091/86682688-29cf9300-c044-11ea-9966-acaf38352634.png)

Moreover the daily number of new cases reported in Australia in July every day was below 10 in NSW and above 50 in Victoria (source: ABC news):
https://www.abc.net.au/news/2020-03-17/coronavirus-cases-data-reveals-how-covid-19-spreads-in-australia/12060704?nw=0#newcases
![image](https://user-images.githubusercontent.com/62164091/86682383-dd845300-c043-11ea-8b35-963e580c7837.png)

Is there anythng in the way the number of conffirmed cases are reported for Australia in time_series_covid19_confirmed_global.csv that explains thse strange numbers?
Can it be corrected?

Respectfully, 

Michael

**Comment by CSSEGISandData** [comment]
@mwmenache My apologies for closing the issues, but this was discussed previously in #2830 and #2832 .  New South Wales was a allocation of cases from the [Ruby Princess to NSW](https://www.theaustralian.com.au/breaking-news/nsw-covid-numbers-spike-after-ruby-princess-crew-reclassified/news-story/422714295b8917d2aa030e3940d205f1).  Victoria is a delay introduced by reporting time variance.

**Comment by mwmenache** [comment]
Thansk! Makes all sense now. Apologies for not having cheked the closed issues before opening mine.
