### ISSUE TITLE
Weber County (Utah) and Morgan County (Utah) missing all case data

### ISSUE THREAD

**Issue by vk4tdi** [CSSEGISandData/COVID-19#2839]
The US case info for Weber County is listed as:
```84049057,US,USA,840,49057.0,Weber,Utah,US,41.27116049,-111.9145117,"Weber,Utah,US",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0```
The Morgan county data is listed as
```84049029,US,USA,840,49029.0,Morgan,Utah,US,41.08830262,-111.5727723,"Morgan, Utah, US",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0```

The county dashboard shows plenty of cases, but it is for the Weber-Morgan health district.
https://weber.maps.arcgis.com/apps/opsdashboard/index.html#/0b436d01339c4bfe91c962bc4e7898c5

The district data at http://www.webermorganhealth.org/coronavirus/ shows Weber and Morgan totals, so it would be great if these could be brought over. I suspect that the other counties with 0 cases ever Utah have a similar problem. My check shows these FIPS have 0 cases at all. 
```49001 49003 49005 49007 49009 49013 49015 49017 49019 49021 49023 49025 49027 49029 49031 49033 49039 49041 49047 49053 49055 49057 80049 90049```
```"Beaver, Utah, US"     "Box Elder, Utah, US"  "Cache, Utah, US"      "Carbon, Utah, US"     "Daggett, Utah, US"    "Duchesne, Utah, US" "Emery, Utah, US"      "Garfield, Utah, US"   "Grand, Utah, US"      "Iron, Utah, US"       "Juab, Utah, US"       "Kane, Utah, US" "Millard, Utah, US"    "Morgan, Utah, US"     "Piute, Utah, US"      "Rich, Utah, US"       "Sanpete, Utah, US"    "Sevier, Utah, US" "Uintah, Utah, US"     "Washington,Utah,US"   "Wayne, Utah, US"      "Weber,Utah,US"        "Out of UT, Utah, US"  "Unassigned, Utah, US"```

**Comment by d76d30dbl** [comment]
This is not a problem.
Utah reports reports some counties thru multi-county health districts. Thus webber and morgan counties are reported in the row  webber-morgan.  There are 6 health districts used for reporting in Utah.
,
Utah is not the only state that uses multi-county proxies for reporting. 

Db

**Comment by vk4tdi** [comment]
> Utah reports reports some counties thru multi-county health districts. Thus webber and morgan counties are reported in the row webber-morgan. There are 6 health districts used for reporting in Utah.

Given that The Weber-Morgan district separates out the cases for each county on their report page, why not report for each? The county, with its FIPS, make comaparison of COVID incidence possible. Or is this not possible because JHU is an aggregator of data and the source doesn't do this?

**Comment by CSSEGISandData** [comment]
Reporting is consistent with the state since changeover to health districts.
