### ISSUE TITLE
Illinois 7-7-20 Deaths Too High

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#2841]
JH total deaths match IL government numbers for 7-6, but are 210 more than the government numbers for 7-7. This makes the JH new death numbers for 7-7  about an order of magnitude more than expected.

https://www.dph.illinois.gov/covid19/covid19-statistics

**Comment by DavidViral** [comment]
I see that the difference is the inclusion of probable deaths in JH numbers.  And I see in the note on the linked website that the probable numbers are updated weekly and were last updated on 7-3.  Yet the numbers are added in 4 days later not 7.  

Are probable numbers included in the historical JH numbers, lumped in weekly or otherwise? What's going on?

https://www.dph.illinois.gov/covid19

**Comment by Ericdmmiller** [comment]
If one were cynical, it could seem like all of these blue states changing their reporting to include probable deaths by lumping them all on the day the reporting changed might be an attempt to deliberately inflate the reporting and make it seem like the current course of the pandemic is worse than it actually is.

**Comment by DavidViral** [comment]
If that were the case they are not doing a very good job of it.  9 out of 10 of the worst Covid states now are states that voted for Trump, while 9 out of 10 of the best states voted for Clinton:  worst and best based on the number of per capita new cases.



    On Wednesday, July 8, 2020, 10:42:16 AM EDT, Ericdmmiller <notifications@github.com> wrote:  
 
 


If one were cynical, it could seem like all of these blue states changing their reporting to include probable deaths by lumping them all on the day the reporting changed might be an attempt to deliberately inflate the reporting and make it seem like the current course of the pandemic is worse than it actually is.

**Comment by CSSEGISandData** [comment]
Hello

@DavidViral please see the README for the folder csse_covid_19_data. Yesterday, we adapted our data collection in a way that captured these probable cases and deaths. We expect to see weekly spikes in cases and deaths if the Illinois Department of Health holds true in releasing probables weekly.

@Ericdmmiller I would point out that whenever possible we backdistribute the probable cases and deaths, thus the inclusion of probables (if backdistributed) should not sufficiently alter any analysis of the acceleration of cases and deaths.
