### ISSUE TITLE
Illinois deaths for 7/7

### ISSUE THREAD

**Issue by catelaine3** [CSSEGISandData/COVID-19#2842]
Illinois Department of Public Health reports 7063 total covid-19 deaths, not 7273

**Comment by CalvinParis** [comment]
Cases seem off as well.

**Comment by CalvinParis** [comment]
Looks like they added a category that they hadn't previously included as their total now matches that of other sources but previously had not. For example they haven't been picking up non-resident deaths in Florida if they suddenly start including  them  it would cause a similar bump.

**Comment by CalvinParis** [comment]
Texas deaths for 7/7 are off as well 2778 vs 2715

**Comment by CSSEGISandData** [comment]
@catelaine3 and @CalvinParis - Illinois has started reporting probable cases and deaths.  We are now including them in our total.  This is consistent with our reporting elsewhere.

![image](https://user-images.githubusercontent.com/60674295/86957288-8310f280-c128-11ea-8da0-166a30166f0b.png)

**Comment by NaKo91** [comment]
@CalvinParis Similar to most other states, Texas' official dashboard lags a day behind the JHU. 
Texas' daily update always provides numbers from the previous day, so the lower death count you're referring to is current to July 6th.
