### ISSUE TITLE
07-08-2020.csv in daily has 7 US State records that should have Admin2 = Unassigned

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#2846]
7 states {Arkansas,DC,Hawaii,Idaho,Iowa,Oklahoma,Utah} have records where Admin2 = Province_state !
==> Arkansas: Confirmed 46.

I think the Admin2 of these records should be changed to Unassigned.
This would be in line with the other Unassigned records of the other states.

**Comment by CSSEGISandData** [comment]
The Admin2 field consists of county names. Arkansas county is a county within the state of Arkansas. Therefore, being in Admin2 as Arkansas. This is true for the other locations stated above. D.C. is a special case where there are no counties within D.C., but we label Admin2 as D.C. We currently report Unassigned locations for the States you have mentioned above.
