### ISSUE TITLE
Time series - drop in the cumulative values 

### ISSUE THREAD

**Issue by RamiKrispin** [CSSEGISandData/COVID-19#285]
I noticed that in some cases there is a drop in the cumulative values of the time series csv files. For example in the [confirmed cases](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv), in Japan, there were 45 confirmed cases on Feb 6th and it dropped to 25 on the next day. 

Are those cases related to a retro update of false-positive cases? or an error?

Thanks!
Rami

**Comment by mbevand** [comment]
IMHO it's an obvious typo. "45" cases in Japan on Feb 6th should read "25"

**Comment by RamiKrispin** [comment]
Thanks, 

Here are a few more cases on the recovery file:

- US (Omaha, NE (From Diamond Princess)) 11 cases drop to 0 on 2020-02-24
- US (Travis, CA (From Diamond Princess)) 5 drop to 0 on 2020-02-24
- Australia (From Diamond Princess) 8 cases drop to 0 on 2020-02-29

Do cases from the Diamond Princess were count from those dates under different regions?

**Comment by JiPiBi** [comment]
I read this comment in the pdf files from the situation report folder in this repositery that can explain these evolutions 

> Location of transmission is classified based on WHO analysis of available official data, and may be subject to reclassification as additional data become available.

**Comment by RamiKrispin** [comment]
Here is another case from March 8 for South Korie [recovered table](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv), drop from 135 to 118

**Comment by CSSEGISandData** [comment]
We have noted this discrepancy in the data and have concluded that these values were reported correctly from our sources. There may be reports that change over time as new requirements in reporting evolve. These values in our data are the result of the changes in reporting.
