### ISSUE TITLE
Alabama hospitalizations

### ISSUE THREAD

**Issue by lmjouhsc** [CSSEGISandData/COVID-19#2853]
Alabama hospitalizations more than doubled between July 10 and 11?

**Comment by CSSEGISandData** [comment]
@lmjouhsc On June 10th Alabama Department of Public Health was able to supplement their cumulative hospitalization data with additional information provided by hospitals.  Up until that time their data reflected case investigations input directly into their surveillance system.  [A full discussion is in the press release from the state.](http://www.alabamapublichealth.gov/news/2020/07/10b.html)
