### ISSUE TITLE
Error in Chile Data, June 16th

### ISSUE THREAD

**Issue by dna33** [CSSEGISandData/COVID-19#2858]
Hi, 

I work at Chile's Ministry of Science and manage the effort to publish official figures from our Health Ministry for Chile in this official repository: https://github.com/MinCiencia/Datos-COVID19 

I'm writing to report an error in the figures you are providing:
- The data from Chile on 17th June 2020 is wrong, the graphic is showing 36.2 k (36.200) daily cases per day .
- Mistake might've happened because that day the government started including cases that were not notified to the sanitary management over the previous weeks, the proper allocation of those cases to dates can be found in Data Product 45 in the mentioned repository.

My e-mail is darancibia@minciencia.gob.cl, in case you require any assistance correcting this error.
Please see attached the pdf of the daily report, here a copy of the table where the correct information lies:

![image](https://user-images.githubusercontent.com/12438811/87330196-32254380-c506-11ea-938a-51f72de68978.png)

And here a picture of the data that is wrong in your repository:

![image](https://user-images.githubusercontent.com/12438811/87330240-49fcc780-c506-11ea-9100-ef1273c69ccf.png)

[Reporte_Covid1920.06.2020.pdf](https://github.com/CSSEGISandData/COVID-19/files/4913837/Reporte_Covid1920.06.2020.pdf)

**Comment by dna33** [comment]
This is related to issue #2722

**Comment by CSSEGISandData** [comment]
@dna33 Thank you!  I will work this issue ASAP.
