### ISSUE TITLE
Lat. Long. coordinates are still outdated in time series data

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#2859]
Daily reports feature the most recent latitude and longitude coordinates according to [JHU's UID_ISO_FIPS_LookUp_Table](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv). In contrast, these same coordinates are outdated in the [time series data](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series). 

In most cases, these differences are minor and do not amount to an error. In some cases, however, the outdated coordinates result in significant inaccuracies. Here are a couple of examples:
1.   Aleutians West, Alaksa 
- The Lookup Table and daily reports, correctly locate Aleutians West at 52.3233, -174.1596. Whereas, the time series data incorrectly suggests 52.72541116, -110.4086433. The latter is located in Alberta, Canada. It appears that this issue dates back to March #1801

2. Mauritania 
- Mauritania is another example. The Lookup Table and daily reports correctly locate Mauritania at 21.0079,-10.9408. The time series data, however, locates Mauritania at 21.0079,10.9408, which places it inside Niger. This issue has also been reported before #2075, #1305, #786.  

It seems related issues have been addressed in the daily reports, but have yet to be fixed in the time series.

**Comment by CSSEGISandData** [comment]
Thanks @Lucas-Czarnecki !
