### ISSUE TITLE
Empty data cells on most recent date

### ISSUE THREAD

**Issue by jtene001** [CSSEGISandData/COVID-19#286]
Up to a couple days ago, all locations had full time series. The last couple days, there have been several locations that do not have data for the last day. I noticed this problem for all three time series sets - confirmed, recovered and deaths.

**Comment by sibblegp** [comment]
Please fix asap.

**Comment by r-lomba** [comment]
More than that, today's CSVs when loaded with pandas result in the last column being of type float64 instead of int64 like all the others. This is causing problems

**Comment by arik-so** [comment]
Today's US cases figures have suddenly dropped.
Cases: 176 -> 46
Recoveries: 8 -> 1
Deaths: 12 -> 0

**Comment by sibblegp** [comment]
The whole dataset is bad. I really hope whoever manages this didn't just publish it and go home for the weekend :(

**Comment by sibblegp** [comment]
Can someone a little better at CSV's than I create a working branch?

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238

**Comment by FAGundum** [comment]
Same here, I saw Boston, New York and Queens County showing empty field for 3/6.

As people mentioned above, this cause issue loading into pandas, but should be resolved once you copy yesterday's value over.

**Comment by jqnatividad** [comment]
For folks doing analysis with pandas, etc, would be interested in some feedback to see if this "enriched" version of the data helps with your analysis.

#283 

I "enriched" it by:
* consolidating all incident types into one table
* deriving the daily incident count (as the current values are running totals)
* enriching the geographic data a bit by geocoding given the lat/long.

**Comment by jtene001** [comment]
Agree with FAGundum's comment above. The three missing venues are Boston, NYC and Queens (rows 68, 135 and 172). Missing date is today - 3/6. The data is missing from all three files.

To get my rmarkdown document to run, I just filled the missing data with the previous day's tally.

**Comment by CSSEGISandData** [comment]
Sorry for the inconvenience. We have have updated the time series table to remove these empty cells.
