### ISSUE TITLE
United Kingdom Deaths figure discrepancy with quoted source (UK govt)

### ISSUE THREAD

**Issue by cuisquare** [CSSEGISandData/COVID-19#2861]
Source quoted for UK data is: https://coronavirus.data.gov.uk/#category=nations&map=rate
Downloadable version from that page: https://coronavirus.data.gov.uk/downloads/csv/coronavirus-deaths_latest.csv

When comparing to JH data, there is a discrepancy in quite a few places, for instance 01/06 where additional deaths is 556 JH side, but only 111 for the data directly obtained from the UK govt website. Another noticeable difference in additional deaths is 24/05 where JH says 118 while UK govt says 441 .

Is it possible that JH got out of sync in the updates, or is there another reason for this discrepancy ? 

In case that helps I put below the full list of discrepancies, on total deaths and deaths increase.

Date | Deaths_GOV | Deaths_JH | Diff_Deaths | Inc_Deaths_GOV | Inc_Deaths_JH | Diff_Inc_Deaths
-- | -- | -- | -- | -- | -- | --
06/03/20 | 1 | 1 | 0 | 1 | 1 | 0
07/03/20 | 2 | 2 | 0 | 1 | 1 | 0
08/03/20 | 2 | 2 | 0 | 0 | 0 | 0
09/03/20 | 3 | 3 | 0 | 1 | 1 | 0
10/03/20 | 7 | 7 | 0 | 4 | 4 | 0
11/03/20 | 7 | 7 | 0 | 0 | 0 | 0
12/03/20 | 9 | 9 | 0 | 2 | 2 | 0
13/03/20 | 10 | 10 | 0 | 1 | 1 | 0
14/03/20 | 28 | 28 | 0 | 18 | 18 | 0
15/03/20 | 43 | 43 | 0 | 15 | 15 | 0
16/03/20 | 65 | 65 | 0 | 22 | 22 | 0
17/03/20 | 81 | 81 | 0 | 16 | 16 | 0
18/03/20 | 115 | 115 | 0 | 34 | 34 | 0
19/03/20 | 158 | 158 | 0 | 43 | 43 | 0
20/03/20 | 194 | 194 | 0 | 36 | 36 | 0
21/03/20 | 250 | 250 | 0 | 56 | 56 | 0
22/03/20 | 285 | 285 | 0 | 35 | 35 | 0
23/03/20 | 359 | 359 | 0 | 74 | 74 | 0
24/03/20 | 508 | 508 | 0 | 149 | 149 | 0
25/03/20 | 695 | 694 | -1 | 187 | 186 | -1
26/03/20 | 878 | 877 | -1 | 183 | 183 | 0
27/03/20 | 1162 | 1161 | -1 | 284 | 284 | 0
28/03/20 | 1456 | 1455 | -1 | 294 | 294 | 0
29/03/20 | 1670 | 1669 | -1 | 214 | 214 | 0
30/03/20 | 2044 | 2043 | -1 | 374 | 374 | 0
31/03/20 | 2426 | 2425 | -1 | 382 | 382 | 0
01/04/20 | 3096 | 3095 | -1 | 670 | 670 | 0
02/04/20 | 3748 | 3747 | -1 | 652 | 652 | 0
03/04/20 | 4462 | 4461 | -1 | 714 | 714 | 0
04/04/20 | 5222 | 5221 | -1 | 760 | 760 | 0
05/04/20 | 5866 | 5865 | -1 | 644 | 644 | 0
06/04/20 | 6434 | 6433 | -1 | 568 | 568 | 0
07/04/20 | 7472 | 7471 | -1 | 1038 | 1038 | 0
08/04/20 | 8506 | 8505 | -1 | 1034 | 1034 | 0
09/04/20 | 9616 | 9608 | -8 | 1110 | 1103 | -7
10/04/20 | 10768 | 10760 | -8 | 1152 | 1152 | 0
11/04/20 | 11608 | 11599 | -9 | 840 | 839 | -1
12/04/20 | 12294 | 12285 | -9 | 686 | 686 | 0
13/04/20 | 13038 | 13029 | -9 | 744 | 744 | 0
14/04/20 | 14085 | 14073 | -12 | 1047 | 1044 | -3
15/04/20 | 14927 | 14915 | -12 | 842 | 842 | 0
16/04/20 | 15956 | 15944 | -12 | 1029 | 1029 | 0
17/04/20 | 16892 | 16879 | -13 | 936 | 935 | -1
18/04/20 | 18007 | 17994 | -13 | 1115 | 1115 | 0
19/04/20 | 18505 | 18492 | -13 | 498 | 498 | 0
20/04/20 | 19064 | 19051 | -13 | 559 | 559 | 0
21/04/20 | 20237 | 20223 | -14 | 1173 | 1172 | -1
22/04/20 | 21074 | 21060 | -14 | 837 | 837 | 0
23/04/20 | 21801 | 21787 | -14 | 727 | 727 | 0
24/04/20 | 22807 | 22792 | -15 | 1006 | 1005 | -1
25/04/20 | 23650 | 23635 | -15 | 843 | 843 | 0
26/04/20 | 24070 | 24055 | -15 | 420 | 420 | 0
27/04/20 | 24408 | 24393 | -15 | 338 | 338 | 0
28/04/20 | 25319 | 25302 | -17 | 911 | 909 | -2
29/04/20 | 26114 | 26097 | -17 | 795 | 795 | 0
30/04/20 | 26788 | 26771 | -17 | 674 | 674 | 0
01/05/20 | 27528 | 27510 | -18 | 740 | 739 | -1
02/05/20 | 28149 | 28131 | -18 | 621 | 621 | 0
03/05/20 | 28464 | 28446 | -18 | 315 | 315 | 0
04/05/20 | 28752 | 28734 | -18 | 288 | 288 | 0
05/05/20 | 29446 | 29427 | -19 | 694 | 693 | -1
06/05/20 | 30098 | 30076 | -22 | 652 | 649 | -3
07/05/20 | 30638 | 30615 | -23 | 540 | 539 | -1
08/05/20 | 31265 | 31241 | -24 | 627 | 626 | -1
09/05/20 | 31610 | 31587 | -23 | 345 | 346 | 1
10/05/20 | 31879 | 31855 | -24 | 269 | 268 | -1
11/05/20 | 32090 | 32065 | -25 | 211 | 210 | -1
12/05/20 | 32720 | 32692 | -28 | 630 | 627 | -3
13/05/20 | 33216 | 33186 | -30 | 496 | 494 | -2
14/05/20 | 33644 | 33614 | -30 | 428 | 428 | 0
15/05/20 | 34028 | 33998 | -30 | 384 | 384 | 0
16/05/20 | 34508 | 34466 | -42 | 480 | 468 | -12
17/05/20 | 34678 | 34636 | -42 | 170 | 170 | 0
18/05/20 | 34838 | 34796 | -42 | 160 | 160 | 0
19/05/20 | 35386 | 35341 | -45 | 548 | 545 | -3
20/05/20 | 35755 | 35704 | -51 | 369 | 363 | -6
21/05/20 | 36093 | 36042 | -51 | 338 | 338 | 0
22/05/20 | 36451 | 36393 | -58 | 358 | 351 | -7
23/05/20 | 36734 | 36675 | -59 | 283 | 282 | -1
24/05/20 | 37175 | 36793 | -382 | 441 | 118 | -323
25/05/20 | 37297 | 36914 | -383 | 122 | 121 | -1
26/05/20 | 37433 | 37048 | -385 | 136 | 134 | -2
27/05/20 | 37876 | 37460 | -416 | 443 | 412 | -31
28/05/20 | 38292 | 37837 | -455 | 416 | 377 | -39
29/05/20 | 38665 | 38161 | -504 | 373 | 324 | -49
30/05/20 | 38895 | 38376 | -519 | 230 | 215 | -15
31/05/20 | 39010 | 38489 | -521 | 115 | 113 | -2
01/06/20 | 39121 | 39045 | -76 | 111 | 556 | 445
02/06/20 | 39447 | 39369 | -78 | 326 | 324 | -2
03/06/20 | 39812 | 39728 | -84 | 365 | 359 | -6
04/06/20 | 39989 | 39904 | -85 | 177 | 176 | -1
05/06/20 | 40347 | 40261 | -86 | 358 | 357 | -1
06/06/20 | 40554 | 40465 | -89 | 207 | 204 | -3
07/06/20 | 40631 | 40542 | -89 | 77 | 77 | 0
08/06/20 | 40686 | 40597 | -89 | 55 | 55 | 0
09/06/20 | 40975 | 40883 | -92 | 289 | 286 | -3
10/06/20 | 41225 | 41128 | -97 | 250 | 245 | -5
11/06/20 | 41377 | 41279 | -98 | 152 | 151 | -1
12/06/20 | 41581 | 41481 | -100 | 204 | 202 | -2
13/06/20 | 41764 | 41662 | -102 | 183 | 181 | -2
14/06/20 | 41800 | 41698 | -102 | 36 | 36 | 0
15/06/20 | 41838 | 41736 | -102 | 38 | 38 | 0
16/06/20 | 42074 | 41969 | -105 | 236 | 233 | -3
17/06/20 | 42258 | 42153 | -105 | 184 | 184 | 0
18/06/20 | 42395 | 42288 | -107 | 137 | 135 | -2
19/06/20 | 42568 | 42461 | -107 | 173 | 173 | 0
20/06/20 | 42698 | 42589 | -109 | 130 | 128 | -2
21/06/20 | 42741 | 42632 | -109 | 43 | 43 | 0
22/06/20 | 42756 | 42647 | -109 | 15 | 15 | 0
23/06/20 | 42927 | 42927 | 0 | 171 | 280 | 109
24/06/20 | 43081 | 43081 | 0 | 154 | 154 | 0
25/06/20 | 43230 | 43230 | 0 | 149 | 149 | 0
26/06/20 | 43414 | 43414 | 0 | 186 | 184 | -2
27/06/20 | 43514 | 43514 | 0 | 100 | 100 | 0
28/06/20 | 43550 | 43550 | 0 | 36 | 36 | 0
29/06/20 | 43575 | 43575 | 0 | 25 | 25 | 0
30/06/20 | 43730 | 43730 | 0 | 155 | 155 | 0
01/07/20 | 43906 | 43906 | 0 | 176 | 176 | 0
02/07/20 | 43995 | 43995 | 0 | 89 | 89 | 0
03/07/20 | 44131 | 44131 | 0 | 137 | 136 | -1
04/07/20 | 44198 | 44198 | 0 | 67 | 67 | 0
05/07/20 | 44220 | 44220 | 0 | 22 | 22 | 0
06/07/20 | 44236 | 44236 | 0 | 16 | 16 | 0
07/07/20 | 44391 | 44391 | 0 | 155 | 155 | 0
08/07/20 | 44517 | 44517 | 0 | 126 | 126 | 0
09/07/20 | 44602 | 44602 | 0 | 85 | 85 | 0
10/07/20 | 44650 | 44650 | 0 | 48 | 48 | 0
11/07/20 | 44798 | 44798 | 0 | 148 | 148 | 0
12/07/20 | 44819 | 44819 | 0 | 21 | 21 | 0
13/07/20 | 44830 | 44830 | 0 | 11 | 11 | 0

**Comment by cuisquare** [comment]
I see now there some other issues with the UK gov data, in that they provide a value for the deaths increase, but this does not match exactly the deaths column if you calculate it. This does not explain the larger discrepancies, but still worth noting.

**Comment by CSSEGISandData** [comment]
Hello

Thank you for bringing this to our attention. This has occurred previously and is due to historical revisions to the time series data presented on the UK government website. We last made an adjustment on June 3rd - comparing the data you have presented with data downloaded from the UK government website on June 8th, I note differences on multiple dates. We will revise our time series to reflect these official revisions.

Unfortunately there is no straightforward way for us to constantly validate our own data with historical revisions across the world. We appreciate the community's help in identifying these issues.

**Comment by cuisquare** [comment]
Hi, thanks for your reply. 

I just wanted to remark though, that the webpage you quote as a source, has the file which I also linked in my original comment which has the whole time series (the same one exists for cases I believe). As such it would seem that the extraction of up to date data should be possible regardless of it being corrected later on (as you would always get the latest version). 

Actually even better than that, it would provide a more accurate historical record of when the UK data was amended, one of the issue I had trying to make sense of the discrepancy is that the UK website does not offer that kind of historical data, the way one can obtain with your repository.
