### ISSUE TITLE
License of CSSE data?

### ISSUE THREAD

**Issue by mhawas84** [CSSEGISandData/COVID-19#2868]
Hello, what is the license of this data in order to use it in modelling and forecasting the infections numbers as part of scientific research ?
In other words, which license should i use and attach to the generated data, which complies with CSSE and JHU? 
CC BY 4.0 or CC BY NC 3.0 or both work fine?

**Comment by NightDragon1** [comment]
Form a legal point of view they can not easily license the data. Reason: The sources they use have already licenses applied, mostly on country level. so they would need to create a license containing all the other licenses.

BUT, they have Terms of use, which can be found at the end of the text here: https://github.com/CSSEGISandData/COVID-19

**Comment by mhawas84** [comment]
Thank you for replying, well, as I understand from the terms of use, they have constituted the grounds of a certain type of a license that requires attribution, limited scope of usage that includes research, and non-commercial usage, this all without making an integration with raw data licenses on country level. that is very similar or speaks out CC BY's extended notices, that does not give all permissions necessary for intended usage, ex. for usages that require the permission of other parties. Except that they have allowed some usages already.

**Comment by CSSEGISandData** [comment]
Hello @mhawas84 ! We are following CC BY 4.0. New terms of use was just updated yesterday. Thanks!
