### ISSUE TITLE
Honduras Data

### ISSUE THREAD

**Issue by axellpadilla** [CSSEGISandData/COVID-19#2873]
Please use https://www.worldometers.info/coronavirus/ for Honduras and all Central America just checked and they are showing very precise and updated data

**Comment by CSSEGISandData** [comment]
@axellpadilla we had some technical issues through the late evening which delayed the update of the dashboard.  The data in the nightly update is correct - 30036 confirmed cases in Honduras.

**Comment by axellpadilla** [comment]
Perfect, thank you very much.
