### ISSUE TITLE
U.S. change in CDC data collection

### ISSUE THREAD

**Issue by rhaimann** [CSSEGISandData/COVID-19#2875]
The U.S. Department of Health and Human Services (DHHS) has stopped COVID data collection and publication by the Centers for Disease Control (CDC) and taken the task to another part of the DHHS. The database they are using to store the data is no longer public access. Has this or will this affect the Johns Hopkins CSSEGIS team from continuing to collect and publish COVID data from the U.S.?  If so, what can we expect the differences to be in U.S. reported data - age, quality, field definitions, etc.? 

By the way, you are doing an amazing job and are so appreciated by so many U.S. citizens and citizens of countries throughout the world.

**Comment by redcap3000** [comment]
More than likely if the current north american administration has the means this repository will be made private or removed, anyone in possession of it will probably be considered an enemy of the state. Good luck!

**Comment by Jelfff** [comment]
If you go the main JHU GitHub page and scroll down, then  you will see lists of their data sources.  With respect to the state and county counts that JHU is compiling, they do not list the CDC as a data source.

**Comment by CSSEGISandData** [comment]
Hello

Please see the following statement from Johns Hopkins University: https://twitter.com/JohnsHopkins/status/1283792012001468416?s=20
