### ISSUE TITLE
Discrepancy for Dallas County, TX Data

### ISSUE THREAD

**Issue by timothybray** [CSSEGISandData/COVID-19#2877]
We have discovered a discrepancy between the CSSE CSV file and the State of Texas data for Dallas County. It appears that data is mysteriously advanced by a day on occasion. See the short comparison below. As you can see, it appears that the series has been out of sync for several days. The series from 7/12 through 7/15 has been displaced to 7/11 through 7/14, shifting all data by one day and omitting the correct data for 7/11.

<table border=0 cellpadding=0 cellspacing=0 width=321 style='border-collapse:
 collapse;table-layout:fixed;width:241pt'>
 <col width=64 span=2 style='width:48pt'>
 <col width=129 style='mso-width-source:userset;mso-width-alt:4579;width:97pt'>
 <col width=64 style='width:48pt'>
 <tr height=38 style='mso-height-source:userset;height:28.2pt'>
  <td height=38 width=64 style='height:28.2pt;width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td class=xl68 width=129 style='width:97pt'>Texas Department of State Health
  Services</td>
  <td width=64 style='width:48pt'>JHU-CSSE</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>15-Jul</td>
  <td class=xl66 align=right>35,914</td>
  <td class=xl66 align=right>35,914</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>14-Jul</td>
  <td class=xl66 align=right>34,914</td>
  <td class=xl66 align=right>35,914</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>13-Jul</td>
  <td class=xl66 align=right>33,800</td>
  <td class=xl66 align=right>34,914</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>12-Jul</td>
  <td class=xl66 align=right>32,626</td>
  <td class=xl66 align=right>33,800</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>11-Jul</td>
  <td class=xl66 align=right>31,525</td>
  <td class=xl66 align=right>32,626</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>10-Jul</td>
  <td class=xl66 align=right>30,361</td>
  <td class=xl66 align=right>30,361</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>9-Jul</td>
  <td class=xl66 align=right>29,160</td>
  <td class=xl66 align=right>30,361</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>8-Jul</td>
  <td class=xl66 align=right>28,131</td>
  <td class=xl66 align=right>29,160</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>7-Jul</td>
  <td class=xl66 align=right>27,054</td>
  <td class=xl66 align=right>28,131</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>6-Jul</td>
  <td class=xl66 align=right>25,840</td>
  <td class=xl66 align=right>27,054</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>5-Jul</td>
  <td class=xl66 align=right>24,778</td>
  <td class=xl66 align=right>25,840</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>4-Jul</td>
  <td class=xl66 align=right>23,675</td>
  <td class=xl66 align=right>24,778</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>3-Jul</td>
  <td class=xl66 align=right>22,590</td>
  <td class=xl66 align=right>23,675</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>2-Jul</td>
  <td class=xl66 align=right>21,882</td>
  <td class=xl66 align=right>22,590</td>
 </tr>
 <tr height=19 style='height:14.4pt'>
  <td height=19 style='height:14.4pt'></td>
  <td class=xl65 align=right>1-Jul</td>
  <td class=xl66 align=right>21,338</td>
  <td class=xl66 align=right>21,882</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=129 style='width:97pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

Please let us know if this is something we need to address with the Texas Department of State Health Services.

Best,

Dr. Bray

**Comment by CSSEGISandData** [comment]
@timothybray Thank you for bringing this up.  In certain states with large municipal health agencies we have found there can be a delay between reporting at the county level and reporting at the state level.  Dallas is an example of this.  If you look at the county press releases archived here: https://www.dallascounty.org/covid-19/judge-press-releases.php, you'll see that the numbers do indeed shift by about a day between the 2 reporting end points.  Harris County is another example where the reporting at the county tends to lead the reporting at the state.  We have observed this pattern elsewhere; it's a systemic artifact and definitely not an issue with Texas.  That said, I will be doing some work to clean up the time series in line with the county level reporting - there are a few days to update.
