### ISSUE TITLE
Number of confirmed cases on Diamond Princess / Others Dropped? 

### ISSUE THREAD

**Issue by KeeganEad** [CSSEGISandData/COVID-19#288]
Curious if there's a source for this or if it's a mistake?

The 'confirmed' number dropped from 706 to 696.  It's the only time that I've seen that a cases number has gone down.  Shouldn't it always be cumulative?

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238

**Comment by arik-so** [comment]
Yes, same with US data: https://github.com/CSSEGISandData/COVID-19/issues/286#issuecomment-596023946.  It all seems related to issue #238.

**Comment by ladris** [comment]
They've begun taking passengers off the Diamond, most likely why there's a
drop

**Comment by Bost** [comment]
> They've begun taking passengers off the Diamond, most likely why there's a drop

That may make sense but(!) when we take into account the all the mishaps, inconsistencies and erroneous commits in this repo... well, can you refer to a source confirming your claim please? Thanks

**Comment by ladris** [comment]
Sure thing!

First relevant article I could find:

https://www.japantimes.co.jp/news/2020/03/04/world/science-health-world/quarantined-diamond-princess-passengers-released-u-s/#.XmMbuJBlB-E
