### ISSUE TITLE
Netherlands seem duplicated

### ISSUE THREAD

**Issue by eilmrein** [CSSEGISandData/COVID-19#2885]
Hello, looks like today (2020-07-17) contains twice the number of cases for the Netherlands. In Provinces AND in the country.

**Comment by yetzt** [comment]
yes, they introduced administrative subdivisions and now adding up the total and the subdivisions. again, because they never learn. #2682

**Comment by CSSEGISandData** [comment]
Thanks @eilmrein - corrected in the daily.  Change will take about 20-30 minutes to propagate to the dashboard.
