### ISSUE TITLE
US data order

### ISSUE THREAD

**Issue by RobertClemenzi** [CSSEGISandData/COVID-19#2889]
07-18-2020 is the first day that Puerto Rico counties were included.
For all the other US states, "Out of xx" and "Unassigned" are placed at the end of the report. Puerto Rico is the only one where these are placed with the state's county records.

Also, 100% of the deaths are in "Unassigned,Puerto Rico", there are none associated with the counties.

**Comment by CSSEGISandData** [comment]
Thanks @RobertClemenzi, I moved the records for consistency.  With respect to the deaths, we have cases at the municipal level but deaths at the Commonwealth level.  Since we are unable to distribute to the municipalities, we report this data in Unassigned.

**Comment by dshemetov** [comment]
Hi @CSSEGISandData, can you say what is reported in Unassigned in the cases time series? It doesn't appear to be just an aggregate across the municipalities.
