### ISSUE TITLE
South Korea location

### ISSUE THREAD

**Issue by tsenyc** [CSSEGISandData/COVID-19#289]
Thank you for the initiative of working on this data. It's very helpful for everyone who is concerned about COVID - 19. I wanted to mention the location of South Korea is shifted on the map.
<img width="685" alt="Screen Shot 2020-03-06 at 9 33 05 PM" src="https://user-images.githubusercontent.com/60830799/76135315-d7c62480-5ff3-11ea-889a-3eb941f71dd7.png">

Thank you

**Comment by joshuascottcherry** [comment]
seems to be fixed
