### ISSUE TITLE
CSV file for COVID 07-19-20

### ISSUE THREAD

**Issue by j26perrin** [CSSEGISandData/COVID-19#2891]
I have copying the data daily from here into Excel, I know low tech for everyone else, writing formulas and creating charts and sending information to friends and families about deaths, delays in deaths, case volume and case changes over time.  The data has looked the same and I have been able to copy and paste into Excel right from the screen until I clicked on the CSV file for 07-19-20.  For some reason it looks completely different and I am unable to copy and paste the data from the screen directly into Excel.  If it would help, I can send my entire Excel file if needed.  Thanks and again I apologize if this is really too low tech for someone to even look at but I'm not really a computer whiz or programmer.

**Comment by j26perrin** [comment]
Sorry, the CSV file in question is for 07-18-20.  A screen shot of 07-17-20 (and all previous files) vs what 07-18-20 data looks like when you click on the file.
<img width="1241" alt="Screen Shot 2020-07-19 at 16 14 46" src="https://user-images.githubusercontent.com/68517732/87885394-3ad0ba80-c9db-11ea-9853-e89eb6d80b5f.png">
<img width="1217" alt="Screen Shot 2020-07-19 at 16 15 07" src="https://user-images.githubusercontent.com/68517732/87885401-4a500380-c9db-11ea-9dae-d5f46e7ef467.png">

**Comment by CSSEGISandData** [comment]
Hi @j26perrin.  What probably happened was that when we added the municipalities in Puerto Rico, the file got too large for GitHub to render in the display.  The best way to get this date in Excel is as follows:

1. In the top right corner, press the button that says "Raw"
![image](https://user-images.githubusercontent.com/60674295/87888254-bccfdc00-c9f9-11ea-892e-842364db3226.png)

2. You'll see a page that looks like the image below.  When you get this you need to save the page.  In chrome this would be File -> Save Page As , which brings up a file browser to let you save as a comma separated value (csv) to your local file system.
![image](https://user-images.githubusercontent.com/60674295/87888412-c443b500-c9fa-11ea-93c4-c2c8d1736542.png)

3. Once you've done this, you should be able to open it via File -> Open in Excel, or you can double click on it from a file explorer or finder window and it will most likely open in Excel.

**Comment by j26perrin** [comment]
Thank you kind person.  I have a MAC and had to change the file extension name but worked basically as you stated.  I don’t mean to be rude and please don’t take offense, but I really think you should work in customer service for a large firm.  Your explanation was correct, concise, no jibber jabber, and timely.  Four things that seem to be missing from most customer care lines I call nowadays.

John Perrin

**Comment by CSSEGISandData** [comment]
No worries and thanks @j26perrin.  Have a great day.
