### ISSUE TITLE
UK death toll paused

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#2896]
The UK government announced ([source](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#dashboard-of-coronavirus-cases-and-deaths)):

> On 17 July, the Secretary of State asked Public Health England (PHE) to urgently review the way daily death statistics are currently reported. We’re pausing the publication of the daily figure while this review takes place.

News about this issue on Reuters: [UK pauses daily coronavirus death toll update over data concerns](https://www.reuters.com/article/us-health-coronavirus-britain-casualties-idUSKCN24J0GC).

This may affect the UK data reporting in our dataset. We are watching on this issue closely. Thanks!

**Comment by pmeier-psm** [comment]
Government continue to publish UK death data, you can find it below (also the time series), it’s just been taken down from the public facing dashboard.

https://coronavirus.data.gov.uk/     and 
https://coronavirus-staging.data.gov.uk/deaths

It’d be useful for us if you could include the data again.
