### ISSUE TITLE
Permission Denied trying to access COVID-19 US Cases Living Atlas layer

### ISSUE THREAD

**Issue by louchios** [CSSEGISandData/COVID-19#2897]
Other map layers by CSSE_GISandData load fine. Please see screenshot thanks.
![2020-07-20_11-20-10](https://user-images.githubusercontent.com/14114900/87961573-8175f180-ca7b-11ea-8e5f-fe2f2c1d98a6.png)

**Comment by CSSEGISandData** [comment]
@louchios - not sure why you are getting an error, we have not changed permissions on any of our data.

**Comment by louchios** [comment]
Thanks. It started working again about an hour after I posted the issue. Sorry I forgot to follow up.
