### ISSUE TITLE
The "confirmed" column in the daily data files is actually giving confirmed + probable for Puerto Rico

### ISSUE THREAD

**Issue by sacundim** [CSSEGISandData/COVID-19#2900]
The "confirmed" column in the daily data files is actually giving confirmed + probable for Puerto Rico, as can be determined by comparing them to daily reports from Puerto Rico's Department of Health.  Here's for example your July 19th file:

* https://github.com/CSSEGISandData/COVID-19/blob/c85a3b95a056a633eac8c1f3102643e397fd9f27/csse_covid_19_data/csse_covid_19_daily_reports_us/07-19-2020.csv

It says 12,063 for Puerto Rico under "confirmed":

<img width="1219" alt="Screen Shot 2020-07-20 at 12 25 30 PM" src="https://user-images.githubusercontent.com/4076056/87980530-a1f87880-ca88-11ea-8638-d01a575aa59d.png">

But the Puerto Rico Department of Health daily PDF reports are available here:

* http://www.salud.gov.pr/Estadisticas-Registros-y-Publicaciones/Pages/COVID-19.aspx

And the July 19th report (which says "data until July 18" in the front page, a common source of confusion) says the number of confirmed cases was 3,791:

<img width="923" alt="Screen Shot 2020-07-20 at 12 34 48 PM" src="https://user-images.githubusercontent.com/4076056/87980675-d2401700-ca88-11ea-9ef5-1e275f9b8ae5.png">

As I've highlighted, 12,063 is the sum of confirmed + probable cases (which in Puerto Rico really means molecular test vs. antibody test).

I've looked also at time series files for municipalities of Puerto Rico and they're systematically making the same error.

**Comment by CSSEGISandData** [comment]
@sacundim The is described in the field descriptions in [Readme](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md) in the data directory:

> **Confirmed**: Confirmed cases include presumptive positive cases and probable cases, in accordance with CDC guidelines as of April 14.

**Comment by sacundim** [comment]
@CSSEGISandData I don't believe you're reading [that April 14 guideline correctly](https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/about-us-cases-deaths.html). If it's the one midway through that link, it reads:

> ### Confirmed & Probable Counts
>
> As of April 14, 2020, CDC case counts and death counts include both confirmed and probable cases and deaths. This change was made to reflect an interim COVID-19 position statement issued by the Council for State and Territorial Epidemiologists on April 5, 2020. The position statement included a case definition and made COVID-19 a nationally notifiable disease. Nationally notifiable disease cases are voluntarily reported to CDC by jurisdictions.
>
> A confirmed case or death is defined by meeting confirmatory laboratory evidence for COVID-19.
>
> A probable case or death is defined by one of the following:
>
> * Meeting clinical criteria AND epidemiologic evidence with no confirmatory laboratory testing performed for COVID-19
> * Meeting presumptive laboratory evidence AND either clinical criteria OR epidemiologic evidence
> * Meeting vital records criteria with no confirmatory laboratory testing performed for COVID19
>
> Not all jurisdictions report probable cases and deaths to CDC. When not available to CDC, it is noted as N/A.

Nowhere in there does it say that the sum of the confirmed and probable case counts should be labeled "Confirmed" as you do. And if we look at [the CDC's own "Cases in the U.S." page](https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html) that your README links when it refers to that same policy in regard to deaths, the way the CDC actually reports Puerto Rico's numbers is not what you claim is their policy. They do "include both confirmed and probable cases," but by that they mean they the list both as separate figures that they label "Confirmed Cases" and "Probable Cases." In addition to that they include the sum of those, but that one they label "Total Cases":

<img width="823" alt="Screen Shot 2020-07-20 at 11 43 17 PM" src="https://user-images.githubusercontent.com/4076056/88021762-ed3f7500-cae2-11ea-9113-b1bfa09e1b56.png">

So I don't believe the policy that you refer to in fact supports your practice.
