### ISSUE TITLE
US Cases and deaths missing

### ISSUE THREAD

**Issue by SchiffS** [CSSEGISandData/COVID-19#2901]
There is a systematic undercounting of US cases and deaths due to the non-inclusion of certain US sources that are not included within the CDC's database.  These include the Veteran's Administration, US Military, Federal Prisons and Navajo Nation.  As of 16:45 EDT on 19 July, these accounted for 83 356 confirmed cases and 2 458 deaths.  Further information, including links to the data sources and updated, complete data may be found at https://www.worldometers.info/coronavirus/country/us/

**Comment by CSSEGISandData** [comment]
@SchiffS saying these cases are being undercounted is incorrect.  These cases are reported to and through the public health reporting chains we are sourcing and are included in our counts.
