### ISSUE TITLE
Adjustment in cases recovered from Mexico?

### ISSUE THREAD

**Issue by EdgarSanchez1796** [CSSEGISandData/COVID-19#2905]
Hi, on 7/18/20 271239 were reported recovered for Mexico, but the next day (7/19/20) 254941 cases were reported, so there was a change of -16298 recovered, which also generates an increase + 16,298 new actives. Is that ok?

Thanks!

![image](https://user-images.githubusercontent.com/24661488/88063791-d2035280-cb40-11ea-9ddd-61d9b523d7fd.png)
tr

**Comment by CSSEGISandData** [comment]
@EdgarSanchez1796 There was a change on the 19th to the reporting at the state level of Active cases in Mexico; moving from https://covid19.sinave.gob.mx/mapaactivos.aspx to https://covid19.sinave.gob.mx/mapaestimados.aspx.  Our reporting is consistent with the totals from these sources.  I agree that it is unfortunate that this introduced the observed delta.
