### ISSUE TITLE
Philly reported -4271 cases compared to yesterday?

### ISSUE THREAD

**Issue by Marcbrig** [CSSEGISandData/COVID-19#2906]

**Comment by wellsangels** [comment]
Total cases for PA dropped about 3,600 between 7/19 and 7/20, largely thanks to that 4k drop in Philadelphia. The total JHU now has for the state is back in line with the total reported by the state Department of Health.

**Comment by CSSEGISandData** [comment]
Hello! We will add a new [scraper](https://www.phila.gov/programs/coronavirus-disease-2019-covid-19/) for Philadelphia. Thanks!

**Comment by Marcbrig** [comment]
Great, thank you!

**Comment by wellsangels** [comment]
Thank you. Can you tell us if the previously reported data were in error or if the county/state has updated their data?

**Comment by CSSEGISandData** [comment]
@wellsangels -previously reported data was in error but has now been updated in #2909.  Going to close this issue.  Thank you.
