### ISSUE TITLE
Issue with Uganda (20-07-2020). 1071 recovered, but totalcases is 1069

### ISSUE THREAD

**Issue by Skorpio21** [CSSEGISandData/COVID-19#2907]
Issue with Uganda (20-07-2020). 1071 recovered, but totalcases is 1069

**Comment by CSSEGISandData** [comment]
Hello! We added a statement in the [data modification section](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#data-modification-records) yesterday about this issue:

> July 20, the negative active cases in Uganda is due to different criteria. According to a tweet mentioned by Uganda Ministry of Health, th recovered cases include Ugandans, non Ugandans and refugees while confirmed cases capture only Ugandans. ([source](https://twitter.com/gbkatatumba/status/1285150623692926976))
