### ISSUE TITLE
Hong Kong data not refreshed

### ISSUE THREAD

**Issue by Gwoots** [CSSEGISandData/COVID-19#2908]
Hello, 
Hong Kong data have not been updated for a couple days.
Would it be possible to correct ? 
Thanks

**Comment by CSSEGISandData** [comment]
@Gwoots - currently working.  Will have resolved ASAP.

**Comment by CSSEGISandData** [comment]
@Gwoots - Data has been updated and merged.  Thank you for posting the issue.
