### ISSUE TITLE
Admin3 selection set does not populate Confirmed/Logarithmic/Daily Case chart

### ISSUE THREAD

**Issue by DM1145** [CSSEGISandData/COVID-19#2910]
Selection of data on the dashboard "Admin3" tab does not update data sets on the Chart displaying Confirmed / Logarithmic / Daily Case data.

Please close if this is by design.

**Comment by CSSEGISandData** [comment]
@DM1145 Thank you.  I agree with you that it would be much better to have admin2 curves if possible, but in the current design this is not implemented.  My apologies.

**Comment by DM1145** [comment]
TY for the rapid response.
