### ISSUE TITLE
Incorrect data for Chile and Peru on 2020-07-20

### ISSUE THREAD

**Issue by gvalenzuelarg** [CSSEGISandData/COVID-19#2911]
The number of confirmed cases and deaths for Chile and Peru on 2020-07-20 is incorrectly populated with the corresponding values from 2020-07-19. 

[Source Peru](https://github.com/jmcastagnetto/covid-19-peru-data/tree/master/datos)
[Source Chile](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto5/TotalesNacionales.csv)

**Comment by CSSEGISandData** [comment]
Thank you for posting the issue and your sources @gvalenzuelarg, I really appreciate your help.
