### ISSUE TITLE
discrepancies on Hong Kong and Chinese provincial data

### ISSUE THREAD

**Issue by patricksawick** [CSSEGISandData/COVID-19#2917]
In comparing the number of cases between the time series and EOD files:

https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_daily_reports/07-21-2020.csv

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

We are noting some discrepancies in the data for 7/21.  Hong Kong is reporting a value of 1655 in the EOD file and 1958 in the time series file.  Xinjiang is reporting a value of 77 in the EOD file and 140 in the time series file.

Which file is correct?  As a rule, should one be deferring to the EOD or time series file?

**Comment by CSSEGISandData** [comment]
@patricksawick Our method and source for collection for provincial data in China unfortunately produced stale data between 7/16 and 7/21.  We have both modified the collection method and updated / validated the historical data in the time series.  We have historically, except in the case of collection failures, updated the time series data as revisions become available and left the data in the daily files unchanged as a record of source reporting.
