### ISSUE TITLE
Texas counties data update

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#2918]
Hi,
I noticed an ongoing inconsistency in the data updates for several Texas counties.
The numbers for some counties (e.g. Harris, Dallas, Bexar) are in line with the local health department, whereas numerous other counties have a permanent 24h-backlog (e.g. Travis, Hidalgo, Denton). I don't see what causes this delay, as all Texas counties update their figures by no later than 01:00 GMT. I would be happy if you could give a brief explanation. 
Thank you.

**Comment by CSSEGISandData** [comment]
@NaKo91 Thank you for your patience.  There are sometimes structural delays in reporting to the state that are reflected in the the Texas DSHS reporting.  We believe that with some recent changes to our collection and reporting methods we have reduced or eliminated the most significant delays.
