### ISSUE TITLE
Iceland dropped a 100 confirmed Cases in 07-21-2020.csv ?!?

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#2919]
Iceland	23-07-20	1840
Iceland	22-07-20	**_1839_**
Iceland	21-07-20	1930
Iceland	20-07-20	1930

**Comment by CSSEGISandData** [comment]
Hello @bobromeo ! We had an [announcement](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#data-modification-records) on this issue yesterday:

> July 22, update Iceland confirmed cases and recovered cases (June 15 to July 20) according to the Directorate of Health and the Department of Civil Protection and Emergency Management of Iceland (https://www.covid.is/data). The positive with antibodies instances no longer figured into the number of total cases.

We also suggest the [time series tables](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) are better for research purpose. Thanks!
