### ISSUE TITLE
Jordan dropped a 100 confirmed Cases in 07-21-2020.csv ?!?

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#2920]
Jordan	23-07-20	1120
Jordan	22-07-20	**_1113_**
Jordan	21-07-20	1223
Jordan	20-07-20	1218

**Comment by CSSEGISandData** [comment]
@bobromeo This is consistent with the reporting revisions from the Jordanian government (see https://corona.moh.gov.jo/en)
![image](https://user-images.githubusercontent.com/60674295/88342670-d2047d80-cd0d-11ea-9da7-c43ccbcfe642.png)
