### ISSUE TITLE
Louisiana Death Drop from July 20th (Monday) to July 21st (Tuesday)

### ISSUE THREAD

**Issue by guzhiling** [CSSEGISandData/COVID-19#2925]
Louisiana Death drops from 3543 to 3462 from July 20th to 21st. I suppose it is related to Louisiana **reports probable cases only on Mondays** (July 20th). 

<img width="707" alt="image" src="https://user-images.githubusercontent.com/37173670/88400404-eab47800-cd8d-11ea-85c5-80fd5ce847fd.png">

Then, if the weekly probable cases continues to grow faster than daily new cases, this type of drop would persist and make the data for this state very difficult to interpret. Is there anyway to track / impute daily probable cases to make more sense about the time series?

**Comment by CSSEGISandData** [comment]
Thanks @guzhiling - corrected.
