### ISSUE TITLE
Lancaster county PA, USA cases in time_series_covid19_confirmed_US.csv is incorrect for 7/22 & 7/23

### ISSUE THREAD

**Issue by mahorst** [CSSEGISandData/COVID-19#2926]
Lancaster county PA, USA cases are the same for 7/21, 7/22 and 7/23. Other PA counties that I spot checked are incremented correctly over this time period, but Lancaster has not changed and has incorrect values for 7/22 and 7/23. 7/22 should be 5158 and 7/23 should be 5190.

**Comment by CSSEGISandData** [comment]
Thanks @mahorst, corrected pull and updated.
