### ISSUE TITLE
No Brazil cases for July 24th

### ISSUE THREAD

**Issue by MaximNN** [CSSEGISandData/COVID-19#2929]
No Brazil cases for July 24th?

**Comment by runrun12** [comment]
@CSSEGISandData are you going to correct this? Thanks!

**Comment by CSSEGISandData** [comment]
@MaximNN @runrun12 working reconstruction now.  Will hopefully have done and pushed very soon.

**Comment by CSSEGISandData** [comment]
@MaximNN @runrun12 @alksak - Data is updated in time series and state data in the daily.
