### ISSUE TITLE
Errors in Rhode Island and Wyoming time series

### ISSUE THREAD

**Issue by flattedk** [CSSEGISandData/COVID-19#2930]
Recent versions of time_series_COVID19_deaths_US have missing/wrong data for Rhode Island and Wyoming deaths

**Comment by runrun12** [comment]
Can you specify?

**Comment by CSSEGISandData** [comment]
@flattedk - as @runrun12 asked above, I would appreciate additional details on your concerns.  Our data matches the data reported by the state for both RI and WY.  

Currently:

Our Rhode Island Deaths
![image](https://user-images.githubusercontent.com/60674295/88464732-1bc6a280-ce8b-11ea-9335-41908361af5d.png)
Our Wyoming Deaths
![image](https://user-images.githubusercontent.com/60674295/88464742-31d46300-ce8b-11ea-9c9e-a111d02803b1.png)

Rhode Island deaths on their dashboard
![image](https://user-images.githubusercontent.com/60674295/88464759-50d2f500-ce8b-11ea-9074-2eedd96ffc26.png)

Wyoming deaths on their dashboard
![image](https://user-images.githubusercontent.com/60674295/88464752-47498d00-ce8b-11ea-825f-822a65759fc1.png)

**Comment by flattedk** [comment]
> Can you specify?

You're right they are there - I wasn't reading in the 'Unassigned' (Admin2) data
