### ISSUE TITLE
Brazil: number of deaths on juli 3rd same as juli 2nd

### ISSUE THREAD

**Issue by cchronograph** [CSSEGISandData/COVID-19#2940]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/07-03-2020.csv
reports the same number of total deaths as
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/07-02-2020.csv
for Brazil
while https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
reports 1290 new deaths.

**Comment by web-sys1** [comment]
@cchronograph  These sources are updated every 24h. I would tell @CSSEGISandData to update data soon.

**Comment by CSSEGISandData** [comment]
@cchronograph @web-sys1 Thanks for letting me know - it's updated now.
