### ISSUE TITLE
March 2020 Data for Kosovo are not correct

### ISSUE THREAD

**Issue by agrondk** [CSSEGISandData/COVID-19#2941]
Hi,

I'm Agron Daka, I am writing a Master Thesis for predicting Covid-19 spread across Kosovo next months comparing data from this dataset and other sources like temperature and humidity and government's measurements.
During my analysis I noticed that data for Kosovo are not correct like start date was 13 March 2020 (2 first cases) whereas on your dataset is 26 March with 71 case. Even if you take accumulative data on this date (March 26th) should be 86 cases and not 71.

Can you correct it please, I can help sending you cases from 13 to 26 March 2020 on daily basis,  find below cases for this period, let me know if you want me to send on any othe format (csv, xml, etc)

![image](https://user-images.githubusercontent.com/45521115/88596289-11600080-d065-11ea-8612-48f9ea9734ed.png)

Thanks in advance,
Agron

**Comment by CSSEGISandData** [comment]
@agrondk Thank you.  I am working this now and will post an update as soon as possible.
