### ISSUE TITLE
USA Recovered Cases by FIPS

### ISSUE THREAD

**Issue by orngeatom** [CSSEGISandData/COVID-19#2942]
Can you please provide insight into why we are not able to see recoveries by FIPS similar to confirmed, active, and deaths? Recovery by FIPS is required to have a true active case volume at a FIPS level.

**Comment by CSSEGISandData** [comment]
@orngeatom data on recoveries is generally not available at the county level.

**Comment by orngeatom** [comment]
Thanks, is this available at the state level?
