### ISSUE TITLE
Spain Confirmed cases no more updated

### ISSUE THREAD

**Issue by bertolem** [CSSEGISandData/COVID-19#2944]
Hello everybody,
  I noticed that Spain Confirmed cases are constant in the last few days.
Could you please double check ?

Thank you

M.

**Comment by CSSEGISandData** [comment]
@bertolem Thank you.  Working now.

**Comment by bertolem** [comment]
Hi,
  I still see same value for Spain confirmed in the last few days, is the fix still mid-air ?

M.

**Comment by CSSEGISandData** [comment]
@bertolem I'm very sorry that took so long, but it is updated now.

**Comment by bertolem** [comment]
really appreciate your support ! thank you
