### ISSUE TITLE
Error in India timeseries data for 28 July 2020

### ISSUE THREAD

**Issue by DrShaikNishan** [CSSEGISandData/COVID-19#2952]
Timeseries data for India on 28 June 2020 showing incorrect numbers. Incidence is over 50,000 while dataset shows 3083.
@CSSEGISandData

**Comment by CSSEGISandData** [comment]
@DrShaikNishan thank you.  Unfortunately with the change to the MOH site, there was far more variability in updates to the data in the past day than we have experienced in the past.  Over the past 24 hours there were 4 significant data changes that we caught.  We will monitor but we hope that as the new site structure stabilizes, the data and associated processes will stabilize as well.

**Comment by DrShaikNishan** [comment]
@CSSEGISandData Data looks correct today (30 July 2020). Thank you for your effort and dedication into this.
