### ISSUE TITLE
Georgia data is not updated in the data file from 7/28/2020

### ISSUE THREAD

**Issue by tcarey1981** [CSSEGISandData/COVID-19#2957]
Hi, 
I noticed that the state of Georgia's data is the exact same numbers from 7/27/2020 and 7/28/2020. Can you please relook at the 7/28/2020 data and see if Georgia did't send in their data for 7/28/2020?
This is the link that I am referring to: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/07-28-2020.csv
Thank you very much!
-Tim Carey

**Comment by CSSEGISandData** [comment]
@tcarey1981 thank you for posting this.  Just closed in the latest pull request.
