### ISSUE TITLE
Michigan Data Source/Manipulation?

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#2961]
Where is JH getting its data?  It does not come close to matching the Michigan.gov data for cases or deaths. And new deaths have been too low to be credible.  Previously in early June MI switched to reporting confirmed + probable cases.  JH did the same, but apparently is no longer doing this.
???

Cummulative JH vs MI 7-29
84650 vs 88974
6346  vs 6422

[https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html](url)

![JH reported data](https://user-images.githubusercontent.com/62083925/88921204-20e57200-d23c-11ea-9b9e-6f64a596c8b7.PNG)
![MI Dashboard](https://user-images.githubusercontent.com/62083925/88921212-23e06280-d23c-11ea-919b-e763711fed2f.PNG)

**Comment by CSSEGISandData** [comment]
@DavidViral Our data comes directly from the stated and includes both probable cases and deaths.  I have no idea what the  source of your data is shown above or where the claim is coming from that this is our data.  If you could point us to that source I would greatly appreciate it.  This is our the data in the daily report:

Michigan,US,2020-07-30 04:35:17,43.3266,-84.5361,**88974**,**6422**,57502,25050.0,26,890.9109242277125,1793233,,7.217838919234833,84000026,USA,17955.929478113085,

This is the data on the dashboard:

![image](https://user-images.githubusercontent.com/60674295/88952986-41c2bd00-d266-11ea-8005-8299d46cec10.png)
![image](https://user-images.githubusercontent.com/60674295/88953026-4edfac00-d266-11ea-917b-64b112874c20.png)

**Comment by DavidViral** [comment]
There was a data overflow that caused the discrepancy. 
My bad.




    On Thursday, July 30, 2020, 1:17:57 PM EDT, CSSEGISandData <notifications@github.com> wrote:  
 
 


@DavidViral Our data comes directly from the stated and includes both probable cases and deaths. I have no idea what the source of your data is shown above or where the claim is coming from that this is our data. If you could point us to that source I would greatly appreciate it. This is our the data in the daily report:

Michigan,US,2020-07-30 04:35:17,43.3266,-84.5361,88974,6422,57502,25050.0,26,890.9109242277125,1793233,,7.217838919234833,84000026,USA,17955.929478113085,

This is the data on the dashboard:

**Comment by CSSEGISandData** [comment]
@DavidViral no problem
