### ISSUE TITLE
Duplicate number of deaths in Mexico (July 25th)

### ISSUE THREAD

**Issue by agentphantom** [CSSEGISandData/COVID-19#2962]
There were 43,374 deaths in Mexico on July 25th but the global deaths file has the same number as July 24th (42,645).

Thanks!

**Comment by CSSEGISandData** [comment]
@agentphantom Thanks.  The Ministry of Health portal didn't update deaths on the 25th (see reporting here: https://mexico.as.com/mexico/2020/07/25/actualidad/1595678297_448716.html).  I'm in the process of reconstructing from other sources.  I'll have an update asap.

**Comment by CSSEGISandData** [comment]
@agentphantom updated.  Thanks!

**Comment by agentphantom** [comment]
Thanks to you!
