### ISSUE TITLE
Michigan Daily Cases

### ISSUE THREAD

**Issue by Tbess2020** [CSSEGISandData/COVID-19#2964]
Your data is way off the Michigan State daily cases.  On 7/28/20 they show 121.  You have 785 cases.  On 4/7/20 you have 1,749 Michigan lists 1,102.  Why such the massive discrepancy?  There is a disturbing trend to your plot line of cases where Michigan's site shows it on a down trend.

https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html?fbclid=IwAR2L31H8wnKwj41KXK9oz8XBBrDe19HGsY_y80KKgLvpf58PjFKlAH-wlxY

**Comment by runrun12** [comment]
Check this:

https://github.com/CSSEGISandData/COVID-19/issues/2961

**Comment by Tbess2020** [comment]
Yea that's no help.  There's is listing both as well and still massive discrepancy.

**Comment by CSSEGISandData** [comment]
Hi @Tbess2020.  I've addressed this issue  in the past (see #2739), but this is essentially the difference between counting based on the date of onset vs. counting based on the date of reporting.  We report based on date of reporting, the curve you are referring to is based on date of onset.  The state of Georgia does a very good job of showing the distinction between the two types of curves so I will explain using the [figures from Georgia ](https://dph.georgia.gov/covid-19-daily-status-report)below.  The first figure is the date of reporting graph, which shows a roughly steadying trend in the number of cases coming into the Georgia DPH over the past few days.  At first blush the second figure shows that there is a sharp downward trend in Georgia over the past few weeks, but as it is explained by Georgia DPH below the chart: 

>Note – Symptom Onset Date data during the reporting period may be incomplete due to the lag in time between when the case was tested and/or reported and submitted to the Georgia DPH for reporting purposes. This delay can vary depending on the testing facility and/or jurisdiction.

So there may be a sharp downward trend in Georgia, and I deeply and truly hope there is, but we just won't be able to say with any degree of certainty based on the date of onset until we are out of the ambiguous time window.  

To give you one more concrete example based on the Michigan data you provided: news outlets in Michigan (e.g. the [Detroit Free Press](https://www.freep.com/story/news/local/michigan/2020/03/18/coronavirus-timeline-first-case-michigan-first-death/5069676002/), the [Detroit News](https://www.detroitnews.com/story/news/local/michigan/2020/03/10/coronavirus-cases-confirmed-michigan/4974109002/), the [Lansing State Journal](https://www.lansingstatejournal.com/story/news/health/2020/03/10/coronavirus-michigan-covid-19/4952203002/)) reported the first 2 cases of COVID-19 on March 10th.  The curve you are referencing shows that based on retrospective analysis there were 155 cases on March 10th, and 14 cases on March 1st.  This does not mean that it was / is incorrect to say that Michigan reported 2 cases on March 10th.

![image](https://user-images.githubusercontent.com/60674295/88960826-1776fc80-d272-11ea-92a0-c0edebb4401c.png)
![image](https://user-images.githubusercontent.com/60674295/88960933-3f666000-d272-11ea-8c47-2c1571562013.png)

**Comment by Tbess2020** [comment]
So why wouldn't you be 14 days behind?  You show through yesterday.

**Comment by Tbess2020** [comment]
On the daily June 5th is crazy higher on yours!  More than any other days.
![image](https://user-images.githubusercontent.com/69011647/88965473-d0403a00-d278-11ea-8e99-d27d8e3352fe.png)

Compared to
![image](https://user-images.githubusercontent.com/69011647/88965563-f239bc80-d278-11ea-80e8-ff601969d950.png)

**Comment by CSSEGISandData** [comment]
We addressed this issue in #2704; June 5th was when Michigan began reporting probable cases and they came in as a single value on that day.  As discussed previously, the daily reports are reflective of the reporting we received at the time.  I recommend you look at the confirmed time series.

**Comment by Tbess2020** [comment]
How do you calculate your 7 day average?  I assume you use Michigan's source data, add the current date and the last 6 days and divide by 7 correct?  I'm not getting anything like you have.
[Michigan Covid new Cases 7-31-20.xlsx](https://github.com/CSSEGISandData/COVID-19/files/5006755/Michigan.Covid.new.Cases.7-31-20.xlsx)
