### ISSUE TITLE
reconciliation of the EOD and time series files

### ISSUE THREAD

**Issue by patricksawick** [CSSEGISandData/COVID-19#2967]
This is more of a general question.  

I had noticed that the daily reports (https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) section include many more series than are included in the time series (https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) section.  A lot of regional data for non-US countries are missing from the time series files that are in the EOD files, for example (Chile, Spain, Brazil, Peru, etc.).

Are there plans to include all geographies from the EOD files into the time series files?

**Comment by CSSEGISandData** [comment]
@patricksawick At this time there is not a plan to modify the time series file.  This has been discussed but for a whole host of technical reasons we have decided to, at least for now, continue with the current format.
