### ISSUE TITLE
Line items at the bottom of the EOD files

### ISSUE THREAD

**Issue by patricksawick** [CSSEGISandData/COVID-19#2969]
I have been noticing that additional line item have been placed at the bottom of the EOD files, i.e., in the case of the file from 7/30:

,,,Zambia,2020-07-31 04:35:18,-13.133897,27.849332,5555,149,3289,2117,Zambia,30.216564922152767,2.682268226822682
,,,Zimbabwe,2020-07-31 04:35:18,-19.015438,29.154857,3092,53,924,2115,Zimbabwe,20.803439322550663,1.7141009055627425
,,Telangana,India,2020-07-30 03:35:26,18.1124,79.0193,57142,480,42909,13753,"Telangana, India",145.16776935096883,0.8400126001890028
80040,Out of OK,Oklahoma,US,2020-07-24 01:34:55,,,0,0,0,0,"Out of OK, Oklahoma, US",,
,,Unknown,Colombia,2020-07-17 22:34:48,,,0,0,0,0,"Unknown, Colombia",,
2070,Dillingham,Alaska,US,2020-07-17 18:35:12,59.79603738,-158.23819419999995,1,0,0,1,"Dillingham, Alaska, US",20.34174125305126,0.0
,,Grand Princess,Canada,2020-07-13 12:34:33,,,13,0,13,0,"Grand Princess, Canada",,0.0
16061,Lewis,Idaho,US,2020-07-10 02:34:22,46.23315327,-116.434146,1,0,0,1,"Lewis, Idaho, US",26.055237102657642,0.0
41069,Wheeler,Oregon,US,2020-07-06 19:33:59,44.72698162,-120.02814270000002,0,0,0,0,"Wheeler, Oregon, US",0.0,

Are the line items at the bottom (so, in this case, below Zimbabwe) of the file here supposed to be values for 7/30?  Or are they supposed to relate to another date?  I know another date is posted on these lines, but when you add up the values and include these lines the sum equaled the global total that was on the dashboard for 7/30.  If you exclude them, then it would not have.

Please advise.

**Comment by CSSEGISandData** [comment]
@patricksawick These entries are for 7/30 and should be included.
