### ISSUE TITLE
District of Columbia data shifted by a day?

### ISSUE THREAD

**Issue by droodman** [CSSEGISandData/COVID-19#2973]
Comparing to the current DC gov spreadsheet, cumulative-cases data seem off by a day. 7/30 and 7/31 are the same value, which also happened before, in the last week. I wonder if there had been a problem in how they were reporting it in their own spreadsheets. Compare to https://coronavirus.dc.gov/sites/default/files/u23/DC-COVID-19-Data-for-July-31-2020.xlsx

**Comment by runrun12** [comment]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md

Please, see link attached. District of Columbia doesn't update data on weekends.

**Comment by droodman** [comment]
But I really wonder whether your DC data is shifted by a day. I am writing on the morning of Aug. 3. DC has updated its data in the last hour, and the final data point is labelled Aug. 2. https://coronavirus.dc.gov/sites/default/files/dc/sites/coronavirus/page_content/attachments/DC-COVID-19-Data-for-August-2-2020.xlsx.

Here is a comparison:

Date | DC gov | JHU
7/1/2020 | 10390 | 10365
7/2/2020 | 10435 | 10390
7/3/2020 | 10447 | 10435
7/4/2020 | 10482 | 10447
7/5/2020 | 10515 | 10482
7/6/2020 | 10569 | 10515
7/7/2020 | 10642 | 10569
7/8/2020 | 10679 | 10642
7/9/2020 | 10743 | 10679
7/10/2020 | 10801 | 10743
7/11/2020 | 10847 | 10801
7/12/2020 | 10906 | 10847
7/13/2020 | 10946 | 10906
7/14/2020 | 11026 | 10946
7/15/2020 | 11076 | 11026
7/16/2020 | 11115 | 11076
7/17/2020 | 11194 | 11115
7/18/2020 | 11261 | 11194
7/19/2020 | 11339 | 11261
7/20/2020 | 11427 | 11339
7/21/2020 | 11529 | 11427
7/22/2020 | 11571 | 11529
7/23/2020 | 11649 | 11571
7/24/2020 | 11717 | 11649
7/25/2020 | 11780 | 11717
7/26/2020 | 11858 | 11780
7/27/2020 | 11945 | 11858
7/28/2020 | 11999 | 11945
7/29/2020 | 12057 | 11999
7/30/2020 | 12126 | 12057
7/31/2020 | 12205 | 12057
8/1/2020 | 12274 | 12057
8/2/2020 | 12313 | 12057

**Comment by CSSEGISandData** [comment]
@droodman The 1 day offset is due to the reporting date (e.g. the data labelled 8/2 is published on 8/3); this is common.  The data carry-over had to do with a reporting delay; it's has been updated in the merge that closed this issue.  Thank you again for bringing this up, it helps resolve issues.
