### ISSUE TITLE
Error in Colombia data

### ISSUE THREAD

**Issue by ddazal** [CSSEGISandData/COVID-19#2974]
On **July 26**, **8181** new cases were reported for a total of **248976** confirmed cases in Colombia. However, the database reports 240795 for this particular day, which is wrong. This can be verified in the [following tweet](https://twitter.com/MinSaludCol/status/1287519855164436483) by the Ministry of Health.

**Comment by runrun12** [comment]
@CSSEGISandData could you please fix this issue? Thanks

**Comment by CSSEGISandData** [comment]
Thanks @ddazal and @runrun12, appreciate the heads up.
