### ISSUE TITLE
Victoria, Australia not updated for August 1st

### ISSUE THREAD

**Issue by chrisjbillington** [CSSEGISandData/COVID-19#2975]
The number of cases for Victoria, Australia in `time_series_covid19_confirmed_global.csv` did not update today.

It reads 10931, the same as yesterday. However, the number reported by health authorities in VIC today was 11557.

**Comment by runrun12** [comment]
@CSSEGISandData could you please fix this? The data is not correct in the daily files either

**Comment by CSSEGISandData** [comment]
Thanks @chrisjbillington and @runrun12, updated.

**Comment by chrisjbillington** [comment]
Thanks for the fix! Much appreciated.
