### ISSUE TITLE
Philippines data not updated

### ISSUE THREAD

**Issue by sil3ntd** [CSSEGISandData/COVID-19#2976]
Data for the Philippines on the following dates are not updated. 

July 29, July 30, and  July 31.

**Comment by runrun12** [comment]
@CSSEGISandData could you please fix this issue? Thanks

**Comment by CSSEGISandData** [comment]
Thanks @sil3ntd @runrun12

**Comment by sil3ntd** [comment]
Thanks @CSSEGISandData for the update
