### ISSUE TITLE
Victoria, Australia did not update August 2nd

### ISSUE THREAD

**Issue by chrisjbillington** [CSSEGISandData/COVID-19#2981]
Data for Victoria, Australia did not update for August 2nd, `time_series_covid19_confirmed_global.csv` lists 11557 confirmed cases, the same as the previous day.

The correct number is 11937, and was probably missed due to a late announcement today.

**Comment by runrun12** [comment]
@CSSEGISandData  could you please fix this issue? Thanks

**Comment by CSSEGISandData** [comment]
Updated @chrisjbillington @runrun12.  Thanks for the heads-up.  Victoria has been coming in a little after the cut-off for the past few days but I think it will come in clean tonight.
