### ISSUE TITLE
No data for 8-2 after Bedford Virginia

### ISSUE THREAD

**Issue by cspnyc** [CSSEGISandData/COVID-19#2982]
There is no data for the US locations listed from Bedford Virginia through the end of the file for 8/2.  There is no data for all of Bedford Virginia.  COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

**Comment by CSSEGISandData** [comment]
@cspnyc I see data in the file for 8/2, can you repull and verify local processing?

**Comment by cspnyc** [comment]
perhaps it was a glitch. In case you're curious, attached is the raw data
that I dropped into excel and converted the data from 1 column out into
it's comma delimited data columns.   Row 2913 is where the data looks like
it got corrupted.

Thanks
Chris
