### ISSUE TITLE
Incorrect data for Peru

### ISSUE THREAD

**Issue by qbitsone** [CSSEGISandData/COVID-19#2989]
Hi,
I have noticed that JHU has releasing the same data on 2 days, june'18 and june'19, for Peru
[https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/06-18-2020.csv](url)
[https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/06-19-2020.csv](url)

Please, take a glance...

JCValeriano

**Comment by CSSEGISandData** [comment]
Thanks @qbitsone - fixed.
