### ISSUE TITLE
Time series data for 3/7/2020 data is blank

### ISSUE THREAD

**Issue by lazd** [CSSEGISandData/COVID-19#299]
I just pulled the 3/7/2020 data and found that case data for all locations is blank:

* https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
* https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
* https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv

The column header is there but all data is blank.

**Comment by lazd** [comment]
Fixed by 6eae5b65a32b679efacf95a2867648330f83a871

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238
