### ISSUE TITLE
United Kingdom data not updating

### ISSUE THREAD

**Issue by ajwl** [CSSEGISandData/COVID-19#2993]
Hello,
For the last 3 days the cases data for the United Kingdom has showed no updates. In reality is has increased by several hundred every day for the last few days. 

8/3/20 | 8/4/20 | 8/5/20
305623 | 305623 | 305623

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv 

Could someone look into this? Many thanks

**Comment by ajwl** [comment]
Correct in the dashboard: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Wrong in the CSV: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by runrun12** [comment]
It is also wrong in the daily files. @CSSEGISandData  could you please fix this? Thanks

**Comment by CSSEGISandData** [comment]
Hello

We are investigating and have identified the source of the issue. Working on a fix. Thank you for your patience.

**Comment by ajwl** [comment]
Thank you

**Comment by CSSEGISandData** [comment]
Thanks for bringing this up @ajwl & @runrun12 - last update should resolve.
