### ISSUE TITLE
AFP Report citing JHU not matching data

### ISSUE THREAD

**Issue by acasstest** [CSSEGISandData/COVID-19#2998]
AFP news is reporting 2060 deaths on 6-AUG and citing JHU as the source
https://www.barrons.com/news/us-tops-2-000-deaths-in-24-hours-for-first-time-in-three-months-johns-hopkins-01596761106

Cannot determine where they are getting this info from and the data here contradicts the AFP.

**Comment by CSSEGISandData** [comment]
@acasstest As of this moment we have recorded 1250 new deaths in the US on the 6th.  We did have a historical revision to the data for deaths in Harris County Texas to line up with state reporting (noted in the retrospective data section of the data readme), but even with those added in (in case the delta with the prior day was not performed), the total would be under 2k.

![image](https://user-images.githubusercontent.com/60674295/89677241-13bf2780-d8bb-11ea-9eb4-c82b8fbf5a2a.png)
