### ISSUE TITLE
add data dictionary to README.md

### ISSUE THREAD

**Issue by jpiter** [CSSEGISandData/COVID-19#30]
What does “confirmed” mean? Recently there were discussions on defining confirmed as “tested positive/exhibit symptoms” as opposed to “tested positive/asymptomatic”. Are we looking at daily or cumulative readings? The latter maybe obvious but it would be nice to add a full data description to the repo.

**Comment by dawenx** [comment]
Regardless definition of “Confirmed”, I think this repo and many others only curate data from different sources.

**Comment by palrogg** [comment]
“Confirmed” means “confirmed cases”, see their dashboard: https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by ldf971215** [comment]
。。。。

**Comment by Hitesh111** [comment]
A "**Confirmed**" Case means those cases in  which  we have  **laboratory confirmation** of a person of having virus(causing COVID-19 infection), irrespective of clinical signs and symptoms. 

For more info [Check this out](https://www.who.int/publications-detail/global-surveillance-for-human-infection-with-novel-coronavirus-(2019-ncov)).

**Comment by Ekanuel** [comment]
Comfirmed simply means assurance that what has been done or submitted is legit or okay based some set of instructions.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. Every country may report confirmed cases slightly differently unfortunately. Due to this, we are aggregating case counts when they are confirmed by the country regardless of their definition of confirmed.
