### ISSUE TITLE
JHU :: data are lower than any other given source

### ISSUE THREAD

**Issue by francesco1119** [CSSEGISandData/COVID-19#3000]
FYI, 

I strongly trust your organization but I just wanted to let you know that your data are usually lower than other sources:

- **https://ncov2019.live/**
- **https://www.worldometers.info/coronavirus/#countries** (which is listed between your sources)

...lower by a good gap sometimes.

**Comment by CSSEGISandData** [comment]
@francesco1119 I am assuming that you are referring to the data for the United States.  If you look at the sources that you are citing above, they include cases (e.g. US Military) that are already included in the data from other places (e.g. Virginia).  Consider the following: you are a US military contractor living in Fairfax County Virginia and you test positive for COVID-19.  In line with the laboratory reporting requirements, your test will be recorded as a positive case in your county of claimed residence, Fairfax County.  However, the US Department of Defense would also report the number in their count for contractors (https://www.defense.gov/Explore/Spotlight/Coronavirus/).  Including this case from both the Virginia data and the US DoD data double counts that case.  A similar pattern exists in the other sources that constitute the gap you are referring to.

**Comment by francesco1119** [comment]
The gap happens a lot. Enough to make some country going up and down in the rank.
If we compare worldometers.info  to JHU and we have:

![Annotation 2020-08-08 094820](https://user-images.githubusercontent.com/3397477/89705644-520e2280-d95f-11ea-82a9-0a34016e71f1.png)

**- US:** 5,095,748 against 4,942,008 = `153,740`
**- Brazil:** 2,967,064 against 2,962,442 = `4,622`
**- India:** 2,089,773 against 2,088,611 = `1,162`
**- Russia:** 877,135 against 875,378 = `1,757`
**- South Africa:** 545,476 against 545.476 = same
**- Mexico:** 469,407 against 469.407 = same
**- Peru:** 463,875 against 463.875 = same
**- Chile:** 368,825 against 368.825 = same
**- Colombia:** 367,196 against 367,204 = `-8`
**- Spain:** 361,442 against 314,362 = `47,080` (terrible gap!!!)
**- Iran:** 322,567 against 322.567 = same

I see most of the countries in South America (apart from Colombia) have the same numbers as worldometers.info so I assume you use the same source. 
Brazil, India and Russia they have all a good thousands of gaps. 
The worst is Spain that has a `47,080`  of gap. 

So people start asking who is providing the right data, JHU, worldometers.info, ncov2019.live .... who knows ....

**Comment by CSSEGISandData** [comment]
@francesco1119 

There is always jitter through the day that often accounts for slight variation in reporting, but for the "terrible gap" you've identified, our data matches the official Spanish reporting:
![image](https://user-images.githubusercontent.com/60674295/89711376-f5f3d000-d957-11ea-8669-7362b68fe7fb.png)
