### ISSUE TITLE
Cases by country new order

### ISSUE THREAD

**Issue by flasp2** [CSSEGISandData/COVID-19#3009]
I have used the order of cases by country to show differences by day, but now the order is changed, so thats no longer possible. It used to end with Zimbabwe, now it ends with grenada. Is that a mistake or are the order of the countries changed forever

**Comment by CSSEGISandData** [comment]
@flasp2 I'm very sorry for the change - a few infrastructure changes have modified the order of the file.  Going forward the file should be ordered by Country_Region, then Province_State, then Admin2.  Slight modification of previous order.  I modified the daily_reports file for August 11 file to match this order.
