### ISSUE TITLE
Please update Brazilian cases / March, 7th is blank

### ISSUE THREAD

**Issue by jonasmrfranca** [CSSEGISandData/COVID-19#301]
1 - Please update the Brazilian confirmed cases, right know there are 19 confirmed cases according to Ministry of Health.

Confirmed - 19
Deaths - 0
Recovered - 0
Existing - 19

https://g1.globo.com/bemestar/coronavirus/noticia/2020/03/07/ministerio-da-saude-confirma-17-casos-do-novo-coronavirus.ghtml

2 - Dataset's columns for March, 7th is empty.

**Comment by picklejason** [comment]
Issue 2 is mostly resolved, except for some states in the US such as RI and AZ are still empty (not a big problem since there are 0 previous cases)

**Comment by jonasmrfranca** [comment]
Perfect! @picklejason  I've seen here.

Thank you!

**Comment by CSSEGISandData** [comment]
Sorry for the inconvenience. We have updated the time series tables.
