### ISSUE TITLE
Netherlands and China data superfluously repeated by province

### ISSUE THREAD

**Issue by doubleunary** [CSSEGISandData/COVID-19#3010]
There are 14 new rows in today's update of time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv:

* Netherlands: Flevoland, Friesland, Groningen, Noord-Holland, Zuid-Holland, Overijssel, Utrecht, Noord-Brabant, Gelderland, Limburg, Zeeland, Drenthe
* China: Hong Kong SAR, Macau SAR

These rows overlap the previous data for Netherland motherland and China's Hong Kong and Macau. All columns in the new rows contain zeros until the column of 2020-08-11. This looks like a deduplication issue.

**Comment by CSSEGISandData** [comment]
Thanks for bringing this to our attention. The time series files are being manually corrected and we are pushing a change to our product generation logic to prevent this reoccurring. Our humblest apologies.
