### ISSUE TITLE
Attribution of deaths in Orange County may be swapped (California vs North Carolina)

### ISSUE THREAD

**Issue by wadefagen** [CSSEGISandData/COVID-19#3016]
In the `08-11-2020` update, there was an unexpected uptick in reported deaths (from 47 to 58, +11) in Orange County, North Carolina.  This data is not seen in the county-level dashboard or state-level dashboards.

Instead, there were exactly +11 deaths in Orange County, California (the `08-11-2020` update shows a decrease of 2 cases from the day previous), the +11 is reported on dashboards and in the news (ex: https://losangeles.cbslocal.com/2020/08/12/orange-county-reports-245-new-coronavirus-cases-11-more-deaths/)

This may be a false positive, but it was suspicious enough that I wanted to pass it on to you all!  Thanks for all your work on this! :)

**Comment by CSSEGISandData** [comment]
@wadefagen thank you for bringing this up.  Tracking it down, it's actually an upstream error in a NC source - source has 58 when it should have been coded as 48.  I will update and close this issue with the merge.
