### ISSUE TITLE
2020-08-11 daily report has US Recovered incorrectly under FIPS 31153

### ISSUE THREAD

**Issue by kulnor** [CSSEGISandData/COVID-19#3019]
The csse_covid_19_daily_reports/08-11-2020.csv file has FIPS code "31153" associated with the "Recovered, US" record (line 3108). The FIPS code should instead be empty / blank. This is causing our parsing scripts to fail (duplicate entry for FIPS).

`31153,,Recovered,US,2020-08-12 04:27:29,,,0,0,1714960,-1714960,"Recovered, US",,`
should be 
`,,Recovered,US,2020-08-12 04:27:29,,,0,0,1714960,-1714960,"Recovered, US",,`

**Comment by CSSEGISandData** [comment]
Thanks @kulnor - technical issue on generation.  May repeat tonight but will knock it down asap.
