### ISSUE TITLE
Missing data for several locations 3/7

### ISSUE THREAD

**Issue by jtene001** [CSSEGISandData/COVID-19#302]
The column for 3/7 has been mostly filled in, but there are still empty cells for today on all three spreadsheets for 5 locations:

Tempe, AZ #39
Santa Clara, CA #65
Providence, RI #123
Berkeley, CA #145
Norwell County, MA #195

I posted this on the closed thread for the empty last column, but was concerned that it would not be read because it is closed.

**Comment by jonasmrfranca** [comment]
@jtene001 in my case, I have fixed manually for theses cases. Mostly adding a " .  " where is missing and a "0" in the end.

Example: -122273.  -> -122.2730

It's a workaround that might work until the dataset is not fixed yet.

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238

**Comment by jtene001** [comment]
@jonasmrfranca I did what I did yesterday for the missing final spots. I filled in today's cell with yesterday's data - and I guess that any error will be minimal. Doing this by hand is tedious though.

I was not aware that there were erroneous decimal point placements. Such an error would throw my plots off significantly and I didn't see any such thing happening.

**Comment by CSSEGISandData** [comment]
Sorry for the inconvenience. We have updated the time series tables.

**Comment by jtene001** [comment]
Thank you.
