### ISSUE TITLE
Question - what happened to "unassigned?" 

### ISSUE THREAD

**Issue by ripstaur** [CSSEGISandData/COVID-19#3023]
I note that in today's data (13 August 2020) all the "out-of" and "unassigned" are not there. Have they been incorporated elsewhere, or are they just not going to be reported any more?

**Comment by CSSEGISandData** [comment]
@ripstaur I think you mean in the daily file.  They are still there, the order of the file has changed.  The file is now uniformly ordered by Country, then State, then County.
