### ISSUE TITLE
Colorado Testing Data

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#3029]
The latest number of people tested and testing rate increase sharply on Aug 13. The number of people tested on Aug 12 was 601330, but it became 825062 on Aug 13, which also influence testing rate. Would you mind look into these data to see whether they are correct? Or could you provide any footnote/explanation on this sharp increase?

**Comment by CSSEGISandData** [comment]
@RuijingZ Testing data is sourced from [Covid Tracking Project](https://covidtracking.com/data).  It looks like there was a change on the 13th to reflect number of tests vs. number of people tested.
