### ISSUE TITLE
Visual Dashboard: Austria side menu links to Senegal and vice versa

### ISSUE THREAD

**Issue by MenOfWar** [CSSEGISandData/COVID-19#303]
When you click in Austria on the left side coutry list, it jumps to Senegal and shows Senegal informacion. Same for clicking in Senegal and seeing Austria's information instead.

Related to the website: https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by CSSEGISandData** [comment]
We have noted the issue and are looking into it. For a quick solution, please clear the browser cache or open the dashboard in incognito window. Sorry for the inconvenience.
