### ISSUE TITLE
Massachusetts different numbers daily reports and daily reports us

### ISSUE THREAD

**Issue by runrun12** [CSSEGISandData/COVID-19#3030]
Hello, the total confirmed cases and deaths cases for Massachusetts are different between the daily reports file and the daily report US file.

In the daily report file, the total confirmed cases are: 122319
In the daily report US, the total confirmed cases are: 121707

Please, could you check this information so both files have the same number?

Thank you

**Comment by CSSEGISandData** [comment]
Thanks @runrun12 working now
