### ISSUE TITLE
08-14-2020.csv that was just published is really  08-15-2020.csv ?

### ISSUE THREAD

**Issue by rahmatiangit** [CSSEGISandData/COVID-19#3036]
inside the newly published (13 minutes ago) 08-14-2020.csv, the "Last_Update" is "2020-08-16 04:30:18" 
which is expected for 08-15-2020.csv 

COVID-19/csse_covid_19_data/csse_covid_19_daily_reports_us/08-14-2020.csv

**Comment by lorint** [comment]
Good find ..  it certainly looks that way from here, apart from two anomalies in US data:
 (1) Arkansas case count is suspect, being -400 confirmed cases compared with 8/14, and
 (2) Minnesota death count shows -34 compared with 8/14.

Here's my dashboards after treating today's 08-14-2020.csv as if it really were 08-15-2020.csv:

https://emotery.com/covid_info.html
https://emotery.com/covid_deaths_info.html

**Comment by lorint** [comment]
Fix available in [PR3038](https://github.com/CSSEGISandData/COVID-19/pull/3038).

**Comment by runrun12** [comment]
@CSSEGISandData  could you fix this problem and Arkansas and Minessota, please? Thanks

**Comment by CSSEGISandData** [comment]
Thanks @rahmatiangit for reporting! Thank you @lorint for the PR, we missed it before fixing in a commit. Fixed in #3039
