### ISSUE TITLE
The latest Automated Update did not push Daily Reports for  08-15-2020 

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#3037]
The latest Automated Update did not upload the expected daily reports for 08-15-2020.  Instead, it appears to have modified the `Last_Update`  values for global and u.s daily reports for 08-14-2020 csvs. The commit did, however, update the time series data as expected.

**Comment by Lucas-Czarnecki** [comment]
Looking closer, it appears that the 08-14-2020 csvs have been modified with data from what should have been the 08-15-2020 csvs.

**Comment by lorint** [comment]
Fix available in [PR3038](https://github.com/CSSEGISandData/COVID-19/pull/3038).

**Comment by puf17640** [comment]
Please fix this! Our service ([disease.sh](https://github.com/disease-sh/API)) is partly dependent on that data.

**Comment by runrun12** [comment]
@CSSEGISandData please, could you fix this issue? A lot of people are using these files. Thanks

**Comment by puf17640** [comment]
It has been fixed by (1aaef2d9b98fa73a71b8e897b68ca67e33923a1e)

**Comment by runrun12** [comment]
Thanks!

**Comment by CSSEGISandData** [comment]
Thanks @Lucas-Czarnecki @lorint @puf17640 @runrun12 for bringing this up! Fixed in #3039
