### ISSUE TITLE
Spanish Death rate not updated Since May

### ISSUE THREAD

**Issue by ltrujilloleon** [CSSEGISandData/COVID-19#3046]
Hi,

The data from Spain is not correctly updated for deaths since May; it stays on the same value

Thanks

**Comment by ltrujilloleon** [comment]
Apologies is the recovered data, not the deaths

**Comment by Holzschuher** [comment]
As far as I am aware the Spanish Health Ministry stopped reporting these, for some unknown reason.

**Comment by CSSEGISandData** [comment]
@ltrujilloleon, @Holzschuher is correct here.  We hope to be able to update the data as soon as it is available again.

**Comment by ltrujilloleon** [comment]
Great
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
