### ISSUE TITLE
Manual Changes to Daily Reports Create Date Formating Inconsistencies 

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#3049]
A couple of recent commits were pushed to address an issue with Nebraska's data (see: #3045). These commits (Specifically, 818a50b09bcd4c22c05a02af248fcccaee140a43 and 60650a32e68ea498b26ad0ffa19967c7d827b1c0 ) appear to have been manually edited. As a result (maybe it was excel's fault) the date format for `Last_Update` changed from `yyyy-mm-dd HH:MM:SS` to `m/dd/yy H:MM`.  The affected files are the daily reports (global and U.S.) for 08-18-2020.

I have fixed it on my end, but this is the type of thing that breaks **a lot** of people's code. This is also a reoccuring issue, which hopefully can be avoided in the future. 

All the best  (Thanks for all your work as always) :)

**Comment by CSSEGISandData** [comment]
@Lucas-Czarnecki thank you for reporting the issue! We've patched the data with #3076 and will keep an eye out for these in the future!

**Comment by Lucas-Czarnecki** [comment]
Much appreciated.
