### ISSUE TITLE
Bristol Bay, Alaska, US in /csse_covid_19_daily_reports/16-08-2020.csv + 17-08+18-08+19-08

### ISSUE THREAD

**Issue by bobromeo** [CSSEGISandData/COVID-19#3050]
The combined key in these files says "Bristol Bay, Alaska, US"
But 6 days ago the record in the file /UID_ISO_FIPS_LookUp_Table.csv was changed to 
"Bristol Bay plus Lake Peninsula, Alaska, US"

**Comment by CSSEGISandData** [comment]
Hello! "Bristol Bay plus Lake Peninsula" replaces "Lake and Peninsula" and its FIPS code (UID=84002164) in our setting to match up with the official report. More info could be found here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#uid-lookup-table-logic. Thanks!
