### ISSUE TITLE
Webster County Iowa csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

### ISSUE THREAD

**Issue by frrobert2** [CSSEGISandData/COVID-19#3068]
Webster County Iowa in file csse_covid_19_time_series/time_series_covid19_confirmed_US.csv goes from 881 Total cases on 8/18 to only 683 Total cases on 8/19.

**Comment by CSSEGISandData** [comment]
Hello

Thanks for bringing this to our attention. The drop in cases appears to be related to recognition that some antigen tests in the county were mistakenly being coded as PCR tests ([news article](https://www.messengernews.net/news/local-news/2020/08/webster-co-public-health-correcting-covid-19-numbers/)) that the county and state health departments are rectifying. We will be reaching out to the county health department to see if we can have access to the accurate historical data.
