### ISSUE TITLE
U.S. totals differ between us and global time series files

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3072]
In the last week, the U.S. totals for cases and deaths in the confirmed_global and confirmed_us time series files have begun to differ slightly.They previously have matched every day up until 8/18 for confirmed and 8/21 for deaths.

For an example, the table below shows the difference between the sum of all rows in time_series_covid19_deaths_US.csv and the total reported for the US in time_series_covid19_deaths_global.csv. The two files have only recently begun to deviate. 

Date | time_series_covid19_deaths_US.csv | time_series_covid19_deaths_global.csv | difference
-- | -- | -- | --
8/8/20 | 162423 | 162423 | 0
8/9/20 | 162938 | 162938 | 0
8/10/20 | 163463 | 163463 | 0
8/11/20 | 164527 | 164527 | 0
8/12/20 | 166034 | 166034 | 0
8/13/20 | 167110 | 167110 | 0
8/14/20 | 168452 | 168452 | 0
8/15/20 | 169481 | 169481 | 0
8/16/20 | 170052 | 170052 | 0
8/17/20 | 170497 | 170497 | 0
8/18/20 | 171821 | 171821 | 0
8/19/20 | 173177 | 173177 | 0
8/20/20 | 174255 | 174255 | 0
8/21/20 | 175367 | 175370 | 3
8/22/20 | 176350 | 176353 | 3
8/23/20 | 176800 | 176802 | 2
8/24/20 | 177245 | 177252 | 7
8/25/20 | 178486 | 178486 | 0

The same pattern holds true for the US and global confirmed time series files.

Would you please let me know more information about this and why the totals are different? Which one is correct for the U.S.?

**Comment by CSSEGISandData** [comment]
Hello

Terribly sorry, that was my mistake. We had to make alterations for the time series for the District of Columbia and Collin County, Texas due to reporting errors on both sides and I hadn't pushed the same changes to the global time series. All have been adjusted now. The changes are documented in the README of the csse_covid_19_data folder, but lack the specific numbers.

**Comment by anthonydb** [comment]
Much appreciated, and thank you.
