### ISSUE TITLE
Belgium revised count for death - explanation in case you missed it

### ISSUE THREAD

**Issue by cuisquare** [CSSEGISandData/COVID-19#3075]
Hi

Belgium has revised their count of death down due to a further investigation in the death occurring in retirement homes. 

The explanation can be found at this address: https://covid-19.sciensano.be/sites/default/files/Covid19/MORTALITE%20COVID-19%20%E2%80%93%20MISE%20%C3%80%20JOUR%20DES%20DONNEES%20%E2%80%93%2026%20AO%C3%9BT%202020.pdf

An article on that matter, as well : https://www.lecho.be/dossiers/coronavirus/le-covid-19-a-fait-moins-de-morts-qu-annonce-en-belgique/10247337.html

In case that helps with your notes regarding that decrease

**Comment by CSSEGISandData** [comment]
Hello

Thank you for this! We will add this explanation to our README and will be reaching out the Belgian Public Health Agency to see if we can access their corrected time series file.
