### ISSUE TITLE
Sweden data for 27th August confirmed cases negative

### ISSUE THREAD

**Issue by PenguinStrikes** [CSSEGISandData/COVID-19#3078]
The confirmed cases data for Sweden on the 27th August appears to show a negative change from the previous day, wondering if this is an incorrect data entry.
![image](https://user-images.githubusercontent.com/5436272/91566355-72684600-e93b-11ea-925f-c2ee9d38758a.png)

**Comment by CSSEGISandData** [comment]
Hello

Thanks for bringing this to our attention. I have looked into the issue, and it appears to be the result of Sweden removing false positive test results performed with a faulty testing kit ([official press release](https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/allman-information-om-testning/felaktiga-provsvar-i-ca-3-700-covid-19-tester)). The Swedish Public Health Agency corrected the historical data on [their dashboard](https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/) to remove these probable cases over time. We have just used this data to recreate our time series files for cases and deaths.
