### ISSUE TITLE
Luxembourg confirmed cases showing substantial drop on 8/28

### ISSUE THREAD

**Issue by dgutkin** [CSSEGISandData/COVID-19#3082]
Luxembourg cases dropped by 1.3K on 8/28.

**Comment by CSSEGISandData** [comment]
Hello

Beginning, August 26, Luxembourg changed its reporting to no longer include non-residents (see report on [August 25](https://download.data.public.lu/resources/covid-19-rapports-journaliers/20200825-172653/coronavirus-rapport-journalier-25082020.pdf) and [August 26](https://download.data.public.lu/resources/covid-19-rapports-journaliers/20200827-191149/coronavirus-rapport-journalier-27082020.pdf)). We are having internal discussions to decide the best way to move forward. I'll leave this issue open until we have a method planned.

**Comment by CSSEGISandData** [comment]
Hello again

We have chosen to carry forward the new reporting structure from Luxembourg but not correct the historical data for two reasons: 1) We are uncertain if these cases have been distributed to their native countries and do not want to lose historical cases for the world total; 2) we are having difficulty finding a reliable corrected time series files for cases on the Luxembourg website; and 3) we want to document the change in reporting from the Luxembourg government.

We have corrected our recovered time series, which we had held at a static number after this change occurred.
