### ISSUE TITLE
New York City naming and population discrepancy

### ISSUE THREAD

**Issue by youyanggu** [CSSEGISandData/COVID-19#3088]
Since the release of the borough-level data for New York City (#3084), there is a small discrepancy in the naming for New York County (Manhattan):

`time_series_covid19_confirmed_US.csv`:

`Admin2` = New York
`Combined_Key` = New York, New York, US

`time_series_covid19_deaths_US.csv`:

`Admin2` = New York
`Combined_Key` = New York **City**, New York, US (should be New York, New York, US)
`Population` = 8,336,817 (should be ~1,629,000)

**Comment by CSSEGISandData** [comment]
Hi @youyanggu 

Thank you for noticing this! Just pushed the update to the time series. I'm happy we are able to assist your modeling.
