### ISSUE TITLE
New Hampshire is gone from web dashboard / map

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#3090]
New Hampshire data is not appearing in the geojson that powers part of the dashboard:
https://opendata.arcgis.com/datasets/1cb306b5331945548745a5ccd290188e_1.geojson

There are no counties, no anything else with that state name under Province_State.

**Comment by CSSEGISandData** [comment]
Should be fixed now. Minor hiccup when transitioning some of the back end infrastructure. Our apologies.
