### ISSUE TITLE
Massachusetts Reporting change

### ISSUE THREAD

**Issue by PCFarese** [CSSEGISandData/COVID-19#3091]
Greetings,

As per:
https://www.mass.gov/doc/covid-19-dashboard-september-2-2020/download

MA has changed the way they are reporting positive cases and deaths.  They also claim in this document they are restating their history.  Will JHU be picking up these changes?

**Comment by CSSEGISandData** [comment]
Hello

The change for Massachusetts is only for their probable cases, thankfully. These cases are located in the Unassigned, Massachusetts entry and our next update cycle will show a significant drop in cases for this entry. We are reaching out to the state to locate their fix to their time series data so we can bring it into our own.

**Comment by PCFarese** [comment]
Thanks for the quick and clear response!
