### ISSUE TITLE
The Bahamas case count does not match government release

### ISSUE THREAD

**Issue by jeanettelt** [CSSEGISandData/COVID-19#3094]
Bahamas case count does not match [Bahamas Ministry of Health releases](http://www.bahamas.gov.bs/wps/portal/public/novel%20coronavirus%20(2019-ncov)/!ut/p/b1/vZbZjqM6EIafZR4gjc2eS3ZCgLDYJHCD2JIOgZAEEpanH1rT0tFoNN03c3BdWSrrq_9XVclERByI6Jq8zqekOzfXpPq4R2xMaTvLlWje4ll6DTYQ2RtZcSiNgsSeOOjhZMqNdVIVLx5caDxH4QSUZH9somfddvJNuhxODHqZFIYZT196mJD7-6BTeSUV1iMdyaTVz6_3dp-Lh3jNGtN0gaWaK3G60vb9U0t0lS9JvV5J5a1-n56cvSqw3E83fqAVTO4eSchlqihh-ipiKQiU9b1TRawVbXYSVxWUBpuLLzpqg6QUfvyYRYWzKPCXI4BfmoFmCcKseUeiD80SZLeYAbzMfr7_IuFbz6LfERoDWLDBjik4nE7uaPCZ8FWJXxdJE-GcwP09gSMQcQB07JfjbTNdJq-cXGChYGOjcIIT7tvLtLeRQtldApEcQpDi3sItsCaL6ibPRrnu5IGHRUF25NP4_Brom_SyQB6xSwOphYEUWBpILg1kFgYaS3cp9e_n0CCic1q_9Vn9Bt4YACFJQZ4hKY7lSCIwshMjNUKvKLLXwneLBUO3pc82qYTp2Y-ajdgNG0cn0-4QO6JL69k4CK653eV5nR_xXlfFAd7WguVi9SZ55uu-0cjGuHLe9Zr291IQH1paV7E4Gc5lfeSzZk0-2CY17tFh-li-tt7UxTeuiH92Nhi21jS7IisjMHHv4wnPrpBWbttt6Y4ABYZ_YQwfD5aNXLLr0KcrkljRXvnddmKXBfIiXBrI_e_ALUnNQJMybV6CvkYtDOT_fdP8Nkr8miLXDAd4mocMBJAIypAd5HYzz5Idvxf4otlNlprSwPdaJYEHqhRvm1XqiLLXURlv9aAhrkhF1Vix2i6gBSHKq6SgTnuAi8zBz8iSwkRwMwN3K88lm60p7EznYT-knnWVGNF8K6Y5xra-6oXD4N9z9TV_aQrOcyvpYYb27pjHDdKzwcJV6NAcX5_fh9FGr2B7s5AfRECP4B77x6ZdncvIliPLMB_HguWyR73qxu45ELf6tTVZT58Of0Shver_Yh7mn5xjfkw!/dl4/d5/L2dBISEvZ0FBIS9nQSEh/), specifically for Aug 22, 2020 to August 27, 2020.

Wikipedia appears to have the correct time series case data: https://en.wikipedia.org/wiki/COVID-19_pandemic_in_the_Bahamas

**Comment by CSSEGISandData** [comment]
Thanks for bringing this to our attention. The three time series files have been updated.
