### ISSUE TITLE
Massachusetts Unassigned Cases  9/3 

### ISSUE THREAD

**Issue by CalvinParis** [CSSEGISandData/COVID-19#3099]
Mass shows  -7636 cases for 9/3 because Mass Unassigned  shows -8023 for 9/3.

Cumulative Mass Unassigned cases  drop from 10,088 |to 2,065 with no corresponding increase in assigned counties.

**Comment by CSSEGISandData** [comment]
Hello

Please see issue #3092. We're still working to redistribute those lost cases back in time.
