### ISSUE TITLE
Ecuador reporting -8K cases on 9/7

### ISSUE THREAD

**Issue by dgutkin** [CSSEGISandData/COVID-19#3102]
Significant drop in confirmed cases for Ecuador on 9/7.

**Comment by CSSEGISandData** [comment]
Hello

The drop in cases appears to the result of the Ecuador Ministry of Health altering their definition of cases from PCR+rapid tests to just PCR tests ([source](https://www.salud.gob.ec/msp-presenta-actualizacion-de-indicadores-en-infografia-nacional-covid-19/)). We're looking into a corrected historical record on the government source.
