### ISSUE TITLE
NYC daily report cases drastically decreased after August 31

### ISSUE THREAD

**Issue by veena-calambur** [CSSEGISandData/COVID-19#3103]
Every week our team pulls data from the csse_covid_19_daily_reports. For this past week we noticed that New York City county (FIPS 36061) saw a significant decrease in reported confirmed cases (as well as active and death numbers) from around ~230k confirmed to ~32k confirmed. It looks like there are 2 sources - one is the NY State health department and the other is the NYC Gov't Health website. The NY state health department shows the 32k number for New York county while the NYC Gov't Health website is still showing the 230k number. So it looks like the New York county source has changed. I wanted to reach out to see if others had noted this change and better understand why this happened?
![36061 data issues](https://user-images.githubusercontent.com/34037159/92621204-87c16680-f291-11ea-852a-8a3fcf9546b6.png)

**Comment by CSSEGISandData** [comment]
Hello

This change was noted in issue #3084 and demonstrates that New York County now represents solely the cases diagnosed in the borough of Manhattan. Our time series file has been back corrected to contain the borough level number of cases and deaths, with the methodology used to regenerate the time series explained in the issue.
