### ISSUE TITLE
Idaho 736 case reduction 

### ISSUE THREAD

**Issue by eolson3260** [CSSEGISandData/COVID-19#3106]
Hi,  Do you assume that the Idaho Unassigned case reduction by 736 is similar to that done by Massachusetts on 9/3, removing positive antibody test cases?     Thanks

**Comment by CSSEGISandData** [comment]
Hello

Thanks for bringing this our attention! The source we had been accessing for county level data had gone stale, so our state level totals were being pushed to the unassigned entry. When we transitioned to a new source (on September 9), those unassigned cases were properly distributed to their respective counties. There was a small hiccup with timing of the source transition and the state level total for Idaho on September 9 included both the unassigned cases (at their peak) and the cases once they had been distributed. This has been manually fixed. Our totals now match the state reporting.

**Comment by eolson3260** [comment]
Thanks so much for responding to my inquiry.

Sent from my iPhone

On Sep 11, 2020, at 2:40 PM, CSSEGISandData <notifications@github.com> wrote:

﻿

Hello

Thanks for bringing this our attention! The source we had been accessing for county level data had gone stale, so our state level totals were being pushed to the unassigned entry. When we transitioned to a new source (on September 9), those unassigned cases were properly distributed to their respective counties. There was a small hiccup with timing of the source transition and the state level total for Idaho on September 9 included both the unassigned cases (at their peak) and the cases once they had been distributed. This has been manually fixed. Our totals now match the state reporting.

**Comment by eolson3260** [comment]
GitHub,

Within the daily_reports_us file, I assume the Incident_Rate and Testing_Rate values are derived from the respective state’s population.  If so, might you have a data file that contains the those state populations?

Also, is there a reason the People_Hospitalized and Hospitalization_Rate columns are empty?

Thank you for what you do!

Regards,  -Eric

Eric Olson, CBCP
Sr. Manager, Business Continuity
HD Supply, Inc.
Orlando, FL
T: 407.822.2969
M: 407.252.0606
Eric.Olson@HDSupply.com<mailto:Eric.Olson@HDSupply.com>
