### ISSUE TITLE
null record with incorrect active case value a sum of all old dates in "time_series_covid19_confirmed_US.csv"

### ISSUE THREAD

**Issue by satvikchekuri** [CSSEGISandData/COVID-19#3107]
In the file located at "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", two new null records were added with the error value of the active case being "6396100" (which is sum cases all previous days).

**Comment by CSSEGISandData** [comment]
Removed- thanks.
