### ISSUE TITLE
India data is not updated

### ISSUE THREAD

**Issue by pratheeshraniprakash** [CSSEGISandData/COVID-19#3109]
In the time-series data for global confirmed cases (COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv), the data for India seems to be not updated. The data for last two consecutive days (12 September 2020 and 13 September 2020) remain the same. Considering the fact that India contributes to the largest share of COVID-19 cases at this moment, this error looks humungous.

The issue exists in deaths and recovered cases too.

**Comment by ManchesterWuer** [comment]
Still waiting for India's data update.

**Comment by Datagraver** [comment]
Indeed.
If not fixed today, we hope it will be updated in release tomorrow, retroactive.

**Comment by CSSEGISandData** [comment]
Hello all,

Looks as if the Ministry of Health and Family Welfare updated a bit later than normal and wasn't updated at the time we generate our daily products. The time series files were just manually updated. We are hoping that this is not a regular occurence.

**Comment by pratheeshraniprakash** [comment]
The issue has repeated in today's release too.

**Comment by ManchesterWuer** [comment]
The issue has repeated today (15 Sep). I checked the India Ministry of Health and Family Welfare (https://www.mohfw.gov.in/) and found that the number has already been updated. Is it possible that India has again postponed the release time?

**Comment by alksak** [comment]
The pipeline for India is broken again.
