### ISSUE TITLE
All Records in Pennsylvania for 9/13/2020 Duplicated from 9/12/2020

### ISSUE THREAD

**Issue by kwittarcgov** [CSSEGISandData/COVID-19#3110]
All the data records for the state of Pennsylvania on 9/13/2020 in the csse_covid_19_time_series were duplicated from 9/12/2020. Will the 9/13/2020 records be updated once the data are available from PA or will there always be no change in the data between those days?

Thanks!

**Comment by mahorst** [comment]
PADOH issued revised #'s for 9/13 (see https://www.health.pa.gov/topics/Documents/Diseases%20and%20Conditions/COVID-19%20County%20Data/County%20Case%20Counts_9-13-2020.pdf), they just need to be updated in this database.

**Comment by kwittarcgov** [comment]
Thank you for the update!

**Comment by CSSEGISandData** [comment]
Hello

Thank you for providing us with this resource! The time series files have been updated. Of note, there appears to be an anomaly in their Philadelphia entry (significant loss of cases that are not reflected the next day) so this record has stayed the same.
