### ISSUE TITLE
Death data for Switzerland

### ISSUE THREAD

**Issue by rwalker1501** [CSSEGISandData/COVID-19#3111]
The death data for Switzerland appears to be systematically in excess of the data published by the health office of the Swiss Federal government (BAG).  For example, today, September 14, CSSE reports 2021 accumulated deaths. BAG reports 1747. Please check.

**Comment by CSSEGISandData** [comment]
Hello

Our data is higher than that reported by the Swiss Federal Government as we access data at the canton level, which sometimes includes probable deaths in nursing homes. These deaths are not being reported by the Federal Government, leading to an elevated count in our data. Including these probable deaths is consistent with our approach to other regions and guidance from US CDC.
