### ISSUE TITLE
New York city population update changed from 8M to 1.6M

### ISSUE THREAD

**Issue by andrei-aron** [CSSEGISandData/COVID-19#3114]
Hi - I noticed that the New York City population has been changed from 8M to 1.6M. I believe the previous value was the correct one.
https://github.com/CSSEGISandData/COVID-19/commit/4010f63b0826198210a1957a6ff1d52f9b1cbd68#diff-eb3e961500680278537f38c751212d2e

See here on Wikipedia:
https://en.wikipedia.org/wiki/New_York_City
Estimate (2019)[7] | 8,336,817

Thanks!

**Comment by CSSEGISandData** [comment]
Hello

Please see issues #3084 and #3103. The population now reflects borough level data.
