### ISSUE TITLE
Massachusetts confirmed case data problems

### ISSUE THREAD

**Issue by vjcitn** [CSSEGISandData/COVID-19#3116]
The JHU csv file has cumulative case count dropping from 9/2 to 9/3:
```
8/29/20 8/30/20 8/31/20  9/1/20  9/2/20  9/3/20  9/4/20  9/5/20  9/6/20  9/7/20 
 128030  128229  128533  128888  129182  121546  121758  122196  122562  122791 
 9/8/20  9/9/20 9/10/20 9/11/20 9/12/20 9/13/20 
 122962  123143  123546  123986  124540  124826 
```
![macum](https://user-images.githubusercontent.com/4624066/93156835-edb94e00-f6d6-11ea-8297-0152498d1bbf.png)

R code:
```
library(dplyr)
library(magrittr)
z = read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", check.names=FALSE)
d = lubridate::as_date(names(z)[-c(1:11)], format=c("%m/%d/%y"))
m = z %>% filter(Province_State=="Massachusetts")
cs = apply(data.matrix(m[,-c(1:11)]),2,sum)
par(mar=c(4,4,2,2))
```

**Comment by CSSEGISandData** [comment]
Hello

Please see issues #3091, #3092, and #3099. #3092 contains the most detailed explanation. The drop in cases is due to a change in Massachusett's definition of probable cases that resulted in a drop in our unassigned entry. We are in contact with the state health department to retrieve the back distribution, but are still waiting for their response.

**Comment by vjcitn** [comment]
Thanks for these pointers.  I note that the divergence between cumulative MA confirmed case counts and those reported by MA DOPH diverge after July 5.  Here is the calculation from yesterday's CSV

![thecsv](https://user-images.githubusercontent.com/4624066/93205913-94790b00-f726-11ea-91da-48b1576733e9.png)

Here is the July 6 MA DOPH dashboard value

![jul6](https://user-images.githubusercontent.com/4624066/93205953-a3f85400-f726-11ea-8047-4777c87a7c45.png)

The July 5 dashboard agrees with CSV

![july5](https://user-images.githubusercontent.com/4624066/93205998-b2467000-f726-11ea-95f0-1171e7ddbd89.png)

If there is any way we can help with MA DOPH let us know.   carey  dot  vj  at   gmail

**Comment by CSSEGISandData** [comment]
Thank you for these resources. We are contacting the state for county level confirmed and probable cases as we need those to alter our time series files.
