### ISSUE TITLE
Swedish data appears to be stale

### ISSUE THREAD

**Issue by ArtisF** [CSSEGISandData/COVID-19#3118]
Hi! Thanks for all the work you are doing. Very helpful. I just noticed that the Swedish total confirmed cases haven't moved since 11 September suggesting that these series haven't been updated. Can this be fixed?

**Comment by CSSEGISandData** [comment]
Hello

Thanks for bringing this to our attention! Sweden normally doesn't publish new data on the weekends, but through this issue we are now aware of a new notice on the [dashboard homepage](https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa) that suggest data will not be updated on Saturdays, Sundays, or Mondays. 

A section of the README file in the csse_covid19_data folder contains locations with irregular update schedules. We have updated the Sweden entry with this new information.

**Comment by ArtisF** [comment]
Thank you!

Artis

CSSEGISandData <notifications@github.com> (šajā datumā: Ot, 2020. g. 15.
sept. 14:52) rakstīja:
