### ISSUE TITLE
Alabama extremely high for 9/15

### ISSUE THREAD

**Issue by rloomer** [CSSEGISandData/COVID-19#3120]
Alabama is extremely high for all counties as of 9/15.  Typically new cases for the state are around 1,000 per day, but as of 9/15 there were 14,092 cases spread out among most of the counties?
Likewise for the number of deaths, typically around 13 new deaths per day, but 166 on 9/15?

**Comment by bms44974** [comment]
The Alabama Department of Health dashboard is reporting 140,160 total cases, 13,391 fewer than the sum across counties in time_series_covid19_confirmed_US.csv. Substantial increases appear to be spread across all counties (except "unassigned").

**Comment by MNRKCM** [comment]
Do we know if this is a bad data point for 9/15 or a one-off adjustment of the data to account for prior under counting?

**Comment by DavidViral** [comment]
The AL error is in the global total as well.

I captured the AL data at their website at 8:57 am ET on 9/15.

https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7


![AL 0857 ET](https://user-images.githubusercontent.com/62083925/93340723-35d19100-f7fb-11ea-802a-1fdeb3ba13df.PNG)

**Comment by stevemk924** [comment]
I concur it doesn't appear to be a restatement, rather an error.  The JHU data has AL total of 153,551 vs. 140,160.

**Comment by CSSEGISandData** [comment]
Hi all

Terribly sorry about this - Alabama distributed their probable cases to the county level yesterday which resulted in a drop in our unassigned, Alabama entry that was caught in our validation architecture. We just updated the time series files and daily reports, and I'll be adding a note to the README about this distribution.

**Comment by MNRKCM** [comment]
Thanks.  I'm not seeing the correction in the State data file?  https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/09-15-2020.csv

**Comment by anthonydb** [comment]
The Alabama total in the time series file works out to 141,087 which is still higher than what the Alabama state dashboard is reporting currently?

**Comment by stevemk924** [comment]
The county level data is off still.  When excluding the "Out of" and "Unassigned", AL's new case number is +14.788 with 9/15 cumulative total of 141,087 vs. 9/14 of 126,299.  The "correction" appeared to be zeroing out Unassigned for 9/15 and is making things worse.

**Comment by CSSEGISandData** [comment]
@MNRKCM we're pushing a correction to the state file shortly.
@anthonydb the Alabama state dashboard is currently displaying 141,087 cases ([link](https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7)).
@stevemk924 Prior to September 15, the unassigned entry contained all of the Alabama probable cases as that information was not available at the county level. These were distributed on September 15. Do not exclude the entries for "Out of" and "Unassigned" prior to September 15 or your calculation will not contain state reported probable cases.

**Comment by stevemk924** [comment]
I wished Alabama would appropriately restate all of their prior periods to include the probable cases. This data treatment is not the proper way to report.  It throws users off because they see the aggregates of the counties are greater than the State level total.

**Comment by MNRKCM** [comment]
You said  "we're pushing a correction to the state file **shortly**"

I'm still not seeing an update of the state file?  Is there still a problem with the correct data?

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/09-15-2020.csv
