### ISSUE TITLE
Reason for Alabama 24k case spike on 9/15 adjusted to 1600 today 

### ISSUE THREAD

**Issue by eolson3260** [CSSEGISandData/COVID-19#3125]
Hi,  Do you have any insight on why Alabama reported so many cases yesterday only to be adjusted today?  Obviously it also showed as a big jump for the overall U.S. yesterday as well, which was corrected today.  I'd just like to call it out to my report recipients this morning,  Any info will be appreciated.  Thanks, -Eric

**Comment by anthonydb** [comment]
See this from yesterday: https://github.com/CSSEGISandData/COVID-19/issues/3120

**Comment by DavidViral** [comment]
Alabama total cases and total deaths are the same as yesterday, i.e. 9/15 and 9/16 are identical in the state time series.

**Comment by eolson3260** [comment]
In yesterday's(9/16) time series file the total for all Alabama cases (including unassigned) increased from 9/14 (139,459)to 9/15(153,551), which is an increase of 14,092 cases(spike).  Alabama Unassigned contained 13160 for 9/14 and 13347 for 9/15.  The 9/15 spike of 14,092 came from increases from all Alabama records, but today's file shows both Alabama Unassigned cases at zero (0) for both 9/15 and 9/16.  I can't explain it.  Any thoughts?

**Comment by anthonydb** [comment]
This seems to explain it: https://github.com/CSSEGISandData/COVID-19/issues/3120#issuecomment-693457693

In short, Alabama assigned probable cases to counties, but JHU's system did not concurrently remove those values from unassigned. JHU corrected this yesterday morning, zero-ing out the unassigned cases.

**Comment by eolson3260** [comment]
That explanation works for me!  Thank you very much, Anthony.

**Comment by CSSEGISandData** [comment]
Hi all

@anthonydb thank you for responding. We made another change today as we realize that we had caught the 9/16 AM update for Alabama when we pushed the fix to the time series yesterday. This has been rectified. Our mistake!
