### ISSUE TITLE
India data start missing

### ISSUE THREAD

**Issue by MaximNN** [CSSEGISandData/COVID-19#3129]
Dear GITHUB team, 

For the daily time series https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series no data is being uploaded for India for 14.09.2020, 16.09.2020 and 17.09.2020.

Is this the case that you will not update India data in future? Please, advise.

Many thanks,
Maxim

**Comment by CSSEGISandData** [comment]
Hello

We're running into issues with India altering the time of day that it publishes updates. It is becoming a bit inconsistent and sometimes there are >24 hours between updates, resulting in our daily products appearing to be stale. I have manually updated the time series files, but this may happen again tomorrow evening. We're having internal conversations for how to fix this moving forward.
