### ISSUE TITLE
Data about India repeted on 17 and 18 september

### ISSUE THREAD

**Issue by antoniocaramia** [CSSEGISandData/COVID-19#3133]
![india_17-18_september](https://user-images.githubusercontent.com/63555593/93691549-04044700-fae7-11ea-8f33-9b4679d1be09.PNG)

Please verify data about **India**.
They seems repeated in the last 2 days (17 and 18 september).

The error is always for the "last 2 days" (and not only 17 and 18 september).
I mean: when you'll check it, 17 and 18 september will be ok but you can notice the problem on the last 2 days.

This is the second time I notice that in the last week. If can be useful, I never noticed this problem before.

Can you check and fix the problem?

Thanks a lot.

Antonio Caramia

**Comment by CSSEGISandData** [comment]
Hello

Please see issue #3129 for an explanation of the reason this is occurring. I have manually updated the time series files.

**Comment by antoniocaramia** [comment]
Thanks a lot.
I hope you'll fix the problem... Otherwise you have to fix data very often!




Il dom 20 set 2020, 14:29 CSSEGISandData <notifications@github.com> ha
scritto:

**Comment by antoniocaramia** [comment]
Hi all,
Can you update Indian data again?
Thanks a lot.




Il dom 20 set 2020, 14:29 CSSEGISandData <notifications@github.com> ha
scritto:
