### ISSUE TITLE
New Hampshire testing numbers are wrong (~150K) starting with 9/18/2020 data

### ISSUE THREAD

**Issue by winginit-nh** [CSSEGISandData/COVID-19#3134]
New Hampshire testing (People_Tested) numbers are wrong (+150K) starting with 9/18/2020 data. Verified by state data and The Covod Tracking Project.  Ex. data for 9/19/2020 should be 238732 but is 393166.

**Comment by CSSEGISandData** [comment]
Thank you for your post. We are capturing total tests (in specimens), which is in agreement with what is posted on The COVID Tracking Project here: https://covidtracking.com/data
<img width="911" alt="Screen Shot 2020-09-20 at 5 08 25 PM" src="https://user-images.githubusercontent.com/60674295/93722356-31430a80-fb64-11ea-98b5-0654d7ff9370.png">
