### ISSUE TITLE
Spike in Harris County, TX (Houston) for 9/21/20

### ISSUE THREAD

**Issue by rloomer** [CSSEGISandData/COVID-19#3142]
Is there an explanation for the spike in Harris County, TX?  Typically they average around 1,000 new cases per day but as of 9/21 it increased by 14,129.  
Several other Texas counties had unusual increases on the same day.  Guadalupe County (northeast San Antonio) typically averages 12 per day but had an increase of 1,587 new cases.  16 other counties had unusual spikes on a smaller scale (Atascosa, Gonzales, Frio, Lavaca, Karnes, Wilson, Calhoun, Jackson, Kerr, Zavala, Kendall, Gillespie, Dimmit, Bandera, Edwards, Kinney).

**Comment by CSSEGISandData** [comment]
Hello

According to the [state dashboard](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83), Texas just released a massive backlog of old case data for multiple counties. I'm going to pin an issue as this will be very problematic for modelers.
