### ISSUE TITLE
Texas Data Backlog 9/21

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#3143]
Numerous counties in the state of Texas see abnormal spikes in cases in the daily report and time series entries for September 21. According to the [state dashboard](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83), these spikes are due to the release of backlogged case data. The statement from the dashboard in full is reproduced here:

_2,088 older case recently reported by labs were included in the statewide total but excluded from statewide and Bexar County new confirmed cases (103)_

_3 older cases recently reported by labs were included in the statewide total but excluded from statewide and Collin County new confirmed cases (42)_

_306 older case recently reported by labs were included in the statewide total but excluded from statewide and Dallas County new confirmed cases (465)_

_298 older cases recently reported by labs were included in the statewide total but excluded from statewide and Frio County new confirmed cases (1)_

_328 older cases recently reported by labs were included in the statewide total but excluded from statewide and Harris County new confirmed cases (225)_

_1 older case recently reported by labs was included in the statewide total but excluded from statewide and Houston County new confirmed cases (2)_

_125 older cases recently reported by labs were included in the statewide total but excluded from statewide and Tarrant County new confirmed cases (203)_

_Older cases are being reported for several counties in Public Health Region 8 after DSHS staff identified 3,921 cases that had not previously been reported. Those counties are Atascosa (522), Bandera (41), Calhoun (186), Dimmit (53), Edwards (33), Gillespie (96), Gonzales (234), Guadalupe (1587), Jackson (77), Karnes (181), Kendall (128), Kerr (142), Kinney (19), Lavaca (252), Real (12), Wilson (307) and Zavala (51). There are no new cases reported for those counties today_

_There was an increase of 1,051 TDCJ cases in Anderson County after a similar decrease on Friday. The county total was adjusted, but the cases did not factor into county or statewide new confirmed cases on either day_

When stating that these cases "were included in the statewide total but excluded from statewide and County new confirmed cases", this only means that they did not include these backlogged cases within their internal reports about new daily cases. The cases are still added to the county total and without historical redistributions we are unable to fix the spikes in our own data. We'll see what we can do but this is problematic and likely won't have a straightforward solution.

**Comment by CSSEGISandData** [comment]
Of note, for several counties listed in this announcement we access case data from county sources rather than the state dashboard. These are the counties as well as the effect of the data backlog on local reporting:

Bexar - data backlog was released one day prior, so the probable case spike occurs on September 20.
Dallas - data backlog was released one day prior, so the probable case spike occurs on September 20.
Harris - see issue #3144 
Tarrant - data backlog appears on September 21.

**Comment by CSSEGISandData** [comment]
Update for 9/22 from the state dashboard:

_2 older cases recently reported by labs were included in the statewide total but excluded from statewide and Dallas County new confirmed cases (314)_

_13,622 older cases recently reported by labs were included in the statewide total but excluded from statewide and Harris County new confirmed cases (507)_

_231 older cases recently reported by labs were included in the statewide total but excluded from statewide and Nueces County new confirmed cases (1)_

_1 older case recently reported by labs was included in the statewide total but excluded from statewide and San Jacinto County new confirmed cases (0)_

As mentioned above, Harris County is pulled from the county so this rise in cases is already in our data (See issue #3144)

**Comment by lorint** [comment]
Thank you very much for providing these clarifications.  Would be outstanding if the backlog data could have included back-dating as well in order to get accurate trending information, but at least we've got a clearer picture at this moment of where things are, so certainly it's still useful.

**Comment by CSSEGISandData** [comment]
@lorint fully agreed! We are going to see if this is feasible by reaching out to individual health departments, especially for those with the greatest spikes.
