### ISSUE TITLE
Deaths in France

### ISSUE THREAD

**Issue by odadoun** [CSSEGISandData/COVID-19#3145]
Hello,

first of all thank you very much for all the work you have done. 
I am wondering what data are you using for the deaths in France ?
I have only the data for what concerns the French hospitals, which represents only 2/3 of the total deaths.
By advance thank you
regards,
Olivier

**Comment by CSSEGISandData** [comment]
Hello

Our data is sourced from https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA, which is the official France source.
