### ISSUE TITLE
A lot of the state numbers are messed up; Especially NY, CA, FL, TX

### ISSUE THREAD

**Issue by ahande123** [CSSEGISandData/COVID-19#3147]
![Numbers_Messed_Up](https://user-images.githubusercontent.com/26362788/93931751-37b0be00-fced-11ea-9243-b59a0b5a20f1.png)

I used the nightly updates to get the data from my COVID data analytics site and I have noticed that the numbers for the 4 big states are way off when compared to WorldoMeters.

What is going on.  This is disappointing.  Did something change?  The screen shot shows the difference in numbers for these 4 states and the JH data is nowhere near the correct numbers for NY, CA, FL, TX and some other states.

**Comment by CSSEGISandData** [comment]
Hello

I think there is an error in the code used to generate your COVID data analytics site. Total cases reported for California in [last night's daily report](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/09-21-2020.csv) was 790,096 (versus 284,190 on your screenshot). No daily report contains the spread of cases reported on the site, so I don't believe you are accessing an old file. The structure of our files has not changed. Is this a recent error that has cropped up?

In general, we cannot speak to the veracity of WorldoMeters data. For our data, all of our sources are clearly listed in the README section of the repository, and we currently align with all of our listed official sources.

**Comment by ahande123** [comment]
Thanks for getting back.  I noticed it about a couple of weeks ago.  I had no problem with the nightly updates for the last 4 months prior to that.
Hmm! I need to investigate this. It is funny that it has affected only some states.
Corona Virus


| 
| 
|  | 
Corona Virus

Covid Analyst

A site dedicated to the Coronavirus outbreak. The facts, numbers, stories, conspiracies, and horror behind the ...
 |

 |

 |




    On Tuesday, September 22, 2020, 04:39:47 PM EDT, CSSEGISandData <notifications@github.com> wrote:  
 
 


Hello

I think there is an error in the code used to generate your COVID data analytics site. Total cases reported for California in last night's daily report was 790,096 (versus 284,190 on your screenshot). No daily report contains the spread of cases reported on the site, so I don't believe you are accessing an old file. The structure of our files has not changed. Is this a recent error that has cropped up?

In general, we cannot speak to the veracity of WorldoMeters data. For our data, all of our sources are clearly listed in the README section of the repository, and we currently align with all of our listed official sources.
