### ISSUE TITLE
Through the analysis of the number of recovery is divided by the sum of the number of recovery and the number of deaths, I may have discovered the law of COVID-19 rehabilitation

### ISSUE THREAD

**Issue by zyq5945** [CSSEGISandData/COVID-19#3148]
[Sorry, I am not good at English,please read Google translate](https://translate.google.com/translate?hl=en&sl=zh-CN&tl=en&u=https%3A%2F%2Fzyq5945.github.io%2Fzyq5945%2Fblog_15.html&sandbox=1)

**Comment by CSSEGISandData** [comment]
Different countries report recoveries using separate criteria so we do not recommend making direct comparisons between countries.
