### ISSUE TITLE
Alaska Confirmed Cases Jump

### ISSUE THREAD

**Issue by Sylvain-Royer** [CSSEGISandData/COVID-19#3149]
On September 23rd, the cases and deaths for Alaska doubled from the day before. The previous numbers were 6936/45 on the 22nd and became 13993/90. This seem to be an error.

**Comment by CSSEGISandData** [comment]
Thank you. We are currently investigating the issue and fixing.

**Comment by CSSEGISandData** [comment]
Issue has been resolved. Thank you again.

**Comment by Sylvain-Royer** [comment]
Thank you very much!
