### ISSUE TITLE
Official source for covid-19 cases in portugal

### ISSUE THREAD

**Issue by perigoso** [CSSEGISandData/COVID-19#315]
This is an official source for up to date numbers.

https://www.dgs.pt/pagina-de-entrada3/corona-virus/boletim-informativo.aspx

**Comment by gimbas** [comment]
data for portugal is not up to date in last update, as of 10/03/2020 00:30. the official source has data available

**Comment by CSSEGISandData** [comment]
Thank you for the source!

**Comment by gimbas** [comment]
The location of the reports was changed, here is and updated link.

https://www.dgs.pt/corona-virus/documentos/boletim-informativo.aspx

**Comment by abacao** [comment]
Information is out of date for Portugal. How can we make this more accurate?

**Comment by gimbas** [comment]
once again the location of the daily reports was changed, it's getting silly, but here is the new location:

https://covid19.min-saude.pt/relatorio-de-situacao/

**Comment by gimbas** [comment]
For anyone looking for real time data for Portugal, the DGS as made available a dashboard.

https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/

**Comment by andre-lx** [comment]
url for the arcgis dashboard: https://esriportugal.maps.arcgis.com/apps/opsdashboard/index.html#/acf023da9a0b4f9dbb2332c13f635829
