### ISSUE TITLE
Alabama county spike 9/16

### ISSUE THREAD

**Issue by Sylvain-Royer** [CSSEGISandData/COVID-19#3150]
This is related to this fix on 09/15. https://github.com/CSSEGISandData/COVID-19/pull/3130

It seems as though the spike among counties in Alabama on 9/16 due to deaths unassigned being assigned on that day. Is there a plan to smooth out and update old date with these cases or can we simply expect this spike on 9/16 to persist?

**Comment by runrun12** [comment]
Hello, @CSSEGISandData  has that information in the readme file. They put this: "We began distributing Alabama's probable cases to the county level (previously aggregated at the state level, in unassigned, AL). This resulted in significant increase in cases in nearly all counties. We are working to get the historical distribution of these probable cases from the State, and will update the timeseries accordingly when we do."
