### ISSUE TITLE
Some Countries have missing Death data

### ISSUE THREAD

**Issue by samscodes** [CSSEGISandData/COVID-19#3152]
Some Countries have missing Death data

**Comment by runrun12** [comment]
what countries and in what file?. Can you provide more detail, please?. Thanks

**Comment by CSSEGISandData** [comment]
I'm lead to assume that this is in response to our nullification of deaths in Rhode Island counties on the dashboard. We report deaths in the unassigned entry of Rhode Island as the county level data was not accessible for some time. We are working to integrate county level deaths.
