### ISSUE TITLE
Wisconsin time series mismatch with state dashboard 9/15 - 9/17

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3154]
Seeing differences between the Wisconsin dashboard and JHU time series.

**Cases**

On cases, the Wisconsin dashboard chart reports these totals:
https://www.dhs.wisconsin.gov/covid-19/cases.htm

9/15|9/16|9/17
-- | -- | --
91304 | 92712 | 94746

The total of Wisconsin counties in the JHU time series file has these:

9/15|9/16|9/17
-- | -- | --
91062 | 92159 | 93819

**Deaths**

The Wisconsin dashboard chart reports these totals:
https://www.dhs.wisconsin.gov/covid-19/deaths.htm

9/16|9/17
 -- | --
1228 | 1231

The total of Wisconsin counties in the JHU time series file has these:

9/16|9/17
 -- | --
1227 | 1230

**Comment by CSSEGISandData** [comment]
Thank you. This issue has been resolved.
