### ISSUE TITLE
Incidence rate?

### ISSUE THREAD

**Issue by thegreatcomet** [CSSEGISandData/COVID-19#3155]
I'm wondering if anybody knows how the incidence rate is calculated on this dataset. I know its cases per 100,000 people but it seems to be a cumulative measure (and not just new cases) and a moving 7 day average.

**Comment by pampi9** [comment]
In the EU, the official incidence rate is calculating with the additional cases per 100,000 people on the previous 14 days.

**Comment by CSSEGISandData** [comment]
Incidence Rate = cases per 100,000 persons.
For more info, please check the readme file: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data
Thanks!
