### ISSUE TITLE
Spike tests in Kentucky 

### ISSUE THREAD

**Issue by runrun12** [CSSEGISandData/COVID-19#3164]
Hello, could you explain why there is a really big spike in Kentucky’s tests?
Thanks

**Comment by CSSEGISandData** [comment]
The state reported these numbers for the number of tests. Please see the state's daily reports here: 
https://chfs.ky.gov/Pages/cvdaily.aspx?View=Sept.%20Daily%20Summaries&Title=Table%20Viewer%20Webpart

or

you can search for them here:

https://chfs.ky.gov/Pages/cvdaily.aspx.

[COVID19DailyReport0922_KY.pdf](https://github.com/CSSEGISandData/COVID-19/files/5285854/COVID19DailyReport0922_KY.pdf)
[COVID19DailyReport0923_KY.pdf](https://github.com/CSSEGISandData/COVID-19/files/5285855/COVID19DailyReport0923_KY.pdf)
