### ISSUE TITLE
Time series data seems to be having 0 cases for many counties since the 9/11 update

### ISSUE THREAD

**Issue by ahande123** [CSSEGISandData/COVID-19#3168]
![Kings_NY](https://user-images.githubusercontent.com/26362788/94343562-f539fa80-ffe6-11ea-8e2b-a9c7f4849647.png)
![Dallas_Texas](https://user-images.githubusercontent.com/26362788/94343564-f5d29100-ffe6-11ea-9d23-b956c55bf5c9.png)

I have included the screen shots for the data from Kings county in NY and Dallas, Texas.  You can see the data on the left as it stood on 9/11 after the 9/10 update and the data from last night's update on the right.  You will see that everything is 0 for these counties now,

NOTE: It is only case data that is missing. You can see that the Deaths data is fine for these counties.

I use Microsoft's Power BI software to pull in the data.

I haven't done a comprehensive analysis yet. A cursory glance shows missing data for many counties in TX and CA.

NY has missing data in Lewis and Kings country
TX has missing data in Andrews, Armstrong, Brewster, Carson, Cherokee, Cochran, Dallas etc. etc.

Can you please look into this.  This had happened sometime in Aug but then it was fixed a few days later.  But this time, it hasn't been fixed for 15 straight days.

**Comment by CSSEGISandData** [comment]
Hello

There has not been changes to these locations in the time frame you are indicating. Looking at both the daily reports and time series files, I see new cases being reported in Kings County, New York each day going back several months. What is the method you are using to pull in the data?

**Comment by ahande123** [comment]
Interesting.  I use Microsoft's Power BI Pro with its data import feature.  Thanks
    On Saturday, September 26, 2020, 06:38:20 PM EDT, CSSEGISandData <notifications@github.com> wrote:  
 
 


Hello

There have not been changes to these locations in the time frame you are indicating. Looking at both the daily reports and time series files, I see new cases being reported in Kings County, New York each day going back several months. What is the method you are using to pull in the data?

**Comment by ShubhankarRawat** [comment]
The same is reported in the case of India - confirmed cases in the global_confirmed.csv. The total number of cases on 21 Sept were reported to be 5562663 and the same figure was also observed on 22 Sept. Meaning the new cases on 22 Sept = 0 (which is not the case). 

I hope the issue will soon be resolved.

By the way, thanks for the dataset.

**Comment by CSSEGISandData** [comment]
@ahande123 it's likely the same data import mistake that had you raise issue #3147. Please check our raw data files before raising issues in the future.

@ShubhankarRawat this is related to the pinned issue #3135 regarding inconsistencies with India's source. I'll manually update the files now.

**Comment by ahande123** [comment]
OK,
I got to the bottom of it all.  Around 9/10 - 9/11 your LAT values in the Cases data changed.  There is a discrepancy between the LAT values in the Cases and Deaths raw data.  My PowerBI Join of the two tables were expecting identical values in both the LAT and LONG and this was throwing it off.
Thanks,Aravind Hande
CASES84036047,US,USA,840,36047.0,Kings,New York,US,40.636182500000004,-73.94935552,"Kings, New York, US",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,4,4,6,7,14,16,24,41,58,84,123,387,660,1334,1872,2765,3467,4167,4946,5701,6807,8045,9018,10029,11917,13115,14304,15700,17504,18558,19702,20879,22082,23394,24715,26243,27471,28404,29306,31969,33521,34705,35763,36482,37030,37694,38481,39354,40648,41660,42487,43014,43587,44236,44872,45519,46275,46839,47183,47579,47974,48550,48998,49461,49817,50072,50331,50667,51095,51581,51991,52298,52485,52681,52889,53385,53639,53902,54175,54360,54560,54779,55147,55446,55727,55900,56053,56242,56405,56587,56770,56966,57131,57260,57367,57484,57605,57733,57919,58059,58177,58274,58386,58502,58634,58761,58874,58949,59047,59111,59206,59311,59420,59507,59576,59650,59742,59855,59957,60078,60149,60211,60281,60386,60461,60560,60647,60748,60815,60904,61012,61124,61233,61351,61432,61488,61568,61662,61752,61824,61926,61988,62053,62110,62194,62295,62385,62494,62577,62641,62715,62790,62890,62999,63086,63155,63223,63308,63410,63542,63636,63779,63861,63913,64002,64082,64162,64236,64301,64375,64422,64495,64572,64664,64754,64857,64930,64998,65118,65201,65328,65440,65540,65626,65700,65757,65819,65929,66009,66124,66197,66274,66381,66468,66586,66737,66971,67136,67227,67391,67510,67717,67892,68095
84036049,US,USA,840,36049.0,Lewis,New York,US,43.784415700000004,-75.44903992,"Lewis, New York, US",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,3,6,6,6,6,6,6,6,6,7,7,8,8,8,8,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,10,10,11,11,11,11,11,12,12,13,16,17,18,18,18,19,19,19,19,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,21,21,21,22,23,23,24,24,25,26,26,29,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,32,32,32,32,32,33,33,33,33,34,34,34,34,34,34,34,34,34,34,35,35,37,37,39,39,41,41,41,45,46,47,47,47,47,47,47,47,47,47,47,47,47,47,48,48,48,48,49,49,49,49,49,49,49,49,49,49,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50DEATHS84036047,US,USA,840,36047.0,Kings,New York,US,40.6361825,-73.94935552,"Kings, New York, US",2559903,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,2,6,12,18,29,41,51,78,101,137,187,262,340,430,536,662,798,966,1107,1270,1437,1606,1785,1958,2148,2326,2486,2686,2845,2998,3129,3255,3373,3490,3608,3703,3794,3902,4008,4101,4177,4238,4326,4383,4455,4521,4576,4622,4668,4710,4759,4797,4842,4885,4913,4939,4971,5004,5027,5041,5067,5091,5110,6663,6685,6721,6753,6771,6799,6817,6834,6843,6854,6870,6893,6909,6926,6942,6952,6970,6984,6991,7004,7012,7025,7032,7046,7050,7058,7064,7076,7081,7086,7095,7100,7106,7112,7120,7126,7135,7140,7144,7147,7158,7160,7165,7120,7126,7129,7137,7143,7147,7151,7156,7163,7169,7173,7176,7180,7182,7186,7190,7193,7195,7201,7205,7209,7213,7214,7221,7223,7226,7229,7231,7232,7233,7235,7237,7240,7242,7242,7244,7244,7250,7247,7250,7250,7252,7253,7253,7255,7256,7258,7259,7261,7262,7263,7266,7266,7268,7269,7270,7270,7271,7272,7273,7274,7276,7290,7290,7290,7289,7290,7293,7293,7297,7298,7298,7299,7299,7306,7306,7306,7309,7311,7312,7314,7315,7318,7318,7319,7319,7321,7323,7323
84036049,US,USA,840,36049.0,Lewis,New York,US,43.7844157,-75.44903992,"Lewis, New York, US",26296,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0



    On Sunday, September 27, 2020, 07:30:24 AM EDT, CSSEGISandData <notifications@github.com> wrote:  
 
 


@ahande123 it's likely the same data import mistake that had you raise issue #3147. Please check our raw data files before raising issues in the future.

@ShubhankarRawat this is related to the pinned issue #3135 regarding inconsistencies with India's source. I'll manually update the files now.
