### ISSUE TITLE
Increase in case count for North Carolina

### ISSUE THREAD

**Issue by bms44974** [CSSEGISandData/COVID-19#3169]
As of 25Sep20, [North Carolina is now including antigen test results in their count of COVID-19 cases](https://covid19.ncdhhs.gov/dashboard). They added 4,563 new cases 25Sep20 due to the cumulative antigen testing. New PCR-based cases for yesterday were  1,590.

Cheers... Brian

**Comment by CSSEGISandData** [comment]
Hi Brian,

Thanks for bringing this to our attention. The state website appears to contain the data we need to backfill our time series files. It might be programmatically difficult to access but it will be a work in progress. I'll leave this issue open until we are able to push a fix.

**Comment by bms44974** [comment]
Thank you for your continuing efforts to make these data accessible!

**Comment by CSSEGISandData** [comment]
Issue #3183 closes this issue.
