### ISSUE TITLE
Time Series missing today's update Mar 8

### ISSUE THREAD

**Issue by hishak** [CSSEGISandData/COVID-19#317]
Timestamp shows 3 files under time series updated.  Don't see update for Mar 8.

**Comment by marshallstanton** [comment]
Very frustrating.  A similar problem happened yesterday.

**Comment by arik-so** [comment]
Latest data would be most appreciated! My public visualization tool depends on it.

**Comment by jonasmrfranca** [comment]
Actually so far there’s no column for March, 8th. :/

@marshallstanton yesterday was a column called “3/7/20” empty. Few minutes later they updated it.

Let’s wait for it! 🙏🏻

**Comment by tranquyphi** [comment]
Time Series files have been updated 2 hours ago but there is no data for yesterday 03-08 !!!????

**Comment by CSSEGISandData** [comment]
Sorry for the delay. The time series tables are now updated.
