### ISSUE TITLE
Alabama Case Counts Include Confirmed + Probable Starting 9/16/2020

### ISSUE THREAD

**Issue by kwittarcgov** [CSSEGISandData/COVID-19#3179]
There was a major increase in the number of new cases for the counties and therefore the state total of Alabama on 9/16/2020. It appears that Alabama began reporting confirmed and probable cases on approximately 5/30/2020 but the JHU dashboard did not report the combined figure until 9/16/2020, resulting in a single-day increase of 14,274 new cases in Alabama. Please see these references, https://bamatracker.com/chart/cases, https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7, and look for the large jump in cases for counties such as Lee County and Tuscaloosa County, both in Alabama, on 9/16/2020 in the JHU dashboard charts. Can JHU please update the data so the Alabama counties include both confirmed and probable cases for the entire time series?

**Comment by CSSEGISandData** [comment]
Hello

This reporting change is documented in the README of the csse_covid_19_data folder. We've been in touch with the state health department and they are preparing a document for us with the collection dates for the prior probable cases. The time series will be updated once we have been provided the data.
