### ISSUE TITLE
Upcoming changes to daily reports headings

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#3182]
Hello all,

Soont, there will be several changes to some of the column names in the daily report to more accurately reflect the information provided or standardize the formatting. We recognize this may break some code, which is why we are posting this issue as a bit of a head's up. These are the changes:

Incidence_Rate --> Incident_Rate
Case-Fatality_Ratio --> Case_Fatality_Ratio
Mortality_Rate ---> Case_Fatality_Ratio
People_Tested ---> Total_Test_Results

Apologies if this causes some of your scripts to freak out, but we believe that this is a better way forward.

The changes will take place in early November.

EDIT: The changes went live on the November 9 product generation. Thank you for your patience.

**Comment by runrun12** [comment]
Hello, thank you for the update. Incidence_Rate never existed. Do you mean that Incident_Rate (before) is going to change to Incidence_Rate?. Could you say when these changes will be applied?. Thanks

**Comment by pampi9** [comment]
How is the incidence rate calculated? (14 days and 100,000 people)

**Comment by d76d30dbl** [comment]
Concerning the name change of:

People_Tested ---> Total_Test_Results

Is this because this field has always been a count of tests and not a count of unique people tested ?

if so, please remove the ambiguity in the definition: "People_Tested - Total number of people who have been tested"
  
thank you
