### ISSUE TITLE
Argentina confirmed death

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#3186]
On October 01, Argentina confirmed death has increased sharply from 16937 to 20288. Is there any reason for this sharp increase?

**Comment by CSSEGISandData** [comment]
Hello

Per [this official report](https://www.argentina.gob.ar/sites/default/files/01-10-20-reporte-vespertino-covid-19.pdf), it appears to be due to the release of 3050 previously unidentified deaths in Buenos Aires. We will add a note to our README section.
