### ISSUE TITLE
Problem with North Carolina data today (Friday Oct 2, 2020) - for Oct 1, 2020 data

### ISSUE THREAD

**Issue by johncdavis200** [CSSEGISandData/COVID-19#3187]
I saw the post  https://github.com/CSSEGISandData/COVID-19/issues/3183 about backloading the North Carolina Antigen test results. 

However the data for Wake County and Union County seems to have been mixed up with the update.  There may be errors in other counties - but I see that the Wake County data is in the Union County row up until Oct 1, and the Wake County data is extremely low until the last day (Oct 1).

I compared your data with data from USAFacts and have confirmed the problem with the JH data.

**Comment by lojic** [comment]
Agreed, here are the last few days of case counts for Wake County, NC:

`208,208,208,208,210,212,212,17878`

That last value seems excessive to say the least.

**Comment by lojic** [comment]
Sorry, it appears the previous values are simply too low. [NC DHHS has the total value for Wake County at 18,014](https://covid19.ncdhhs.gov/dashboard/cases).

**Comment by johncdavis200** [comment]
It is worse than that... if you look at the numbers for Union County - they are WAY too high - and comparing them column by column - it appears to me that the Wake County numbers from January to October are listed for Union county and some other county's numbers are listed for Wake County up to the Oct 1 number.

Looking at the deltas for counties in NC from Sept 29 to Oct 1 - I see the following that are obviously not correct:

Wake County           +17,666 new cases
Union County          -12,813 new cases
Richmond County      -3,575 new cases 
Rutherford County        -994 new cases

Others are not as obvious - but I believe that there is a major malfunction with whatever update was done to the NC data to back-post the antigen testing results.

**Comment by yarrington88** [comment]
It appears that all the data preceding Oct 1. for each of the counties are shifted by 1 (alphabetically) after 'out of state, NC' and then by two after 'unassigned, NC'.   The counties starting with 'A' through 'O' seem correct.

**Comment by johncdavis200** [comment]
Thanks - glad that you figured that out - I had not dug in that far.  Is this issue visible to the folks who maintain the data? Will it be fixed ASAP?  I've got a bunch of reports that use this data and I'm in NC, so this is visible.

**Comment by CSSEGISandData** [comment]
@johncdavis200 @yarrington88 @lojic working through a patch now - Yarrington's intuition is correct

**Comment by johncdavis200** [comment]
Fantastic! That's great!  Thanks for the quick response...

**Comment by CSSEGISandData** [comment]
Push fixed, terribly sorry for the trouble.

**Comment by DavidViral** [comment]
![NC 10-6](https://user-images.githubusercontent.com/62083925/95203412-b9562080-07b0-11eb-8ecd-af2dc8584b06.PNG)

The data looks wonky since Sept. 30.  I did find this statement this morning on the NC Dashboard:

"On October 4, NCDHHS experienced technical issues which prevented some laboratory data files from being processed in the NC COVID reporting system. As a result, cases and test data are lower for October 4 than they would have been had all data been processed. Data reported on October 5 will be higher as it will incorporate cases that were intended to be submitted on October 4. NCDHHS is working to resolve the issue" 

The problem seems more systemic than the October 4th report.

**Comment by johncdavis200** [comment]
The longer I look at this data (I mean all the daily numbers coming in from across the country) - the more the term "wonky" seems to apply to much of the data.  Sometimes it feels like there is a random number generator behind the data...

No negative intent with this statement to the great folks at JH who have done yoepersons work compiling and publishing this data!  You all have done a fantastic job!!

**Comment by DavidViral** [comment]
> 
> 
> The longer I look at this data (I mean all the daily numbers coming in from across the country) - the more the term "wonky" seems to apply to much of the data. Sometimes it feels like there is a random number generator behind the data...
> 
> No negative intent with this statement to the great folks at JH who have done yoepersons work compiling and publishing this data! You all have done a fantastic job!!


Keeping these states in line must be like herding cats.
