### ISSUE TITLE
Kansas case data shows large 2.1K case increase for 10/6

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#3208]
There is a large spike of 2,107 new cases reported statewide for Kansas yesterday, 10/6. The state was averaging about 500-600 new cases per day prior to yesterday. Curious if there might be an issue with these figures, a reporting change, etc. Thanks.

**Comment by Marcbrig** [comment]
Yes, I was about to report the same issue.  Also, the KS Department of Health website only has a total of 62,708 cases compared to 63,938 reported here.

**Comment by eolson3260** [comment]
The Kansas DoH site was last updated on 10/5 at 9am, so they have yet to post yesterday's new case count.   https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas

**Comment by Marcbrig** [comment]
Yes, I realized that, but still doesn't explain why there is so many new cases added today.  are you still looking into that?

**Comment by CSSEGISandData** [comment]
Thank you for your issue. We are currently looking into the issue.

**Comment by CSSEGISandData** [comment]
Issue has been resolved in the daily report and time series data.
