### ISSUE TITLE
Don't default to '0 Total deaths' in case of `No Data` errors

### ISSUE THREAD

**Issue by roshni-b** [CSSEGISandData/COVID-19#321]
Ran into a `no data` error for a couple minutes specifically for Italy and Iran but soon appeared to be back to the correct numbers. Would be better if this error would default to any other placeholder text, especially in the Total Deaths field.
<img width="186" alt="Screen Shot 2020-03-08 at 8 40 32 PM" src="https://user-images.githubusercontent.com/7680686/76174350-3074f900-617d-11ea-880b-bf8f2c5f98ce.png">

Otherwise, Thank You so much for making this!

**Comment by CSSEGISandData** [comment]
For any dashboard related issues that have not been addressed by us in the read me page or issues page of this repository please try clearing your browser cache and refresh the dashboard.
