### ISSUE TITLE
Spain Data

### ISSUE THREAD

**Issue by AlexanderRahn** [CSSEGISandData/COVID-19#3212]
I just noticed that due to the "time_series_covid19_confirmed_global" CSV file since the third of July there is no case movement in Spain at the weekent - is it supposed to be like that?

**Comment by jeremydratcliff** [comment]
Hello

Yes, Spain has stopped providing updates on the weekend. There are several countries and regions that are no longer updating with regularity, we are documenting them in the section "Irregular Update Schedules" of the README file in COVID-19/csse_covid_19_data/.

**Comment by CSSEGISandData** [comment]
Hello

Yes, Spain has stopped providing updates on the weekend. There are several countries and regions that are no longer updating with regularity, we are documenting them in the section "Irregular Update Schedules" of the README file in COVID-19/csse_covid_19_data/.
