### ISSUE TITLE
Backlogged cases added in Fayette County Kentucky

### ISSUE THREAD

**Issue by bms44974** [CSSEGISandData/COVID-19#3213]
The [Kentucky DPH reported 2,398 new cases 07Oct20](https://chfs.ky.gov/agencies/dph/covid19/COVID19DailyReport.pdf), 1,472 of which came from a backlog of reports from one jurisdiction, likely Fayette County. Does KY provide enough detail to back-fill these cases?

Thanks... Brian

**Comment by CSSEGISandData** [comment]
Hi Brian,

We've documented the backlog of reports to our README section, but it does not appear that there is a back distribution currently available. Based on this [county announcement](https://www.facebook.com/LFCHD/posts/10159412744354739), it appears that the county actually has 1900ish cases that are being reported out of date. We will continue to track the state website to see if they provide the correct distribution in the future.

**Comment by bms44974** [comment]
Thanks for all of your hard work to keep us informed!
