### ISSUE TITLE
Rhode Island deaths went from 1,130 to 115

### ISSUE THREAD

**Issue by richardkazuomiller** [CSSEGISandData/COVID-19#3227]
This looks like an error, unless it was a very large correction to past data

https://github.com/CSSEGISandData/COVID-19/commit/b05360cef11048da3d64c689f883b69829ad5c9a#diff-cfc896f668af28c0d72baead17327a580707f3696b28016041465819c48b6467L522

**Comment by CSSEGISandData** [comment]
Thank you for your post. We are currently fixing the technical issue.
