### ISSUE TITLE
Missouri State Dashboard has not updated since October 10

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#3231]
Hello all,

The Missouri State Dashboard is currently down and therefore our data has not updated since October 10.

Here is [a link to their site](https://showmestrong.mo.gov/data/public-health/). [Here is a news article](https://www.ky3.com/2020/10/12/missouri-agency-working-to-fix-states-covid-19-dashboard/) describing the issue. The article states that the Health Department expects the dashboard to be online tomorrow (Wednesday) morning.

**Comment by NaKo91** [comment]
Despite the Missouri State Dashboard didn't provide new case numbers on October 12 and 13, the JHU dashboard shows 216 and 205 new cases on those days. I'd like to ask where you got these numbers from, particularly as they appear unexpectedly low.

**Comment by anthonydb** [comment]
Also @CSSEGISandData, can you clarify the discrepancy between the 150,794 cumulative cases you're reporting for Missouri as of 10/14 vs. the 148,679 on the state's dashboard? Do they reflect two different days? Thanks.

**Comment by wellsangels** [comment]
It looks like the Department of Health has resolved the database issue. Is it possible to update the JHU time series?

https://twitter.com/HealthyLivingMo/status/1316516288957734912

**Comment by CSSEGISandData** [comment]
@NaKo91 and @anthonydb the discrepancy is because we source St. Louis City, St. Louis County, and Nodaway County directly from the jurisdiction's website while the rest of the state is sourced from the state website (which was stale). The new cases reported on our dashboard relative to the state were cases in those jurisdictions.

@wellsangels thank you for the notification. We will look into pulling this data in as soon as possible.
