### ISSUE TITLE
Sitka Borough, Alaska, not being reported

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#3236]
Sitka is both a borough and a city in Alaska. Other boroughs are getting reported as they get cases, presumably as a feed from here:
https://coronavirus-response-alaska-dhss.hub.arcgis.com/datasets/table-2b-geographic-distribution-of-cases-by-report-date/data

This data set doesn't include entries for Sitka as a zero-case county because they haven't had one.

**Comment by CSSEGISandData** [comment]
Hello,

I'm sorry, can you be more specific with your question? Our Sitka, Alaska entry includes cases in both the city and the borough, as all of our Alaska reporting is at the borough level.
