### ISSUE TITLE
Why are dates not in an ISO or other standard format?

### ISSUE THREAD

**Issue by hellznrg** [CSSEGISandData/COVID-19#3247]
Why are dates not in an ISO or other standard format?

**Comment by bobromeo** [comment]
At the beginning there were sometimes changes in record-layout and about dates, there was a an american mindset :)
But in my opinion, i wouldn't like more changes.
You could consider closing this issue.

**Comment by hellznrg** [comment]
Well it's a good thing python defaults to parsing US dates (mdy) so this didn't turn out to be a huge problem after all.
