### ISSUE TITLE
Date contains year 2002 instead of 2020

### ISSUE THREAD

**Issue by rolkra** [CSSEGISandData/COVID-19#3248]
Confirmed Cases time series contain variable date with values 2002-10-10 to 2002-10-17. I guess it should be 2020-10-10 to 2020-10-17!
Same with time series deaths and recovered

**Comment by CSSEGISandData** [comment]
Hello

Can you be more specific with which files you are experiencing this issue? The header rows for all six time series files do not contain this described problem. The time series files are csvs, so the entries don't contain any specific data type until they are read in by whichever software you are using.

**Comment by rolkra** [comment]
Sorry, it was a problem during csv import. The raw data does not contain year 2002.
