### ISSUE TITLE
Spokane County, WA 03-08-2020 erroneous report

### ISSUE THREAD

**Issue by jankyupeblik** [CSSEGISandData/COVID-19#325]
For the moment the Confirmed case for Spokane County, WA appears to have been made erroneously.

https://www.khq.com/coronavirus/coronavirus-confusion-state-health-dept-somehow-misreports-positive-coronavirus-in/article_7aedf854-6189-11ea-9829-1b4b2ec15f87.html  
https://www.spokesman.com/stories/2020/mar/08/first-coronavirus-case-confirmed-in-spokane-county/  
https://www.doh.wa.gov/emergencies/coronavirus

**Comment by CSSEGISandData** [comment]
please see issue #382
