### ISSUE TITLE
Bristol Bay Reporting Zero Cases as of Daily Report 10-19-2020

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [CSSEGISandData/COVID-19#3256]
A couple of days ago JHU introduced some changes in 53233d1f22eefa15a9b9d92780dd6d311087d917 to their Lookup Table pertaining to the Bristol Bay area (Alaska, USA). The changes renamed Bristol Bay plus Lake Peninsula to Bristol Bay (FIPS: 02060) and Lake and Peninsula to Bristol Bay plus Lake and Peninsula (FIPS: 02164). 

Daily reports starting on 10-19-2020 have started reporting 0 cases (confirmed, deaths, etc) for Bristol Bay (down from 10 confirmed cases on 10-18-2020). Confirmed cases appear to have been reassigned from Bristol Bay (FIPS 02060) to Bristol Bay plus Lake and Peninsula (FIPS 02164). Is there a reason for the change to reporting and is their a reason for continuing to include Bristol Bay (FIPS 02060), if cases are no longer being assigned to it?

**Comment by CSSEGISandData** [comment]
Hello! To match up with the Alaska DHSS report, we recently aggregated cases in "Bristol Bay" and "Lake Peninsula" into "Bristol Bay plus Lake Peninsula to Bristol Bay" with the same FIPS as "Lake Peninsula." We also updated the time series tables for Alaska to reflect this change over time. Thanks!
