### ISSUE TITLE
Data for India 2020-10-20.csv

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#3257]
I believe that the 2020-10-20.csv data for ALL reporting Indian States and Territories is the same as that in the 2020-10-19.csv report.  Can you verify.

Thanks for all your work.

Rowan

[India_2020-10-20.zip](https://github.com/CSSEGISandData/COVID-19/files/5420179/India_2020-10-20.zip)

**Comment by CSSEGISandData** [comment]
Hello

This is addressed in the pinned issue #3135. Typically, we able to push the Automated Update for Delayed Data around 4 AM EST.
