### ISSUE TITLE
California Backlog Data Lumped into 10/22-10-23

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3267]
Estimated 2000+ cases from LA county were lumped into one or two days of data - more expected according to the California Dashboard.

![Notice](https://user-images.githubusercontent.com/62083925/97099815-aa51e800-1663-11eb-9954-2124c270f25d.PNG)

https://public.tableau.com/views/COVID-19CasesDashboard_15931020425010/Cases?%3Aembed=y&%3AshowVizHome=no

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We will add this to our README and reference this issue.
