### ISSUE TITLE
Hoonah-Angoon, Alaska has no data for 10/26/20

### ISSUE THREAD

**Issue by thanatos** [CSSEGISandData/COVID-19#3275]
Hi,

I run a post-processor over the JHU data. It presently assumes that the values in the date columns in the US confirmed cases timeseries data are integers. However, Hoonah-Angoon presently has the empty string in the final column, currently 10/26/20.

Presently, I am looking at [this version of the data](https://github.com/CSSEGISandData/COVID-19/blob/3a1f0e85589489f440166c67bbc47b3a5188c8e6/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv), which is currently the version pointed to by `master`.

One way to see this is,
```
<csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv awk 'NR==1 || NR==81 { print $0 }' | xsv table | less -S
```
(this requires the very wonderful [`xsv` utility from BurntSushi](https://github.com/BurntSushi/xsv).)
Then, scroll all the way right:
```
10/23/20  10/24/20  10/25/20  10/26/20
0         0         0         
```
I've been post-processing for some number of months, and this is the first occurrence of this.

**Comment by CSSEGISandData** [comment]
Hello @thanatos! Thanks for your reminder. We just added that missing value for Hoonah-Angoon.

**Comment by thanatos** [comment]
Wow, that was quick! Thank you!
