### ISSUE TITLE
FLORIDA NEW TEST. Huge difference

### ISSUE THREAD

**Issue by runrun12** [CSSEGISandData/COVID-19#3277]
Hello, any explanation for the huge spike in the new tests in Florida?. The difference is huge.
Florida has an average of 35.066 daily test and today tests are 562.220
Thanks

**Comment by DavidViral** [comment]
"Florida changes the way it reports COVID-19 data to focus on daily numbers, not long term testing"

https://www.clickorlando.com/news/local/2020/10/27/florida-changes-the-way-it-reports-covid-19-data-to-focus-on-daily-numbers-not-long-term-testing/

Covid Tracking Project shows about 56K for 10-28 i.e. positive + negative tests.
