### ISSUE TITLE
Create ‘latest.csv’ on update

### ISSUE THREAD

**Issue by scottmcdaniel** [CSSEGISandData/COVID-19#328]
Instead of ‘03-08-2020.csv’, name each new iteration ‘latest.csv’ for purposes of automation. The name can then be modified to the date format when updated/replaced/archived.

**Comment by Bost** [comment]
No! That would be yet another "format" breaking change.

In theory:
- a simlink `latest.cs -> 03-08-2020.csv` could be created, but that won't work on Windows AFAIR or,
- `latest.cs` and `03-08-2020.csv` could be identical copies. But that would confuse a too many people - notably the guys committing the files, in the first place.

NACK.

**Comment by Bost** [comment]
#238

**Comment by scottmcdaniel** [comment]
I think this is a fair critique. My thought was that for applications using only webhooks (i.e. not downloading to a server), being able to link to `https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/latest.csv` would be very useful.

If I can think of a way to automate this, I'll post it.

**Comment by scottmcdaniel** [comment]
In retrospect, I think that perhaps using the `csse_covid_19_time_series` files may be a better solution. This provides flexibility in time tracking as well as monitoring growth and of course, having a static path.

**Comment by CSSEGISandData** [comment]
To be consistent with the processes we have in place, each daily push will be labeled with the current date in EST 'mm-dd-YYYY' followed by '.csv'
