### ISSUE TITLE
No entry for Colombia deaths 28/10/2020

### ISSUE THREAD

**Issue by spendiff** [CSSEGISandData/COVID-19#3280]
The entry for deaths in Colombia is for 28/10/2020 is currently blank

**Comment by QuinHsieh** [comment]
I have the same problem, too.

**Comment by CSSEGISandData** [comment]
Hello,

Apologies. This issue has just been manually adjusted. We will look into the mechanism through which this appeared today.

**Comment by spendiff** [comment]
thanks!
