### ISSUE TITLE
Corrupted FIPS codes in U.S. deaths, U.S. confirmed files

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#3282]
The U.S. deaths and U.S. confirmed files in the Github repo have a corrupted FIPS field that's being processed as a floating point instead of as a string:
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv

For example, Autauga County, Alabama, has a FIPS code of 01001. Here it's showing as 1001.0.

**Comment by CSSEGISandData** [comment]
#3284
