### ISSUE TITLE
Franklin County, VA zeros then spike

### ISSUE THREAD

**Issue by tkcy** [CSSEGISandData/COVID-19#3285]
Hi! I just noticed Franklin County, VA (FIPS  51067 ) shows zero reported cases for over a month, followed by a huge spike on 10/28.  

USAfacts appears to have a (more) correct time series.  

Thanks!

Teresa

**Comment by CSSEGISandData** [comment]
Hello

This is a consequence of an internal mapping error we discovered on October 28 (hence the spike in cases). Cases from Franklin City, VA had been tallied for Franklin County, VA and then the Franklin City source went stale. This morning, we updated our historic daily reports and the time series files to fix this issue.
