### ISSUE TITLE
Official Belgian source

### ISSUE THREAD

**Issue by wolfman87** [CSSEGISandData/COVID-19#3286]
I was surprised to find out that this collection does not have Belgian data at a sub-national level. Belgium probides very detailed data via Sciensano, the Belgian institute for health under https://epistat.wiv-isp.be/covid/
Could you integrate this into your data set?

**Comment by CSSEGISandData** [comment]
Hello! We are now internally testing Belgium subnational data, and will make it available soon. Stay tuned!
