### ISSUE TITLE
Data entry error. COLOMBIA, 10/30/20.

### ISSUE THREAD

**Issue by coder-amey** [CSSEGISandData/COVID-19#3292]
A data entry error of one order of magnitude appears to have occurred in the RECOVERED cases.

Where: time_series_covid19_recovered_global.csv
What: Tally for COLOMBIA
When: 10/30/20

Description: The recovered cases appear to have decreased because the entered value (95870) is smaller than the previous value (950348) by one order of magnitude and clearly appears to be a data-entry error.

**Comment by sapienzafra** [comment]
Thank you, I was struggling to find the error! Colombia gave an issue also on yesterday's datas :)

**Comment by CSSEGISandData** [comment]
Thanks for bringing this to our attention. It has been updated.
