### ISSUE TITLE
Iceland wrong recovered data

### ISSUE THREAD

**Issue by Flower7C3** [CSSEGISandData/COVID-19#3295]
Today (https://github.com/CSSEGISandData/COVID-19/commit/5d19cc7dcbd23744226be3fa701d53abf28ed933) Iceland has 4890 confirmed cases, 4890 recovered cases and 12 deaths. So there is -12 active cases, which is wrong.

**Comment by CSSEGISandData** [comment]
Hello

We are investigating and will hopefully a fix deployed soon. Thank you for your patience.

**Comment by CSSEGISandData** [comment]
Historical data has been adjusted, live data should be adjusted shortly.

**Comment by Flower7C3** [comment]
I can see that it is corrected in https://github.com/CSSEGISandData/COVID-19/pull/3304 on branch [master](https://github.com/CSSEGISandData/COVID-19/commits/master) (commit f26a1a6c5b85b559c38e75cf92131c7c05938b59). But there is still no updates in branch [web-data](https://github.com/CSSEGISandData/COVID-19/commits/web-data).
