### ISSUE TITLE
Differences in recoveries USA!

### ISSUE THREAD

**Issue by wimvincken** [CSSEGISandData/COVID-19#3296]
We're talking about millions of differences per day!
The csv files report for example 25,569 recoveries. The site worldometers.info report about the double of that number (6,062,438)! That happens each day.
And that only happens with the USA (as far as I can see).

**Comment by wimvincken** [comment]
I see similar with the data from Brazil, but here it's the cases.
And when it's also Brazil, it's likely that it's the case with other countries too.

The problem is not only at wordometers, but at coronavirus.1point3acres.com too. They use the same numbers (i.e. 5,581,417 for today. In your data that value will be in the 3 million. A difference of about 2 million reported per day!

**Comment by CSSEGISandData** [comment]
Hello

Our recoveries data for the United States is sourced from CovidTrackingProject. We do not know the source used by WorldoMeter and therefore cannot comment on the mechanism behind the differences.
