### ISSUE TITLE
Illinois zeros for 10/31 -- redistribute from 11/1

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3298]
Cases and deaths for Illinois appear as 0 in your time series for 10/31, but the 11/1 totals seem to catch up by including totals for both days. Can you back-distribute the data so our calculated seven- and 14-day averages can be accurate.

Press releases:
Sat
http://www.dph.illinois.gov/news/public-health-officials-announce-7899-new-confirmed-cases-coronavirus-disease
Sun
http://www.dph.illinois.gov/news/public-health-officials-announce-6980-new-confirmed-cases-coronavirus-disease

**Comment by CSSEGISandData** [comment]
Thank you...the data has been back-distributed.
