### ISSUE TITLE
Antigen tests & probable cases

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3300]
My question concerns your case count for Denton County, Texas:

![Unbenannt](https://user-images.githubusercontent.com/66752944/97945743-b38c3480-1d88-11eb-81a8-862d473c316f.JPG)

I know that some states include positive antigen tests in their "probable cases" figures.
Since you have not included antigen cases for Denton County, I wonder if there is any official or inofficial guidline about the implementation/exclusion of positive antigen tests in your data.
I would be glad about an answer. 
Thank you :)

**Comment by NaKo91** [comment]
Update: Georgia just added roughly 30.000 "Antigen positive cases" to its dashboard. 
They also report daily numbers for this kind of cases now.

With regards to my previous question, I found this on the CDC website: 
"Antigen tests may be used for screening or diagnostic purposes. Positive test results for COVID-19 antigen are considered a probable case as outlined in the CSTE position statement, and might not be confirmed using FDA authorized RT-PCR tests for COVID-19."

I don't understand why you're not reporting such cases. I would be happy if you could give a brief explanation.                                 
Thank you.

**Comment by CSSEGISandData** [comment]
Thank you for your postings. We have documented these locations and are in the process of reporting these probable cases.
