### ISSUE TITLE
Lander County Nevada death total shows 66 instead of 4

### ISSUE THREAD

**Issue by rokhopr** [CSSEGISandData/COVID-19#3303]
Lander County Nevada deaths show 66 and should be 4.  Resulting in the state total being too high and Lander county calculating as the highest per capita death rate in the US.

Further, JHU data for Lander county shows 2 deaths as of Oct 22nd then zeros for Oct 23rd - Nov 1st, then pops up to 66.

Nevada state site shows 4:  https://nvhealthresponse.nv.gov/ "Statistics By County" tab

Thank you.

**Comment by CSSEGISandData** [comment]
Hello

Thank you for bringing this to our attention. We're working on a fix at the moment and hope to have it deployed shortly. I will overwrite the time series files and daily report to remove this issue.
