### ISSUE TITLE
garbage line at end of file?

### ISSUE THREAD

**Issue by greg-minshall** [CSSEGISandData/COVID-19#3309]
hi.  for months i've been meaning to leave some form of comment to laud you all for the great job you've done providing this data (which i've been a consumer of since 04 March).  and, how the quality of the data, spotty at first, became so solid.  i assume because the team learned "how to do it", and maybe also imported some expertise from outside.  but, whatever.

today.  a problem.  there appears to be a spurious line at the end of the 11-03-2020.csv file.  removing it wouldn't be a bad idea.

again, thanks so much!

https://github.com/CSSEGISandData/COVID-19/blob/b8c8738470c4db7fadfc56442130ed26a1bffae8/csse_covid_19_data/csse_covid_19_daily_reports/11-03-2020.csv#L3961

**Comment by CSSEGISandData** [comment]
Hello

We've removed this. Not sure why it happened, but we are investigating. We learned how to do it, by the way.

**Comment by greg-minshall** [comment]
good job.  times two!!

**Comment by greg-minshall** [comment]
(sadly, a "good job", even "times two", even from me, doesn't put much money in the bank.  but... :)

**Comment by RobAtticus** [comment]
@CSSEGISandData This line is back with the recent update for 11-04
