### ISSUE TITLE
Death number is wrong for Japan

### ISSUE THREAD

**Issue by hikarine3** [CSSEGISandData/COVID-19#331]
I don't know from where the data came but death number 17 is not the number of Japan (Spain's one?)
![Coronavirus COVID-19  2019-nCoV  (2)](https://user-images.githubusercontent.com/197538/76200405-ed765c80-6234-11ea-8d16-43e85cbbc7b8.png)

**Comment by JiPiBi** [comment]
From time to time , I agree that there are some differences between official values known locally and the dataset . (As the picture is taken at a certain moment of the day which could be different for different countries , it could be difficult to compare data)
In my opinion, except for huge anomalies, more important are  the trends and compared ratio to see how the different countries manage the covid issues.

**Comment by hikarine3** [comment]
I mean, 
Latest official data from 
Data sources: WHO, CDC, ECDC, NHC and DXY
are 7 deaths.

Locally known latest death number is 
+2 today until now, which means 9 deaths.

https://twitter.com/search?f=tweets&vertical=default&q=%20%E6%AD%BB%E8%80%85%209%E4%BA%BA%20%E6%97%A5%E6%9C%AC&src=typd
![9 dead Japan-Twitter Search](https://user-images.githubusercontent.com/197538/76205979-9b3a3900-623e-11ea-92a1-972b24ca67c7.png)

https://jagjapan.maps.arcgis.com/apps/opsdashboard/index.html#/55c22ee976bc42338cb454765a6edf6b
![Coronavirus COVID-19 Japan Case  2019-nCoV  - English (1)](https://user-images.githubusercontent.com/197538/76206150-d9375d00-623e-11ea-808e-b5a49f3326a9.png)

So I wonder from where this wrong data "17 deaths" for Japan came.

**Comment by hikarine3** [comment]
By new update, the death number becomes correct.
![Coronavirus COVID-19  2019-nCoV  (4)](https://user-images.githubusercontent.com/197538/76280986-0cc5c600-62d7-11ea-83d0-24edf2f07ca0.png)

I wonder how the wrong data can come but anyway thanks for correction by data update.
