### ISSUE TITLE
Unusual spike in Iowa data

### ISSUE THREAD

**Issue by wellsangels** [CSSEGISandData/COVID-19#3316]
Iowa's total cases jumped almost 4% overnight - wondering if there are any backlog issues there. It looks like a few counties reported an unusually high number of cases on Thursday: Jones, Scott and Cerro Gordo, for example.

**Comment by CSSEGISandData** [comment]
Hello

Spikes appear to be genuine increases in cases in these counties. Here is an example:
[Jones County](https://www.thegazette.com/subject/news/health/jones-county-covid-19-numbers-almost-double-in-two-days-20201106)

We are unable to find any announcement on data backlogs or retrospective reporting that explain these jumps.
