### ISSUE TITLE
Tunisia Recovery Cases Sudden Increase on Nov 5

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#3317]
Hello, recovery cases for Tunisia have raise to 36727. It is big big jump comparing to previous date data 5032. I tired to search the reason but could not find anything. Can you confirm the validity of this data?

**Comment by CSSEGISandData** [comment]
Hello

Here is a post from the Tunisian Ministry of Health: https://www.facebook.com/santetunisie.rns.tn/posts/3595648773807534

Thank you
