### ISSUE TITLE
Georgia probable cases and deaths 

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3318]
Unfortunately, you didn't answer my previous request about your handling of positive antigen testing data. 
According to CDC guidelines, positive antigen tests should be counted as probable cases. Therefore, more and more states started to report positive antigen cases in recent days.
The following declaration can be found on your dashboard: "Cases and Death counts include confirmed and probable (where reported)." I recommend you reconsider this proposition or start to report positive antigen cases and probable deaths as required by your own guidelines.

Snapshot of Georgia's covid-19 dashboard:
![Unbenannt](https://user-images.githubusercontent.com/66752944/98398049-985b4680-2060-11eb-9413-85dcfa7b77ef.JPG)

**Comment by CSSEGISandData** [comment]
Thank you for your posting. We are in the process of updating our reporting to include probable cases.
