### ISSUE TITLE
Smith county, TX probable cases and deaths

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3319]
As already issued in #3300 and #3318, here's another example of massive underreporting:

![Unbenannt2](https://user-images.githubusercontent.com/66752944/98429418-bc417b00-20a6-11eb-8284-d5c0af957e22.JPG)
 
I'm still looking forward to receiving an answer from you.

**Comment by CSSEGISandData** [comment]
Thank you for your posting. We are in the process of updating our reporting with probable cases.
