### ISSUE TITLE
Two identical references for Republic of Ireland and Ireland

### ISSUE THREAD

**Issue by EI8EJB** [CSSEGISandData/COVID-19#332]
There are two references for the Republic of Ireland. Should be amended to show only as "Republic of Ireland" and the additional "Ireland" reference which should be removed to avoid confusion. The data figure for Northern Ireland lies within the data set for the UK.

**Comment by Bost** [comment]
It's obviously too late now[1] but to avoid confusion the norm [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) should had been used. More precisely the 2 or 3 letter country codes. I personally map all the non-standard names to the names provided by the ISO norm:
- in clojure https://github.com/Bost/corona_cases/blob/master/src/corona/countries.clj 
- in python https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/app/utils/countrycodes.py

and then use the 2 letter country code in my project(s).

[1] #238 Do not change it !!!

**Comment by plt005** [comment]
To avoid changing the current data structure it would be very helpful to provide a separate data set mapping the country/region names to the ISO_3166-1 codes.

**Comment by Bost** [comment]
@plt005 this merge effort may interest you https://github.com/Bost/corona_cases/issues/1

**Comment by EI8EJB** [comment]
Well done and many thanks for the VERY fast response. Regards!!
