### ISSUE TITLE
Colombia bad data on 2nd Nov

### ISSUE THREAD

**Issue by simonhampel** [CSSEGISandData/COVID-19#3320]
The data for every state in Colombia for 2nd Nov jumps by a very large amount before reverting back on the 3rd Nov to data in line with that from the 1st Nov.

Would indicate that the data for the 2nd Nov is invalid?

An initial analysis looks like the entire data set has been transposed one row higher than it should (when sorted by the Confirmed number of cases).

**Comment by CSSEGISandData** [comment]
Hello

Can you point to the file with this issue? I do not see it in the time_serires_covid19_confirmed_global.csv. Thanks!

**Comment by simonhampel** [comment]
Ahh yes, apologies - I wasn't specific enough.

Data in this file: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-02-2020.csv

**Comment by CSSEGISandData** [comment]
Hello

I have tracked down the source of this discrepancy. The csv file we pull from the national Colombian source had anomalous data being pulled from 10/28 to 11/02. As such, we were forced to overwrite our time series data with the corrected totals from the national dashboard. However, the historical subnational data (that which is reported in the daily reports) was unavailable and thus we were not able to fix those daily reports.

Our historical changes to time series data is documented in our [Errata file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/Errata.csv).

Thank you for your patience. I would consider the Colombia values in the daily report on the 2nd of Nov invalid, but the time series entries accurate.

**Comment by CSSEGISandData** [comment]
In general, we are more readily able to edit the time series files than the daily reports so I point individuals to those files as being the "ground truth" or as close as we can come to it.
