### ISSUE TITLE
Unusual spike in data. 

### ISSUE THREAD

**Issue by satish-pola** [CSSEGISandData/COVID-19#3322]
Data seems wrong here. In CA, I don't think there are 306327 confirmed cases in just one data. Also, when I sum total US cases for the day 10-30-2020, it's giving me very usual number. Same thing happening when summing all the confirmed/recovered/death cases from all the csv files. 

csse_covid_19_data/csse_covid_19_daily_reports/10-30-2020.csv
6037,Los Angeles,California,US,2020-10-31 04:24:44,34.30828379,-118.2282411,306327,7056,0,299271,"Los Angeles, California, US",3051.3371358627805,2.3034208541852332

+----------------+
| sum(confirmed) |
+----------------+
|        9044103 |
+----------------+

**Comment by satish-pola** [comment]
In the same file recovered 3578452 ?? Looks something is wrong ?
,,Recovered,US,2020-10-31 04:24:44,,,0,0,3578452,-3578452,"Recovered, US",,

**Comment by satish-pola** [comment]
One more example: shows 80104 cases in 10-28-2020.csv. Please let me know if I am not reading it correctly. 
32003,Clark,Nevada,US,2020-10-29 04:24:49,36.21458855,-115.0130241,80104,1506,0,78598,"Clark, Nevada, US",3533.9246442539093,1.8800559272945172

**Comment by CSSEGISandData** [comment]
Hello

All of the data highlighted in your issue is accurate as reported.
