### ISSUE TITLE
Covid-19 Cases per mln counts

### ISSUE THREAD

**Issue by SebCaputa** [CSSEGISandData/COVID-19#3325]
Hello,

I think I found a bug in data presentation in Google - redirected here when looking for data source.

Here is the description of the bug:

When you look at the Cases per million for the whole country (Poland), you'll find that is currently 14,238. But when you look at the same figures for different regions, the max Cases per million count is 13,919. Other regions start from 4,406 and falling 1,502. How can you explain that the Cases per million count for the whole country is much higher than the arythmetic mean for all regions and even higher than the highest number for a particular region? There must be something wrong with the averaging formula, or am I wrong?

Please check this for Poland - I haven't checked this for other countries.
![CasesPerMln_Poland](https://user-images.githubusercontent.com/74180870/98527551-77227200-227b-11eb-801c-9d2f9c7283e3.PNG)

**Comment by CSSEGISandData** [comment]
Hello

We do not report subnational data for Poland. This is an issue with those generating the data visualization.

**Comment by SebCaputa** [comment]
Two questions:

1. Where do you get the national values from?
2. Which values are correct then? Do you know where the subnational values come from?

The data presented in Google are indicating you as source.

**Comment by CSSEGISandData** [comment]
Hello

Poland reports their data via twitter every day: https://twitter.com/MZ_GOV_PL/status/1325732460215357448

The national data in your screenshot matches the data we reported yesterday. We cannot speak to the source of Polish subnational data used by Google, but it appears we are misattributed.
