### ISSUE TITLE
Only observations

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#333]
![index](https://user-images.githubusercontent.com/44967630/76203234-95b90080-61f6-11ea-82d1-b6aec3e6a947.png)
I am surprised to see that visually  different groups of countries show  similar curves  in number of Discovered  : 
- Iran and Italy have the same exponential curve , 
- Germany and France are grouped 
- US and Japan are in the same forms of evolutions

but in fact the second group has now the same values than Italy had only one week ago, so as the daily reports dont show (at the contrary of  China)  a real decrease, perhaps in 1 week or 2,  all these countries will be at the level where Italy is today .

But what is quite worrying in Italy , is the number and rate of dead people which is inflating dramatically compared with countries like Germany where there are no dead people at all with significant number of discovered.
What is the explanation for 0  death ratio in Germany ?

The number of recovered in Iran seems also very high in my opinion, when compared to other countries : more recovered now than discovered 4  days ago ??

**Comment by SeidChr** [comment]
As sad as it sounds, but give it some time.
People do not die straight away, and as of today, i have heard of 5 deaths.
When the health system is affected, as is probably the case in Italy, this rate may rise.

Btw, like your graph :) almost looks like mine
https://github.com/SeidChr/COVID-19-Report-Data-Pipeline/wiki/The-Plot

**Comment by JiPiBi** [comment]
@SeidChr 
My observation was made  some days ago and even if the first dead persons appear, the rate if very low, and my interrogations remain.

In your graphs we can also see the different groups of country in relation with their evolution curves.
I would like to understand what it means: is it linked to the national health system, to the decisions made or to the number of realized tests .

**Comment by carlosvega** [comment]
> What is the explanation for 0 death ratio in Germany ?

For ICU ratio plus early tests to detect people before they have symptoms.

Also, do not compare countries that easily. Countries have different density, different health systems, different population and culture. Hence, they have different restrictions, respond very differently to such restrictions, treat the cases differently, etc.

**Comment by JiPiBi** [comment]
@carlosvega 
the interest of the dataset is also to analyse the differences and understand why SouthKorea and Germany have so low death rates (for a significant number of discovered cases) and Italy so high.  

I think also that knowing the number of realized test and people into ICU could help to understand 

For the number of tests, to see  if the good results are linked with intensive testing   (and if the beginning of the testing has an influence)  

For the number of people in ICU,  to see how is the tendancy for  both the capacities of countries to deal with the number of people who need an ICU treatment  and the risk of future  increase in the number of dead people : I did'nt read informations about the percentage of people that recover after ICU and the treatment's duration in ICU for recovered and dead people .

**Comment by JiPiBi** [comment]
No more reaction ,I close
