### ISSUE TITLE
Required Active Cases data in single file

### ISSUE THREAD

**Issue by linusgvr** [CSSEGISandData/COVID-19#3333]
Dear Team,

Could you please load "Active Cases" daily reports in single file like "Confirmed", "Deaths" and "Recovered" case file in
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
I expect complete historical data in single file. I have also observed some locations in "Active Case" file not present in "Confirmed", "Deaths" and "Recovered" files.

**Comment by CSSEGISandData** [comment]
Hello

We do not report active cases in our time series files and at the moment do not have plans to create an additional time series file. Part of the motivation for this is that there is not historical data at the subnational level for the entirety of our time series - this is the reason that subnational data is generally present in the daily reports and not the time series files as you point out. Secondly, the active cases are equal to (confirmed)-(deaths+recovered) and thus are easily computable at the user level.
