### ISSUE TITLE
US cases/deaths out of sync with global time series files

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3335]
A change in the last several days seems to have un-synchronized the case and deaths totals for the US that are reported in the time series US and time series global files.

Summing all rows in the `time_series_covid19_confirmed_US.csv` file used to create a total that matched the US row in `time_series_covid19_confirmed_global.csv`. Those totals are now out of sync starting with 11/8/20.

Meanwhile, the death totals in the US and Global time series files are now out of sync beginning 9/22/20.

**Comment by CSSEGISandData** [comment]
Thank you for posting this issue. We are in the process of correcting.

**Comment by eolson3260** [comment]
Hi, Have the corrections been posted yet?  I noticed JHU dashboard shows new daily cases for the U.S. as 119,944 versus the 111,433 case increase shown in the time_series_covid19_confirmed_global.csv file.  Thank you.

**Comment by CSSEGISandData** [comment]
Thank you for your patience, this should be resolved with #3339.
