### ISSUE TITLE
Error data on file 03.11.2020

### ISSUE THREAD

**Issue by lphan** [CSSEGISandData/COVID-19#3338]
Please take a look at this file:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-03-2020.csv

The last row is redundant.
Thanks a lot for your hard work. 

Best, Long Phan

**Comment by CSSEGISandData** [comment]
Hello,

Error fixed, thank you for notifying us of this issue.
