### ISSUE TITLE
New York State infection cases not updated on Nov 10 2020

### ISSUE THREAD

**Issue by rahmatiangit** [CSSEGISandData/COVID-19#3344]
It is still @ 532,180 as it was  yesterday Nov 9th(?!)

.../csse_covid_19_data/csse_covid_19_daily_reports/...

**Comment by CSSEGISandData** [comment]
Thank you for posting your issue. We are in the process of correcting.

**Comment by rahmatiangit** [comment]
Thanks, issue is fixed
