### ISSUE TITLE
11/08 Florida People_Tested count is incorrect.

### ISSUE THREAD

**Issue by unclebob** [CSSEGISandData/COVID-19#3345]
csse_covid_19_daily_reports_us/11-08-2020.csv  In the Florida row, the People_Tested column is 10,555,504.  It declines to 6,410,130 in the Total_Test_Results column the day after.  So this was more than just a header change.

**Comment by CSSEGISandData** [comment]
Thank you for posting your issue. We are in the process of correcting.

**Comment by mndmr** [comment]
See also Issue #3367

**Comment by CSSEGISandData** [comment]
This issue has been resolved.
