### ISSUE TITLE
Deaths for 2020-11-09 out of sync between US/Global time series files

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3346]
Hi, thanks for fixing the broader syncing issue I raised in https://github.com/CSSEGISandData/COVID-19/issues/3335. All looks correct now except for the U.S. deaths number for November 9.

The file `time_series_covid19_deaths_global.csv` shows 238,256 deaths for Nov. 9.

Summing all rows in `time_series_covid19_deaths_US.csv` shows 238,251 deaths for Nov. 9.

Thanks!

**Comment by CSSEGISandData** [comment]
Thanks @anthonydb!  #3349 fixes.
