### ISSUE TITLE
New York Death Cases

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#3347]
Hello,

I noticed that NY death cases have been revised before Nov 8. However, the new figures on Nov 9 (33705) and Nov 10 (33705)  shows a declining trend (Nov 8 number is 33903), which is not normal for cumulative death cases. Would you mind confirmed the decrease of NY death case?

**Comment by CSSEGISandData** [comment]
This issue has been resolved.
