### ISSUE TITLE
Increase in US-GA confirmed cases on 2020-11-03

### ISSUE THREAD

**Issue by StateCenterKid** [CSSEGISandData/COVID-19#3348]
There is an unusual jump in the Confirmed value in the csse_covid_19_daily_reports/11-03-2020.csv file.   The total increase for US-GA on that day is 31,605 compared to the normal range of 2000-5000 cases.  The anomaly is spread across multiple counties.  This spike doesn't appear in other data sources.

**Comment by NaKo91** [comment]
I brought that up in #3318 
On November 3rd, Georgia started to report cases based on positive antigen tests. This lead to a spike in the daily numbers.
Other sources possibly may not have been aware of that change or refuse to show positive antigen cases.

**Comment by bjb100** [comment]
Worth noting that the NY Times database showed a similar spike for GA back around Oct 5, which reflected their decision to include positive antigen cases at that time. Now that this is true of JHU, the GA numbers in both databases are in good agreement.

**Comment by StateCenterKid** [comment]
Closed per 3318
