### ISSUE TITLE
Italian data by region

### ISSUE THREAD

**Issue by AnthonyEbert** [CSSEGISandData/COVID-19#335]
Could you split the Italian data into regions? I have already formatted the region-level data into your format https://github.com/AnthonyEbert/ItalyCovid19/tree/master/johns-hopkins-format

I've converted the Italian data available from https://github.com/pcm-dpc/COVID-19, this is direct from the Italian government. 

The relevant R script is here https://github.com/AnthonyEbert/ItalyCovid19/blob/master/johns-hopkins-format_Italy.R

**Comment by jawz101** [comment]
https://github.com/pcm-dpc/COVID-19
I just came here to say the same thing after looking to see if there were any implementations in QGIS.  
[Here is a QGIS presentation](http://coronavirusin-italy-greece-cyprus.epizy.com) of their data set

and an ARCGIS page of this Italian Ministry of Health's data set.
http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/dae18c330e8e4093bb090ab0aa2b4892

**Comment by AnthonyEbert** [comment]
The province-level data includes only confirmed cases, not deaths and recovered.

**Comment by jawz101** [comment]
Ah.  Gotcha

**Comment by lazd** [comment]
@AnthonyEbert nice work. I found 2 issues with the data and filed against your repo:

https://github.com/AnthonyEbert/ItalyCovid19/issues/1
https://github.com/AnthonyEbert/ItalyCovid19/issues/2

Once I worked around those issues, I was able to add your data to my application and it worked fine.

Are you planning on keeping your repo up to date daily?

**Comment by AnthonyEbert** [comment]
Thanks for your comments. Yes the repo will be kept up to date daily.

**Comment by jawz101** [comment]
@lazd ok your coronaglobe is cool

**Comment by lazd** [comment]
Thanks @jawz101. One thing I'm struggling with is whether to begin breaking down data into smaller regions. Using @AnthonyEbert's data, I was able to draw data across the different regions of Italy, and it still seems to communicate the data nicely, but in the US, data comes by county and sometimes city, which are much smaller than provinces, and I'm not sure that will communicate the data effectively... Maybe the answer is to allow users to pick the granularity they want to see.

![image](https://user-images.githubusercontent.com/201344/76263209-85ffe300-621b-11ea-9596-c6c040b1f926.png)

**Comment by jawz101** [comment]
are the varying colors to indicate active/recovered/deaths?

I feel like keeping them the same brightness or something might be more attractive.

I also like http://coronamapper.com/ which does shading of a location but they have an option to do it as a % of population in millions.

[This site](https://blog.datawrapper.de/choroplethmaps/) also has some nice ideas of attractive choropleths if it inspires anything

**Comment by lazd** [comment]
@jawz101 the varying colors are just due to point density. It's basically a heatmap with tiny points (1 for every 2 cases), so it's behaving like a heatmap would, but without the imprecise spread. Choropleth with rate-based data is an excellent way to visualize it. Thank you for the links!

But back to Italy; I went with the province based data, and started breaking down the US into counties. I'm going to add a slider for granularity that lets you select country, state, and province based visualization, that way the data can be presented at the level of precision that the user wants.

**Comment by jawz101** [comment]
did anyone else notice the John Hopkins map reverted to state-level data?  It seemed like yesterday and before it had been at the city level..  I also just found a [city-level repo for China](https://ncov.ahusmart.com/)

**Comment by lazd** [comment]
@jawz101 no, I have not seen that change. I just looked at the history from 3 days ago, 226 rows, 267 today. Look at the Git history: https://github.com/CSSEGISandData/COVID-19/commits/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by CSSEGISandData** [comment]
Subnational data for Italy is now available in the dashboard!
