### ISSUE TITLE
Maine case counts

### ISSUE THREAD

**Issue by wellsangels** [CSSEGISandData/COVID-19#3353]
The time series data show an unusual increase in covid cases in Maine yesterday which is not reflected in the Maine CDC page, which is linked as the source: https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/airborne/coronavirus/data.shtml

**Comment by CSSEGISandData** [comment]
Thank you for posting this issue. We are in the process of correcting.

**Comment by CSSEGISandData** [comment]
This issue has been resolved.

**Comment by wellsangels** [comment]
These numbers don't seem to have been updated. The state CDC, cited as JHU's source, has 8,396 total cases as of 11/11 (7,516 confirmed and 880 probable) and JHU has 8,202 total cases.
