### ISSUE TITLE
Georgia Case & Death Numbers Incorrect

### ISSUE THREAD

**Issue by ngold1** [CSSEGISandData/COVID-19#3354]
For the last three days, the case and death counts for the State of Georgia have been incorrect.

**Comment by CSSEGISandData** [comment]
Thank you for your post.

Georgia cases and deaths includes antigen positives (as probable cases) and probable deaths.

For example, the latest case report for 11/11/2020 sums to 413894. Georgia is currently reporting

Confirmed cases - 377,694
Antigen Positive Cases - 36,200

which sums to 413894.

**Comment by DavidViral** [comment]
So did they start counting positive antigen tests as cases on November 3rd?  There is an anomaly of around 36K additional cases in JH data reported for Nov. 3rd.  Are these all the pre- Nov 3rd historical positive antigen tests lumped into Nov. 3rd?

**Comment by wellsangels** [comment]
Georgia began reporting antigen and probable cases on 11/3 

https://www.ajc.com/news/coronavirus/georgia-adds-antigen-tests-and-probable-deaths-to-coronavirus-dashboard/K5RO2JGMCFHBPGE24J23NPSLN4/
