### ISSUE TITLE
New York Deaths

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3356]
NY Cumulative Deaths reported for 11-11-20 are 91 fewer than the previous day.

**Comment by CSSEGISandData** [comment]
Thank you for your posting. Could you please point to which file you are finding the above issue?

**Comment by DavidViral** [comment]
I am referring to the US time series, posted the morning of 11-12,  for deaths - where 11-10 was 33939 and 11-12 was 33848 total deaths.

**Comment by CSSEGISandData** [comment]
In the time_series_covid19_deaths_US.csv file we have the following totals

11-10: 33939
11-11: 33961
11-12: 33975

--

**Comment by DavidViral** [comment]
Thanks for fixing the data.

    On Friday, November 13, 2020, 7:52:31 AM EST, CSSEGISandData <notifications@github.com> wrote:  
 
 


In the time_series_covid19_deaths_US.csv file we have the following totals

11-10: 33939
11-11: 33961
11-12: 33975

--
