### ISSUE TITLE
Georgia New Cases anomaly 11-03

### ISSUE THREAD

**Issue by rendermouse** [CSSEGISandData/COVID-19#3357]
The state of Georgia graph for daily confirmed cases is showing an enormous spike of 31.605k for November 3, with data points at 939 and 2611 on the previous and following days, respectively.

https://coronavirus.jhu.edu/data/new-cases-50-states/georgia

Is this accurate?

GA DPH site has 11-03 confirmed cases listed at 1702.

**Comment by NaKo91** [comment]
The numbers are accurate.
This issue has already been discussed in issue #3348 and #3354

**Comment by CSSEGISandData** [comment]
Thanks @NaKo91. Yes, this is due to a large release of probable cases by the state. We have contacted the state health department in an attempt to obtain a back distribution of the probables so the curve can be smoothed out.

**Comment by rendermouse** [comment]
Thank you for the response.
