### ISSUE TITLE
Canada numbers are being doubled in the "Confirmed cases by country" list

### ISSUE THREAD

**Issue by bigmaciraq** [CSSEGISandData/COVID-19#336]
I note that there is a format change in the Canada map which is probably responsible for this, but the totals in individual provinces is 66, abut the confirmed cases list by country is showing 132.

**Comment by davidacollins** [comment]
That seems to have happened about the same time that the cases for Vancouver, BC became the cases for British Columbia, Canada; and the geolocation marker moved.

**Comment by CSSEGISandData** [comment]
We have noted the issue and are working to check our sources for the proper count.

**Comment by phrayz** [comment]
This is still an issue.
