### ISSUE TITLE
Wisconsin Deaths

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3363]
The JH US time series for WI deaths is neither plausible or in agreement with WI Dashboard for more than the past week.

![WI Dashboard](https://user-images.githubusercontent.com/62083925/99078258-17cea580-258c-11eb-94e5-15894cae2f86.PNG)
![0833 EST](https://user-images.githubusercontent.com/62083925/99078266-1c935980-258c-11eb-908f-223510f525ed.PNG)

https://data.dhsgis.wi.gov/datasets/covid-19-historical-data-by-state/data?orderBy=GEOID

**Comment by CSSEGISandData** [comment]
Hello

Our data now includes probable cases and deaths from October 19 on. We are attempting to get a further back distribution from the state health department. I've updated our README to make this more clear.

**Comment by DavidViral** [comment]
Adding probables since Oct 19 does not explain why JH new deaths have been rapidly decreasing, now at zero, while new cases continue to skyrocket.  Until JH works out an agreement with WI we need a realistic data set.  The Wisconsin gov. Covid data a least qualitatively makes sense.  

I can't find a Readme file that addresses this issue, can you supply a link?


    On Friday, November 13, 2020, 1:37:38 PM EST, CSSEGISandData <notifications@github.com> wrote:  
 
 


Hello

Our data now includes probable cases and deaths from October 19 on. We are attempting to get a further back distribution from the state health department. I've updated our README to make this more clear.

**Comment by DavidViral** [comment]
The Covid Tracking Project shows these numbers which make sense.

![CTP](https://user-images.githubusercontent.com/62083925/99123537-5b4a0380-25ce-11eb-8096-6db211552b60.PNG)
