### ISSUE TITLE
Louisiana Total Case Jump

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3369]
Regarding jump in cases Nov. 12 and or Nov13,  this and other relevant information from LA Dashboard:

"November 13, 2020

The Louisiana Department of Health on Friday began incorporating antigen tests into the state’s COVID-19 data reporting and dashboard.

There are two different types of COVID tests – diagnostic tests and antibody tests. An antigen test is a type of diagnostic test. A diagnostic test can show if you have an active COVID-19 infection and should take steps to isolate yourself from others, and if your close contacts will need to quarantine themselves to protect the larger community. In some settings an antigen test will need to be confirmed with a more accurate and definitive molecular/PCR test.

The use of antigen tests in Louisiana has increased substantially over the past few weeks.

**On the COVID-19 dashboard, antigen tests are now included in Total Cases**, which are then broken down into Confirmed Cases (molecular/PCR) and Probable Cases (antigen). Antigen tests are also now included in Total Tests, which are similarly broken down so one can see which are antigen tests and which are PCR tests. ...."

https://ldh.la.gov/index.cfm/newsroom/detail/5879

**Comment by DavidViral** [comment]
It is my understanding that antigen tests should not be used for new cases because a positive test only indicates past infection which could be months prior to the test.    Since new cases are calculated as total cases at t=0 minus total cases at t-1, this gives inflated new case numbers and destroys any possibility of trend analysis.  Comments please.

**Comment by CSSEGISandData** [comment]
@DavidViral @Nako91 I appreciate your concerns over the spike.  Louisiana has traditionally only updated  probable cases and deaths weekly.  With the change on the 12th there was a jump from 5020 probable reported cases to 6642.  Unfortunately at this time data is not available to back distribute, however Louisiana is now updating probables daily so this should be resolved going forward.  If and when data becomes available, I'll update the timeseries.

**Comment by DavidViral** [comment]
JH is not reporting Cases or Deaths per the stated JH protocol in the US  time series, i.e. confirmed plus probable cases and deaths.  As stated above LA is now reporting per that protocol but JH has dramatically different numbers as of yesterdays report , 11-16.  JH reporting 7590 too many cases on 11-16 and 2532 on the day before.  Likewise 237 too many deaths on 11-16 and 11 too few the day before.

**Comment by CSSEGISandData** [comment]
Hello

We caught the source of the error for 11/16 and the fix has been applied to the time series and daily reports. Thanks again for all of your help, I really do appreciate how close of an eye you keep on the data as it helps us improve our process.
