### ISSUE TITLE
High Texas case count for 11/13

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#3370]
Morning all, it looks like JHU has reported 19,043 new cases for Texas for yesterday, vs. 10.542 reported on the [state dashboard](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83). I do see that the prior day (11/12) had a lower than usual number of daily cases reported for Texas at 1,737. Any notes you might be able to share? Possible this large single-day total for today includes some backlog from the day prior? Thanks in advance.

**Comment by CSSEGISandData** [comment]
Thank you we are currently fixing this issue.

**Comment by CSSEGISandData** [comment]
This has been corrected. Thank you for your post.

**Comment by naterattner** [comment]
Thank you for the weekend update, @CSSEGISandData.
