### ISSUE TITLE
High Louisiana case count for 11/16 -- double probables?

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#3379]
Morning all. Wanted to flag that the new case count for Louisiana yesterday (10,668) is larger than what the [LA state dashboard](https://ldh.la.gov/coronavirus/) shows (547). 

Might probable cases be included twice in the cumulative state count for yesterday? 197,467 confirmed + 7,592 probable + 7,592 probable = 212,651 total, close to the 212,649 total posted by JHU this AM. 

![image (49)](https://user-images.githubusercontent.com/7976152/99396261-845ce380-28af-11eb-84ff-649fc0a6c27c.png)

Thank you.

**Comment by CSSEGISandData** [comment]
Thank you for your post. We have corrected the issue.
