### ISSUE TITLE
New Category for > 2000000 Cases

### ISSUE THREAD

**Issue by stephanweidmann** [CSSEGISandData/COVID-19#3387]
Hi,
I hope this is the correct place to send this small topic:
On the dashboard, there is no sign on France.

https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Probably this is because there is no circle for more than 2 million cases. 

Thank you!
Stephan

![Unbenannt](https://user-images.githubusercontent.com/36635930/99839818-a7b3b700-2b6b-11eb-82ac-2ef541392f61.jpg)

**Comment by CSSEGISandData** [comment]
Thank you for your post. We have fixed the issue.
