### ISSUE TITLE
High Texas data for 11/24

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#3398]
Hi all, flagging that it looks like JHU has recorded 19.5K new cases for Texas yesterday, vs. 13,988 shown on the [state dashboard](https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83). Any notes you might be able to share? Thanks in advance.

**Comment by wellsangels** [comment]
It looks like there are some counties that have no new cases recorded for a few days in JHU's data, but did report those days. Hidalgo County for example, reported [729 new cases 11/23 ](https://www.hidalgocounty.us/DocumentCenter/View/42937/11232020---Four-more-deaths-related-to-COVID-19-reported-in-Hidalgo-County-along-with-729-positive-cases)and [655 on 11/24](https://www.hidalgocounty.us/DocumentCenter/View/42946/11242020---Ten-more-deaths-related-to-COVID-19-reported-in-Hidalgo-County-along-with-655-positive-cases), while JHU has 0 for 11/23 and that total 1,384 for 11/24. 

Thanks for taking a look at this.

**Comment by CSSEGISandData** [comment]
Hi Nate,

Thanks for bringing this up. We were tracking this internally yesterday morning as we were a bit worried this would happen. The vast majority of counties on the state dashboard were stale from 11/22 to 11/23 and so our internal interpretation is that this rise in cases includes a slight backlog of cases. However, there haven't been any announcements by the state to explain why these counties were stale so it is primarily speculation.
