### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by palrogg** [CSSEGISandData/COVID-19#34]
A suggestion: indicate the time zone (Eastern Standard Time if I remember well) or, even better, use UTC?

Keep up the good work!

**Comment by ciscorucinski** [comment]
I suggested that they do that before in the Google Doc comments but it was ignored. They should put a static EST label for a quick fix. But I would like to see 2 times. ETC and local time

**Comment by awtimmering** [comment]
`daily_case_updates` has a [README.md](https://github.com/CSSEGISandData/COVID-19/blob/master/daily_case_updates/README.md) that states:

> All file names are in US Eastern Time.
> The "Last Update" is in US Eastern Time (GMT -5) for all files before Feb 1 12:00 (ET).
> The "Last Update" is in UTC (GMT +0) for all files after Feb 1 12:00 (ET).

However it is unclear what timezone the `time_series` files are in. Are all of these in EST? Would be great to have it clarified in `time_series/README.md`.

**Comment by ciscorucinski** [comment]
We are also talking about timezone information on the [dashboard website](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), not just the GitHub information

**Comment by CSSEGISandData** [comment]
We know the time zone difference is a headache for many developers and uses. Now all timestamps maintained in csse_covid_19_data folder are in UTC.

**Comment by CSSEGISandData** [comment]
Also, in the dashboard, the last update time at the lower left corner indicator is your local time, and the time plot is in UTC.

**Comment by awtimmering** [comment]
Thank you for adjustment & clarification.
