### ISSUE TITLE
Where is the official list of countries?

### ISSUE THREAD

**Issue by AnthonyEbert** [CSSEGISandData/COVID-19#340]
Every time the first infection occurs in a new country, this country is added to the dataset. 

I can't anticipate what the precise name of the country will be, since I do not know which list of country names you are using. 

Could you let us know, in advance, what the full list of country names is? So that we can plan for the dimension of the data before it arrives. 

Thank you!

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/105#issuecomment-596653997

**Comment by CSSEGISandData** [comment]
Please check out the readme page of this repo for the full list of sources we are currently using. New data sources for subnational data will be within that list as well.
