### ISSUE TITLE
No City information for BC Canada

### ISSUE THREAD

**Issue by LNisom** [CSSEGISandData/COVID-19#341]
No City information given for British Columbia Canada. 
Also, cases for Canada on the side bar doubled from 66 to 132 but confirmed cases still show only 66

**Comment by davidacollins** [comment]
A few days ago the 'Province/State' column in the data showed 'Vancouver, British Columbia'.  The text for this column and the lat/long have been changed since then.  Vancouver actually means metro-Vancouver since today's (2020-MAR-09) death was in North Vancouver.

**Comment by CSSEGISandData** [comment]
We are currently reporting Canada at the Province/State level. During a dashboard update, some modules may take longer to update than others. Please be patient for the dashboard to fully update!
