### ISSUE TITLE
France data has not been updated since the past 4 days

### ISSUE THREAD

**Issue by anurag12singh** [CSSEGISandData/COVID-19#3413]
Hi,

The total number of cases in France has not been updated since Nov 29, 2020 and has been stuck at 2,217,555.

Best regards,
Anurag

**Comment by edomt** [comment]
And same for deaths.

**Comment by edomt** [comment]
The source data in the README seems to say that CSSE is using https://raw.githubusercontent.com/opencovid19-fr/data/master/dist/chiffres-cles.json as the source, which is a good and reliable one, but then I can't see why it wouldn't collect the updated cases and deaths at each update?

This is what the file looks like right now, filtering on `granularite == "pays"` and `source_type == "ministere-sante"`:

![image](https://user-images.githubusercontent.com/7103774/101024393-55fc2b00-3574-11eb-8bb9-10f60a666f18.png)

Cumulative cases are stored in `cas_confirmes`, and cumulative deaths can be obtained with `deces + deces_ehpad`.

**Comment by CSSEGISandData** [comment]
Hello all,

There was an alteration in the data structure of opencovid19-fr for mainland France that impaired our scrapper. We've corrected our time series files and daily reports with what the total should have been. Sorry for the trouble - we are looking to alter our France source as this has happened a handful of times.
