### ISSUE TITLE
Dec 2nd - Eureka County Nevada shows 353 deaths should be zero

### ISSUE THREAD

**Issue by rokhopr** [CSSEGISandData/COVID-19#3414]
Dec 2, 2020 State of Nevada dashboard shows zero deaths for Eureka but 353 _tests_, so someone made a typo somewhere in JHU dataset for Dec 2, 2020.  All other days for Eureka show zero.

353 deaths would mean 1 in 5 people died related to covid making it the #1 US county in deaths per capita and throwing the state total off.

Thank You.

![2020-12-03-EurekaCountyNevada](https://user-images.githubusercontent.com/70174391/100993471-148b6180-351b-11eb-93f0-245d955162d8.JPG)

**Comment by CSSEGISandData** [comment]
Thank you. We have resolved this issue.
