### ISSUE TITLE
Nevada New Deaths 10X Expectation 12-2-20

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3416]
In the states deaths time series Nevada is reported with 2555 total deaths with 391 New deaths on 12-2;  this is roughly 10 times the expectation for new deaths.  NV gov Covid dashboard reported 2201 total deaths. 

https://nvhealthresponse.nv.gov/

**Comment by CSSEGISandData** [comment]
Thank you for posting. This issue has been resolved.
