### ISSUE TITLE
" Azerbaijan" in 02-28-2020.csv

### ISSUE THREAD

**Issue by greg-minshall** [CSSEGISandData/COVID-19#342]
i don't know if this is of interest, but the first entry for Azerbaijan, which shows up in 02-28-2020.csv, is offset from the separating comma by a space, causing (at leat R's) CSV reader to record it as " Azerbaijan" rather than "Azerbaijan".  presumably editing this wouldn't cause any compatibility problems, and might help future usrers.

cheers, and thanks for much.
----
bash apollo2: {1158} grep -i azerbaijan *.csv
02-28-2020.csv:, Azerbaijan,2020-02-28T15:03:26,1,0,0
03-01-2020.csv:,Azerbaijan,2020-03-01T02:43:03,3,0,0,40.1431,47.5769
03-02-2020.csv:,Azerbaijan,2020-03-01T02:43:03,3,0,0,40.1431,47.5769
03-03-2020.csv:,Azerbaijan,2020-03-01T02:43:03,3,0,0,40.1431,47.5769
03-04-2020.csv:,Azerbaijan,2020-03-01T02:43:03,3,0,0,40.1431,47.5769
03-05-2020.csv:,Azerbaijan,2020-03-05T13:53:03,6,0,0,40.1431,47.5769
03-06-2020.csv:,Azerbaijan,2020-03-05T13:53:03,6,0,0,40.1431,47.5769

**Comment by Bost** [comment]
> presumably editing this wouldn't cause any compatibility problems, and might help future usrers.

Quite a large portion of all issues in this repo is caused by changing stuff under our feet! NO. Do not ask these guys to change anything!!!

Define yourself aliased like https://github.com/Bost/corona_cases/commit/01f27198b0e0124841b13d3d580ed4aeec5bff65

**Comment by greg-minshall** [comment]
i'm a newbie, so works for me.
