### ISSUE TITLE
Possible Irregularity in Afghanistan Confirmed Cases Data dated 3 December 2020?

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#3423]
Hi,

Confirmed cases data of Afghanistan on 3 December 2020 shows a lower figure (46718) than that of 2 December 2020 (46980). Is this a possible incorrect entry?

**Comment by CSSEGISandData** [comment]
Thanks for bringing this to our attention! We've corrected the data in this PR: #3425
