### ISSUE TITLE
Massachusetts 12-3-20 New Case Delayed Numbers

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3424]
From the MA Dashboard - posted today.

PLEASE NOTE: Today’s case numbers include 680 cases tested by one Massachusetts based
laboratory prior to December 1. The delay in reporting was caused by a technical
issue with the software used by that laboratory’s reporting vendor.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the notification. We've documented it in our README. I'll leave this issue open until tomorrow so others can see it quickly. Thanks again.
