### ISSUE TITLE
Need some clarification on Kazakhstan data

### ISSUE THREAD

**Issue by Epi-Mic** [CSSEGISandData/COVID-19#3430]
I suppose the totals contain probable cases, am i right? 
Since when the numbers were adjusted?

**Comment by CSSEGISandData** [comment]
Hello

Correct- our data for Kazakhstan includes probable cases and is sourced from [here](https://www.coronavirus2020.kz/). The switch was made on December 2 and the entire time series was updated to include these cases, as documented in our README.
