### ISSUE TITLE
Ohio case numbers artificially high

### ISSUE THREAD

**Issue by wellsangels** [CSSEGISandData/COVID-19#3438]
It looks like the increase in Ohio's case total on Tuesday is [partially the result of backlogged antigen tests.](https://www.cleveland.com/open/2020/12/ohio-reports-25721-new-coronavirus-cases-an-expected-one-day-record-due-to-clearing-backlog-tuesday-update.html) Do you know if you'll get dates for these cases and be able to backdate them?

**Comment by CSSEGISandData** [comment]
Hello

We've added a note about this issue to our README. We will keep an eye out for a back distribution but historically these have not been provided. We will leave this issue open for today to ensure individuals are aware.
