### ISSUE TITLE
Suggestion: file naming convention to be ISO 8601 compliant

### ISSUE THREAD

**Issue by markgalassi** [CSSEGISandData/COVID-19#344]
You have: "File naming convention ... MM-DD-YYYY.csv in UTC."
It would be very good to switch that to the ISO standard date specification of YYYY-MM-DD which would allow very flexible data processing thanks to the lexicographic sorting by date.

https://xkcd.com/1179/

**Comment by Shail-Shouryya** [comment]
Addressed in PR https://github.com/CSSEGISandData/COVID-19/pull/322

**Comment by CSSEGISandData** [comment]
To be consistent with our current processes, we will continue with our current naming convention. Sorry for the inconvenience.
