### ISSUE TITLE
patch #3440 for Albany Co, Wyoming leaves remaining error

### ISSUE THREAD

**Issue by cabuerkle** [CSSEGISandData/COVID-19#3441]
Thank you for patch #3440 and your prompt attention..  

There appears to be a lingering error. 

The data in jhu_covid-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv for Albany,Wyoming appear corrected for recent dates, but the last value is anomalous (it is 3120, which was the previously repeating value that started on 1-Dec-20, whereas the previous value was 3256).  

The last value in the series should be for 12/8/20 according to the header, but the 12/8/20 data appear to be in the penultimate value and the 3120 appears to be a spurious addition.  More generally going back in time, your data and for the NYTimes are offset by one day, going back to beginning of April.

Most recent days:

> Date NYT JHU
> X12.1.20  3120 3136
> X12.2.20  3136 3152
> X12.3.20  3152 3180
> X12.4.20  3180 3195
> X12.5.20  3195 3219
> X12.6.20  3219 3238
> X12.7.20  3238 3256
> X12.8.20  3256 3120

To compare the full series, in R:
```
# NYT data
nyt<-read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
## select FIPS 56001, which is Albany Co. Wyoming
nyt<-nyt[nyt$fips == 56001 & !is.na(nyt$fips),]

#JHU data -----
jhu<-read.csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
jhu<-jhu[jhu$FIPS == 56001 & !is.na(jhu$FIPS),]
## select 3.25.20 (NYT data start on day of first case) through last date
jhu<-jhu[, which(names(jhu) == "X3.25.20"):ncol(jhu)]

data.frame(nyt=nyt$cases, jhu=as.numeric(jhu), row.names = names(jhu))
```

_Originally posted by @cabuerkle in https://github.com/CSSEGISandData/COVID-19/issues/3439#issuecomment-742110535_

**Comment by CSSEGISandData** [comment]
@cabuerkle Thank you for noticing this and reporting it, it appears our original patch had a day shift in it. It should be adjusted in #3443. Thanks again!
