### ISSUE TITLE
Washington Reported as Negative 166 New Deaths on 12-10-20

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3448]
The JH State Series has 2850 total deaths and 3016 the day before.

**Comment by CSSEGISandData** [comment]
Thank you for your post. On 12-09, WA posted 3016 and on 12-10 WA posted a decrease in cases of 2850. Please see screenshots of their reporting below.

<img width="1264" alt="WA_Reporting_1209" src="https://user-images.githubusercontent.com/60674295/101953716-d819ce80-3bc8-11eb-8988-a019feba9277.png">
<img width="1081" alt="WA_Reporting_1210" src="https://user-images.githubusercontent.com/60674295/101953718-d8b26500-3bc8-11eb-91d7-3415eba45fcd.png">
