### ISSUE TITLE
(Bad Data) Arizona Total_Test_Results jumped from 2.4m to 4.1m in 1 day

### ISSUE THREAD

**Issue by wolpert** [CSSEGISandData/COVID-19#3449]
Aggregated AZ data from csse_covid_19_data/csse_covid_19_daily_reports_us/12-10-2020.csv shows a massive uptick from 2.4m to 4.1m for Total_Test_Results.

(12-09-2020 had 2419380, 12-10-2020 has 4136075)

**Comment by CSSEGISandData** [comment]
Thank you for posting this issue. We are currently looking into the issue.

**Comment by CSSEGISandData** [comment]
We have fixed the issue. Thank you again.
