### ISSUE TITLE
Iowa Death count not updating since 12/08

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3451]
The death count remains at 2724 since Tuesday, whereas, as of today, the Iowa dashboard shows 3197 deaths.

**Comment by CSSEGISandData** [comment]
Thank you, we are looking into this issue.

**Comment by NaKo91** [comment]
Thank you for solving this. Unfortunately, the Iowa dashboard doesn't provide an effective timeline to redistribute the daily death count. However, if you have any use for manual data, The Covid Tracking Project shows an accurate record of recent covid-19 fatalities in Iowa.
