### ISSUE TITLE
Información erronea

### ISSUE THREAD

**Issue by Lazarillo252** [CSSEGISandData/COVID-19#3467]
Hay 2 situaciones: 1.- Una de ellas es que la semana pasada en la grafica que publican en Google aparecen 2 picos exagerados de contagios a como se habían estado presentando ya habían pasado esas fechas con otros datos y las modificaron, creo yo que es un error!. 2.- La segunda es que el informe que publican del Estado de Chihuahua, esta equivocado, por ejemplo hoy publican que van 33.669 contagios y 4.086 muertes, siendo que las autoridades de salud publican 42.810 contagios y 3.990 muertes, lo que representa gran variación que no corresponde a 1 día de variación, ya que estos datos son de ayer y se publican hoy!
![image](https://user-images.githubusercontent.com/76069006/102266480-bf196200-3ed5-11eb-9cde-074883a47b15.png)

**Comment by CSSEGISandData** [comment]
Hola

Muchas gracias por sus preguntas. Lo siento que tengo una compentencia basicá en Español.

1. Por el primero, el pico exagerado del 5 de Octubre se debe a un cambio de las definiciones para casos en Mexico. Un aviso que describe el cambio está disponible [aquí](https://www.eluniversal.com.mx/nacion/coronavirus-5-de-octubre-mexico-suma-789-mil-casos-de-covid-y-81-mil-muertes). Yo voy a investigar el pico del 28 de Noviembre.
2. Por el dos, la fuente de datos que usamos es del gobierno de Mexico [aquí](https://datos.covid-19.conacyt.mx/#DOView). 
¿Si tiene una fuente de datos específicamente por del Estado de Chihuahua, puede compartir aquí?

**Comment by Lazarillo252** [comment]
The Chihuahua's information is right until today, the country information it's from yours, but is impossible to have that peaks, may be the unregistered information could be compliane that, but I do not think so!!!Sent from my Verizon, Samsung Galaxy smartphone
-------- Mensaje original --------De: CSSEGISandData <notifications@github.com> Fecha: 15/12/20  1:46 PM  (GMT-07:00) A: CSSEGISandData/COVID-19 <COVID-19@noreply.github.com> CC: Lazarillo252 <lazarillodechiwas@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [CSSEGISandData/COVID-19] Información erronea (#3467) 

Hola

Muchas gracias por sus preguntas. Lo siento que tengo una compentencia basicá en Español.



Por el primero, el pico exagerado del 5 de Octubre se debe a un cambio de las definiciones para casos en Mexico. Un aviso que describe el cambio está disponible aquí. Yo voy a investigar el pico del 28 de Noviembre.

Por el dos, la fuente de datos que usamos es del gobierno de Mexico aquí.

¿Si tiene una fuente de datos específicamente por del Estado de Chihuahua, puede compartir aquí?





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/CSSEGISandData/COVID-19/issues/3467#issuecomment-745556901",

"url": "https://github.com/CSSEGISandData/COVID-19/issues/3467#issuecomment-745556901",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
