### ISSUE TITLE
New York decline in deaths on 12/14

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3468]
New York's number of deaths went from 35.557 on 12/13 to 35.427 on 12/14.
Is this correct and, if so, can you provide more information about the decline?
Thank you!

**Comment by gsjennings** [comment]
It is from 2 counties - Orange (517 to 467) and Rockland (692 to 549).

**Comment by NaKo91** [comment]
@gsjennings Thank you for this information! I checked up the numbers provided by local covid-19 dashboards, and the decline in deaths doesn't show up there. 

Snapshot Orange:
![Orange](https://user-images.githubusercontent.com/66752944/102288474-d8092e00-3f3c-11eb-9334-7ba0ad7b8bcb.JPG)
(The Orange County dashboard seems to be updated only from Tuesdays to Fridays)

Snapshot Rockland:
![rockland](https://user-images.githubusercontent.com/66752944/102288616-274f5e80-3f3d-11eb-8511-8c84706b98c4.JPG)

**Comment by CSSEGISandData** [comment]
Thank you for your post. We have corrected this issue.
