### ISSUE TITLE
Official source for Switzerland

### ISSUE THREAD

**Issue by GermainZ** [CSSEGISandData/COVID-19#347]
The number of cases in the dashboard seems off (currently shows 374; actual confirmed cases at the time of writing: 312).

Official source: https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov.html#903671355

**Comment by CSSEGISandData** [comment]
Thank you for the source!
