### ISSUE TITLE
Utah Missing Cases/Deaths Data Dec 18 2020

### ISSUE THREAD

**Issue by lcoome** [CSSEGISandData/COVID-19#3476]
Confirmed cases and deaths are almost entirely missing as a [time series](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv) over the course of the pandemic for most counties in Utah as of today. These missing data are reflected on the [dashboard](https://coronavirus.jhu.edu/us-map) as well.

**Comment by CSSEGISandData** [comment]
Hello

Our data is consistent with the reporting of the [Utah State dashboard](https://coronavirus-dashboard.utah.gov/) where the reporting for some counties is at a lower resolution health district level.
