### ISSUE TITLE
US data for RECOVERED started being wrong on Dec 14

### ISSUE THREAD

**Issue by przemekklosowski** [CSSEGISandData/COVID-19#3485]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

The data for US is just zeros beginning on Dec 14. This is probably some error in data pipeline.

**Comment by CSSEGISandData** [comment]
Hello

Please see #3464.
