### ISSUE TITLE
Questions about cases in Antarctica

### ISSUE THREAD

**Issue by AnnaNishino** [CSSEGISandData/COVID-19#3486]
Hello,

Thank you always for your work!
I have a couple of questions about cases in Antarctica.

Some cases have been reported today in Antarctica, and they are all from Chilean Antarctic research team (source:https://www.bbc.com/news/world-latin-america-55410065).
It seems that Chilean government might not include those cases in Antarctic as of today (Dec, 22nd) according to [here](https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/)...?
(I just assumed those cases should probably go to the 'unknown' section and new cases in the section was zero today)
![image](https://user-images.githubusercontent.com/65237882/102966526-5f553380-4533-11eb-95bb-9065306f5299.png)

1. Does this official number include the cases in Antarctica?
2. Are you planning to create independent country/region for Antarctica as you have done to cases on Cruise lines? As you explained before, Antarctica is supposed to be categorized as a dependency of undetermined sovereignty by the US State Department.

Thank you for your time & take care!

Best,

Anna

**Comment by CSSEGISandData** [comment]
Very good point! We are aware of this issue and trying to contact the Chilean Ministry of Science. We will update the information as soon as we get further official confirmation. Thanks!

**Comment by CSSEGISandData** [comment]
See #3487
