### ISSUE TITLE
Source for case updates grouped by Region in the UK

### ISSUE THREAD

**Issue by DnsZhou** [CSSEGISandData/COVID-19#349]
Hi Team,

Thank you so much for your contribution!

Just want to suggest that for **UK** cases you can use this source for detailed region information:

- **England** https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public
or even more detailed report can be found here: https://www.gov.uk/government/publications/coronavirus-covid-19-number-of-cases-in-england/coronavirus-covid-19-number-of-cases-in-england

- **Scotland** https://www.gov.scot/coronavirus-covid-19/

- **North Ireland** https://www.publichealth.hscni.net/news/covid-19-coronavirus

- **Wales** https://phw.nhs.wales/topics/latest-information-on-novel-coronavirus-covid-19/

Thanks.

**Comment by takkaria** [comment]
I am downloading the regional data day-by-day for England & Scotland, starting March 11.  Happy to submit as a pull request.

**Comment by CSSEGISandData** [comment]
Subnational data for the UK is currently a work in progress and will soon be available in the dashboard.
