### ISSUE TITLE
Windows sees Trojan:Script/Conteban.A!ml packed into COVID-19-master.zip.  elusive rare issue

### ISSUE THREAD

**Issue by jimgrcovid** [CSSEGISandData/COVID-19#3495]

**Comment by CSSEGISandData** [comment]
Hello

Can you provide any more details? We have audited our repository and can't find this script in any files or hidden files, nor does it appear to have been introduced in any commits in the past 24 hours.

**Comment by jimgrcovid** [comment]
https://github.com/CSSEGISandData/COVID-19
click green/Code/download button
click Download ZIP
save file (to Downloads folder on my pc)
COVID-19-master.zip
(Just D/Ld tnow o get notice language detail)

Windows flags this file:
Treat found - action needed.
Detected: Trojan:Script/Conteban.A!ml
Status: Active
Active threats have not been remediated and are running on your device.

Date:  12/28/2020 11:12 AM
Details: This program is dangerous and executes commands from an attacker.

Affected items:

file: C:\Users\jim\Downloads\COVID-19-master.zip



using: windows 10 Home. Firefox

________________________________

**Comment by programmer1017** [comment]
Have you run a file check on Virustotal?
https://www.virustotal.com/gui/

**Comment by jimgrcovid** [comment]
No, I have not. I understand false positives happen. How to I spend 40 minutes uploading a file to Virustotal without file being active?  Where does Windows move the file to when it deems it a threat and isolates it?

**Comment by programmer1017** [comment]
I think isolated files are moved to %LOCALAPPDATA%\IsolatedStorage\

**Comment by ladris** [comment]
That and it's important to note that it may further be confounded if your
system itself is fundamentally infected by something that injects into
compressed files on your PC. Have you tested other .zip files to see if
it's specifically that one alone?

**Comment by ladris** [comment]
So far I'm not seeing anything indicating alteration or injection if
additional code into the zip file and nothing in the files contained
inside. Also don't see any indication of packing like UPX or other
typically hostile uses. Virscan org and Virus total show no engines packed
in or issues, but I'm going through the individual unpacked files still to
see.

**Comment by jimgrcovid** [comment]
No one else seems to have this problem, so it must be just my situation.  Thus at this point, thank you HELPING JUST ME by checking the file from last night (last 12 hours).

I keep windows security up to date.
I have done quick, full and MS Defender Offline scans. I have run MSERT.exe.
I have other zip files and none have been a problem.  During this situation I have downloaded zip files from other sources without problem.  I even have older COVID-19-master.zip files which continue to be fine.
This issue happened to me for a few consecutive days near the first of the month, and now since the 23rd.
Just now I D/Ld COVID-19-master.zip and an other source zip.  Other source fine.  COVID-19-master fine and VirusTotal says fine also.

To find  %LOCALAPPDATA%\IsolatedStorage\ I looked for C:\Users\jim\AppData\Local\IsolatedStorage\,  C:\Users\jim\AppData\Roaming\IsolatedStorage\,  and C:\ProgramData\IsolatedStorage\.  I did not find it.  I also Windows searched for "isolatedstorage" and "isolated storage" - no results.

So of course when I get help, the problem no longer presents.
Thanks for the help (Virustotal and independently picking the zip apart).  I would still like to know where Windows puts quarantined files, so I can try to scan and VirusTotal when/if this happens again.

Looking like odds are it is a false positive, but unresolved.  Seems odd it would only false positive for one person.

**Comment by ladris** [comment]
To view it, you need to open Windows Defender and look under recent items/events. One of two things happened, either it isolated the file download process and prevented it from executing OR it quarantined the file. It looks like it, in your case, it blocked the event but may not have moved it quarantined it if it said it remains unresolved.

Still have a look at the Windows Defender gui and see what all it offers, which if it did move it will allow restoration so you can interact with it.

**Comment by jimgrcovid** [comment]
Protection history shows 5 removed (by me). 2 blocked and one quarantined.  In all cases the file no longer is in download folder nor the folder I (sometimes) am able to move it to before opening it and Windows gets upset.  Interesting that Windows does not react at the same point in time after download.
One quarantined would imply it is still on my HDD.  But as stated above, I can not find it.  As for clicking the Restore button, I do not have the confidence to do so .... it might not be a false positive and I am not a trojan containing/removing expert.  If I could find where the zip is in quarantine, I think I could send it to VirusTotal.

**Comment by jimgrcovid** [comment]
did it again just now.  Got zip ~7 hours ago, left it in Download folder.  moved zip to another folder.  opened zip to first level .... MS reacted by both quarantining and blocking the zip.  won't find it as blocked is described as removing it from device.

**Comment by jimgrcovid** [comment]
D/Ld jan 01 data just now and scan shows ok

**Comment by jimgrcovid** [comment]
D/Ld zip with Jan 3rd info. Scanned w/ MS Defender (quick scan) - ok.  Moved zip (different folder still on same HDD) and opened zip and then went into first (COVID-19-master) folder and MS called it a threat and quarantined and blocked it.

**Comment by jimgrcovid** [comment]
no more issues for the last 23 days.  Nothing abnormal with user system.
