### ISSUE TITLE
Alberta Update

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#3498]
Find attached spreadsheet containing the Confirmed and Death numbers announced by the Alberta Govt.. at last nights Covid19 Press Conference which differ from your posted Alberta Update values.

Thanks for all your work!
Rowan

[ALBERTA_Dec25-28_fix.xlsx](https://github.com/CSSEGISandData/COVID-19/files/5751347/ALBERTA_Dec25-28_fix.xlsx)

**Comment by CSSEGISandData** [comment]
You should see the changes reflected in #3501
Thank you for bringing this to our attention!
