### ISSUE TITLE
Sweden - One graph/data series contain two different types of data on same axis?

### ISSUE THREAD

**Issue by love-lace** [CSSEGISandData/COVID-19#3499]
Hello,
So I was looking at the statistics for Sweden on google when I noticed that the graph for their "all" deaths looked very strange. I'm not a data scientist but I could tell something was wrong with the graph. I decided to look at where they got their data from and ended up here. I checked the website https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 and noticed the similiar issue when looking at Sweden's death graph. 

![image](https://user-images.githubusercontent.com/20403468/103300276-cc1e7100-49fe-11eb-9c7f-6cdcf46591db.png)

What you see is one data during spring and then during autumn it just jumps up and down. The data you use for spring was also not reported every day (and thus contains delay) so why is it so much smoother than the rollercoaster in autumn? Well, that's because they contain two *different* kinds of data.

In spring: the data shows the death on _the date they occur_.  I don't know where you get the data here but I assume it was reported correctly from the beginning because in the first part of the graph, it looks correct. The excel sheets that are given by the FHM agency can be found [here](https://www.arcgis.com/sharing/rest/content/items/b5e7488e117749c19881cce45db13f7e/data)/[here](https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/bekraftade-fall-i-sverige/). The tab "antal avlidna per dag" is "number of deaths per day". 

In autumn: the data shows the death on _the date they were reported._ (hence not when they occured)  Because the FHM changed their reporting times and increased the delay, this gives the roller coaster effect, and it seems the source data you use also changed their data format so the autumn numbers contains a different type of data information. It means the graph is basically completely wrong and giving a lot of misinformation. It looks like in spring, people died consistently everyday but in autumn they only died during tuesday-friday.

It is my understanding that proper data information need to be consistent so if the autumn data source is changed, the effect need to be applied on the spring as well (or vice versa). If not, clear labelling and separation of the graph needs to be done. 

If assistans is needed with translation for fixing this, please let me know.

**Comment by love-lace** [comment]
Here is an image from the public news channel in Sweden which shows the different graphs.

One is for the death as when they occured.

One is for the death as when they are reported.

Your graph mixes both of them into one graph.

![image](https://user-images.githubusercontent.com/20403468/103300196-9e392c80-49fe-11eb-98f1-f771950671f8.png)

**Comment by davidjayjackson** [comment]
Beginning around Aug. 28, 2020 Sweden stop recording number for Saturday, Sunday and Monday. And  instead added Saturday, Sundays and Mondays numbers with Tuesday numbers....

**Comment by davidjayjackson** [comment]
Here is a video where I try to explain Swedens Covid19 numbers (part 3)
https://youtu.be/ng7hfgcZ52Y

**Comment by love-lace** [comment]
> Beginning around Aug. 28, 2020 Sweden stop recording number for Saturday, Sunday and Monday. And instead added Saturday, Sundays and Mondays numbers with Tuesday numbers....

Hello. Thank you for the reply. I understand that Sweden stopped reporting their numbers those days but it doesn't explain the differences between the spring and autumn numbers in the graphs. The numbers they reported in spring during Saturday-Monday where significantly less and gave thus big gaps as can be seen in the second graph (the graph that depicts the number of death _reported_ for the day):
![image](https://user-images.githubusercontent.com/20403468/103751403-8bc78000-5008-11eb-9173-a2e56bd890dd.png)

Where are these gaps in the data/graphs that is graphs/data that is used in the dashboard and JHU? 

Like I wanted to point out, the metrics are completely different.
I.e. For the data you use:
Spring data = number of deaths on the day they occured.
Autumn data = number of deaths on the day they are reported.

The reporting days may have changed that doesn't explain why the metric was also changed in the same graph.

**Comment by davidjayjackson** [comment]
Howdy,
Here is Part 4 of my Closer Look at Sweden's COVID19 Numbers.
Hopefully this will answer you questions.

https://youtu.be/d_VHERiCAYU

David

**Comment by CSSEGISandData** [comment]
You are spot on. Please see issue #3594. We have altered our data to be consistent.
