### ISSUE TITLE
Thailand data issue

### ISSUE THREAD

**Issue by dmparker0** [CSSEGISandData/COVID-19#35]
From files "01-28-2020_1300.csv" to "01-31-2020_1400.csv", Thailand is listed as having 5 "Recovered" cases.

Then in file "02-01-2020_1000.csv", Thailand is listed as having 7 "Recovered" cases, with an update time of "2/1/20 10:00". 

Then from files "02-01-2020_1800.csv" to "02-01-07-2020_20204.csv", Thailand is again listed as having 5 "Recovered" cases.

Finally, in file "02-08-2020_1024.csv", Thailand is listed as having 10 "Recovered" cases, with an update time of "2/8/20 12:53".

It appears that either a) file "02-01-2020_1000.csv" should be edited to 5 "Recovered" cases, or b) files "02-01-2020_1800.csv" to "02-01-07-2020_20204.csv" should be edited to 7 "Recovered" cases.

**Comment by dmparker0** [comment]
It appears this issue actually pops up a number of times in the dataset. Here's the full list of potential errors + approximate dates for the files that might need to be edited.

**Place** | **Variable** | **Prior** | **Flagged** | **Next** | **Prior Date** | **Flagged Date** | **Next Date** | 
:--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | 
Queensland, Australia | Confirmed | 0 | 3 | 2 | 29-Jan | 30-Jan | 31-Jan | 
unspecified, Germany | Confirmed | 0 | 10 | 8 | 30-Jan | 31-Jan | 1-Feb | 
unspecified, Thailand | Recovered | 5 | 7 | 5 | 31-Jan | 1-Feb | 2-Feb | 
Shanxi, Mainland China | Recovered | 1 | 3 | 2 | 1-Feb | 2-Feb | 3-Feb | 
Guizhou, Mainland China | Recovered | 2 | 9 | 6 | 4-Feb | 5-Feb | 6-Feb | 
unspecified, Japan | Confirmed | 22 | 45 | 25 | 5-Feb | 6-Feb | 7-Feb | 
Ningxia, Mainland China | Recovered | 5 | 15 | 13 | 7-Feb | 8-Feb | 9-Feb | 
Heilongjiang, Mainland China | Recovered | 14 | 30 | 28 | 9-Feb | 10-Feb | 11-Feb | 
Guangxi, Mainland China | Recovered | 24 | 33 | 32 | 10-Feb | 11-Feb | 12-Feb |

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. This seems to have been adjusted based on the time series table. Thank you for the input.
