### ISSUE TITLE
Missing data for March 9

### ISSUE THREAD

**Issue by gena** [CSSEGISandData/COVID-19#350]
The last commit https://github.com/CSSEGISandData/COVID-19/commit/a3df4f322811946a12c6308cd728162ba58db89e did not seem to update data to March 9, it's still 8th

**Comment by CSSEGISandData** [comment]
We have noticed this issue and are working on it. Sorry for the inconvenience!

**Comment by acura650** [comment]
I am assuming this is also why the live ArcGIS map has not been updated as well?

**Comment by gena** [comment]
Thank you! 

And thanks for all the effort you're putting into this :clap:

PS: I'm using your data to keep the following app running: http://bit.ly/ee-coronavirus

**Comment by jtene001** [comment]
The March 9 data is now partially in. Still have the same problem as yesterday and the day before, about 6 or 7 cells are still missing.

**Comment by CSSEGISandData** [comment]
The issues are now resolved. The daily case upload has been updated and the time series tables have been updated as well. Thank you for your patience.

**Comment by CSSEGISandData** [comment]
Please note that the daily push to this repository will occur every day at 11:59 AM UTC time. There was confusion on upload time today due to Daylight savings in the United States. The correct time is 7:59 PM EST due to Daylight savings or simply follow UTC time for a more consistent time.

**Comment by jtene001** [comment]
Shouldn't that be 11:59 PM UTC?
