### ISSUE TITLE
New Jersey case jump

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3503]
The JHU dashboard shows a massive spike in New Jersey's case numbers, rising from 463.965 yesterday to 513.713 today. 
The case jump isn't consistent with official numbers, neither at the state nor the county level.
I guess this must be a mistake,

**Comment by CSSEGISandData** [comment]
Hello

We've reverted these numbers back to what is displayed on the public-facing dashboard.
