### ISSUE TITLE
Daily Death in Sweden seems way off compared to source

### ISSUE THREAD

**Issue by MarcelloGrita** [CSSEGISandData/COVID-19#3518]
Hi, I live in Sweden and checked the number of daily death today. Google shows a graph from this source and I was shocked to see the number of daily death being higher than the peak in April. I checked the source which is the same that I normally check (https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/ ) and the number there are way down (last chart on the bottom right corner). Why this discrepancy?

**Comment by davidjayjackson** [comment]
Hello,
I believe at some point Sweden rather then recording numbers for Saturday
and  Sunday added then into Monday's numbers.

David Jackson

**Comment by MarcelloGrita** [comment]
Hi David, thank you for your answer. I watched your video but I still don't understand. The 2 charts below should be the same as they have the same source and both shows daily numbers (according to their respective labels):

Folkhälsomyndigheten (Official source for Sweden and common source of both charts): https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/

<img width="809" alt="Screenshot 2021-01-04 at 19 18 28" src="https://user-images.githubusercontent.com/13627387/103566811-fb335780-4ec2-11eb-9297-1c050111cea7.png">

Google query:
<img width="711" alt="Screenshot 2021-01-04 at 19 19 34" src="https://user-images.githubusercontent.com/13627387/103566867-0d14fa80-4ec3-11eb-90d4-d0243a6b6bf7.png">

The one from google shows way higher number then April period, if compared to the one from Folkhälsomyndigheten. However, April period is similar from both.

**Comment by CSSEGISandData** [comment]
Hello

@davidjayjackson is correct in that the different in daily deaths is due to the reporting delays from the Swedish Ministry of Health. They report data Tuesdays-Fridays, so the Tuesday reports have high numbers of daily deaths as an artifact of their reporting structure and is the reason the peaks are cyclical. The graph linked in your second comment @MarcelloGrita ("Avlinda per dag") is plotting deaths by date of death rather than date of reporting, hence the discrepancy and the lack of peaks and troughs.

**Comment by davidjayjackson** [comment]
Hello again,
I've updated my Sweden Report to explain what appears to be going on .
https://youtu.be/LcFR_VjJFfE

By the way, Spain does the same thing....
Note: My Sweden Report is updated every Monday , Wednesday and Friday.
Also don't forget the like and share this video if you find it useful..

David

**Comment by MarcelloGrita** [comment]
Hi, does it means that the numbers of the first waive (around April) are then treated in some way (normalised, averaged or what else) in both charts, wile the number of the second waive are reported differently in the second chart (google screenshot?).

/Marcello

**Comment by davidjayjackson** [comment]
On Aug. 28, 2020 Sweden from report data 7 days a week, to only
reporting data Tuesday - Friday. They appear to be adding Sunday -
Monday to Tuesday. It appears that they are doing something with the
numbers , but the docs don't say anything about the data being
smoothed...or averaged.

https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/

**Comment by davidjayjackson** [comment]
Another video (part 3) where I take a closer look at Sweden's numbers.
https://youtu.be/ng7hfgcZ52Y
