### ISSUE TITLE
US Recovery Data Outlier 

### ISSUE THREAD

**Issue by therealcyberlord** [CSSEGISandData/COVID-19#3526]
There is a day where the number of US recoveries went down. When I graph the daily increase in recoveries, you can clearly see the negative outlier. As a result, it is causing a sudden drop in recovered cases for worldwide coronavirus cases. 

Thank you

![image](https://user-images.githubusercontent.com/30872286/103801397-aa834200-501b-11eb-9b6f-c7e85daf4287.png)
![image](https://user-images.githubusercontent.com/30872286/103801523-d8688680-501b-11eb-9dfc-9a27df759b74.png)

**Comment by CSSEGISandData** [comment]
Please see #3464
