### ISSUE TITLE
[Colaboration] Brasil has 30 confirmed cases

### ISSUE THREAD

**Issue by jonasmrfranca** [CSSEGISandData/COVID-19#353]
@CSSEGISandData please update the Brazilian confirmed cases to 30.

Rio de Janeiro just confirmed +5 cases, now there’re 30 confirmed cases.

Source: https://www.brasil247.com/brasil/brasil-tem-30-casos-confirmados-do-novo-coronavirus

**Comment by CSSEGISandData** [comment]
We have updated the dashboard. Thank you for the notification.
