### ISSUE TITLE
Empty Data in time_series_covid19_recovered_global.csv

### ISSUE THREAD

**Issue by monikerzju** [CSSEGISandData/COVID-19#3531]
Hello. I notice that in master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv, the recovered statistics of US after 2020-12-14 are all zeroes. I am confused so I calculate the recovered numbers using daily data of US provided by your group and it is definitely not zero. I wonder if I misunderstand something. A screenshot of the csv file mentioned above is attached and the line of US is the second last in the screenshot.
![screenshot](https://user-images.githubusercontent.com/70131923/104021300-81200d00-51f9-11eb-9df3-d00f6eabde49.png)

**Comment by CSSEGISandData** [comment]
Please see #3464
