### ISSUE TITLE
France New Cases 07.01.2021

### ISSUE THREAD

**Issue by Cromorne** [CSSEGISandData/COVID-19#3533]
Dear Madam or Sir,
I would like to point out to you what seems to be a mistake.
In France, on 7 January 2021, there are 21,703 new cases, according to the Ministry of Health, and not 254 as you indicate.
Kind regards.

**Comment by CSSEGISandData** [comment]
Thank you for posting. We are looking into the issue.

**Comment by Cromorne** [comment]
Dear Madam or Sir,
May I humbly ask you again about my question?
I would like to extend this to the following aspect.
Please find below two curves, again for France: one from Our World in Data, which uses your data, and another curve based on raw data from the French Ministry of Health.
The two curves represent the number of positive cases, on average over 7 consecutive days. The two curves are conspicuously different.
There are differences beyond 7 January.
![Capture d’écran 2021-01-12 160841](https://user-images.githubusercontent.com/77192551/104333109-289a8980-54f1-11eb-9ef8-1374a3edd7ac.jpg)

**Comment by Cromorne** [comment]
Dear Madam or Sir,
Today I can see that you are announcing 291 cases for France on 16.01.2021.
At the same time, the French Ministry announces 21,406 new cases.
Why these differences, which are repeated?
