### ISSUE TITLE
Raw Data Move?

### ISSUE THREAD

**Issue by dholmquist** [CSSEGISandData/COVID-19#3534]
When I try to access the "Raw" data table in the daily Covid19 reports, I get an error message that the URL has been moved or is temporarily down.  Could this be re-directed to the new data repository?

**Comment by CSSEGISandData** [comment]
Hello

Can you try again? I am unable to replicate this issue and we were not moving the repository. Please close if the issue has resolved itself.

**Comment by dholmquist** [comment]
Thanks for your reply.

I tried again and it still isn’t working as it had in the past (last time it worked for me was Jan 7th).

This is the message I get when pushing the “Raw” button:

[cid:image001.jpg@01D6E6A9.EEE058B0]

[cid:image002.png@01D6E6A9.EEE058B0][cid:image003.jpg@01D6E6A9.EEE058B0]

**Comment by dholmquist** [comment]
Issue resolved - thank you for your reply

**Comment by phuoctuannguyen** [comment]
#24

**Comment by phuoctuannguyen** [comment]
#3524

**Comment by phuoctuannguyen** [comment]
#3534

**Comment by LUCKYBOY1991** [comment]
dholmquist

**Comment by LUCKYBOY1991** [comment]
#246

**Comment by LUCKYBOY1991** [comment]
#3541

**Comment by LUCKYBOY1991** [comment]
#3534
