### ISSUE TITLE
Discrepancy with official data

### ISSUE THREAD

**Issue by Epi-Mic** [CSSEGISandData/COVID-19#3540]
JHU data differs from official figures presented by MOH of **Seychelles** (http://www.health.gov.sc/), Ministry of national security of **Saint Vincent and the Grenadines** (https://www.facebook.com/SVGHEALTH) and MOH of **Eritrea** (https://shabait.com/2021/01/08/announcement-from-the-ministry-of-health-103/)

**Comment by CSSEGISandData** [comment]
Thank you for your posting. We are looking into the issue.

**Comment by CSSEGISandData** [comment]
Hello,

We identified the issue and have adjusted our historical data. The present data should reflect the up-to-date epidemic data for these locations.
