### ISSUE TITLE
Recent missing days in Thailand data

### ISSUE THREAD

**Issue by sobri909** [CSSEGISandData/COVID-19#3546]
I haven't spotted the exact bits in the csv files yet, but looking at OWID's graphs there's several days showing 0 new cases in the past fortnight (most recent being 2021-01-08), while government announced numbers in the 100-500 range.

OWID's cumulative graph shows correct total to date, and csv files seem to use that rather than daily figures? Possibly then an issue with reporting time. I'll keep looking.

**Comment by CSSEGISandData** [comment]
Hello

Thank you for notifying us of this issues. We are working on a fix and hope to have it deployed today. Thanks again for your help.

**Comment by CSSEGISandData** [comment]
#3563 should fix the issue!
