### ISSUE TITLE
The U.S. FIPS codes should be zero-padded

### ISSUE THREAD

**Issue by ubiq-x** [CSSEGISandData/COVID-19#3547]
Affected file: [UID_ISO_FIPS_LookUp_Table.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv)
Affected UID range: `84000001` - `84000009`

The U.S. state FIPS code should be a two-character string, not an integer.  Single-digit integers should be zero-padded.  Interestingly, the U.S. county FIPS codes are correctly zero-padded.  This error must have been introduced recently; it was correct up to a few weeks ago.

**Comment by CSSEGISandData** [comment]
Issue fixed. Thanks!
