### ISSUE TITLE
"critical trends" graphs and "daily new cases" grtaphs do not match

### ISSUE THREAD

**Issue by rryi** [CSSEGISandData/COVID-19#3549]
Please have a look at the "critical trends" graph of e.g. South Africa in comparison to the daily new infections graph:

![image](https://user-images.githubusercontent.com/26365322/104326835-74960000-54ea-11eb-8f4d-38339eb6b23c.png)

![image](https://user-images.githubusercontent.com/26365322/104326994-a018ea80-54ea-11eb-982b-74d592eec90e.png)

Daily cases report an all time high these days about 21000, "critical trends" has its all time high instead in November, showing a daily peak of >100000. Wrong country picked in "critical trends" graph?

**Comment by CSSEGISandData** [comment]
Hello

The graph in the critical trends visualization is of France. It appears that this issue has been rectified on https://coronavirus.jhu.edu/data/new-cases

**Comment by rryi** [comment]
Error is not fixed, but has moved a little - see my new issue #3553
