### ISSUE TITLE
mismatch between US "cumulative deaths" and "daily deaths"

### ISSUE THREAD

**Issue by NaKo91** [CSSEGISandData/COVID-19#3551]
There's a discrepancy between the US numbers for "cumulative deaths" and "daily deaths" on January 8th.
The dashboard shows 4.017 deaths for that day, but the difference between cumulative deaths from January 7th to January 8th only adds up to 3.939 deaths.

![Unbenannt](https://user-images.githubusercontent.com/66752944/104412408-7bfded80-556c-11eb-8339-74f204743ee8.JPG)

**Comment by CSSEGISandData** [comment]
Thank you for your posting. We will look into the issue.

**Comment by runrun12** [comment]
@CSSEGISandData  are you going to correct this?
Thank you!

**Comment by NaKo91** [comment]
@runrun12 I'm sure they'll correct this. However, it could probably take some time to figure out from which state/county the discrepancy originates.

**Comment by CSSEGISandData** [comment]
Thanks for bringing this to our attention! This should be patched with #3586
The discrepancy should be resolved within a few update cycles with a new delta in deaths for the 7th into the 8th. Thank you!
