### ISSUE TITLE
Jan. 12 case totals mismatched between Global and US files

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3560]
Here's what I'm seeing for total cases by day since Jan. 9 in the global time series and US time series files:

<img width="359" alt="Screen Shot 2021-01-14 at 8 49 24 AM" src="https://user-images.githubusercontent.com/273891/104599375-ab345d80-5645-11eb-9b66-0d5abd118e19.png">

**Comment by CSSEGISandData** [comment]
Thank you for bringing this to our attention! #3562 should fix it.
