### ISSUE TITLE
MapView not zooming correctly

### ISSUE THREAD

**Issue by daviscyl** [CSSEGISandData/COVID-19#357]
The main desktop website's map view is not working correctly when zoomed out to global level. 
Maybe use a fixed zoom upper bound to prevent the  map from scaling way too small?

<img width="2560" alt="Screen Shot 2020-03-09 at 6 02 36 PM" src="https://user-images.githubusercontent.com/4491871/76270212-a470d900-6231-11ea-980a-6ce10536d8fb.png">

**Comment by daviscyl** [comment]
Also the same issue is found on the mobile site.

**Comment by CSSEGISandData** [comment]
Please refer to ESRI: https://livingatlas.arcgis.com/en/home/ for any technical support issues!
