### ISSUE TITLE
U.S recovered/active discrepancy/error since Dec 14th and 15th 2020 releases

### ISSUE THREAD

**Issue by kulnor** [CSSEGISandData/COVID-19#3574]
We recently noticed that our country level aggregated data for the U.S. no longer shows correct counts for the number of recovered and active cases.

Changes seem to have taken place in the 12-14-2020, 12-15-2020, and subsequent daily report for the US Recovered record.

In the [12-13-2020.csv file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-13-2020.csv
), the record at line 3095 is:
```,,Recovered,US,2020-12-14 05:26:27,,,0,0,6298082,-6298082,"Recovered, US",,```
where **Recovered=6298082** and **Active=-6298082**

In the [12-14-2020.csv file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-14-2020.csv), the record at line 3095 becomes
```,,Recovered,US,2020-12-15 05:26:38,,,0,0,6399531,0,"Recovered, US",,```
where Recovered=6399531 and **Active=0**

In the [12-15-2020.csv file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-15-2020.csv), the record at line 3095 becomes
```,,Recovered,US,2020-12-15 05:26:38,,,0,0,6399531,0,"Recovered, US",,```
where **Recovered=0** and Active=0

So in the Dec 14th data file, the Active count is now 0 instead of being a negative value offsetting the recovered count (which is really a virtual record not associated with a county). And then since the Dec 15th data release, the Recovered count is always zero. This is the case for all subsequent data releases.

This introduces a critical issue in the aggregated data roll-ups on the 'US' country code as seem to have lost the count of recovered/active cases at the national level.

This can be seen in our [RDS data explorer](https://covid19.richdataservices.com/rds-explorer/explore/int/jhu_country/data?collimit=25&coloffset=0&count=true&offset=0&limit=25&where=(iso3166_1%3DUS)%20AND%20(date_stamp%3E2020-12-10)
)

**Comment by KelumPerera** [comment]
As per this file source data [https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv](url) follwing counties/ states recovery data is available.


![image](https://user-images.githubusercontent.com/17468031/104836386-a4bb1580-58d3-11eb-8ecc-db6941cf46ab.png)

**Comment by CSSEGISandData** [comment]
Hello

Please see the pinned issue #3464

**Comment by kulnor** [comment]
Thank you all for the quick feedback, much aprpeciated.
