### ISSUE TITLE
2021-01-21 report - internal error

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#3597]
I believe there was an internal error with last nights report

{
    "success": false,
    "message": "internal error",
    "data": null
}

**Comment by scottstarsman** [comment]
I'm seeing the same error

**Comment by Zacb24** [comment]
I'm getting that same error...

**Comment by CSSEGISandData** [comment]
Hello all,

We've reverted the PR that caused this error. Apologies.
