### ISSUE TITLE
is the 9 March US total infection number (605) correct?

### ISSUE THREAD

**Issue by Swartzlander** [CSSEGISandData/COVID-19#360]
The total number of reported COVID-19 infections in the US amounted to 605 cases according to JHU daily report (9 March 2020), but this number seems anomalously low, given that it amounts to only 68 new cases since yesterday.  Over the previous few days the daily increment as been 31, 68, 57, 139, and 120.  While some variability of this increasing trend may be expected, a drop from 120 to 68 new cases seems unnatural.  I hope that someone will verify the 9 March 2020 data for the US.

**Comment by robert-mcdermott** [comment]
Either King county WA stopped testing or it's numbers haven't been updated since yesterday.

**Comment by Swartzlander** [comment]
Thank you.

*************************
Prof. Grover Swartzlander
Chester F. Carlson Center for Imaging Science, Rochester Institute of Technology

**Comment by erikamoya123** [comment]
Also noticing upon refresh US number appears at 709 and then reverts to 605.

**Comment by dawenx** [comment]
They probably did not update data since this afternoon. USA has 738 cases according to our dashboard. You can find the link from my github profile.

**Comment by CSSEGISandData** [comment]
During dashboard updates some modules may take longer to update than others. Please be patient.
