### ISSUE TITLE
Sweden reported deaths from week 1 missing/been combined

### ISSUE THREAD

**Issue by love-lace** [CSSEGISandData/COVID-19#3607]
Thank you for updating this to be more consistent. Although can I ask, where is this new data repository you are using now coming from? The reason being I took a double take at the 8th January which says it has 706 deaths reported. Being a Swede, I would remember the news outcry at that seeing as are largest reporting death we have had was 350 deaths at the 14th January and that was a big shock. 

I assume this is because the data reported from week 1 on [Tueday 5th January](https://www.youtube.com/watch?v=TfSMt5Ikj0o&list=PLLqBo3UjMccAyAkJ9uiJkQpPjDYUoWlHp&index=6) (249) and [Thursday 7th January](https://www.youtube.com/watch?v=Afqp_WV0ndA&list=PLLqBo3UjMccAyAkJ9uiJkQpPjDYUoWlHp&index=5) (276) has been combined with the numbers on Friday the 8th January? I see that they are reported as 0 deaths from the new repo I assume. 

_Originally posted by @love-lace in https://github.com/CSSEGISandData/COVID-19/issues/3594#issuecomment-765950005_

**Comment by CSSEGISandData** [comment]
PR #3613 should fix. Data from December 30 was stale until January 8.
