### ISSUE TITLE
Japan Deaths unusually large

### ISSUE THREAD

**Issue by pruggia** [CSSEGISandData/COVID-19#3611]
On Jan 19th, Japan deaths are being reporting as 314 in this repository, which seems very large compared to the other dates around.
I tried to find other sources reporting a similar number but the are all around 100 (examples https://toyokeizai.net/sp/visual/tko/covid19/en.html and https://www.worldometers.info/coronavirus/country/japan/)

Thanks!

**Comment by CSSEGISandData** [comment]
Thank you for your patience. We have resolved the issue.
