### ISSUE TITLE
Israel 16000 New Covid Cases?

### ISSUE THREAD

**Issue by rzlim08** [CSSEGISandData/COVID-19#3619]
It looks like the dashboard is reporting nearly 16000 new covid cases today for Israel, which would be a pretty big outlier. I don't see this reflected in the data source listed for Israel: https://datadashboard.health.gov.il/COVID-19/general. However, the total number of cases seems to be pretty similar.

Was this just a reporting backlog? Or a data error?

**Comment by Zayn12321** [comment]
Anyone know what can protect us from covid-19 except masks? It is reported that uv light can inactive the coronavirus, is it ture?

**Comment by CSSEGISandData** [comment]
Hello,

Sorry this has taken us so long to get to - became much more complicated than expected. It was a source issue and we have used media reports to correct the 25th and 26th to smooth the curve.
