### ISSUE TITLE
Wrong Data for Country India

### ISSUE THREAD

**Issue by sh4hids** [CSSEGISandData/COVID-19#362]
When I click on India from sidebar it shows the data for France.

![DeepinScreenshot_select-area_20200310083107](https://user-images.githubusercontent.com/25576246/76274021-9e1e4380-62a9-11ea-85e1-6c40b058252f.png)

**Comment by prinudickson** [comment]
This issue is fixed. The dashboard is reporting the correct data for India now.

**Comment by sh4hids** [comment]
I am closing the issue as it seems the issue has been fixed.
