### ISSUE TITLE
Recovered data Germany

### ISSUE THREAD

**Issue by mbender-ith** [CSSEGISandData/COVID-19#3623]
The "Recovered" data (file time_series_covid19_recvovered_global) has shown an ununsual leap from yesterdays number for Germany for Jan 27.

**Comment by bhagemeier** [comment]
I can confirm this. Came here because of the same issue.

**Comment by CSSEGISandData** [comment]
Hello,

The rise in recoveries for the entirety of Germany was driven by substantial increases in the reporting from multiple federal states. It is unclear why numerous federal states had above-average reporting for this day, but it appears to be a systematic change.

For clarity, these were some of the gains in recoveries at the federal state level, keeping in mind a normal backdrop of ~20,000 recoveries per day across the country:

Baden-Wurttemberg - 27,595
Bayern - 37,121
Brandenburg - 11,695
Hessen - 18,605
Rheinland-Pfalz - 13,305
Sachsen - 15,051
Sachsen-Anhalt - 8,089
Thuringen - 8,592

**Comment by Bost** [comment]
One of my users hints: "missing zero at the end of 16184 or something like that"

**Comment by gihco** [comment]
Thanks for the clarification!
On the other hand, Berliner Morgenpost [1] - which is one of your main sources for Germany - as well as the official numbers from the German RKI [2] do not show this peek. Instead, they both report recoveries in the range of ~20,000 as in the past days.

[1] https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/
[2] https://www.rki.de/EN/Content/infections/epidemiology/outbreaks/COVID-19/Situationsberichte_Tab.html => https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Jan_2021/2021-01-27-en.pdf?__blob=publicationFile

**Comment by CSSEGISandData** [comment]
Hello @gihco 

If you look into the Morgenpost's documentation, you would see that the total number of recoveries they report are an estimation for the national level directly from RKI. However, if you were to sum the recoveries independently reported for each of the federal states (as reported in the sixth section of the page - the section after "Entwicklung der Todesfälle in Deutschland") you would arrive at the number we report on our dashboard and in our data products.

**Comment by mbender-ith** [comment]
Numbers for Jan 28 are again properly aligned to the numbers we had before Jan 27, so it seems to me the data for the Jan 27 reports were flawed "one-time".

**Comment by gihco** [comment]
Thanks @CSSEGISandData for the super quick response yesterday!
As @mbender-ith pointed out, today's numbers seem to prove that yesterday's recovered numbers - for whatever reason - were indeed not correct.
Can you please correct that one erroneous datapoint (German recovered on 2021-01-27) retrospectively?

**Comment by GismoNo1** [comment]
An errata on the 2021-01-27 recovered cases for Germany would be great. We use your data to permanently monitor the pandemic and totally agree with @mbender-ith and @gihco.

By the way: Thanks for your awesome work!
