### ISSUE TITLE
City data is gone (state/province level only now)

### ISSUE THREAD

**Issue by jkirkland-cityoflewisville-com** [CSSEGISandData/COVID-19#363]
Around 21:30 CST the "Province_State" field's data starting showing complete US state names instead of [City,State Abbreviation].  Hopefully the city/county level data will come back soon

**Comment by jrmatchett** [comment]
Bummer! Although, I understand it's probably a very labor-intensive process to compile county-specific data as the situation escalates.

**Comment by Hammerfest** [comment]
> 
> 
> Bummer! Although, I understand it's probably a very labor-intensive process to compile county-specific data as the situation escalates.

this may be true, but thats no reason to remove existing data... (I know your not in charge, just a reply for those reading)

--------------


Ya, there removal of this data is disturbing and unhelpful

**Comment by bemosior** [comment]
It's very helpful, for educational purposes, to observe patterns of spread at the city/county level. For state-level data the NY Times dashboard is fine, but I've been coming here for the granularity.

I'm guessing here, but it seems more likely that it is an accidental configuration issue, as even as recently as a few hours ago data was being added (https://github.com/CSSEGISandData/COVID-19/commit/473681f6be0ccbba896557f1649611f46ed8b891) to this repo that includes county-level granularity.

These folks are working very hard to share this information with us, so let's be patient and see what they have to say tomorrow.

**Comment by mw32** [comment]
What I'm curious is how the data is pulled. If these are all automated or manual somehow (someone pulling strings behind the scene). I really hope it's just a config error, which can be easily fixed, but without knowing what goes under the hood, hard to say.

**Comment by JeffLoucksPersonal** [comment]
Canada now Geotagging at the provincial level only, city data is gone? 
This is a big loss of transparency. We need it back. You can imagine it is a very different thing to have a geotag 2000 KM away from the actual location as it is in Ontario or Quebec,

**Comment by mw32** [comment]
I think the problem should say "Some granular data is not displayed".
At least for me, California counties are no longer displayed but I can confirm they are still there.

**Comment by jrmatchett** [comment]
The [hosted feature layer](https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c#data) was definitely changed to include only state-level data. How exactly are you confirming that the county-level data are still there?

**Comment by mw32** [comment]
Check out the last update (4-5 hrs ago) to the time series data: https://github.com/CSSEGISandData/COVID-19/commit/473681f6be0ccbba896557f1649611f46ed8b891
That still has counties in California, at least the county I was looking for.

**Comment by urbnfntsys1973** [comment]
County data seems to still be in the auto data files. Likely a decision to combine at a higher level.

**Comment by jrmatchett** [comment]
The time-series data has been compiled at 00:00 UTC. We'll see tomorrow if the next date period still includes the county-level data. Either way, that's not the data source that is has been used to render points on the map.

**Comment by ciscorucinski** [comment]
This change might be related to my suggestion in #284 

I suggested a "mechanism" to change the behavior of the grouping. This could all happen locally on our computers. This would allow people to view the USA cases on the `county`, `state`, or `country` level.

**Comment by mw32** [comment]
I hope it's not a decision to combine all the data at that high a level because granularity matters. 

I like the idea of grouping at higher level but ONLY when the view is at the bigger level.  When you zoom in it should still display granularity at the level you want to see (county is good enough for me).
In other words these grouping should be dynamic at the user interface.

**Comment by jrmatchett** [comment]
That'd be ideal, but it also places a burden on the data maintainers to provide accuracy at the finer scales. I've already noticed a few counties around me that have had incorrect data for several days.

**Comment by mw32** [comment]
Sure,  same here.  Alameda showed only 2 earlier (before it disappeared)  when there's already 3. That's minor and much better than not having anything.  That goes back to my earlier question - how is the data acquired and compiled. 
Anyway I hope I can see the granular data again.

**Comment by ciscorucinski** [comment]
@mw32 I agree with you partially. I do like the current State-level grouping as default, but I want to still see the other levels (county and country). 

Zooming in shouldn't be the trigger that switches. It should be a clear user-specified action. A new UI panel could be created that would allow you to control which grouping to use. It wouldn't include every country with cases. Only those with different groupings.

- China: Province and Country level
- USA: County, State, Country

- Korea: Districts, Province, and Country level _(not in this dataset though)_

**Comment by urbnfntsys1973** [comment]
Could change/specify a tolerance of accuracy dependent on zoom level.. Maybe?

**Comment by urbnfntsys1973** [comment]
Data of this global magnitude is huge, If a County tests positive for a case, then does further testing and determines it is negative (tests are not 99% effective yet), then the margin of error at a smaller level will be greater if data is determined between auto uploads. Not saying this is ideal, but could be why they have chosen to change the scope of the map. Better detail is better but more prone to error.

**Comment by ciscorucinski** [comment]
@urbnfntsys1973 the dataset still breaks it down via county-level, but the map is using the state-level

**Comment by urbnfntsys1973** [comment]
@ciscorucinski agreed, but for margin of error on public view may be the reason. I like all here would still prefer the more detailed view.  The data is still there you just have to modify their feature script and build your own dashboard using their data to retrieve it. I am looking into that currently.

**Comment by jrmatchett** [comment]
I've been accessing their data for a few days now to mix with other data and dashboards, and what I've observed is that the feature layer is the dataset that is updated throughout the day, while the individual date and time-series CSV files in this repository appear to be snapshots of the feature layer data taken at 00:00 UTC each day. So we'll see if the next daily snapshot still includes the more granular locations.

**Comment by mw32** [comment]
@urbnfntsys1973 zoom function is exactly what I was saying above.  This is similar to smart chart or those chart libraries often used in js.

**Comment by ciscorucinski** [comment]
@mw32 @urbnfntsys1973 the problem with a zoom trigger is when you want to view county and state-level data on the same zoom levels. You just cannot do that. 

How about this. There are 23 zoom levels. Zoom all the way out to level 0, and then count how many zooms should show the state levels (zoom 0, 1, 2 ...), and at which zoom level should it switch to county-level?

**Comment by EdMabe** [comment]
The time_series data still contains latitude and longitude and although it's a bit of work, your can create a custom Google map using the data to get greater granularity.
I made this today (please forgive my rudimentary map skills)
https://drive.google.com/open?id=10Dw_OZ928gHFoGXWzOZyXR5_QAwXyKZ7&usp=sharing

**Comment by jqnatividad** [comment]
NYTimes has Hyperlocal data behind its COVID-19 US map
https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html#us

Perhaps, they can be convinced to open source it and follow JHU’s lead?

**Comment by ciscorucinski** [comment]
@jqnatividad It makes complete sense to use county-level reporting with a US map only. Perhaps @CSSEGISandData can create another map. They have accumulated and active maps, they could add a US map

**Comment by pnisita** [comment]
This is virtually useless without the local data, especially for people in high population large states like NY, Cali, Texas, etc.  Here in Long Island, the overall state cases means nothing if we don't easily know how many are on the island itself.

**Comment by chucksings** [comment]
Like if you request they return to view by county.

**Comment by MuffleKerfuffle** [comment]
In TX, county-level Data still there in the most recent update. (14 hrs ago)
I can't seem to locate where, or which update changed to a compiled state-level result. 

<img width="1001" alt="Screen Shot 2020-03-10 at 9 37 53 AM" src="https://user-images.githubusercontent.com/50849080/76324383-eb9fae00-62b3-11ea-8c7e-cc1c935951a6.png">

**Comment by CSSEGISandData** [comment]
Please see Issue #382
