### ISSUE TITLE
In the USA confirmed cases time series the numbers are incorrect for the state of Georgia (correct on the Dashboard) 

### ISSUE THREAD

**Issue by inprosys** [CSSEGISandData/COVID-19#3632]
01/312021 13:12 EST
In the time_series_covid19_confirmed_US.csv, the entire time series data for the state of Georgia is incorrect. For example, the current value for the number of confirmed cases in the downloaded data (01302021) is 24,198 when it should be around 6,343. The total cumulative number in the downloaded data is 7,627,667 when the JHU dashboard shows it to be 905,858.

**Comment by CSSEGISandData** [comment]
Hello

Can you provide with how you are calculating these numbers? Neither numeral are present in the time series file (nor does the file include entries at the state level). The summation of all the Georgia counties for their 1/30/2021 entries equals the total displayed on the dashboard from yesterday, so it is not clear to me how you were able to calculate 7,627,667.

**Comment by inprosys** [comment]
You are correct, we do add up the individual county values to get a total for the state of Georgia. 

After your comment (thanks for the quick reply) I inspected the actual csv downloaded data, added up the counties and the total was correct as you said. The problem was in our local automated processing -- your github data was and is correct.

We add our own update file from the most current Georgia data which the state produces at around 14:50 EST.  The problem was introduced yesterday in our process which induced the error on our end yesterday and was carried forward to today.

This "issue" can be closed as an error on our part. Again, thank you for your quick response.
