### ISSUE TITLE
ARCGis REST keeps flaking out

### ISSUE THREAD

**Issue by corysimmons** [CSSEGISandData/COVID-19#364]
https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/0/1/0.pbf
```
{"error":{"code":404,"message":"The requested URL was not found.","details":[]}}
```

This happens when I go to page, click on USA, click on Kentucky.

Are you hitting rate limits? Surely they could make an exception to your app?

**Comment by rossarmer** [comment]
I've seen rate limiting API responses stating they've reached a limit and 10,000 and to try again in 60 sec often today.  I think they are bumping up next to their limit on some feature layers today.

**Comment by corysimmons** [comment]
I sent their sales dept a message requesting they remove the rate limit but they didn't reply so who knows if they'll do it.

**Comment by CSSEGISandData** [comment]
Please refer to ESRI: https://livingatlas.arcgis.com/en/home/ for any technical support issues!
