### ISSUE TITLE
Flagging Indiana deaths backlog

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#3646]
I know you all are on top of this, but on the off chance you haven't seen -- Indiana has this on their data dashboard: "Today's total deaths includes 1,507 historical deaths identified through an audit of 2020 and 2021 COVID death records and test results."

https://www.coronavirus.in.gov/2393.htm

**Comment by CSSEGISandData** [comment]
Thank you Nate! Will document in our README. I will leave this issue open so others can see.

**Comment by naterattner** [comment]
Thank you @CSSEGISandData. Do you have any initial sense of whether it will be possible to back distribute this data?

**Comment by CSSEGISandData** [comment]
Hi @naterattner it does not appear that the state is making a back distribution available at the county level - we will reach out to them to see if that data can be made available.

**Comment by CSSEGISandData** [comment]
Hi @naterattner we are still awaiting a response from the state health department, but in the interim we have distributed the difference between our state total and that of the Indiana dashboard to the unassigned, Indiana entry. We hope this is a temporary fix.

**Comment by naterattner** [comment]
Thank you for the info @CSSEGISandData

**Comment by CSSEGISandData** [comment]
Hi @naterattner and all others - we have finally been able to distribute the deaths to the county level and as such will be closing this issue.
