### ISSUE TITLE
Star (*) next to Taiwan in CSVs

### ISSUE THREAD

**Issue by somerandomcodenstuff** [CSSEGISandData/COVID-19#3648]
Hello,
I've noticed that in the CSV files under `COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/` Taiwan is listed as `Taiwan*`.  Is this intentional or is the `*` character supposed to be removed? It doesn't seem like it is serving any purpose.

**Comment by ivanMSC** [comment]
\>It doesn't seem like it is serving any purpose.
Beijing wants to know your location.

**Comment by somerandomcodenstuff** [comment]
I meant that if it points to an explanation or a note, I can't see it in the CSV or in the readme. It might be a minor detail but I think it may create confusion if a project used country names directly from the table.

**Comment by stucka** [comment]
See this https://github.com/CSSEGISandData/COVID-19/issues/690

**Comment by kivanctezoren** [comment]
Thank you, I've found the disclaimer in `COVID-19/csse_covid_19_data/README.md`.

**Comment by somerandomcodenstuff** [comment]
Thank you, I have found the disclaimer in `COVID-19/csse_covid_19_data/README.md`.
