### ISSUE TITLE
New York State and California incorrect Confirmed and Deaths. 

### ISSUE THREAD

**Issue by Monesha67** [CSSEGISandData/COVID-19#3651]
New York State and California incorrect numbers. Here’s some pictures. 

I am sending incorrect numbers on CSSEGISandData / Covid-19 
![08E9FA40-78C6-43AC-BFA0-0ACB95C3906C](https://user-images.githubusercontent.com/75553737/107125449-fca7c500-685e-11eb-8522-0342b6f6ecf8.jpeg)
![4D6A34D1-2A90-4B3C-ADEB-3D8A7D5EFD92](https://user-images.githubusercontent.com/75553737/107125451-fdd8f200-685e-11eb-80ef-2985403abbaa.jpeg)
![6C4DFF57-6C01-4A43-A9E8-062035839EEF](https://user-images.githubusercontent.com/75553737/107125452-fdd8f200-685e-11eb-80e4-36e51f0762ed.jpeg)
![6D7BE3D7-DF20-489D-A40B-81C112D20573](https://user-images.githubusercontent.com/75553737/107125454-fe718880-685e-11eb-9f1f-72dd1b22663b.jpeg)
![3EC25685-8597-46CD-9E03-7843073F7613](https://user-images.githubusercontent.com/75553737/107125456-ff0a1f00-685e-11eb-9e1b-32cc541bc2c8.jpeg)
![13B12453-550E-4C0C-B3D8-7DA4240401C2](https://user-images.githubusercontent.com/75553737/107125458-ffa2b580-685e-11eb-9d73-f38dc619e386.jpeg)
![B79F139B-3C0A-485B-BDCE-9EBB44151C5C](https://user-images.githubusercontent.com/75553737/107125460-003b4c00-685f-11eb-91b5-b9ad9ddf1632.jpeg)
Here’s the correct numbers from Worldometer website. 
![8190D070-1158-4A38-A80E-407229453EE3](https://user-images.githubusercontent.com/75553737/107125473-1c3eed80-685f-11eb-8008-ce8e95c4269a.jpeg)
![724464BA-8226-4EE8-A6AE-7A3E8ACF8786](https://user-images.githubusercontent.com/75553737/107125474-1cd78400-685f-11eb-9bfa-853a73f6a82f.jpeg)
![380C238A-4245-4C03-B433-71BA89D7337E](https://user-images.githubusercontent.com/75553737/107125476-1d701a80-685f-11eb-81a5-6223c4feacb8.jpeg)
![23135C2C-C7A1-484C-BE08-6339E20C4114](https://user-images.githubusercontent.com/75553737/107125478-1e08b100-685f-11eb-8d10-0e4f3cfbeca3.jpeg)
![DFCC0950-201F-4E34-BE86-910868A7BCF1](https://user-images.githubusercontent.com/75553737/107125481-1ea14780-685f-11eb-8960-b22f3ee552f8.jpeg)

I am hoping that you fixed this problem. Thank You!

**Comment by Monesha67** [comment]
Here’s another state that have the exact same number in your system. 
![1B5A8454-8A6C-496D-952B-C6FE4E4B4558](https://user-images.githubusercontent.com/75553737/107125703-5230a180-6860-11eb-9cea-8b513378d66f.jpeg)
![81DCB93D-E8D7-4577-8AB3-BF548F973259](https://user-images.githubusercontent.com/75553737/107125705-52c93800-6860-11eb-8c4b-a76500756091.jpeg)
![21336041-1C4E-4CE7-8C2E-FA87C00582F8](https://user-images.githubusercontent.com/75553737/107125706-5361ce80-6860-11eb-8744-861cb1265c60.jpeg)
![AFA440FF-D2A4-4207-8D06-C60478D31F09](https://user-images.githubusercontent.com/75553737/107125709-53fa6500-6860-11eb-9dbd-7d52ebfde7a4.jpeg)

Here’s a picture from Worldometer website correct numbers. I am saying that those states incorrect numbers in your system. 
![3CA7777D-6AAD-4159-B6F5-CCEADC478EBD](https://user-images.githubusercontent.com/75553737/107125774-9623a680-6860-11eb-9531-3a5a6a83cfcf.jpeg)
![BC5308BD-E8B3-48FE-94F0-AC1300046E32](https://user-images.githubusercontent.com/75553737/107125775-9754d380-6860-11eb-9a19-84fb23d4b3ca.jpeg)

**Comment by CSSEGISandData** [comment]
Hello

Thank you for using our resource. The comparison you are making is for our data published on February 5 and data from WorldoMeter published on January 6. As such, they are not directly comparable.
