### ISSUE TITLE
Deaths in Japan at 2021/1/19

### ISSUE THREAD

**Issue by AnnaNishino** [CSSEGISandData/COVID-19#3654]
Hi! Thank you always for your work.

Same question in #3611.

In JHU data, daily deaths for 2021/1/19 is 314 (4366 -> 4680).
The data source here (https://covid19japan.com/) records 104 at 2021/1/19.
According MOFA (https://covid19.mhlw.go.jp/en/), it should be around 100 as well (depending how you count).

Thank you very much!

Anna

**Comment by CSSEGISandData** [comment]
Thank you. We are currently fixing this issue.

**Comment by CSSEGISandData** [comment]
Thank you for your patience. We have resolved the issue.
