### ISSUE TITLE
Possible Error in "Patch DE data from 20200311 to 20210209"

### ISSUE THREAD

**Issue by RobertClemenzi** [CSSEGISandData/COVID-19#3668]
It appears that the wrong data column was edited in the latest Delaware patch.
As a result, the *cumulative* values in time_series_covid19_confirmed_US.csv appear to actually be the *daily* values.
The following is the last part of New Castle,Delaware,US - notice that the last value is correct and much larger than the others.

    581,582,584,587,589,591,591,46237

**Comment by rsgoodwin** [comment]
Well,  that would explain why Delaware jumped to the top of worse states when I pulled and plotted the data.

@RobertClemenzi - thanks for catching it and letting the team know.  I am sure it will get fixed soon.

![image](https://user-images.githubusercontent.com/2280241/107723402-4731a300-6c9e-11eb-91eb-46769e305669.png)

**Comment by stucka** [comment]
Thank you for flagging this! I thought I was going crazy looking at it. The time series shows about 98% of the cases in Delaware were reported Wednesday.

**Comment by CSSEGISandData** [comment]
Terribly sorry, that merge request was meant to be for deaths and not cases. We're working up a fix now.

**Comment by CSSEGISandData** [comment]
Very sorry for any inconveniences this may have caused! The cases should be repaired and the deaths should be properly allocated in #3671
