### ISSUE TITLE
Source for Slovak data?

### ISSUE THREAD

**Issue by freedomlives** [CSSEGISandData/COVID-19#3677]
Hi, I see that you rely on Worldometers for Slovak data. They don't get the complete number of deaths because the page they take it from is only giving the number of deaths where infection with SARS-CoV-2 was the primary cause of death, but not the deaths of positive individuals where it may have contributed.

To the English speaking world, the only information on deaths in Slovakia are "deaths of a SARS-CoV-2 positive individual, where it was the primary cause of death". On a government portal, only in the Slovak language, there is also information on number of "deaths of a SARS-CoV-2 positive individual, where the primary cause of death was another illness". This information can be found on https://covid-19.nczisk.sk/sk Right now the first number is 5629 deaths "from" COVID, while the latter is 1213 deaths "with" COVID, which works out to a total deaths per million of 1253, moving Slovakia up the list by nine countries.
I have written details how to navigate that portal here: https://blog.freedomlives.net/node/2

There is a Slovak github site of the Institute for Health Analysis. On there are two datasets, though only through mid-January. One contains summaries by day of the "from" and "with" death counts, the other is data on date-of-death, age-group and district of each "from" death.

Full disclosure: I live in Slovakia, and from early on I've felt like the government has been choosing very non-standard ways to measure deaths which minimize the severity of the situation. These non-standard ways, like at first doing full autopsies of victims and only counting those where the cause of death was the respiratory form of COVID-19, probably have some scientific validity. But if you're going to compare how your country is doing to others, you need to use a similar measurement. Unfortunately, based on calculation of excess deaths for 2020 compared to the five prior years, I have a suspicion that Slovak authorities only registered perhaps half or fewer of SARS-CoV-2 related deaths (2819 deaths in total had been reported till year end, excess deaths were almost 5500. On average, 4000 people die from some respiratory illness each year, of those 2500 from pneumonia, and it is hard to suppose that none of the people who are reported to have died from/with SARS-CoV-2 wouldn't have otherwise died from pneumonia, so thousands of extra deaths beyond officially reported COVID deaths...)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you very much for your message. We have adjusted our sources to collect data directly from the Slovakian ministry: https://korona.gov.sk/. We very much appreciate the difficulty in selected the correct metric for deaths and agree that it complicates comparisons between different locations. In situations such as this, we have defaulted to follow the same interpretations of the data as the World Health Organization (WHO). In this instance, the WHO data source reports the deaths from COVID, but if that situation were to change we would similarly adjust our dataset.

**Comment by freedomlives** [comment]
Thanks for the reply. I found that definition, doesn't quite fit what is known about the Slovak approach, but I guess it is close (and closer than at the beginning of the fall, as the pathologists have widened their criteria). At the end of the day, I guess the best cross-country comparisons of the fallout of the pandemic are going to be calculations of overall excess mortality. 
"A COVID-19 death is defined for surveillance purposes as a death resulting from a clinically compatible illness in a probable or confirmed COVID-19 case, unless there is a clear alternative cause of death that cannot be related to COVID-19 disease (e.g. trauma). There should be no period of complete recovery between the illness and death."
