### ISSUE TITLE
Iowa 27K New Case Error

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3702]
Iowa has 27K New Cases too many in the JH  time series on 2-19.

Perhaps this has something to do with it:

(KTIV) - Starting Feb. 19, the Iowa Department of Public Health will be making changes to the way it reports COVID-19 results on its website.

Health leaders say Iowa will no longer report individual test results, but total results instead. They say it will make the positivity rate go down.

They are making the change because at-home tests are becoming more available, and they want to prevent duplicating results on the website.

Health leaders say it's how they track other diseases, like the flu.

**Comment by CSSEGISandData** [comment]
Hi David,

We're aware of this issue, thanks for posting.
