### ISSUE TITLE
Ohio New Deaths

### ISSUE THREAD

**Issue by DavidViral** [CSSEGISandData/COVID-19#3703]
The Ohio redistribution of their Death series data dump makes no sense.

![OhioRedist](https://user-images.githubusercontent.com/62083925/108598775-9e4e0c80-735d-11eb-878b-0c867b2729fe.PNG)

**Comment by CSSEGISandData** [comment]
Thank you. We will look into this issue.

**Comment by JustaNormalGuy230** [comment]
Hi David:

Thanks for the post.  Have you caught this link (it's dated Feb 15th but may reveal further info)?:

https://www.cincinnati.com/story/news/2021/02/15/ohio-covid-19-death-backlog-4275-deaths-added-doubling-count-november-december/4484171001/

**Comment by davidjayjackson** [comment]
Thanks, for the link. Lots of good information. David
