### ISSUE TITLE
Iowa alteration to reporting method - artificial spike in data

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#3705]
Hello all,

We are aware of a 27k spike in the case data for Iowa. This is due to [an alteration](https://ktiv.com/2021/02/19/iowa-changing-how-it-reports-covid-19-results/) in how they are choosing to report positive cases (rather than reporting individual cases they will be reporting individual test results). This change has the affect of adding 26,775 positive test results that are either not affiliated with a known case or represent multiple positive test results for one individual. We're in internal discussions for how to proceed but please know that we are aware. This announcement will be updated as we sort this out.

**Comment by hdschulte** [comment]
This page on the Iowa COVID dashboard does report numbers for "individual cases"
https://coronavirus.iowa.gov/pages/case-counts

I cannot locate a historical database that parses numbers by the day for the above page, so if someone has that location it would be helpful.

**Comment by CSSEGISandData** [comment]
This issue has been fixed with PR #3756 and a new announcement is imminent.
