### ISSUE TITLE
Are the time series data really csv format?

### ISSUE THREAD

**Issue by pmcculey** [CSSEGISandData/COVID-19#371]
They save for me as html......

**Comment by stelaninja** [comment]
You have to choose raw format.

**Comment by 2010019970909** [comment]
Yes, they are. You can download them (RAW files) via the following links:
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv

**Comment by pmcculey** [comment]
Thank you all for your input.....
