### ISSUE TITLE
No new data - Israel 20.2.2021

### ISSUE THREAD

**Issue by RealA10N** [CSSEGISandData/COVID-19#3711]
As the title says, data for Israel is not updated in 20.2.2021 and stayed exactly the same as in 19.2.2021

### 20.2.2021
https://github.com/CSSEGISandData/COVID-19/blob/965479418db1346faf22242c5c8672e5a42b04ce/csse_covid_19_data/csse_covid_19_daily_reports/02-20-2021.csv#L292

### 19.2.2021
https://github.com/CSSEGISandData/COVID-19/blob/965479418db1346faf22242c5c8672e5a42b04ce/csse_covid_19_data/csse_covid_19_daily_reports/02-19-2021.csv#L292

**Comment by CSSEGISandData** [comment]
Hello,

We have investigated our internal data collection, contemporaneous news reports, and other aggregating sources and as near as we can tell the Israeli dashboard failed to update this day. As such, we will be maintaining the data we had previously. We recommend all users use smoothing algorithms when using our data for modeling or evaluative purposes.
