### ISSUE TITLE
Ascension Island

### ISSUE THREAD

**Issue by Helmeda** [CSSEGISandData/COVID-19#3716]
Ascension Island has had 4 positive cases in quarantine with the first 2 confirmed on 6 September. They have all since recovered.

https://www.ascension.gov.ac/covid-19-response-level-escalated-to-level-2-red
https://www.ascension.gov.ac/covid-19-response-level-escalated-to-level-2-red-2 
https://www.ascension.gov.ac/covid-19-response-level-escalated-to-level-2-red-3

**Comment by CSSEGISandData** [comment]
Thanks for your information. After checking those cases and recoveries, we will add them to the time series tables and the dashboard.

**Comment by CSSEGISandData** [comment]
Hello,

You should now see Ascension Island in our time series and daily reports as an admin level 1 region of the UK listed under "Saint Helena, Ascension and Tristan da Cunha". Thank you for notifying us of these missing cases.
