### ISSUE TITLE
Active cases spike for Germany 26/02/2021

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#3733]
Hi all,

Active cases for Germany have spiked quite significantly between yesterday and today. My assumption is that confirmed cases are reported as active cases. 

Edit: Just followed up on the source data on https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/ and it seems they have problems providing the data for Germany.

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the notification. We're looking into the cause of the issue and should have the corrupt data patched in the short term.
