### ISSUE TITLE
403 forbitten

### ISSUE THREAD

**Issue by downFast** [CSSEGISandData/COVID-19#374]
HI
I am receiving 403 (Forbidden) when using GET for these csvs, what happened?

**Comment by Bost** [comment]
Use [curl](https://curl.haxx.se/) or [wget](https://www.gnu.org/software/wget/) from the command line and send us results.

**Comment by downFast** [comment]
It says

message: "API rate limit exceeded for 2.47.160.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
documentation_url: "https://developer.github.com/v3/#rate-limiting"
