### ISSUE TITLE
Spain (Catalonia) Data drop of confirmed cases

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#3748]
Hi all,

Confirmed cases in Catalonia dropped from 582,073 on 2021-03-02 to 503,209 on 2021-03-03. Had a look at your source (https://www.rtve.es/noticias/20210302/mapa-del-coronavirus-espana/2004681.shtml) but was unable to pin-point the issue unfortunately. I have not checked the other Spanish states, so I cannot tell you if this impacts all states.

As always, you are doing fantastic work!

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hello

In their daily report, the Spanish health ministry has confirmed that they have removed cases that had been double counted with Catalonia ([available here](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Actualizacion_323_COVID-19.pdf)):

** La Comunidad de Cataluña ha eliminado casos duplicados. Estos duplicados se generaron al actualizar la información de casos ya registrados en el sistema informático SiViEs con un código de
identificación diferente al asignado originalmente. Se ha procedido a corregir las series de datos.
