### ISSUE TITLE
Czech new confirmed doesnot match

### ISSUE THREAD

**Issue by tom-maca** [CSSEGISandData/COVID-19#3751]
Your Non-US data sources at the country/region for the March 2nd: 12 191
Czechia Ministry of Health: https://onemocneni-aktualne.mzcr.cz/covid-19

The same source - ceck it on the same URL: Czechia Ministry of Health: https://onemocneni-aktualne.mzcr.cz/covid-19 : 16 642

More days are affected. 

Regards, 

Tom
![obrazek](https://user-images.githubusercontent.com/63140229/109782013-b7ca4080-7c08-11eb-808b-148e2f58b3f5.png)

**Comment by CSSEGISandData** [comment]
Hello

The data you are comparing ours to is the newly reported data as of _this morning_. Czechia publishes data for the previous day the following morning, which is after our daily products have been generated and published. If you were to compare the most recent two days in our time series file, you would find the difference equals 12,301, which is the number reported in the total below the entry you have highlighted. Further, if you were to look at the dashboard, you would see that our current reporting matches that of the Czechia Health Ministry. This number (currently 1,269,058 confirmed cases) will persist until tomorrow morning, which is after the daily reports and time series are published, and as such our reported cases for Czechia on 03/03/2021 will be 1,269,058.
