### ISSUE TITLE
Rhode Island updated deaths thru March 1 

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#3764]
The March 1, 2021, revision of Rhode Island death data appears to be incorrect across a long time-span for the files sitting in the https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports and https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us links. Deaths are more similar to fluctuating daily death type data than to cumulative totals. Total case counts appear to still be correct. Time period most strongly affected is March 27 through October 11, 2020. The problem is apparently not present in the time series version hosted on your website at https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series. The error was not present in the February 14 version of the data files in the *daily_reports and *daily_reports_us, although other errors in Rhode Island deaths needing correction apparently were.

**Comment by GWMW** [comment]
The March 1 update of many months of Rhode Island data have a serious error in the period from May 31, 2020 through October 11, 2020. Total cumulative deaths appear to have been replaced with new daily deaths during this period of time. I am not promising that the death counts in the next few weeks after October 11 are reasonable in the period where deaths ramp back up. The entire revision for Rhode Island seems questionable and needs to be reconsidered.

**Comment by CSSEGISandData** [comment]
Hello

I'm not able to identify this issue in our data set - we have no negative deltas in cumulative deaths at the state level which would be the case if the data represented daily deaths. By chance, are you looking at the unassigned, Rhode Island entry in isolation?

**Comment by GWMW** [comment]
I am looking at all Rhode Island entries. The cumulative deaths drop on a daily basis many times, including May 8 to 9, May 29 to 30, May 30 to May 31, July 30 to 31, Aug. 7 to 8, Aug. 30 to 31, Oct. 11 to 12. I have rechecked several dates in this period by pulling down the data again and the problems don't appear to have gone away. I am happy to send you summary death counts by date if you want me to.

**Comment by CSSEGISandData** [comment]
Hello

Can you walk me through how you are downloading the data and calculating the state death totals? Perhaps there is a mistake in a daily report, if that is the file you are using. I can confirm that there are no drops in death at the state level in time_series_covid19_deaths_us.csv. This is also the file that used for the visualization on [the dashboard](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), which has no negative deltas at the state level. 

For example, the state level death totals for May 7-10 are 499, 521, 536, and 550. August 6-9 is 1034, 1036, 1037, and 1037.

**Comment by GWMW** [comment]
Here are the first 11 columns from May 30 and 31 from the csse_covid_19_daily_reports_us

Province_State | Country_Region | Last_Update | Lat | Long_ | Confirmed | Deaths | Recovered | Active | FIPS | Incident_Rate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Rhode   Island | US | 5/31/2020 2:32 | 41.6809 | -71.5118 | 14819 | 154 | 1225 | 12883 | 44 | 1398.862
Rhode   Island | US | 6/1/2020 2:32 | 41.6809 | -71.5118 | 14928 | 5 | 1252 | 12958 | 44 | 1409.151

 I have not been using the time_series_covid19_deaths_us.csv, but rather have been downloading what I assumed was an alternate mostly complete set of data in the csse_covid_19_daily_reports.csv and then extracting the US data (as well as summarizing data for the rest of the world). 

Could the problem simply be that you've had a problem with the csse_covid_19_daily_reports.csv and csse_covid_19_daily_reports_us.csv files for the Rhode Island data? One that is never existed or was properly fixed in the time_series_covid19_deaths_us.csv version?

**Comment by GWMW** [comment]
Hi there,

    I believe I have caught and handled all of the cases in which formats for items like STATE NAME varied from early on in the reporting period (February, March, April, May of 2020) on up through the present, but I have gone ahead and done some rechecking to verify that the problem is not in my methods (which have always used the https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports link to access the daily files). I will not bore you with all the details of how I have tidied up the data to sit nicely inside of Excel spreadsheets, but here is a short version of the process. Every two weeks on a Monday I download all of the individual daily files from January 22, 2020, on up through the most recent day of March 1, 2021, into an empty directory on my Dell Precision 3630. I then process them using Python scripts robust enough to handle all the various oddities in “site naming” nomenclature used over the entire time period, stripping out all of the HTML code and producing a clean “.TXT” file suitable for opening in Python or Excel or Word. These revised daily data files contain latitude and longitude from March 1, 2020, onward, the timestamp given to the file on your website, total case counts, total deaths, recoveries, etc. The full set of headers I process are as follows: FIPS          Admin2 Province_State               Country_Region                Last_Update       Lat         Long_    Confirmed           Deaths               Recovered           Active    Combined_Key   Incident_Rate     Case_Fatality_Ratio

   The “Incident_Rate” and “Case_Fatality” values first appear on May 29, 2020. The files hosted on your website are in the “Pretty/Searchable” format through July 17, and generally are in the “TooBigToBePretty/Searchable” format after that date, except for 14 individual days, mostly in September, when you reverted to using the “Pretty/Searchable” format. Another Python script then opens each of the revised daily files to pull out the data of interest one category at a time (case counts, deaths, recovered, active, incident rate, and case fatality), and writes it first into a Python dictionary one date at a time, and then finally out to a “.TXT” file. Processing takes between 2 and 3 hours to run the entire time period for a single category such as total case counts or total deaths. The text files are then opened in Excel and copied into a TAB that had held the data summary from two weeks earlier (as a new spreadsheet). The summary data files are padded out through Dec. 31, 2021, in the hopes that such a time is far enough away that I can go on to looking at and worrying about other topics after then. Of course, the code would not be particularly hard to revise to include another year or two, if god forbid, that turns out to be necessary.  

   My summarized data files match nearly all other summaries I have compared them to, but I have to admit that I have seldom compared them directly to your own “time_series” data files. I have looked at a number of the individual daily files in the csse_covid_19_daily_reports by just opening them in my Firefox browser window, and the data for Rhode Island deaths in them matches with the values I have extracted through my Python scripts. As I said before, the data for COVID deaths for Rhode Island from March 27 through October 11 appears to just be the daily new deaths rather than the cumulative total deaths. The values you are reporting jump on October 12, and I can’t tell exactly  what you have done. The period from March 27 through October 11 totaled 9052 deaths (assuming the data values in that time period were really just the raw daily deaths), but then your figures jump to only 1159 on October 12, so I don’t know if someone adjusted out approximately 7800 deaths as of October 12. 

   I am happy to share my Python scripts with anyone who would like them, or even my biweekly summaries, but right now I am just hoping that we can clear up whatever is funky about Rhode Island’s data. Feel free to call me on my cell phone at 541-207-2440 if you think there is any reason to talk this over directly.

 

Sincerely,

George Mueller-Warrant, PhD

Research Agronomist, USDA-ARS (retired) and Courtesy Associate Professor at Oregon State University

 

Cell phone: 541-207-2440

**Comment by GWMW** [comment]
I have gone back to the Feb.14, 2021, version of the Rhode Island data, and find that it is drastically different from that in your March 1, 2021, update. Specifically, the Feb. 14 version has the "to be expected" day to day behavior of cumulative death rates either increasing or staying the same across the entire period up to Feb. 14, 2021. The total deaths as of your Feb. 14 file in the https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports link for Rhode Island through Feb. 14 are 2290 (and total cumulative cases are 120,821). The same 120,821 cumulative case count is present in your March 1 revision of the ".CSV" files in https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports. The Feb. 14 entries for Rhode Island in your March 1 revision of the "02-28-2021.csv" file reports 2462 total deaths, a figure that is at least roughly similar to that in your original Feb. 14, 2021, file of 2290 deaths. I assume that the 172 additional deaths through Feb. 14, 2021, are what were intended to be included in the revision, but I can't say that they were necessarily handled properly given the messed up data through Oct. 11, 2020. 
  Hope this information is somewhat helpful in your figuring out what went wrong in your update of RI deaths on March 1, 2021.

**Comment by CSSEGISandData** [comment]
Thank you for bringing this to our attention! RI deaths should now be resolved with #3791

**Comment by GWMW** [comment]
Did your correction also include https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports or just the https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us ? 

 

George Mueller-Warrant

**Comment by GWMW** [comment]
I don’t want to just keep bothering you, but the fix #3791 was only applied to the *daily_reports_us files and not to the similarly messed up *daily_reports (world-wide) files. 

Do I need to start a new active issues report, or are you monitoring replies to the close cases?

 

George Mueller-Warrant

 

 

From: ***@***.*** ***@***.***> 
Sent: Monday, March 8, 2021 8:42 PM
To: 'CSSEGISandData/COVID-19' ***@***.***>
Subject: RE: [CSSEGISandData/COVID-19] Rhode Island updated deaths thru March 1 (#3764)

 

Did your correction also include https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports or just the https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us ? 

 

George Mueller-Warrant
