### ISSUE TITLE
Problem with time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv

### ISSUE THREAD

**Issue by CleHou** [CSSEGISandData/COVID-19#3778]
Hello, 

Per the last update, `time_series_covid19_confirmed_global.csv`and `time_series_covid19_deaths_global.csv`became the data shown below:
```
{
    "success": false,
    "message": "internal error",
    "data": null
}
```

**Comment by Antoinelypro** [comment]
Arf, hopefully it does not come from covid tracking stopping data collection.

**Comment by RobertClemenzi** [comment]
It is ok now - Thanks

**Comment by CSSEGISandData** [comment]
Sorry - we will have to investigate the cause. #3779 fixed this issue. Apologies all.
