### ISSUE TITLE
Henrico, VA Data Issue on March 4th

### ISSUE THREAD

**Issue by GiorgiLomaia** [CSSEGISandData/COVID-19#3783]
Good morning, cumulative number of cases in Henrico, VA on March 4, 2021 (21,571) were less than cumulative number of cases on March 3, 2021 (21,685).  Is this a state data issue?

**Comment by CSSEGISandData** [comment]
Hello! Further investigation of this issue shows that the Virginia Department of Health did reported 21,571 cumulative cases on March 4, 2021 and 21,585 cumulative cases on March 3, 2021

See details below. Thank you for the inquiry!
 
Dashboard: https://www.vdh.virginia.gov/coronavirus/
Link to the data source from the dashboard above: https://data.virginia.gov/Government/VDH-COVID-19-PublicUseDataset-Cases/bre9-aqqr

<img width="1044" alt="Screen Shot 2021-03-08 at 1 46 11 PM" src="https://user-images.githubusercontent.com/60674295/110366721-a7550400-8014-11eb-8315-f162d2ea4e48.png">

<img width="1041" alt="Screen Shot 2021-03-08 at 1 52 50 PM" src="https://user-images.githubusercontent.com/60674295/110367366-95279580-8015-11eb-9f51-b8c805ff4937.png">
