### ISSUE TITLE
Utah Case Decline 3/7?

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3784]
I'm seeing `374,287` cases for Utah for March 7, 2021, which is a drop from the prior day. Meanwhile, the [Utah dashboard](https://coronavirus.utah.gov/case-counts/) currently shows `374,850`. Any insight on the difference?

**Comment by CSSEGISandData** [comment]
Thank you for noticing this issue! We are currently working to resolve this discrepancy.

**Comment by CSSEGISandData** [comment]
The issue is now resolved and the data has been adjust accordingly.
