### ISSUE TITLE
Chile Aysen Recovery Cases on Mar 07

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#3787]
Hello, 

Recovery cases for Chile Aysten does not look correct with 51022 on Mar 7, while confirmed cases are 3176 and deaths are 25.

Aysen | Chile | 3/7/2021 | -45.9864 | -73.7669 | 3176 | 25 | 51022 | -47871 | Aysen, Chile

Could you have a look?

**Comment by CSSEGISandData** [comment]
Hello

Looks to have been a source error, similar to #3785. #3788 will resolve this issue.
