### ISSUE TITLE
Problem with time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv

### ISSUE THREAD

**Issue by CleHou** [CSSEGISandData/COVID-19#3793]
Same problem as yesterday (cf #3778 )

Per the last update, time_series_covid19_confirmed_global.csvand time_series_covid19_deaths_global.csvbecame the data shown below:
```
{
    "success": false,
    "message": "internal error",
    "data": null
}
```

**Comment by msgoussi** [comment]
![image](https://user-images.githubusercontent.com/18138496/110447237-12fca700-80d1-11eb-982e-0f7ebf7a2774.png)

**Comment by CSSEGISandData** [comment]
#3795 will revert the merge that caused this issue
