### ISSUE TITLE
Delayed automated update for US

### ISSUE THREAD

**Issue by GiorgiLomaia** [CSSEGISandData/COVID-19#3797]
Good morning! I've noticed the files have been updated with a delay as called out in the file names today and yesterday. Are files going to be updated with an automated delay going forward or is this a temporary issue (if so, do we know for how long?). Thank you.

**Comment by CSSEGISandData** [comment]
Hello,

We have had automated delayed updates for several US states since the end of January. For details, please see #3590. There were issues in generating the data files the last two days, we are investigating the cause.
