### ISSUE TITLE
Data Error: Total tested for Arizona/US almost doubled on  03/08

### ISSUE THREAD

**Issue by wolpert** [CSSEGISandData/COVID-19#3800]
Looks like the "Total_Test_Results" for Arizona/US almost doubled. From the files in csse_covid_19_data/csse_covid_19_daily_reports_us you can see the entries below per date 

["Total_Test_Results"] 2021-03-06 3818450
["Total_Test_Results"] 2021-03-07 3842945
["Total_Test_Results"] 2021-03-08 7908105
["Total_Test_Results"] 2021-03-09 7930064

**Comment by wolpert** [comment]
Data error still there as of today

**Comment by wolpert** [comment]
Checking again to see if anyone had time to look at this issue. There is around 7 million people in Arizona... I would not expect to see almost 8 million people tested.

**Comment by wolpert** [comment]
Not sure what's going on.... Looks like the historical data was patched here: https://github.com/CSSEGISandData/COVID-19/commit/10cef56b2a5f53520a6adabfb864880b275cb264 by Ryan Lau which significantly changes the historical numbers. Trying to see if details can be posted here.

**Comment by CSSEGISandData** [comment]
Hello, 

Apologies for the delayed response. The discrepancy in Arizona's testing data was a result of the change in the types of testing data that was reported. Currently, Arizona Department of Health and Services are reporting "Total Tests Conducted" and is defined by them as "Diagnostic tests include PCR and antigen testing" (See link below). The large historical correction in the data was to align our data with their current reporting. Sorry for any confusion. 

https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php
