### ISSUE TITLE
More to fix for the Rhode Island deaths

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#3801]
The #3791 correction to Rhode Island deaths in https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us also needs to be applied to the Rhode Island death data in https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports.

**Comment by CSSEGISandData** [comment]
Thank you for bringing this issue to our attention. It should now be fixed and synchronized with #3821
