### ISSUE TITLE
where to find the data from Guadeloupe

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [CSSEGISandData/COVID-19#3804]
Who can tell me where to find the data from Guadeloupe, thanks.

**Comment by CSSEGISandData** [comment]
Hello,

Please explore the data files available here: https://www.guadeloupe.gouv.fr/Politiques-publiques/Risques-naturels-technologiques-et-sanitaires/Securite-sanitaire/Informations-coronavirus
