### ISSUE TITLE
Buchanan, Missouri (29021) cases 31% increase in cases.

### ISSUE THREAD

**Issue by allaboutjeeps** [CSSEGISandData/COVID-19#3813]
The positive cases in Buchanan, Missouri (29021) jumped from 6,984 in 3/10/2021 to 9,139 in 3/11/2021.

COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/03-10-2021.csv

COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2021.csv

Could be related to handling of unassigned cases? Related to #3812 and #3806.

Thanks for all of the phenomenal work and efforts on this!

**Comment by CSSEGISandData** [comment]
Hello,

The case total now represents the summation of confirmed and probable cases reported by the Missouri Department of Health.

**Comment by allaboutjeeps** [comment]
Thanks for the response as I was unable to find any mention of that on the Missouri DOH website. Appreciate the support!
