### ISSUE TITLE
Possible errors in Canada, France, UK, and Netherlands on March 12th, 2021

### ISSUE THREAD

**Issue by EdJohnsen** [CSSEGISandData/COVID-19#3814]
I believe that the time_series_covid19_deaths_global.csv has some errant entries related to (at least) the above countries.

Those countries seem have multiple entries for single dates... I am guessing that data (maybe entire rows) from a different source (perhaps daily deaths?) snuck their way into the table.

**Comment by CSSEGISandData** [comment]
Hello,

The listed countries all have multiple entries in the "Province/State" column but these have been place for many months. Is this a new problem you have just identified? How are you ingesting the data?

**Comment by EdJohnsen** [comment]
Many thanks for the instant response!

I have been ingesting this data a few times a week for a couple months or so; really appreciate it.
I pull the same basic data from a couple other sources as well (OWID and DataHub).
Today was the first day I noticed a difference.

Based on your response, I'm guessing that I'd just been lucky until today that my ingestion method handled these outliers-by-number-of-entry-rows.

I'll just tell my ingestion method to consider information in the "Province/State" column when choosing whether to use a related row based on the "Country/Region" column value.

Thanks again.
