### ISSUE TITLE
The new Covid-19 cases in Czechia are moved +1 day

### ISSUE THREAD

**Issue by juanito-cz** [CSSEGISandData/COVID-19#3819]
Dear GitHub,

when you compare the data, that you send to Google.cz homepage you can see, that the whole "new cases" are moved +1 day. 

You can find it by comparing all the lowest/highest peaks. The problem is in the source data or in the upload to Google. 

Here are the official numbers from Czech Ministry of Health - the 1st graph are the new cases.
![image](https://user-images.githubusercontent.com/80647521/111082959-66288c80-850b-11eb-9b05-dee6919be413.png)

https://onemocneni-aktualne.mzcr.cz/covid-19
(the stats in all the Czech media looks the same as there)

The numbers at Google.cz are moved +1 day 
![image](https://user-images.githubusercontent.com/80647521/111082909-2366b480-850b-11eb-9b33-ca425f268457.png)

Thank you for checking it. J.

**Comment by paveljasek** [comment]
I was checking the data about Czechia included in daily reports around these dates to further validate the point of juanito-cz.

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-06-2021.csv
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
,,,Czechia,2021-03-07 05:21:54,49.8175,15.473,1312164,21558,1126420,164186,Czechia,12252.929363407278,1.6429348770428087


https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-07-2021.csv
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
,,,Czechia,2021-03-08 05:24:48,49.8175,15.473,1321331,21717,1131209,168405,Czechia,12338.530403730252,1.6435700063042493


https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-08-2021.csv
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
,,,Czechia,2021-03-09 05:28:19,49.8175,15.473,1325291,21882,1135251,168158,Czechia,12375.508708484147,1.651109077176258


The value 3960 that juanito-cz noticed seems to be calculated as 1325291-1321331=3960, so as the number of Confirmed cases on 2021-03-09 minus the number of Confirmed cases on 2021-03-08.

These is a similar recent issue https://github.com/CSSEGISandData/COVID-19/issues/3751 that is looking at similar differences from the Czech Ministry of Health, but does not explain the attribution to the original date.

To conclude, in daily_reports CSVs the number of new cases look like being calculated for 2021-03-08, whereas the official data source that juanito-cz reported assigns the value to 2021-03-07.

**Comment by CSSEGISandData** [comment]
Hello,

This issue appears to be a result of a semantic difference between how we define the date of cases and that of the Czechian Health Ministry. If you were to presently look at the source you linked, you would see that they reported 3,291 new cases at 7:59 AM on March 15. For us, as those cases were reported after 12 AM EST on March 15, the cases are most appropriately dated as having been reported on March 15. This is our standard for all locations globally (with two exceptions for some regions in India and California). The Czechian Health Ministry, in their "daily overview" graphic dates these same cases as having been reported March 14.

Of note, a consequence of the reporting system of the Czechian Health Ministry is that they have reported 0 new cases for March 15.

@paveljasek the reason for the slight discrepancies between our time series and that of the Czechian Health Ministry is the disclaimer on the dashboard: "S ohledem na fakt, že u publikovaných dat probíhá validace a průběžné doplňování hlášení, může u přehledů osob s laboratorně prokázaným onemocněním COVID‑19 dle hlášení KHS a laboratoří docházet zpětně k drobným změnám. Poslední aktualizace dat v tomto přehledu byla provedena k půlnoci předchozího dne."
