### ISSUE TITLE
Possible backlogged cases in Alabama, US (csse_covid_19_daily_reports_us)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#3825]
Hi all,

it seems that there were significantly more confirmed cases in Alabama reported on 2021-03-15 compared to the days before, see below:

2021-03-13: 503305 
2021-03-14: 503673 (+368)
2021-03-15: 508229 (+4556)

All the best,

Christoph

**Comment by anthonydb** [comment]
Yes, there's a note about that on Alabama's state dashboard:
https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7

```
The Alabama Department of Public Health (ADPH) processed a backlog of 4007 cases on 03/14/21. These will be classified as confirmed and probable COVID-19 cases reported on 03/15/21 even though the tests were performed on during October 1, 2020 through January 1, 2021.
```

**Comment by c-hera** [comment]
Hi Anthony,

thanks for checking!

All the best,

Christoph
