### ISSUE TITLE
Palestine shows up as `occupied Palestinian territory`

### ISSUE THREAD

**Issue by AtomicNicos** [CSSEGISandData/COVID-19#383]
I don't disagree, but it might shock some people...

**Comment by Bost** [comment]
Political disagreements like this are also one of the motivations behind the https://github.com/Bost/corona_cases/issues/1 Everybody please learn your lesson. Thank you.

**Comment by CSSEGISandData** [comment]
The names of locations included on the Website correspond with the official designations used by the U.S. Department of State.
