### ISSUE TITLE
Issue with French data - new source available

### ISSUE THREAD

**Issue by TaoSunVoyage** [CSSEGISandData/COVID-19#3830]
Hello there,

I noticed that the French data is abnormal in recent days:
|3/14/21|3/15/21|3/16/21|3/17/21|
|--|--|--|--|
|4043769|4043769|4080012|4080012|

I doubt it's because your source of French data was not updated regularly. 

According to README, your source is this dataset from French government: https://www.data.gouv.fr/en/datasets/donnees-relatives-a-lepidemie-de-covid-19-en-france-vue-densemble/. 

However, as it says at the top of that page, the data is now available in a new dataset: https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/:

> Point d'attention: les données sont désormais disponibles sur [ce jeu de données](https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/).

In the past, we have already experienced similar issues (e.g. #3704) due to the irregular updating schedules of the dataset you have been using. On the other hand, I have been watching this new dataset for a while and it turns out that the new one is updated on a more regular and stable basis. 

Would you please consider changing your source of French data?

Thanks.

**Comment by CSSEGISandData** [comment]
Hello

Thank you for your message. As documented in our README, our priority source for France has been altered to their [government dashboard](https://dashboard.covid19.data.gouv.fr/). Looking at our commit history, it appears that the government dashboard failed to update for these two days. We will investigate a back distribution from our alternative source and hopefully correct our data.

CSSE
