### ISSUE TITLE
Alterations to Oklahoma Reporting Schedule

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#3831]
As detailed in the following [press release](https://kfor.com/news/coronavirus/oklahoma-dept-of-health-switching-from-reporting-covid-19-daily-to-weekly/), the Oklahoma Department of Health is altering their reporting schedule. Relevant to our reporting, the following will be their new practice:

- County-level case data and confirmed deaths updated on Wednesdays only.
- State-level case counts updated Monday through Friday through daily reports.

Functionally, we will use the daily reports to add cases to our Unassigned, Oklahoma category such that our state level cases align with the state reporting. These cases will presumably be distributed to the counties on Wednesdays, so expect cyclical increases and decreases for that entry specifically.

**Comment by anthonydb** [comment]
@CSSEGISandData  I'm seeing no change to Oklahoma cases over the last several days, including in Unassigned. Is that related to this ticket?
