### ISSUE TITLE
Catalonia removed 80K cases 3/2

### ISSUE THREAD

**Issue by Jferrie1** [CSSEGISandData/COVID-19#3832]
Does anyone have a reliable source to restate this data? seeing other sites restating, but having issues locating data

**Comment by CSSEGISandData** [comment]
Hello,

We have been on the lookout for this data as well. As near as we can find, the only historical data published by the Spanish Health Ministry that contains this data is at [the following link](https://cnecovid.isciii.es/covid19/#documentaci%C3%B3n-y-datos). However, based on the [README for these files](https://cnecovid.isciii.es/covid19/resources/metadata_tecnica_ccaa_prov_res.pdf), the dates to which these historical cases are distributed are not equivalent to "date of report", which is the standard for our repository. As such, we are unable to use it to correct our dataset. If you are able to locate a dataset with the appropriate datatype, please reopen this issue.

**Comment by davidjayjackson** [comment]
Btw,  Spain, only reports numbers Monday - Friday.  Saturday and Sundays
are added onto Monday..
