### ISSUE TITLE
https://github.com/CSSEGISandData/COVID-19/blob/ba428278d4a310e90337e9460a1607bd90572db0/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv#L212

### ISSUE THREAD

**Issue by wez378** [CSSEGISandData/COVID-19#3846]
https://github.com/CSSEGISandData/COVID-19/blob/ba428278d4a310e90337e9460a1607bd90572db0/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv#L212

__Originally posted by @monicapires in https://github.com/CSSEGISandData/COVID-19/issues/3840__

**Comment by CSSEGISandData** [comment]
Hello,

Is there a specific issue with this file?

**Comment by monicapires** [comment]
After checking, no.
Can be closed
