### ISSUE TITLE
Australian Time Series Data incorrect

### ISSUE THREAD

**Issue by GregAyling** [CSSEGISandData/COVID-19#3847]
Total confirmed cases for March 11, 2021 for Australia is 58,204. For March 12, 2021 is 29,112. 
The values for March 12 and later appear to be correct, but all values before that appear to be double what they should be.

See file https://api.covid19api.com/total/dayone/country/AU

Also, in same file, there is a value for active cases on March 7, 2021 which is much larger than surrounding values.

**Comment by CSSEGISandData** [comment]
Hello

I am unable to identify this error in either our time series or daily reports. Could you please direct me to the file in our repository where you are seeing this error? We do not manage the file you have linked in the issue.

**Comment by GregAyling** [comment]
You may need to educate me on how you get your Australian data then.

Here is an extract from the end of the file:

{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":58092,"Deaths":909,"Recovered":22929,"Active":28137,"Date":"2021-03-07T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":58122,"Deaths":909,"Recovered":22931,"Active":5221,"Date":"2021-03-08T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":58148,"Deaths":909,"Recovered":22936,"Active":5229,"Date":"2021-03-09T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":58180,"Deaths":909,"Recovered":22945,"Active":5236,"Date":"2021-03-10T00:00:00Z"},**_{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":58204,"Deaths":909,"Recovered":22949,"Active":5244,"Date":"2021-03-11T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29112,"Deaths":909,"Recovered":22952,"Active":5251,"Date":"2021-03-12T00:00:00Z"},_**{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29117,"Deaths":909,"Recovered":22957,"Active":5251,"Date":"2021-03-13T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29130,"Deaths":909,"Recovered":22957,"Active":5264,"Date":"2021-03-14T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29137,"Deaths":909,"Recovered":22958,"Active":5270,"Date":"2021-03-15T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29154,"Deaths":909,"Recovered":22960,"Active":5285,"Date":"2021-03-16T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29166,"Deaths":909,"Recovered":22962,"Active":5295,"Date":"2021-03-17T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29183,"Deaths":909,"Recovered":22963,"Active":5311,"Date":"2021-03-18T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29192,"Deaths":909,"Recovered":22965,"Active":5318,"Date":"2021-03-19T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29196,"Deaths":909,"Recovered":22966,"Active":5321,"Date":"2021-03-20T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29206,"Deaths":909,"Recovered":22971,"Active":5326,"Date":"2021-03-21T00:00:00Z"},{"Country":"Australia","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29211,"Deaths":909,"Recovered":22977,"Active":5326,"Date":"2021-03-22T00:00:00Z"}]

**Comment by CSSEGISandData** [comment]
Hello

I do not believe this is an issue with our data files and is due to the means by which whomever is managing this API is ingesting our data. If you are able to locate this error in our data files, please direct me to the specific file such that it can be rectified. If you were to observe our [time series file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv), you will see that this error is not present. Nor in the [daily report](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2021.csv) for March 11.
