### ISSUE TITLE
Mix-Up of Confirmed and Active Cases in Thailand (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#3848]
Hi all,

It seems that the data source you are using for infection numbers in Thailand has changed its layout. For today, confirmed cases are reported as active, for detailed information see below:

 Country_Region | Last_Update | Confirmed | Active
 Thailand             | 21/03/2021  | 27594        | 1054
 Thailand             | 22/03/2021  | 27594        | 27713

All the best and as always, thanks for the great work!

Christoph

**Comment by CSSEGISandData** [comment]
Hello, 

Thank you for the notice! We have investigated the issue and corrected our data to align with the source. Please reference 
#3850 for the data changes and the updated README.md for the associated source. 

Thank you
