### ISSUE TITLE
What is the data source for the live map?

### ISSUE THREAD

**Issue by meldehi** [CSSEGISandData/COVID-19#385]
What is the data source for the live map at https://coronavirus.jhu.edu/map.html
It looks like it is more up to date than what is in the repo here.
On the map is shows as of now: Last Updated at (M/D/YYYY) 3/10/2020, 10:13:32 AM
While this folder COVID-19/csse_covid_19_data/csse_covid_19_time_series/ was updated 18 hours ago.

Also confirmed cases in the map for US is 791 while the summation on the file is 605 cases.

Current time for reference: 3/10/2020, 12:00:00 PM PST

**Comment by bendada3** [comment]
+1

**Comment by jrmatchett** [comment]
https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c#data

**Comment by meldehi** [comment]
Thanks @jrmatchett
