### ISSUE TITLE
Case in San Mateo has been stale 

### ISSUE THREAD

**Issue by roxyshuwang** [CSSEGISandData/COVID-19#3853]
Hi there

We have noticed that county case in San Mateo have been stale for 5 days (03-16 to 03-21) 
Which is different from their main health dashboard: https://www.smchealth.org/data-dashboard/county-data-dashboard 
Could we update our source with the correct number?

Thanks
Roxy

**Comment by CSSEGISandData** [comment]
Hello,

This has been resolved by #3873. Thanks and apologies!
