### ISSUE TITLE
Data for Czechia wrong

### ISSUE THREAD

**Issue by vrujbr** [CSSEGISandData/COVID-19#3855]
There is an error in new cased data for Czechia for 20 Mar to 23 Mar. According to https://onemocneni-aktualne.mzcr.cz/covid-19 it should be 5459, 2389, 8243 and 10883 respectively.

**Comment by CSSEGISandData** [comment]
Hello

The source you link is the same from which we access our data. Please see issues #3819 and #3751 for the reasons that there is a difference in how the days are reported.
