### ISSUE TITLE
Correction Needed for Turkey's Feb 7, 2021 Recovered Patients

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#3864]
In reference to https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html of the Ministry of Health of Turkey, Turkey's recovered patients on Feb 7, 2021 are 2,420,706 not 2,440,706. Please see row "7 Şubat 2021" and column "Toplam İyileşen Hasta Sayısı" in the aforementioned webpage.

**Comment by CSSEGISandData** [comment]
Please see PR #3867 which resolves this issue.
