### ISSUE TITLE
Graph data needs to change

### ISSUE THREAD

**Issue by Muramas** [CSSEGISandData/COVID-19#387]
Right now for the graph (that shows Mainland China, other location and total recovery) should be changed to something like total confirmed, total recovered and total deaths. Right now the china metric is important but no longer the big future picture. 

https://i.imgur.com/lbVEUfH.png

**Comment by jawz101** [comment]
https://ncov.dxy.cn/ncovh5/view/pneumonia

**Comment by Muramas** [comment]
> https://ncov.dxy.cn/ncovh5/view/pneumonia

This site is missing a lot of data.
