### ISSUE TITLE
Italy Graph: Mistake on middle cases for 7 days

### ISSUE THREAD

**Issue by LudIta04** [CSSEGISandData/COVID-19#3875]
On the Italy's graph there's a mistake on the blue line pointing out the middle of cases for 7 days that from the 20th of March isn't correct since the values are too high.

**Comment by CSSEGISandData** [comment]
Hello,

For which data file is there an issue? We do not publish rolling averages which is what I believe you are referring to.

**Comment by Matteo11111** [comment]
The data about the 22th March are wrong, the real cases have been 13486

**Comment by CSSEGISandData** [comment]
Hello,

Our data for March 22 (and 21 and 23) match that of the [dashboard](https://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1) of the [Italian Ministry of Health](http://www.salute.gov.it/portale/nuovocoronavirus/homeNuovoCoronavirus.jsp).
