### ISSUE TITLE
Wrong data on the 22nd March for Italy 

### ISSUE THREAD

**Issue by Matteo11111** [CSSEGISandData/COVID-19#3877]
Data of the 22nd March for Italy are wrong. 
![16167895973838091333340196828612](https://user-images.githubusercontent.com/81435273/112687674-1c7b6280-8e78-11eb-9afa-a17e0bc981e1.jpg)
Directly from the dashboard of the Minestry

**Comment by CSSEGISandData** [comment]
Hello,

Our data matches those of the cumulative counts provided by the Italian Ministry of Health (see three attached screenshots). The daily case curve that you are referencing does not include the backlog of 10,665 cases reported in Bolzano on March 22, which has now been documented in our README. Italy is not providing a back distribution for these cases so we must include them by date of report, which was March 22.
<img width="135" alt="March 23" src="https://user-images.githubusercontent.com/60674295/112692216-7da23680-8e76-11eb-8648-378e2951c873.png">
<img width="194" alt="March 22" src="https://user-images.githubusercontent.com/60674295/112692219-7e3acd00-8e76-11eb-8375-63d2e822ecce.png">
<img width="153" alt="March 21" src="https://user-images.githubusercontent.com/60674295/112692221-7ed36380-8e76-11eb-9051-010d6d934c63.png">
