### ISSUE TITLE
New York State incorrect total cases and total deaths

### ISSUE THREAD

**Issue by Monesha67** [CSSEGISandData/COVID-19#3878]
Why New York State disconnect from Worldometer when most the states are correct on JHU-CSSE. Dr. Howard Zucker the commissioner in New York State. Dr. Zucker have access to JHU-CSSE system or are you putting incorrect numbers. Here’s the link to Worldometer. https://www.worldometers.info/coronavirus/usa/new-york/
![898074D1-F02A-4778-ACB1-1A1769D5B4D9](https://user-images.githubusercontent.com/75553737/112708559-e3d78b00-8e6f-11eb-8f44-77f472ac5244.jpeg)
![6BAD044C-FE63-46F1-84CC-0B1B83D2ABF4](https://user-images.githubusercontent.com/75553737/112708560-e4702180-8e6f-11eb-9ec4-969eeed9b55b.jpeg)
![CCE75A7B-C01B-4DBB-83AF-0B82115093CE](https://user-images.githubusercontent.com/75553737/112708561-e508b800-8e6f-11eb-93ec-af2f966362dd.jpeg)
![331A3835-47B9-4768-AF16-A7E1AA1C4990](https://user-images.githubusercontent.com/75553737/112708563-e5a14e80-8e6f-11eb-87fc-e1eea1f246d0.jpeg)

**Comment by CSSEGISandData** [comment]
Hello,

Our data for the state of New York is a combination of data from the New York City Health Department (for the five boroughs of NYC) and the New York State Health Department (for all other counties). Our sources for data in New York State are listed on our README and I will link them here:

[New York](https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e/data)

[New York City](https://www1.nyc.gov/site/doh/covid/covid-19-data.page)

We unfortunately are unable to comment on the reliability of data from other initiatives such as Worldometer.
