### ISSUE TITLE
Saint Helena

### ISSUE THREAD

**Issue by Helmeda** [CSSEGISandData/COVID-19#3882]
The Health Directorate has received confirmation that a passenger who arrived on the chartered flight from Stansted on Wednesday, 24 March, has tested positive for COVID-19 on arrival. 

https://www.facebook.com/StHelenaGovt/posts/2291445744332459

No specified number but multiple cases in St Helena waters:

The Health Directorate can confirm from tests taken from the crew on Friday, 26 March, that there are positive cases of COVID-19 on-board. The entire crew remains on board the vessel in quarantine conditions. 

https://www.facebook.com/StHelenaGovt/posts/2292303564246677

**Comment by CSSEGISandData** [comment]
Hello, 

Thank you for informing us to these potential new cases. Unfortunately, until we can determine the specific number of cases we cannot report these to our dashboard. We will keep an eye out for the official reported numbers!
