### ISSUE TITLE
Compare Alaska State Correct Number. New York State Incorrect Number. 

### ISSUE THREAD

**Issue by Monesha67** [CSSEGISandData/COVID-19#3883]
You are so quick to give a answer on New York State because you have a deal with Governor Andrew Cuomo. 
Here’s the link to Alaska State Correct Number
http://dhss.alaska.gov/dph/Epi/id/Pages/COVID-19/default.aspx
Here’s the link to New York State Incorrect Number. 
https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Map?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n

Why do you have links to different website to access the numbers? 
![F887E92D-6936-44EC-B2DF-EA35C24653BC](https://user-images.githubusercontent.com/75553737/112739888-efd55280-8f2c-11eb-9ca5-7693ada41b5e.jpeg)
![34E82D74-3391-405D-900B-A63DD40162B3](https://user-images.githubusercontent.com/75553737/112739889-f1067f80-8f2c-11eb-8c01-1805ed48d9fa.jpeg)
![14376F75-91AC-4E8E-9B95-F8B4485F0863](https://user-images.githubusercontent.com/75553737/112739891-f19f1600-8f2c-11eb-930b-a5bd86f18e03.jpeg)
![078EF175-6192-4526-94B5-5154A8DF6670](https://user-images.githubusercontent.com/75553737/112739892-f237ac80-8f2c-11eb-916a-2587c5eb9df6.jpeg)
![751BF902-5FDC-450C-9593-58962BB731E9](https://user-images.githubusercontent.com/75553737/112739893-f237ac80-8f2c-11eb-9ce6-8a43d5040260.jpeg)
![47C08010-4388-4F9B-A0A2-78B14E174D61](https://user-images.githubusercontent.com/75553737/112739894-f2d04300-8f2c-11eb-8f36-f499cf36514d.jpeg)

**Comment by CSSEGISandData** [comment]
Hello,

Our data for Alaska comes from a [single source](https://alaska-coronavirus-vaccine-outreach-alaska-dhss.hub.arcgis.com/), which publicizes the same data as is hosted on the page you. This is the reason that our data is equivalent to that of WorldoMeter, as assumedly they rely on the same source. As stated in the response to our previous issue, our data for New York is a composite of data shared by the New York Health Department (linked by you) and the [New York City Health Department](https://www1.nyc.gov/site/doh/covid/covid-19-data.page). Presently, all of our US data comes from non-aggregated data sources (which themselves are used for some global locations) which are listed clearly in the README.


Again, we are unable to comment on the data reliability of Worldometer.

Our data all comes from sources that are publicly available. We do not coordinate with government officials to share data that is not in the public domain.
