### ISSUE TITLE
Wrong number of middle cases for Italy

### ISSUE THREAD

**Issue by LudIta04** [CSSEGISandData/COVID-19#3886]
The Italian graph contains a mistake on the blue curve for the middle cases for 7 days that raises too high values from the past week. I invite someone to control it and correct him basing on the correct values of the official cases from Ministero della salute.

**Comment by CSSEGISandData** [comment]
Please see the explanation in #3877. This is related to a reporting issue from the Ministry of Health. Our data matches the cumulative reported case counts published by the Ministry of Health.
