### ISSUE TITLE
Any chance the data here would be updated at the same cadence the live map is?

### ISSUE THREAD

**Issue by meldehi** [CSSEGISandData/COVID-19#389]
I just want to say that I truly appreciate your work guys on tracking this data and make it publicly available to everyone.

Any chance the data in this repository here would be updated at the same cadence the live map is?

**Comment by skandragon** [comment]
Seconded.  I want to write a twitter bot.

**Comment by meldehi** [comment]
I have already written a data fetcher that grabs the data from here and planning on building a rest API around it and make it available to everyone but the cadence of update will not make it as useful.

**Comment by molx** [comment]
I believe the [this answer](https://github.com/CSSEGISandData/COVID-19/issues/352#issuecomment-596855211) from another issue may address what you guys are looking for.

**Comment by jrmatchett** [comment]
There's already a REST API to the data source. For example, here are the current cases: https://services1.arcgis.com/0MSEUqKaxRlEPj5g/ArcGIS/rest/services/ncov_cases/FeatureServer/1/query?where=1%3D1&outFields=*&f=pjson

**Comment by meldehi** [comment]
Thanks @jrmatchett for the quick response

**Comment by meldehi** [comment]
One last question, the rest endpoint only has the most recent data. It does not have historical data which is recorded in this repo, correct?

**Comment by jrmatchett** [comment]
> One last question, the rest endpoint only has the most recent data. It does not have historical data which is recorded in this repo, correct?

Yes, just the most recent from what I can tell.

**Comment by meldehi** [comment]
Awesome, thanks!
