### ISSUE TITLE
Level 3 raw file not updated since 3/24/2021

### ISSUE THREAD

**Issue by kenshermock** [CSSEGISandData/COVID-19#3891]
I manually downloaded and confirmed no updates since 3/24 for any global location.

**Comment by CSSEGISandData** [comment]
Hello,

Can you provide more detail? For which file are you seeing this stale data?

**Comment by kenshermock** [comment]
Hi,

It is this file: https://storage.covid19datahub.io/data-3.csv

Thank you,

Ken

From: CSSEGISandData ***@***.***>
Reply-To: CSSEGISandData/COVID-19 ***@***.***>
Date: Monday, March 29, 2021 at 4:25 PM
To: CSSEGISandData/COVID-19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [CSSEGISandData/COVID-19] Level 3 raw file not updated since 3/24/2021 (#3891)


      External Email - Use Caution





Hello,

Can you provide more detail? For which file are you seeing this stale data?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you. This is an api that is not managed by our team. I don't believe that this issue is due to our data, but please reopen this issue if you are able to see it in our data products.
