### ISSUE TITLE
Incorrect geospatial coordinates

### ISSUE THREAD

**Issue by elmavon** [CSSEGISandData/COVID-19#390]
As of today the map is displaying cases attributed to central Virginia, however no cases have been reported there in any of your sources.  I dug through some of your raw data and I believe some cases are getting attributed to the coordinate your system has assigned to the geographic center of the state of Virginia.  I would suspect some of the data has missing or non-resolvable fields.  I only noticed this since it was near my region, but it may be worthwhile to institute some checks before displaying this type of information to the general public. Or at least place a noticeable disclaimer?

Thanks!

**Comment by jawz101** [comment]
I think something happened to the data because all states used to show it at the city level before today.

**Comment by fanfare** [comment]
Can confirm it's been like this for over two days.

**Comment by jawz101** [comment]
looks like they are aware of it
https://github.com/CSSEGISandData/COVID-19/issues/382

It's really just a symptom of the country and world not really prepared to actually do [syndromic surveillance](https://github.com/CSSEGISandData/COVID-19/issues/339#issuecomment-597328426)

**Comment by CSSEGISandData** [comment]
The dashboard is currently reporting US data at the county level. All cases will be allocated to their specific county centroid within the state that they reside in.
