### ISSUE TITLE
Missing data in victim world record holder Hungary

### ISSUE THREAD

**Issue by d4242** [CSSEGISandData/COVID-19#3902]
I guess you are using a scraper to get new data, but quite possibly due to political reasons (PM took a victory lap about 2M inoculated jabs on Monday, that, in fact, happened on Tuesday only, and that would have been revealed by the regular Tuesday morning update) official data update that, for this reason, has been messed up, and you haven't updated the database yesterday. Monday's death toll was 274, source: https://koronavirus.gov.hu/cikkek/orszagos-tisztifoorvos-magyarorszag-oltonemzet and that's missing from the DB.

Today's update was fine.

**Comment by CSSEGISandData** [comment]
Hello,

In which data file are you seeing this issue? In both the time series and daily reports, I see 20,161 deaths reported on March 29 and 20,435 deaths reported on March 30 which reduces to the 274 deaths that you note.

**Comment by d4242** [comment]
Thank you. The visualisation at ourworldindata seems to be wrong, but the source data is accurate. Since they are automated, I have assumed that data was missing. Apologies for the false alarm.
