### ISSUE TITLE
WA, WI, WV, WY missing on the 3/25/2021 CSV

### ISSUE THREAD

**Issue by sidharthrajaram** [CSSEGISandData/COVID-19#3911]
Hey, noticed that the CSV file for [3/25 data](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-25-2021.csv) seems to end at Virginia. I could not see Washington, Wyoming, West Virginia, nor Wisconsin. 

Just wanted to give a heads up and hoping for a potential fix! :) 

Thanks.

**Comment by sidharthrajaram** [comment]
Screenshot of the end of the 3/25 CSV:
![image](https://user-images.githubusercontent.com/14987538/113444829-7cf32e00-93a9-11eb-99f3-9ebf744565d0.png)

**Comment by CSSEGISandData** [comment]
Hello, 

We have investigated this issue but we could not replicate it. Please see the screenshot below taken from the link you posted in your issue. 

<img width="1330" alt="Screen Shot 2021-04-02 at 3 23 41 PM" src="https://user-images.githubusercontent.com/60674295/113447220-6a87ed00-93c7-11eb-8bed-414630b3550c.png">
