### ISSUE TITLE
New Mexico altering reporting schedule to once per week

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#3918]
Hello all,

This announcement serves to notify that the [New Mexico Department of Health dashboard](https://cvprovider.nmhealth.org/public-dashboard.html) has changed their reporting schedule to only update data once per week. This is the text currently displayed on their dashboard:

"DATA IS UPDATED EVERY OTHER WEEK. NEXT UPDATE: 4/07/2021."

**Comment by StateCenterKid** [comment]
Please review this issue.   I believe the note on the New Mexico dashboard is intended to mean that the raw data is only reviewed every  other week.    Case Counts still appear to be published daily.    Full text of New Mexico announcement

"DATA IS UPDATED EVERY OTHER WEEK. NEXT UPDATE: 4/21/2021. DAILY CASE COUNT AND TEST NUMBERS ARE RAW DATA BASED ON INFORMATION THE STATE RECEIVES TODAY - MEANING DATA THAT HAS NOT YET BEEN SCRUTINIZED BY STATE EPIDEMIOLOGISTS TO IDENTIFY POTENTIAL DUPLICATES OR LATE-ARRIVING POSITIVES OR NEGATIVES. BY CONTRAST, THE RED YELLOW GREEN ANALYSIS PROVIDES A MORE ACCURATE PICTURE FOR A TWO-WEEK PERIOD OF TIME."

The website includes a link at the lower left leading to this statement..

"When is the data updated?
Data Updated Daily:
Total Number of Cases, Total Number of Tests, Total Number of Cases by County, Total Number of Deaths, Total Hospitalizations, Current Hospitalizations, Total Recovered, Age Demographics, Gender Demographics, Race/Ethnicity Demographics, Total Cases per Zip Code"
