### ISSUE TITLE
Virgin Island US People Tested

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#3939]
Hello,

I found that there is a huge jump for Virgin Island people tested from 50108 on Mar 26 to 69587 on Mar 27. Might I ask if it is a valid increase? 

Best,
Ruijing

**Comment by CSSEGISandData** [comment]
Hello,

The Virgin Islands Health Authority maintains their historical reports [at this link](https://www.covid19usvi.com/covid19-report). As you can see, there had been no update on official data from 3/11 to 3/22, resulting in this large spike in reported tests when the reporting resumed. We will look into back distributing the testing data for 3/23 to 3/26.
