### ISSUE TITLE
Daily global stats are now stopped ?

### ISSUE THREAD

**Issue by bossbeagle1509** [CSSEGISandData/COVID-19#3948]
[This](https://covid-api.com/api/reports/total?date=2021-04-10) no longer works. The dates seem to work until the 8th, after that, all I get is [ ]. Has the API been discontinued ?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Unfortunately, this API is not under management of our team so I am not able to assist you. All the data products in our GitHub repository are under a daily update cycle if you could adapt your analysis pipeline to using our csv files directly.
