### ISSUE TITLE
[Collaboration] Brazil has 34 confirmed cases

### ISSUE THREAD

**Issue by jonasmrfranca** [CSSEGISandData/COVID-19#395]
@CSSEGISandData, please update brazilian confirmed cases, it’s 34.

Source (Ministry of Health): http://plataforma.saude.gov.br/novocoronavirus/

Thanks folks!

**Comment by CSSEGISandData** [comment]
The dashboard is now reporting Brazil at a subnational level. Please check out the readme file in this repo for the source we are currently using to report this data.
