### ISSUE TITLE
March 10th Confirmed Cases 0 for Iran and Hong Kong?!

### ISSUE THREAD

**Issue by aminadibi** [CSSEGISandData/COVID-19#396]
March 10th Confirmed Cases is reported as 0 in the time series CSV file for many countries including Iran and Hong Kong!

**Comment by Sitius86** [comment]
It appears they changed the Country/Region names for a number of countries. Including Iran> Iran (Islamic Republic Of) and Korea is now Republic of Korea. Vietnam became Viet Name. Russia became Russian Federation.  

This is pretty absurd if this was an intended change.  I hope this gets fixed immediately and/or they update their readme files to address this.

**Comment by yy** [comment]
Different names are used for many countries in the latest commit. Here's a list in Python format:

```python
changed_names = {
    "Vatican City": "Holy See",
    "Hong Kong SAR": "Hong Kong",
    "Iran (Islamic Republic of)": "Iran",
    "Macao SAR": "Macau",
    "Republic of Korea": "South Korea",
    "Republic of Moldova": "Moldova",
    "Russian Federation": "Russia",
    "Saint Martin": "St. Martin",
    "Taipei and environs": "Taiwan",
    "Viet Nam": "Vietnam",
    "occupied Palestinian territory": "Palestine",
}
```

**Comment by duncanmak** [comment]
I'd much rather see Hong Kong as a separate item, separate from the data from the PRC.

**Comment by ChunJuC** [comment]
> I'd much rather see Hong Kong as a separate item, separate from the data from the PRC.

Yes, Macau and Taiwan too.

**Comment by CSSEGISandData** [comment]
The names of locations included on the dashboard correspond with the official designations used by the U.S. Department of State.
