### ISSUE TITLE
UK daily cases is Negative?

### ISSUE THREAD

**Issue by zizwiz** [CSSEGISandData/COVID-19#3964]
I use data from https://github.com/owid/covid-19-data/blob/master/public/data/jhu/total_cases.csv

The UK cases as shown in the small extracted sample below on 09 April 2021 UK had -4787 cases. I shortened the part below by just extracting the data to show you as the whole file is much larger.

  | United Kingdom cases |
Date | Total | Daily
06/04/2021 | 4379033 |  
07/04/2021 | 4381830 | 2797
08/04/2021 | 4384954 | 3124
09/04/2021 | 4380167 | -4787
10/04/2021 | 4382880 | 2713
11/04/2021 | 4384610 | 1730

I raised this at OWID but they say the issue comes from files they get from yourselves and they just use the data direct. Maybe you get the data from another source where the data is incorrect.

I also saw Belgium deaths has a negative entry.
![belgium](https://user-images.githubusercontent.com/18355464/114692270-638aa400-9d10-11eb-8a03-3081c05ac6b6.jpg)
![uk](https://user-images.githubusercontent.com/18355464/114692273-64233a80-9d10-11eb-968e-dd10a17b3597.jpg)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for bringing this to our attention. The UK Dashboard has a collection of [data notes](https://coronavirus.data.gov.uk/details/whats-new) on their site. It appears that these negative cases are the result of individuals who received false positive lateral flow tests that were later confirmed negative by PCR. The site is explicit that the historical data has not been corrected, so we will unfortunately have to allow the negative delta to persist in our dataset.

**Comment by zizwiz** [comment]
Thanks. Looks like it will have to remain with negative cases.
