### ISSUE TITLE
Total recovery count dropped (it should never drop as it is total)

### ISSUE THREAD

**Issue by vyaduvanshi** [CSSEGISandData/COVID-19#3968]
In the '`time_series_covid19_recovered_global.csv`' file, the total recoveries count decreases from date 13 Dec 2020 to 14 Dec 2020.

```
12/13/20    47328396
12/14/20    41338399
```

This can be reproduced by this code (python, pandas)

```
recovered_df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/\
csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
recovered_df[['12/13/20','12/14/20']].sum()
```

Inspecting further, the issue is caused by discrepancy in US data for those dates

12/13/20 | 12/14/20 | Country/Region
-- | -- | --
6298082 | 0 | US

**Comment by vyaduvanshi** [comment]
Upon even further inspection, I see that 13 Dec 2020 is the last date for recording US's recoveries. And thereafter, the recoveries for US are 0 for all the dates which is leading to the big drop.

Is this supposed to be intentional?

**Comment by CSSEGISandData** [comment]
Hello,

Yes, this was intentional. Please see pinned issue #3464.
