### ISSUE TITLE
Germany csv numbers not matching reality

### ISSUE THREAD

**Issue by Maxwelljones** [CSSEGISandData/COVID-19#397]
It's been a couple of days I'm looking at your csv and comparing to official numbers in Germany. Here's what I found out:

03-10-2020.csv
Automated upload file showing 
2020-03-10T18:53:02 | **1457** | 2 | 18

Official only source for Germany (RKI) showing on the same day and time:
**1296** | 2 | <not specified>

Here's the link to the official source:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

**Comment by daichen1337** [comment]
Hello @Maxwelljones I think this is no issue. The Robert Koch Institute is not the primary source. If you are able to read/speak german read also YOUR posted link:

> Hier sind ausschließlich Fälle aufgelistet, die dem RKI über den Meldeweg oder offizielle Quellen mitgeteilt wurden. Da es sich um eine sehr dynamische Situation handelt, kann es zu Abweichungen zwischen der RKI-Tabelle und Angaben anderer Stellen, etwa der betroffenen Bundesländer, kommen.

Tranlate by google translator

> Only cases that have been communicated to the RKI via the reporting path or official sources are listed here. As this is a very dynamic situation, there may be differences between the RKI table and information from other bodies, such as the federal states concerned.

Therefore some differences are ok

**Comment by Maxwelljones** [comment]
@daichen1337 would you please be so kind and guide me to the source? Can't cross the numbers of the csv with any other official site.

**Comment by daichen1337** [comment]
@Maxwelljones I think this is the source for the csv files: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

The primary source of this website are local reports from the federal state goverments and so on.

**Comment by mogol07** [comment]
I guess it's strange. RKI and ECDC have as for today (15.03.20) quite similar count of case:
ECDC 3062 (8:00 14.03)
RKI     3795 (20:00 14.03)
but
JHU    4585 (15.03)

**Comment by heidekrueger** [comment]
As pointed out in #826, there seems to be a systematic error in the data source regarding Germany's numbers. (I've observed this for more than a week but didn't know why until seeing the other issue. The data source Germany seems to add up the numbers <current cases> + <change since yesterday> that RKI reports. This leads to the numbers in the dashboard being too high. In a way, the dashboard is always one day ahead (with yesterday's rate of change.)

**Comment by Melykuti** [comment]
For what it's worth, I found that the Wikipedia page
[COVID-19-Fälle in Deutschland#Infektionsfälle nach Bundesländern](https://de.wikipedia.org/wiki/COVID-19-F%C3%A4lle_in_Deutschland\#Infektionsf%C3%A4lle_nach_Bundesl%C3%A4ndern)
has the time series data copied from the Robert Koch Institute day after day.

I've done a study to estimate e.g. the doubling rate and you can download the Python 3 script that I wrote to parse the two Wikipedia tables.
https://github.com/Melykuti/COVID-19/blob/master/Deutschland.md

Unfortunately, there is no table on Wikipedia and no sign of the RKI publishing the number of recovered patients. This Sunday, 15th March at around noon I emailed the RKI to ask them to release and to curate the time series data in a computer-readable form. No answer yet.

**Comment by line-o** [comment]
Maybe this source is good to scrape? https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html?nn=13490888

**Comment by Maxwelljones** [comment]
I think the answer is clear here: https://github.com/CSSEGISandData/COVID-19/issues/826#issuecomment-599577818

> A total of 4,838 (+1,043) laboratory-confirmed cases of coronavirus disease 2019 (COVID-19) have been detected in Germany since 27/01/2020, of which 4,195 were electronically reported to and validated at the RKI. So far, 12 (+4) deaths related to COVID-19 diseases were reported.

the number in the parenthesis (i.e. +1043) represents the difference between today and the day before.

Therefore Germany is always showing numbers highre and not matching reality but it's a sum of 
the people infected today + the difference between today and yesterday.
**The numbers should definitely not be added.**

How do we get this corrected?

@line-o no. RKI is the only official German source, don't scrape it ;)

**Comment by jgehrcke** [comment]
Here I explain why the RKI numbers are often behind: https://gehrcke.de/2020/03/covid-19-http-api-for-german-case-numbers

The RKI numbers are of course great and credible, but not quite fresh.

For the _current_ count you always want to look at what the individual ministries of health have published to date. This is what zeit.de is doing. I have built an HTTP API around that. See the blog post linked above. 

In short:
```
$ curl https://covid19-germany.appspot.com/now 2> /dev/null | jq
{
  "current_totals": {
    "cases": 9348,
    "deaths": 25,
    "recovered": 72,
    "tested": "unknown"
  },
  "meta": {
    "contact": "Dr. Jan-Philip Gehrcke, jgehrcke@googlemail.com",
    "source": "zeit.de (aggregates data from individual ministries of health in Germany)",
    "time_source_last_consulted_iso8601": "2020-03-18T00:11:24+00:00",
    "time_source_last_updated_iso8601": "2020-03-17T21:22:00+01:00"
  }
}
```

For historical data I think the data in this repo here is great! Good luck!

**Comment by CSSEGISandData** [comment]
The dashboard is now reporting subnational data for Germany! Please check out the source in the readme file located in this repo.
