### ISSUE TITLE
Michigan cases/deaths zero for 4/20/21

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#3988]
The Michigan dashboard has updated data for Tuesday:

<img width="370" alt="Screen Shot 2021-04-21 at 10 01 23 AM" src="https://user-images.githubusercontent.com/273891/115567397-38143600-a289-11eb-9735-6a974e5f37a0.png">

[URL](https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html)

Any plans to update the JHU data sets, which are showing zero new cases/deaths for Michigan for Tuesday?

**Comment by CSSEGISandData** [comment]
Hello, 

Thank you for notifying us about this update. We have corrected our Michigan data for Tuesday, April 20th, 2021.
