### ISSUE TITLE
Saarland (Germany) Active Cases seem to be erroneous (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#3992]
Hi all,

Saarland (Germany) increased its active cases from 2269 to 28762 (2021-04-20 vs 2021-04-21). 

The data at the source https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/ looks fine. 

Thanks as always for checking!

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hi Christoph,

Thank you for your message. Our active cases are computed internally from case, death, and recovery data so this was likely a computation error that we will need to investigate. In the interim, I have manually patched the error. Thank you for bringing it to our attention.

**Comment by fahadq820** [comment]
N

**Comment by fahadq820** [comment]
I
