### ISSUE TITLE
Table Column has changed

### ISSUE THREAD

**Issue by igoralves1** [CSSEGISandData/COVID-19#40]
By Today Feb-23 (and also yesterday) I realised that tables has change columns headers. I am not sure but I realised also that the class name for table header is not correspond with coulum values
![Screenshot from 2020-02-12 23-12-49](https://user-images.githubusercontent.com/3280251/74404969-f02e8f00-4df9-11ea-8125-0559e8eb6445.png)
![Screenshot from 2020-02-13 00-52-56](https://user-images.githubusercontent.com/3280251/74405529-47812f00-4dfb-11ea-9067-1a69a0884a77.png)

Also I have an open repository here - https://github.com/igoralves1/scrap2019-ncov

I am using puppeteer for async scrapping. I just updated today with the latest changes. 
![Screenshot from 2020-02-13 00-55-27](https://user-images.githubusercontent.com/3280251/74405626-8b743400-4dfb-11ea-8b01-be0d30ab1020.png)

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We have committed to our current data structure and we will notify users of any structural changes in the future.
