### ISSUE TITLE
South Korea in 2 times

### ISSUE THREAD

**Issue by ironoverload** [CSSEGISandData/COVID-19#400]
There are 2 entries, Republic of Korea and South Korea are the same country.

**Comment by spencerj411** [comment]
^ it seems like South Korea was being relabelled as Republic of Korea (last cell of South Korea is empty whereas all cells of Republic of Korea are 0's except the last cell). Hope they fix this soon.

**Comment by jgriffi6** [comment]
Ditto for Iran

**Comment by CSSEGISandData** [comment]
The names of locations included on the dashboard correspond with the official designations used by the U.S. Department of State. The dashboard is currently reporting the proper naming convention and has removed any duplicate and/or mislabeled countries.
