### ISSUE TITLE
Is there a Virginia Cases (Confirmed & Deaths) Reporting/Update Issue, Today (2021-04-27)?

### ISSUE THREAD

**Issue by JustaNormalGuy230** [CSSEGISandData/COVID-19#4015]
Normally this update occurs very early in the morning.  At the Virginia site earlier, 18 deaths were reported/graphed:

https://www.vdh.virginia.gov/coronavirus/key-measures/

Update: A Death Count of 16 showed up for Virginia, later on. 

Thanks in advance!

**Comment by CSSEGISandData** [comment]
Hello,

We noted this as well - it appears the state had issues updating several of their products and metrics yesterday evening. Our data was updated using one of their products that did contain the daily update and accurately reflects that reported by the state for 4/27.

**Comment by JustaNormalGuy230** [comment]
Hi:

Thanks for all that you're doing CSSEGISandData, btw...

FYI:

... I noticed that this morning, 2 deaths were added today (so far) ... From their graph/plot, I'm expecting 11 new deaths for today.  So either yesterday was 16 deaths (not 18) or we should see 13 deaths for today (another 11, instead of 11 total), making up the difference.
