### ISSUE TITLE
Pakistan cases and deaths for April 23

### ISSUE THREAD

**Issue by pruggia** [CSSEGISandData/COVID-19#4018]
Cases for Pakistan on April 23 are reported as 0, but the correct number according to https://covid.gov.pk/stats/pakistan is 5908
Deaths are also reported as 0, but the same site above shows non-zero numbers.

**Comment by CSSEGISandData** [comment]
Hello, 

Thank you for identifying this issue. We have correct our data to match the appropriate Cases, Deaths, and Recovered values for April 23rd - April 24th. Please see #4041
