### ISSUE TITLE
Same issue every day - data for last day is not complete

### ISSUE THREAD

**Issue by jtene001** [CSSEGISandData/COVID-19#402]
The data has the same problem today, except far more severe. The data for 3/10 has numerous empty cells - many more than yesterday and the day before. Problem is in all three data sets - confirmed, recovered and deaths. This time there are so many empty cells that extrapolating for the last data point has become impractical.

**Comment by Bost** [comment]
#238

It's been happening so many times, that I think from now on it is pointless to complain. We just have to live with the fact that providing data is something these guys are... yeah maybe there are other things they do better.

Besides, the [mortality rate](https://www.worldometers.info/coronavirus/coronavirus-death-rate/) of **reported** cases is ~3.4% and there are maaaany more unreported cases (e.g. Turkey has 0 confirmed cases)... so everybody take it easy. And yea it looks like it's 2020 and the humanity still haven't learned how to collect data... But who cares?!? This corona thing, compared to the bubonic plague is just a joke. [Don't Panic](https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Don't_Panic).

**Comment by CSSEGISandData** [comment]
Due to some technical difficulties that occurred during this period of transition for us, we experienced a few issues that are now resolved. Sorry for the inconvenience.
