### ISSUE TITLE
Error in Chile Recovered Cases May 1st 2021

### ISSUE THREAD

**Issue by roysaad** [CSSEGISandData/COVID-19#4033]
There's a spike in the Recovered Cases of Chile. The number jumped by over 1 Million in one day.

**Comment by CSSEGISandData** [comment]
Hello

It appears that Chile is [currently posting an error](https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/) for recoveries in the province of Biobío. I have attached a screenshot of what the table currently presents. We will hold back the previous day's reported recoveries for that province until the data is corrected.
<img width="640" alt="Screen Shot 2021-05-02 at 12 21 14 PM" src="https://user-images.githubusercontent.com/60674295/116811387-f1ec8b80-ab40-11eb-8b6e-eb80ea1e3d12.png">
