### ISSUE TITLE
Taiwan was taken off list, we are a free democracy, not part of china. 

### ISSUE THREAD

**Issue by ScottcWaring** [CSSEGISandData/COVID-19#404]
Im not sure why we were taken off the list, but please put Taiwan back on the list. Taiwan is a free separate country from China. Apparently a Chinese person complained and had it taken down. This is just wrong. Just because China hates taiwan, we get excluded from this list. This needs to be fixed please.

**Comment by ChunJuC** [comment]
Taiwan is now included in China, which is totally wrong. 
Not only because of political issues, but also Taiwan and China have different system in public health field.  
Counting Taiwan as part of China will be misunderstanding and confusing for further analysis and tracking.

**Comment by CSSEGISandData** [comment]
We are following the WHO report standard. Thanks!

**Comment by SilverChunJuChen** [comment]
WHO made a lot of wrong decisions from the very beginning.
It is now Winnie Happy Organization (or CHO if you prefer), and not really talking about the truth.
You should really reconsider it.
And the number of this issue is #404. Coincidence? I don't think so.

**Comment by poweic** [comment]
Oh, come on! THIS is exactly what happens when people blindly follow WHO.

**Comment by ByronLian** [comment]
Please fix it asap

**Comment by Spiritator** [comment]
> We are following the WHO report standard. Thanks!

Looks like johns hopkins are infected by one-china-policy virus, too. Just like winnie happy organization (WHO).
This kind of bullshit which neglect the actual problem is the reason that makes the coronavirus spread worldwide.

**Comment by ladris** [comment]
This is an entirely ineffective form of feedback and requires being
entirely ignored until it can be done an a civilized manner. Lack of
civility should never be rewarded in situations where real world death
scenarios are involved and it's ridiculous.

**Comment by kitsing** [comment]
> We are following the WHO report standard. Thanks!

Johns Hopkins University, [the most-federal-funded educational institution in the world](https://hub.jhu.edu/2018/03/23/nsf-research-funding-rankings/), should be using the US government sanctioned country list [GENC](https://www.fgdc.gov/standards/news/GENC). GENC is widely considered as much more geopolitically neutral than the lists provided by various UN agencies and has been adopted by [major civilian software projects](https://bugzilla.mozilla.org/show_bug.cgi?id=733417#c20). And GENC currently lists Taiwan as Taiwan, as one would expect.

**Comment by duncanhsieh** [comment]
Are you follow the "Winnie Happy Organization" report standard?

**Comment by hsuzchan** [comment]
Plus, travel restrictions are made based on the original "Country or Area" label. Please consider your ethics over influence while travel and relocate decisions are possibly based on your dashboard as an important supporting item. Though the old way on the dashboard mentioning "Taiwan" with a state/province name also labelled "Taiwan" was a vague way to avoid politics, these labels are not causing PR crises which ruins the Johns Hopkins reputation. So please fix this issue according to the national and academic standard. Thanks.
https://www.cdc.gov/coronavirus/2019-ncov/travelers/index.html

**Comment by markwu** [comment]
Is Johns Hopkins University part of China? YES, definitely!

That's why you guys think Taiwan is part of China.

**Comment by kekwowse01** [comment]
The reality is that Taiwan is not part of China. China does not have any governing power over Taiwan and grouping Taiwan as a part of China make zero sense in disease control and public health. Stop playing the word game and leave Taiwan as Taiwan. Shame on you, Johns Hopkins University!

**Comment by wwschung3** [comment]
> We are following the WHO report standard. Thanks!

WHO may be part of china, but Taiwan and HongKong are not

**Comment by tlin40** [comment]
> We are following the WHO report standard. Thanks!

My dear alma mater, please change my country's name back.

**Comment by andyfcx** [comment]
Following China or WHO will lead to disastrous results.

**Comment by u8906250** [comment]
Thank you.

Taiwan is Taiwan.  NOT part of china.

**Comment by davll** [comment]
Taiwan is Taiwan, and it is a democratic nation which is never ruled by Communist Party of China.
