### ISSUE TITLE
Time Series Data

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#405]
We are currently adjusting the time series tables. Sorry for the inconvenience and thank you for your patience.

**Comment by loulouOz** [comment]
Thank you!

**Comment by chiester** [comment]
Thank you. Is the csv manually or automatically generated? I'd be happy to help and I'm sure others would be willing to take some states and manually backfill the numbers for states from the county data and submit PRs.

**Comment by treerunner** [comment]
Thank you very much. We appreciate your effort.

**Comment by jtene001** [comment]
Thank you. There are serious problems with the data.

**Comment by sibblegp** [comment]
Thank you! You can check if the CSV works by visiting covid.bio. If it's good, all the pages will work. If they don't, the dataset is bad.

**Comment by loulouOz** [comment]
Palestine too

**Comment by loulouOz** [comment]
vietnam and viet nam

**Comment by yy** [comment]
Thanks! Would you consider reorganizing it into the "tidy" (long) data format? https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html The diffs will be more meaningful and it'll be easier to manipulate. Here's Python code that might be useful: https://github.com/yy/covid19-data/blob/master/scripts/combine_ts.py

**Comment by ciscorucinski** [comment]
What's changing with the time series data?

**Comment by freeeve** [comment]
it looks like US states and city/counties are now represented twice in some cases?
for example, is Virginia -> 7 including the Fairfax County -> 2 ?

**Comment by philipncohen** [comment]
> it looks like US states and city/counties are now represented twice in some cases?
> for example, is Virginia -> 7 including the Fairfax County -> 2 ?

Tonight's update added state data for today only (zeros before today) and left in the county data through yesterday (blank for today).

**Comment by freeeve** [comment]
> > it looks like US states and city/counties are now represented twice in some cases?
> > for example, is Virginia -> 7 including the Fairfax County -> 2 ?
> 
> Tonight's update added state data for today only (zeros before today) and left in the county data through yesterday (blank for today).

got it, so are you not going to manage county level data anymore?

**Comment by philipncohen** [comment]
> > > it looks like US states and city/counties are now represented twice in some cases?
> > > for example, is Virginia -> 7 including the Fairfax County -> 2 ?
> > 
> > 
> > Tonight's update added state data for today only (zeros before today) and left in the county data through yesterday (blank for today).
> 
> got it, so are you not going to manage county level data anymore?

Don't look at me, I'm just a user :). Don't know what they'll do.

**Comment by jqnatividad** [comment]
NY Times has US City level data

https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html?action=click&pgtype=Article&state=default&module=styln-coronavirus&variant=show&region=TOP_BANNER&context=storyline_menu#us

If JHU is aggregating at the State level (less useful), perhaps NYTimes can be persuaded to open source their data?

**Comment by ohbriansung** [comment]
#404

**Comment by ivh** [comment]
Iran and South Korea have changed name and appear twice in the timeseries now. Is this temporary or do I need to make my script mitigate this? 

Anyway, thanks for your work!

**Comment by CSSEGISandData** [comment]
We have adjusted the time series tables! Thank you for your patience.

**Comment by sibblegp** [comment]
The data is wrong. The total for the US today is over 1600 when only 1000 people are sick. This makes everyone's analyses useless. What's up with the numbers?
