### ISSUE TITLE
Missing data in csse_covid_19_time_series for 3/10/20

### ISSUE THREAD

**Issue by dorofino** [CSSEGISandData/COVID-19#407]
Hi, 

There are some missing data on the last update for 3/10/20 in the file csse_covid_19_time_series 

Best Regards
Do

**Comment by eugene-yang** [comment]
Looks like #405 is working on it.

**Comment by CSSEGISandData** [comment]
Due to some technical difficulties that occurred during this period of transition for us, we experienced a few issues that are now resolved. Sorry for the inconvenience.
