### ISSUE TITLE
Confirmed Cases Germany May 8/9

### ISSUE THREAD

**Issue by mbender-ith** [CSSEGISandData/COVID-19#4070]
The number of confirmed cases for Germany in https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv on May 8/9 is identical 
(3530887).
Please check original data source.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Our reporting comes from [Berliner Morgenpost](https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/) and our data matches their reporting for those two days. The Morgenpost takes their national level data from [risklayer](https://www.risklayer-explorer.com/event/100/detail) and computes an "Unknown, Germany" entry based on the difference between this national level total and the sum of the federal state reporting. Between the two stale days, our data for the individual federal states updated while the "Unknown, Germany" entry had a reciprocal decrease, resulting in the national data appearing to have no new cases. We will continue to look for a back distribution however we find it unlikely that this data is available if the upstream issue was a failure of risklayer to update.
