### ISSUE TITLE
Pakistan cases for May 4th

### ISSUE THREAD

**Issue by pruggia** [CSSEGISandData/COVID-19#4071]
Cases for Pakistan on May 4th are reported as 0, but the correct number according to https://covid.gov.pk/stats/pakistan is 4112.
Thanks!

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We have identified the source of this issue and are working a patch. Thank you for your patience.

**Comment by CSSEGISandData** [comment]
Thank you for your patience. This was resolved with #4078.
