### ISSUE TITLE
Missing the number of recovered cases

### ISSUE THREAD

**Issue by mischoene** [CSSEGISandData/COVID-19#4080]
Hi,
I have seen the new layout of your great COVID-19 Dashbord, but I miss the number of recovered cases.
Is ist still available?
Thanks and kind regrads
Michael

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. The recoveries are no longer included in the visualization, but they are available in our GitHub repository at this link: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

Similarly, they will continue to be included in our daily reports.

**Comment by garyfarbar** [comment]
Hi,
Still cannot see the recoveries.  Please confirm where they are located in daily reports.
Thanks
Gary

**Comment by CSSEGISandData** [comment]
Hello,

They are the 10th column (header = "Recoveries") in the daily report files: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

**Comment by garyfarbar** [comment]
Thanks

Regards
Gary

**Comment by mischoene** [comment]
Thanks and kind regrads
Michael
