### ISSUE TITLE
Turkey recovery data spike

### ISSUE THREAD

**Issue by vyaduvanshi** [CSSEGISandData/COVID-19#4081]
There is a huge spike in the global recovered data for Turkey on the date of `12 Dec 2020`.

`df[df.country=='Turkey'][(df['date'] > '2020-12-05') & (df['date'] < '2020-12-15')][['date','country','new_recovered','total_recovered']]`

  date | country | new_recovered | total_recovered
-- | -- | -- | --
 | 2020-12-06 | Turkey | 4011.0 | 431253.0|
 | 2020-12-07 | Turkey | 5017.0 | 436270.0|
 | 2020-12-08 | Turkey | 5245.0 | 441515.0
 | 2020-12-09 | Turkey | 5846.0 | 447361.0
 | 2020-12-10 | Turkey | 5232.0 | 452593.0
 | 2020-12-11 | Turkey | 5516.0 | 458109.0
 | 2020-12-12 | Turkey | 1123456.0 | 1581565.0
 | 2020-12-13 | Turkey | 22215.0 | 1603780.0
 | 2020-12-14 | Turkey | 28164.0 | 1631944.0

I read the pinned issue #3484 about the spike in `confirmed_cases` on date `10 Dec 2020`. Due to the difference in dates, I wanted to ask if it is due to the same reason? Is there going to be any change in it?

**Comment by CSSEGISandData** [comment]
Hello,

Please see the official Turkey source, which also includes this spike in recovered patients: https://covid19.saglik.gov.tr/EN-69532/general-coronavirus-table.html
