### ISSUE TITLE
US Data missing all values except most recent value

### ISSUE THREAD

**Issue by LucidObscurity** [CSSEGISandData/COVID-19#410]
Basically, all the historical data is missing from the files with only the most recent "total" filled in the last date column.
[Edit] I guess it's only some states, but many of them are like this. California for example

**Comment by scottmcdaniel** [comment]
Still available using:

https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv

https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv

**Comment by LucidObscurity** [comment]
thanks @scottmcdaniel, I did notice that county data is historical so I'll close this. Would be nice to see the State records identified as such.
