### ISSUE TITLE
Ohio deaths on 5/18/21

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#4106]
Hello @CSSEGISandData, it looks like there were 100 deaths initially reported for the state of Ohio on May 18 which are no longer included in the data. I think this issue may be related to this: https://github.com/CSSEGISandData/COVID-19/commit/a59165a6f6cf787fbcc5b1c152c5a8664fd5f405

Do you have any details you might be able to share on whether this data was back distributed after an initial report? Thank you.

**Comment by CSSEGISandData** [comment]
Hi Nate,

Please see issue #3757. We back distribute Ohio deaths by date of death once they are published.

**Comment by naterattner** [comment]
Thanks for the response @CSSEGISandData! Got it, I missed that announcement.
