### ISSUE TITLE
Luxembourg (Grand Duchy) typo in data source (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#4109]
Hi all,

Today, authorities confused active cases with recovered cases in the raw data, which created quite a spike. 
Active Cases should be 1662, recoveries 66.994.

 All the best,
 
 Christoph

**Comment by CSSEGISandData** [comment]
Hi Christoph,

Thank you for the message. PR #4117 patches this issue. You are correct that the two entries we're swapped in their daily pdf report.

**Comment by c-hera** [comment]
Thanks, much appreciated!
