### ISSUE TITLE
Oh, so Diamond Princess can be in the list, but Taiwan can't?

### ISSUE THREAD

**Issue by puetsua** [CSSEGISandData/COVID-19#411]
I'd rather be in **Other** instead of being **Communist China**. Your decision to follow CHO is a big disappointment. You ignored the fact that CHO underestimated Wuhan Pneumonia and created huge economic disaster all over the world in the first place.

#404 #406

**Comment by avenirmello** [comment]
They probably want to be The John Hopkins University of Winnie Happy Organization.

**Comment by CSSEGISandData** [comment]
please see issue #482
