### ISSUE TITLE
Cyprus data not being updated

### ISSUE THREAD

**Issue by mishiaros** [CSSEGISandData/COVID-19#4111]
It has been 43 days since the last update for cases in Cyprus. This site has valid up to date data, so just posting it if it is of any help.
https://covid19.ucy.ac.cy/

**Comment by CSSEGISandData** [comment]
Hello,

Can you please point me to where you are not seeing the Cyprus data not updating? I see new cases being reported in our [daily reports](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) and [time series files](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series).

**Comment by mishiaros** [comment]
Oh I'm sorry, I posted this issue after seeing that google was not displaying up to date information.
![Untitled](https://user-images.githubusercontent.com/84567455/119152930-0beb0100-ba51-11eb-954e-27ed8d7c610e.png)
