### ISSUE TITLE
Cases and deaths in France stagnating since 2021-05-19

### ISSUE THREAD

**Issue by edomt** [CSSEGISandData/COVID-19#4114]
Dear CSSE team,

Both cases & deaths for France seem to be stuck at their 2021-05-19 level for the last 2 days.

**Comment by yetzt** [comment]
yes, france dropped about 350k cases on may 20th, so their data is pretty much fucked up now. apparently they were counting tests and did not account for people taking more than one test.

**Comment by CSSEGISandData** [comment]
Hi Edouard,

Please see #4125.
