### ISSUE TITLE
How can i help?

### ISSUE THREAD

**Issue by gtallen1187** [CSSEGISandData/COVID-19#412]
I love the work your team is doing here, and I'd love to help out in any way that i can.  I'm a product manager with technical skillsets for wrangling data, but i also do a fair amount of technical writing.  How can i lend a hand that would best help the project?  Here are a few I thought of, but i really want to do whatever is most helpful for the project.

* Write technical documentation outlining the different data pipelines and ETL processes involved in this project
* Write out technical documentation for newcomers: "How to get up and running with our data"
* Write jobs to find & parse new datasets
* QC existing data output
* Add Logs/reporting/monitoring surrounding the data processing pipeline

Please let me know, I really would like to help!

**Comment by CSSEGISandData** [comment]
We are not currently looking for new team members but we appreciate the support!
