### ISSUE TITLE
Taiwan is not part of China

### ISSUE THREAD

**Issue by huijunchen9260** [CSSEGISandData/COVID-19#413]
![image](https://user-images.githubusercontent.com/54217138/76382074-e8e19f00-632d-11ea-957d-bbecea5d4763.png)

Now in the map, Taiwan is mistakenly named as "Taipei and environs, China". As US government has passed Taipei Act and several Acts that in favor of Taiwan, I believe that it is very clear that US government is supporting Taiwan. 

I strongly against this modification based on political purpose. Taiwan is in no sense part of China. As a database from a high-ranking university in US, I strongly suggest that JHU should not follow the political purpose of Chinese government, but to follow the policy of US government.

**Comment by longskikondi** [comment]
cause of different government  and epidemic prevention system from China ,I have no idea why developer decide to remove Taiwan from the map let all people ignore it.

**Comment by CSSEGISandData** [comment]
please see issue #482
