### ISSUE TITLE
Yesterday's update of May21_2021 omitted hundreds of rows of US data

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#4134]
The update for May 21, 2021 "Indonesia" that appeared yesterday (May 24) in the 
COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/ somehow omitted approximately 300 entries from the US starting in the midst of data for Virginia.

**Comment by CSSEGISandData** [comment]
Hello,

This is a temporary error with the file previewing functionality of GitHub with large files. If you were to look again, you may be able to see the data now. If you aren't sure, you can check the raw csv at this link: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-21-2021.csv
