### ISSUE TITLE
Missing rows of time series data

### ISSUE THREAD

**Issue by alykat** [CSSEGISandData/COVID-19#4139]
Not sure if this is related to #4134 — We're noticing a lot of missing entries in the [timeseries data](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/8bd908f9ec581aee1c0c6b6e8dfcc7235ab439b6/data/cases_time.csv) from the `web-data` branch this morning. For example, there are only two entries for American Samoa, and there are lots of gaps in Arizona.

```
US,1/22/20,0,0,,,0,,0.0,,,American Samoa,60,16,ASM,2020/01/22,0
US,5/25/21,0,0,,,0,,0.0,,,American Samoa,60,16,ASM,2021/05/25,0
```

I checked [one of the files from yesterday](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/3d3765e7bac1652d45d3bbd5931d9e4df5847f31/data/cases_time.csv) and it included all the data we'd expect — one row for each day since Jan. 22, 2020.

**Comment by alykat** [comment]
Seems to have been resolved for now in the latest commit https://github.com/CSSEGISandData/COVID-19/commit/821735c6bd8850db43b4265ee0ea4b807e288c3d#diff-cea0b6794d0dc05596cf6fb1cb68eefac846dde4fd3c2207df542637b0e7c109

**Comment by CSSEGISandData** [comment]
Hello,

The issue you noted should be resolved. Cases_time_reduced.csv decreases the data loaded into our visualizations. Cases_time.csv will remain as is and we apologize for the trouble.
