### ISSUE TITLE
Name Inconsistencies (Outside US) i.e. Iran, Hong Kong, South Korea

### ISSUE THREAD

**Issue by analyzewithpower** [CSSEGISandData/COVID-19#414]
We appreciate your commitment to providing this data to the public and are thankful. 

The latest update, 3/10/2020, has name changes for the locations below (outside of the US).  Normally, this data was clean and needed little manipulation to generate reports and analyze. I am not sure if this is a one time issue or if we should expect these types of inconsistencies in the data provided. Please, advise and let me know how I can be of help. 

Thanks!
![NameChanges](https://user-images.githubusercontent.com/61880866/76382291-9c4a9380-632e-11ea-9ce1-312ade2ac698.JPG)

**Comment by joetynan11** [comment]
Agreed, I am very grateful that the data is being updated so regularly but it can be frustrating when you have built further analysis on top of the data (e.g. grouping countries by region, pop density, etc) only for the name to change

**Comment by nanami-773** [comment]
Why Russia has decreased from 17 to 10 ?

**Comment by CSSEGISandData** [comment]
The names of locations included on the dashboard correspond with the official designations used by the U.S. Department of State. The dashboard is currently reporting the proper naming conventions with duplicates and/or incorrect names removed.
