### ISSUE TITLE
South Africa data reads zero for new cases May 25-26

### ISSUE THREAD

**Issue by ajtiffin** [CSSEGISandData/COVID-19#4144]

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the message. South Africa had several anomalies in their reporting over the past few days. Their reports on [May 24](https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-24-may-2021/) and [May 25](https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-25-may-2021/) demonstrated no new cases (1,637,848 in both). The publication of case data for May 26 was delayed, resulting in being published to our May 27 data, while the data for [May 27](https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-27-may-2021/) was not published until May 28 and thus was combined with our reporting for that day. We will work corrections for May 26 and 27 and close this issue once they are in place. Thank you in advance for your patience.

**Comment by CSSEGISandData** [comment]
Patched by #4155
