### ISSUE TITLE
Where is the Incidence Rate Data which used to be on the map app?

### ISSUE THREAD

**Issue by DivadabNewton** [CSSEGISandData/COVID-19#4159]
Incidence rate map is now pretty much useless since you removed the data - why on earth did you do that? Can you please put it back?

**Comment by CSSEGISandData** [comment]
Hello,

Can you be more specific? The Incidence Rate map is still present on the dashboard as the second option if you toggle to the right.

**Comment by DivadabNewton** [comment]
Yes - it is still there, but when you click on a jurisdiction, there is no data. It used to show the incidence rate per 100k population for every jurisdiction - now, nothing. The "dots" are sized by a range of incidence rates but this is just not precise enough. 
Correction - there is a change and it requires an additional click to display the incidence rate. Seem a strange mod to make but the data is still there. Thanks for the prompt reply! 

David M. Camp


360-927-9275


Disclaimer: This message is intended only for the individual(s) to whom it is addressed and may contain confidential information. Any disclosure is strictly prohibited. If you have received this message in error please delete all copies of the message. 

    On Sunday, May 30, 2021, 09:25:52 AM PDT, CSSEGISandData ***@***.***> wrote:  
 
 


Hello,

Can you be more specific? The Incidence Rate map is still present on the dashboard as the second option if you toggle to the right.
