### ISSUE TITLE
Link to India State Wise Data

### ISSUE THREAD

**Issue by imdevskp** [CSSEGISandData/COVID-19#416]
Would you mind considering state-wise data from India

**Comment by imdevskp** [comment]
https://www.mohfw.gov.in/

**Comment by sagarkulkarny** [comment]
Hello team,

You are doing a great job of maintaining this data and I wanted to request you to add the state-wise data for India from this official Ministry of Health and Family welfare website: https://www.mohfw.gov.in/

I know there are people complaining about the continuous changes in structure and the data errors here and there but please know that you guys are doing a wonderful job nonetheless. Do let me know if you need any help.

Thank you @imdevskp for tagging this so early!

**Comment by imdevskp** [comment]
Hey @sagarkulkarny please see https://github.com/imdevskp/covid-19-india-data

**Comment by akhilnew123** [comment]
hey @imdevskp ,

Great job, I am completely new to this git and python. 
i have seen your python code. here I just wanted to understand you are saving the daily files right when can i get those details?.

I just wanted to run the python script and get the all the days data in a single file, but when I run, it is stopping me in that line of code where you have daily data saved in your desktop.
Could you help me!

Thanks in advance.
