### ISSUE TITLE
Alabama, US drop in active cases / no increase of confirmed cases (csse_covid_19_daily_reports_us)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#4160]
Hi all,

For three days, active cases in Alabama see a sharp drop with no added new cases. The Alabama dashboard has last been updated on 27/05/2021 (https://alpublichealth.maps.arcgis.com/apps/MapSeries/index.html?appid=d84846411471404c83313bfe7ab2a367). Memorial day might be a reason for this.

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hello Christoph,

This was due to the Memorial Day holiday. We've posted an announcement listing the states with abnormal reporting due to the holiday. See #4166
