### ISSUE TITLE
GBR negative case values

### ISSUE THREAD

**Issue by cliffwm** [CSSEGISandData/COVID-19#4163]
Your COVID dataset https://covid.ourworldindata.org/data/owid-covid-data.csv is showing negative values for the number of 'New Cases' for GBR on 2021-05-18 (-2362) and 2021-04-09 (-4787). Is this an error or some sort of data correction? Thank you.

**Comment by CSSEGISandData** [comment]
Hello,

Please see documentation on the UK website, specifically for April 9 and May 18: https://coronavirus.data.gov.uk/details/whats-new

I note that we have not yet documented these in our README, so I will do so now. Thank you for bringing this to our attention.
