### ISSUE TITLE
Taiwan IS NOT China

### ISSUE THREAD

**Issue by eacvo67347** [CSSEGISandData/COVID-19#417]
Why is Taiwan now grouped with China and hidden under "Taipei and environs, China"?

I thought they weren't even part of the WHO.

This is seriously undermining Taiwan's efforts in fighting off the pandemic. Multiple countries have voiced their support for Taiwan to join the WHO, but you guys are seriously undermining a nation's fight for equal treatment on the world stage. 

As mentioned in another ticket: The US government has passed Taipei Act and several Acts that in favor of Taiwan, I believe that it is very clear that US government is supporting Taiwan.

Also, HK and Macau were originally on the list, Macau has essentially closed off borders with China, and HK has implemented a mandatory quarantine. Why the change now?

**Comment by ohbriansung** [comment]
Hong Kong is gone, too.

**Comment by eacvo67347** [comment]
Hong Kong and Macau were targeted since recently, and I believe it's due to VP Mike Pence singling out Singapore & Hong Kong as having effective control measures. Also, China has recently tried to take credit for Taiwan's efforts for the 15 minute rapid test kit. 

 I'm not even trying to politicizing this, but that is what the CCP does. The CCP is brazen.

http://www.taipeitimes.com/News/front/archives/2020/03/10/2003732404
https://www.taiwannews.com.tw/en/news/3894151

**Comment by LucidObscurity** [comment]
Hmm...I wanted to use this repo for my own data analysis, but I'm seeing these "issues" posted and it looks like Taiwan was removed from the data almost a month ago. 
Here's an interesting google search: China's "Thousand Talents Program"

**Comment by runsun** [comment]
LucidObscurity, what are you talking about ? Taiwan has been there since the very first day until today (3/10). Somehow the people in charge suddenly think they need China's attention. Check the old data. I can still find it.

**Comment by CarberryChai** [comment]
不要着急嘛！用不了多久就会武统台湾，至于你美爹通过的什么法案，屁用没有，不信等着瞧

**Comment by CSSEGISandData** [comment]
please see issue #482
