### ISSUE TITLE
Low Priority: Is Virginia having Issues Reporting Deaths Today (2021-06-01)? (No, not really: due to a coding bug, but it may have changed from 9 to 8 at about 10 AM PDT.) 

### ISSUE THREAD

**Issue by JustaNormalGuy230** [CSSEGISandData/COVID-19#4171]
Hi:

Here's an output of my update log so far, today:

2021-06-01 05:04:48,594568,[0:0]
2021-06-01 05:34:23,594568,[0:0]
2021-06-01 06:34:50,594568,[0:0]
2021-06-01 07:34:24,594572,[1:4],SD:4
2021-06-01 08:34:57,594590,[5:27],VA:14,WV:5,SD:4,MD:2,MS:2
2021-06-01 09:34:33,594603,[8:40],VA:14,IN:8,WV:5,SD:4,TX:3,IA:2,MD:2,MS:2
2021-06-01 10:34:17,594650,[13:87],NC:23,VA:13,AL:10,IN:8,CA:7,NJ:7,WV:5,SD:4,TX:3,IA:2,MD:2,MS:2,MN:1
2021-06-01 11:34:50,594718,[18:155],NY:25,NC:23,LA:16,MI:13,VA:13,AL:10,IL:10,IN:8,CA:7,NJ:7,WV:5,RI:4,SD:4,TX:3,IA:2,MD:2,MS:2,MN:1
2021-06-01 12:34:24,594853,[20:290],FL:114,NY:25,NC:23,WI:19,LA:16,MI:13,VA:13,AL:10,IL:10,CA:9,IN:8,NJ:7,WV:5,RI:4,SD:4,TX:3,IA:2,MD:2,MS:2,MN:1

(Times are PDT)

VA is reporting 8 deaths for today, at their web site (graph): https://www.vdh.virginia.gov/coronavirus/key-measures/ .  If one looks closely at the transition from 7:34 AM to 8:34 AM, the Death Tally is short 5 deaths, when compared to the State/Territory/Entity Breakdown (This is strange, but could be an error in my logging routine.)... Later, one sees that VA decreases by one death, now 5 days extra for the day...

Is the 5 days short and the 5 days extra, coincidence?  All State/Territory/Entities not listed, should be reporting 0 deltas for the day, by the way... All Death Tally Deltas agree with the Breakdown Deltas, except for the one discrepancy, mentioned above.

... If the current, web cases_state.csv file isn't in sync with the tally count, this could explain things, I suppose...

... Thanks for shedding any light on this.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the message. I wonder if this is a timing/dating issue? We reported 13 new deaths in Virginia from [May 30](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/05-30-2021.csv) to [May 31](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/05-31-2021.csv) and that's in line with the Virginia dashboard ([linked here](https://www.vdh.virginia.gov/coronavirus/key-measures/)) on the "Deaths by Date Reported" tab. Can you double check that the update logs aren't shifted by one day when you pull them and then we can regroup?

**Comment by JustaNormalGuy230** [comment]
Greetings:

Thanks for the reply.

Normally, I observe that VA reports its "Deaths by Date Reported" early in the morning.  For Saturday (5/29), 4 Deaths were reported.  For Sunday (5/30), 13 Deaths were reported.  For Monday (5/31), another 13 Deaths were Reported. This morning (Tuesday, 2021-06-01), 8 Deaths were reported.  It's my understanding that these deaths are backlogged (certificate) deaths, and that they are most likely prepared/collected/analyzed the day before, then released on the JHU CSSE GIS & Data Database early the next morning (what I would term the reporting date) as well as on VA's Plot at the link I gave above, & that you have also given (They are also released in spreadsheet format also and it's possible to perform the backlogging; I've done it once a month for the last 2 months during my US Death Analysis, here: https://www.reddit.com/r/CoViD19_Analysis/ )...

... Since I am looking at the data as it is posted throughout the day (Tuesday), this is ongoing data and I really shouldn't be commenting/analyzing it until it becomes registered via the end of the day, via the [US] Automated [Delayed] Update(s).  I reference the cumulative deaths against the previous day's Automated Update (in this case: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/05-31-2021.csv ) Each hour (shortly after the on the half hour update), I grab the following file to perform the deltas (which hasn't changed for the last 14 hours): https://github.com/CSSEGISandData/COVID-19/blob/web-data/data/cases_state.csv .  During this whole process, it's quite possible that I have an error in the logging, since I spent some of the weekend modifying it.  It's more likely that I misunderstand the updating process that is the cause of any discrepancy on my end...

... For the most part, the VA updating has followed this pattern, except for a couple weeks ago (when we both noticed an issue) and today (There was a day when the Indiana Reporting didn't agree with JHU (several days ago), but that never occurred again; IN handles things similar to VA, but I haven't been able to backlog their data yet.)...

... I hope I'm explaining things on my end, to sufficiently understand what is going on with today's (ongoing) VA Case.  It's interesting that we have the hourly times to figure out what actually happened, in the logging (above).

Thanks,

**Comment by JustaNormalGuy230** [comment]
What is the difference between:
1): https://github.com/CSSEGISandData/COVID-19/raw/web-data/data/cases_state.csv
2): https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_state.csv

Is one a cache of the other? ... Is there a delay between when one updates versus the other? .... Do they vector to the same file, one with a slight delay?

Thanks

**Comment by JustaNormalGuy230** [comment]
I have found a bug in my Weekend Modifications of my Code that resolves the Issue, but I would appreciate a response to the question immediately above, concerning the 2 versions/locations of cases_state.csv, thanks.

The issue involved searching for "Virginia" and also getting a hit for "West Virginia", thus summing the deltas for both states, when calculating the delta for "Virginia".  I don't think the problem would have occurred for an other US State/Territory/Entity, so it only showed up for this particular search/state.

**Comment by CSSEGISandData** [comment]
Hello,

The two versions of the csv should be in sync. That they exist as two files is just do to GitHub's file management.
