### ISSUE TITLE
United Arab Emirates slope of active cases is constant for a while

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#4177]
Hi all,

the active cases for the UAE are following a more or less constant slope. I went on their dashboard to check if there is an explanation for that. Could it be that you are picking up the vaccination rates as active cases?
![image](https://user-images.githubusercontent.com/22978682/120491690-bcde8d80-c3b9-11eb-9faf-ad27a1a0dda9.png)

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hi Christoph,

Probably a weird coincidence. Our reported active cases are computed on our side as (confirmed)-(deaths+recoveries), so we don't collect them from the source side. Thanks for checking!

**Comment by c-hera** [comment]
Thanks for getting back to me and the feedback, appreciated!
