### ISSUE TITLE
Peru: Number Of Deaths

### ISSUE THREAD

**Issue by oboyco** [CSSEGISandData/COVID-19#4179]
Hi, could you please check your time series "Peru: Number Of Deaths" here:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

We can see suspicious volatility that looks like error in 06/02/2021 period in latest update on 06/03/2021.
Could you please advise on this.
Thank you.
#PER.DEATHS.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Please see #4167
