### ISSUE TITLE
Sudden peak of deaths for some Latin American countries

### ISSUE THREAD

**Issue by alessiolombini** [CSSEGISandData/COVID-19#4183]
Bolivia, Peru and Ecuador experienced strange sudden peaks, followed by a sudden drop, of COVID-19 deaths. These are shown in September, August (and July) and September respectively. Might you kindly explain which are the causes?

**Comment by CSSEGISandData** [comment]
Hello,

The cause of the spikes in Peru and Ecuador are documented in our data [README](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md). 

The cause of the spike in Bolivia is uncertain but it is also present in data published by PAHO ([linked here](https://www.paho.org/en/file/72208/download?token=Tgj4cHcb) - its a pdf download).
