### ISSUE TITLE
Spike in Alaska deaths on May 17 is from death certificate review

### ISSUE THREAD

**Issue by krivard** [CSSEGISandData/COVID-19#4184]
I found a spike in Alaska deaths that's not listed in the [retrospective reporting log](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md#retrospective-reporting-of-probable-cases-and-deaths):

https://alaska-native-news.com/covid-19-daily-summary-may-17-2021/55811/

10 of 11 deaths reported on May 17 were from death certificate review.

**Comment by CSSEGISandData** [comment]
Thank you! I have added it to our README.
