### ISSUE TITLE
South Africa Latest Case's incorrect value of 0

### ISSUE THREAD

**Issue by Alpha2492** [CSSEGISandData/COVID-19#4187]
Latest data for South Africa is incorrect.

1st June 2021 is correct.

2 June 2021 should be 5782 not 0
3 June 2021 should be 5361 not 0

Source: https://sacoronavirus.co.za/

Thanks :D

**Comment by xapel** [comment]
Case and death numbers for South Africa for the last 2 days have been incorrectly reported as 0 in the repository.

**Comment by CSSEGISandData** [comment]
Thank you. This will have been resolved by #4190
