### ISSUE TITLE
Peru spike due to excess death adjustment

### ISSUE THREAD

**Issue by fibke** [CSSEGISandData/COVID-19#4188]
Do you expect that the large excess death adjustment recently introduced will remain allocated in the dataset to one single day? Or will it be spread over the entire period over which the excess have been incurred?

**Comment by fibke** [comment]
WHO has started to report the correct information day-by-day FYI. Would be nice to have this updated in your dataset too:

https://covid19.who.int/table

**Comment by CSSEGISandData** [comment]
Please see #4207.
