### ISSUE TITLE
Taiwan is a independent country, NOT PART OF CHINA.

### ISSUE THREAD

**Issue by FinnWeng** [CSSEGISandData/COVID-19#419]
Taiwan is a independent country, NOT PART OF CHINA.

The purpose of this service should be providing current situation of WUHAN Corovavirus.
Not serving as promotion of China Fascism. 

If humanity and liberalism is still virtue for you,  please correct this mistake.

Don't kneel on front of Xi.

**Comment by puetsua** [comment]
This repository should be a confirmed case of communist virus.

**Comment by issuehsu** [comment]
Agree! This repository is infected by the communist virus.

**Comment by CSSEGISandData** [comment]
please see issue #482
