### ISSUE TITLE
Taiwan is not part of China

### ISSUE THREAD

**Issue by RoyaHsueh** [CSSEGISandData/COVID-19#421]
Notice ! Taiwan is a independent country. Taiwan is never ever in part of China.
I have no idea why developer decide to remove Taiwan from the dashboard, why let all people ignore it?

**Comment by patrickfung** [comment]
Yes, please don't merge the data for Taiwan with China together.

**Comment by CSSEGISandData** [comment]
please see issue #482

**Comment by RoyaHsueh** [comment]
Truly appreciate it. Thank you.

**Comment by patrickfung** [comment]
Thank you!
