### ISSUE TITLE
UK confirmed cases, negative values

### ISSUE THREAD

**Issue by khblue** [CSSEGISandData/COVID-19#4210]
UK covid-19 confirmed cases for 9th April 2021, 18th May 2021 have negative values. This site pulls and uses the github data.

https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&minPopulationFilter=1000000&time=2021-04-05..latest&pickerSort=asc&pickerMetric=location&hideControls=true&Metric=Confirmed+cases&Interval=New+per+day&Relative+to+Population=true&Align+outbreaks=false&country=GBR~PRT

**Comment by CSSEGISandData** [comment]
Hello,

The reasons for these drops are documented in [our README](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#readme). The reasoning is also available in the [data notes](https://coronavirus.data.gov.uk/details/whats-new) for the United Kingdom dashboard.

**Comment by khblue** [comment]
Many thanks.
