### ISSUE TITLE
Why did COVID death totals decrease by 399 in California yesterday

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#4221]
Is California correcting some type of past overreporting of COVID deaths? The number of cumulative deaths as of June 10, 2021, was 399 lower than on June 9. This issue is present in the ..../csse_covid_19_daily_reports directory. I have not checked whether it is also present in the ..../csse_covid_19_daily_reports_us directory.

**Comment by CSSEGISandData** [comment]
Please see #4223
