### ISSUE TITLE
Wrong New Cases in Singapore on 2021-06-12

### ISSUE THREAD

**Issue by TobySkarting** [CSSEGISandData/COVID-19#4235]
The Ministry of Health of Singapore had announced 21 new cases on 2021-06-12, but then withdrawn 3 cases afterward, according to the [official news](https://www.moh.gov.sg/news-highlights/details/9-new-cases-of-locally-transmitted-covid-19-infection_12_June2021):

> This is updated from our afternoon press release as we have withdrawn 3 cases which were verified to be negative for COVID-19 upon further tests

so the number of new cases is 18, with the total cases of 62263, while this repository is recording as -21, with that of 62224.

On 2021-06-13, there are [13 new cases](https://www.moh.gov.sg/news-highlights/details/10-new-cases-of-locally-transmitted-covid-19-infection13june/). Due to the wrong recording of the previous day, the number of new cases recorded becomes (62263 + 13) (correct total) - 62224 (wrong previous total) = 52.

Compared to the recent situation in Singapore, this number is quite high and not reflecting to the reality.

![](https://i.imgur.com/RvLvFom.png)

**Comment by CSSEGISandData** [comment]
Closed by #4239
