### ISSUE TITLE
Namibian Data out of date 06/16/2021

### ISSUE THREAD

**Issue by EstherBasson** [CSSEGISandData/COVID-19#4250]
The Namibian Covid data as reflected shows zero new cases for 16 June 2021, likely as the figures had not been released at the time of publishing. The figures have been released by the Namibian Department of Health and are in fact as follows: 
Newly confirmed cases : 2075
Recoveries : 796
Active cases : 11 678
Deaths : 33

**Comment by CSSEGISandData** [comment]
Resolved by #4266. If this happens in the future, it is due to the Ministry of Health releasing data late and we will do our best to fix.
