### ISSUE TITLE
is Cook Island maybe a separate nation?

### ISSUE THREAD

**Issue by greg-minshall** [CSSEGISandData/COVID-19#4256]
[wikipedia](https://en.wikipedia.org/wiki/Cook_Islands) seems to think so.

(it's sort of an issue, having both blank and non-blank Province_State columns for the same Country_Region; of course, that's my programming not yours.  but, still...)

cheers!

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your comment. We use the designations of the United States State Department when deciding the governance of locations. Their list for ["Dependencies and Areas of Special Sovereignty"](https://www.state.gov/dependencies-and-areas-of-special-sovereignty/) place the Cook Islands under the sovereignty of New Zealand.
