### ISSUE TITLE
Reports stopped for Lebanon

### ISSUE THREAD

**Issue by roysaad** [CSSEGISandData/COVID-19#4258]
Numbers have stopped being updated for Lebanon starting from June 15 2021

**Comment by CSSEGISandData** [comment]
Hello,

The Lebanese government appears to have stopped maintaining their dashboard but are still updating via press release. We will work on a method of updating their data.

**Comment by CSSEGISandData** [comment]
Hello,

This has been addressed and we have back distributed the data from June 15 to 20 in #4270.
