### ISSUE TITLE
Nova Scotia data error

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#4265]
The number of reported confirmed cases for Nova Scotia, Canada on 2021-06-20 was 5791 NOT 5251 as was reported.

**Comment by bftsystems** [comment]
Yup, ACTIVE column currently showing -457 active cases, which is definitely not correct.

**Comment by CSSEGISandData** [comment]
Thank you for bringing this to our attention. This should be resolved with #4268.
