### ISSUE TITLE
Taiwan Recovery Huge Jump on June 21

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#4272]
Hello team,

I found that Taiwan recovery jumps to over 7000 from 1133, which is a very large increase. However, confirmed cases and deaths do not indicate this huge jump. May I ask if this figure is correct or if you will revise the history of recoveries?

Thanks

**Comment by CSSEGISandData** [comment]
Hello,

Unfortunately it does not appear that our Taiwanese source has historical data for recoveries so we will not be able to back distribute these newly reported recoveries.

**Comment by RuijingZ** [comment]
> Hello,
> 
> Unfortunately it does not appear that our Taiwanese source has historical data for recoveries so we will not be able to back distribute these newly reported recoveries.

Thanks for explanation. I am looking at the source that list in ReadMe, but there is no recoveries data from this site: https://sites.google.com/cdc.gov.tw/2019ncov/taiwan?authuser=0
May I ask where the recoveries data come from?
