### ISSUE TITLE
Put science above politics please 

### ISSUE THREAD

**Issue by sjmackenzie** [CSSEGISandData/COVID-19#428]
It is incorrect to classify Hong Kong and Macao as a province or state. They are Special Administrative Regions and are self governing. The only thing they lack are a permanent military run by themselves. In essence they are their own country with border control, passports and their own monetary system.

Taiwan on the other hand has all of the above and their own military. 

We need this data for scientific purposes and not political purposes.

I need a recommendation on where to get accurate non-politicized data https://twitter.com/sj_mackenzie/status/1237654254208180224

**Comment by CSSEGISandData** [comment]
please see issue #482
