### ISSUE TITLE
wrong czech data

### ISSUE THREAD

**Issue by radekborsky** [CSSEGISandData/COVID-19#4296]
hi, 

there are definitely wrong data here.
if you check 
https://www.google.cz/search?q=covid+stat&source=hp&ei=TJ_ZYOqwI-SDjLsP0OyjuAc&iflsig=AINFCbYAAAAAYNmtXOLNC-7QCoA7PTTnUpjF77LCt5cr&oq=covid+stat&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAELEDMggIABCxAxDJAzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAOggIABCxAxCDAToOCAAQsQMQgwEQxwEQowI6BAgAEAM6CAgAEMcBEKMCOgsIABCxAxDHARCjAjoICC4QsQMQgwE6CwgAELEDEMcBEK8BOgcIABCxAxAKUJwGWOwOYPwRaABwAHgAgAF1iAGoBZIBAzkuMZgBAKABAaoBB2d3cy13aXo&sclient=gws-wiz&ved=0ahUKEwjqhtm3irrxAhXkAWMBHVD2CHcQ4dUDCAY&uact=5
and 
https://onemocneni-aktualne.mzcr.cz/covid-19
(this page you are supposed to obtain data from)
- you see some discrepancies
- there was no 196, 165 positive people last week, but google (who gets data from you) shows it. 
- please sort it out, so your data match those on https://onemocneni-aktualne.mzcr.cz/covid-19

**Comment by CSSEGISandData** [comment]
Hello,

This has been raised before in #3819. Please see the disclaimer on the [Czechia dashboard](https://onemocneni-aktualne.mzcr.cz/covid-19): "S ohledem na fakt, že u publikovaných dat probíhá validace a průběžné doplňování hlášení, může u přehledů osob s laboratorně prokázaným onemocněním COVID‑19 dle hlášení KHS a laboratoří docházet zpětně k drobným změnám. Poslední aktualizace dat v tomto přehledu byla provedena k půlnoci předchozího dne."

**Comment by radekborsky** [comment]
it doesn't make much sense, because your data has more people sick than the original. so additional occurrences is not this case.
either they gave your wrong data (c. 50% more occurrences than there truly were, or you imported the data wrong way..)
