### ISSUE TITLE
Campbell, VA backlog of cases between 6/24 and 6/26

### ISSUE THREAD

**Issue by sth-del** [CSSEGISandData/COVID-19#4299]
Hello,

It appears that Campbell County, VA released old data between 6/24 and 6/26. Prior to these days, the 14-day average of new cases was 1. Here are the numbers of new cases reported:

6/24 - 66
6/25 -  231
6/26 - 94

Any insight into this would be appreciated.

**Comment by CSSEGISandData** [comment]
Hello,

The case counts match those posted on the [Virginia dashboard](https://www.vdh.virginia.gov/coronavirus/covid-19-in-virginia-locality/). We'll reach out to their DoH for comment.
