### ISSUE TITLE
Ohio deaths on 2021-06-22 and 2021-06-25 not backdistributed as of 2021-06-28

### ISSUE THREAD

**Issue by brookslogan** [CSSEGISandData/COVID-19#4300]
The Ohio death time series data has spikes on 2021-06-22 (47 deaths) and 2021-06-25 (68 deaths), using a version of the data as of 2021-06-28.  I'm assuming that these are spikes that have not been backdistributed yet.  [The upstream csv by date of death](https://coronavirus.ohio.gov/static/dashboards/COVIDDeathData_CountyOfResidence.csv) seems to have dates of death only through 2021-06-20, yet may still have updates not in the JHU-CSSE data: e.g., on 2021-06-11, it appears to have 4 deaths (by date of death) recorded instead of the JHU-CSSE value of 1 death.  This may indicate that the JHU-CSSE backdistribution script didn't run or encountered a problem rather than that the upstream data are still stale.

(I'm using this code to compare the values:)
```
library(tidyverse)
read_csv("COVIDDeathData_CountyOfResidence.csv", col_types=cols(`Date Of Death`=col_date())) %>% group_by(`Date Of Death`) %>% summarize(deaths=sum(`Death Due To Illness Count - County Of Residence`)) %>% arrange(`Date Of Death`) %>% print(n=500)
library(covidcast)
covidcast::covidcast_signal("jhu-csse","deaths_incidence_num",geo_type="state",geo_value="oh",start_day=Sys.Date()-30L,end_day=Sys.Date()-1L) %>% select(time_value,value)
```

**Comment by CSSEGISandData** [comment]
Hello,

What time did you pull the data? There was a commit at 6:02 PM GMT +1 today to back distribute data, about 4:10 minutes before this issue was posted.

**Comment by brookslogan** [comment]
I pulled the data a few times throughout the day 10AM--5PM for preparing and sanity-checking forecasts, but `covidcast` will typically record the data only once per day, sometime in the morning, too early for the 1:02PM EDT update, so
```
library(dplyr)
library(covidcast)
covidcast::covidcast_signal("jhu-csse","deaths_incidence_num",geo_type="state",geo_value="oh",start_day=Sys.Date()-30L,end_day=Sys.Date()-1L,as_of="2021-06-28") %>% select(time_value,value)
```
still includes this mixed data while `as_of="2021-06-29"` has the backdistributed version.
