### ISSUE TITLE
Wrong New Cases in Singapore on 2021-06-29

### ISSUE THREAD

**Issue by TobySkarting** [CSSEGISandData/COVID-19#4319]
The Ministry of Health of Singapore has announced 10 new cases on 2021-06-29, according to the [official press release](https://www.moh.gov.sg/news-highlights/details/5-new-cases-of-locally-transmitted-covid-19-infection-29jun201).

> In total, there are 10 new cases of COVID-19 infection in Singapore today.

So the total number of confirmed cases should be 62563 on June 29.

**Comment by CSSEGISandData** [comment]
Thank you for flagging this! This should have been resolved with #4329
