### ISSUE TITLE
Wrong cases for Summer Olympics

### ISSUE THREAD

**Issue by NikitaCbonds** [CSSEGISandData/COVID-19#4337]
Hi!

I see a rise from 1 to 6 of confirmed cases on the Olympics and then again 1 in time_series_covid19_confirmed_global.csv

![изображение](https://user-images.githubusercontent.com/65162091/124739096-38d07600-df22-11eb-8769-80af468b6d70.png)

And from July 5 again 6 cases confirmed.

Why did it happen? 6 people were wrongly positive?

**Comment by CSSEGISandData** [comment]
Thanks for bringing this to our attention! This should be resolved with #4339.
