### ISSUE TITLE
South Africa vaccine stats updating but fully vaccinated Individuals not being updated 

### ISSUE THREAD

**Issue by Justinkri** [CSSEGISandData/COVID-19#4338]

**Comment by CSSEGISandData** [comment]
Thank you very much for raising this issue. Coincidentally, the South Africa Ministry of Health has altered the structure of their reporting to remove this issue. Nevertheless, I will describe the conditions that resulted in the data for fully vaccinated being stale just as useful information for the challenges in collating this data.

Firstly, the vaccine data is available from the following link: https://sacoronavirus.co.za/latest-vaccine-statistics/. Prior to the July 9, the dashboard had consisted of four pages, none of which included measures for reporting individuals partially or fully vaccinated. The second page did, however, include total doses administered through two government programs - the Sisonke Programme and the National Programme. The Sisonke Programme was only for healthcare workers and consisted of doses of the Johnson & Johnson vaccine (and thus all dosed individuals were tabulated as fully vaccinated).  The National Programme is administering the Pfizer vaccine. As it only recorded doses administered, we were left with the assumption that this was the first dose of the series and included each of these individuals as partially vaccinated. The Sisonke Programme had not given doses for some time and we were not able to identify second doses in the National Programme which was the reason “people fully vaccinated” had been stale.

Thankfully, the Ministry of Health’s new dashboard specifically totals those partially and fully vaccinated (table 4) and both metrics are now updated daily.
