### ISSUE TITLE
July 8 and July 9 Data for Turkey are the Same?

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#4346]
Currently, JHU's global csv file shows the same figures for Turkey on July 8 and 9. 

The Ministry of Health of Turkey publishes the COVID19 data on https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html

Unfortunately, on the MoH TR's aformentioned page, the aggregated tests, confirmed cases, deaths, and recoveries are not presented in an aggregated manner after July 3. 

When aggregated, July 9 COVID19 data for Turkey should be reflected as
Total tests: 62798364
Total confirmed cases: 5470764
Total deaths: 50155
Total recoveries: 5338885

**Comment by zekib** [comment]
Recently the MOH stopped publishing the total cases and total deaths.  But they continue to post new cases and deaths every day.  This may be the cause of this error. We need this fixed.

**Comment by tllkrmn** [comment]
Seems partially solved for 9-11 July 2021 but data for 12 July shows 9 July data now.

**Comment by CSSEGISandData** [comment]
This has been patched with #4359.
