### ISSUE TITLE
Cases for Bavaria are way too high on May 14th 2020 in Google search results

### ISSUE THREAD

**Issue by Julian1203** [CSSEGISandData/COVID-19#4348]
I think you can clearly tell what's wrong just by looking at the graph. As Google says that you're the source for the data, I think it's your data that causes this.
![Screenshot_20210711_111845](https://user-images.githubusercontent.com/29153612/125189787-2b74fd80-e23a-11eb-83f5-0762b18136dc.png)
![Screenshot_20210711_111823](https://user-images.githubusercontent.com/29153612/125189789-2ca62a80-e23a-11eb-89ec-0c35f59b6e95.png)

**Comment by CSSEGISandData** [comment]
Hello,

May 14, 2020 was the first day where we were able to access and publish subnational data for Germany. This spike on May 14, 2020 represented all cases that had been identified in that location to date and this is the case for all subnational locations in Germany. 

We don't have subnational time series published at the moment for this reason (they will inevitably be incomplete). Google is choosing to access our daily report files for this visualization. It is currently not feasible for us to back distribute subnational data for all locations where we have increased our data resolution.
