### ISSUE TITLE
Taiwan cases missing since June 20?

### ISSUE THREAD

**Issue by Francoyy** [CSSEGISandData/COVID-19#4349]
Somehow Google stopped showing Taiwan cases since June 20.
Not sure why, I couldnt find if the data is missing or if the problem is somewhere else. Feel free to close this issue if not related to data.
https://www.google.com/search?q=covid+cases+taiwan

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the message. Our data products show updated case data so this appears to be an issue with Google's visualization. Sorry that we are unable to help.
