### ISSUE TITLE
Hong Kong has its own immigration border and CDC

### ISSUE THREAD

**Issue by richardhyu** [CSSEGISandData/COVID-19#435]
It is incorrect to list Hong Kong as a province of China. The US Hong Kong Relationship Act regards HK as a separate governing entity from China. Even for the purpose of science, Hong Kong has its own border control, immigration and healthcare system, that is independent of China. Mixing it with China is not helping disease prevention, but to give in to political pressures from the Chinese.

**Comment by CSSEGISandData** [comment]
please see issue #482
