### ISSUE TITLE
Kenya drop of active cases on 2021-07-09 (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#4351]
Hi all,

Active cases in Kenya dropped from 52710 to 6476 between 8th and 9th July 2021.
Unfortunately, I am not sure which source you are using so I was not able to have a look myself.

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Hi Christoph,

Thanks for your message (as always!). The Kenya Ministry of Health publishes their data to a twitter feed, and we access the data from another aggregate source that publishes this data in a machine-readable format. 

From [July 6](https://twitter.com/MOH_Kenya/status/1412463622270427137) to [July 7](https://twitter.com/MOH_Kenya/status/1412804806624882696), the Ministry of Health published a very large increase in recoveries which we were able to validate and publish on the 9th. This lead to the decrease in active cases. The MoH did not specify what factors had changed that resulted in the large increase in recoveries.

**Comment by c-hera** [comment]
Thanks for the explanation, appreciated!
