### ISSUE TITLE
Ukraine Numbers Reported are Different to Referenced Source

### ISSUE THREAD

**Issue by Tofel4US** [CSSEGISandData/COVID-19#4362]
Hello.

I have compared data reported by your team with referenced source data for Ukraine and found a mismatch seen there from day one of reporting. Please find 7 days of data compared in excel attached.
[Data Check - Ukraine.xlsx](https://github.com/CSSEGISandData/COVID-19/files/6814052/Data.Check.-.Ukraine.xlsx)

I have compared only 4 data points below while other data points are advised to be verified as well:
- total_cases
- new_cases
- total_deaths
- new_deaths		

Thank you and
Best Regards,
Valentyn

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Consistent with the designations of the US Department of State, our totals for Ukraine include those of the Crimea Republic and Sevastopol which are not included in the Ukrainian source. These totals are accessed from the [Russian Ministry](https://xn--80aesfpebagmfblc0a.xn--p1ai/information/).

This is recorded in June 5, 2020 of the Data Modification Records of the [README file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md).
