### ISSUE TITLE
Global recoveries to no longer be maintained in one week (July 21)

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#4369]
In one week’s time (July 21), we will no longer be maintaining recovered data globally. As detailed in issue #3773 where we removed recovery data at the state level, we have determined this metric to generally be unreliable globally. Locations where we would normally have to perform maintenance to regain access to recovery data will instead be held stale.

**Comment by familyachil** [comment]
Stil research
