### ISSUE TITLE
Taiwan is not part of China in all perspective.

### ISSUE THREAD

**Issue by KilinW** [CSSEGISandData/COVID-19#438]
If you do some research. You will realize that Taiwan is not part of China in economic, political, military, land, people, and so on.
But if you consider China's delicious money, aggressive oppression and threat.
Then yeah, Taiwan is part of China.
That's what we face everyday. 
Hope you have basic conscience.
But if you don't, we will not be surprise about it.

**Comment by CSSEGISandData** [comment]
please see issue #482
