### ISSUE TITLE
Iowa Confirmed Cases Discrepancy and Singapore recoveries

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#4381]
Hello,

I found that Iowa confirmed cases are declining since July 7. And I cannot match the figures to any of the figures here: https://coronavirus.iowa.gov/pages/case-counts
May I ask what numbers are you quoting for this?

For Singapore recoveries, they also show declining trend. I understand the recoveries data would be discontinued soon, but still would like to ask if the recoveries data are valid for Singapore?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the message. Our time series is built from the daily reported totals for each location, and our source for Iowa is the same as you indicate. This source does not contain a similar time series figure based on _report date_ which is the cause of the discrepancy.

Our numbers are still being updated for Singapore and are based on the 'discharges' reported on the [Singapore dashboard](https://www.moh.gov.sg/covid-19).
