### ISSUE TITLE
problem with cumulative counts in global recovered :

### ISSUE THREAD

**Issue by sanjayhamal** [CSSEGISandData/COVID-19#4388]
there is an error in the cumulative recording of recovered cases in few of the dates. The counts in some dates are lower than their prior recordings which needs to be fixed.

![image](https://user-images.githubusercontent.com/66766529/126068115-6a71c4a6-0e50-431e-96a9-60f54d05d0d1.png)

**Comment by CSSEGISandData** [comment]
Thank you for your message. Please see #3464 detailing when the US level total recoveries were nullified.
