### ISSUE TITLE
time_series_covid19_confirmed_global.csv Drop of cases in France on 19 May 2021

### ISSUE THREAD

**Issue by DrFabach** [CSSEGISandData/COVID-19#4391]
There is a sharp decline in confirmed cases in France between 19 May 2021  (5863138 ) and 20 May 2021 (5514022).

This is quiet unexpected.

**Comment by CSSEGISandData** [comment]
Hello,

This has been documented in the [README file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md) as an entry on May 20, 2021. It reads:

"May 20, 2021: France | Reduction of 350,000 duplicate cases without correcting historical data | See press release"
