### ISSUE TITLE
Icelandic case data inconsistencies

### ISSUE THREAD

**Issue by Kalli** [CSSEGISandData/COVID-19#4394]
The recent time series data for Iceland appears to be in error. The [`time series`](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) data shows no cases in Iceland since mid May 2021, but official Icelandic sources have reported cases in the last weeks. 

## Official Icelandic data 

You can find the official Icelandic covid stats at: https://www.covid.is/data ([csv link](https://e.infogram.com/6a1497cc-b1c8-4547-9528-1b79a1898283?parent_url=https%3A%2F%2Fwww.covid.is%2Fdata&src=embed#)). This is mentioned as a data source in your [ReadMe](https://github.com/CSSEGISandData/COVID-19)

<summary>
<details> Screenshot:

![image](https://user-images.githubusercontent.com/465566/126171028-2ff76c17-b324-4b45-a742-e1217f28e689.png)

</details>
</summary>

## JHU - Covid-19 Dashboard

If you select Iceland in the [dashboard](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), you'll see it looks like cases have not been updated since mid may 

<summary>
<details> 

Screenshot:

![image](https://user-images.githubusercontent.com/465566/126178172-e34af805-4aa5-4ce9-8de1-224b38ee4cbb.png)

</details>
</summary>

## JHU Data 

*Edit: My original comments on the daily data were using the incorrect dates, corrected now* 

If you look at the daily reports, they have been stuck at `6555` since `05-20-2021`:

```bash 
$curl -s https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-20-2021.csv | sed '1p;/Iceland/!d'
FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
,,,Iceland,2021-05-21 04:20:43,64.9631,-19.0208,6555,29,6476,50,Iceland,1920.8791208791208,0.4424103737604882
```

If you look at [`time_series_covid19_confirmed_global.csv`](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) Icelandic reports have been stuck at `6555` since `5/19/21`

```bash
curl -s https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv | sed '1p;/Iceland/!d'
```

## Other links 

* [News about press briefing](https://www.ruv.is/frett/2021/07/15/covid-press-briefing) on increasing infection rates from 15.07.21 from RÚV the national broadcaster
* See also reports in this [Twitter thread](https://twitter.com/OurWorldInData/status/1416020311875768323)

Thanks for your time and for all of your hard work on providing this great resource!

**Comment by CSSEGISandData** [comment]
Thank you. We've investigated this issue and it is due to Iceland no longer updating [their original dashboard](https://e.infogram.com/deaf4fd6-0ce9-4b82-97ae-11e34a045060?parent_url=https%3A%2F%2Fwww.covid.is%2Fdata&src=embed#async_embed) and migrating to a new dashboard with new endpoints on their [main site](https://www.covid.is/data). We have adapted our process to capture this new source and have back distributed case and death data for the days that were stale.

**Comment by Kalli** [comment]
Nice. Thanks for the swift response and for the great work in general.
