### ISSUE TITLE
Covid stats for Colombia on July 10th and 11th, 2021 need to be rectified.

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#4399]
Number of recovered cases in Atlantico, Colombia for 10th July, 2021 is exactly same as active cases on July 11, 2021. Also, active cases for July 10th are showing negative i.e. -284300.

Total number of confirmed and death cases for Colombia is same for both these dates.

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this issue. We have corrected our data on the 10th and the 11th to align with official reporting.
