### ISSUE TITLE
Contents of csv files are overwritten. Why?

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#44]
How can it be that in, for example, the last data (daily_case_updates) of 12 February 2020, 22.00 (02-12-2020_2200.csv), there are update data with the date 13 February 2020?

Then the data is no longer correct? It's like when I name a file January 10th, but keep updating the contents. Then nothing at all matches anymore.

![Bildschirmfoto vom 2020-02-14 01-54-28](https://user-images.githubusercontent.com/49625256/74492098-f7bf6800-4ecd-11ea-8c3b-907a1e47975e.png)

**Comment by dawenx** [comment]
See the README file on this directory, the “Last Update” column is using UTC and the file name is using EDT.

**Comment by iceweasel1** [comment]
Thanks for the answer. I already know the column with the "last update".

Is there a plausible explanation why you use two different time zones (UTC, EDT) and not a single one?

This inevitably leads to irritations.

**Comment by dawenx** [comment]
@iceweasel1 I agree with you. I talked to one of the JHU developers a few days ago and raised the same concern. I think they will address it.

Or the community can come together to:

- [ ] come up with a standard.

- [ ] generate new files and data based on the standard.

- [ ] meanwhile, JHU will follow standard when they generate new files. @enshengdong

**Comment by dawenx** [comment]
ps. we just prepared a short tutorial for my tool, you can find it [here](https://drive.google.com/open?id=17Afk9ksxE32XXqs7TPE-O0Qa_FreV33Y)
