### ISSUE TITLE
How Dare Totalitarian China Keep Oppressing Taiwan and the World

### ISSUE THREAD

**Issue by eileen71** [CSSEGISandData/COVID-19#440]
Stop claiming Taiwan is a part of China. Coronavirus is a serious global issue, not a field for unreasonable bully. So fed up with PRC. They are everywhere, in everytime, and will eat you to death, eat you alive, Can't the world see how despicable and brutal they are?

**Comment by CSSEGISandData** [comment]
please see issue #482
