### ISSUE TITLE
Colombian data has an error - July 12th

### ISSUE THREAD

**Issue by catalinamcruzr** [CSSEGISandData/COVID-19#4401]
It seems there's a mistake on July 12th, because data from 10th and 11th are in 0. However the 12th is adding up 3 different dates creating a huge mistake in deaths and cases reported daily. 
<img width="1002" alt="Screen Shot 2021-07-19 at 12 40 16 PM" src="https://user-images.githubusercontent.com/87737919/126409700-fece9dbf-4423-44e2-af1a-860430a8d33c.png">
<img width="995" alt="Screen Shot 2021-07-19 at 12 41 42 PM" src="https://user-images.githubusercontent.com/87737919/126409718-ea8dfe9b-4d2b-46d7-be9e-5b8fb505908c.png">

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this issue. We have adjusted our data to match the correct reporting for these days.
