### ISSUE TITLE
Colombia's total number of administered vaccines doses is wrong - July 21st 2021

### ISSUE THREAD

**Issue by SimonKaran13** [CSSEGISandData/COVID-19#4404]
According to different sources, the current (21/July/2021) number of administered doses is around the 23 million mark, according to the data, more than 238 million doses have been administered.
![image](https://user-images.githubusercontent.com/69362542/126502632-02aca597-86cd-426b-b4ae-8d5f959d34ce.png)

This error can be reproduced in the "Global Map", by clicking the "Global Vaccination" tab.

**Comment by CSSEGISandData** [comment]
Thank you, this has now been corrected.
