### ISSUE TITLE
Covid - Active cases for Colombia on July 10th and 11th, 2021 needs to be rectified 

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#4411]
Currently, the active cases for both days are same i.e. 160665 whereas:
For 10th July, expected active cases = 152041 (4492537 - 4228198 - 112298)
For 11th July, expected active cases = 144576 (4511960 - 4254558 - 112826)
Formula : active cases = total cases - total recovered - total deaths

Please validate and rectify the active cases for both days.

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this issue. We have corrected our active cases for the 10th and the 11th.
