### ISSUE TITLE
Florida data stale since July 16

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#4415]
I haven't checked the \\csse_covid_19_daily_reports_us directory, but the Florida data in the \\csse_covid_19_daily_reports directory has not been updated since July 16. Is Florida still in denial?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Florida has shifted their reporting to only provide data once per week on Fridays. We should see an update this evening.
