### ISSUE TITLE
NSW Australia: discrepancy between CSSEGIS and cited sources

### ISSUE THREAD

**Issue by Patrick-closeassociate** [CSSEGISandData/COVID-19#4423]
Cumulative cases in NSW Australia are reported by CSSEGIS as:

- 22 July 2021 - 7498
- 23 July 2021 - 7492
- 24 July 2021 - 7792
- 25 July 2021 - 7943

The data sources cited by CSSEGIS (see below) report different numbers

Government Department of Health: https://www.health.gov.au/news/coronavirus-update-at-a-glance
(For NSW see https://www.nsw.gov.au/covid-19/find-the-facts-about-covid-19)

- 22 July 2021 - 7344
- 23 July 2021 - 7495
- 24 July 2021 7638
- 25 July 2021 - 7753

COVID Live: https://www.covidlive.com.au/

- 22 July 2021 - 7357
- 23 July 2021 - 7492
- 24 July 2021 - 7651
- 25 July 2021 - 7792

Why are the numbers reported different from the sources cited?

**Comment by CSSEGISandData** [comment]
Closed by #4427.
