### ISSUE TITLE
Number of confirmed cases on 23-Jul-2021 not updated for some countries 

### ISSUE THREAD

**Issue by b-ear** [CSSEGISandData/COVID-19#4424]
(time_series_covid19_confirmed_global.csv)

For Australia, India, South Korea and Vietnam (as far as I can see) the datapoints for 22-Jul-2021 and 23-Jul-2021 is the same/not updated. 

Many thanks!

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for noticing this. We have patched the error in our pipeline that caused this and are working a back distribution for the stale countries (they are more than those you listed unfortunately). We will update this issue when we are able to merge in a data fix. Thank you for your patience.

**Comment by CSSEGISandData** [comment]
Thanks again. This was resolved with #4429.
