### ISSUE TITLE
New cases and death cases for Guatemala are not updated since July 20, 2021

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#4428]
Covid data for Guatemala from July 20th till date is either missing or incorrect when compared with worldometers and WHO stats. This is also causing the total confirmed cases to show incorrectly. For e.g. total confirmed cases for July 19th and July 20th is same i.e. 334375 which shows new cases as zero.

Refer:
Worldometers- https://www.worldometers.info/coronavirus/country/guatemala/
WHO- https://covid19.who.int/region/amro/country/gt

**Comment by CSSEGISandData** [comment]
Hello,

Our source had been stale for those days but resumed reporting on July 21.
