### ISSUE TITLE
Non-sens value for New Zealand confirmed cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4433]
Hi team,
Could you please check the data for New Zealand confirmed cases as we observe non-sense value for July 23, 2021 (or for further values).

![image](https://user-images.githubusercontent.com/80464515/127113127-4bc332d0-b779-4663-972d-3d13ed1e0de9.png)

Could you please check and advise?
Thank You

**Comment by CSSEGISandData** [comment]
Patched by #4442.
