### ISSUE TITLE
Suspicious data - China, Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4435]
Hi Team,

Could you please check data for China, Number Of Confirmed Cases
We can see suspicious data in 07/23/2021 as there is " China unknown" region with 37 confirmed cases only for 1 day .
Could you please advise on this?

Thank You.

Best regards,

KATERYNA BOBRYK
Data Analyst

Cell: +38063345 8621 Email: Kateryna_Bobryk@epam.com
Kyiv, Ukraine epam.com

**Comment by jawz101** [comment]
China has the largest population in the world and chooses not to report valid data.

Here is the stereotypical report in any news site- correspondents named Roxanne Liu, Sophie Yu, or Ryan Woo write an article saying 10 tourists brought covid into China yesterday and 4 villagers in a border town with Mongolia got it.

Regardless, the github readme lists

https://3g.dxy.cn/newh5/view/pneumonia
http://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm
http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

 as their data source on China.
