### ISSUE TITLE
Value decrease in cumulative series

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4436]
Hi, 

Could you please check data for Switzerland confirmed death time series where after 07/20/2021 data point values begin to decrease, however series is cumulative and death number cannot decrease:
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

Thank you.

**Comment by CSSEGISandData** [comment]
Please see #4560.
