### ISSUE TITLE
Taiwan is not a member of WHO, and it is not a part of China 💩💩

### ISSUE THREAD

**Issue by fangpenlin** [CSSEGISandData/COVID-19#444]
Taiwan is not a member of WHO, and replying what you said here

https://github.com/CSSEGISandData/COVID-19/issues/404?fbclid=IwAR2WbxsGHY5b6UKy8MIferrAF6CgiwUehQbAIWjazm2nArjSV2b8D8ExkjM#issuecomment-597409148

That org doesn't have any saying to a non-member country, why follow their standard? Please change it, thanks

**Comment by nguyenhychan** [comment]
I am very confused by the name "Taipei and environs" in the time series CSV data as well. Put aside political issues, this kind of naming is very confusing and also affects further analysis of the data.

**Comment by Eclipsed830** [comment]
I do find it a bit strange to follow the naming convention of the WHO in regards to Taiwan at the same time that Taiwan isn't a WHO member. Furthermore, what does "Taipei and environs" even mean? Is that information for the specific city of Taipei? The Taipei metropolitan area or the entire country of Taiwan? This sort of gymnastics takes away from what was once seen as a reputable source and essentially invalidates the entire data-set.

**Comment by CSSEGISandData** [comment]
please see issue #482
