### ISSUE TITLE
Drop in cumulative values in New Zealand: Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4441]
Hi, could you please check time series "New Zealand: Number Of Confirmed Cases" here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

We can see suspicious revision/volatility for 07/23/2021 period (3211) that brings drop in cumulative values in latest release.
Could you please fix it.
Thank you.

**Comment by CSSEGISandData** [comment]
Closed by #4442
