### ISSUE TITLE
Incorrect "new cases" data on July 28th for Germany

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#4451]
Huge difference between the stats for 27th July and 28th July, 2021

 it's 10735  but as per https://www.worldometers.info/coronavirus/country/germany/#graph-cases-daily  and  https://www.who.int/countries/deu/ it's  3059

**Comment by mkhanka** [comment]
Any update on this issue?

**Comment by CSSEGISandData** [comment]
Thank you for bringing this to our attention! This should be corrected with #4535
