### ISSUE TITLE
decrease of daily cases for Germany 2021-07-29

### ISSUE THREAD

**Issue by ZackDev** [CSSEGISandData/COVID-19#4454]
There is a difference of **-4910** daily cases in the data-row for Germany for 2021-07-28 (cases: 3777236) and 2021-07-29 (cases: 3772326)  in the [time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) file.

Probably related to #4451.

**Comment by CSSEGISandData** [comment]
Thanks for identifying this! We've patched with #4535
