### ISSUE TITLE
Wrong numbers

### ISSUE THREAD

**Issue by GauchoPortugues** [CSSEGISandData/COVID-19#4462]
Hello,

I want to inform that I found some wrong numbers for the country Portugal.

Date        new cases
July 28            3452        correct
July 29            0               incorrect, the number must be 3009
July 30            5604        incorrect, the number must be 2595
July 31            0              incorrect, the number must be 2590
August 1        0               incorrect, the number must be 2306

You can verify this with the following sites on internet:

https://covid19.min-saude.pt/wp-content/uploads/2021/07/513_DGS_boletim_20210728.pdf 
https://covid19.min-saude.pt/wp-content/uploads/2021/07/514_DGS_boletim_20210729.pdf 
https://covid19.min-saude.pt/wp-content/uploads/2021/07/515_DGS_boletim_20210730.pdf 
https://covid19.min-saude.pt/wp-content/uploads/2021/07/516_DGS_boletim_20210731.pdf 
https://covid19.min-saude.pt/wp-content/uploads/2021/08/517_DGS_boletim_20210801.pdf

Best regards

**Comment by CSSEGISandData** [comment]
Thank you. These have been adjusted by #4464.
