### ISSUE TITLE
South Korea, no. of cases on 7/27/21 is incorrect

### ISSUE THREAD

**Issue by lux098** [CSSEGISandData/COVID-19#4471]
The number of cases in South Korea for July 27, 2021 is listed as 3,261 cases, which is incorrect.

The official number of cases reported by KDCA (Korea Disease Control and Prevention Agency) on July 27, 2021 is 1,365 cases.

http://www.kdca.go.kr/board/board.es?mid=a30402000000&bid=0030 (Please access the July 27 pdf file with the statistics)

**Comment by CSSEGISandData** [comment]
Thank you. This has been resolved by #4476.
