### ISSUE TITLE
Finnish national data incorrect, not properly sourced

### ISSUE THREAD

**Issue by ThomasHy** [CSSEGISandData/COVID-19#4472]
Finland's daily confirmed Covid cases on Our World in Data repeatedly differ from Finland's official statistics (THL:s and Tartuntatautirekisteri's published numbers [here](https://experience.arcgis.com/experience/d40b2aaf08be4b9c8ec38de30b714f26)). Tried to look into it, but it is impossible to find where exactly Finland's numbers are taken from. It is, however, very easy to look up the official Finnish authorities' numbers (link provided).

This is particularly worth attention as the numbers published on Our World in Data are often tens of percents smaller than the official count (for instance, 26.7. 267 vs 764 cases, 27.7. 616 vs 676 cases, and so on).

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We have updated our source list to indicate that we have been pulling our data from the English language version of the THL dashboard ([linked here](https://experience.arcgis.com/experience/92e9bb33fac744c9a084381fc35aa3c7)). 

By the description in the second half of the issue, it appears that you are comparing the data in our repository with the "Cases by day (by date of specimen collection)" / "Päiväkohtaiset tautitapaukset (näytteenottopäivän mukaan)" graph in the bottom right of the THL dashboard. It is important to clarify that our repository and this graph are not representing the same data and that is the reason that they appear different. 

Our data is and has been organized by date of report, with our daily reports containing snapshots of current reporting around the world and our time series files being appended with those snapshots on a daily basis. As such, each entry represents the total number of cases or deaths that had been reported in that respective location up until that date.

Data organized by date of event (such as the referenced THL dataset) are constantly revised as more data comes in. For instance, the current report for 02.08 is 259 cases and this will certainly change in the next update to the THL dashboard. Our data pipeline (capturing the cumulative case and death data reported on that day) does not have a means of capturing and recording these retrospective changes.

We are not in the practice of revising our files to match date of event datasets as these are irregularly updated, are incomplete for recent dates, and are not accessible in all locations around the world.
