### ISSUE TITLE
Cumulative Cases Decreasing

### ISSUE THREAD

**Issue by NathanDai5287** [CSSEGISandData/COVID-19#4478]
On 8/30/2020, New York, New York (36061) had 233969 confirmed cases, but on 8/31/2020, they had 30874. This is just one example of the total cases decreasing, but it had the largest change of approximately 200,000 cases. How does this happen? 

link to data for 30th
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/08-30-2020.csv

link to data for 31st
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/08-31-2020.csv

**Comment by CSSEGISandData** [comment]
Hello,

As documented in our [README](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#readme), on August 31, 2020 we split New York City up into it's five boroughs (Bronx, Kings, New York, Queens, Richmond). The summation of the five boroughs is equivalent to the past "New York City" entry.
