### ISSUE TITLE
time_series_covid19_recovered_global.csv on 2021-08-06 06:21 UTC corrupted, cumulative recovered all zero for all countries as last datapoint

### ISSUE THREAD

**Issue by KlausGPaul** [CSSEGISandData/COVID-19#4479]
[COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv) conatins zeroes as the last datapoint, example:
```
,Germany,51.165691,10.451526,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,12,12,12,14,14,14,14,
....
3654720,3654950,3658150,3659260,0
```
This is the case for all countries.

**Comment by coder-amey** [comment]
The last entry (as on 6th Aug, 2021) is 0 for all the countries.

**Comment by KlausGPaul** [comment]
@coder-amey just spotted I had the wrong date in the title....

**Comment by CSSEGISandData** [comment]
Please see #4465.

**Comment by KelumPerera** [comment]
Kindly make a suggestion where to refer to get daily recovery data after 04th August?

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

**Comment by KlausGPaul** [comment]
@CSSEGISandData thanks for the pointer, pity these data are no longer available, I was aware these are hard to come by (and they are generally not reported).
Thanks for your fantastic work all that time!
@KelumPerera I am afraid you will need to look for various national sources, oddly enough most countries do not track recovered, only infected and deceased.

**Comment by CSSEGISandData** [comment]
Thank you for your kind words @KlausGPaul. @KelumPerera I would point you to https://www.worldometers.info/coronavirus/ however with the caution that they compute recovered data for locations that are not reporting (e.g., Netherlands, United Kingdom) and will also edit historical data to distribute large spikes in data using their own internal algorithms.

**Comment by coder-amey** [comment]
Thank you for the discussion and the redirect.
