### ISSUE TITLE
data for deaths at 2021/8/5 and 2021/8/6  are zero!!

### ISSUE THREAD

**Issue by mehdihadi** [CSSEGISandData/COVID-19#4485]
Deaths data for all countries in deaths time series at at 2021/8/5 and 2021/8/6 are zero!!!

**Comment by CSSEGISandData** [comment]
Hello,

The recovery and active case fields have been nullified, but the case and death data for August 5, 6, and 7 for the daily reports and time series files have updated correctly. I am unable to locate this issue in the data files so this issue will be closed.
