### ISSUE TITLE
No Recovery data updated in this file after 04th August 

### ISSUE THREAD

**Issue by KelumPerera** [CSSEGISandData/COVID-19#4489]
No Recovery data was updated in this file after 04th August 2021. 
Kindly make a suggestion where to refer to get daily recovery data after 04th August?

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

**Comment by CSSEGISandData** [comment]
Please see #4465.
