### ISSUE TITLE
COVID-2019 recoveries data disposal

### ISSUE THREAD

**Issue by ZOSIMMPNN** [CSSEGISandData/COVID-19#4492]
Global Covid-2019 recoveries data is not not collected and publiished since the August 5th. There are zero values. Is it temporary situation or there won't be new recoveries data any more?

Link is below:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

**Comment by thamarsou** [comment]
Same problem on my side. All countries show 0 recoveries.

**Comment by CSSEGISandData** [comment]
Hello,

Please see #4465.
