### ISSUE TITLE
South Korea became Republic of Korea ? 

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#450]
Hi
Why changing names of country ?

**Comment by hkhc** [comment]
I suppose the official name of the country is Republic of Korea.
https://en.wikipedia.org/wiki/South_Korea

**Comment by JiPiBi** [comment]
For sure , but when a name is changed in certain files (like time series ) on which I made my extractions with a selection of countries , I got an issue . 
Easy to fix , but the daily files remain with South Korea country name , and this is not the only case for the countries' names on this 10th of March : many issues related to that today, without speaking on issues on US numbers perhaps related to the same type of modifications 

In such a database without primary key its a real challenge to make modifications

**Comment by JiPiBi** [comment]
As another issue speaks of the same subject , so I close this one
