### ISSUE TITLE
How to get at daily data now with new weekly format

### ISSUE THREAD

**Issue by mcconnde** [CSSEGISandData/COVID-19#4500]
I have been tracking and modeling the cases since the beginning using the daily cases and deaths.  How can I get at the daily data now?

**Comment by CSSEGISandData** [comment]
Hello,

All of the daily data is still available in this GitHub repository in the [CSSE COVID-19 Data folder](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data). The alteration of the visualization platform does not impact the publicly available data files.
