### ISSUE TITLE
official national data lower than project ones

### ISSUE THREAD

**Issue by Zahra-tn** [CSSEGISandData/COVID-19#4505]
For the case of Tunisia, the official national data especially for deaths are much lower than those published by the project? Do you use official country data please?

**Comment by CSSEGISandData** [comment]
Thank you for your message. This project uses data from the Tunisian Ministry of Health [facebook page](https://www.facebook.com/santetunisie.rns.tn/) and the [WHO COVID-19 Dashboard](https://covid19.who.int/region/emro/country/tn).
