### ISSUE TITLE
New drop in cumulative values, France

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4514]
Hi, could you please check your time series:

1) France: Number Of Confirmed Cases: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

2) France: Number Of Deaths: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

We can see new drop in cumulative values, this time for latest period 08/15/2021.

Could you please advise on this or fix it.

Thank you.

**Comment by CSSEGISandData** [comment]
Closed by #4516
