### ISSUE TITLE
TAIWAN IS NOT PART OF CHINA

### ISSUE THREAD

**Issue by cloudhy417-ntu** [CSSEGISandData/COVID-19#453]
Please don't take Taiwan as part of China. We have our own government. We have our own culture and writing system. We are democracy country and we just finished our presidential election on 11, January, 2020. We have different political parties just like many other  countries. In The Economist 2019, Taiwan had been rated 7.73 in democracy index and the index of China is only 2.26. For anyone who live in country of democracy, they should stand with Taiwan people since we all embrace democracy and freedom and don't like communism. This behavior of merging Taiwan into part of China is encouraging China's behavior of suppressing democracy country. Taiwan have been suppressed in every aspect in the world by China for a long time, since China became stronger in economy and ministry. However, if you believe that democracy is better than communism, or you prefer to live in country of democracy. You should stand with Taiwan people and don't bend to China no matter how much pressure you have from China. Excluding Taiwan as one of the country in the world is a big mistake. Do not take my word, see these 33 report from 23 country. 
🇺🇸美國 #USA
(1)「外交家雜誌」(The Diplomat)：疫情爆發，民主台灣如何勝過獨裁中國 https://bit.ly/2TG1AKJ
(2)「美國之音」(VOA News)：為何當鄰近國家出現千百例確診，台灣仍僅40餘例 https://bit.ly/2v6U6GT
(3)「美洲日報」(Diario las Americas)：台灣緊鄰中國卻成為防疫典範 https://bit.ly/39zdCLc
🇨🇦加拿大 #Canada ─「Fodor’s Travel」網站：台灣的防疫水準是另一個層次 https://bit.ly/38D2efS
🇩🇪德國 #Germany
(1)「每日鏡報」(Der Tagesspiegel)：台灣已成功研發出快篩新冠病毒的檢測法 https://bit.ly/33ckLik
(2)「焦點雜誌」(FOCUS)：台灣對抗新冠病毒的成就被WHO忽視 https://bit.ly/2TYrhoK
🇬🇧英國 #UK
(1)「衛報」(The Guardian)：台灣似乎已完全掌控疫情，現在我開始擔心回英國了 https://bit.ly/2v4HVua
(2) 「愛丁堡記者報」(The Edinburgh Reporter)：旅遊在疫情蔓延時，看看台灣的防疫經驗 https://bit.ly/39CVa4z
(3)「每日電訊報」(The Telegraph)：台灣黃金防疫標準有效控制確診人數 https://bit.ly/2vRZe23
🇫🇷法國 #France
(1)「世界報」(Le Monde)：台灣致力成為對抗新冠病毒的榜樣 https://bit.ly/38BITfa
(2) 「十字架報」(La Croix)：台灣因應疫情堪為典範 https://bit.ly/38BjZML
(3)「解放報」(Libération)：台灣憑一己之力成為防疫模範 https://bit.ly/2vJwkBl
(4)「TourMaG.com」觀光新聞網：新冠病毒全球蔓延，在臺灣受到適當控制 https://bit.ly/38C0pjt

🇨🇭瑞士 #Switzerland ─「撇報」(Blick)： 台灣有效防堵疫情爆發 https://is.gd/iNxZHr
🇨🇿捷克 #CzechRepublic ─「捷克電視台」(Česká televize)：台灣位處病毒高風險地帶，卻成功防堵疫情 https://bit.ly/2IxEFux
🇮🇹義大利 #Italy ─「Formiche」雜誌：台灣以不限制公民自由的方式有效防疫 https://bit.ly/3cMRizV
🇪🇸西班牙 #Spain
(1)「ABC日報」(abc)：台灣防疫措施有效抑制疫情 https://bit.ly/339MnEz
(2)「20分鐘報」(20 minutos)：台灣保護學童避免感染病毒措施亮眼 https://bit.ly/3aEL9Uq
🇵🇱波蘭 #Poland ─「選舉報」(Gazeta Wyborcza)：看看台灣如何因應新冠病毒疫情 https://bit.ly/2Q0oCJW
🇧🇦波赫 #BosniaAndHerzegovina ─「Klix」新聞網：雖位於新冠病毒重災區，台灣的感染率最低 https://bit.ly/2VXkjme
🇳🇱荷蘭 #Netherlands ─「荷蘭日報」(Nederlands Dagblad)：臺灣SARS的寶貴經驗有效因應新冠防疫 https://bit.ly/2Q3WCVw
🇳🇿紐西蘭 #NewZealand ─「紐西蘭廣播電台」(Radio New Zealand)：紐西蘭衛長肯定台灣檢疫及自主隔離防疫的優異成果 https://bit.ly/3cLtMmM

🇯🇵日本 #Japan
(1)「朝日新聞」：台灣天才政委運用IT避免口罩供需混亂 https://bit.ly/2W5PGuS
(2)「東洋經濟新報社」：應效法台灣目前的口罩政策 https://bit.ly/3cUMQPE
🇰🇷韓國 #Korea
(1)「韓聯社」(뉴스 홈페이지)：台灣提前一個月實施口罩限售政策 https://bit.ly/2TDa2tY
(2)「每日報」(Korean Daily)：台灣公私部門合作導入IT口罩政策 https://bit.ly/2TAF0ms
🇹🇭泰國 #Thailand ─「Workpoint News」新聞網：台灣唐鳳數位政委運用IT防疫 https://bit.ly/3aI1SWQ
🇮🇩印尼 #Indonesia ─「Kabar24」電台：台灣防疫措施可讓其他國家借鏡 https://bit.ly/332tTWH
🇮🇳印度 #India ─ 「News Vibes of India」新聞網：僅40餘例確診，台灣如何抑制疫情 https://bit.ly/2Q67Jxl
🇱🇨聖露西亞 #StLucia ─「星報」(The Star)：我們應全面學習台灣的防疫經驗 https://bit.ly/3aLuf6J
🇨🇱智利 #Chile ─「第三日報」(La Tercera) ：台灣致力成為防疫楷模 https://bit.ly/2Q3nHbz
🇹🇷土耳其 #Turkey ─「郵報」(POSTA)：台灣在新冠疫情中如何成功因應 https://bit.ly/2IOlc9f
🇶🇦卡達 #Qatar ─「半島電視台」(Al Jazeera)：如何控制疫情傳播：學習台灣的經驗 https://bit.ly/2VYdfG5
🇿🇦南非 #SouthAfrica ─「Getaway」旅遊雜誌：台灣政府積極保護民眾與遊客健康 https://bit.ly/2W

TAIWAN CAN HELP

**Comment by CSSEGISandData** [comment]
please see issue #482
