### ISSUE TITLE
Empty recovered data in Poland

### ISSUE THREAD

**Issue by Flower7C3** [CSSEGISandData/COVID-19#4533]
There are empty recovered values for Poland since 2021-08-05

https://github.com/CSSEGISandData/COVID-19/blob/51dda4a10338522b787095bc8d5e2d7da71d50c7/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv#L200

**Comment by CSSEGISandData** [comment]
Please see #4465.
