### ISSUE TITLE
28-Day Vaccine Doses Administered >> Total Vaccine Doses Administered 

### ISSUE THREAD

**Issue by Stanislas-Kazla** [CSSEGISandData/COVID-19#4540]
The 28-Day Vaccine Doses Administered is greater than Total Vaccine Doses Administered 

**Version observed** : 22/08/2021, 13:21
**Way to reproduced**: Open the dashboard - https://gisanddata.maps.arcgis.com/apps/dashboards/bda7594740fd40299423467b48e9ecf6
no filter
**Workaround**: Cumul value of charts (seems acceptable (2.4Mds) from 18-Jul to 15-Aug))
**Result observed**: 28-Day Vaccine Doses Administered : 109 344 525 102 (109Mds) / Total Vaccine Doses Administrated 4 917 851 374
**Result desired** : 28-Day Vaccine Doses Administered : 2.4Mds (same as value in the charts

**Comment by CSSEGISandData** [comment]
Thank you for posting. We are addressing.

**Comment by CSSEGISandData** [comment]
Resolved in #4544.
