### ISSUE TITLE
COVID-19 Dashboard Daily doses administered graph

### ISSUE THREAD

**Issue by Greensnowrock** [CSSEGISandData/COVID-19#4543]
![daily dose graph](https://user-images.githubusercontent.com/89350093/130361064-2effcf7c-e22e-45e8-bdaf-2af7ff7f7fac.JPG)
the vertical axis has wrong units

**Comment by CSSEGISandData** [comment]
#4541

**Comment by CSSEGISandData** [comment]
Resolved in #4544.
