### ISSUE TITLE
28-Day Data Issue resolved

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#4544]
We have patched the error that was resulting in the 28-day data being duplicated and the dashboard is now displaying the correct data. Thank you all for your patience.

**Comment by benni-r1** [comment]
the daily cases of germany and United kingdom look correct too now .

**Comment by ron442** [comment]
I'm still having issues.  I'm in Australia (UTC+10) and in the evening (when the day here is the same as the day in the US), the number of cases for countries like the US seem way too big.
