### ISSUE TITLE
Revision for Switzerland: Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4556]
Hi, could you please check your time series "Switzerland: Number Of Deaths".
We've got today suspicious revision of whole backhistory that contains drops in cumulative values (e.g. 08/16/2021, 08/19/2021 periods).
Could you please advise on this and fix it asap.
Thank you.

#CHE.DEATHS.COVID19.D@JHU

**Comment by DataOps-epam** [comment]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

**Comment by CSSEGISandData** [comment]
Please see #4560.
