### ISSUE TITLE
Taiwan and Hong Kong are not a province under China

### ISSUE THREAD

**Issue by Charles-Ngg** [CSSEGISandData/COVID-19#458]

**Comment by callmejon** [comment]
PRC china government block user access www.github.com behind great firewall

taiwan government do not block www.github.com

**Comment by ladris** [comment]
People opening 70+ "Issues" to espouse geopolitical drama and rhetoric aren't helping. It's turning half the issue board into a propaganda protest and it's despicable. There is a time and a place, if you have an issue with it, protest the organization that set the breakdown standard.

**Comment by Bost** [comment]
> PRC china government block user access [www.github.com](http://www.github.com) behind great firewall

Tangentially relevant https://github.com/CSSEGISandData/COVID-19/issues/307#issuecomment-596193367
