### ISSUE TITLE
Upcoming France spike in deaths August 17th due to republication of deaths in nursing homes

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#4588]
Hello all,

On August 17th, 2021, the government of France reintroduced a metric that had been stale since February 19, 2021 - deaths in nursing and care homes (EHPAD). The total number of EHPAD deaths reported on that day had been 24,480, a number which we had carried forward as a constant being added to the number of deaths being reported as having occurred in hospitals. On August 17th, deaths in EHPAD were reintroduced, beginning with a total of 37,815 (an increase of 13,335 deaths). At present, there is no back distribution of these deaths available so we will have to include these as a spike to the overall dataset. We will be back distributing deaths from August 17th on to include these newly identified EHPAD deaths.

A visualization of the gap in the availability of this data is available in the curve of cumulative COVID-19 deaths in EHPAD on [this France government dashboard](https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA) (which has been deprecated). An image from this curve is below.
<img width="541" alt="France EHPAD deaths" src="https://user-images.githubusercontent.com/60674295/131743874-35394ec5-72ab-4ef0-99dc-c53fc7a0c3df.png">

**Comment by edomt** [comment]
Hi @CSSEGISandData !

It seems this has been (accidentally?) rolled back today?

![coronavirus-data-explorer(75)](https://user-images.githubusercontent.com/7103774/131962204-042ec305-64e6-4798-894a-7decbc9cd19d.png)

**Comment by CSSEGISandData** [comment]
Hi @edomt,

It appears that the France government has reduced their numbers by ~10,000 deaths in EHPAD. We are working a fix. Thank you for your patience.

**Comment by CSSEGISandData** [comment]
#4605 revises the death data to again match that of the French government.
