### ISSUE TITLE
Taiwan people:  please stop trying to destroy this resource

### ISSUE THREAD

**Issue by zawy12** [CSSEGISandData/COVID-19#459]
Please stop spamming this resource. A lot of people need this data and need to discuss the medical situation, not politics.  Hopefully he will correct the error.   Are these bots from the Taiwan government?  I see the same title and from Github accounts just opened.

**Comment by hkhc** [comment]
So given the different situations of HK, Macau, Taiwan and China, why are these data merged?

**Comment by zawy12** [comment]
Hopefully it is because he is ignorant of the politics instead of favoring or bowing to pressure like governments and companies.

**Comment by tycheng-sunny** [comment]
Perhaps they should not have spent their time on changing "Taiwan" to "Taipei and evirons", or they spent a few mins to change it back, then they won't have this "spam".

**Comment by zawy12** [comment]
In other words, you want to make people angry so they start saying you are part of China?

**Comment by a2d8a4v** [comment]
Hello @zawy12, I think this not just a political concern, one more important is that although the confirmed case in Taiwan is not so much as other country, and maybe is merged not influence the whole number, but in fact Taiwan really take action quickly in compare with other countries in the world, it would be more a good way to separate Taiwan from China.

**Comment by tycheng-sunny** [comment]
> In other words, you want to make people angry so they start saying you are part of China?

Obviously, no need for angry people, this website has done this misunderstanding and shown it to the world. What if the website made a mistake and put the Ireland as a part of UK? I bet you will change it back immediately. 

First, this website should not have changed it in the first place. Second, just change it back, then you solve these "spams". Even though it is not spam, we are reporting a serious mistake shown on the website. 

The Johns Hopkins University is an honourable university, and I really appreciate people's effort on building this website which benefits the world in this tough period. I really hope authors can make an educational judgement on this issue.

**Comment by zawy12** [comment]
I think it is important to find out why it was changed.  But for every down vote I get on my initial post above, my friendship with Taiwan decreases.

**Comment by takua624** [comment]
@zawy12 Actually, except for the mis-labeling of Taiwan (and some regions the communist china doesn't want listed as a country/region), there's nothing wrong with the map, you can still get the information you wanted, why are you so irritated?

Do you know Taiwan was still listed in the "country/region" tab just yesterday? So obviously it's the maintainer of this map who changed the label that brings politic to science. You should complain to that guy, not to us who just react to his/her misbehavior.

**Comment by Eclipsed830** [comment]
I am an American too, and we as Americans should be outraged that an American institution of higher learning would take the political position of the Chinese Communist Party and not that of our own US government. It is a verifiable fact that the PRC government and/or the Chinese Communist Party does not have any effective jurisdiction or authority over Taiwan, it's government or it's people. This sort of misinformation (propaganda?) leads to misrepresented data and can literally hurt Taiwan's economy. As Americans, we need to stand up with our democratic allies like Taiwan and ensure the 23 million people of Taiwan have the right to self-determination.

**Comment by takua624** [comment]
> I am an American too, and we as Americans should be outraged that an American institution of higher learning would take the political position of the Chinese Communist Party and not that of our own US government. It is a verifiable fact that the PRC government and/or the Chinese Communist Party does not have any effective jurisdiction or authority over Taiwan, it's government or it's people. This sort of misinformation (propaganda?) leads to misrepresented data and can literally hurt Taiwan's economy. As Americans, we need to stand up with our democratic allies like Taiwan and ensure the 23 million people of Taiwan have the right to self-determination.

I greatly appreciate your support!

**Comment by zawy12** [comment]
I am complaining about people from Taiwan acting like they are from Taipei by trying to make the issues part of this Github unusable. The appropriate target is Johns Hopkins, maybe by contacting students there.  1 reminder every 3 issues would be sufficient.

**Comment by zawy12** [comment]
I see H.K and Taiwan are not listed in their country/region
https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by Eclipsed830** [comment]
>I am complaining about people from Taiwan acting like they are from Taipei by trying to make the issues part of this Github unusable. The appropriate target is Johns Hopkins, maybe by contacting students there. 1 reminder every 3 issues would be sufficient.

While I agree with you that this issue might have been better solved in a single thread, we should not downplay the importance of getting this issue corrected. At this point, [it's made Reuters](https://www.reuters.com/article/us-health-coronavirus-taiwan-university/taiwan-protests-as-top-u-s-university-labels-island-part-of-china-on-virus-map-idUSKBN20Y0NK) and I'm sure it'll be an international story by noon California time.

**Comment by zawy12** [comment]
That's great news.

**Comment by Eclipsed830** [comment]
> I see H.K and Taiwan are not listed in their list of countries/regions. And "Taiwan" is not on the map anymore but Taipai.
> https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

What do you mean? I don't see Taiwan period. I just see "Taipei and environs, China" under China... it is not visible unless I click "China" under Country/Region:

![taipei](https://user-images.githubusercontent.com/6769384/76414935-39f79e80-63d3-11ea-8907-03969f754961.gif)

**Comment by takua624** [comment]
> I see H.K and Taiwan are not listed in their list of countries/regions. And "Taiwan" is not on the map anymore but Taipai.
> https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

We already emailed the person in charge, Dr. Lauren Gardner, before leaving comments here.

A journalist also contacted Dr. Gardner while Taiwan was still in the Country/Regions tab but changed into "Taipei and environs". According to the journalist, Dr. Gardner said they had already caught it & would change back to "Taiwan" immediately. But this is what we got, an even worse version.
https://twitter.com/BethanyAllenEbr/status/1237565381788569603

The easiest way to "fix" this problem is to label the country/regions as they were prior to yesterday.

Imagine the US got labelled as "US, UK", you might not be very happy about that.

**Comment by zawy12** [comment]
I'm looking at the country list, not the breakdown. (no listing of Taiwan or HK.  And the map lists "Japan" and "Phillipines" but nothing over Taiwan.

**Comment by designbyadrian** [comment]
This ticket should solve the issue:

https://github.com/CSSEGISandData/COVID-19/issues/470

By only referring to country code, each data consumer can use any ISO code converter they wish.

Now stop talking shit about Taiwan people. Country name and location is an incredibly sensitive issue to not only them, but many others.

**Comment by zawy12** [comment]
Never mind now I see it.  I think they might have just added it back.

**Comment by Eclipsed830** [comment]
> I see H.K and Taiwan are not listed in their list of countries/regions. And "Taiwan" is not on the map anymore but Taipai.
> https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Just caught your edit.

Yes and that's the problem. Taiwan is the country and Taipei is only a small city. By landmass, Taipei itself is only 104 square miles compared to the entire island which is 14,000 square miles. Furthermore, most of the cases were initially in the southern Taiwan, a 4 hour drive away.

From a governance standpoint, the Chinese government has literally zero authority over the Taiwanese people. Taiwan has never been part of the People's Republic of China (China) or been under control of the Chinese Communist Party.

**Comment by CSSEGISandData** [comment]
please see issue #482

**Comment by eacvo67347** [comment]
> Never mind now I see it. I think they might have just added it back.

Taiwan's country name is called "Other". Do you get it now? 


49 Philippines
**48 Other**
35 Vietnam



China is trying to take Taiwan off the world map, like they did in the United Nations. 
**Taiwan was a founding member of the UN, and now they are not even part of it.**

I'm trying to be civil here, but these are points of principle, and principles must be firm. When the boundaries are blurred and we let it happen, we are in fact enabling it.
