### ISSUE TITLE
Positivity rate Washington

### ISSUE THREAD

**Issue by cestigarribia-dtt** [CSSEGISandData/COVID-19#4592]
Hi everyone,

Some counties in the state of Washington have been reporting an incredible high positivity rate in the last few days. 

¿Does anyone know why this might be happening?

**Comment by CSSEGISandData** [comment]
Hello,

Please see this notice on the [Washington COVID-19 dashboard](https://www.doh.wa.gov/Emergencies/COVID19/DataDashboard):

"Negative test results data from Aug 20, 2021 to today are incomplete, impacting the reporting of negative test results, “testing rate” and “percent positive” metrics, displayed on the Testing tab. "
