### ISSUE TITLE
September 2 confirmed cases and deaths data for Turkey are the same as September 1 data

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#4602]
There is an irregularity in Turkey's September 2 confirmed cases and deaths data as they are the same as September 1 data. https://covid19.saglik.gov.tr/EN-69532/general-coronavirus-table.html has the incremental data for September 2, though.

**Comment by tllkrmn** [comment]
Irregularity is also observed for September 3 confirmed cases and deaths data.

**Comment by Khairil82** [comment]
[Khairil](khairilisharimysewan@gmail.com) [Eeee](khairilisharimysewan@gmail.com)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We have been unable to update our data for Turkey as the website for the [Ministry of Health](https://covid19.saglik.gov.tr/EN-69532/general-coronavirus-table.html) is currently inaccessible.

**Comment by greg-minshall** [comment]
hi.  i don't know what the page used to look like.  but, if it looked like the following (but, maybe with English column names?), maybe this is where to look?

https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html

**Comment by greg-minshall** [comment]
also, maybe omit Turkey until it recovers?  the daily .csv files *seem* to be claiming to have accessed Turkey's numbers on successive days.  i suppose, also, you could provide the numbers, with the date of the last successful access?  cheers.

**Comment by CSSEGISandData** [comment]
Thanks. We patched the stale data with #4617.
