### ISSUE TITLE
Taiwan mislabeled as a part of china

### ISSUE THREAD

**Issue by takua624** [CSSEGISandData/COVID-19#461]
Hi, I found a bug in the system. When the system was established, Taiwan was labeled as "Taiwan" in the Country/Region tab, but now it becomes "Taipei and environs, china" in the St/Prov tab.

Everyone in the world except for those under the influence of the communist china knows Taiwan is a country distinct from china, your map shouldn't convey false information.

I believe this is a bug either in the codes or in your team, please fix it as soon as possible.

I understand there are much more important things to do than for Taiwanese to "spam" your system, but that should also be true for the maintainer of this system: there are much more important things to do than to surreptitiously tweak the labels to align with the maintainer's political inclination.

Thank you.

**Comment by ladris** [comment]
People opening 70+ "Issues" to espouse geopolitical drama and rhetoric aren't helping. It's turning half the issue board into a propaganda protest and it's despicable. There is a time and a place, if you have an issue with it, protest the organization that set the breakdown standard.

**Comment by takua624** [comment]
what about this tracing map not engaging in geopolitical drama in the first place?

Taiwan has been in the Country/Region map for more than a month, and we didn't see chinese complaining about it, and everything went well until for some reason, the curator of this map decided to bring geopolitical drama into this map just yesterday.

You are more than welcome to think of some means to help restore the labeling of the map to the way it was prior to yesterday.

**Comment by paulyehtw** [comment]
Hey, why on the earth you think Taiwan is a part of China? I suggest you to read some history and you will realize you are being ignorant

**Comment by B03901108** [comment]
Dear @ladris 
Since you just keep copying and pasting the same nonsense, I think it's wise to consider you a communist robot :)
