### ISSUE TITLE
Decrease of cumulative cases for Germany 2021-09-05

### ISSUE THREAD

**Issue by ZackDev** [CSSEGISandData/COVID-19#4612]
Hi,

there is a decrease of **-1050** cases from 2021-09-04 (cases: 4014858) to 2021-09-05 (cases: 4013808) in the [time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) file.

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this discrepancy. We have corrected our data to align with the source. See commit: cd117bb

**Comment by ZackDev** [comment]
Thanks for the update!
