### ISSUE TITLE
Data on JHU is updating one day prior to WHO for Portugal on 3rd and 4th September 

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#4615]
It looks like the new daily cases of  Portugal for 3rd and 4th September showing incorrect data. 

For September 3 and 4 “new daily cases” are zero and 3535 respectively.

However, on external sources available stats are different. 

[Worldometers](https://www.worldometers.info/coronavirus/country/portugal/): Daily cases for 3rd September is 1822 and for 4th September it is : 1713

[WHO](https://covid19.who.int/region/euro/country/pt): Daily increase for 4th is 1822 and for 5th September is 1713.

I have observed that the data on JHU is updating one day prior to WHO. 

Please look into this and let me know whether the stats for the mentioned dates are expected or not.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We have patched the data for Portugal for September 3 in #4623. Our data is based on the date in which the data was reported in EST. We cannot comment on how WHO reports dates for their data.
