### ISSUE TITLE
Data mismatch for AFGHANISTAN in GITHUB feed and WHO on 4th and 5th Sept.

### ISSUE THREAD

**Issue by Saurabh0027** [CSSEGISandData/COVID-19#4627]
It looks like the new daily cases of Afghanistan for 4th  and 5th  September showing incorrect data.

For September 4 and 5 “new daily cases” are zero and Zero respectively.

However, on external sources (WHO) available stats are different.

On Comparing the data of Github and WHO , we found that the new daily cases except from September 4th- 6th are the same. However, no new case reported on Github for 4th and 5th September. Also, new daily cases for 6th September is the sum of new daily cases on WHO from Sep 4-6 (20+28+111= 159).

Please check and update.

**Comment by Khairil82** [comment]
Khairil027
###

**Comment by CSSEGISandData** [comment]
Addressed by #4642.
