### ISSUE TITLE
Daily cases for Libya is not being updated on regular basis, stats are from one day past

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#4632]
Confirmed cases for 13th August and 14th August are same, that is why the new daily cases are coming out to be zero for 14th August.

However, on external sources Worldometer and WHO, the available data is different.
- Worldometer: Daily cases for 14th August is same as in Github file.
- WHO: Daily cases for 14th August is 2360 and for 15th August is 0.
- The data on Worldometer and Github update one day prior to WHO

Please look into this and let me know whether the stats for the mentioned dates are expected or not.

**Comment by CSSEGISandData** [comment]
Hello,

The responses to #4613 and #4615 will provide clarity on this issue. The dates in our GitHub repository reflect the date in EST that that data was captured on the source.
