### ISSUE TITLE
South Korea 2021-09-03 new case/death issue

### ISSUE THREAD

**Issue by WWolf** [CSSEGISandData/COVID-19#4637]
KOR total case number and deaths are wrong, possibly due to glitch in retrieving the statistics from the official site.

See the archived website (Korean) with case and death numbers: https://web.archive.org/web/20210903091137/http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=11&ncvContSeq=&contSeq=&board_id=&gubun=

Cumulative case numbers on 2021-09-03 (00:00) should be 257,110. Death is 2,308.

However, https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/09-03-2021.csv file states:

258,913 and 2,315 for cumulative case and deaths respectively.

Which is the same as reported on 2021-09-04.

So it looks like the 2021-09-03 record was retrieved too late and took the next day's data creating a glitch.

**Comment by CSSEGISandData** [comment]
Thank you. This was patched with #4649.
