### ISSUE TITLE
What is Costa Rica's data origin?

### ISSUE THREAD

**Issue by zkwinkle** [CSSEGISandData/COVID-19#4650]
I have a little personal project where I keep track of the active cases in my country, Costa Rica. The discontinuation of recovered data has ruined it so I'm looking for a new API I may use to maintain it. I thought I'd use whatever is used a source by this project, but I can't find a source listed for my country in the README. Also I know it's not worldometer because their data doesn't match what our country reports like yours does.

Thank you in advance for the help, it'll be greatly appreciated.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. Our source is Worldometer. We cannot comment on their historical data.
