### ISSUE TITLE
Discrepancy in Germany nation wide cumulative vs. Germany state wise cases: sept 3rd  

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#4673]
Cumulative count for Germany showing 2899 reported cases as per time_series_covid19_confirmed_global.csv

But if we look at state wise count for Germany (csse_covid_19_daily_reports/09-03-2021.csv - csse_covid_19_daily_reports/09-02-2021.csv), number goes higher on sept 3rd . 

I observed that the  discrepancy in total count is due to the fact that the data for Unknown, Germany decrease by -7918 due to which the cumulative count for Germany is coming to   2899, even if the count of other states is 10817

While verifying the data from other sources:

[Wordometers](https://www.worldometers.info/coronavirus/country/germany/#graph-cases-daily) shows new cases in Germany for 3rd Sep, 2021 to be 12633
[CoronaTracker](https://www.coronatracker.com/country/germany/) shows new cases in Germany for 3rd Sep, 2021 to be 12633

Please have a look at the above data and if the discrepancy can be resolved?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. This has been addressed before in #3417. It's related to our source, the [Berliner Morgenpost](https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/), combining multiple sources to report national and state level case totals. The day-on-day changes in nationwide cases and deaths will differ for this reason.
