### ISSUE TITLE
Singapore data for 20 Sep 2021

### ISSUE THREAD

**Issue by sentri1129** [CSSEGISandData/COVID-19#4687]
Hi, the number of confirmed cases for Singapore 20 Sep 2021 was not updated:

Current data:
19 Sep = 77804
20 Sep = 77804
21 Sep = 79899

Should be:
19 Sep = 77804
**20 Sep = 78721**
21 Sep = 79899

**Comment by CSSEGISandData** [comment]
Thank you. This was patched in #4696.
