### ISSUE TITLE
Dewitt, TX new cases

### ISSUE THREAD

**Issue by cestigarribia-dtt** [CSSEGISandData/COVID-19#4701]
Hello all, Dewitt, TX has reported 199 new confirmed cases after having reported 0 cases for almost a month. 
Is this a backlog for the whole month?

**Comment by CSSEGISandData** [comment]
Hello,

At the moment, there is no indication in the [data notes page](https://dshs.texas.gov/coronavirus/datanotes.aspx) of the [Texas dashboard](https://dshs.texas.gov/coronavirus/AdditionalData.aspx) that these were all backlogged cases. The increase in cases is also reflected in the state's [time series file for new confirmed cases](https://dshs.texas.gov/coronavirus/TexasCOVID-19NewCasesOverTimebyCounty.xlsx). We will continue to investigate.

**Comment by CSSEGISandData** [comment]
Hello,

There is another large increase of cases for October 4 that is again not included in the [state data notes](https://dshs.texas.gov/coronavirus/datanotes.aspx). From previous correspondence with the state, whether or not cases are "older" (14 or more days from specimen collection date) is ultimately determined by the metadata associated with the cases submitted by the county. As such, at the moment we have no indication that these cases are "older" but the information received by the state indicates that they are not.
