### ISSUE TITLE
Sept 29 Confirmed Cases and Deaths Data for Turkey Not Updated

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#4708]
Confirmed cases and deaths data for Turkey for Sept 29 repeat the data of Sept 28. https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html (in Turkish) publishes the daily increment data for confirmed cases under column (Bugünkü Vaka Sayısı) and deaths under column (Bugünkü Vefat Sayısı).

**Comment by CSSEGISandData** [comment]
Thank you. This has been addressed in #4721.
