### ISSUE TITLE
Israel number of daily deaths update

### ISSUE THREAD

**Issue by eseses1976** [CSSEGISandData/COVID-19#4717]
Dear all

When I compared daily deaths data from OWID versus daily deaths  data from IL MOH it seems like something has been changed (around end of 2020) in the way history is updated.

you can see in the graph the different behavior before the Yellow arrow and after it

If I have to guess I would say that in the past the data used to update retroactively the number of deaths by the original death date like IL MOH is doing (cause sometime deaths are reported only few days after the original death date) and in some point (around end of 2020) you stopped updating retroactively,  and when there is an update in IL MOH data that is related to more than 1 day in the past it all added to the last day number of deaths.

are you familiar with this phenomenon? 

Can you confirm if I'm guessing correct?

If it's correct, do you know when exactly the change took place (on what date)?

Will appreciate very much any comment, 

 Thanks a lot in advanced

![image](https://user-images.githubusercontent.com/91841797/135763301-b67c8cc6-5a12-47f6-9ffd-e9757b051a27.png)

**Comment by CSSEGISandData** [comment]
Thank you for raising this issue. This is similar to #4613 and I would recommend reviewing the response there.

We have updated retroactively. The Israel Ministry of Health altered their posture to update multiple times per day, but at nonstandard and nonregular times. As such, on some days our snapshots contain four updates or two updates. This is responsible for the high heterogeneity seen in the graph posted. Prior to the "yellow arrow", the Israeli MOH was only updating once per day and all data was caught in a cycle update cycle on our GitHub repository.

Please let us know any further questions.

**Comment by eseses1976** [comment]
Thank for your quick response.

I'm not sure to fully understand you...

You mentioned that you do update retroactively the data, so why isn't it match MOH data after the update for the all period except the last day  ?

I understood the timing issue of capturing the data (that in some days you might get 2 updates and in the other 4) but shouldn't be fixed the next day if you are updating it retroactively ?

On top of it, I think that the misalignment in the timing of the updates mentioned (2 or 4 updated instead of 3) wouldn't end up in such a misalignment as we can see in the 4'th wave. In order to make it more visual, I've created the same graph but this time I used moving average of the last 4 days. you can see the difference between waves 1+2 (no misalignments), wave 3(when misalignments started) and wave 4 (where misalignment is much higher). if the reason for that was only 2/4 updates instead of 2, I would accept to see that in the 4'th wave the misalignments will be me much less than in wave 3 cause the number of daily deaths in wave 4 is much lower than the number of deaths in wave 3
Thanks again for your feedback, it's really important for me to understand it

![image](https://user-images.githubusercontent.com/91841797/135978928-8819e7c8-dbc1-4aa7-b0ed-d39e019f7787.png)
