### ISSUE TITLE
Taiwan is a COUNTRY. Taiwan is not a province under China

### ISSUE THREAD

**Issue by Taiwannoone** [CSSEGISandData/COVID-19#474]
Taiwan is not a province under China!!

**Comment by Aragorn222** [comment]
？？？

**Comment by jackychentrinetx** [comment]
Taiwan should be a separated country/region out side of China

**Comment by JiPiBi** [comment]
Where is aggreagtion made , by the way not in csv data ?

**Comment by leafwind** [comment]
> Where is aggregation supposed to be made , by the way not in csv data ?

I have not check the logic in website, but I think it is aggregated by the country name in the csv

**Comment by ladris** [comment]
> Taiwan is not a province under China!!

People opening 70+ "Issues" to espouse geopolitical drama and rhetoric aren't helping. It's turning half the issue board into a propaganda protest and it's despicable. There is a time and a place, if you have an issue with it, protest the organization that set the breakdown standard.

**Comment by JiPiBi** [comment]
@leafwind  I repeat that in the csv files in this repo , these states (Taiwan, Macau, Hong Kong) are not agregated with Mainland China but as separate states

**Comment by paulyehtw** [comment]
Hey, why on the earth you think Taiwan is a part of China? I suggest you to read some history and you will realize you are being ignorant

**Comment by yhtaitaiwan** [comment]
Taiwan is Taiwan, no more explanation!

**Comment by Ajexsen** [comment]
For people who are having a hard time to understand this bug, here is a thorough tutorial.
https://youtu.be/T2hTQtl4nwg

**Comment by CorwinOA** [comment]
See Issue #504

**Comment by B03901108** [comment]
@ladris No, you are wrong. Protest the authors because they trust the flawed breakdown standard. During peer review, reviewers blame authors for an inappropriate reference but not the reference itself.
