### ISSUE TITLE
Malaysia deaths based on date reported vs date of death

### ISSUE THREAD

**Issue by UserFiftyOne** [CSSEGISandData/COVID-19#4774]
Hi all, Malaysia said that they have a backlog of deaths and started releasing death data based on both date reported and date of death ([source](https://www.reuters.com/world/asia-pacific/malaysia-posts-record-monthly-covid-19-deaths-authorities-cite-backlog-2021-10-01/)). This is the documentation on https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic#deaths:
> `deaths_new`: deaths due to COVID-19 based on **date reported to public**
> `deaths_new_dod`: deaths due to COVID-19 based on **date of death**

Which stat does JHU use and will this change in the future?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We use date of report for all locations except for the US state of Ohio (the reason for the exception is detailed in #3757).
