### ISSUE TITLE
error in Slovenia death time series 

### ISSUE THREAD

**Issue by majazaloznik** [CSSEGISandData/COVID-19#4775]
There is an error in the 2010-10-06 time point of the cumulative deaths series for Slovenia in `COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv`. The value 4899 is wrong and should be 4597 instead. 

I am writing from [sledilnik.org](https://covid-19.sledilnik.org/) - we are the listed source of this data, but this data point did not come from us. The correct variable is `state.deceased.todate` from  [this file](https://github.com/sledilnik/data/blob/master/csv/stats.csv). 

Not sure how this happened, but testing to ensure the cumulative values are always strictly increasing would have flagged this earlier.

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this issue. We have patched our data accordingly.
