### ISSUE TITLE
Data error in 02-13-2020_2115.csv

### ISSUE THREAD

**Issue by dawenx** [CSSEGISandData/COVID-19#48]
See below screenshot, for Hubei, **the number for Deaths and Recovered are wrong**.

![Screenshot_2020-02-14 CSSEGISandData COVID-19](https://user-images.githubusercontent.com/26723038/74529910-d58e1000-4ef6-11ea-9ef2-01afeb9fece2.png)

See below for screenshot from qq.com at 6:51AM EDT 02-14-2020.

![Screenshot_2020-02-14 实时更新：新冠肺炎疫情最新动态](https://user-images.githubusercontent.com/26723038/74529944-e8a0e000-4ef6-11ea-9c80-bcd54cc06c69.png)

See below for screenshot from DXY at 6:56AM EDT 02-14-2020.

![Screenshot_2020-02-14 全国新冠肺炎疫情实时动态 - 丁香园·丁香医生](https://user-images.githubusercontent.com/26723038/74530066-2f8ed580-4ef7-11ea-8c6d-d5bf84ed96d8.png)

**Comment by avatorl** [comment]
They just included regular daily update +116 and -108 update* in 2 different CSV files I think. It ws reported in different time (a few hours difference) by China I think.

_*China reported -108 cases - "deducted 108 prior deaths from the death toll due to double counting" (c)_

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. This repo is updated daily around 12 AM UTC. There may be discrepancies  from the data in this repo and the data reported from DXY due to the timing of this repos update. The Dashboard will always be reporting in real-time.
