### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#482]
We are working to reconsider naming convention of countries. Sorry for the inconvenience and thank you for your patience through these transitions.

**Comment by cwacht** [comment]
Thank you for the update!

**Comment by StateCenterKid** [comment]
Please consider keeping the naming conventions of March 9th and making the modifications in a separate file. This will give users time to transition to the new formats.


 Your work is greatly appreciated and the daily releases work great for the intended use of this data.

**Comment by jimmychang851129** [comment]
Many thanks !
It really means a lot to us that Taiwan is not part of China.

**Comment by SeanHung06** [comment]
Many Thanks!

**Comment by scottmcdaniel** [comment]
For reference: https://github.com/CSSEGISandData/COVID-19/issues/415

**Comment by memochou1993** [comment]
Taiwan is Not a part of China. Thank you for your reconsideration.

**Comment by Miserlou** [comment]
Although the team here is claiming they are "working to reconsider", the University is telling journalists that it will not be changed back: https://twitter.com/BethanyAllenEbr/status/1237565381788569603

Terribly shameful for the University, sad for an otherwise extremely beneficial project.

+1 for reverting the change.

**Comment by Miserlou** [comment]
Interestingly, this ticket has also made the wire service, which is something I've never seen before: https://www.reuters.com/article/us-health-coronavirus-taiwan-university/taiwan-protests-as-top-u-s-university-labels-island-part-of-china-on-virus-map-idUSKBN20Y0NK

**Comment by changey** [comment]
Thank you! Appreciated!

**Comment by takua624** [comment]
Thanks for reconsidering this. Hope the labels can soon resume what they were prior to March 9th.

**Comment by ladris** [comment]
I, for one, feel it's atrocious that instead of having a civil discourse about it, as academic persuit requires, the reaponse was to spam and essentialy attempt to hold the project hostage until demands were met.

**Comment by Eclipsed830** [comment]
> I, for one, feel it's atrocious that instead of having a civil discourse about it, as academic persuit requires, the reaponse was to spam and essentialy attempt to hold the project hostage until demands were met.

While I agree it might have been better if all the responses and comments were in a single ticket, let's not let that get in the way of correcting the issue at hand. If this was about academic rigor, the name change never would have or should have happened in the first place. The media has WIDELY reported Taiwan's contributions and best practices with regards to this specific virus and Taiwan should have never been censored and marginalized like they were with this policy change. The fact of the matter is, Taiwan has never been part of the PRC and the Chinese Communist Party has never had effective authority over the country of Taiwan. Labeling Taiwan under China and as "Taipei" instead of Taiwan is absolutely unacceptable and that sort of misinformation does not belong anywhere, let alone on a Johns Hopkins University project. Of course people got upset over this issue... with this update it essentially made it so Taiwan and the 23+ million people that put blood, sweat and tears into their country simply don't exist.

**Comment by ladris** [comment]
That's not what it did at all, that's a political perception of the issue. The fact of the matter, is the project is data driven. If it's demonstrated that someone on the project maliciously edited or modified the data **TO** do that, that is one thing. It's another entirely if, in the course of formatting continuously being adjusted because not everyone has a Country>State>County>City>Town>Village model, that ultimately the guidelines of organization from the WHO were followed, then go protest the WHO. The appropriate response is certainly not to go mass disrupt a global source of information as a miss-targeted entity.

**Comment by Eclipsed830** [comment]
> That's not what it did at all, that's a political perception of the issue. The fact of the matter, is the project is data driven. If it's demonstrated that someone on the project maliciously edited or modified the data **TO** do that, that is one thing. It's another entirely if, in the course of formatting continuously being adjusted because not everyone has a Country>State>County>City>Town>Village model, that ultimately the guidelines of organization from the WHO were followed, then go protest the WHO. The appropriate response is certainly not to go mass disrupt a global source of information as a miss-targeted entity.

I think the issue is people are talking about the output on the actual map posted by @CSSEGISandData and not the git repository itself. You have two types of people here; people upset that Taiwan was removed and censored on the map, and people upset that their dataset was broken.

Taiwan is not a member of the WHO, so protesting the WHO would be meaningless. The best you can do is go directly to the source (here).

>I highly doubt someone woke up and said "Oh, hmmm, Taiwan... can't have them independent" and most likely it was a mass edit of formatting across multiple countries. My issue isn't whether or not it should be listed independently, but how the response was handled, and the continuous validation that it's an appropriate response.

To be fair, [China is kind of notorious for forcing these types of edits](https://www.washingtonpost.com/world/asia_pacific/taiwan-contemplates-retaliating-against-airlines-that-refer-to-it-as-part-of-china/2018/08/07/a3ded97a-99fa-11e8-b55e-5002300ef004_story.html) and Taiwanese people are just sick of it I think...

**Comment by ladris** [comment]
> To be fair, [China is kind of notorious for forcing these types of edits](https://www.washingtonpost.com/world/asia_pacific/taiwan-contemplates-retaliating-against-airlines-that-refer-to-it-as-part-of-china/2018/08/07/a3ded97a-99fa-11e8-b55e-5002300ef004_story.html) and Taiwanese people are just sick of it I think...

To be honest, I have very similar feelings. But also understand time and place needs to be considered.  This legitimately has a chance of snowballing recklessly out of control to the point where the top 10 pages are nothing but the same, one line thread over and over again to the point that it would have to be mass "censored" which would cause even more fury because it "validates" that they are being oppressed and censored, instead of the reality being the mass spam being disruptive with only one real solution. :-/

**Comment by takua624** [comment]
I, for two, think it completely reasonable to blame JHU **before** JHU explains it's just reporting whatever misinformation the WHO feed it. Now that we know the origin of this farce is WHO (or, CHO since it's obeying the instructions from china so faithfully), we'll make sure that every Taiwanese knows it's useless to issue a complaint here.

Without the knowledge about the involvement of WHO, it seems just like the maintainer of this map surreptitiously brought chinese propaganda into this project. Instead of issuing complaints, do you expect Taiwanese to appreciate the elegance of this sneaky move (although now we know they probably didn't do it) and patiently check out who has already filed a complaint and leave a feeble "yeah, please change it back" comment in that inconspicuous thread?

I, for three, think no one can hold the project hostage just by leaving angry comments. The maintainer of the project can still do what they want to do, and people can still report whatever other bugs they find. 

I, for one, think it's actually atrocious to use "atrocious" to describe the anguish felt by the Taiwanese due to the injustice delivered by WHO.

**Comment by designbyadrian** [comment]
Can we stop shouting about Big Bad China and just recognise the fact that printing data with free-text fields as keys is bad practice? Taiwan isn't unique in receiving wrong country names.

**Comment by ladris** [comment]
> Without the knowledge about the involvement of WHO, it seems just like the maintainer of this map surreptitiously brought chinese propaganda into this project. Instead of issuing complaints, do you expect Taiwanese to appreciate the elegance of this sneaky move (although now we know they probably didn't do it) and patiently check out who has already filed a complaint and leave a feeble "yeah, please change it back" comment in that inconspicuous thread?
> 
No, I expect them to be very vocal about it. In a single thread. As I said. 70+ one liner threads get spammed out, filtered and closed. A single thread, or even two threads, with 500+ responses keeps attention as long as it is civil.

> I, for three, think no one can hold the project hostage just by leaving angry comments. The maintainer of the project can still do what they want to do, and people can still report whatever other bugs they find.
> 
And sure, no _one_  person could. But how about when the top 600 "issue" posts are rhetoric protest posts? Or when 1 out of every 16 posts is actually a technical issue or missing cases report. How about when people go to report an issue and see nothing but a spam "attack" and decide that a crucial issue isn't worth reporting because the devs will never see it?

> I, for one, think it's actually atrocious to use "atrocious" to describe the anguish felt by the Taiwanese due to the injustice delivered by WHO.

**Comment by takua624** [comment]
If it's wrong from the beginning, it's just a mistake.
But it has been correct for more than a month, and then become wrong, that made Taiwanese suspect it's Big Bad China taking advantage of the bad practice of printing data with free-text fields as keys.

**Comment by takua624** [comment]
> > Without the knowledge about the involvement of WHO, it seems just like the maintainer of this map surreptitiously brought chinese propaganda into this project. Instead of issuing complaints, do you expect Taiwanese to appreciate the elegance of this sneaky move (although now we know they probably didn't do it) and patiently check out who has already filed a complaint and leave a feeble "yeah, please change it back" comment in that inconspicuous thread?
> 
> No, I expect them to be very vocal about it. In a single thread. As I said. 70+ one liner threads get spammed out, filtered and closed. A single thread, or even two threads, with 500+ responses keeps attention as long as it is civil.
> 
> > I, for three, think no one can hold the project hostage just by leaving angry comments. The maintainer of the project can still do what they want to do, and people can still report whatever other bugs they find.
> 
> And sure, no _one_ person could. But how about when the top 600 "issue" posts are rhetoric protest posts? Or when 1 out of every 16 posts is actually a technical issue or missing cases report. How about when people go to report an issue and see nothing but a spam "attack" and decide that a crucial issue isn't worth reporting because the devs will never see it?
> 
> > I, for one, think it's actually atrocious to use "atrocious" to describe the anguish felt by the Taiwanese due to the injustice delivered by WHO.
> 
> And we haven't even discussed the extra time sink necessary to police and clean up the posts being taken out of the maintainers probably valuable time.

Very civil. Got it.

**Comment by paulyehtw** [comment]
Hey, why on the earth you think Taiwan is a part of China? I suggest you to read some history and you will realize you are being ignorant

**Comment by ladris** [comment]
> Hey, why on the earth you think Taiwan is a part of China? I suggest you to read some history and you will realize you are being ignorant

Whereas I think you should actually read the conversation before ignorantly posting

**Comment by alexkychen** [comment]
Hey @CSSEGISandData, 
I just want to give you a kind heads-up. Now it is 3 AM in Taiwan. Once the mistake (list Taiwan as part of China) is on Taiwan local media tomorrow morning, it will only make it crazier here. I bet you want to fix the bug very quickly. I highly appreciate your hard work and good luck!!

**Comment by takua624** [comment]
It's already "fixed" somehow, Taiwan now belongs to the country/region "others"

**Comment by ladris** [comment]
> Hey @CSSEGISandData,
> I just want to give you a kind heads-up. Now it is 3 AM in Taiwan. Once the mistake (list Taiwan as part of China) is on Taiwan local media tomorrow morning, it will only make it crazier here. I bet you want to fix the bug very quickly. I highly appreciate your hard work and good luck!!

Except it's not a bug nor a mistake. It's an issue with how the WHO defines sovereignty, and most of the data used comes from them. But it is being discussed and options looked at.

**Comment by alexkychen** [comment]
> It's already "fixed" somehow, Taiwan now belongs to the country/region "others"

Great! That's an improvement. It would be perfect to see "Taiwan" listed on the "Confirmed Cases by Country/Region" panel instead of "others". Keep up the good work, folks!

**Comment by designbyadrian** [comment]
@alexkychen Why on earth would it be in the local media?

**Comment by ladris** [comment]
> @alexkychen Why on earth would it be in the local media?

Never doubt the power of ill informed outrage.

**Comment by takua624** [comment]
you still can do something to prevent this outrage: write to the Taiwan local media to tell them the right information.

**Comment by Axelandre42** [comment]
Is it possible to add an **ISO 3166-1 numeric** field?
This would allow better data processing with other datasets...

**Comment by eacvo67347** [comment]
> > Hey, why on the earth you think Taiwan is a part of China? I suggest you to read some history and you will realize you are being ignorant
> 
> Whereas I think you should actually read the conversation before ignorantly posting
> 
> At no point did any of us say it was. However, we have all commented on the appropriate way to discuss the issue, of which you are a demonstration of the problem.

I think you are being too nice about this, and are giving China / WHO the benefit of the doubt.

A lot of people were drawn here because a report double checked with JHU for a response, and they flip flopped on their initial response. 

```
When contacted by Axios, Lauren Gardner, an associate professor of civil and systems engineering at JHU who directs the map project, at first said they would be changing it back to "Taiwan" immediately.

However, a JHU spokesperson later said they would retain the term “Taipei and environs” and would be adopting the World Health Organization naming scheme, which also uses “Taipei and environs” to refer to Taiwan.
```

Just to list out Taiwan's accomplishments in this keeping the coronavirus off its shores:
```
- stopped China PRC nationals from entering since early February.
- stopped HK, Macau residents from entering, since its very easy for China PRC nationals from entering via those cities.
- closed down many flight routes between China (5 remaining).
- 14 day home quarantine with daily checks via telephone. if the person is found to have sneaked out, they would be fined.
- closed schools before there was an outbreak and recently resumed, with temperature checks and disinfection stations, and everyone wears a mask.
- banned exportation of face masks and N95 respirators
- government led rationing of face masks, adults can purchase 3 masks per week and children can buy 5 masks per week, at a non inflated price. (~ $0.2 USD each)
- government used open data to the showing the mask in stock at each pharmacy. citizens use an open sourced map to find out where is the closest pharmacy that has masks in stock. it only takes a 20 minute wait to buy masks, vs 3 to 6 hours in Korea, where it's not even in stock.
- screening stations outside hospitals to screen all incoming visitors. visitors required to present their health cards, and if they have a fever, they are required to do a nasal and throat swab for testing.
- hospital workers only work on their specific floors to prevent intrahospital transmission (compartmentalize the areas for possible transmission).
- daily CDC press conferences, and confirmed cases are described (personal details are omitted)
- synthesized Remdesivir & Favilavir for emergency usage.
```

This is why Taiwan's numbers are so low. **And this is why there is an outrage.**
I doubt other countries have done as much in keeping their citizens safe.

/rant

**Comment by CSSEGISandData** [comment]
please see issue #504

**Comment by eacvo67347** [comment]
> Is it possible to add an **ISO 3166-1 numeric** field?
> This would allow better data processing with other datasets...
> 
> For example, https://population.un.org/wpp/Download/Standard/CSV/
> 
> At the moment it's not really possible to make an hard link between this dataset and those from the UN... Adding the numeric ID field would allow to compare much more things.


quoting someone else about the issue of ISO country codes. Unicode CLDR is more equitable.

> 
> The problem with using ISO country codes is they are politicized as being involved with the ISO requires UN Membership. This is why using ISO 3166-2 country codes and naming is considered bad practice and most software developers instead use Unicode CLDR. http://cldr.unicode.org/translation/displaynames/country-names
> 
> https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/en/territories.json
> 
> _Originally posted by @Eclipsed830 in https://github.com/CSSEGISandData/COVID-19/issues/372#issuecomment-597427641_

**Comment by eugene-yang** [comment]
I will like to give some credit to the team! @CSSEGISandData Thank you for addressing this issue.

I do understand there are political challenges out there and thank you so much for making this change. 
Based on your commit log, I know you are working really hard on this! 
![image](https://user-images.githubusercontent.com/15350619/76460722-ed04cf80-63b4-11ea-98a0-008105d4090c.png)

and minutes after
![image](https://user-images.githubusercontent.com/15350619/76461020-76b49d00-63b5-11ea-98a3-3d6f60d7d19a.png)

For every Taiwanese who was outrageous about this issue, please give them some credit for addressing this. They are a small team and faced tons of issues when updating the data last night. Having this issue handled in a day is incredible!

**Comment by changey** [comment]
Thank you @CSSEGISandData !

**Comment by ohbriansung** [comment]
Thank you @CSSEGISandData ! Well done!

**Comment by eugene-yang** [comment]
And a follow-up message to @CSSEGISandData, since you have already put it on github as an opensource project, feel free to reach out to the community for help. There are tons of experienced engineers and developers can help with solving whatever issue or even implementing new features. 

Based on your commit log on `web-data` branch, I know you are working very hard on this and we can actually see the updates on the map. Nice work and feel free to call for help :)

**Comment by takua624** [comment]
Thank you @CSSEGISandData ! I greatly appreciate your effort to restore a map free of the mis-information originated from WHO. I'm sorry for being not particularly civil and blamed you for altering how the data was represented.

**Comment by weasellin** [comment]
Thanks @CSSEGISandData for building this nice project,
and for the great effort to handling this naming issue,
to give us taiwanese people basic respect.
Hope WHO could learn from you.

**Comment by annieyanghy** [comment]
Thank you @CSSEGISandData for making changes in the face of political hostility.
However, I still want to know why Taiwan has a star sign though.

**Comment by eugene-yang** [comment]
@annieyanghy at the footnote of the interactive map
FYI --
> *This website and its contents herein, including all data, mapping, and analysis (“Website”), copyright 2020 Johns Hopkins University, all rights reserved, is provided to the public strictly for educational and academic research purposes. The Website relies upon publicly available data from multiple sources, that do not always agree. The names of locations correspond with the official designations used by the U.S. State Department, including for Taiwan. The Johns Hopkins University hereby disclaims any and all representations and warranties with respect to the Website, including accuracy, fitness for use, and merchantability. Reliance on the Website for medical guidance or use of the Website in commerce is strictly prohibited.

**Comment by ShawTim** [comment]
@CSSEGISandData excuse me - how about Hong Kong? It's still combined into China.

**Comment by annieyanghy** [comment]
> @annieyanghy at the footnote of the interactive map
> FYI --
> 
> > *This website and its contents herein, including all data, mapping, and analysis (“Website”), copyright 2020 Johns Hopkins University, all rights reserved, is provided to the public strictly for educational and academic research purposes. The Website relies upon publicly available data from multiple sources, that do not always agree. The names of locations correspond with the official designations used by the U.S. State Department, including for Taiwan. The Johns Hopkins University hereby disclaims any and all representations and warranties with respect to the Website, including accuracy, fitness for use, and merchantability. Reliance on the Website for medical guidance or use of the Website in commerce is strictly prohibited.

Thank you for the clarification. I was thinking that might be a footnote to it but couldn't find it. Thank you.

**Comment by wzxu** [comment]
"Taipei and environs, China" was such a creative, unprofessional, irresponsible, politics-over-global-health monstrosity of a naming by WHO. Casting aside the fact that PRC has never ruled over Taiwan for one second, it simply has zero say and no direct info of how the disease is being controlled in Taiwan, so how is it logical to even suggest they can represent her? 

Now it's finally back to normal* Good job everyone 👏

**Comment by RoyaHsueh** [comment]
Truly appreciate it. Thank you @CSSEGISandData

**Comment by KevinCayenne** [comment]
Truly thanks! Thanks @CSSEGISandData stand for making it change and all your effort on the map!

**Comment by Johnny850807** [comment]
Apprecieted! @CSSEGISandData

**Comment by hanshengchiu** [comment]
If you multiply number of deaths and infections in China by 10, you'll get realistic numbers, not "official" ones.

**Comment by lung2008123** [comment]
@CSSEGISandData Appreciate! Taiwan is an independent country, not a part of CCP & CRP.

**Comment by goldflower** [comment]
Thanks, you guys rock :)

**Comment by sjmackenzie** [comment]
@Ryllau have you returned Hong Kong and Macao back to their rightful positions yet?

**Comment by bachi76** [comment]
Did that change break the whole data? Lots of data is currently corrupt, not updated (e.g. Italy, Switzerland) for 2 days, and the dashboard shows only 91'000 infections at the moment... @CSSEGISandData

**Comment by nodeful** [comment]
I'll just leave it here:
```json
{
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Belarus": "BY",
  "Belgium": "BE",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Congo (Kinshasa)": "CD",
  "Costa Rica": "CR",
  "Cote d'Ivoire": "CI",
  "Croatia": "HR",
  "Cuba": "CU",
  "Cyprus": "CY",
  "Czechia": "CZ",
  "Denmark": "DK",
  "Dominican Republic": "DO",
  "Ecuador": "EC",
  "Egypt": "EG",
  "Estonia": "EE",
  "Faroe Islands": "FO",
  "Finland": "FI",
  "France": "FR",
  "French Guiana": "GF",
  "Georgia": "GE",
  "Germany": "DE",
  "Gibraltar": "GI",
  "Greece": "GR",
  "Hong Kong": "HK",
  "Guyana": "GY",
  "Holy See": "VA",
  "Honduras": "HN",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Korea, North": "KP",
  "Korea, South": "KR",
  "Kuwait": "KW",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Macao": "MO",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Malta": "MT",
  "Martinique": "MQ",
  "Mexico": "MX",
  "Moldova": "MD",
  "Monaco": "MC",
  "Morocco": "MA",
  "Mongolia": "MN",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Nigeria": "NG",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Panama": "PS",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Reunion": "RE",
  "Romania": "RO",
  "Russia": "RU",
  "Saint Barthelemy": "BL",
  "San Marino": "SM",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbia": "RS",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "South Africa": "ZA",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "St. Martin": "MF",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Taiwan*": "TW",
  "Thailand": "TH",
  "Togo": "TG",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Ukraine": "US",
  "United Arab Emirates": "UA",
  "United Kingdom": "GB",
  "US": "AE",
  "Vatican City": "VA",
  "Vietnam": "VN"
}

This is how the names appear in the dataset + added some more trying to somewhat follow the convention
```

**Comment by Bost** [comment]
See also
https://github.com/Bost/corona_cases/blob/master/src/corona/countries.clj
https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/app/utils/countrycodes.py

**Comment by brianmorrisuk** [comment]
Hi guys,

Is it just me or did the United Kingdom 'GB' going missing off the map today?

Great work..!!

**Comment by brianmorrisuk** [comment]
Further to last.

United Kingdom is on list but data is incorrect. Currently shows 3 cases puting it at bottom of list out of sight. Did naming changes seperate Uk from Gibraltar and break data feed?

**Comment by cloudhy417-ntu** [comment]
Thank you. This mean a lot for Taiwan people.

**Comment by vi000246** [comment]
Thank you @CSSEGISandData

**Comment by yetzt** [comment]
Thank you for all your efforts. Me opening issues is not to complain, but to get stuff fixed. I appreciate all your hard work and though i'm frustrated at times i'm tremendously grateful for you being out there and doing a hard job!

**Comment by aditsu** [comment]
Hong Kong has been missing from the list of countries for many days now.
Hong Kong is **NOT** a province of China!!!

**Comment by designbyadrian** [comment]
Please search and +1 similar issues instead of creating new ones.

**Comment by JakeVestal** [comment]
For now, here's the scheme I'm using to match old & new region names onto each other. Feel free to use yourself; let me know if you spot a mistake!

```
`Mainland China`             = "China",
`The Bahamas`                = "Bahamas",
`Bahamas, The`               = "Bahamas",
`Congo (Brazzaville)`        = "Congo",
`Congo (Kinshasa)`           = "Congo",
`The Gambia`                 = "Gambia",
`Gambia, The`                = "Gambia",
`Hong Kong`                  = "Hong Kong SAR",
`Iran (Islamic Republic of)` = "Iran",
`Korea, South`               = "South Korea",
`Macao SAR`                  = "Macao",
`Republic of Ireland`        = "Ireland",
`Republic of Korea`          = "South Korea",
`Republic of Moldova`        = "Moldova",
`Republic of the Congo`      = "Congo",
`Russian Federation`         = "Russia",
`Taipei and environs`        = "Taiwan",
`Taiwan*`                    = "Taiwan"
```

**Comment by sjmackenzie** [comment]
@JakeVestal where is your site?

**Comment by Benjozork** [comment]
People, before you get mad, the country names are probably generated from a list and associated with official data. I highly doubt JHU is expressing their support for the PRC on purpose here.

**Comment by yetzt** [comment]
The data should instead of only relying on arbitrary strings that may vary between data sources make use of *ISO 3166-1 alpha-2* (colloquially known as *domain endings*) to have a uniform and dependable scheme of which country is which.

**Comment by aditsu** [comment]
> People, before you get mad, the country names are probably generated from a list and associated with official data. I highly doubt JHU is expressing their support for the PRC on purpose here.

If they have some automated process and the data sources suddenly butchered the country list without their knowledge, then I can agree with you... for a couple of days at most. But the problems have been brought to their attention repeatedly and they did absolutely NOTHING for many many days now, this is either active support of terrorism and tyranny or EXTREME incompetence / negligence.
What if their data sources suddenly decide to classify the US as a minor province of North Korea? Would it be acceptable to let that stand for weeks?

**Comment by designbyadrian** [comment]
@yetzt CLDR is a much better option: https://github.com/CSSEGISandData/COVID-19/issues/470#issuecomment-597599428

**Comment by yetzt** [comment]
@designbyadrian whatever standard works :)

**Comment by JakeVestal** [comment]
@sjmackenzie not up yet. Check back this evening or maybe tomorrow morning :3

**Comment by sjmackenzie** [comment]
Such a pity the ideological steps taken by Johns Hopkins has hidden vital epidemiological data. For example would people have seen the `[masks for all](https://www.youtube.com/watch?v=qFmaSNP6_z4)` trend sooner had saving millions of lives in the future? Please contact these people at [Whiting School of Engineering](https://systems.jhu.edu/about/team/)

**Comment by gazhayes** [comment]
Hong Kong was the perfect example to learn from and save lives. Quite a shame that in this day and age people still have to die for silly reasons like this.

**Comment by sjmackenzie** [comment]
Yes, sadly the data is hidden for political reasons. Here's a video illustrating the importance of masks https://www.youtube.com/watch?v=gAk7aX5hksU
