### ISSUE TITLE
Issue in Data feed for confirmed cases in Germany.

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#4824]
There is a discrepancy in the confirmed cases data of Germany in Github CSSE feed for 24th October. As a total no of confirmed cases for 23th October(4476187) is greater than 24th October(4476078).

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this discrepancy. We have corrected our data to align with the source. See commit: https://github.com/CSSEGISandData/COVID-19/commit/cd117bb6a031cda70dfa303e6494aa2d6a731f2e
