### ISSUE TITLE
Discrepancy in the confirmed cases data of India. 

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#4838]
There is a discrepancy in the confirmed cases data of India in Github feed for 2nd January. Total no of confirmed cases for 1st January (10325823) is greater than 2nd January (10323965), which is not possible. Kindly look into this issue.

**Comment by CSSEGISandData** [comment]
Thank you. We will look into this issue.

**Comment by CSSEGISandData** [comment]
We have investigated and patched the issue. Thank you for notifying us of this discrepancy! 

commit: https://github.com/CSSEGISandData/COVID-19/commit/70ae8e8bc4ea9759903fdaf4040383ae5564f72a
