### ISSUE TITLE
Nebraska Deaths on Oct 27

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#4839]
Hi,

I noticed that Nebraska put all data under unassigned category days ago. However, there was still a large jump on deaths on Oct 27, with 330 new deaths reported. May I ask if Nebraska reported data all at a time for several months?

**Comment by CSSEGISandData** [comment]
Thank you. We will look into this issue.

**Comment by CSSEGISandData** [comment]
Please see the additional note in #4825.
