### ISSUE TITLE
Covid stats incorrect for Germany

### ISSUE THREAD

**Issue by nickybisht** [CSSEGISandData/COVID-19#4840]
Covid cases for germany for 30 Dec,20 (49,044) and 21 Mar, 21(768) seems to be incorrect. For both the dates stats are different in WHO(https://www.who.int/countries/deu/) and Worldometer(https://www.worldometers.info/coronavirus/country/germany/)

11149 on worldometer for 21 Mar
13733 on WHO for 21 Mar

22459 on WHO for 30 Dec
28410 on worldometer for 30 Dec

Please confirm if github(https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) is showing correct data or not. If it is incorrect, Please update the data.

**Comment by CSSEGISandData** [comment]
Thank you. We will look into this issue.

**Comment by CSSEGISandData** [comment]
Currently, our source for Germany is Berliner Morgenpost and can be found here: https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/

We have investigated the listed dates above and found a few discrepancies that we are working on patching. Thank you for notifying us of this issue!

Following the patch, we will close this issue accordingly.
