### ISSUE TITLE
Discrepancy in New covid cases count for Israel

### ISSUE THREAD

**Issue by nickybisht** [CSSEGISandData/COVID-19#4841]
Noticed discrepancy in New Covid cases count for Israel for 26th Jan 2021 (8587).

As per the Ministry of Health of Israel's official website the count for that day was 7824 (https://datadashboard.health.gov.il/COVID-19/general?tileName=newVerifiedDaily).

As per https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data on February 22, 2021 few adjustments were made for 1/25/2021 and 1/26/2021 daily reports.

https://www.israelhayom.com/2021/01/26/health-minister-relentless-covid-morbidity-requires-extending-lockdown/: Count "609,656" was added taking this source as reference for 26th jan.

https://www.israelhayom.com/2021/01/25/health-ministry-180-people-infected-by-single-passenger-returning-from-dubai/: Count 601,069 was added taking this source as reference for 25th jan.

Due to this the new cases count is 609,656 - 601,069 = 8587

But this doesn't match with the Ministry's data. So please check this again.

**Comment by CSSEGISandData** [comment]
Thank you. We will look into this issue.

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for this issue. It is related to #4613. Our historical case data for Israel does not match those of the Ministry of Health (irrespective of the media back distribution) for the details shared in the below post.
