### ISSUE TITLE
Bad data in 01-14-2021.csv

### ISSUE THREAD

**Issue by rjanderson** [CSSEGISandData/COVID-19#4848]
There is a divide by zero error in computing Case Facility Ratio - leading to the text of #DIV/0! which occurs on row 268 (and a few others).  This is a problem for the CSV Reader I am using.  I assume that some script needs to have a divisor check.

**Comment by CSSEGISandData** [comment]
Thank you for the notification. This has been patched. I have not located the error in any other files, but please raise another issue if you locate another.
