### ISSUE TITLE
Possibly Incorrect Data on Japan new Cases on 10/30/2021

### ISSUE THREAD

**Issue by SperoGalaty** [CSSEGISandData/COVID-19#4851]
Hello, I have looked through all of the primary sources and Japanese-specific sources specified that use the data pooling and have yet to find any information on a sudden jump of cases that are being reported.

**Comment by CSSEGISandData** [comment]
Thank you for your message. One of our sources, NHK news, has an alert regarding this spike on their webpage. I'll include the google translation here:

"The Tokyo Metropolitan Government has made a large-scale correction on October 29, 2021 and the number of infected persons announced during the six months from April 2, 2021 to October 2, 2021. 4512 were newly added and 447 were removed, an increase of 4065 from previous announcements as a result of additions and removals."

As these are newly reported cases, they are most accurately included in the report on Oct 30 unless a back distribution is made publicly available.
