### ISSUE TITLE
A number of Utah counties are showing zero cumulative cases but NYT site shows non-zero figures

### ISSUE THREAD

**Issue by macpheeb** [CSSEGISandData/COVID-19#4852]
Counties showing as zero cumulative cases include Uintah, Washington and Weber, while these show non-zero -
https://www.nytimes.com/interactive/2021/us/utah-covid-cases.html

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your question. Our reporting matches the jurisdictional levels published on the [Utah Department of Health](https://coronavirus.utah.gov/case-counts/#overview) COVID-19 dashboard. For example, you will see that Weber County is not reported independently but is instead the Weber-Morgan Health District, which is reported in our dataset. We cannot speak to the sourcing or reporting of the New York Times.
