### ISSUE TITLE
New cases in Japan on Oct 30, 2021

### ISSUE THREAD

**Issue by MikihiroMatsuoka** [CSSEGISandData/COVID-19#4854]
We see a big jump in new cases in Japan on Oct 30 in your database, from the current trend of less than 300 daily cases to 4,284 cases. Local data available in Japan do not show such a jump. Would you please examine if this data is correct? Thank you very much in advance.
[211101-COVID-19-JHU-Japan-TotalCases.xlsx](https://github.com/CSSEGISandData/COVID-19/files/7449867/211101-COVID-19-JHU-Japan-TotalCases.xlsx)

**Comment by CSSEGISandData** [comment]
Thank you for your message. One of our sources, [NHK news](https://www3.nhk.or.jp/news/special/coronavirus/data-all/), has an alert regarding this spike on their webpage. I'll include the google translation here:

"The Tokyo Metropolitan Government has made a large-scale correction on October 29, 2021 and the number of infected persons announced during the six months from April 2, 2021 to October 2, 2021. 4512 were newly added and 447 were removed, an increase of 4065 from previous announcements as a result of additions and removals."

As these are newly reported cases, they are most accurately included in the report on Oct 30 unless a back distribution is made publicly available.
