### ISSUE TITLE
Covid cases for Japan seem to be incorrect.

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#4865]
Covid cases for Japan for 30 Oct,21 (49,044) and 31 Oct, 21(768) seem to be incorrect. For both the dates stats are different in WHO(https://www.who.int/countries/deu/) and Worldometer(https://www.worldometers.info/coronavirus/country/germany/)
 290 on worldometer for 30 Oct,21
4343 on WHO for 30 Oct,21
287 on WHO for 30 Dec
312 on worldometer for 30 Dec
Please confirm if github(https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) is showing correct data or not. If it is incorrect, Please update the data.

**Comment by CSSEGISandData** [comment]
Hello,

Please see #4851 and #4854 for explanations regarding the spike in cases on October 30. Secondly, I believe you may have calculation errors for the new case differences you are posting. For Japan, our new cases for Oct 30 are 4,284 and for Oct 31 are 232, not 49,044 and 768. As listed in our README, our data sources for Japan are [COVID19Japan](https://covid19japan.com/#all-prefectures) and [NHK](https://www3.nhk.or.jp/news/special/coronavirus/data/). We cannot comment on the small differences between WHO and WoM.
