### ISSUE TITLE
Unusual spike in covid cases for Turkey on December 10, 2020

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#4866]
Official Turkish gov website says that the count of new covid cases on December 10, 2020 was 30,424 [(link)](https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html) while the change in github feed is significantly large as total cases count on December 10 increases to 1748567 from 925342 on the previous day (Δ 823225).

Also, 925342 does not match with count of total cases on December 9 when compared with official source i.e. 558,517.

**Comment by CSSEGISandData** [comment]
Please see #3484 where this has been addressed previously.
