### ISSUE TITLE
Request for including Region/Province level Time Series Data for Available Countries

### ISSUE THREAD

**Issue by sudheesh001** [CSSEGISandData/COVID-19#4869]
The current data in the `time_series_covid19_confirmed_global.csv` include 8 countries with Region/Province level data:
- Australia
- Canada
- China
- Denmark
- France
- Netherlands
- New Zealand
- United Kingdom

<details><summary>Corresponding Regions/Provinces (arrow to collapse/uncollapse)</summary>
<pre>
├── Australia
│   ├── Australian Capital Territory
│   ├── New South Wales
│   ├── Northern Territory
│   ├── Queensland
│   ├── South Australia
│   ├── Tasmania
│   ├── Victoria
│   └── Western Australia
├── Canada
│   ├── Alberta
│   ├── British Columbia
│   ├── Diamond Princess
│   ├── Grand Princess
│   ├── Manitoba
│   ├── New Brunswick
│   ├── Newfoundland and Labrador
│   ├── Northwest Territories
│   ├── Nova Scotia
│   ├── Nunavut
│   ├── Ontario
│   ├── Prince Edward Island
│   ├── Quebec
│   ├── Repatriated Travellers
│   ├── Saskatchewan
│   └── Yukon
├── China
│   ├── Anhui
│   ├── Beijing
│   ├── Chongqing
│   ├── Fujian
│   ├── Gansu
│   ├── Guangdong
│   ├── Guangxi
│   ├── Guizhou
│   ├── Hainan
│   ├── Hebei
│   ├── Heilongjiang
│   ├── Henan
│   ├── Hong Kong
│   ├── Hubei
│   ├── Hunan
│   ├── Inner Mongolia
│   ├── Jiangsu
│   ├── Jiangxi
│   ├── Jilin
│   ├── Liaoning
│   ├── Macau
│   ├── Ningxia
│   ├── Qinghai
│   ├── Shaanxi
│   ├── Shandong
│   ├── Shanghai
│   ├── Shanxi
│   ├── Sichuan
│   ├── Tianjin
│   ├── Tibet
│   ├── Unknown
│   ├── Xinjiang
│   ├── Yunnan
│   └── Zhejiang
├── Denmark
│   ├── Faroe Islands
│   └── Greenland
├── France
│   ├── French Guiana
│   ├── French Polynesia
│   ├── Guadeloupe
│   ├── Martinique
│   ├── Mayotte
│   ├── New Caledonia
│   ├── Reunion
│   ├── Saint Barthelemy
│   ├── Saint Pierre and Miquelon
│   ├── St Martin
│   └── Wallis and Futuna
├── Netherlands
│   ├── Aruba
│   ├── Bonaire, Sint Eustatius and Saba
│   ├── Curacao
│   └── Sint Maarten
├── New Zealand
│   └── Cook Islands
└── United Kingdom
    ├── Anguilla
    ├── Bermuda
    ├── British Virgin Islands
    ├── Cayman Islands
    ├── Channel Islands
    ├── Falkland Islands (Malvinas)
    ├── Gibraltar
    ├── Isle of Man
    ├── Montserrat
    ├── Saint Helena, Ascension and Tristan da Cunha
    └── Turks and Caicos Islands
</pre>
</details>

However the daily reports contain information of Region/Province level from 16 additional countries (listed below). Would it be possible to provide this information in the time series data?

- Belgium
- Brazil
- Chile
- Colombia
- Germany
- India
- Italy
- Japan
- Malaysia
- Mexico
- Pakistan
- Peru
- Russia
- Spain
- Sweden
- Ukraine

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the question. At the present, we are not making further subnational data available in the time series. Please use the daily reports for historical subnational data.
