### ISSUE TITLE
Guernsey not listed and Moldova cases listed twice

### ISSUE THREAD

**Issue by Puebla1** [CSSEGISandData/COVID-19#487]
Republic of Moldova = Moldova (the cases are again duplicated)
Guernsey has a case registered at WHO since report 50 (just yesterday)

Thank you

**Comment by iandoug** [comment]
probably under Channel Isles, which is not a country.

**Comment by Puebla1** [comment]
Ok, thank you for the feedback.


-----Mensaje original-----
De: "Ian Douglas" <notifications@github.com>
Enviado: Wednesday, March 11, 2020 10:00am
Para: "CSSEGISandData/COVID-19" <COVID-19@noreply.github.com>
CC: "Puebla1" <jgarces@clinicaruiz.com>, "Author" <author@noreply.github.com>
Asunto: Re: [CSSEGISandData/COVID-19] Guernsey not listed and Moldova cases listed twice (#487)



probably under Channel Isles, which is not a country.
