### ISSUE TITLE
Time series and Country/Region issue

### ISSUE THREAD

**Issue by tranquyphi** [CSSEGISandData/COVID-19#488]
The dashboard and data provided by the team from JHU CSSE is unique and valuable. I watched the Dr. Lauren Gardner's presentation about this dashboard and the data gathering and validating process... at a conference about COVID-19 .

So I think some issues of data on this repository is not too big to resolve.

The name of country/region is not a political issue only. That is the epidemiological aspect of the disease outbreaks we must consider carefully too. 

Thanks to the authors again.

**Comment by crbarahona** [comment]
Any chance that presentation is publicly available somewhere? I'm really interested in the process.

**Comment by tranquyphi** [comment]
https://www.youtube.com/watch?v=Pnk8DuAly9Y
