### ISSUE TITLE
Extra columns in 08-09-2021.csv and 08-10-2021.csv under csse_covid_19_daily_reports_us folder

### ISSUE THREAD

**Issue by luxuyan2018** [CSSEGISandData/COVID-19#4894]
I found 2 issues with the data format of 08-09-2021.csv and 08-10-2021.csv under csse_covid_19_daily_reports_us folder:
1. All the rest csv files have 18 columns beside 08-09-2021.csv and 08-10-2021.csv, these 2 files have 2 extra columns: Cases_28_Days and Deaths_28_Days.
2. Last_Update format in these 2 files  (m/dd/yyyy) are different with other files (yyyy-mm-dd).

**Comment by CSSEGISandData** [comment]
Patched here: https://github.com/CSSEGISandData/COVID-19/commit/af2cb6522b227e717caabf96ebe6eba0577bbb24
