### ISSUE TITLE
Denmark: Same count of Daily cases for 4th & 5th Nov

### ISSUE THREAD

**Issue by nickybisht** [CSSEGISandData/COVID-19#4897]
Daily confirmed cases for Denmark for 4th & 5th Nov is same: 395797

Please fix this.

Source: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

![image](https://user-images.githubusercontent.com/90417853/141140732-3fb8b25e-f01b-49c7-96a7-f80dfc5fef46.png)
![image](https://user-images.githubusercontent.com/90417853/141140809-3045a5e6-c04c-43a2-a045-b316754e0194.png)

**Comment by CSSEGISandData** [comment]
Thank you for notifying us of this discrepancy. We have investigated and patched the issue with commit: https://github.com/CSSEGISandData/COVID-19/commit/3f20f13715b7fbc3b7c627efedaca8cf788bdb11
