### ISSUE TITLE
China vs WHO confirmed cases

### ISSUE THREAD

**Issue by kerskine** [CSSEGISandData/COVID-19#49]
Will WHO statistics be used for your dataset versus those published from Chinese sources?

China changed its confirmed case statistic to include clinically diagnosed cases (cat scan of patients lungs to see if they're infected) in addition to laboratory confirmed cases. The WHO doesn't agree with this change and are publishing statistics based on laboratory confirmed cases. 

Thanks

**Comment by CSSEGISandData** [comment]
We are also providing WHO confirmed cases in https://github.com/CSSEGISandData/COVID-19/tree/master/who_covid_19_situation_reports. Thanks!

**Comment by CSSEGISandData** [comment]
Hello,

We are also tracking WHO data here:
https://github.com/CSSEGISandData/COVID-19/tree/master/who_covid_19_situation_reports

Thanks!
Frank
