### ISSUE TITLE
Pennsylvania spike 11/13

### ISSUE THREAD

**Issue by BioTurboNick** [CSSEGISandData/COVID-19#4907]
The Pennsylvania spike on 11/13 doesn't match the PA dashboard: https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx

Might be a double-count?

**Comment by CSSEGISandData** [comment]
Hi Nick,

We're investigating but it appears to be related to the visualization on the PA dashboard. [Our data](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/11-12-2021.csv) for 11-12-2021 matches the [state report for that day via twitter](https://twitter.com/PAHealthDept/status/1459208248146411527). The one day change in cases as reported by the state (1639310 - 1618870 = 20,440) is not compatible with the change as visualized by the state on their dashboard. Additionally, the historical data in their [open data portal](https://data.pa.gov/Covid-19/COVID-19-Aggregate-Cases-Current-Daily-County-Heal/j72v-r42c), which is meant to be organized by date of report, does not match recent news reporting (e.g., [Nov 12](https://www.statecollege.com/centre-county-adds-70-covid-19-cases-pennsylvania-reports-5555-new-positives/)), suggesting an alteration to historical data on their end affecting their visualization.

We'll investigate and update this issue when we have more clarity.

**Comment by CSSEGISandData** [comment]
Please see #4912.
