### ISSUE TITLE
Unusual Indiana counts

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#4910]
On Thursday, Nov. 11, a federal holiday, quite a few Indiana counties reported significantly higher case counts than on a regular day, often something like 1.5x to 3x the usual count. Previous Thursdays were consistent with adjacent Wednesdays and Fridays; in this week the numbers were quite disparate: 2,783; 6,874; 2,809.

I can't find anything to explain a backlog, and the Johns Hopkins total reported through that day, 1,046,792, is significantly above the total reported in media at the end of that day -- 1,042,847.

I'm thinking there's a case backlog dump in here but I can't find any documentation.

**Comment by CSSEGISandData** [comment]
Hi Mike,

Please see #4912. Hopefully this helps! Indiana added reinfections on this date.
