### ISSUE TITLE
Ireland cases - Yesterdays count is more than double the real number.

### ISSUE THREAD

**Issue by callumok2004** [CSSEGISandData/COVID-19#4919]
![image](https://user-images.githubusercontent.com/35779365/142247959-b2f5ab1b-b5ec-423c-ad7f-7fd4e1f6568c.png)

The value on the repo for 16/11/21 is 8,965, the real value is 4,407

https://covid19ireland-geohive.hub.arcgis.com/
![image](https://user-images.githubusercontent.com/35779365/142248198-cd34442c-5f79-4fc9-984d-e3f16c55990e.png)

I believe what happened is the data from that 15th was added to the 16th, as the 15th shows 0, which also needs to be fixed.

**Comment by CSSEGISandData** [comment]
Patched in #4971
