### ISSUE TITLE
Deaths and vaccinations stats not working

### ISSUE THREAD

**Issue by turbo5** [CSSEGISandData/COVID-19#4921]
I have tried to see these data in the google search results, it only fetches and shows the new cases. No deaths and vaccinations are shown, for any of the countries I tried (I clicked on multiple countries randomly).
It has been present during the day, tested on multiple clients, mobile and desktop as well.
Screenshot attached, from a mobile client.
![covid stats error](https://user-images.githubusercontent.com/980749/142279040-73a88e21-e788-4138-b55f-8f0b81e2b2a2.jpg)
.

**Comment by CSSEGISandData** [comment]
Thank you. There have been no changes to our dataset so this is likely an issue with the google display and thus we are not able to correct this. We apologize for the inconvenience.
