### ISSUE TITLE
Spike in Missouri cases 11/18

### ISSUE THREAD

**Issue by naterattner** [CSSEGISandData/COVID-19#4929]
Hi all, it looks like Missouri reported an abnormally high number of cases yesterday: 11,088, compared to a previous seven-day average of about 1,400.

Any idea if this is due to a backlog release, adding of reinfections, error, etc.?

Thanks as always.

**Comment by naterattner** [comment]
Looks like this may be related to an addition of reinfection data: https://health.mo.gov/news/newsitem/uuid/9509c2b6-fd39-4d22-8fe9-f5757a9393a7/breakthrough-infection-data-added-to-missouri-s-covid-19-dashboard

> Additionally, data displaying information about SARS-CoV-2 reinfections has been added to the dashboard. A reinfection refers to someone who has tested positive for the virus, recovered and tested positive again after 90 days or more. 

> Prior to this update, each “case” on the dashboard represented an individual Missourian. Now, the total count of cases will represent individual infections among Missourians rather than Missourians who have been infected.

**Comment by CSSEGISandData** [comment]
Thanks Nate! Announced in #4930.
