### ISSUE TITLE
Daily Covid-19 reports query on Confirmed field for Ireland

### ISSUE THREAD

**Issue by edwardUL99** [CSSEGISandData/COVID-19#4935]
I was looking at Covid-19 daily reports data, particularly at the cases for Ireland. Since the reports are "daily reports", I assumed that the confirmed field contained the number of cases confirmed on that day. However, I now realised, that the confirmed cases field contains the total number of cases recorded since counting of COVID-19 cases began. For example, as of the 01-06-2021 (file https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/01-06-2021.csv), I read confirmed as 121154. The actual daily case for this date was somewhere around 8000. However, looking at historical data, the number 121154 was the total recorded since the whole pandemic. The 'Active' cases field also doesn't reflect the daily recorded cases. So, is there a field that I am missing that actually records the number of cases reported on that particular date only?

I believe the issue is that the confirmed value is retrieved from https://covid19ireland-geohive.hub.arcgis.com/. However, this site only gives confirmed as the total number of cases since the start of the pandemic. It's daily cases come under New Cases

Thanks in advance

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. The daily reports only contain the total cases and deaths for a location up to that specific day. We do not publish files reporting the deltas.
