### ISSUE TITLE
total_tests in France

### ISSUE THREAD

**Issue by odadoun** [CSSEGISandData/COVID-19#4938]
Hi,

'total_tests' (cumulative tests) seems to be not  available for France but 'new_tests' (new per day) yes.
Does the total_tests is the sum of new tests ? if yes why it is not apply for France ?
By advance thank you
And thanks for all your work 
cheers
Olivier

**Comment by CSSEGISandData** [comment]
Thank you for your comment. Our repository does not contain testing data.

**Comment by odadoun** [comment]
oups sorry ... I though it was owid data ...
