### ISSUE TITLE
South Africa daily cases incorrect

### ISSUE THREAD

**Issue by CTucker897** [CSSEGISandData/COVID-19#4943]
The data shows that on the 23rd November 2021 new cases were 18,586, but the South African National Commonable Diseases reported only 868 (https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-23-november-2021/) which is far more in line with the current trend of cases in the country.

**Comment by CTucker897** [comment]
Also, thanks for all your hard work!

**Comment by CSSEGISandData** [comment]
Thank you for notifying. These are associated with a backlog of antigen tests. Further details in #4956.
