### ISSUE TITLE
23 July data was not updated for India. 

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#4945]
As per the github feed of India for both 22/07- 23/07, total number of confirmed cases is 31293062 which shows there were not any new cases on 23/07, but as per other sources like https://www.worldometers.info/coronavirus/country/india/ & https://www.who.int/countries/ind/ there were considerable number of new cases. Please look into this as it seems there is some data issue in the feed.

Thanks

**Comment by CSSEGISandData** [comment]
Corrected in #4976.
