### ISSUE TITLE
incorrect confirmed counts for Slovakia in time_series_covid19_confirmed_global.csv

### ISSUE THREAD

**Issue by kurcam** [CSSEGISandData/COVID-19#4947]
From the date November 18th 2021 there is some mistake in confirmed counts for Slovakia in time_series_covid19_confirmed_global.csv. Today there is 631738 positive tested persons (PCR) in Slovakia, but in your CSV file is 1092704 confirmed cases. What data source do you use for Slovakia? Our official pages are:
https://github.com/Institut-Zdravotnych-Analyz/covid19-data
https://korona.gov.sk/en/coronavirus-covid-19-in-the-slovak-republic-in-numbers/
It seems that until 17.11.2021 you counted only positive PCR tests and after 18.11.2021 you count PCR and AG tests together.

**Comment by CSSEGISandData** [comment]
Please see #4925.
