### ISSUE TITLE
Data for SA is incorrect there were not 18000 cases on the 23rd November

### ISSUE THREAD

**Issue by Slalom110** [CSSEGISandData/COVID-19#4955]
![image](https://user-images.githubusercontent.com/95075462/143555008-89953f4a-60b3-4b28-84bd-8282070708fb.png)
[](url
![Cases SA 23 11 2021](https://user-images.githubusercontent.com/95075462/143555130-6b9130e5-f67b-4058-821f-93bac0ea2706.JPG)
)

**Comment by CSSEGISandData** [comment]
Please see #4956
