### ISSUE TITLE
New Cases count for South Africa for 23rd Nov'21 is too high 

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#4960]
Coronavirus cases for South Africa is does not match for 23 November 2021 – >18,000 cases, is a huge spike.

Github Data
Verified the stats from csse_covid_19_daily_reports of November 22, 2021(https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-22-2021.csv) and November 23, 2021(https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-23-2021.csv) and the difference is 18586 [New cases]

However, on an external source Worldometer (https://www.worldometers.info/coronavirus/country/south-africa/#graph-cases-daily), we found stats different from the Github source i.e. 868.

Could you please check the reason for this variance between github and worldometer's data.

**Comment by CSSEGISandData** [comment]
Please see #4956.
