### ISSUE TITLE
Bad data for Afghanistan series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#4964]
Hi Team, 

We have observed that data published for Afghanistan on the file "time_series_covid19_deaths_global.csv" for the period 11/23/2021-11/28/2021 are not correct, since it's an accumulative series and the data points released are decreasing. 

Could you please check and advise on this? 
[time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/files/7617953/time_series_covid19_deaths_global.csv)

Thank you.

Regards,

**Comment by CSSEGISandData** [comment]
Thank you, patched using WHO time series data in #4972
