### ISSUE TITLE
Names and coordinates do not match up

### ISSUE THREAD

**Issue by mkiang** [CSSEGISandData/COVID-19#498]
I realize you might be moving away from reporting at the county level (which is hugely unfortunate). If you decide to stick with county, the names and coordinates often do not match up. For example:

```
   province_state        country_region   lat   long last_date  total_confirmed
   <chr>                 <chr>          <dbl>  <dbl> <date>               <dbl>
 1 Adams, IN             US              39.9  -77.3 2020-03-10               1
```

The coordinates here are actually for Adams County, PA. If I intend to use sub-state data, should I go by the name (`province_state`) or by the coordinates?

**Comment by CSSEGISandData** [comment]
Thanks @mkiang - corrected in current.
