### ISSUE TITLE
Netherlands Death difference in Daily report and time series files file

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#4988]
Hello,

I found that Netherlands death data is different in the following 2 files:

Daily report shows Netherlands deaths as 19974 on Dec 2 2021.

Time series file shows Netherlands deaths as 19524 on Dec 2 2021.

May I know which on is correct?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your comment. The total in the daily report, 19974, includes the total deaths in the Dutch territories of Aruba, "Bonaire, Sint Eustatius and Saba", and Curacao. The total 19524 only includes the deaths in admin level 1 regions of Netherlands, Netherlands.
