### ISSUE TITLE
South Africa - bad data for deaths time series

### ISSUE THREAD

**Issue by MrSpiffyClean** [CSSEGISandData/COVID-19#4994]
Hello there. An issue raised on a tracker I contributed raised the issue that the death count for South Africa is wrong for a couple of dates.

Starting at 2021-11-13, the values that are in the time series are:
89746,89746,89489,89504,89515,89515,89562,89572,89574,89584,89635,89657,89771,89783,89791,89797,89822,89843,89871,89915,89944,89944

They should be (according to [the SA Corona Virus Online Portal](https://sacoronavirus.co.za/category/daily-cases/)):
89476,89484,89489,89504,89515,89555,89562,89572,89574,89584,89635,89657,89771,89783,89791,89797,89822,89843,89871,89915,89944,89965

So, it seems the values for 2021-11-13, 2021-11-14 and 2021-11-18 are wrong (and the value for 2021-12-04 hasn't been updated yet).

**Comment by CSSEGISandData** [comment]
Hello,

We believe this is due data entry errors on the SA Dashboard that were not present in the daily reports on the SA Corona Virus Online Panel. We've used the data link you've provided to correct this data in #5010. Thank you very much and I hope this can rectify your tracker.
