### ISSUE TITLE
South Africa Incidence Rate 12-04-2021

### ISSUE THREAD

**Issue by rjanderson** [CSSEGISandData/COVID-19#4996]
The incidence rate for south africa (row 616, column M) is 50627 on 12-04,  but 5065 on 12-03 - so assume that the 12-04 value is off.  (I am using incidence rate to derive my normalization factor,  and was naturally interested in the SA data.)

**Comment by CSSEGISandData** [comment]
Thank you for notifying. We've corrected in #5020.
