### ISSUE TITLE
Keep the date time format consistent 

### ISSUE THREAD

**Issue by themindstorm** [CSSEGISandData/COVID-19#5]
In all files in [time_series](https://github.com/CSSEGISandData/2019-nCoV/tree/master/time_series), all times follow a specific format (2/5/2020 9:00 AM): `%m/%d/%Y %I:%M %p`. The last datetime however, has a different format. The time is now in the 24-hour format, and the year has been shortened from 2020 to 20 (2/8/20 23:04). I believe this format is `%m/%d/%y %I:%M`.

**Comment by takavarasha** [comment]
Could you use the International Standards Organisation (ISO) 8601 format? For example, use 2020-01-31T09:00 instead of 1/31/2020 9:00 AM.

**Comment by flindeberg** [comment]
Or even UTC time format, i.e. 20200209T120934Z, to avoid all probable issues with date and time formatting and filenames on different filesystems. I only think somewhat technically knowledgeable are going to use this repository anyhow, so keeping it technically meaningful seems like a good idea.

**Comment by Bost** [comment]
This might help you guys:

```clojure
(def month-nr-hm
  {
  "jan" "01"
  "feb" "02"
  "mar" "03"
  "apr" "04"
  "may" "05"
  "jun" "06"
  "jul" "07"
  "aug" "08"
  "sep" "09"
  "oct" "10"
  "nov" "11"
  "dec" "12"
   })

(defn normal-month [messy-month]
  (if-let [normal-m (get month-nr-hm messy-month)]
    normal-m
    (throw (Exception. (format "Unrecognized month: %s" messy-month)))))

(defn messy-month [normal-month]
  (if-let [messy-m (get (clojure.set/map-invert month-nr-hm) normal-month)]
    messy-m
    (throw (Exception. (format "Unrecognized month: %s" normal-month)))))

(defn time-am-pm [date-time]
  (let [time-am-pm (.substring date-time 6)
        length (count time-am-pm)
        am-pm (.substring time-am-pm (- length 2) length)]
    [
     ;; am-pm
     (if (or (= am-pm "am") (= am-pm "pm"))
       am-pm
       (-> "Unrecognized 12-hour (am/pm) format: %s"
           (format date-time)
           Exception.
           throw))
     ;; time
     (.substring time-am-pm 0 (- length 2))]))

(defn fix-octal-val
  "(read-string s-day \"08\") produces a NumberFormatException
  https://clojuredocs.org/clojure.core/read-string#example-5ccee021e4b0ca44402ef71a"
  [s]
  (clojure.string/replace s #"^0+" ""))

(defn normal-time
  "Remember: Always code as if the person who ends up maintaining your code is a
  violent psychopath who knows where you live

  e.g. (normal-time \"Jan28_11pm\") returns: \"0128_2300\""
  [messy-date-time]
  (let [
        date-time    (clojure.string/lower-case messy-date-time)
        month        (.substring date-time 0 3)
        month-normal (normal-month month)
        [am-pm time] (time-am-pm date-time)
        time-normal  (case (count time)
                       1 (str "0" time "00") ;; e.g. 1pm
                       2 (str time "00")     ;; e.g. 10pm
                       3 (str "0" time)      ;; e.g. 930pm
                       4 time)               ;; e.g. 1130pm
        s-hour       (.substring time-normal 0 2)
        s-min        (.substring time-normal 2)
        n-hour       (->> s-hour
                          (fix-octal-val)
                          (read-string))
        hour-normal  (+ n-hour (case am-pm
                                 ;; 12am ~ 00:00 / Midnight / day-start
                                 "am" (if (= 12 n-hour) -12 0)
                                 ;; 12pm ~ 12:00
                                 "pm" (if (= 12 n-hour) 0 12)))
        s-hour-normal (str "0" hour-normal)
        normal        (str (.substring s-hour-normal
                                       (- (count s-hour-normal) 2))
                           s-min)
        ]
    (str
     month-normal
     (.substring date-time 3 6)
     normal)))
```

I'll soon put my code to github.
BTW I implement a Telegram Chatbot `@corona_cases_bot` using the same data[*] as this project does. Would you give it a try. Thanks.

[*] from **the** [Google Sheet](https://docs.google.com/spreadsheets/d/1wQVypefm946ch4XDp37uZ-wartW4V7ILdg-qYiDXUHM/edit?usp=sharing) ... but my graphs differ! And I double checked the numbers... :-(

**Comment by jmcastagnetto** [comment]
Just in case someone else needs them, I put a couple of simple R scripts to cleanup the data at: https://github.com/jmcastagnetto/2019ncov-data-cleanup

**Comment by CSSEGISandData** [comment]
Sorry for the late response. We have updated time stamps in our data to UTC and are now following this format for our time series columns (e.g. 2/8/20). We are pushing updates to the time series (in folder csse_covid_19_data) once a day. Therefore, we have removed the time stamp and are now only displaying the date.

**Comment by Bost** [comment]
As promised, source code of the `@corona_cases_bot` is here https://github.com/Bost/corona_cases PRs welcomed

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238
