### ISSUE TITLE
Suspected cases

### ISSUE THREAD

**Issue by oliveiraandrade** [CSSEGISandData/COVID-19#50]
Hi.. is there any "suspected cases time series"?

**Comment by dawenx** [comment]
as far as i know, several sites in Chinese report suspected cases at country level; not sure whether they report suspected cases at province level; not sure whether other countries report this.

we have curated this data since 01/13. if it is useful for the community, we can add this to our [dashboard](http://ncov.bii.virginia.edu/dashboard/).

**Comment by oliveiraandrade** [comment]
@dawenx , I believe it would be useful for many people. Thanks!

**Comment by hazrulk77** [comment]
@dawenx,

Hi. Apologies if my message is posted here against your policy as I would like to seek clarifications,

I noticed that the Death data is lower compared to yesterday (1491 vs 1384). I have to ask to get confirmation.

Thank you!

**Comment by dawenx** [comment]
@hazrulk77 no apology is needed and i'm an user of this data set as you. in fact, i reported data issue on Hubei for 02/13 in #48 , i think they fixed it around 30 minutes ago. looks like they are doing some re-organization on the folders as I'm typing, i wish they communicate a little bit better as it would break lots of people's API call although the fix should be easy. @CSSEGISandData

**Comment by hazrulk77** [comment]
@dawenx Thank you for your clarifications. I believe they are working really hard to resolve this. Again, thanks for responding.

**Comment by avatorl** [comment]
-108 is ok. China reported -108 cases ("duplicate records found in past days statistics"). What is missing is +116 (new cases). But this is how JH CSSE usually manage data, they usually upload a file (or more than a file) with other provinces data and finally a file with Hubei update. Not sure how  it will work now with new files structure...

**Comment by CSSEGISandData** [comment]
Hello all, sorry for the sudden change. We are trying to unify the timestamp to UTC and fix some known errors. We are also working on automating the daily push. As for the suspected, we cannot find a reliable data source for this information. Neither do we want to surprise the public with a uncertain large number of the suspected. Thanks!
