### ISSUE TITLE
Maryland COVID-19 dashboard offline due to cyberattack

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#5002]
Hello all,

The website for the Maryland Department of Health is currently offline due to a cyberattack as [reported in local media](https://dcist.com/story/21/12/06/maryland-health-department-website-shut-down-due-to-cyberattack/). Among other issues, this has resulted in the Maryland COVID-19 dashboard being offline. New data was not reported on 12-05 and it is currently unclear when the dashboard may be back online.

**Comment by stucka** [comment]
Maryland's dashboard is updated as of 12-19.

I don't know if the data is formatted similarly to how it was before the attack, but there is now data.

https://coronavirus.maryland.gov/

**Comment by CSSEGISandData** [comment]
@stucka looks like hospitalizations and cases are back! Just have to keep waiting for deaths.
