### ISSUE TITLE
Do not copy all data from 10th Dec 2021

### ISSUE THREAD

**Issue by turbo717** [CSSEGISandData/COVID-19#5031]
From December 10, 2021, case (Country / Regions / Sovereignty about 200 regions) data can no longer be copied. For example, only 20 Regions data from US to South Africa. I am in great trouble.

**Comment by Epi-Mic** [comment]
Yeah, the main page contains the most recent data unlike time_series on GitHub, and it could be very helpful sometimes to copy that information and convert by using extra tools

**Comment by CSSEGISandData** [comment]
This has been resolved. Apologies.
