### ISSUE TITLE
pop_age_65_above.csv

### ISSUE THREAD

**Issue by Vamshi02** [CSSEGISandData/COVID-19#5032]
where can I get this data, pop_age_65_above.csv

**Comment by CSSEGISandData** [comment]
Hello,

The population data available in this repository is located in the [UID lookup table](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv). Our data only includes total population and population above 65 is not in this repository, apologies.
