### ISSUE TITLE
West Virginia vaccination count skyrocketed

### ISSUE THREAD

**Issue by BioTurboNick** [CSSEGISandData/COVID-19#5035]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1438610/145916270-e9316be6-2df9-42e1-8729-39e9dffd2000.png">

This may be an error also with the CDC data; many outlets show way too many people in WV fully vaccinated.

**Comment by CSSEGISandData** [comment]
Hello,

The statistics are accurate and are associated with a substantial lag in the state reporting COVID-19 vaccinations to the CDC. This statement is available in the footnotes of the [CDC COVID-19 vaccination dashboard](https://covid.cdc.gov/covid-data-tracker/#vaccination-trends): 

"West Virginia recently conducted an internal review of COVID-19 vaccine administrative data and determined that there was a lag in some of their data uploads to CDC Data Clearing House (DCH). Beginning November 15, 2021 and continuing through December 9, West Virginia submitted multiple files to DCH containing administration records from July through November of this year, which resulted in an increase of 1.47 million administration records for the state."

There is also [this relevant tweet](https://twitter.com/cyrusshahpar46/status/1469414898849366019) from the White House COVID-19 Data Director.

**Comment by BioTurboNick** [comment]
Thank you for checking. There were news stories saying a data reconciliation saw numbers go down, which was why some people, myself included, were confused: https://www.wboy.com/news/health/coronavirus/wv-gov-jim-justice-to-hold-virtual-covid-briefing-at-11-a-m/
