### ISSUE TITLE
Validate new covid cases for South Africa - Nov 23

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5039]
We have searched for the new cases on Nov 23rd 2021 on South Africa govt. Site (Link: https://sacoronavirus.co.za/2021/11/23/update-on-covid-19-tuesday-23-november-2021/
) and found that a total 868 new cases were reported on this date.

Worldometer (Link: https://www.worldometers.info/coronavirus/country/south-africa/
) also reported the same stats.

As per the github feed (Doc link: https://docs.google.com/spreadsheets/d/1I8RwxaPR0oaslqQ5ZAP28f1TCIwZVckZjhkIcuKqD5I/edit#gid=0
), we have huge new cases on Nov 23rd; 18568

Github Link: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Can you please check and confirm if the stats are correct on github?

**Comment by CSSEGISandData** [comment]
Please see #4956 which addresses the backlog of cases published on this day.
