### ISSUE TITLE
Question: Country values with null Province/State value

### ISSUE THREAD

**Issue by lucasrodes** [CSSEGISandData/COVID-19#5051]
I am wondering about the values for `Denmark` (and other countries) in [time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) or [time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv).

If I filter the tables with `Country/Region = "Denmark"`, I get three rows:

|Province/State|Country/Region|Lat    |Long    |1/22/20|1/23/20|1/24/20|
|--------------|--------------|-------|--------|-------|-------|-------|
|Faroe Islands |Denmark       |61.8926|-6.9118 |0      |0      |0      |
|Greenland     |Denmark       |71.7069|-42.6043|0      |0      |0      |
|              |Denmark       |56.2639|9.5018  |0      |0      |0      |

Does the last row (empty value for `Province/State`) refer to European Denmark? The same occurs with other countries with overseas territories (France, Netherlands, United Kingdom). I tried to find this info in the documentation but could not find it.

Thanks for your work & help!

**Comment by CSSEGISandData** [comment]
Hello,

You are correct that the entries which are blank represent the higher level administrative levels. For countries with overseas territories (e.g., Denmark, France, United Kingdom) the ',Country/Region' entry represents the "mainland" location. In the daily reports, the subnational locations are included in the "Province/State" entry. Please let us know if you need more clarification.

**Comment by Akashkunwar** [comment]
Adding all the values of Province/State in the country value is good for doing analysis of this data country-wise?
