### ISSUE TITLE
Data Error on time_series_covid19_confirmed_global.csv for Chile  (10 Dec 2021)

### ISSUE THREAD

**Issue by elaval** [CSSEGISandData/COVID-19#5058]
**COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv**

The value for confirmed cases on 2021-12-10 (10 Dec) duplicates the value reported for 2021-12-09 (9 Dec)
![image](https://user-images.githubusercontent.com/68602/146639742-dbac0da3-cbac-440b-befc-c0e61368d4ba.png)

This has implications on the calculation of weekly cases for Dec 17 (gets over reported)

Oficial reports in Chile do not show this duplication

![image](https://user-images.githubusercontent.com/68602/146639903-5843754c-2e69-4046-93ac-7eb71039e0ef.png)

[https://s3.amazonaws.com/gobcl-prod/public_files/Campa%C3%B1as/Corona-Virus/Reportes/17.12.2021_Reporte_Covid19.pdf](https://s3.amazonaws.com/gobcl-prod/public_files/Campa%C3%B1as/Corona-Virus/Reportes/17.12.2021_Reporte_Covid19.pdf
)

Thanks

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for the message. Chile did not publish their COVID-19 data on December 10, 2021. Therefore, our data is accurate when interpreted as "report date". Please see that there is no "Reporte Diario COVID-19 10-12-2021" on their [Ministry of Health website](https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/).
