### ISSUE TITLE
Dec 16 Confirmed Cases and Deaths Data of Turkey Repeated in Dec 17 and Dec 18

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#5060]
Confirmed cases and deaths data for Turkey for Dec 17 and 18 repeat the data of Dec 16. https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html (in Turkish) publishes the daily increment data for confirmed cases under column (Bugünkü Vaka Sayısı) and deaths under column (Bugünkü Vefat Sayısı).

**Comment by CSSEGISandData** [comment]
Addressed by #5069.
