### ISSUE TITLE
New covid cases in Argentina for Dec13-14

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5065]
Hi team, 

It has been observed that the new covid-19 cases in Argentina were not updated on 13th Dec & 14th Dec. As it is showing 0 new cases on 13th of Dec & 8067 new cases on 14th of Dec. However Data in other sources are Different, like on Worldometer it shows 3512 & 4555 for 13th & 14th respectively. Similarly in coronatracker.com data is same as worldometer and data in WHO has 2445 & 1570 for 13th & 14th dec respectively and in OWID it shows 2186 for 13th & 2897 for 14th.

Github source - https://github.com/CSSEGISandData/COVID-19/archive/master.zip
WHO - https://covid19.who.int/region/amro/country/ar 
Worldometer - https://www.worldometers.info/coronavirus/country/argentina/ 
Coronatracker - https://www.coronatracker.com/country/argentina/ 
OWID - https://ourworldindata.org/coronavirus/country/argentina 

Please check

**Comment by CSSEGISandData** [comment]
Patched in #5135
