### ISSUE TITLE
New covid cases for Germany mismatch

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5066]
For the location Germany “new cases” on the date Dec 25th 2020, provided by github feed (https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
); 2140 is not matching with the govt site (https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/
) and few other external sites; ~25k

WHO: https://www.who.int/countries/deu/
Corona tracker: https://www.statista.com/statistics/1100823/coronavirus-cases-development-germany/

Can you please check and correct if the feed stat is wrong?

**Comment by CSSEGISandData** [comment]
Thank you. Our cumulative data matches that posted by the source you have linked above ([Berliner Morgenpost](https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/)). Their daily new cases graph does not match their historical data.

Statista rehosts data from Worldometer.
