### ISSUE TITLE
New covid cases for Spain missing

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5067]
For the location Spain, new cases for multiple days are missing (0 new cases) from github feed.
Feed: for date Dec 11th 2021: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-11-2021.csv

Feed: for date Dec 12th 2021 :https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-12-2021.csv

Whereas other external sources have reported some new cases count for same dates.
WHO: https://covid19.who.int/region/euro/country/es (new cases: 19,673 and 24,172)
Worldometer: https://www.worldometers.info/coronavirus/country/Spain/#graph-cases-daily (new cases: 16,601, 16,601)
 
Can you please check and update if feed stats are wrong?

**Comment by CSSEGISandData** [comment]
Thank you for your question. We take our data directly from the Spanish Ministry of Health, who do not publicly report data on the weekends. This is the reason there are no updates on December 11th or 12th (or other weekend days). The reporting from the Spanish Ministry of Health is more timely than that of the World Health Organization. 

WorldoMeter generates their own data when sources have gaps in reporting. This is the reason they have updates on December 11th and 12th and the reason the case counts for those two days are identical. All data in our repository can be traced back to their original source and we do not publish estimates.
