### ISSUE TITLE
Naming Convention (continue)

### ISSUE THREAD

**Issue by CNNPress** [CSSEGISandData/COVID-19#507]
We noticed the programmer attempted to remove previous insulting name "Taipei and environs" and
probably accidentally changed it to "Other," while the correct name should be "Taiwan."

Does that mean people from Taiwan now need to say they are from Other?

Please kindly correct the problem.
Thank you very much.

**Comment by ladris** [comment]
Oooof. That username could be interpereted as an attempt to immitate and fake an identity. This matter is closed and has been decided in another thread update.

**Comment by CNNPress** [comment]
Please close the ticket. It just changed back to correct name. Thanks.
