### ISSUE TITLE
Tokyo death cases count high - July 28

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5071]
The "deaths" data for Tokyo on July 28th is incorrect since it shows 23 deaths but a different number has been reported by other sources.
Github Source (difference in 2 dates is 23):
28 July : 2285 https://github.com/CSSEGISandData/COVID-19/blob/a709afe7d89fd24236b9fb1196462cd1c69c7e6c/csse_covid_19_data/csse_covid_19_daily_reports/07-28-2021.csv
27 July : 2262 https://github.com/CSSEGISandData/COVID-19/blob/a709afe7d89fd24236b9fb1196462cd1c69c7e6c/csse_covid_19_data/csse_covid_19_daily_reports/07-27-2021.csv

As per other sources for Japan overall, the deaths are 15 or 14.
Other Sources:
https://covid19.who.int/region/wpro/country/jp
https://www.worldometers.info/coronavirus/country/japan/

Please check and confirm the github data.

**Comment by CSSEGISandData** [comment]
Hello,

The data files you are referencing exist on a branch which has not been maintained for many months. Please see the [07-27-2021 daily report](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/07-27-2021.csv) and [07-28-2021 daily report](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/07-28-2021.csv) on the master branch which match the data from [NHK](https://www3.nhk.or.jp/news/special/coronavirus/data-widget/#mokuji0).
