### ISSUE TITLE
Bad data for Afghanistan series - Confirmed Coronavirus Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5076]
Hi Team,

We have observed that data published for Afghanistan on the file "time_series_covid19_confirmed_global.csv" for the period 12/13/2021-12/20/2021 are not correct, since it's an accumulative series and the data points released are decreasing.

Could you please check and advise on this?
[time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/files/7754994/time_series_covid19_confirmed_global.csv)

Thank you.

Regards,

**Comment by CSSEGISandData** [comment]
Thank you for reaching out about this data issue. We have investigated and patched our data accordingly. See commit: e15a8b9f47e6d487407a153763f70cda2b1a3737
