### ISSUE TITLE
0 case for Denmark two days in a row

### ISSUE THREAD

**Issue by edomt** [CSSEGISandData/COVID-19#5088]
Hi CSSE team!

It seems like the data collection has somehow failed for Denmark in the last two days:

![image](https://user-images.githubusercontent.com/7103774/147340993-6b21272d-652f-407e-8535-712a10a9f7a2.png)

**Comment by CSSEGISandData** [comment]
Thank you very much Ed and apologies for this. We've tracked the issue down to a reorganization of the [Denmark dashboard](https://experience.arcgis.com/experience/aa41b29149f24e20a4007a0c4e13db1d) to include reinfections that decommissioned but did not retire the previous data tables behind the dashboard. We have the updated data tables now so tonight's data update will include the current value and we are tracking down historical data for the days we have been stale. I'll keep this issue open until we are able to correct the stale days.

**Comment by CSSEGISandData** [comment]
Hi @edomt - patched in #5093. Should be good for your team! Apologies again.
