### ISSUE TITLE
Florida missing data updates?

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#5096]
The @CSSEGISandData data set is showing zero cases reported in Florida on Dec. 24.

Florida reported about 125,000 for the week in its official report; JHU data show about 50,000.

Florida's official report puts the total at 3,864,213, some 31,683 cases more than this data set is showing. That's close to the increase tracked by local media at 31,758: https://www.palmbeachpost.com/story/news/coronavirus/2021/12/24/covid-omicron-variant-florida-record-cases-reported-testing-centers-close-christmas/9016240002/

Thank you for all you do!

**Comment by CSSEGISandData** [comment]
Thanks Mike! Patched in #5104.
