### ISSUE TITLE
Confirmed cases for Romania seem to be incrorrect on December 22 and 23, 2021.

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#5103]
The confirmed cases for Romania  are 0 cases  on 22 Dec-21 and 1626 cases on 23 Dec 21 as per feed: 
 
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-21-2021.csv 

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-22-2021.csv

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-23-2021.csv 

As per [WHO](https://covid19.who.int/region/euro/country/ro), reported stats for 22 & 23 dec 2021, are 826 & 851, respectively for Romania.

Could you please check the reported stats?

**Comment by CSSEGISandData** [comment]
Patched in #5110.
