### ISSUE TITLE
Confirmation required for new covid cases for Ontario for 25 Dec, 2021 & 26 Dec, 2021

### ISSUE THREAD

**Issue by nickybisht** [CSSEGISandData/COVID-19#5113]
For the Location Ontario new cases on the dates 25-12-2021 and 26-12-2021 provided by github feed were 103 and 21 respectively. 

December 24:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-24-2021.csv

December 25: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-25-2021.csv

December 26:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-26-2021.csv

However, stats cannot be verified from the official website as the last updated date was December 24, 2021.

OW: 
https://covid-19.ontario.ca/data

Could you please check and confirm if these stats are expected.

**Comment by CSSEGISandData** [comment]
As documented in the [README file](https://github.com/CSSEGISandData/COVID-19/blob/master/README.md), our data for Ontario is composed of nine total sources. While the Ontario government site has not updated, the [Public Health Grey Bruce](https://www.publichealthgreybruce.on.ca/) website did update on December 26 for example.

**Comment by nickybisht** [comment]
On 29th December, the stats were updated on the OW(https://covid-19.ontario.ca/data/case-numbers-and-spread) for new cases . 

For the Location Ontario new cases calculated from github for the dates 25th, 26th, 27th, 28th December are found to be low in comparison with OW stats:

December 25:
Calculated from GITHUB : 103 cases https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-25-2021.csv
OW: 10412 cases

December 26:
Calculated from GITHUB: 21 cases https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-26-2021.csv
OW: 9826 cases

December 27:
Calculated from GITHUB: 7548 cases  https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-27-2021.csv
OW: 9418 cases

December 28:
Calculated from GITHUB: 2040 cases  https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-28-2021.csv
OW: 8825 cases

Also, we searched new cases for Ontario on sources mentioned on the README file, but could not verify with  the available stats on Github. So kindly look into it again and correct the feed if the stats are wrong.
