### ISSUE TITLE
Hong Kong is still merged into China in the latest update

### ISSUE THREAD

**Issue by ShawTim** [CSSEGISandData/COVID-19#516]
One day ago Hong Kong is listed as a State/Region, but now it's merged into China.

Merging Hong Kong into China doesnt help to prevent spread of COVID-19 becoz they have different immigration and borders, and also different policy for disease control and prevention.

Please separate Hong Kong out - which is what it is a day ago - such that ppl can effectively analyze the data for stopping spreading of COVID-19.

**Comment by ladris** [comment]
what does the US State Department list Hing King as?

**Comment by ShawTim** [comment]
> what does the US State Department list Hing King as?

https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories.html/
The Travel Advisories lists Hong Kong as a separated location from China. There is a reason.

**Comment by ladris** [comment]
Just noticed my phone murdered that one on auto correct.

That aside, the data will take a bit to restructure with todays announcement of firmly following the new chosen standard, so keep an eye on it incase it updates

**Comment by sjmackenzie** [comment]
Please inform us on what "standard" you are choosing? In the mean time wikipedia is a better source of information https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic

**Comment by Sania011** [comment]
Taiwan and Hong Kong have different border control and epidemic control measures. To understand the spread of the virus and what measures are effective, data from Taiwan and HK must be separated out. Please leave politics out of scientific data.

**Comment by AndroidDev77** [comment]
They aren't actively placing Taiwan and Hong Kong into China. China is reporting data for those regions. This data is for the purpose of their visualization, which maps using the Latitude and Longitude and not country. They would have to manually remove those regions from China's dataset and pull them for another source. 

Source: http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

**Comment by koyung** [comment]
@AndroidDev77 China is not the actual source of data for those regions. China is just copying data from Taiwan CDC and Hong Kong CHP, like any press. I think we should not treat them as a single region just because China repeats other region data in their press release.

Taiwan CDC: https://www.cdc.gov.tw/En/Bulletin/List/7tUXjTBf6paRvrhEl-mrPg
Hong Kong CHP: https://www.chp.gov.hk/en/media/116/index.html

China NHC, Taiwan CDC and Hong Kong CHP are organization responsible for epidemic control in Mainland China, Taiwan and Hong Kong respectively. They are independent to each other.

**Comment by ShawTim** [comment]
> They aren't actively placing Taiwan and Hong Kong into China. China is reporting data for those regions. This data is for the purpose of their visualization, which maps using the Latitude and Longitude and not country. They would have to manually remove those regions from China's dataset and pull them for another source.
> 
> Source: http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

@CSSEGISandData should not use the data source from China for HK data from day one. And the fact is, they are separated 2 days before. They either used the correct data source, or they had the so-called manual effort to put HK out, whatever.

It's nth about the Latitude and Longitude. While HK is a SAR, which has its own borders/immigrations/health dept, it's now put under China as a province.

HK is separated from US State Gov for travel advisory:
https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/hong-kong-travel-advisory.html

Merging HK into China doesnt help, instead it confuses ppl and put them into threats.
data is here for helping us to prevent virus spread. If @CSSEGISandData merges HK data into China, then how should US State Gov gives advisories? What supports them to give Level2 on HK while Level4 on China?

**Comment by Edditoria** [comment]
Hong Kong and China are different in medical, legal and economic systems. Separating those data will be helpful for further analysis, e.g. resource allocations, political policies, etc.

It is very common in real world, such as air ticket, GDP, email registration, Windows installation.

This is not about political power. This is all about solving problems. Thank you very much.
