### ISSUE TITLE
Jordan stale confirmed cases for 17 days (csse_covid_19_daily_reports)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#5178]
Moien from Luxembourg and Happy New Year!

Hope you all had nice holidays.
It seems that the numbers from Jordan are not picked up correctly anymore for two weeks+. I checked the source website and the Jordanian authorities are still publishing their new cases using this URL. 

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Patched using data from the World Health Organization in #5188.
