### ISSUE TITLE
Duplicated data for South Korea on 12-01-2021 and 12-02-2021

### ISSUE THREAD

**Issue by do2dkd** [CSSEGISandData/COVID-19#5189]
Hi,
I can see a huge peak in the Daily New Confirmed COVID-19 cases graph for South Korea on December 3, 2021
and Daily new confirmed COVID-19 cases on December 2, 2021 is zero.

![chrome_2022-01-12_120541_681](https://user-images.githubusercontent.com/4329681/149056738-2dd6ab8d-a266-43f8-8ea7-eab76ce69624.png)

I found the data of South Korea on [12-01-2021.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-01-2021.csv) and [12-02-2021.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/12-02-2021.csv) have duplicated value.
12-01-2021: `... 457612,3705,,,"Korea, South",892.5673732698257,0.8096378591470503`
12-02-2021: `... 457612,3705,,,"Korea, South",892.5673732698257,0.8096378591470503`
12-03-2021: `... 467907,3809,,,"Korea, South",912.6476620468089,0.8140506553652755`

It should be **462555** in total cases and **3739** in total deaths on **12-02-2021**, based on the data updated on 12-03-2021 from Ministry of Health and Welfare of South Korea: [Archive link(Korean)](https://web.archive.org/web/20211203075215/http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=11&ncvContSeq=&contSeq=&board_id=&gubun=)

Could you please check and fix data?

Thank you.

**Comment by CSSEGISandData** [comment]
Thank you for your assistance. Patched in #5258.
