### ISSUE TITLE
time_series_covid19_recovered_global.csv data not being updated after August 2020

### ISSUE THREAD

**Issue by Akashkunwar** [CSSEGISandData/COVID-19#5193]
I was doing some analysis, I noticed that data of **(time_series_covid19_recovered_global.csv)** recovered globally are not updated.
<img width="1310" alt="Screenshot 2022-01-12 at 8 46 18 PM" src="https://user-images.githubusercontent.com/75558817/149168622-8f863b4a-4a60-42ac-8bc2-b7da14a4252b.png">

As you can see in your data below:
<img width="1212" alt="Screenshot 2022-01-12 at 8 47 19 PM" src="https://user-images.githubusercontent.com/75558817/149168700-42e08ff6-a8b6-48c8-b4f8-ee08903242d7.png">

Can anyone help me with this?

**Comment by CSSEGISandData** [comment]
Please see #4465.
