### ISSUE TITLE
U.S. data not updated to Jan 11 for levels 2 and 3

### ISSUE THREAD

**Issue by kenshermock** [CSSEGISandData/COVID-19#5194]

**Comment by CSSEGISandData** [comment]
Would you be able to be more specific? There are updates at the US county, state, and national level in our [daily reports](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) and our [time series](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) for January 10, 11, and 12.

**Comment by kenshermock** [comment]
OK, they are now there as of this morning. They were not updated at the time I wrote my message. Thank you for all the work and care to provide these vital data.  Ken

From: CSSEGISandData ***@***.***>
Reply-To: CSSEGISandData/COVID-19 ***@***.***>
Date: Thursday, January 13, 2022 at 04:45
To: CSSEGISandData/COVID-19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [CSSEGISandData/COVID-19] U.S. data not updated to Jan 11 for levels 2 and 3 (Issue #5194)


      External Email - Use Caution





Would you be able to be more specific? There are updates at the US county, state, and national level in our daily reports<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCSSEGISandData%2FCOVID-19%2Ftree%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_daily_reports&data=04%7C01%7Cken%40jhmi.edu%7C5db6fcc737cf4f1db7d908d9d6797cde%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637776639550390209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=465%2F2h%2BZfNsrLiTNBm7trf2KRa0JUeO08yY89NXSvxk%3D&reserved=0> and our time series<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCSSEGISandData%2FCOVID-19%2Ftree%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series&data=04%7C01%7Cken%40jhmi.edu%7C5db6fcc737cf4f1db7d908d9d6797cde%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637776639550390209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WxD2Y35MnLT2A0CucThikHhuMoG4mLFhr1y8irk8hqo%3D&reserved=0> for January 10, 11, and 12.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCSSEGISandData%2FCOVID-19%2Fissues%2F5194%23issuecomment-1011965997&data=04%7C01%7Cken%40jhmi.edu%7C5db6fcc737cf4f1db7d908d9d6797cde%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637776639550390209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vMiyTAusyhJiFIn32h993ztdI%2BaoyTNMT8SkacB%2FouY%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB4MMYD6C5ZQPYSAHRAZ2B3UV2NL5ANCNFSM5LZR7YFQ&data=04%7C01%7Cken%40jhmi.edu%7C5db6fcc737cf4f1db7d908d9d6797cde%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637776639550390209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WFwBY2YCh2%2FQtG%2BT04EnUCqVwcQdvxkreItyvW2YzUQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cken%40jhmi.edu%7C5db6fcc737cf4f1db7d908d9d6797cde%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637776639550390209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Vq%2FgI%2FtgTs%2FuP5A8PuHBwwYAX%2B545cbacGyBvGb35%2BU%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cken%40jhmi.edu%7C5db6fcc737cf4f1db7d908d9d6797cde%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637776639550390209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aPR1bhgaYt0OPLHWQBQKyA3rXXOjzCYtTNJsjaJdREc%3D&reserved=0>.
