### ISSUE TITLE
Ontario_Canada: new daily cases, discrepancy wrt OW

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5207]
There is huge difference found between the stats of [OW](https://covid-19.ontario.ca/data/case-numbers-and-spread) and [JHU](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) data for new daily cases for the below mentioned dates:

December 29, 2021:
New daily cases calculated from JHU: 41560
OW: 10436
January 4, 2022:
New daily cases calculated from JHU: 47700
OW: 11352

Also, searched new cases for Ontario on other sources mentioned on the README file, but could not verify with the available stats on Github. 
Please confirm if these stats are expected or require a fix.

**Comment by CSSEGISandData** [comment]
Patched in #5303.
