### ISSUE TITLE
Florida deaths not properly updated

### ISSUE THREAD

**Issue by jdgalarneau** [CSSEGISandData/COVID-19#5214]
Florida Department of Health showing 63,158 fatalities as of Jan 14, but the JHU Florida data not only is 600+ off of this number, but there have been very few updates since the beginning of the year.

**Comment by stucka** [comment]
@jdgalarneau , some of this is being addressed in https://github.com/CSSEGISandData/COVID-19/issues/5196 ... You may wish to peruse that.

With the exception of like one week around September, Florida stopped reporting county-level deaths in early May, when it also switched to weekly reports overall. I understand @CSSEGISandData is trying to integrate a community report -- used to be called the White House report -- using numbers supplied by the state to the federal government, but not directly reported from the state itself. I think maybe what we're seeing is a race condition between the two sets of reports, where the federal data is older for the state totals but is several months ahead for the county-level data.

**Comment by CSSEGISandData** [comment]
Patched by #5275 and internal changes to our logic to take advantage of both the HHS CPR and Florida DOH weekly report.
