### ISSUE TITLE
India new cases on Jan 14, 2022 reported wrong

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [CSSEGISandData/COVID-19#5215]
As per the widget on Google, the new cases on January 14, 2022, was 5,33,035.

![Screenshot_20220116-124931.jpg](https://user-images.githubusercontent.com/16065837/149651050-e24fbb1b-e44e-4f9c-b5cb-6c8425ef87bb.jpg)

Whereas as per the NDTV website ("Coronavirus India Highlights: India Records 2.64 Lakh Fresh Covid Cases, 315 Deaths" https://www.ndtv.com/india-news/coronavirus-india-live-updates-india-records-2-47-417-new-covid-cases-2707258) the new cases on the same.date were 2,64,202.

Kindly look into the same.

**Comment by CSSEGISandData** [comment]
Fixed in #5375.

**Comment by Aram1374** [comment]
Aram Rostami
