### ISSUE TITLE
Daily cases are showing incorrect for Lithuania on January 12 and 13

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#5230]
Number of daily cases for Lithuania on 12th January, 2022 are shown as 8.95k and 0 for January 13th in the repository. On [WHO,](https://covid19.who.int/region/euro/country/lt) they are 4797 and 4164 respectively for these dates. It seems that JHU has merged the data for these two dates to show for January 12th only. Please fix this.

**Comment by CSSEGISandData** [comment]
Corrected in #5284.
