### ISSUE TITLE
You broke it.

### ISSUE THREAD

**Issue by kashaiahyah85** [CSSEGISandData/COVID-19#525]
The data itself now appears to have been more-or-less scrubbed. We, the community, can take over if you need. You appear to be new.

**Comment by ciscorucinski** [comment]
#close

**Comment by showdownhero** [comment]
> #close
> 
> They have provided all their sources. You are free to create your own perfect version

Do you know anywhere else that is collating this data? A tremendous amount of the historical data from South Korea and Iran (amongst others) has been scrubbed. I would love to find another place that has retained all this information.

**Comment by CSSEGISandData** [comment]
please see issue #521

**Comment by kashaiahyah85** [comment]
> please see issue #521

This answers little or nothing, except to reaffirm that you REALLY NEED to stop breaking things, however small you believe the changes to be. Either that, or just straight up shove your live raw data directly up here and let US work with it. Give warning before you go fiddling with this, or even get someone with coding experience, please. This could be Vital.
