### ISSUE TITLE
[FRANCE] Wrong daily cases

### ISSUE THREAD

**Issue by o71** [CSSEGISandData/COVID-19#5253]
Since 3 days the number of new cases for France is 0 while the number of cases explodes (436 167 cases yesterday)

Do you know the reason for this anomaly?

Thank you for your work.

**Comment by CSSEGISandData** [comment]
Hello,

It appears the file that we use from [data.gouv.fr](https://www.data.gouv.fr/en/datasets/donnees-relatives-a-lepidemie-de-covid-19-en-france-vue-densemble/) has published "NaN" in the "total_cas_confirmes" for the last three days. We'll investigate an alternative source and see if we can back distribute our historical data.

**Comment by Nicow91** [comment]
Good morning. You shoud use the column "conf_j1", which is still updated every day. https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/

**Comment by CSSEGISandData** [comment]
Patched in #5260
