### ISSUE TITLE
Error in Deaths Numbers in Cuba

### ISSUE THREAD

**Issue by FabrizioChiodo** [CSSEGISandData/COVID-19#5256]
There is a bug in your system in the death reported in Cuba. You reported on January 10th more than 24 death (as you can see  it is a very strange peak, a bug). On day 10th January, using the sources you have been using for Cuba since the beginning, only ONE death was recorded on that day... Thanks

**Comment by efaysal** [comment]
Yes indeed, the cumulative also is totally no-sense, please and thanks for fixing these numbers.

**Comment by FabrizioChiodo** [comment]
By the way, I have no idea how to fix it...

**Comment by efaysal** [comment]
the message is for the leading CSSEGISandData project  not you. 
hopefully,  it will take a quick fix ...

**Comment by CSSEGISandData** [comment]
Patched in #5261
