### ISSUE TITLE
Required Unique Key for Country/Region-A permanent resolution

### ISSUE THREAD

**Issue by tranquyphi** [CSSEGISandData/COVID-19#526]
We all known a table should have a ID field, aka key.   In this context, that is country code. The ISO code is available, if not, we are free to create one. The naming convention we apply is the description only and depend on the context of each user.

Thank you for your effort.

**Comment by analyzewithpower** [comment]
Agree. Also, on the university's dashboard, there is zero discrepancies as to county/state/country name. They have unique keys, could we get that same data?
