### ISSUE TITLE
Finland data outdated

### ISSUE THREAD

**Issue by 3dgiordano** [CSSEGISandData/COVID-19#5264]
Hi!

THL of Finland deprecated its old monitors at the end of the year 2021 and it seems that you are facing that you are not having the updated data since they stopped updating them since approximately January 12.

Now the new site where they report of covid tracking is
https://www.thl.fi/episeuranta/tautitapaukset/coronamap.html

And there is a webpage where you can easily obtain information on cases, test and deaths (also allow to export to csv using the api that is ideal for a automatic batch)
https://sampo.thl.fi/pivot/prod/en/epirapo/covid19case/fact_epirapo_covid19case?row=dateweek20200101-509093L&column=measure-444833.445356.492118.&fo=1

I hope this will be useful to keep the data up to date.

Regards
David

**Comment by EmTee70** [comment]
Would be nice if the JHU team would find time to fix this. No new data since Jan 13th now.

**Comment by yetzt** [comment]
i wish they would open source their scrapers so we could send pull requests.

**Comment by reima-ai** [comment]
Pretty easy csv using this. 

https://sampo.thl.fi/pivot/prod/en/epirapo/covid19case/fact_epirapo_covid19case.csv?row=dateweek20200101-509093L&column=measure-444833.445356.492118.&&fo=1

Updated about 11:40 GMT+2:00 (Mon to Fri)

Might need this in code:
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)
df = pd.read_csv(data,sep=';',encoding='utf8')

![image](https://user-images.githubusercontent.com/62258611/151253316-835ec5f0-e487-40a6-95eb-8d2711e5b5e9.png)

**Comment by CSSEGISandData** [comment]
Patched in #5300.

**Comment by EmTee70** [comment]
Thank you!
