### ISSUE TITLE
Mexico count of new cases missing for 18 and 20 Jan

### ISSUE THREAD

**Issue by MehraSakshi** [CSSEGISandData/COVID-19#5266]
Github data for Mexico is not updated for 18 Jan and 20 Jan(0 New cases) and 19 Jan(109895 New cases) https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/01-19-2022.csv

Data is getting updated on other websites for 18 Jan(17101 New cases), 19 Jan(49343 New cases) and 20 Jan(60552  New cases)

* Corona Tracker:(https://www.coronatracker.com/country/mexico/)

* Worldometer:(https://www.worldometers.info/coronavirus/country/mexico/)

**Comment by MehraSakshi** [comment]
Any update?

**Comment by CSSEGISandData** [comment]
Our internal records show that our source from the [government of Mexico](https://datos.covid-19.conacyt.mx/#DOView) did not update on these days. We will investigate if there are alternative sources.

**Comment by mkhanka** [comment]
The government of Mexico do have data for these days, can be confirmed by this graph
![image](https://user-images.githubusercontent.com/87356889/151021814-9d8aa867-35a7-4a25-9638-8bc86eebd30d.png)
and csv file [here](https://datos.covid-19.conacyt.mx/#DownZCSV) also have data for these days

**Comment by CSSEGISandData** [comment]
Thank you. These graphs are by a different metric then date of report, hence why the data for the most recent days would suggest the pandemic is ending in the country. Our data is by date of report as stated in the README.
