### ISSUE TITLE
Incorrect data for Oklahoma 01/24/2022

### ISSUE THREAD

**Issue by rterryou** [CSSEGISandData/COVID-19#5282]
The date suggests about 249 million news cases in a state with only 4.5 million people.

**Comment by CSSEGISandData** [comment]
Thank you. Could you please point to the data file or visualization that reports this number? I am unable to find that in any of the data files in this repository.

**Comment by rterryou** [comment]
Off of the website
epiforecasts.io/covid/posts/subnational/united-states/oklahoma/

**Comment by CSSEGISandData** [comment]
It appears to be an issue with the website rehosting our data rather than with our data itself. I would raise an issue on their repository: https://github.com/epiforecasts/covid/issues.

**Comment by rterryou** [comment]
Thanks.
