### ISSUE TITLE
Incorrect England New Cases of 19th & 20th Jan.

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5283]
Number of new cases of England on 19th Jan and 20th Jan, 2022 is incorrect in feed.

On 19th Jan, 2022, number of new cases on github is 95935 and on Official website it is 85901

On 20th Jan, 2022, number of new cases on github is 95157 and on Official website it is 76211

Official website:- https://coronavirus.data.gov.uk/details/cases?areaType=nation&areaName=England

**Comment by CSSEGISandData** [comment]
Hello,

The graph you are referencing is by _cases by specimen date_ while our repository is _cases by report date_. That specific graph will have its historical data modified with each update - tomorrow, the number of new cases will not be 85091 on Jan 19 and 76211 on Jan 20. It's also the reason for the disclaimer on the gov.uk site that "Data for the last 5 days, highlighted in grey, are incomplete." Our data will be maintained as it reflects the total number of new cases first reported on that day.

Our numbers for the United Kingdom nations of England, Scotland, Wales, and Northern Ireland match those reported by the UK Health Security Agency on [January 19](https://twitter.com/UKHSA/status/1484198290677714948?s=20) and [January 20](https://twitter.com/UKHSA/status/1483833065336156166?s=20).
