### ISSUE TITLE
Incorrect death data for Ontario, Canada

### ISSUE THREAD

**Issue by stephenpetersen** [CSSEGISandData/COVID-19#5289]
Time series currently shows no change to the cumulative death total since 18-Jan-2022 (i.e., 0 deaths for a week) for Ontario, Canada. This is incorrect and incompatible with official sources (https://covid-19.ontario.ca/data/case-numbers-and-spread#:~:text=Each%20day%E2%80%99s%20total,Table).

**Comment by CSSEGISandData** [comment]
Patched in #5303.
