### ISSUE TITLE
FYI: Covid-Dashboard for germany

### ISSUE THREAD

**Issue by klartext** [CSSEGISandData/COVID-19#529]
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

**Comment by klartext** [comment]
http://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/

**Comment by Bost** [comment]
Wow!

**Comment by loulouOz** [comment]
Nice, I have done a general one myself as I was curious to see spread over time for each country as well as new cases each day for each country:  https://virus-corona.herokuapp.com

**Comment by johnhorsema** [comment]
I've got one too, but simpler http://dz8je.csb.app/

**Comment by klartext** [comment]
Will close that issue.

The dashboard is now in
https://github.com/CSSEGISandData/COVID-19/issues/576

And the visualization from the media article is now in
https://github.com/CSSEGISandData/COVID-19/issues/578

**Comment by navmedvideos** [comment]
Coronavirus Live Stream - Real-time counter, Maps, and worldwide stats.

https://www.youtube.com/watch?v=qTbR2UKTQQc
