### ISSUE TITLE
Ontario not being updated in daily csv

### ISSUE THREAD

**Issue by mister-elliott** [CSSEGISandData/COVID-19#5299]
in your daily csv, you have not been updating Ontario since Jan 22.
COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/mm-dd-yyyy.csv

,,Nova Scotia,Canada,2022-01-27 04:21:19,44.681999999999995,-63.7443,35543,136,,,"Nova Scotia, Canada",3636.272490759184,0.38263511802605293
,,Nunavut,Canada,2022-01-27 04:21:19,70.2998,-83.1076,1439,5,,,"Nunavut, Canada",3834.4507478081487,0.34746351633078526

,,Ontario,Canada,2022-01-22 23:21:15,51.2538,-85.3232,971033,10702,,,"Ontario, Canada",6600.356298371372,1.1021252624782063

,,Prince Edward Island,Canada,2022-01-27 04:21:19,46.5107,-63.4168,6282,9,,,"Prince Edward Island, Canada",4307.085319743547,0.14326647564469913
,,Quebec,Canada,2022-01-27 04:21:19,52.9399,-73.5491,841413,12936,,,"Quebec, Canada",9903.903569051712,1.5374138502732904

**Comment by CSSEGISandData** [comment]
Patched in #5303.

**Comment by mister-elliott** [comment]
thanks, data is better today
