### ISSUE TITLE
Data Problems

### ISSUE THREAD

**Issue by wmrasmussen** [CSSEGISandData/COVID-19#53]
The data field "Province/States" has rows showing statuses (i.e. confirmed, deaths, severe etc.) along with actual provinces.  This is clearly a mistake. Can you fix this?  

Also, why did you do away with longitude/latitude? Can you bring it back?

Please commit to a format as to avoid introducing human error into the process.

**Comment by SchlittDataSci** [comment]
I'm using the archive data for now and letting my data be a bit late. I hope/couldn't imagine they're committing to the mixed statuses, that was just too strange of a format.

**Comment by Bost** [comment]
> I'm [...] letting my data be a bit late.

Hehe :) that's probably the best treatment for this data-format-breakage outbreak in this repo.

**Comment by CSSEGISandData** [comment]
We apologize for the changing data structure. Currently, the archived files are no longer being updated and we have moved on to using a new structure in csse_covid_19_data . This folder will be updated daily around 12am UTC (7pm EST). We are finalizing on a reliable data format that will be reflected in the new folder.

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238
