### ISSUE TITLE
Hong Kong Tai Wan are not China

### ISSUE THREAD

**Issue by standwithhongkong1234** [CSSEGISandData/COVID-19#530]
How dare they combine all the data into another country

**Comment by sjmackenzie** [comment]
I've found wikipedia to be a better non-political source of data https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic

**Comment by klartext** [comment]
There were already a lot of issues on the taiwan/hongkong issue.
Flooding the issue tracker with the same issue over and over again will not help you to solve the issue. It blocks ressources, and possibly will not be helpful then.

https://github.com/CSSEGISandData/COVID-19/issues/523
https://github.com/CSSEGISandData/COVID-19/issues/474
https://github.com/CSSEGISandData/COVID-19/issues/466
https://github.com/CSSEGISandData/COVID-19/issues/461
https://github.com/CSSEGISandData/COVID-19/issues/458

**Comment by tklam** [comment]
Merging Hong Kong or Taiwan into China is inhumane and irresponsible.

- As a medic:: one should treat regions with different measures and seriousness of the crisis separately
- As a statiscian/data scientist/engineer: is merging data sets from different environments or under different settings professional?
- As a human: kowtowing to an authoritarian government, which promotes police brutality/terrorism, silencing disobedients, and hegemonic control over other countries/regions, is evil

**Comment by cnineyy** [comment]
Hong Kong is still a special administrative region, that’s why we have our own sports team doing international sports in Olympics. So stop putting HK and China together coz Hong Kong is not China!

**Comment by B03901108** [comment]
@klartext The authors should have avoided these mistakes. But they didn't, and that's why they deserve this outrage :)
