### ISSUE TITLE
Hong Kong is NOT China !!

### ISSUE THREAD

**Issue by irisshing1211** [CSSEGISandData/COVID-19#533]
Please note that Hong Kong is **Not** China!!
Since we have different laws and other things.

**Comment by AndroidDev77** [comment]
As far as I can tell China is reporting data for Hong Kong and listing it under China. 

Source: http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

**Comment by ben181231** [comment]
So... If Japan also reports the data for China, China can become a part of Japan?

**Comment by TobyOoO** [comment]
HK SAR's statistics reported by China according to @AndroidDev77 is not accurate and should not be regarded as a reason to enlist Hong Kong under China.

1. Standard of case confirmation is different.
Mainland China has changed the standard of case recongnition twice in the past two months; whereas situations in Hong Kong are still relatively manageable.

2. Data source is second-handed and not up-to-date.
According to @AndroidDev77 's data, 129 cases are reported in HK [1] up to 2020/3/11; but the government of HK has already reported details of the 130th case on 2020/3/11 [2].

[1] http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml
[2] https://www.news.gov.hk/eng/2020/03/20200311/20200311_220655_377.html

**Comment by AndroidDev77** [comment]
My point is that this data is compiled by scripts and is meant only for their visualization tool. Medical and government officials would pull from HK's dataset [1]. This gives them much more data including age, sex, current location, and current status of the patient. 

[1] https://chp-dashboard.geodata.gov.hk/covid-19/zh.html

**Comment by ShawTim** [comment]
> My point is that this data is compiled by scripts and is meant only for their visualization tool. Medical and government officials would pull from HK's dataset [1]. This gives them much more data including age, sex, current location, and current status of the patient.
> 
> [1] https://chp-dashboard.geodata.gov.hk/covid-19/zh.html

- same data source (actually it's not) doesnt mean @CSSEGISandData should put them together
- HK is separated from US State Gov for travel advisory:
https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/hong-kong-travel-advisory.html

Merging HK into China doesnt help, instead it confuses ppl and put them into threats.
data is here for helping us to prevent virus spread. If @CSSEGISandData merges HK data into China, then how should US State Gov gives advisories? What supports them to give Level2 on HK while Level4 on China?

**Comment by wearehongkong-2019** [comment]
The sudden change in coding rules messes with our codes too.

Please, do the right thing, list Hong Kong as a separate entity and use the official data given by the Hong Kong government, not the Chinese government. Hong Kong's medical system is independent from China.

Available data here: [https://data.gov.hk/en-data/dataset/hk-dh-chpsebcddr-novel-infectious-agent](url)
