### ISSUE TITLE
Covid 19 Indonesia, 0 cases (wrong)

### ISSUE THREAD

**Issue by Wiwidz4737** [CSSEGISandData/COVID-19#5337]
Why Indonesia covid 19 Cases 0 for 3 days, if u want the information of Indonesia I tell it, so in February 1 the new cases 16.021, and February 2 the new cases 17.895, and February 3 the new cases 27.197

**Comment by andrew-susanto** [comment]
Indonesia just updated the COVID-19 official website, most probably it breaks the data scraper. New API data source https://data.covid19.go.id/public/api/update.json

**Comment by Wiwidz4737** [comment]
Okay

**Comment by Wiwidz4737** [comment]
Positif mean positive
Sembuh = recovery
Meninggal = dead

**Comment by CSSEGISandData** [comment]
Thank you, this issue has been resolved.
