### ISSUE TITLE
Mainland China time_series_19-covid-Confirmed.csv is missing on 3/11/20

### ISSUE THREAD

**Issue by kechan** [CSSEGISandData/COVID-19#534]

**Comment by mainadwitiya** [comment]
exactly my whole web-app is messed up now

**Comment by rks125** [comment]
It's not missing.  They just changed the name from "Mainland China" to "China".  I don't get why data sets are changing the structure over the past 2 days.. I recommend using Lat/Long for consistency (do a lookup based on Lat/Long)

**Comment by mainadwitiya** [comment]
Alright thanx

**Comment by FAGundum** [comment]
@mainadwitiya , the 03/11/2020 data for China is available at the very end of the file, where the country name is called China instead of Mainland China

**Comment by mainadwitiya** [comment]
@FAGundum thanx I just saw it but still the timeseries is not updated for previous dates, it's messed up right now, the admins have notified that they are working on the dataset

**Comment by kechan** [comment]
The file time_series_19-covid-Confirmed.csv and others seemed updated. It is now just "China" (without mainland). It seems they roll Hong Kong into it, but kept Taiwan as a country with an asterisks. I am not sure if this is the final state of their fix. I should have kept a backup as a sanity check on if the previous dates are correct.

But just to see if someone can sanity if this looks right. I did a semilogy plot of a few countries and attached here.
![Screen Shot 2020-03-12 at 3 06 11 AM](https://user-images.githubusercontent.com/122762/76496166-ce332700-640e-11ea-8083-77ca879c2f94.png)
