### ISSUE TITLE
Total cases in Indonesia is incorrect, 

### ISSUE THREAD

**Issue by Wiwidz4737** [CSSEGISandData/COVID-19#5344]
Total cases:**4.446.694**
Recovery:**4.161.987**
Death:**144.453**
I get that from 
![Screenshot_2022-02-05-11-52-18-99.jpg](https://user-images.githubusercontent.com/99014990/152629180-5d11cd6e-ec24-48e0-8bcf-88c7d243e239.jpg)

**Kasus aktif mean active case or mean the people who still have the virus**

Literally 0 cases
![Screenshot_2022-02-05-11-56-01-15.jpg](https://user-images.githubusercontent.com/99014990/152629336-ac5b66e1-7838-477e-802d-2836dcd6d1ea.jpg)

**Comment by CSSEGISandData** [comment]
Thank you, this issue has been resolved.
