### ISSUE TITLE
Death reported in India on 3/11/2020 due to COVID-19 is not confirmed.

### ISSUE THREAD

**Issue by gokuSSJ95** [CSSEGISandData/COVID-19#535]
According to the data reported for India in the file "COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv", the cause of reported death due to Coronavirus is yet to be confirmed. Link to the news article : https://www.livemint.com/news/india/karnataka-man-dies-could-be-india-s-first-coronavirus-casualty-11583917407064.html

**Comment by imdevskp** [comment]
https://www.mohfw.gov.in/
