### ISSUE TITLE
Poor data curration

### ISSUE THREAD

**Issue by flow4u** [CSSEGISandData/COVID-19#536]
In the latest set i.e. the following:
Russian, but also Russian Federation
China, but also Mainland China
UK, but also United Kingdom
Viet Nam, but also Vietnam
Replublic of Moldova but also Moldova
Czech Republic but also Chechia
Taiwain*      (with *)
....and many more data curration issues

**Comment by soilstack** [comment]
Don't forget Korea....

This is absurd.

**Comment by danslee** [comment]
The last good commit is 473681f .
