### ISSUE TITLE
Update cases in Indonesia

### ISSUE THREAD

**Issue by Wiwidz4737** [CSSEGISandData/COVID-19#5362]
Positive:+37.492
Death:+83
Recovered:+10.708

**Comment by CSSEGISandData** [comment]
Thank you. This issue has been resolved.

**Comment by Wiwidz4737** [comment]
I will tell the update covid 19 everyday because Indonesia cases is 0

---------- Forwarded message ---------
Dari: Wiracle ***@***.***>
Date: Min, 13 Feb 2022 13.56
Subject: Re: [CSSEGISandData/COVID-19] Update cases in Indonesia (Issue
#5362)
To: CSSEGISandData/COVID-19 <
***@***.***>


Why it still 0 cases in 12 february

Pada tanggal Sab, 12 Feb 2022 01.20, CSSEGISandData <
***@***.***> menulis:

**Comment by Wiwidz4737** [comment]
Covid 19 Indonesia 0 cases again

**Comment by Wiwidz4737** [comment]
Update covid 19 Indonesia New record again
