### ISSUE TITLE
28 Day - Data discrepancy between map and summary

### ISSUE THREAD

**Issue by patmolloy** [CSSEGISandData/COVID-19#5365]
![image](https://user-images.githubusercontent.com/4441625/153094507-f3dc5359-e54c-4d20-ba22-af0471f52063.png)

The UK Data here differs - have not checked others.

**Comment by CSSEGISandData** [comment]
Thank you for your question. In the above provided images, you are comparing the admin level 0 location of the United Kingdom and the admin level 1 location of England, United Kingdom. The admin level 0 locations includes other admin level 1 locations within the United Kingdom such as Scotland, Wales, and Northern Ireland, hence the discrepancy.

**Comment by patmolloy** [comment]
Sorry, my bad!
