### ISSUE TITLE
What is the source for Syria cases and deaths?

### ISSUE THREAD

**Issue by ckrf** [CSSEGISandData/COVID-19#5370]
The README.md does not mention any data sources for Syria:
> ...
> Switzerland:
> - Federal Office Of Public Health: https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international.html
> - Open Government Data Reported By The Swiss Cantons: https://github.com/openZH/covid_19
>
> Taiwan:
> - CDC: https://sites.google.com/cdc.gov.tw/2019ncov/taiwan?authuser=0
>
> ...

What sources do you use for cases and deaths in Syria? Apologies if this is already available - I was not able to find it.

Thanks for the herculean work!

**Comment by CSSEGISandData** [comment]
Thank you for your question - our data will come from either the World Health Organization or Worldometers.info, dependent on which source is most up-to-date.
