### ISSUE TITLE
Indonesia New cases in 9 February wrong

### ISSUE THREAD

**Issue by Wiwidz4737** [CSSEGISandData/COVID-19#5371]
It's not 0 but it's 46.843
And the death too, it's not 0 but it's 65

**Comment by Wiwidz4737** [comment]
10 February wrong too

Pada tanggal Jum, 11 Feb 2022 11.39, CSSEGISandData <
***@***.***> menulis:

**Comment by CSSEGISandData** [comment]
Thank you. This issue has been resolved.

**Comment by Wiwidz4737** [comment]
Update covid 19 Indonesia 12 February

**Comment by Wiwidz4737** [comment]
Update covid 19 Indonesia 13 February

**Comment by Wiwidz4737** [comment]
Covid 19 Indonesia 0 cases again

**Comment by Wiwidz4737** [comment]
New record for Indonesia cases !!!!

**Comment by Wiwidz4737** [comment]
Update covid 19 Indonesia 17 february

**Comment by Wiwidz4737** [comment]
Indonesia🔽
