### ISSUE TITLE
Pointless

### ISSUE THREAD

**Issue by iphorde** [CSSEGISandData/COVID-19#538]
This data set is pointless now.

**Comment by Tumne** [comment]
Not so, it's still relevant to track this kind of data visually even if it quickly becomes outdated. As a matter of fact, it's important to keep building and updating the data set

**Comment by iphorde** [comment]
Really? The data isn't valid. Cruise ship passengers have been counted multiple times, county and states don't reconcile. Right. This database is not accurate. Don't make predictions off of it, because they will be wrong.

**Comment by Bost** [comment]
> This data set is pointless now.

Yea, we have data set managed by a bunch of... well by a bunch of people who don't know how to manage data. 
And we have a virus which killed some `((4.6×10^3)÷(7.7×10^9))×100 <= 0.00006 %` of population. In total.
So what? Who cares? The number ob deaths only for TODAY is `162×10^3` and more importantly: newborns `67×10^3`. So what? Don't panic!
