### ISSUE TITLE
Taiwan is a province of CHINA

### ISSUE THREAD

**Issue by CarberryChai** [CSSEGISandData/COVID-19#539]
台独不得好死！

**Comment by small90214** [comment]
Hi Taiwan No. 1

**Comment by u8906250** [comment]
Taiwan No. 1

**Comment by avenirmello** [comment]
Stop being nonsense, China only rapes Taiwan in International Organizations, China has totally no control over what happens in Taiwan

**Comment by SamJheng** [comment]
sorry! china dog back country and kiss your president dick.

**Comment by duncanhsieh** [comment]
> 台独不得好死！

厂厂

Taiwan need not be independent, because R.O.C. independence in 1911.
But P.R.C. independent of R.O.C. in 1949.

You have to rebuild the Chinese history.

Taiwan doesn't need to care about Chinese claims, and Taiwan will not interfere in P.R.C.'s internal affairs.

**Comment by B03901108** [comment]
中共匪類生不如死：）

**Comment by lung2008123** [comment]
No, China is a occupied territory by evil communist party, so called CCP and CRP.

Taiwan and Hong Kong shall liberate the mainland China and get rid of communist gems from Chinese.

P.S. This is an international collaboration, please speck in English even if you're not good at it.

**Comment by andrewintw** [comment]
No, Taiwan actually is not part of China. Does China really govern Taiwan? Do Taiwan people pay any tax to China? Does Taiwan use the same constitution with China? Does Taiwan use the same currency-codes with China? All the answer is NO. China people always like to deceive themselves.

**Comment by Eorlingas** [comment]
导弹就是真理，瑟瑟发抖吧台蛙

**Comment by duncanhsieh** [comment]
@Eorlingas 聽你在狗吠，對耶，你的 avatar 真的是狗

**Comment by u8906250** [comment]
Errrrrrrr 真理能不能射準一點??? 演習四發射到哪裡大家都看到了

**Comment by Eorlingas** [comment]
@u8906250 你是在说打中自己家渔船的“熊三”吗？？可真狠啊，对自己人都下狠手

**Comment by Eorlingas** [comment]
@duncanhsieh 抓紧时间去买红旗吧，别来不及了。哦哦对了，台蛙没钱买红旗。

**Comment by duncanhsieh** [comment]
> @duncanhsieh 抓紧时间去买红旗吧，别来不及了。哦哦对了，台蛙没钱买红旗。

我只聽到汪汪汪

**Comment by Eorlingas** [comment]
@duncanhsieh 哇哇哇哇哇哇哇哇哇呱呱呱呱呱呱

**Comment by CarberryChai** [comment]
> > @duncanhsieh 抓紧时间去买红旗吧，别来不及了。哦哦对了，台蛙没钱买红旗。
> 
> 我只聽到汪汪汪

@duncanhsieh 台蛙没见过世面，做美国的狗不是那么好当的！台湾岛的地理位置对于大陆来说至关重要，想独立？想都不用想！大陆的经济与军事实力碾压蛙岛简直易如反掌！武统台湾之时，就是杀光你们这些台独分子之日！

**Comment by duncanhsieh** [comment]
> > > @duncanhsieh 抓紧时间去买红旗吧，别来不及了。哦哦对了，台蛙没钱买红旗。
> > 
> > 
> > 我只聽到汪汪汪
> 
> @duncanhsieh 台蛙没见过世面，做美国的狗不是那么好当的！台湾岛的地理位置对于大陆来说至关重要，想独立？想都不用想！大陆的经济与军事实力碾压蛙岛简直易如反掌！武统台湾之时，就是杀光你们这些台独分子之日！

@CarberryChai 呵呵，又來一隻狗，繼續吠吧，我我繼續聽你汪汪汪。這些廢話了無新意，早就已經聽膩了。

**Comment by u8906250** [comment]
@duncanhsieh 說真的看到這一代小粉紅只會台蛙台蛙呱呱叫的素質我真的放心很多

**Comment by duncanhsieh** [comment]
> @duncanhsieh 說真的看到這一代小粉紅只會台蛙台蛙呱呱叫的素質我真的放心很多

@u8906250 其實他們無論是翻牆或是人在國外，在自由世界討論政治就是犯罪。我剛剛還不小心請他們說自己的觀點，根本是引誘犯罪。
他們只能用貓、狗代替自己的形象，避免出事拖累家庭誅九族，除了吠叫之外，一點自己的觀點都不能有，可憐呀。

**Comment by Eorlingas** [comment]
> > > @duncanhsieh 抓紧时间去买红旗吧，别来不及了。哦哦对了，台蛙没钱买红旗。
> > 
> > 
> > 我只聽到汪汪汪
> 
> @duncanhsieh 台蛙没见过世面，做美国的狗不是那么好当的！台湾岛的地理位置对于大陆来说至关重要，想独立？想都不用想！大陆的经济与军事实力碾压蛙岛简直易如反掌！武统台湾之时，就是杀光你们这些台独分子之日！

他们真的好无知啊，以前以为他们是自欺欺人，后来发现他们是真的被美国宣传的什么是真实的都不知道了，美国佬还是厉害啊，不用建墙就能洗脑这么彻底。

**Comment by duncanhsieh** [comment]
> > > > @duncanhsieh 抓紧时间去买红旗吧，别来不及了。哦哦对了，台蛙没钱买红旗。
> > > 
> > > 
> > > 我只聽到汪汪汪
> > 
> > 
> > @duncanhsieh 台蛙没见过世面，做美国的狗不是那么好当的！台湾岛的地理位置对于大陆来说至关重要，想独立？想都不用想！大陆的经济与军事实力碾压蛙岛简直易如反掌！武统台湾之时，就是杀光你们这些台独分子之日！
> 
> 他们真的好无知啊，以前以为他们是自欺欺人，后来发现他们是真的被美国宣传的什么是真实的都不知道了，美国佬还是厉害啊，不用建墙就能洗脑这么彻底。

zzz
