### ISSUE TITLE
COVID-19 cases for Hong Kong shown here are way less than the official sources

### ISSUE THREAD

**Issue by sfa16055** [CSSEGISandData/COVID-19#5392]
(in Feb 2022)

e.g.:
Feb 13 2022:-
- Official sources: **1,347** cases
- Here: **327** cases

**Comment by ANTICOLD** [comment]
Maybe they run their script in the middle of each day instead of at the end of them...

**Comment by jonathanykh** [comment]
The webpage you linked is not accessible anymore.
The government in HK is swamped with dealing with the cases and I don't think they will reply to you anytime soon, but still we need to keep the reporting figures correct right?
Here's the proper link that might help you fetch the correct Confirmed Cases data everyday:
https://www.chp.gov.hk/en/features/102997.html


> Thank you for raising. The discrepancy appears to be due to the Hong Kong dashboard (https://www.chp.gov.hk/en/features/102465.html) adding the metric "Tested Positive". We match the "Confirmed" count. We have reached out to the managers of the dashboard to a) obtain clarity for the difference between "Tested Positive" and "Confirmed" and b) obtain historical data to correct our time series in the instance that the "tested positive" metric is consistent with our definition of probable cases.

**Comment by jonathanykh** [comment]
Any updates?

**Comment by CSSEGISandData** [comment]
See #5478.
