### ISSUE TITLE
Change in Polish reporting scheme

### ISSUE THREAD

**Issue by jbracher** [CSSEGISandData/COVID-19#5399]
Dear JHU-CSSE team, we would like to bring to your attention a change in the way COVID case numbers are being reported in Poland (in these files: https://arcgis.com/sharing/rest/content/items/e16df1fa98c2452783ec10b0aea4b341/data). Until 8 February, only first infections were counted (in a column called `liczba_przypadkow`). Now there are three different columns:

1. `liczba_nowych_zakazen` is detected cases EXCLUDING reinfections = the same as `liczba_przypadkow` before 8 February
2. `liczba_ponownych_zakazen` is detected reinfections - this has not been reported before 8 February
3. `liczba_wszystkich_zakazen` is detected cases INCLUDING detected reinfections, i.e. `liczba_nowych_zakazen` + `liczba_ponownych_zakazen`

The JHU data currently seem to contain the data from the `liczba_nowych_zakazen` column, i.e. without re-infections. The numbers used currently are consistent with those used historically, but we feel like at this stage cases including re-infections may be a more meaningful measure. We have also noticed some confusion among colleagues in Poland due to the resulting discrepancy to official Polish data (specifically with respect to the European COVID-19 Forecast Hub  https://covid19forecasthub.eu/ which uses JHU data). We noticed that eg, for the UK a switch to cases including reinfections has been made in the past (https://github.com/CSSEGISandData/COVID-19/issues/5310).

We would be very happy to hear your thoughts on this. Thanks a lot in advance,

Johannes Bracher (Karlsruhe Institute of Technology, Germany) and Marcin Bodych (Wrocław University of Science and Technology, Poland, @eMaerthin)

**Comment by CSSEGISandData** [comment]
Thank you very much for raising this issue. We would like to be able to include this data. Is it available on a front end dashboard? Currently, it is unclear whether the dashboard we are using (https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2) is included reinfections in their totals.

Thank you!

**Comment by jbracher** [comment]
Hi, sorry for the delayed reply. The dashboard shows both cases including and excluding re-infections, see this explanation by @eMaerthin:
<img width="1575" alt="Zrzut ekranu 2022-02-16 o 23 50 25" src="https://user-images.githubusercontent.com/14276689/154445182-05a962e9-7a00-4224-a496-46032c8e0605.png">
I hope this helps.

**Comment by jbracher** [comment]
We moreover wanted to mention that these data are also available at the finer geographical levels of voivodeship powiat.
<img width="1053" alt="Zrzut ekranu 2022-02-16 o 23 58 00" src="https://user-images.githubusercontent.com/14276689/154504843-7f7eadbf-c6a8-4d8f-a463-211a5a5281af.png">

**Comment by CSSEGISandData** [comment]
Closed by #5456. Thank you!!
