### ISSUE TITLE
Hong Kong Should not group under China as educational and academic point of view

### ISSUE THREAD

**Issue by wongfree** [CSSEGISandData/COVID-19#540]
If this project is aim for **educational** and **academic research** purposes, Properly Hong Kong should not group under China!
As you should aware, during the pass 2 months the WuHan Virus spread very differently among CN vs HK. No matter the infection rate or the spreading speed!
Event may be there is a potential inspiration help for slow down the worldwide spreading!

**Comment by darke1891** [comment]
Wuhan should not group under China for the same reason

**Comment by wongfree** [comment]
https://www.washingtonpost.com/world/2020/03/12/hong-kong-learned-sars-can-united-states-learn-hong-kong/

**Comment by elitemaks** [comment]
@wongfree Hi, maybe it would be better to put Hong Kong as "Province/State" under China since it's a Special Administrative Region of China?

**Comment by LungZeno** [comment]
It is like European Union. Hong Kong has border control itself. In the data of this project, the separation of Hong Kong and China is stronger than member countries of EU.  Their movement of goods, movement of capital, movement of services, movement of persons, custom, taxation and market are two different entities. It is not "Province/State".

**Comment by LungZeno** [comment]
@elitemaks Hi! It is like European Union. Hong Kong has border control itself. In this project, the separation of Hong Kong and China is stronger than member countries of EU. Their movement of goods, movement of capital, movement of services, movement of persons, custom, taxation and market are two different entities. It is not "Province/State".

**Comment by wongfree** [comment]
@elitemaks The reason i create this topic is, i hope this project can provide more help than just showing the "number" especially under current situation.
currently already had few articles talking about how HK,TW & SG manage to maintaining the low local infection, but the coverage it's far behind enough i feel.
So as one of the highest traffic platform (I believe) regarding the WuHan Virus, i feel it could / should provide more useful / critical insight to the public. 
p.s I'm HKer i may be biased, but the number from HK i believe it more realistic.

**Comment by elitemaks** [comment]
@LungZeno, @wongfree  I see your point, but this data still need clear geo structuring. HK is not a province/state, but it's a SAR, so it's still some administrative division of China. There is no point in adding a new hierarchy to this data.
Besides, HK has a separate row of data, so what's the problem take and learn this data? What's the difference if it's listed as a country or region?

**Comment by wongfree** [comment]
@elitemaks you're correct, if the reader like you and me had enough technical knowledge, we can dive into the data to dig information. 
But i don't think most of the public have such knowledge level.

**Comment by thomasklwong** [comment]
@elitemaks, using your logic, I believe all the cases in Crimea should be grouped under Russia and not the Ukarine then?

China, Macao and Hong Kong all have separate border and quarantine policies. Engineer and health official can NEVER neglect the geopolitical influence of the data.

**Comment by elitemaks** [comment]
@thomasklwong let's not go into politics. I read it on Wikipedia - "officially the Hong Kong Special Administrative Region of the People's Republic of China". If it's not correct, ok, I may be mistaken.
Basically there is no point in this discussion as I'm not the one who structure this data.

**Comment by thomasklwong** [comment]
@elitemaks, are you saying the Wikipedia is the single source of truth?

I am not accusing you of structuring the data. Instead, what I am very annoyed is how the programmer made careless merge without considering the political consequence.

In this world, there are many politically sensitive areas that a company need to tread the water very carefully. If not, why would [Google Map redraw the border depending on where are you accessing Google Map from?!](Google redraws the borders on maps depending on who’s looking
)

China, Hong Kong and Macau all have their independent health care system. 

[Macau, until very recently, have a strong restriction on the visitors from China.](https://fortune.com/2020/03/15/coronavirus-macau-cases-response/)

Travel ban and quarantine measures in Hong Kong is also different from the rest of China and also Macau. As highlight by other commenters in other tickets.

If Hong Kong and Macao cannot be treated differently, why would Hong Kong and Macau be allocated the country calling code 852 and 853 respectively? While China is allocated a separate 86? Or why or Macau is allocated a ccTLD .mo, Hong Kong to .hk and China .cn? How about the ISO 3166 country code? Again, the three regions are separate, MO/MAC/446, HK/HKG/344 and CN/CHN/156.

Remember, my dear, what this list does is documenting part of the human history, trying to remove politic away from it is futile.
