### ISSUE TITLE
Wrong cases for 14/02/2022 in Indonesia

### ISSUE THREAD

**Issue by Jery12345** [CSSEGISandData/COVID-19#5404]
The cases for 14th february in indonesia is supposed to be 36,501 and not 0 
And the cases for 15th february in indonesia is 57,049

**Comment by Wiwidz4737** [comment]
That right

**Comment by Wiwidz4737** [comment]
Today indonesia new record 64K

**Comment by CSSEGISandData** [comment]
Patched in #5415
