### ISSUE TITLE
USA States Cumulative instead of broken up by city

### ISSUE THREAD

**Issue by dbensonmsop** [CSSEGISandData/COVID-19#541]
the map used to show # of cases by city in the USA. Now you can only track by state as a whole. you can no longer see the epicenters in each state.

**Comment by dbensonmsop** [comment]
![](https://www.syracuse.com/resizer/hXPBNI29bvDW16LI8legry9Nj3w=/1280x0/smart/arc-anglerfish-arc2-prod-advancelocal.s3.amazonaws.com/public/3QYQ72UE7FGODPJTMCQAD63BA4.png)


this is what the map used to look like

**Comment by colinmegill** [comment]
Generally, I agree with this, and would advocate for each CSV to have: 

Country total
State total
City total

And if State and City are not available, that's ok, but the aggregates are still there to reference.

**Comment by joetynan11** [comment]
I don't think it matters what granularity you want to show on the map.  The most important part should be if I sum up all rows of data = US the total should agree. 

Currently, the confirmed cases for 11 March (time series) are 2384, when they should be 1281

**Comment by uncovery** [comment]
> Currently, the confirmed cases for 11 March (time series) are 2384, when they should be 1281
Exactly! How are the cases for the USA calculated to give the overall of 1281 as on the map?

**Comment by BMPMS** [comment]
There is a major issue here with the new US states getting cases out of nowhere:

For example Washington DC, New York, California.  They jump from 0 to 267, 173 and 144 respectively on 10th March which makes it impossible to track the increase over time.

Moreover, the origin data (ie broken up into states) is still in the dataset.

**Comment by BMPMS** [comment]
Also, they don't match up...

Total for all Region, States in California (ie _Region_, CA) = 101 on 10th March
Total for California = 144?

You need a row for EITHER the state OR the regions within the states, you can't have both..

**Comment by eilifm** [comment]
@CSSEGISandData, who inside Johns Hopkins can sort this one out? Can the community help?
