### ISSUE TITLE
Bad data for Spain series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5412]
Hi Team,

We have observed that data published for Spain on the file [time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) for the period 02/03/2022-02/06/2022 are not correct, since it's an accumulative series and the data points released are decreasing.

Could you please check and advise on this?

Thank you.

Regards,

**Comment by CSSEGISandData** [comment]
Patched in #5414
