### ISSUE TITLE
Incorrect COVID data on Hong Kong

### ISSUE THREAD

**Issue by MarioCatty833** [CSSEGISandData/COVID-19#5425]
Data shown on Google that there are around 1000 cases added per day in Hong Kong, when there have been 6000-7000 confirmed cases these few days and upward to [13000 cases](https://www.scmp.com/news/hong-kong/health-environment/article/3167660/hong-kong-facing-record-7000-coronavirus-cases) inclusive of preliminary positives. The Hong Kong government webpage reports different numbers than those released in live press conferences by government officials. Various news outlets such as South China Morning Post offer reliable statistics that come from the Department of Health representative himself. Please update the figures and prevent misinformation.

**Comment by MarioCatty833** [comment]
For official statistics, find - chp.gov.hk - Latest situation of local situation of COVID-19

**Comment by CSSEGISandData** [comment]
Please see our response to #5392. We have not yet received a response from the Ministry of Health.
