### ISSUE TITLE
New Zealand stats incorrect for 12/13 Feb 2022

### ISSUE THREAD

**Issue by Nixinova** [CSSEGISandData/COVID-19#5426]
The data for 12 Feb has been merged with the 13 Feb data which is annoying as it misrepresents the start of our omicron outbreak.

<img width=400px src=https://user-images.githubusercontent.com/42429413/154822803-b8cfb5e5-ac5d-4cb7-b133-a2b10dc7a96e.png>

**Comment by CSSEGISandData** [comment]
Hello,

New Zealand did not post any new cases on February 13th (NZ time) which resulted in no new data being reported in our data repository on February 12th, 2022. Please see [wayback machine screenshots](https://web.archive.org/web/20220213233843/https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-current-cases) on February 13 (NZ time).
