### ISSUE TITLE
Washington state case numbers are suspicious for the past 8 days

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#5430]
I have read that the state of Washington was changing to just reporting data on three days out of every week, but the numbers you have for the past week for Washington are mostly negative new cases, and a net loss of 1343 cases from the running total. Is the problem in CSSEGISandData, the state of Washington, or both?

**Comment by CSSEGISandData** [comment]
Thank you for the raising this issue. Please see response in #5437 where we will consolidate responses for this specific issue.
