### ISSUE TITLE
Poland daily confirmed cases discrepancy wrt to other sources  

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5436]
For Poland, As per the [JHU](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) daily confirmed cases on the dates Feb 15th 2022 and Feb 16th 2022, were 19,847 and 25,670 whereas :
As per:
 [WHO](https://covid19.who.int/region/euro/country/pl), cases were 22243 & 28,837 
 [Corona Tracker](https://www.coronatracker.com/country/poland/), cases were 22,267 & 28,462
They both are showing approx differences of 2,396 & 3,167.
Please look into this as it seems the data in the JHU is incorrect.

**Comment by CSSEGISandData** [comment]
See #5456.
