### ISSUE TITLE
Suspicious data for China series - Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5443]
Hi Team,

We have observed that the value published for China on the file "[time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)" for the period 02/21/2022 seems extreme in comparison with other historical values.
Could you please confirm that the value is correct and provide the reason for such a big jump?

Thank you in advance

Best regards,
Mariia Podacheva
Data Analyst

**Comment by CSSEGISandData** [comment]
Thank you, this issue has been resolved.
