### ISSUE TITLE
Bad data for France series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5444]
Hi Team,

We have observed that data published for France on the file [time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) for the period 02/21/2022 are not correct, since it's an accumulative series and the data point released are decreasing.

Could you please check and advise on this?

Thank you.

Best regards,
Mariia Podacheva
Data Analyst

**Comment by DataOps-epam** [comment]
Hi Team,

Could you please advise if you have any updates regarding the issue?

Thank you in advance.

Best regards,
Mariia Podacheva
Data Analyst

**Comment by DataOps-epam** [comment]
Hello Team,

Could you please advise if you had a chance to look at the issue above?

Thank you in advance.

**Comment by CSSEGISandData** [comment]
Patched in #5494 - apologies for delay.
