### ISSUE TITLE
Discrepancy in UK cases wrt OW on 19th and 20th Feb

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5446]
* New cases for UK as per JHU on 19th Feb, 2022 and 20th Feb, 2022 are 34,011 and 25,536 respectively.
* Since the data is collected from [https://coronavirus.data.gov.uk](https://coronavirus.data.gov.uk/details/cases?areaType=overview%26areaName=United%20Kingdom#card-cases_by_date_reported), as per which, new cases on 19th and 20th Feb, 2022 are 39,693 and 31,170 respectively. 
* Although the number on 21th is 48820 as per JHU and 38409 as per OW, looks like this was done to balance the accumulative cases, but should be added to respective dates.

These seems to be discrepancy in data w.r.t to the official source, Please look into this

**Comment by CSSEGISandData** [comment]
Thank you. This has been patched.
