### ISSUE TITLE
Bad data for Alabama Convington Confirmed cases

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#5450]
The latest data for 1/25/2022 is shown as 85607, but the previous day data is reported as 8579. Can you take a look?

**Comment by RuijingZ** [comment]
> 

Hi, the high number still shows for 01/25/2022, which is not normal. Is there any reason? The confirmed cases are even larger than the population in that county.

**Comment by CSSEGISandData** [comment]
Patched in #5462.
