### ISSUE TITLE
France: Incorrect data of 22nd Feb. 

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5460]
For France, daily death counts for 22nd of February, as per JHU is 4577, i.e. difference between [21st February](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/02-21-2022.csv ) and [22nd February](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/02-22-2022.csv) cases. 

When checked on other sources for daily death counts, data fluctuates :
[WHO](https://covid19.who.int/region/euro/country/fr) is 164
[Corona Tracker](https://www.coronatracker.com/country/france/)  is 682

Looks like there is a discrepancy in the data on Github. Please look into this.

**Comment by CSSEGISandData** [comment]
Patched in #5494.
