### ISSUE TITLE
Suspicious data for China series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5469]
Hi Team,

We have observed that the value published for China on the file "[time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)" for the period 02/24/2022 seems extreme in comparison with other historical values.
Could you please confirm that the value is correct and provide the reason for such a big jump?

Thank you in advance

Best regards,
Mariia Podacheva
Data Analyst

**Comment by CSSEGISandData** [comment]
Thank you. These are due to a recent increase in deaths in the Hong Kong SAR, China. Please see [their dashboard](https://www.chp.gov.hk/en/features/102465.html).
