### ISSUE TITLE
Hong Kong data is not correct

### ISSUE THREAD

**Issue by lhkjacky** [CSSEGISandData/COVID-19#5472]
According to HK Government the new Covid case numbers are:
21/2  7533
22/2  6211
23/2  8674
24/2  8798
25/2  10010
26/2  17063
27/2  26026
28/2  34466

[https://chp-dashboard.geodata.gov.hk/covid-19/web/main2.html?lang=en](https://chp-dashboard.geodata.gov.hk/covid-19/web/main2.html?lang=en)

However, in owid-covid-data.csv the number are much much lower
21/2  3570
22/2  2662
23/2  0
24/2  6352
25/2  3840
26/2  5494
27/2  n/a

Hopefully you will fix it. 
Thank you

**Comment by beansrowning** [comment]
See #5392

**Comment by CSSEGISandData** [comment]
See #5478.
