### ISSUE TITLE
Irregular Update Schedules should now include Saskatchewan, Canada

### ISSUE THREAD

**Issue by dhhepting** [CSSEGISandData/COVID-19#5477]
The data from the province of Saskatchewan, Canada has gone from daily updates to weekly updates, as indicated at this web page: https://www.saskatchewan.ca/government/health-care-administration-and-provider-resources/treatment-procedures-and-guidelines/emerging-public-health-issues/2019-novel-coronavirus/cases-and-risk-of-covid-19-in-saskatchewan

There have been 3 weekly reports to date, released on Thursdays covering the week (Sun-Sat) previous.

* report for Jan. 30 to Feb. 5, published on Feb. 10 [(link to report page)](https://publications.saskatchewan.ca/#/products/116598) [(link to pdf)](https://publications.saskatchewan.ca/api/v1/products/116598/formats/133268/download)
* report for Feb. 6 to Feb. 12, published on Feb. 17 [(link to report page)](https://publications.saskatchewan.ca/#/products/116760) [(link to pdf)](https://publications.saskatchewan.ca/api/v1/products/116760/formats/133554/download)
* report for Feb. 13 to Feb. 19, published on Feb. 24 [(link to report page)](https://publications.saskatchewan.ca/#/products/116896) [(link to pdf)](https://publications.saskatchewan.ca/api/v1/products/116896/formats/133771/download)

The first of these reports overlaps with previously published daily reports. The reports for the weeks ending Feb. 12 and Feb. 19 contain new data.

* Feb. 6 - Feb. 12:  2,522  new cases; 42 newly reported deaths
* Feb. 13 - Feb. 19: 1,407 new cases;  37 newly reported deaths

Further weekly reports should be available at  https://www.saskatchewan.ca/government/health-care-administration-and-provider-resources/treatment-procedures-and-guidelines/emerging-public-health-issues/2019-novel-coronavirus/cases-and-risk-of-covid-19-in-saskatchewan with the next one published on  Mar. 3

Please let me know of any questions or concerns.

Best regards,
Daryl

**Comment by dhhepting** [comment]
- report for Feb. 20 to Feb. 26, published on Mar. 3 [(link to report page)](https://publications.saskatchewan.ca/#/products/116943) [(link to pdf)](https://publications.saskatchewan.ca/api/v1/products/116943/formats/133890/download)
- Feb. 20 - Feb. 26: 1,102 new cases; 44 newly reported deaths

**Comment by CSSEGISandData** [comment]
Thank you - we've updated our README to reflect the reporting schedules of Canada's provinces.
