### ISSUE TITLE
Renamed Czech republic to Czechia - inconsistent data

### ISSUE THREAD

**Issue by smisek1** [CSSEGISandData/COVID-19#549]
In last daily reports ("\csse_covid_19_data\csse_covid_19_daily_reports\03-11-2020.csv") was renamed Czech republic to Czechia.
Name of state  is "Czech republic" in other daily reports.
 => the data is inconsistent.

**Comment by Wikunia** [comment]
See #504 they decided now to use WHO names

**Comment by JiPiBi** [comment]
@Wikunia 
The issue is for people using daily reports and not time series, the previous daily reports remain as they were (very clear in the pull requests)

**Comment by smisek1** [comment]
Is it possible to rename Czech republic  to  Czechia in old daily reports?

**Comment by Bost** [comment]
> Is it possible to rename Czech republic to Czechia in old daily reports?

You must be joking! :(
Or, are you new here?
NEVER EVER CHANGE THE FORMAT AND NAMING CONVENTIONS OF THE DATA YOU MANAGE!
#238

**Comment by smisek1** [comment]
So, I don't understand why naming of data was change. (Czech republic to Czechia)
It will be understandable if there was some key.

**Comment by Bost** [comment]
> So, I don't understand why naming of data was change. (Czech republic to Czechia)
> It will be understandable if there was some key.

Because they're a good-natured people not anticipating the consequences of their deeds. And for what it's worth - slow or not willing to learn.

**Comment by CSSEGISandData** [comment]
please see issue #504
