### ISSUE TITLE
Mainland China , China duplicate entries

### ISSUE THREAD

**Issue by apogs** [CSSEGISandData/COVID-19#551]
As of 12th of March, the time series CSV have duplicates records for the same province-country tuples, where the same Chinese province is listed twice, one with country as Mainland China, the other with China. Resulting in duplicate counts.

**Comment by Wikunia** [comment]
See #504 now it should stay China. Btw in the csv file there is no Mainland China anymore

**Comment by JiPiBi** [comment]
@apogs my time series pull doesnt show what you say , No more mainland china only china (extraction made 1 hour ago)

**Comment by apogs** [comment]
Yes it has been fixed already few hours ago. Thanks!
