### ISSUE TITLE
Mauritius confirmed cases doubled on March 07 and March 08

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#5511]
Hello,

Maritius confirmed cases went over 169k on March 07 compared to 70k on March 6. Also, the number does not change during the whole February. Could you confirm this large increase? Also, the number does not change during the whole February. May I ask if it is able to back fill the data?

**Comment by CSSEGISandData** [comment]
This has been patched using WHO data in #5516.
