### ISSUE TITLE
Large jump in New Zealand - Number Of Deaths 03/10/2021

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5520]
Hi team,

Could you please advise if you have any info regarding data change in series below for 03/10/2021:

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

This value seems extreme in comparison with other historical values.

Thank you

Regards,

**Comment by CSSEGISandData** [comment]
Thank you. This has been verified using data from the World Health Organization.
