### ISSUE TITLE
China Number Of Confirmed Cases extreme revision

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5545]
Dear JHU,
Could you please check your time series "China: Number Of Confirmed Cases" here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

With latest update we got extreme revision for 2022-02-26 - 2022-03-17 period.
Could you please advise on this.
Thank you.

#CHN.CONFIRMED.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Please see #5546.
