### ISSUE TITLE
Case counts for China – should they include confirmed but asymptomatic infections?

### ISSUE THREAD

**Issue by HannahRitchie** [CSSEGISandData/COVID-19#5559]
Hello,

Cross-checking the case count figures from China: it seems they report both confirmed symptomatic and asymptomatic cases separately in their daily reports: https://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm

At the moment only symptomatic cases seem to be counted in JHU data. However, it seems (from reading these reports, which are not 100 clear) that the asymptomatic cases are actually confirmed via testing.

Would it be more appropriate and consistent to also include confirmed asymptomatic cases in the total?

Thank you.

**Comment by CSSEGISandData** [comment]
Addressed in #5579.
