### ISSUE TITLE
France: Under reported cases on 24th and 25th Mar

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5567]
For France, daily cases on the dates Mar 24th 2022 and Mar 25th 2022
 
As per the [JHU](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) were 140141 and 139194.

Whereas on other sources:
On the 24th March:
[WHO](https://covid19.who.int/region/euro/country/fr), New daily cases = 144951
[Worldometer](https://www.worldometers.info/coronavirus/country/france/), New daily cases = 148635
On the 25th March:
[WHO](https://covid19.who.int/region/euro/country/fr), New daily cases = 148243
[Worldometer](https://www.worldometers.info/coronavirus/country/france/), New daily cases = 143571

**Comment by CSSEGISandData** [comment]
Thank you for your enquiry. Can you please clarify how you calculated the numbers in this issue? Our daily cases for France, France were 65331 on February 23, 2022, 66700 on February 24, 2022, and 58120 on February 25, 2022.

**Comment by mkhanka** [comment]
Hi, 
Apologies for the incorrect month, updated it to March.

Also if we consider that WHO and Worldometer calculates including provenance data,  that count for JHU on 24th Mar comes to 140528 & for 25th Mar comes to 143619, which is far from what WHO or Worldometer are projecting

**Comment by CSSEGISandData** [comment]
Thank you. We would kindly point out that our reporting matches the present reporting of the French source: https://www.santepubliquefrance.fr/dossiers/coronavirus-covid-19/coronavirus-chiffres-cles-et-evolution-de-la-covid-19-en-france-et-dans-le-monde. WHO is reporting higher daily cases than this source for reasons that are unclear to us.
