### ISSUE TITLE
[South Africa] Discrepancy in new cases count and death count from 19th to 25th March

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5568]
New cases count and death count from 19th to 25th March for South Africa are different on [JHU](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) and JHU data source:  [sacoronavirus.co.za](https://sacoronavirus.co.za/category/daily-cases/).

New cases | JHU data source | JHU
-- | -- | --
19th March | 1287 | 2845
20th March | 889 | 889
21st March | 566 | 566
22nd March | 912 | 912
23rd March | 1393 | 0
24th March | 2120 | 3513
25th March | 1560 | 1557

Death | JHU data source | JHU
-- | -- | --
19th March | 11 | 50
20th March | 2 | 2
21st March | 9 | 9
22nd March | 3 | 3
23rd March | 6 | 0
24th March | 33 | 39
25th March | 7 | 7

Please look into this data discrepancy

**Comment by CSSEGISandData** [comment]
Patched in [this commit](https://github.com/CSSEGISandData/COVID-19/commit/dcdf122568639a50ed7832fecbb32289d560ab14).
