### ISSUE TITLE
Suspicious data for Germany series - Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5570]
Hi Team,

We have observed that the value published for Germany on the file "[time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)" for the period 03/29/2022 seems extreme in comparison with other historical values.
Could you please confirm that the value is correct and provide the reason for such a big jump?

Thank you in advance

Best regards,
Mariia

**Comment by c-hera** [comment]
Hi Mariia, 

for about a week, data from 8 states in Germany was not further updated (Niedersachsen to Thueringen, incl. unknown), see [#55
56 ](https://github.com/CSSEGISandData/COVID-19/issues/5556). On 29th, the missing data was dumped for the entire missing period. This most probably caused the jump in numbers you are referring to.

All the best,

Christoph

**Comment by DataOps-epam** [comment]
Hi Christoph,

Thank you so much for the explanation provided.

Best regards,
Mariia
