### ISSUE TITLE
China Aysmptomatic cases

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#5583]
Thanks for adding China's Asymptomatic cases to your published data
This is to confirm that the Asymptomatic cases have only been compiled to the "Unknown" Province_State. and not to each individual Province/City.
How would you like the backdated Province/City data formatted?  Total Cum or separate columns.

Please contact me directly

**Comment by CSSEGISandData** [comment]
This is correct. We have clarified #5579.
