### ISSUE TITLE
Data inconsistencies between dashboard and time_series files

### ISSUE THREAD

**Issue by przemyslawpluta** [CSSEGISandData/COVID-19#56]
It appears there are some inconsistencies in terms of data between what [dashboard](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html) shows and what  timeseries csv files record. If you look at:

**2/13/2020** the graph says `59,8k` cases in Mainland China while [who_covid_19_sit_rep_time_series.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv#L3) indicates `46550` and [time_series_2019-ncov-Confirmed.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/archived_data/time_series/time_series_2019-ncov-Confirmed.csv) indicates `63841`?

![img1](https://user-images.githubusercontent.com/221250/74568614-49203380-4f70-11ea-9c14-9dcc5508d8fc.png)

**2/11/2020** the graph says `44.3k` cases in Mainland China while [who_covid_19_sit_rep_time_series.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv#L3) indicates `42708` and [time_series_2019-ncov-Confirmed.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/archived_data/time_series/time_series_2019-ncov-Confirmed.csv) indicates `44641`?

![img2](https://user-images.githubusercontent.com/221250/74568721-8ab0de80-4f70-11ea-8e15-941c0447ec5e.png)

**2/10/2020** the graph says `42.3k` cases in Mainland China while [who_covid_19_sit_rep_time_series.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv#L3) indicates `40235` and [time_series_2019-ncov-Confirmed.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/archived_data/time_series/time_series_2019-ncov-Confirmed.csv) indicates `42310`?

![img3](https://user-images.githubusercontent.com/221250/74568794-b5029c00-4f70-11ea-9512-e8f14a613f7b.png)

**2/7/2020** the graph says `34.1k` cases in Mainland China while [who_covid_19_sit_rep_time_series.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv#L3) indicates `31211` and [time_series_2019-ncov-Confirmed.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/archived_data/time_series/time_series_2019-ncov-Confirmed.csv) indicates `34569`?

![img4](https://user-images.githubusercontent.com/221250/74568862-e5e2d100-4f70-11ea-858c-f80a71a7771f.png)

**Comment by dawenx** [comment]
good finding @przemyslawpluta , i'm pretty sure their dashboard is using its own data source which is hosted on ArcGIS online; while those csv files were generated/exported at a particular time. (check out my profile for the dashboard i'm actively working on now, data used for rendering map is shown in a data table.)

**Comment by bicubic** [comment]
After the latest data changes, it seems like the timeseries data is _missing the latest day that it contained yesterday_. And is now lagging even further behind the dashboard. As of right now, the timeseries dataset adds up to 48206 confirmed cases while the dashbaord is indicating 67079.

 @CSSEGISandData could anything be done to improve the latency or harmonise the timeseries dataset with what's presented on the dashboard? This is a pretty huge delta.

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. The time series table and daily case updates are updated every day around 12 AM UTC (7 PM EST). The dashboard is updated real-time. There may be discrepancies between the dashboard and this repository  due to these update times.
