### ISSUE TITLE
Discrepancy in UK's stats WRT to Official data : date range: 29th mar to 1 Apr

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5600]
As per the info here https://github.com/CSSEGISandData/COVID-19, JHU uses [OW](https://coronavirus.data.gov.uk/details/cases) for UK but somehow the data is over reported than what was actually present in the OW.  We can see from the below stats that even 18 hr earlier when there was no stats available for 1st Apr JHU reported  69449, which is at the time of reporting this issue was    45,504. Is there anything I am missing here?

**Number of cases reported by JHU**
29th March: 80656
30th March: 86838
31st March: 74416
1st April:      69449

**Number of cases reported by [OW](https://coronavirus.data.gov.uk/details/cases) at time of reporting this issue:**
29th March:79,704
30th March: 72,818
31st March: 53,428
1st April:      45,504
![image](https://user-images.githubusercontent.com/87356889/161652901-3db77d19-db38-42ed-932a-7660d04a88a9.png)

**Number of cases reported by [OW](https://coronavirus.data.gov.uk/details/cases) ~18 hr earlier from the time of reporting this issue:**
29th March: 77,915
30th March: 63,462
31st March: 29,825
1st April:      Not available
![image](https://user-images.githubusercontent.com/87356889/161653033-cef564ec-5104-4263-aa13-619459a63073.png)

**Comment by mkhanka** [comment]
Also Abov this, there seem to be some data discrepancy WRT other data sources:

[WHO](https://covid19.who.int/region/euro/country/gb) :
29th March : 67,870
30th March: 91,075
31st March: 69,485
1st April: 35,968

[Worldometer:](https://www.worldometers.info/coronavirus/country/uk/)
29th March: 92279
30th March: 77,915
31st March: 63, 462
1st April: 29,825

**Comment by CSSEGISandData** [comment]
Hello,

1) The graphs to which you are referencing are by specimen date. Please compare our data to the data in the section "cases by report date"
2) The column "United Kingdom daily" in the "cases by report date" table is not equal to the differences between consecutive days in the column "United Kingdom total", which is what we are using to calculate our daily totals. If you use that data, you will see it matches what we have reported.
