### ISSUE TITLE
JHU "Past Month" totals high for US

### ISSUE THREAD

**Issue by stanvand** [CSSEGISandData/COVID-19#5609]
For several days at least I find the "Past Month" totals to be high for both cases and deaths, compared to the time_series csv data. These numbers are typically a moving 30-day sum. Has anyone else noticed this? Here is the JHU page:

https://coronavirus.jhu.edu/region/united-states

Thanks

**Comment by CSSEGISandData** [comment]
Hello,

The visualization uses 7-day averages rather than 30-day averages. The aberrant drop in deaths around March 14 is due to revision of MA deaths as addressed in #5529.
