### ISSUE TITLE
US death cases shrinking on weekly basis (from 4.2021-3.2022) - why?

### ISSUE THREAD

**Issue by reinas104** [CSSEGISandData/COVID-19#5614]
Hello, all

I've been dealing with the 'Global Covid Total Death Cases' time-series data for some time now. (THANK YOU!)
The recent time-series, however, shows US total death cases shrinking almost on weekly basis between 6.4.2021-15.3.2022.

A bit of digging suggests that most of the downward adjustment comes from figures announced by Massachusetts, US but I could not search why that was the case. 

Does anyone happen to know the reason behind this?

Very much appreciated. 
Kind regards,

**Comment by CSSEGISandData** [comment]
This has been addressed. Further details in #5615.

**Comment by mdarosa** [comment]
Well #5615 is that secret?
