### ISSUE TITLE
Spain data missing for past week

### ISSUE THREAD

**Issue by eleanorlutz** [CSSEGISandData/COVID-19#5619]
It looks like the J.H.U. data reports 0 new cases or deaths in Spain during the past week. 

However, the government dashboard has a normal [update](https://www.sanidad.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/situacionActual.htm) as of April 8th. 

It seems that the RTVE dashboard listed as the source for Spain in the J.H.U. source list has changed in April to no longer include the case number. Perhaps this is why the scraper is not returning any new information? 

Thank you for your time and attention!

**Comment by CSSEGISandData** [comment]
Thank you Eleanor! This will have patched in #5622.
