### ISSUE TITLE
Bad data for Spain series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5626]
Hi Team,

We have observed that data published for Spain on the file [time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) for the periods 03/29/2022 - 03/31/2022 are not correct, since it's an accumulative series and the data points released are decreasing.

Could you please check and advise on this?

Thank you.

Best regards,
Mariia

**Comment by CSSEGISandData** [comment]
Please see the following data note on the Ministry of Health publication for [March 29](https://www.sanidad.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Actualizacion_586_COVID-19.pdf) which explains the decrease:

"Aragón ha depurado los datos ajustando los fallecidos a casos fallecidos por COVID, por lo que el nº total de fallecidos ha disminuido"
