### ISSUE TITLE
North Carolina case counts do not correspond to NC DHHS

### ISSUE THREAD

**Issue by lojic** [CSSEGISandData/COVID-19#5635]
The case counts for North Carolina differ significantly from:
https://covid19.ncdhhs.gov/dashboard/cases-and-deaths

NC recently went to weekly reporting, but I'm not sure the difference is entirely attributable to the switch to weekly reporting.

**Comment by CSSEGISandData** [comment]
Hello,

Could you be a bit more specific? From a quick look, our current totals for cases and deaths match the NC dashboard (2,634,007 and 23,257, respectively).

**Comment by lojic** [comment]
This may be a problem with NC DHHS.  

The totals may match, but I think the absolute total may have been reduced a few days ago. Considering just Wake County, NC, I see the last value is 290,240, but six days earlier, the value was 290,545. I compute the number of daily cases via the delta of successive days, so the reduction in the absolute total (which theoretically should never happen) combined with the switch to weekly updating, makes the daily numbers garbage for about a week.

**Comment by lojic** [comment]
To clarify further re: what I was referring to with the discrepancy, the daily new cases, extrapolated from this repository's daily totals, is very different than the daily numbers reported on the NC DHHS site on the link I provided. Given you're using the total number of cases instead of the new daily cases, I'm not sure that anything can be done about this.

**Comment by lojic** [comment]
NC DHHS seems to reply via Twitter better than other means, so I asked them if they made a correction here:
https://twitter.com/lojic/status/1513958547251503108

**Comment by CSSEGISandData** [comment]
Thank you for the clarification. The discrepancy is likely due to the "new cases" displayed on the NC DHHS website being by specimen date rather than date of report. We will monitor your twitter thread to see if they post a reason for the reduction in cases.
