### ISSUE TITLE
Canada covid cases need to be fixed and please fix up Canada’s cases

### ISSUE THREAD

**Issue by 807lachlb** [CSSEGISandData/COVID-19#5637]
Quebec covid cases are not updating and need to be fixed and Canada’s as well

**Comment by 807lachlb** [comment]
Please fix up Quebec covid cases and Canada covid cases

**Comment by gauravjoshijo** [comment]
Also there is a discrepancy in 7th, 8th, & 9th Data. As per feed new cases for dates:
7th April, 2022      6019
8th April, 2022       N/A
9th April, 2022     11609

While as per [WHO](https://covid19.who.int/region/amro/country/ca):
7th April, 2022  	 15328
8th April, 2022   	 7779
8th April, 2022    	 529

**Comment by JoyMishu** [comment]
Hello
