### ISSUE TITLE
Stat from French is broken.

### ISSUE THREAD

**Issue by Knackie** [CSSEGISandData/COVID-19#564]
Hi,
U have country French and France, and french is not update.

**Comment by lazd** [comment]
There is a `French Guiana` in the dataset, as well as `France` itself and two territories `St Martin, France`, and `Saint Barthelemy, France`. I see no issues with the data for any of those rows.

I think you should close this issue.

**Comment by JiPiBi** [comment]
Please See #555 :  the issue is a bad aggregation for France

**Comment by JiPiBi** [comment]
@Knackie
 at this moment,  only Martinique remains as a country, the other territories became provinces
