### ISSUE TITLE
[Issue type: Data  updation] Data has not been updated for Spain since 9th April. 

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5656]
As per other sources [WHO](https://covid19.who.int/region/amro/country/ca), [Worldometer](https://www.worldometers.info/coronavirus/country/canada/) and[ Corona Tracker](https://www.coronatracker.com/country/es). There are new death cases on the dates after 9th April, but the same is not visible in the JHU feed where there is no change in the death cases (which is 103104 for all the dates after 9th). 

WHO -     
9th April      54   
10th April    45  
11 th April   39 

Worldometers: 
9th April        79
 10th april 	77
11th April 	76

Please look into it.

**Comment by noeoeoe** [comment]
![Screenshot_20220419-015928~2](https://user-images.githubusercontent.com/103971970/163896603-e8ea3c88-b745-47a3-bdd0-561f11266864.png)

**Comment by CSSEGISandData** [comment]
Thank you, this has been corrected.
