### ISSUE TITLE
Date Format Change?

### ISSUE THREAD

**Issue by th3013a** [CSSEGISandData/COVID-19#5662]
I noticed the dates went from (for example) 1/22/2020 to 1/22/20

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your question. This date format has been our standard for quite some time. Can you please provide the following details which will help us understand if the way we are hosting the data has changed:

- files affected
- Dates where the format first changed (both dates with previous format and new format)
- Software used to download/visualize the change

Thank you!
