### ISSUE TITLE
Scraped New Brunswick dashboard is no longer being updated

### ISSUE THREAD

**Issue by eleanorlutz** [CSSEGISandData/COVID-19#5667]
Hello!

I wanted to let you know that the [New Brunswick dashboard](https://experience.arcgis.com/experience/8eeb9a2052d641c996dba5de8f25a8aa/page/COVID-19-Case-Data/) you're scraping is no longer being updated as of March 29th. Here are some screenshots from the dashboard showing the issue. 

<img width="975" alt="Screen Shot 2022-04-21 at 5 22 59 PM" src="https://user-images.githubusercontent.com/6994487/164554622-e76ec9ef-559e-484c-b021-d4c697889d86.png">
<img width="919" alt="Screen Shot 2022-04-21 at 5 23 20 PM" src="https://user-images.githubusercontent.com/6994487/164554623-2e241ec1-ecc8-4168-9ffa-f34c27d3976a.png">

It looks like the replacement dashboard data matches what is reported in the [main Canada page](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html) you are already scraping, so perhaps migrating New Brunswick over to the main Canada source would work. 

Thank you,
Eleanor

**Comment by CSSEGISandData** [comment]
Thanks Eleanor and apologies for not responding earlier. We patched our historical data on [April 25](https://github.com/CSSEGISandData/COVID-19/commit/9d53cdbb4ae0a4ab9696a7ecf36b8814a1eec79a) and have swapped our pipeline to using the Canadian government as our default source. Thank you!!

**Comment by eleanorlutz** [comment]
Thank you very much, I appreciate it!
