### ISSUE TITLE
China Asymptomatic Cases in April

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#5668]
I am looking at China Asymptomatic data shown S "Unknow" in time_series_covid19_confirmed_global.csv
I compared the period difference for cumulative data to get new asymptomatic cases, but data is different with NHC data. like in the csv file, new cases for April 21 2022 is 30919, but in the press release, new asymptomatic data should be 16465: http://www.nhc.gov.cn/xcs/yqtb/202204/ba9c572de4104c5fa0d730f8b778f089.shtml

Can you take a look at why there is such a discrepancy?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | Province/State | Country/Region | 4/15/2022 | 4/16/2022 | 4/17/2022 | 4/18/2022 | ######## | 4/20/2022 | 4/21/2022 |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
All | Unknown | China | 387592 | 387592 | 414252 | 442327 | 471691 | 501847 | 532766 |  
  |   |   |   | 0 | 26660 | 28075 | 29364 | 30156 | 30919 |  
  |   |   |   |   |   |   |   |   |   |  

</body>

</html>

**Comment by david-zihao-xu** [comment]
I am having the same issue here. Would be great if you could take a look! Thanks :)!

**Comment by CSSEGISandData** [comment]
We removed "asymptomatic cases converted to confirmed cases" in our counting.

**Comment by RuijingZ** [comment]
> We removed "asymptomatic cases converted to confirmed cases" in our counting.
If asymptomatic cases converted to confirmed cases are removed from counting cumulative cases, then the difference between consecutive 2 days should be less than official new cases. However, the difference between consecutive days are still much larger than official new cases, which does not make sense. Do you have any insight about this?
