### ISSUE TITLE
Kansas data stale again

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#5673]
A repeat of #5654

This data set didn't get Kansas' Friday update. The state says:
https://www.coronavirus.kdheks.gov/160/COVID-19-in-Kansas

"Last updated: 4/22/2022 at 9:00am. There were 1,574 new cases and 73 new deaths reported since Friday, 4/15/2022."

This data set reflects one case.

Thanks for all you do!

**Comment by CSSEGISandData** [comment]
Thanks Mike! Live data is corrected, historical data should be patched soon. We've made adjustments so this won't happen again. Apologies for the disruption.

**Comment by stucka** [comment]
Thank you so much for all you do. Some day I hope to buy you all some frosty beverages.
