### ISSUE TITLE
US COVID recovery data on 5/11/20+11/22/20 [in time_series_covid19_recovered_global.csv] 

### ISSUE THREAD

**Issue by ikgyu98** [CSSEGISandData/COVID-19#5681]
I'm seeing 230287 as an entry under 5/11/20 while having both 232733 & 243430 under 5/10/20 & 5/12/20. 

Can I get some help on that?

Thank you in advance!

**Comment by CSSEGISandData** [comment]
Thanks for your question. The drop in recovered individuals actually takes place on 5/12/2020. It was associated with a loss of recovered data for Minnesota that was reestablished on 5/14/2020. We are no longer maintaining our recovered data as noted in #4465.
