### ISSUE TITLE
Request to backfill death stats for Sub division of Belgium 

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5689]
For sub divisions of Belgium, only confirmed cases stats is available & death stats is missing and is only provided at country level in an entity named UNKNOWN

![image](https://user-images.githubusercontent.com/87356889/165870472-5a4dfc98-7e5b-4c96-9978-4e01e63e65d5.png)
Few example 
Ref: JHU dataset for [25th Apr, 2022](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-25-2022.csv)
Ref: JHU dataset for[ 26th Apr, 2022](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-26-2022.csv)
Ref: JHU dataset for [27th Apr, 2022](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-27-2022.csv)

Please confirm If there is possibility of back-filling the covid death stats on sub division level for Belgium locations.

**Comment by CSSEGISandData** [comment]
Thank you for your inquiry. Belgium does not provide death data at as fine a resolution as provided for their case data, so we populate all of their deaths in the "Unknown, Belgium" category. You can explore the Belgium source [at this link](https://datastudio.google.com/embed/reporting/c14a5cfc-cab7-4812-848c-0369173148ab/page/giyUB). They do provide death data at the regional level, but we have opted to report the higher spatial resolution provided for cases.
