### ISSUE TITLE
China death data

### ISSUE THREAD

**Issue by david-zihao-xu** [CSSEGISandData/COVID-19#5691]
Question for the team - why are the death statistics different from JHU (https://coronavirus.jhu.edu/region/china) vs. OurWorld (https://ourworldindata.org/coronavirus/country/china)? I have also reviewed the data source cited in this repo (https://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm). The death statistics and cases statistics are more aligned between OurWorld  and the China CDC. 

Could you please take a look into this mismatch? Really appreciate your help!

**Comment by CSSEGISandData** [comment]
Hello! We count deaths from Hong Kong SAR (9,328 deaths by far) and Macau SAR (0 deaths) into the total deaths in China.

**Comment by david-zihao-xu** [comment]
Thank you very much for clarifying!
