### ISSUE TITLE
Could not track data on ArcGIS

### ISSUE THREAD

**Issue by web-sys1** [CSSEGISandData/COVID-19#570]
Can someone please fix the problem? Data cannot be loaded.
Here is the link: https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Screenshot: ![screencapture-gisanddata-maps-arcgis-com-apps-opsdashboard-index-html-1584028055565](https://user-images.githubusercontent.com/61905565/76539998-33782e00-648a-11ea-86f0-86c993ab489d.png)

**Comment by MaverickLunarX** [comment]
Getting the same results/error. 
![image](https://user-images.githubusercontent.com/4042630/76541013-ee83d580-6450-11ea-89f8-5292904d8501.png)

**Comment by dada513** [comment]
same here.

**Comment by feren** [comment]
same here too.

**Comment by M0n7y5** [comment]
Same

**Comment by lightblueandy** [comment]
BORKED

**Comment by TheWCKD** [comment]
The API may be down due to a large number of requests per minute.

**Comment by web-sys1** [comment]
> The API may be down due to a large number of requests per minute.

Maybe, yes.

**Comment by AndroidDev77** [comment]
Issue resolved

**Comment by TheWCKD** [comment]
> Issue resolved

It's not. It still doesn't work.

**Comment by web-sys1** [comment]
> > Issue resolved
> 
> It's not. It still doesn't work.

It works fine. Click [here](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6).

![screencapture-gisanddata-maps-arcgis-com-apps-opsdashboard-index-html-1584035648287](https://user-images.githubusercontent.com/61905565/76550808-6119a300-649b-11ea-90bb-11f339892e75.png)

**Comment by TheWCKD** [comment]
> > > Issue resolved
> > 
> > 
> > It's not. It still doesn't work.
> 
> It works fine. Click [here](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6).
> 
> ![screencapture-gisanddata-maps-arcgis-com-apps-opsdashboard-index-html-1584035648287](https://user-images.githubusercontent.com/61905565/76550808-6119a300-649b-11ea-90bb-11f339892e75.png)

For me it isn't, I'm from Eastern Europe.

![image](https://user-images.githubusercontent.com/37099416/76551052-c7062a80-649b-11ea-8d8b-ea8cdfe3da29.png)

**Comment by web-sys1** [comment]
Let's see if is maintained and is working. So we're going to watch carefully this situation.

**Comment by web-sys1** [comment]
> > > > Issue resolved
> > > 
> > > 
> > > It's not. It still doesn't work.
> > 
> > 
> > It works fine. Click [here](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6).
> > ![screencapture-gisanddata-maps-arcgis-com-apps-opsdashboard-index-html-1584035648287](https://user-images.githubusercontent.com/61905565/76550808-6119a300-649b-11ea-90bb-11f339892e75.png)
> 
> For me it isn't, I'm from Eastern Europe.
> 
> ![image](https://user-images.githubusercontent.com/37099416/76551052-c7062a80-649b-11ea-8d8b-ea8cdfe3da29.png)

Lol. Is so confusing...

**Comment by TheWCKD** [comment]
> > > > > Issue resolved
> > > > 
> > > > 
> > > > It's not. It still doesn't work.
> > > 
> > > 
> > > It works fine. Click [here](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6).
> > > ![screencapture-gisanddata-maps-arcgis-com-apps-opsdashboard-index-html-1584035648287](https://user-images.githubusercontent.com/61905565/76550808-6119a300-649b-11ea-90bb-11f339892e75.png)
> > 
> > 
> > For me it isn't, I'm from Eastern Europe.
> > ![image](https://user-images.githubusercontent.com/37099416/76551052-c7062a80-649b-11ea-8d8b-ea8cdfe3da29.png)
> 
> Lol. Is so confusing...

Now it's working for me too!

**Comment by dada513** [comment]
Not working for me in Poland.

**Comment by web-sys1** [comment]
> Not working for me in Poland.

Why? Please provide some screenshots.

**Comment by dada513** [comment]
> > Not working for me in Poland.
> 
> Why? Please provide some screenshots.

Same as everyone.
![s](https://user-images.githubusercontent.com/49000790/76555731-8822a580-6498-11ea-9566-a6481a3d9aa6.PNG)

**Comment by feren** [comment]
It's fixed for me.

**Comment by dada513** [comment]
It’s fixed on my phone, but not on PC. Werid.

**Comment by ElijahLynn** [comment]
Partially broken still 
![image](https://user-images.githubusercontent.com/1504756/76572750-2b16f780-6478-11ea-8b8d-2c3a381af8cd.png)

On both these URLs (not sure the difference):
* https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
* https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by ElijahLynn** [comment]
> Partially broken still
> ![image](https://user-images.githubusercontent.com/1504756/76572750-2b16f780-6478-11ea-8b8d-2c3a381af8cd.png)
> 
> Also this doesn't say timezone, but current UTC is 22:45 (10:35pm) and my time is 3:45pm Pacific Daylight Time (PDT):
> 
> > Last Updated at (M/D/YYYY)
> > 3/12/2020, 6:33:02 AM
> 
> On both these URLs (not sure the difference):
> 
> * https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
> * https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Appears to be working again for me now, from Oregon, US.

**Comment by TheWCKD** [comment]
The server has been encountering issues for almost 18 hours now. Any updates on this?

**Comment by dada513** [comment]
Fixed for me.

**Comment by TheWCKD** [comment]
Now it works, but shows completelly inaccurate information.

**Comment by web-sys1** [comment]
CASE CLOSED: #570

**Comment by adrian5** [comment]
Firefox users may want to try [this](https://github.com/CSSEGISandData/COVID-19/issues/572#issuecomment-819765212).
