### ISSUE TITLE
Dashboard elements stating they are "not fully configured" 

### ISSUE THREAD

**Issue by salfej** [CSSEGISandData/COVID-19#572]
Something appears to be off with the configuration.
![image](https://user-images.githubusercontent.com/10404888/76543440-859e5c80-6454-11ea-9cd5-ab5c25b7fb7a.png)

There also appears to be an issue with the vector tiles not loading. 
![image](https://user-images.githubusercontent.com/10404888/76543598-bda59f80-6454-11ea-8017-02fbab14be66.png)

**Comment by csavva** [comment]
I confirm. Same issue for me.

**Comment by mahnoka** [comment]
Also confirm here

**Comment by Carleslc** [comment]
Same here

**Comment by mle-enso** [comment]
+1

**Comment by jonasmrfranca** [comment]
Positive!

**Comment by corysimmons** [comment]
Almost certain this is ArcGIS doing rate limiting on the app.

1. Go here https://www.esri.com/en-us/arcgis/products/arcgis-online/resources
2. Click talk bubble
3. Chat
4. Beg them to remove all rate limits from https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Someone else should really make an app to do this statically, or to spin up their own versions of this without needing a constant internet connection.

I'll be offline soon, but I'll work on an offline version of this as soon as I can.

**Comment by JonArcherII** [comment]
Seems like it is working once again.

**Comment by corysimmons** [comment]
It will just keep going down until we spam ArcGIS enough to remove the rate limit from that account.

**Comment by khibma** [comment]
@corysimmons ArcGIS/Esri is **not** rate limiting the dashboard or service. They're fully engaged with keeping it operational from everything I've seen. 
Disclaimer: I work for the Esri distributor, I'm far removed from the team that manages ArcGIS.com

**Comment by corysimmons** [comment]
![image](https://user-images.githubusercontent.com/224636/77001281-129f5500-6930-11ea-827e-a4bc1cc617f4.png)

Seems like CORS errors...

**Comment by adrian5** [comment]
If you're using Firefox, consider lowering your `network.http.referer.XOriginPolicy` (`about:config`). That worked for me. Far from ideal, since it's there for a purpose; pick your poison.
