### ISSUE TITLE
Site Broken: "Not Fully Configured" (404 on https://basemaps.arcgis.com/...)

### ISSUE THREAD

**Issue by ElijahLynn** [CSSEGISandData/COVID-19#573]
404 on e.g. https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/1/2/1.pbf

**Desktop**
![image](https://user-images.githubusercontent.com/1504756/76543794-3fd99800-6444-11ea-84e2-ea28c4e66c47.png)

**Mobile**
![image](https://user-images.githubusercontent.com/1504756/76543894-61d31a80-6444-11ea-86a9-d8ce9ceea423.png)

**Comment by JonArcherII** [comment]
#572

**Comment by TheSeer507** [comment]
seems to be a 404 error on a GET method in init.js

**Comment by web-sys1** [comment]
> 404 on e.g. https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/1/2/1.pbf
> 
> **Desktop**
> ![image](https://user-images.githubusercontent.com/1504756/76543794-3fd99800-6444-11ea-84e2-ea28c4e66c47.png)
> 
> **Mobile**
> ![image](https://user-images.githubusercontent.com/1504756/76543894-61d31a80-6444-11ea-86a9-d8ce9ceea423.png)

I have already reported the [issue](https://github.com/CSSEGISandData/COVID-19/issues/570). No need to report another one.

**Comment by ElijahLynn** [comment]
Thanks for linking those issues. Site is working for me now.
