### ISSUE TITLE
Germany not having it's cases split into the States/Bundersländer

### ISSUE THREAD

**Issue by LordDamionDevil** [CSSEGISandData/COVID-19#574]
How come this is the case as ArcGIS also has a page for Germany
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4
I mean yeah the data is from RKI but that is the only way data can be grabbed as of right now in Germany even if the numbers are mostly not up to date

If you are on the search for something that updates more often and also is very close to the real numbers then this would be enough(This gets data from Johns Hopkins University CSSE, Bundesländer and RKI)
https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/?fbclid=IwAR04HlqzakGaNssQzbz4d8o8R3gz0C910U8tvfYlBT6P0lVJJvHfk9uS2rc

**Comment by klartext** [comment]
These links are known.

The first one is in
https://github.com/CSSEGISandData/COVID-19/issues/576

The second one is in
https://github.com/CSSEGISandData/COVID-19/issues/578

Both issues are meant to gather links of a certain kind.
So IMHO it would make sense that you close your issue.
Nevertheless thanks for reporting.

btw: the dashboard for germany does split into Bundesländer.
