### ISSUE TITLE
UK Unknown 2022-05-17

### ISSUE THREAD

**Issue by RetiredGeologist** [CSSEGISandData/COVID-19#5740]
Can you confirm that the United Kingdom added 1,935,833  new cases and 12,071 new deaths to the "Unknown"  Prov/State as of this mornings report.

Both fields have been Zero (0) since 2020-07-09

Makes for a big spike in the UK numbers

Thanks

**Comment by CSSEGISandData** [comment]
Thank you. This has been corrected.
