### ISSUE TITLE
UK Data Anomaly

### ISSUE THREAD

**Issue by GrayAnderson** [CSSEGISandData/COVID-19#5743]
The UK is currently showing 2,269,738 cases over the last 28 days, but the cases over those individual days come nowhere near that.  Is there anything that can be done so that it doesn't look like the UK has the most cases anywhere in the world right now?

**Comment by AlecLamb** [comment]
I think they have an issue with their database.
Looking at the Admin1 data, it reports a large number of cases (1,928,050) under "Unknown United Kingdom", perhaps this explains the issue or has the UK gained a country?
