### ISSUE TITLE
Discrepancy in Belarus Data.

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5745]
As per the JHU feed, there are zero daily cases on 7th,9th, and 11th whereas as per [WHO](https://covid19.who.int/region/euro/country/by) there are 579, 323 and 58 for these dates. Please look into this if that is the case of there is some issue in the feed.

**Comment by CSSEGISandData** [comment]
Thank you, this has been corrected.
