### ISSUE TITLE
Query: Regarding Colombia new cases.

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5747]
![Screenshot 2022-05-21 2 35 26 AM](https://user-images.githubusercontent.com/91567479/169610419-43dd7271-65b7-4c0d-8059-640fa8466858.png)

As given in the SS, there have been zero cases since 5th May, and then there is a surge in cases on 12th. Is it like on 12th all the cumulative cases since 5th has been added or is how data is? because a similar pattern was observed in other sources like [WHO](https://covid19.who.int/region/amro/country/co), but there the surge is on 14th instead of 12th, which shows it is shifted right by two dates. 

same thing can be observed for death cases.

**Comment by CSSEGISandData** [comment]
Thank you for your question. As noted in [our README](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#irregular-update-schedules), Colombia has changed their update frequency to Thursdays only. The update on the 19th of May similarly contains one weeks worth of data. We cannot comment on the reason the WHO reporting is delayed by two days.

**Comment by gauravjoshijo** [comment]
Thanks for clarification.
