### ISSUE TITLE
Portugal datapoint for cases 

### ISSUE THREAD

**Issue by fibke** [CSSEGISandData/COVID-19#5752]
[Global cases file](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) shows a huge jump in cases between 5/19 and 5/20 for Portugal. 

Could you confirm this outlier observation as a correct data entry? Does it reflect a statistical adjustment on the part of government?

Seems to show up as well in the ECDC data. The[ link ](https://github.com/CSSEGISandData/COVID-19)to the dashboard for Portugal points a site that doesn't update anymore.

Thanks

<img width="285" alt="image" src="https://user-images.githubusercontent.com/69641575/169686077-c4a7b4e4-c6ba-4e1a-9749-95dd2f6b67c2.png">

**Comment by fibke** [comment]
Our World in Data has in the meantime marked the 5/20 entry as NA. 

It is still showing in the JHU dataset

<img width="602" alt="image" src="https://user-images.githubusercontent.com/69641575/170264579-c127c8c7-eafb-40f9-9fa7-a7805079dfef.png">

**Comment by fibke** [comment]
Should add that the above is derived from your cumulative series for cases.

Note the jump on 5/20

<img width="784" alt="image" src="https://user-images.githubusercontent.com/69641575/170270278-e9ee131f-d554-4791-8151-5a6a49b46476.png">

**Comment by edomt** [comment]
Hi @fibke 

On OWID's side, we received the following explanation from the Directorate-General of Health:

> The Directorate-General of Health (Portugal) began to include SARS-CoV-2 reinfections in pandemic monitoring reports and publications.
According to available data, 4.65% of notifications between June 1, 2020, and May 10, 2022, are related to cases of reinfection, values ​​similar to those recorded internationally.
The prevalence of reinfection cases is higher in the period when the Omicron variant is more frequent, with a proportion of 6.10%, surpassing the proportion of about 2% in the period when the Delta and Alpha variants were more frequent, and only 0.35% in the period of the original variant (wild-type) identified in Wuhan (China).
Data on reinfections, 194,244 in total, have been monitored regularly, and so far there have been no changes in the interpretation of patterns relating to the epidemiological situation.
Cases registered in the Portuguese Surveillance System are considered reinfections when there is a positive test after 90 days of the last episode of infection, as defined by the World Health Organization. All notifications that occur in this period (90 days) for the same person are considered to be part of the same episode of the disease.
The change now communicated reflects an evolution in the data reporting methodology used so far, in which only the first infections of each individual were considered.

**Comment by fibke** [comment]
Thank you, @edomt. This is very helpful. 

JHU has in the meantime adjusted its series as follows, which still begs the question what explains the differential treatment between JHU (31,861) and OWID (NA).

<img width="613" alt="image" src="https://user-images.githubusercontent.com/69641575/170461073-10ae1a59-9248-471f-b24d-09cefa758957.png">

**Comment by edomt** [comment]
That's because – due to the data correction above – we had removed that data point from the daily series. We'll now reinstate it.

**Comment by CSSEGISandData** [comment]
Thank you both - we have revised our time series using the data of the [World Health Organization](https://covid19.who.int/) who had been able to back distribute the reinfections in their dataset.
