### ISSUE TITLE
FYI / Montana missed a data update

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#5755]
Montana vowed to release weekly statistics updates, but the latest report is from May 13, meaning they missed May 20. Johns Hopkins' data accurately reflects the latest reported by the state.

**Comment by CSSEGISandData** [comment]
The Montana Department of Health has just published this report now so we're going to correct our historical data so that this jump is reported on Friday, 5/20/2022. Thanks as always for your help!

**Comment by CSSEGISandData** [comment]
Hi Mike, just closing this now as we have corrected the data.
