### ISSUE TITLE
Scotland data is not being updated?

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5758]
As per feed on [JHU](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports), confirmed cases for Scotland on May 19, 2022, May 20, 2022, May 21, 2022, May 22, 2022 is  1949599 which shows zero new cases for these dates, but as per [Public Health Scotland ](https://public.tableau.com/app/profile/phs.covid.19/viz/COVID-19DailyDashboard_15960160643010/Dailyupdate)the number of new cases are as follow:
20/05/2022: 722
21/05/2022: 691
22/05/2022: 528
Please look into it, as it seems data is not being updated.

**Comment by CSSEGISandData** [comment]
Thank you for your question. Public Health Scotland only updates twice per week (Mondays and Thursdays). The time series displayed on their dashboard is by specimen date and not report date.
