### ISSUE TITLE
Descripency in Mexico Data

### ISSUE THREAD

**Issue by gauravjoshijo** [CSSEGISandData/COVID-19#5762]
![Screenshot 2022-05-25 7 51 28 PM](https://user-images.githubusercontent.com/91567479/170284979-04bbe458-d879-4595-8f9c-956676d08b6f.png)
Data for JHU feed is collected from [Government of Mexico](https://datos.covid-19.conacyt.mx/#DOView) but for many dates JHU feed is not matching with it. For eg. In JHU feed,  new cases 17, 18,19,20 and 21 is zero whereas as per the Government of Mexico there are cases for these dates (Please refer to SS for more details) Now possibility is that JHU is dumping data from 17 to 22 on 23, but I am unable to find the frequency of extraction of Mexico data in any of the readme. This pattern of missing data has been observed since 1st May. Can you confirm if this is the case where data is being dumped on a single date?

**Comment by CSSEGISandData** [comment]
Thank you for your question. We can confirm that Mexico is reporting once per week and we have updated the README file.
