### ISSUE TITLE
01-06-2022.csv not yet published (csse_covid_19_daily_reports, csse_covid_19_daily_reports_us)

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#5778]
Hi all,

01-06-2022.csv in both daily_reports and daily_reports_us has not yet been published.

All the best,

Christoph

**Comment by CSSEGISandData** [comment]
Thank you Christoph. It has been posted now, apologies for the delay.

**Comment by c-hera** [comment]
Thanks, much appreciated!
