### ISSUE TITLE
Extreme revision in China: Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5780]
Dear JHU,

Could you please check time series "China: Number Of Confirmed Cases" here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Today we got 2 releases and first got extreme volatility in 06/01/2022 (latest) period when second release provided revision for this period to normal value. It looks like error in first release that was fixed. Could you please advise on this. Thank you.

#CHN.CONFIRMED.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Please see #5777, we have corrected our tabulation of asymptomatic cases.
