### ISSUE TITLE
China's June 5 daily new confirmed death count is wrong 

### ISSUE THREAD

**Issue by sevenwong** [CSSEGISandData/COVID-19#5789]
Why did the number of new deaths in China on 2022-06-05 suddenly soar from zero to 600? According to the following data sources, the number should be zero:
https://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm
http://www.nhc.gov.cn/xcs/yqtb/202206/ff816b30b08648da9f89b59cf33ea1ea.shtml

**Comment by CSSEGISandData** [comment]
We corrected the death count for 6/5/22. Instead of 600 for Unknown, China, it should be 0.
