### ISSUE TITLE
drop in cumulative values for China series - Number Of Deaths 

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5790]
Hi Team,

Could you please check your time series for China on the file "[time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)" (China: Number Of Deaths)

We can see drop in cumulative values in 06/06/2020 period.

Could you please fix it?

Thank you.

Best regards,
NELIA TSOKUROVA

**Comment by DataOps-epam** [comment]
Hi Team,

Sorry for the typo, the right period for this issue is 06/06/202**2**.

Thank you

**Comment by CSSEGISandData** [comment]
We corrected the death count for 6/5/22. Instead of 600 for Unknown, China, it should be 0. Thanks!
