### ISSUE TITLE
New cases for Nicaragua have been same since April 4, 2022

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#5797]
Cases for Nicaragua have been showing as 18491 since April 4, 2022. Please look into this. Also, can you share where JHU gets its data from for Nicaragua?

**Comment by CSSEGISandData** [comment]
Thank you for raising this issue. We determined that the aggregate source that we were using (Worldometers.info) was using a source that does not align with the reporting from the National Health Ministry or the WHO. We have back corrected our data using that posted on WHO and have altered our sourcing to use WHO primarily.
