### ISSUE TITLE
Time series data is gone?

### ISSUE THREAD

**Issue by bicubic** [CSSEGISandData/COVID-19#58]
The below path is empty

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

The below file is clearly broken with rows where province='Confirmed' 

https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv

What's going on? What's supposed to be the definitive data source for this now?

Also it would be super nice if you folk didn't randomly make breaking changes with 0 warning. There is a lot of analysis and information tooling downstream of your dataset now. If you need assistance in data management/stewardship open an issue and I or any of the other dozens of SMEs active on this repo can assist with that.

**Comment by CSSEGISandData** [comment]
Hello, the first folder is just uploaded with files, and we are working on the second folder to update the WHO data. We made some changes to all files to unify the time zone and fix some known issues. Hope that will be more organized and easier to use.
