### ISSUE TITLE
I think you're double-counting the US

### ISSUE THREAD

**Issue by joelaaronseely** [CSSEGISandData/COVID-19#580]
In the data I see data like "Washington" in State/Province.  But I also see data like "Kitsap, WA".  This appears to have just started providing non-zero numbers on 3/10.  Is this real data that had been unreported, or is this double counting?

**Comment by AndroidDev77** [comment]
Please use the search function. This is has been submitted https://github.com/CSSEGISandData/COVID-19/issues/559

**Comment by justchen1369** [comment]
close?

**Comment by ujch** [comment]
The number in dashboard is about 1000 less than in the .csv file (confirmed). ??What's up

**Comment by justchen1369** [comment]
Can this issue be closed because of it being a duplicate?

**Comment by joelaaronseely** [comment]
Yes.
