### ISSUE TITLE
[Incorrect Data] No. of COVID deaths in South Korea June 15th

### ISSUE THREAD

**Issue by dorisykim** [CSSEGISandData/COVID-19#5819]
According to your data listed by Google, the new deaths due to Covid in South Korea on June 15th is 98 people.
[corona data south korea - Google Search](https://www.google.com/search?q=corona+data+south+korea&oq=corona+data+south+korea)

However, the Korean Government statistics site in English says 98 is the total number of hospitalized people around that time:
[ncov.mohw.go.kr](http://ncov.mohw.go.kr/en/bdBoardList.do?brdId=16&brdGubun=161)

It seems to me an error occured when the South Korean data got transferred to JHU. If you do not mind, could you have a look? For your information, I already sent an email with the same information to jhusystems@gmail.com.

Best Regards.

**Comment by CSSEGISandData** [comment]
Thank you very much for the notification! We have patched out data [here](https://github.com/CSSEGISandData/COVID-19/commit/ec38e513f09248a92dbcd77b6134812e61efe326).
