### ISSUE TITLE
Underestimated total numbers for US

### ISSUE THREAD

**Issue by WoVollmer** [CSSEGISandData/COVID-19#582]
Hi,
From my perspective the e.g. total confirmed numbers of your dashboard https://coronavirus.jhu.edu/map.html
are underestimated for some countries with separate provinces.

See my R calculation of your time series data from today for 3/10/20 = yesterday and today = 3/11/20. Therfore the numbers from yesterday are higher than for today and the dashboard is outlining from my perspective the counts from today.
> sum((corona_confirmed %>% filter(`Country/Region` == "US"))$`3/10/20`, na.rm = TRUE)
#> [1] 1670
> sum((corona_confirmed %>% filter(`Country/Region` == "US"))$`3/11/20`, na.rm = TRUE)
# > [1] 1281

Reasoning: if you sum up the last date column provinces with still missing updates (=> 0 or NA) are not reflected even when they have had yesterday a high number. Therefore in my calculation I am using max( , na.rm = TRUE) instead last() function.

Regards,
Wolfgang

**Comment by joetynan11** [comment]
The numbers from 10/3 were including state and county figures, therefore double counting the numbers, this has now been removed and the new figure is correct.

**Comment by WoVollmer** [comment]
Thank you for quick response and your great service! Working fine now.
Wolfgang
