### ISSUE TITLE
data: discrepancy in China data wrt OW i.e CNHC

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5831]
Example dates:
total cases for China , if we exclude Hong Kong:

28/05/2022 : 326
29/05/2022 : 218
30/05/2022 : 195

Data on the OW i.e [CNHC](http://en.nhc.gov.cn/2022-05/29/c_85981.htm)(official source):

28/05/2022 : 82
29/05/2022 : 34
30/05/2022 : 50

When we closely checked the data we found that CNHC bifurcates the data on the basis of Symptomatic & Asymptomatic.
**Query**: The data you pulled from CNHC, you included asymptomatic data in it or not?

**Comment by CSSEGISandData** [comment]
Hello,

Please investigate #5777 and #5579 and see if these announcements answer your question. If not, please reopen this issue. Thank you!
