### ISSUE TITLE
Data discrepancy: Nuevo leon, Mexico

### ISSUE THREAD

**Issue by nickybisht** [CSSEGISandData/COVID-19#5832]
New cases reported in Nuevo leon, Mexico doesnt match with the website its data is extracted from.

As per https://github.com/CSSEGISandData/COVID-19, data for Mexico is extracted from https://datos.covid-19.conacyt.mx/#DOView, when we compared the csv available for Statewise data, we observed a discrepancy between the website and Github data.

Date | JHU Stats | Official Website Stats
-- | -- | --
17/06/2022 | 0 | 538
18/06/2022 | 0 | 169
19/06/2022 | 1255 | 142
20/06/2022 | 75 | 361

Please look into this data discrepancy as there is a huge difference between the stats.

**Comment by CSSEGISandData** [comment]
Thank you for your question. The graphs displayed on the [Mexico government website](https://datos.covid-19.conacyt.mx/#DOView) are not by date of report. For an easy verification, compare the value in the time series graphic for confirmed cases on June 1, 2022 (5,792,836) to a screencapture of the Mexico dashboard collected on [June 1, 2022](https://web.archive.org/web/20220601124304/https://datos.covid-19.conacyt.mx/) (5,823,844). As such, they can not be directly compared with the statistics we aggregate.
