### ISSUE TITLE
WHY ARE PLACES WITH NO CONFIRMED CASES EVEN IN THE SHEET? 

### ISSUE THREAD

**Issue by AaronWard** [CSSEGISandData/COVID-19#585]
Again, i am probably going to be ignored like the last issues i brought up but why is there listings for countries for absolutely no reason?

<img width="840" alt="Screen Shot 2020-03-12 at 20 20 52" src="https://user-images.githubusercontent.com/22074246/76563275-01bd9200-649f-11ea-93cc-5d3d4327bd7c.png">

Please fix your shit

**Comment by crbarahona** [comment]
0 still seems like a useful number in analysis, especially time series data.

**Comment by DesiQuintans** [comment]
Keep the zeroes; they are true known zeroes, and therefore important information.
