### ISSUE TITLE
Grand totals for USA GONE?!?

### ISSUE THREAD

**Issue by wldflwr** [CSSEGISandData/COVID-19#586]
First, I’d like to thank you for all the hard work you all have put into this site. I know you all have put countless hours into it. However, I would like to stress as a citizen who has frequented this site early on I would like to impress upon you that the site was more useful and user friendly with “total cases” by “country” (ie. USA) in the left window frame (USA totals), with main mapping system showing  🔴 per state which when selected details state demographics in right window frame which when selected county breakdowns appear in a third window frame. Thank you for your dedication and hard work!

**Comment by wldflwr** [comment]
I’d like to add how the recent change requires a user to scroll through countless providence’s and countries in left window pain requiring user to add each individual state in the union to get a total numbers in the USA. As a concerned citizen i feel this is a tactic to hide or manipulate actual numbers of people affected in the USA.

**Comment by ragzilla** [comment]
This site is primarily for reporting issues the data set, however you may want to look at the <> arrows at the bottom of the left panel you're looking (which probably says "Confirmed Cases by Province/State/Dependency" right now) to switch it back over to "Confirmed Cases by Country/Region/Sovereignty"

**Comment by wldflwr** [comment]
Thanks, I’m interested is in the total number of cases (actual number) in the USA without having to add it all up through ALL 52 states.  I feel taking the USA “totals” away from the left window pane is deceitful tactic meant bury the real number of people affected in the USA giving people a false sense of security.
