### ISSUE TITLE
Confirmed case in Germany is not being updated - Cannot access data

### ISSUE THREAD

**Issue by shadlyd15** [CSSEGISandData/COVID-19#588]
Confirmed case in Germany is not being updated. It shows "Cannot access data".
According to [this source](https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/?fbclid=IwAR0uh8DQhtFoq8Hz8fCaI5QNY6dpE9ZuCSAp1wt00Utf9AzSxb_Kq3OF9c8) the confirmed case is much higher.

**Comment by 00lex** [comment]
for me it seem the data are not from end of the day, rather from morning :(

**Comment by shadlyd15** [comment]
@00lex Dashboard is now getting updated except Germany. It is showing much less number of  cases.
