### ISSUE TITLE
Washington state case total for 7/13 seems high - data matches source dashboard

### ISSUE THREAD

**Issue by anthonydb** [CSSEGISandData/COVID-19#5886]
Hi, I'm seeing 76,206 cases for WA on Wednesday, 2020-07-13. The cumulative total for the state seems higher than what's in their dashboard. 

https://doh.wa.gov/emergencies/covid-19/data-dashboard

**Comment by CSSEGISandData** [comment]
Hi Anthony,

Thank you very much for notifying us of this issue. We've tracked it down to aberrant data being posted to the "Cumulative Cases, Hospitalizations, and Deaths by County" table on the [Washington COVID-19 Dashboard site](https://doh.wa.gov/emergencies/covid-19/data-dashboard#tables). We're contacting the state to enquire as to the discrepancy between the Power BI dashboard and the table and hopefully obtain data to correct our time series. We appreciate your patience.

**Comment by CSSEGISandData** [comment]
The data has been patched in [this commit](https://github.com/CSSEGISandData/COVID-19/commit/0c062ea9abf63694fadec002a350950d8ddbf91c), we have manual overrides in place until the data is corrected, and have reached out to the state.

**Comment by CSSEGISandData** [comment]
Fully resolved now so I will close this issue. Thanks again, Anthony!
