### ISSUE TITLE
Index Column missing in csse_covid_19_daily_reports_us - 2022-07-19

### ISSUE THREAD

**Issue by c-hera** [CSSEGISandData/COVID-19#5903]
Hi all,

it seems that the index column at position 0 in your latest file is missing. Is this intentional?

Thanks for checking!

All the best,

Christoph

**Comment by c-hera** [comment]
Hi all,

do you have any news on this?

All the best,

Christoph

**Comment by StateCenterKid** [comment]
I had problems reading the US Report from Jun 10 - July 20th.   It seems to be working as expected on Jul 21.

**Comment by c-hera** [comment]
It seems like the issue has been resolved now, see: #5917.
Will close this ticket.
Thanks for resolving!
