### ISSUE TITLE
United kingdom: date

### ISSUE THREAD

**Issue by lucasrodes** [CSSEGISandData/COVID-19#5904]
Hi,
We were wondering if it is in your plans to use 'date of death' or 'specimen date' instead of 'reporting date' for your UK data since this is what is used in [their official dashboard by default](https://coronavirus.data.gov.uk/details/deaths).

Thanks!

**Comment by CSSEGISandData** [comment]
Hello,

Please see #6021. Case data will remain to be reported by taking a snapshot of the cumulative numbers and appending this value to the time series.
