### ISSUE TITLE
Covid information for Costa Rica

### ISSUE THREAD

**Issue by gbonillas** [CSSEGISandData/COVID-19#5909]
Hi, my name is Guillermo Bonilla I work as a EHS Engineer for the company IBM (Costa Rica)
 
IBM use the Our World in Data, for the tracking of the Covid cases, our government (Costa Rica) have several issues related with the main page in where we can consult an track the information related to the covid cases in our country (we have not any update since May 30), but checking the last update of Our World in Data related with Costa Rica Covid cases, you have as the las update this July 20, so my question is, knowing that the official data from Costa Rica is given by the Costa Rica government, and they did not give any data since May 30, where did you get the information related to the last update? (see the attach graph)
 
I really appreciate any help you can give me

**Comment by gbonillas** [comment]
I recieve this response (see the attach)
![Response Covid](https://user-images.githubusercontent.com/109757964/180282397-40ddd94d-e1ca-4cbb-9752-e20e6ed88f1b.JPG)

**Comment by gbonillas** [comment]
But Checking the source data from the link, Costa Rica is not on the list (see the attach)
![Lista paises covid](https://user-images.githubusercontent.com/109757964/180282700-d14241ec-3f12-441b-8a63-34c610428d9d.JPG)

**Comment by CSSEGISandData** [comment]
Hello,

Our reporting is sourced from the World Health Organization: https://covid19.who.int/region/amro/country/cr. Our data matches theirs.
