### ISSUE TITLE
Possible Incorrect Total Deaths in India on 20 Jul 2022

### ISSUE THREAD

**Issue by tllkrmn** [CSSEGISandData/COVID-19#5916]
The total deaths in India on 20 July 2022 data shows 528,433 which then decreases to 525,930	on 21 Jul 2022. Any reason for that?

**Comment by CSSEGISandData** [comment]
Thank you - this has been corrected: https://github.com/CSSEGISandData/COVID-19/commit/238c922a33e887ca5c40ed2e498ee7763cc014ea
