### ISSUE TITLE
UK Death cases discrepancy 

### ISSUE THREAD

**Issue by mkhanka** [CSSEGISandData/COVID-19#5928]
For UK, In the sources  ref.  by JHU, 

Government of the United Kingdom: https://coronavirus.data.gov.uk/#category=nations&map=rate
Scottish Government: https://www.gov.scot/publications/coronavirus-covid-19-trends-in-daily-data/
---
death cases are available till 18 July, 2022 and 8 Apr, 2022, however JHU is showing data for 20th July.
<img width="1473" alt="Screen Shot 2022-07-26 at 6 51 49 AM" src="https://user-images.githubusercontent.com/87356889/180902335-17c58bf8-6e69-466c-bdde-522ce90f84a2.png">

Is there something I am missing here , are we referring to some other source here?

**Comment by CSSEGISandData** [comment]
Thank you for the question. The referenced file is organized by _date of death_ while our data is by _date of report_. The United Kingdom dashboard updates on Fridays only ([source](https://coronavirus.data.gov.uk/details/whats-new/record/2d8367fb-8235-4ad3-9f55-7f96573f73c6)).
