### ISSUE TITLE
Question about source of extra cases and deaths in U.K. data

### ISSUE THREAD

**Issue by eleanorlutz** [CSSEGISandData/COVID-19#5930]
Hello! I've noticed that the total number of cases and deaths in the U.K. are much higher than the total of each of the U.K. subregions combined. Could you possibly clarify for me where these extra cases and deaths are coming from? 

For example, right now the JHU case total for the U.K. is : **23,422,751**
But adding together all the cases for England, Northern Ireland, Scotland, and Wales only add up to **23,212,565** (19560297 + 713294 + 2058616 + 880358). That's a difference of 210,186 cases unaccounted for.

Similarly, right now the JHU death total for the U.K. is : **183,416**
But adding together the nationwide deaths only adds up to **182,727** (159288 + 3445 + 12389 + 7605), for a total of 689 deaths unaccounted for. 

Any information you could provide would be very helpful. Thank you very much!

**Comment by CSSEGISandData** [comment]
Hi Eleanor,

Thanks very much for your question! These totals provided match those published for the admin0 location on the dashboard. The admin level 0 location is inclusive of all admin level 1 locations within the United Kingdom. This includes not only  England, Scotland, Northern Ireland, and Wales but also Anguilla, Bermuda, the British Virgin Islands, Cayman Islands, Channel Islands, Falkland Islands, Gibraltar, Guernsey, Isle of Man, Jersey, Montserrat, "Saint Helena, Ascension and Tristan da Cunha", and Turks and Caicos Islands. In the time series files, we have a ",United Kingdom" entry that is inclusive of only England, Scotland, Northern Ireland, and Wales but this entry is not represented on the dashboard visualization. I hope this is helpful!
