### ISSUE TITLE
Suspicious data change for Confirmed Cases in Greece

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#5946]
Hi,

Could you please advise if you know the nature of large revision of full history of Greece Confirmed Cases data? (from 3843142 cases to 4210771 cases from 19 to 20 July 2022)
Reference: https://www.worldometers.info/coronavirus/country/greece/

Thank you.

**Comment by CSSEGISandData** [comment]
Thank you for your question. Our case data for Greece has not been revised recently.
Our data matches that reporting by the Greece government. Please see:
[July 10, 2022 daily report](https://eody.gov.gr/wp-content/uploads/2022/07/covid-gr-daily-report-20220710.pdf)
[July 17, 2022 weekly report](https://eody.gov.gr/wp-content/uploads/2022/07/covid-gr-weekly-report-2022-28.pdf)
[July 24, 2022 weekly report](https://eody.gov.gr/wp-content/uploads/2022/07/covid-gr-weekly-report-2022-29.pdf)

The weekly reports are published with a several day delay from the date of which they are dated. Of note, WorldoMeters reporting for July 10, 2022 is greater than the daily report released that day from the source.
