### ISSUE TITLE
Discrepancy in New Zealand's data

### ISSUE THREAD

**Issue by nickybisht** [CSSEGISandData/COVID-19#5949]
Hi,

For 5th and 6th July, new cases data for New Zealand has a huge difference from official website of Ministry of Health:

New Cases on JHU: [time_series_covid19_confirmed_global.csv](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)
5th July: 0
6th July: 28538

On official website of Ministry of Health: 
5th July: [10290](https://www.health.govt.nz/news-media/news-items/10290-community-cases-522-hospitalisations-10-icu-12-deaths)
6th July: [10710](https://www.health.govt.nz/news-media/news-items/10710-community-cases-554-hospitalisations-12-icu-15-deaths)

Could you please check

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your question. Firstly, our internal records show that New Zealand did not update on the 5th, which was the reason for there not being a chance in cumulative cases. Further, this issue has highlighted a discrepancy between the Ministry of Health pdfs, which you have kindly linked, and the data displayed on the actual dashboard which we source for our data collection, which likely explains the reason our increase in cases on July 6th (28538) is greater than the sum of the two case totals you have provided (10290+10710=21000).

For example, the total on July 7th displayed on the dashboard was [1,403,073 cases](https://web.archive.org/web/20220705103218/https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-current-cases) versus [1,394,745 cases](https://www.health.govt.nz/news-media/news-items/10710-community-cases-554-hospitalisations-12-icu-15-deaths) quoted in the pdf from July 7th. We are confident this explains the discrepancy.
