### ISSUE TITLE
Data problems in New Jersey

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#5953]
This data set shows zero cases reported for the last four days in New Jersey, which has continued to report cases aggregated to a state level.

I suspect @CSSEGISandData  is pulling its data from the county-level map feed, which appears to be broken: https://www.nj.gov/health/cd/topics/covid2019_dashboard.shtml

**Comment by CSSEGISandData** [comment]
Thank you, Mike. We've notified NJDOH of this issue and are working internally to create a back distribution and a temporary patch to grab state-level cases and deaths until the errors on the NJDOH side are fixed.

**Comment by CSSEGISandData** [comment]
Hi Mike - data issue fixed [here](https://github.com/CSSEGISandData/COVID-19/commit/76ce1733c578a32f362e22b1ae353be6dfd631ca). I'm going to keep this issue open until NJDOH resolves the issue on their side.
