### ISSUE TITLE
No Data on Panels 

### ISSUE THREAD

**Issue by laneadams** [CSSEGISandData/COVID-19#596]
<img width="1440" alt="Screen Shot 2020-03-12 at 7 20 11 PM" src="https://user-images.githubusercontent.com/59070605/76575744-80620180-6496-11ea-806d-17f520b1db19.png">

**Comment by J-Reis** [comment]
Same here, since this morning. I had assumed there was a spike in demand which is overwhelming the service … but of course I don't actually know anything. Can provide logs if relevant (I'm assuming they aren't).

**Comment by CSSEGISandData** [comment]
please see issue #597
