### ISSUE TITLE
Covid-Incidence Austria doesn't match official numbers

### ISSUE THREAD

**Issue by DetektivMittens** [CSSEGISandData/COVID-19#5977]
The Covid-Incidence of JHU doesn't mach with the [offical numbers]( https://covid19-dashboard.ages.at/?l=en) of the austrian gouverment. Unfortunately I can't see which are the source of your numbers for Austria to investigate what's the cause of the difference. There might be an issue with late registration of cases.

**Comment by CSSEGISandData** [comment]
Thank you for raising this question. 

If your question is related to the cumulative numbers currently displayed, our data is sourced from the [World Health Organization COVID-19 Dashboard](https://covid19.who.int/region/euro/country/at). That source has not updated yet today which explains the difference between the cumulative numbers of the source that was linked and our live numbers.

If your question is regarding the "Epidemic curve – new confirmed cases per day Austria" graphic on the Austria website, that curve is based on "day of diagnosis" and not "date of report" (as is our repository). This would result in inherent differences between their data and ours as their historical data is constantly revised.
