### ISSUE TITLE
Ongoing problems with S. Africa

### ISSUE THREAD

**Issue by dlluskin** [CSSEGISandData/COVID-19#5995]
New cases for South Africa are now updating, but deaths still are not!

**Comment by CSSEGISandData** [comment]
Thank you. As before, neither the [South Africa Department of Health](https://sacoronavirus.co.za/) or [World Health Organization](https://covid19.who.int/region/afro/country/za) have published new deaths. Our reporting matches theirs.

**Comment by dlluskin** [comment]
Thank you for your reply. However, unless you are telling me there have been no deaths in South Africa for two weeks or more, then the JH data is NOT updating.

-=-=-=-=-
Donald L. Luskin
Chief Investment Officer, TrendMacro
Room Rater<https://twitter.com/BookLockdown/status/1533278533987905537> score: 9/10
