### ISSUE TITLE
Please release data twice a day

### ISSUE THREAD

**Issue by dawenx** [CSSEGISandData/COVID-19#60]
I read through the new README and csv file for 02-14 and I have some concerns: under the new plan, you make release before 8AM Beijing time and most provinces in China have not updated their data yet; the next release will not come until 24 hours later. (China normally release data between 8-10am.) Please make another daily release at around 4am UTC if possible. Thanks.

**Comment by dawenx** [comment]
Maybe I was not clear: in /csse_covid_19_daily_reports/02-14-2020.csv, only a few provinces in China have “Last Update” closes to  midnight of 02-14 (UTC) which is 8am in Beijing. I’m not saying this particular file has problems by itself, but it does not give full picture of China’s situation (daily change) as most cases are in China.

**Comment by dawenx** [comment]
We had to switch to our own crawling data after 02-14 due to the reason mentioned in this issue. If you need DAILY data after China updates their data every morning local time (typically 7-10am GMT +8; 11pm - 2am UTC; 6pm-9pm EDT), you can download it from our tool (http://ncov.bii.virginia.edu/dashboard/)

Our day is defined in EDT, the last update for each day is around 10pm EDT. Currently we use UTC in our “Last Update” column to make it easier to compare to the data here.

**Comment by CSSEGISandData** [comment]
We apologize for the inconvenience. We have decided to transition our data to report in UTC to be consistent with the time values on the dashboard, as well as in our data. The dashboard will be consistently updating to the latest updates throughout the day. However, the data in this repository will only be updated once a day.
