### ISSUE TITLE
USA - Missouri stats for 8/20/2022

### ISSUE THREAD

**Issue by jusstru** [CSSEGISandData/COVID-19#6008]
Missouri is showing a huge uptick in cases and deaths; the admin2 field is 'Unassigned'. Is this an error or a correction of prior reporting that has not been associated with a particular county? I cannot find these numbers in Missouri's reporting. Datasets are showing 762 deaths reported and 124,622 cases reported on this date.

Thanks!

**Comment by CSSEGISandData** [comment]
Thank you for posting. We will look into this issue.

**Comment by jusstru** [comment]
As of today's update, the 762 deaths/124,622 cases in Missouri with an Unassigned county (admin2) are now showing up on 8/21/2022.
