### ISSUE TITLE
US County level info is no longer being reported

### ISSUE THREAD

**Issue by rajrao** [CSSEGISandData/COVID-19#601]
US County level info was extremely useful and important. It looks like since 3/10, county level info has been removed. The ArcGis JHU map no longer shows county level numbers. Please bring it back.

This seems to be the data set after which this change started happening: https://github.com/CSSEGISandData/COVID-19/commit/82e1397911272be823cb93cbc19b62551608b8dc#diff-eb3e961500680278537f38c751212d2e

**Comment by cscollett** [comment]
Yes, it sounds like they were having some issues with the county data lagging the state data or some places reporting by county reporting. Having both was also resulting in double counting if people didn't programmatically divide the by-state and by-county data, and aggregate only one of them.

The issue is here:
https://github.com/CSSEGISandData/COVID-19/issues/590

I hope they reconsider. I was mapping the counties to major metropolitan areas. That can often be inferred by State data, because there will only be one big city with most of the density. But in places like CA and TX with more than one major metropolitan area, the state data is less useful.

**Comment by kamermans** [comment]
For what it's worth, I've updated my implementation to subtract the per-county data from the statewide totals to maintain county data where available and pool everything else into `[unknown]` like this:

```
Washington (442):
  Clark: 1
  Grant: 1
  Jefferson: 1
  King: 83
  Kittitas: 1
  Pierce: 4
  Snohomish: 31
  [unknown]: 320
```

https://gist.github.com/kamermans/397488317c75b23414100d7e1316e96f

**Comment by ciscorucinski** [comment]
@rajrao @cscollett  @kamermans as the number of `unknowns` grow, then the other known data points become more pointless. 

Check out #558

**Comment by kamermans** [comment]
Yes, that's a good point @ciscorucinski , thanks!  I wasn't sure if the county-level data would come back or be backfilled.  I'll watch that thread to see how things develop.

**Comment by bachi76** [comment]
Something is really broken in the data. Italy or Switzerland for example shows the same numbers yesterday and today, and on the dashboard https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 Italy and ohers are currently completely missing and the infection count shows 91'000 when it way above 120k before.

**Comment by lazd** [comment]
I'm making good progress over here on a scraper to get county-level data. So far, 95 counties: https://github.com/lazd/coronadatascraper

We're gathering resources for state and county data here: https://docs.google.com/spreadsheets/d/1T2cSvWvUvurnOuNFj2AMPGLpuR2yVs3-jdd_urfWU4c/edit#gid=0

And we have a Slack instance set up to discuss development: https://github.com/CSSEGISandData/COVID-19/issues/658#issue-580790114

**Comment by lazd** [comment]
The scraper I was working on has been released with data for 335 counties. Please see the following comment for all of the info: https://github.com/CSSEGISandData/COVID-19/issues/558#issuecomment-599032742

**Comment by reyemtm** [comment]
It's insane to me county level data is not available. Is there really no county level data besides the one mentioned above? How can there be any type of coordinated response with no data?

**Comment by rajrao** [comment]
Closing this issue as being a duplicate of #382
