### ISSUE TITLE
the number of global death is decreasing

### ISSUE THREAD

**Issue by ku6otM** [CSSEGISandData/COVID-19#6015]
I downloaded time series data [time_series_covid19_deaths_global.csv].
The cumulative number of global death was decreased at 8/22.
Is it a bug, or the definition of death was changed at 8/22?

Thanks

**Comment by lucasrodes** [comment]
I think this is related to https://github.com/CSSEGISandData/COVID-19/issues/6016 (i.e. UK decrease)

![coronavirus-data-explorer (1)](https://user-images.githubusercontent.com/18101289/186363156-9abeaa5d-fc54-4467-bcfe-32d996a4aad8.png)


https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=Confirmed+deaths&Interval=Cumulative&Relative+to+Population=false&Color+by+test+positivity=false&country=~GBR

**Comment by CSSEGISandData** [comment]
Addressed in #6021
