### ISSUE TITLE
Large revision of UK confirmed deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6016]
Hi,

Could you please advise the nature of revision of UK`s confirmed deaths for the whole time series in the file below?
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

Thank you.

**Comment by dlluskin** [comment]
There is a gigantic discontinuous drop in CUMULATIVE deaths reported in the database starting August 21. It just has to be massively wrong. If it is right, we need to think about revising all prior data.

**Comment by DataOps-epam** [comment]
Please advice on when the data will be fixed for UK confirmed deaths as we still see large jump 8/22/2022.

**Comment by CSSEGISandData** [comment]
Reason for back distribution referenced in #6021. Correction of recent data made in #6022
