### ISSUE TITLE
South Africa deaths continue to show zero change every day.

### ISSUE THREAD

**Issue by dlluskin** [CSSEGISandData/COVID-19#6019]
There has been only one day in the last three weeks in which you data base shows any change at all in CUMULATIVE deaths. This simply can't be right.

**Comment by jusstru** [comment]
Related to this announcement August 1 possibly:

https://sacoronavirus.co.za/2022/08/01/media-statement-health-department-announces-the-end-of-covid-19-daily-reporting/

Thus, this means the department will, with effect from 01 August 2022, publish the COVID-19 surveillance data on a weekly basis, but continue to closely monitor the situation.

**Comment by CSSEGISandData** [comment]
As in #5992 and #5995, our reporting matches that of the [South Africa Department of Health](https://sacoronavirus.co.za/) or [World Health Organization](https://covid19.who.int/region/afro/country/za). This currently reflects 102,066 deaths, as reported by both WHO and the South Africa Department of Health.
