### ISSUE TITLE
Haiti data appears misaligned

### ISSUE THREAD

**Issue by tom-pham** [CSSEGISandData/COVID-19#6024]
In [time_series_covid19_confirmed_global.csv](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) I'm seeing for Haiti:

8/23/2022: 32994 (daily cases 151)
8/22/2022: 32843 

But according to their MOH I see
8/14/2022: 32994
8/10/2022: 32843
https://mspp.gouv.ht/site/downloads/Sitrep%20COVID-19_14-08-2022.pdf
https://mspp.gouv.ht/site/downloads/Sitrep%20COVID-19_14-08-2022.pdf

The data that is coming in here seems to be lagged by a large amount but also reported in the wrong intervals. With the time series data here it is leading to a day of 151 cases  on 8/23/2022, whereas according to MOH that 151 would be over 3 days. Could you please investigate this? Thank you!

**Comment by CSSEGISandData** [comment]
Thank you for your question. We have aligned our data to that of the World Health Organization in #6080.
