### ISSUE TITLE
Suspicious data for United Kingdom series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6028]
Hi Team,

We observe a large drop published for United Kingdom on the file "[time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)" for the period 08/24/2022.
Could you please confirm that the value is correct?

Thank you in advance

**Comment by fibke** [comment]
Indeed, we see a huge drop in recorded deaths. A statistical adjustment or a data entry error?

8/23: 205,009
8/24: 187,761

**Comment by DataOps-epam** [comment]
Hi Team,
We can observe that the value for 08/24/2022 was revised, however, the new data point for 08/25/2022 seems not correct since it's an accumulative series and the data points released are decreasing.

Could you please check and advise on this?

Thank you.

**Comment by dlluskin** [comment]
This still looks wrong. Zero deaths for a week. Once again today, the number of deaths is negative for msot recent day.

**Comment by DataOps-epam** [comment]
Hi Team,

Could you please advise if you have any updates on the above?

Thank you

**Comment by dlluskin** [comment]
This is still an outstanding issue. With today's no data, there is a sudden massive discontinuous jump in cumulative deaths, implying a single day change of 589. PLEASE let us know what is going on with this.

**Comment by DataOps-epam** [comment]
Hi Team, 
We would greatly appreciate it if you could provide us with any insights regarding the series mentioned above.
We are still observing the decrease in cumulative deaths from 8/25/2022 to 8/30/2022. 
Could you please advise on the issue?

Thank you in advance

**Comment by CSSEGISandData** [comment]
Hello,

Apologies for the delay. This should all be patched presently and we will be moving forward with the weekly back distributions as specified in #6021.

**Comment by DataOps-epam** [comment]
Hi,

We still observe drop in cumulative data. In example data point on 09/12/2022 is 206752 and data point for 09/13/2022 is 206751 which cannot be correct. Could you please check again?
