### ISSUE TITLE
FYI / Mississippi changed its reporting schedule

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#6041]
Mississippi has shifted from reporting five days a week to reporting weekly, on Tuesday.

https://msdh.ms.gov/msdhsite/_static/14,0,420.html

**Comment by CSSEGISandData** [comment]
Thank you, Mike! We've added this to our [README file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md#irregular-update-schedules).
