### ISSUE TITLE
Drop in Netherlands' cases from 8M+ to 7M+. Any explanation?

### ISSUE THREAD

**Issue by Epi-Mic** [CSSEGISandData/COVID-19#6055]

**Comment by DataOps-epam** [comment]
+ the same issue for deaths Netherlands drop from 23.2 to16.5. Could you advise on this as well, please?

**Comment by CSSEGISandData** [comment]
Thank you. We are looking into the issue.

**Comment by RuijingZ** [comment]
> Thank you. We are looking into the issue.

Deaths data also drops from 22600 to 15879 on Sep 2. Could you also take a look? Thank you.

**Comment by DataOps-epam** [comment]
Hi team, any news on the drops reported above?

**Comment by CSSEGISandData** [comment]
Apologies, this was caused by the Netherlands reorganizing their data structure. This data was patched in [this commit](https://github.com/CSSEGISandData/COVID-19/commit/8875a020eb0c04426ce4a9af737c0dee9efa196f).
