### ISSUE TITLE
Niger cases August 31, 2022 issue

### ISSUE THREAD

**Issue by pham-tom** [CSSEGISandData/COVID-19#6085]
I've noticed a potential issue with Niger cases between 8/30 and 8/31. 

8/30/2022  [9329 cases ](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/08-30-2022.csv#L471)
8/31/22 [9931 cases](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/08-31-2022.csv#L471)

This is leading to a large daily case spike of 602. And the cumulative has continued to stay the same at 9931. I see that [worldometers ](https://www.worldometers.info/coronavirus/country/niger/) also reported 602 cases on that day. However, that number seems inconsistent with the source https://who.maps.arcgis.com/apps/dashboards/0c9b3a8b68d0437a8cf28581e9c063a9 which currently shows a cumulative case total of 9388 as of 9/14/22
![image](https://user-images.githubusercontent.com/91288795/190467108-e9af9b0c-ebf7-4bc8-9b7a-a29f7d69fb12.png)

I think this dashboard is using the same numbers as the main WHO page https://covid19.who.int/region/afro/country/ne

**Comment by IHMEkaleb** [comment]
Looks like typo. The main WHO site has 9,331 on August 31 instead of 9,931. https://covid19.who.int/region/afro/country/ne

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We have corrected our data in #6101.
