### ISSUE TITLE
bitcoin spam in comment of old issue

### ISSUE THREAD

**Issue by greg-minshall** [CSSEGISandData/COVID-19#6089]
i'm not sure how to report this.  but, probably the administrator should delete the comment?  (well, i'm not sure i'm interpreting the issue numbers, comment, etc., correctly!)  let me know if i should clarify.  cheers.

_Originally posted by @Katerinalos in https://github.com/CSSEGISandData/COVID-19/issues/5883#issuecomment-1248589507_

**Comment by CSSEGISandData** [comment]
Thank you. We've removed the comment.
