### ISSUE TITLE
NO POLITICAL ISSUES HERE!

### ISSUE THREAD

**Issue by ChrisTing** [CSSEGISandData/COVID-19#609]
Can These issues (....#461,#466,#458,#474,#523,#530,#533 ....)which these people arguing  will cure COVID-19 patients around the world ? MEANNINGLESS !!
GitHub is a place for technical communication , NO POLITICAL ISSUES !!

**Comment by ulidtko** [comment]
@hongru94 pin this.

**Comment by a7032018** [comment]
As a scientist who is focusing in the infectious diseases for 15+ years, I must agree with you but with the different way. This is not a political issue but purely a scientific issue. Merging all countries/economical areas (whatever you call) having totally different policies for containment/mitigation doesn’t help for the policy makers to come up with the effective strategies to cope with the diseases. I am not judging who is doing the best work, but you have to agree the truth that China, Hong-Kong SAR, Macau SAR and Taiwan are enforcing different strategies to mitigate the COVID-19 considering the size of population and the available resources they have, and the outcome is quite different at least by far. Given the fact that China has overwhelm cases of COVID-19, any significant efforts, which can give a hint to the rest of countries/areas to fight against the COVID-19, will be diluted out by merging the efforts from relatively small area (Hong-Kong SAR, Macau SAR and Taiwan) with China. Again, I have to emphasize this is not a political issue, but a pure science issue.
