### ISSUE TITLE
Data for United Kingdom series - Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6096]
Hi Team,

We have observed that data published for United Kingdom on the file "[time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)" for the periods 09/13/2022 - 09/14/2022 seems are not correct, since it's an accumulative series and the data points released are decreasing.
For example, data point on 09/12/2022 is 206752 and data point for 09/13/2022 is 206751.

Could you please check and advise on this?

Thank you.

**Comment by CSSEGISandData** [comment]
Hello,

Could you please confirm in which file you are seeing these data points? I do not see 206752 present for the United Kingdom in [time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) and we have not pushed any changes to the file since this issue was opened.

**Comment by DataOps-epam** [comment]
Hi, 

The issue comes from Pitcairn Islands where value on 09/13/2022 becomes from 0 to -1 for some reason and consequently total amount of deaths for UK decreases by 1

**Comment by DataOps-epam** [comment]
Hi,

We have noticed today that the latest value for 09/20/2022  for the same series as well is decreasing. 
Could you please advise on this?

Thank you

**Comment by DataOps-epam** [comment]
Hi Team, 

We can see that the issue with Pitcairn Islands is fixed now, thank you.
Could you please check as well in the same file the drop for UK from 09/19/2022 to 09/20/2022 (from 206,466 to 206,151)?

Thank you in advance

**Comment by DataOps-epam** [comment]
Hi Team,

We would greatly appreciate it if you could provide any insights related to the drops in cumulative series. 
Today we can observe a new drop from 9/26/2022 to 9/27/2022.

Thank you
