### ISSUE TITLE
Vietnam: Peaks in the number of confirmed cases

### ISSUE THREAD

**Issue by lucasrodes** [CSSEGISandData/COVID-19#6098]
We have detected data peaks in August in the number of confirmed cases in Vietnam (see attached picture, [source](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2022-05-24..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=Confirmed+cases&Interval=New+per+day&Relative+to+Population=false&Color+by+test+positivity=false&country=~VNM)).

- **4th August 2022**: Increase from 10.79 million to 11.19 million (+400k), when the average daily increase in the preceding months is between 1k and 2k.
- **August 6th 2022**: Increase from 11.19 million to 11.35 million (+150k), when the average daily increase in the preceding months is between 1k and 2k.

This might be due to the source reporting several cases at once / backwards correction. Is there any action planned to smooth these peaks?

Thanks for your time and help

![coronavirus-data-explorer (3)](https://user-images.githubusercontent.com/18101289/191118570-1fc0f1d4-5c71-42a5-8df5-9bcaad359f2b.png)

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for raising this important issue. Our data for Vietnam is sourced from the [WHO COVID-19 Dashboard](https://covid19.who.int/region/wpro/country/vn). Their data shows the same spikes, and at present we aren't able to locate any independent reporting for Vietnam that includes historical data. We will continue to investigate but in the interim we do not expect this to be back distributed.

**Comment by CSSEGISandData** [comment]
Hello,

We investigated further and did find independent reporting for Vietnam from the [Vietnamese government](https://ncov.vncdc.gov.vn/viet-nam-full.html). Unfortunately, all of their plots display the same spike in cases that we reported. The cases appear to all be within the city of Haiphong. We will, unfortunately, not be able to correct our historical data.
