### ISSUE TITLE
Maryland Dorchester county Deaths on 05/11/2022

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#6118]
![image](https://user-images.githubusercontent.com/68354122/192336646-8c661f39-1eae-4c44-87bb-fd51f825ec17.png)
In time_series_covid19_deaths_US.csv file, Maryland Dorchester county has a cumulative deaths for 351 on 05/11/2022, but then it reversed back to 108 again. Would this be a miss calculate?

**Comment by CSSEGISandData** [comment]
Patched in #6119.
