### ISSUE TITLE
The confirmed case for Japan 

### ISSUE THREAD

**Issue by kentatkd** [CSSEGISandData/COVID-19#6135]
Hi JHU Team,

Japanese confirmed case has not been updated since 27th Sep in time_series_covid19_confirmed_global.csv. 
The data source (https://www3.nhk.or.jp/news/special/coronavirus/data/) seems to be still active.
Could you please check on it?

Thanks in advance.

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We've tracked this to the NHK COVID-19 data csv ([download link](https://www3.nhk.or.jp/n-data/opendata/coronavirus/nhk_news_covid19_prefectures_daily_data.csv)) no longer being updated but still being a live url. We are working to alter our data collection methods and correct our historical data. Accurately scraping the new website design will require significant refactoring on our end and may take some time. We apologize in advance for any delays.

**Comment by kentatkd** [comment]
Thanks for letting us know about the situation.
As we all know that your team is extremely busy, it is ok with us not to update Japanese cases.
We deeply appreciate JHU team’s great contribution to the world.

**Comment by CSSEGISandData** [comment]
We believe this has been resolved. We will ensure the data posted to the daily reports and time series files tonight are accurate and then close this issue. Thank you for your patience.
