### ISSUE TITLE
United Kingdom deaths

### ISSUE THREAD

**Issue by dlluskin** [CSSEGISandData/COVID-19#6143]
Sorry to keep pushing this. But it just never gets addressed, it seems. UK deaths show up mostly as zero every day in the data, often with large negative updates (such as right now). This can't be right. This has been going on for many weeks and I don't know why no one will address it. You guys are wonderful to do this work, but this little part is falling short. Thank you.

**Comment by CSSEGISandData** [comment]
We have patched the error in our pipeline that resulted in the negative decreases the days following our back distributions by date of death. Please see #6021 for the reasoning behind the back distributions by date of death.
