### ISSUE TITLE
Ohio deaths missing

### ISSUE THREAD

**Issue by stucka** [CSSEGISandData/COVID-19#6156]
The dataset had daily death reports from Ohio through Sept. 29, but none since then. Deaths had been reported daily since late March 2020.

**Comment by CSSEGISandData** [comment]
Hi Mike,

We back distribute Ohio deaths based on their date of death due to their approach to reporting COVID-19 deaths (see #3757). Ohio updates once per week (Thursdays) and then we push the back distribution. Next update should be October 13.
