### ISSUE TITLE
Thailand: Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6165]
Hi dear team!
Could you check and advise please on the large jump for Thailand: Number Of Confirmed Cases from 4,685,047 to 4,713,909 for "as of date" 10/12/2022.
This jump looks suspicious and we would greatly appreciate it if you could provide us with a reasons for this or confirm some kind of mistake there. Thank you!

**Comment by CSSEGISandData** [comment]
Thank you, this was corrected in [this commit](https://github.com/CSSEGISandData/COVID-19/commit/25dc6f47b6ad78f0d1d3c41bb4e2ded42f1690fc).
