### ISSUE TITLE
Data issue for Netherlands location for  the daily new cases dated  Oct 10, 2022 & Oct 11, 2022

### ISSUE THREAD

**Issue by Saurabh0027** [CSSEGISandData/COVID-19#6169]
For Netherlands location we found that the daily new cases for date Oct 10, 2022 & Oct 11, 2022  are as follows :-
[JHU](https://raw.githubusercontent.com/CSSEGISandData/COVID-
19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) :  Oct 10, 2022 - 0  & Oct 11, 2022 - 12065 
[Govt. Website](https://experience.arcgis.com/experience/ea064047519040469acb8da05c0f100d) : Oct 10, 2022 - 2039  & Oct 11, 2022 - 3982 
Note: We found that the data is inputted in JHU on the basis of addition of the cases for the dates where '0' cases are marked.
Since new cases are reported by the official website for a given date, please correct the discrepancy.

**Comment by CSSEGISandData** [comment]
Thank you for your message. The Netherlands dashboard only updates Tuesdays and Fridays. Our data reflects cumulative cases and deaths based on date of report (as described [here](https://www.sciencedirect.com/science/article/pii/S1473309922004340)). As such, we will only see new cases and deaths published on these days while the rest will report 0 daily cases and deaths.
