### ISSUE TITLE
New York deaths up by 100% in last week

### ISSUE THREAD

**Issue by GWMW** [CSSEGISandData/COVID-19#6189]
Is the doubling of weekly deaths in New York State through Oct. 21, 2022, actually a cause for concern or is it merely some type of delayed reporting of previous deaths?

**Comment by CSSEGISandData** [comment]
Thank you for raising this issue. We can confirm that the spike in deaths is largely isolated to the New York City Boroughs. We have validated the increase in deaths is present in their data from [October 20](https://github.com/nychealth/coronavirus-data/blob/1cbf6e88dd0c557b3b497348af3c30d5e1696eb8/totals/group-data-by-boro.csv) and [October 21](https://github.com/nychealth/coronavirus-data/blob/3c28aa0e198c706d01b4b0edc45e73e909e5d950/totals/group-data-by-boro.csv). The city has not provided any language for the reason for the spike. We will leave this issue open for now and continue to investigate.

**Comment by CSSEGISandData** [comment]
We can confirm a similar spike in deaths has been reported on 10/26/2022. We have reached out to the state for comment.

**Comment by CSSEGISandData** [comment]
Please see #6200.
