### ISSUE TITLE
Data issues for the daily confirmed cases in Guadeloupe from 12 October 2022 to 26 October 2022

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#6193]
https://covid19.who.int/region/amro/country/gp
https://coronalevel.com/France/Guadeloupe/
195593,195593,195593,195593,195593,195593,195593,195954,195954,195954,195954,195954,195954,195954,196270

**Comment by CSSEGISandData** [comment]
Hello,

WHO frequently corrects their historical data, a practice which we do not commonly do. If you look at [their data](https://covid19.who.int/region/amro/country/gp) now, you will see that it differs from that which you copy and pasted above. For that reason, you will commonly see differences between the historical data in our repository (which is generated by appending cumulative values to the end of the time series) and the historical data in the WHO dataset.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ratcljd1/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ratcljd1/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Date | WHO Guadeloupe Cases | User Guadeloupe Cases | Difference
-- | -- | -- | --
10/12/22 | 195954 | 195593 | 361
10/13/22 | 195954 | 195593 | 361
10/14/22 | 195954 | 195593 | 361
10/15/22 | 195954 | 195593 | 361
10/16/22 | 195954 | 195593 | 361
10/17/22 | 196270 | 195593 | 677
10/18/22 | 196270 | 195593 | 677
10/19/22 | 196270 | 195594 | 676
10/20/22 | 196270 | 195594 | 676
10/21/22 | 196270 | 195594 | 676
10/22/22 | 196270 | 195594 | 676
10/23/22 | 196270 | 195594 | 676
10/24/22 | 196270 | 195594 | 676
10/25/22 | 196270 | 195594 | 676
10/26/22 | 196270 | 196270 | 0



</body>

</html>
