### ISSUE TITLE
Latvia

### ISSUE THREAD

**Issue by Onnere** [CSSEGISandData/COVID-19#620]
As 13.03.2020, there are 17 cases in Latvia, not 10.
Sources: https://spkc.gov.lv/upload/Aktualitates/2020/2019-nCoV/12martskopsavilkums.pdf

<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FSPKCentrs%2Fposts%2F2797396273649679&width=500" width="500" height="232" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

**Comment by Onnere** [comment]
SPKC (Latvian Centre of Desease Profilactics & Control) published latest data on their Facebbok profile but of the official web-site is just yesterday data. So I tried to post the link.

**Comment by emilianbold** [comment]
Probably related to #650, all recent data is flawed.
