### ISSUE TITLE
Can you publish unpivoted tables?

### ISSUE THREAD

**Issue by rkolka** [CSSEGISandData/COVID-19#623]
Your time series csv-s are pivot tables. 
Source data would be much more useful if the colunms were:
Province/State,  Country/Region, Lat,  Long, Date, Confirmed, Deaths, Recovered

One table would be enough. Can you publish "unpivoted" tables?

**Comment by ybouane** [comment]
I think this is what you are looking for:
https://sweetdata.io/candy/covid-19

It uses the same data as this repository.

**Comment by rkolka** [comment]
Well, no. I hoped for an URL to raw csv file. 
Sweetdata requires login. Even after creating account I only get a "button" to download csv. 
This repo is the source for sweetdata covid-19 candy, right? So then at least it proves the point. "Unpivoted" data is desirable.

**Comment by lglip** [comment]
When using R you can easily transform the data to get a 'tidy' dataset using `tidyr` (https://tidyr.tidyverse.org).

**Comment by JoepvandenHoven-Bluemine** [comment]
The daily reports are unpivoted. To get the changes over time you just need to concatenate them.

**Comment by becare-rocket** [comment]
Mac from bash shell to get tidy dataset from European CDC:

$ /usr/local/bin/wget https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-13.xls
$ ln -s COVID-19-geographic-disbtribution-worldwide-2020-03-13.xls euroCdc.xls
$ /Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to csv euroCdc.xls

Should be similar (but with different paths) on Linux.  Should be a way to run equivalent on Windows using Unix compatibility subsystem.

**Comment by rmcd1024** [comment]
@rkolka This is R code to do what you want. It  presumes that the time series data csv files live in `~/git/COVID-19/csse_covid_19_data/csse_covid_19_time_series/`. And it converts the date field to an R date variable.

```
## Specify paths and file names
library(tidyverse)
path <- '~/git/COVID-19/csse_covid_19_data/csse_covid_19_time_series/'
condition <- c('Deaths', 'Recovered', 'Confirmed')
fn <- 'time_series_19-covid-'
fnall <- paste0(path, fn, condition, '.csv')

## Read the data, combining by rows
x <- map(fnall, ~ read_csv(.)) %>%
    set_names(condition) %>% 
    bind_rows(.id = 'condition')

## Pivot to long, then back to wide to get desired format
xl <- pivot_longer(x, cols = 6:ncol(x), names_to = 'date') %>%
    mutate(date = as.Date(date, format = '%m/%d/%y')) %>%
    pivot_wider(names_from = condition, values_from = value)
```

**Comment by rkolka** [comment]
It is not so much about the technicalities of transforming the data. 
I want to emphasise that the form of data could be ... tidy, sweet as candy, unpivoted, normalized, relational. 

I'd rather not use R or LibreOffice right now. I used the URL to raw.githubusercontent csv inside Manifold GIS, that is perfectly capable of linking to plain csv-s on the web, parsing them to tables of strings, numbers, dates etc and mapping and transforming them in wonderful ways. As would R and LibreOffice.

**Comment by rkolka** [comment]
Forgot to mention. The dashboard links to this repo as 'Downloadable database'. I'm a database freak. I almost "can't see where the database is?"

**Comment by rmcd1024** [comment]
@rkolka If you install git you can download the latest version of the data by typing `git pull`. It is definitely downloadable.

Regarding the format: You asked for the data to be posted in a specific form different from what they're already posting. Since it's easy to use standard tools to transform their data (and I even gave you the code), it strikes me as an unreasonable request. One can ask that the data be in a standard format, that it not contain duplicates, that the format be consistent over time. But it's on the user to take it from there. There are legitimate quality of data concerns that are appropriately being discussed here. IMO those comments should be the focus in this forum.

**Comment by rkolka** [comment]
>  You asked for the data to be posted in a specific form different from what they're already posting.
Yes. 

I think I understand better now your (and other) comments. You were trying to help me get the data. Am I right? 
I got the data. I'm good.   

My question and suggestion was to improve the format. I do believe it would be an improvement. 
This is not an urgent issue, but a very general one. Something to consider in future perhaps. It wasn't even a request.

**Comment by rmcd1024** [comment]
@rkolka Yes, I was trying to help you get the data. Glad you got it!

The problem with format requests is that there is no one best format. Different formats suit different purposes and different tastes. I think the most we can ask of the JHU folks is that that the data be in some standard normalized form. Beyond that, it's up to the user.

**Comment by rkolka** [comment]
@rmcd1024 I have to disagree with you that it is only a matter of taste. 
Why I think my suggestion would be improvement? 
As one [youtube](https://www.youtube.com/watch?v=UrL-YrhlCJQ) video title puts it: "... Convert Summarized Table To **Proper Data Set** ..." :-)
It actually stems from database theory and predicate logic. 
I also think there are many-many more tools with built in 'pivot' than 'unpivot' function.

**Comment by forcequit** [comment]
@rkolka Had the same issue as I needed the data for @observablehq visualisation.
This requires data as rows not columns.

Files are created everyday at 6am UTC by cronjob
https://github.com/forcequit/covid19/
