### ISSUE TITLE
Extreme volatility in Venezuela, Bolivarian Republic of: Number of confirmed cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6280]
Dear JHU, could you please check your data for "Venezuela, Bolivarian Republic of: Number of confirmed cases" here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

With latest release today we can see suspicious extreme volatility for 2022-11-22 period.
Could you please advise on this.
Thank you

#VEN.CONFIRMED.COVID19.D@JHU

**Comment by DataOps-epam** [comment]
Hi, could you please advise if you had a chance to check this issue? Now with following updates we have drop in cumulative values after 2022-11-22. Thank you

**Comment by CSSEGISandData** [comment]
Patched in #6296.
