### ISSUE TITLE
Drop in cumulative values for Peru: Number Of Confirmed Cases

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6294]
Dear JHU< could you please check your data here:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

for time series "Peru: Number Of Confirmed Cases" with release on 11/27/2022 for 11/26/2022 period we can see drop in cumulative values.
Could you please advise on this.
Thank you

#PER.CONFIRMED.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Patched in #6296
