### ISSUE TITLE
China new and total COVID case data error

### ISSUE THREAD

**Issue by xismsix** [CSSEGISandData/COVID-19#6297]
The figures both both new cases and cumulative cases for China don't match those on the website of the National Health Commission, which is your source [http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml]

For example, for Nov 27:
Cumulative cases: you show 1.49 million. NHC shows 311,624 cases. 
New cases: you show 38,503. NHC shows 3,822 cases

**Comment by bylickilabs** [comment]
@xismsix 
---
|This is extremely worrying.|Synchronization may take a while!|
|---|
---

**Comment by CSSEGISandData** [comment]
Hello,

Please see #5579. The totals to which you are referring are specific to confirmed cases only while our totals include asymptomatic cases.

For example, the [November 27 NHC report](http://www.nhc.gov.cn/xcs/yqtb/202211/a6ad14ad49c74489b86b5a19ecff2a15.shtml) has 3,822 new confirmed cases,  36,525 new asymptomatic infections, and 1,251 cases converted from asymptomatic to confirmed cases. Cumulative asymptomatic cases are not reported in the reports.

**Comment by xismsix** [comment]
> Hello,
> 
> Please see #5579. The totals to which you are referring are specific to confirmed cases only while our totals include asymptomatic cases.
> 
> For example, the [November 27 NHC report](http://www.nhc.gov.cn/xcs/yqtb/202211/a6ad14ad49c74489b86b5a19ecff2a15.shtml) has 3,822 new confirmed cases, 36,525 new asymptomatic infections, and 1,251 cases converted from asymptomatic to confirmed cases. Cumulative asymptomatic cases are not reported in the reports.

fantastic. Thanks a lot
