### ISSUE TITLE
Daily updates with no changes in Hubei data

### ISSUE THREAD

**Issue by avatorl** [CSSEGISandData/COVID-19#63]
Dear @CSSEGISandData, thank you for you work once again.

If I understand correct that the problem with same Hubei data in different daily updates (see the image) is probably related to when you publish your updates  and when China publish Hubei updates (they delay the updates sometimes for a few hours). Will you fix this problem? Probably by publishing your daily update only after Hubei update already available or just a few hours later?

Or did I miss something and there is an easy way to extract for missing Hubei data from your files? There were a lot of changes in file structure, so maybe I have missed something...

But I see same issues in daily reports and time series - different dates, same Hubei data.

Thousands of people are already using my reports based on your data [http://avatorl.org/covid-19/](http://avatorl.org/covid-19/) and I hope 

![image](https://user-images.githubusercontent.com/59934292/74587555-423b0480-4ff4-11ea-8d88-696eccc33f58.png)

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We are currently updating this repo daily around 12 AM UTC (7 PM EST). There may be discrepancies with the data from the dashboard and this repository because of the different update time periods. Sorry for the inconvenience.
