### ISSUE TITLE
Peru issue is closed but not fixed

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6300]
Dear JHU, please check your data here:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

for time series "Peru: Number Of Confirmed Cases" with update on 11/27/2022 for 11/26/2022 period we can see drop in cumulative values.
Could you please fix this.
Thank you

#PER.CONFIRMED.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Apologies. We determined yesterday's correction mistakenly only applied to the daily reports and not the time series file. The time series was corrected in #6303.
