### ISSUE TITLE
Guangdong CN cases go to zero

### ISSUE THREAD

**Issue by dlluskin** [CSSEGISandData/COVID-19#6309]
I see today that daily cases for the Guangdong Province of China have been set to zero all the way back to the beginning of time in the data. Could you please look into this?

**Comment by CSSEGISandData** [comment]
Hello,

Can you please confirm where you are seeing this anomaly? I am not able to replicate this issue in [the time series file](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) or a random selection of daily reports ([1](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-25-2022.csv), [2](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/10-03-2021.csv), [3](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/10-01-2020.csv)).

**Comment by dlluskin** [comment]
I will do so in several hours. Thanks for following up.

-=-=-=-=-
Donald L. Luskin
Chief Investment Officer, TrendMacro
Room Rater<https://twitter.com/BookLockdown/status/1533278533987905537> score: 9/10

**Comment by dlluskin** [comment]
I’ve investigated further and the problem is on my end. Sorry to have bothered you with a false alarm. I appreciate your follow up.

-=-=-=-=-
Donald L. Luskin
Chief Investment Officer, TrendMacro
Room Rater<https://twitter.com/BookLockdown/status/1533278533987905537> score: 9/10

**Comment by CSSEGISandData** [comment]
No problem at all. Have a great day.
