### ISSUE TITLE
Georgia Deaths Declined after 11/30/2022

### ISSUE THREAD

**Issue by RuijingZ** [CSSEGISandData/COVID-19#6322]
I observed that Georgia deaths number has been reported over 16900 since September 2022. However, cumulative number is reported below this number since 11/30/2022. May I ask if this is the correct number? If it is correct, is it possible to also revise historical data?
Here is the link: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

**Comment by RuijingZ** [comment]
Hi, may I ask if the latest data are correct? it keeps reporting 16882 for the last several days, but it used to be reported as 16912 for about 1 month. If the latest data are correct, is it possible to revise the past 3 months data?

**Comment by CSSEGISandData** [comment]
Please see #6339.
