### ISSUE TITLE
ISSUE Paraguay: Number of confirmed cases

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#6324]
Could you please check the data for the following series - Czechia: Number of confirmed cases
We can observe a large jump (from around 718000 to 777525) for the 12/2/2022 period and it looks suspicious to us. Could you please confirm that the data is correct and advise the reason for the following jump?
Thank you!

**Comment by CSSEGISandData** [comment]
Hello,

This appears to be a similar issue that led to the correction for #6313. Essentially, the headline number for confirmed cases [reported by Paraguay](https://dgvs.mspbs.gov.py/page/#vista_boletines_covid19.html) now includes reinfections when it didn't previously. We will investigate a back distribution.

**Comment by IHMEkaleb** [comment]
Hello, we're looking for an update. Have you come to a conclusion on how much to back distribute and if you will?

**Comment by Huy077** [comment]
It covers from late December 2021 to date:
https://dgvs.mspbs.gov.py/files/boletines_covid19/SE46_2022_Boletin_Covid19.pdf
https://www.worldometers.info/coronavirus/country/paraguay/

**Comment by CSSEGISandData** [comment]
Please see #6380.
