### ISSUE TITLE
Number of confirmed cases in France are wrong

### ISSUE THREAD

**Issue by alexandrsanches** [CSSEGISandData/COVID-19#633]
Getting the `.csv` time_series_19-covid-Confirmed file and adding the number of confirmed cases in France, the number that i'm getting is 3297. But, in the dashboard, the number of cases in France is 2882.

**Comment by sorny92** [comment]
Duplicate issue: #619

**Comment by JiPiBi** [comment]
@alexandrsanches 
I agree with sorny92 , but  even if the values are  low, for France  you have alos to agregate in the csv Martinique , SaintBarthelemy which are now provinces in the Country France , and in the future Reunion and French Guyana that remain for the moment as Countries 
See #555
