### ISSUE TITLE
Extreme volatility in Peru: Number Of Deaths

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6333]
Dear JHU,
Could you please check your time series "Peru: Number Of Deaths" here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

With today's update for 2022-12-06 period we got extreme spike that looks suspicious.
Could you please advise on this.
Thank you

#PER.DEATHS.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Thank you. We've determined that Peru Ministry of Health published elevated death values on [their dashboard](https://covid19.minsa.gob.pe/sala_situacional.asp) briefly yesterday evening before publishing lower numbers later in the day. These elevated numbers were caught in our QA processes. We'll work to correct our historical data today.

**Comment by CSSEGISandData** [comment]
Original issue corrected in #6335. We'll investigate 2022-11-14.

**Comment by CSSEGISandData** [comment]
Hello,

The decrease from 2022-11-13 to 2022-11-14 is spread across multiple Province_State locations and as such we believe it was a data reconciliation effort by the source and therefore will not be addressed in our dataset.

**Comment by DataOps-epam** [comment]
Hi, could you please double check it. There is no decrease between 13/14 Nov in your data:

[cid:988a59e6-b869-4e65-b8cb-c563e958239f]
The decrease is between 14/15 Nov and 14 Nov looks off the pattern.

Thank you
________________________________
