### ISSUE TITLE
Canada missing from the sidebar?

### ISSUE THREAD

**Issue by shirriff** [CSSEGISandData/COVID-19#635]
I don't see Canada on the sidebar. It should appear somewhere around 157 cases, but I don't see it anywhere.

![image](https://user-images.githubusercontent.com/188116/76631900-a2dc3500-64ff-11ea-8069-d231b8ff79f8.png)

**Comment by bystritskiy** [comment]
~30 countries are missing from the list

**Comment by Sashie** [comment]
sounds like more fun with the web panel

**Comment by asmaloney** [comment]
Don't know how they are getting the data, but if they are scraping [this page](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html), the table layout changed today by adding the _Number of probable cases_ column.

**Comment by shirriff** [comment]
Canada has returned, so I'm closing this.

**Comment by asmaloney** [comment]
...but the numbers don't match the official ones on the government site: 193 vs. 176. Unless there's some other official source we aren't aware of?

(And when you click the 193 it shows 191 as "Total Confirmed" at the top.)
