### ISSUE TITLE
Coronavirus World Data missing 12/7/2022+

### ISSUE THREAD

**Issue by AC243** [CSSEGISandData/COVID-19#6353]
On page https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports the data for 12-06-2022 is missing and data after 12/6 for 2020, 2021 & 2022 are all missing.
Possibly caused by incorrect truncation ("Sorry, we had to truncate this directory to 1,000 files. 58 entries were omitted from the list.")
Note that the US data (https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us) is all complete

**Comment by CSSEGISandData** [comment]
Please see #6255 for a guide on how to access all the daily reports.
