### ISSUE TITLE
ISSUE Vietnam: Number of confirmed cases

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#6369]
There is a mysterious jump from 11520639 to 11529639 and then back to 11521388 cases. Could you check the data please?
I gave you some references:
https://suckhoedoisong.vn/ngay-11-12-co-194-ca-covid-19-thap-nhat-gan-2-thang-qua-169221211173206779.htm (11520639 cases)
https://suckhoedoisong.vn/ngay-12-12-so-mac-covid-19-tang-len-gan-400-ca-169221212171857601.htm (11521022 cases)
https://suckhoedoisong.vn/ngay-13-12-co-366-ca-mac-covid-19-moi-169221213173525232.htm (11521388 cases)
https://www.worldometers.info/coronavirus/country/viet-nam/

**Comment by CSSEGISandData** [comment]
Patched in #6382.
