### ISSUE TITLE
China NHC ceased daily report

### ISSUE THREAD

**Issue by ZauberViolino** [CSSEGISandData/COVID-19#6398]
Today the National Health Commission of P.R. China [announced](http://www.nhc.gov.cn/xcs/yqtb/202212/7272431ee60c4f4d953b0c16257c230e.shtml) that they will no longer report daily data of the COVID-19 pandemic, and that CDC will report "related information" instead.

The CDC of P.R. China [hasn't report COVID-19 data](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_11809/) as of 12:00 (UTC+8).

**Comment by ZauberViolino** [comment]
Update: [CDC reported Dec. 24 data.](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_11809/202212/t20221225_263104.html)

**Comment by CSSEGISandData** [comment]
Thank you. We've turned this into an announcement in #6414.
