### ISSUE TITLE
Which time series are correct now? Total figures from earlier days are different

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#64]
Which daily dates are still correct at all?

Referred to "confirmed" in the "time series".

At Google Spreadsheet and the last days here at Github the data was usually entered twice a day. Mostly in the morning and late in the evening. To be seen in the first line with the date and the given time.

Since you've changed it now (1 time a sum for one day) here at GitHub; how can it be that the daily sum is less compared to the old data (Spreadsheet, GitHub) for the day instead of more?

For example, February 9th. I was comparing saved records. These include the last (February 11th) from Google Spreadsheet and also February 11th from GitHub, as well as February 12th GitHub, yesterday and today GitHub.

If I compare all of them, except for today, the result is the same total sum for the day. 40,536 confirmed. I took the last entry for this on February 9th at 23:20. 

If I look at today's data that is available in GitHub and take February 9th, I get only 40,151 confirmed for the calculation.

As you could see, the other data sets had the time at 23.20 on the second measurement on February 9th. So 20 minutes before midnight. 

How can it be that the new data sets, with the once existing daily statistics, are now negative? The 20 minute difference for a new day is not long, but the few confirmed at the end for February 9th 385 are more than before is quite strange.

Differences (even big ones) also occur on all other days when I compare them with the data available in GitHub today to previous data sets.

So what is true?

Unfortunately, visualizations from other users who relied on the last measurement data of that day are no longer correct. If a last measurement was many hours before the end of the day, a new one-day statistic can't show any minus differences for that day?

![github_11te](https://user-images.githubusercontent.com/49625256/74591241-88a15b00-5016-11ea-89fc-27edea0b35b0.png)
![github_new_now](https://user-images.githubusercontent.com/49625256/74591242-8939f180-5016-11ea-98a4-05ea4bfe32b3.png)
![google_11te](https://user-images.githubusercontent.com/49625256/74591243-8939f180-5016-11ea-92cd-b1f6e34b75fd.png)

**Comment by CSSEGISandData** [comment]
Sorry for the confusion. The Google sheet is now deprecated and there have been a few refactoring  updates to the Github repository. The csse_covid_19_data will have our **daily** up-to-date case files and time series files. All the date/time fields will now be in UTC.
