### ISSUE TITLE
datapoint French polynesia in wrong spot

### ISSUE THREAD

**Issue by TimHHH** [CSSEGISandData/COVID-19#641]
Your datapoint for French Polynesia is next to Australia, whereas it should be much further east in the Pacific Ocean.

**Comment by maxdevblock** [comment]
`French Polynesia, France, -17.6797, 149.4068`

should be

`French Polynesia, France, -17.6797, -149.4068`

**Comment by christophGeoHealthCentre** [comment]
oh no, LAT and LON have been mixed, today French Polynesia is close to Australia

**Comment by maxdevblock** [comment]
> oh no, LAT and LON have been mixed, today French Polynesia is close to Australia

They're not mixed, LON is correct, LAN is the opposite +/–
