### ISSUE TITLE
California Data Point is missing

### ISSUE THREAD

**Issue by markolo25** [CSSEGISandData/COVID-19#643]
Hello The count of cases for california is missing now, can someone please look into it

![image](https://user-images.githubusercontent.com/1953943/76638871-6b26ba80-650a-11ea-8c25-47f363ca9af3.png)

**Comment by upretip** [comment]
+1 

the data is available on the csv files. I notice that Oregon is not available either. Must be an issue on the AIRgis rendering

**Comment by graphguy** [comment]
Looks like the red bubble on California is back now. But the red bubble on Florida is still missing.

**Comment by grugnog** [comment]
Oregon is still missing also

**Comment by jlevente** [comment]
I'm also missing a few others, like CO and TX.

**Comment by crbarahona** [comment]
Looks like, while it's in the CSVs, it's missing from the Feature Layer: https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c#data

**Comment by GrayMatter** [comment]
Do we know why it is no longer in the CSV? California counties have data up to and including 9th March then show 0 from 10th to 15th.

**Comment by graphguy** [comment]
They (Johns Hopkins) decided to no longer provide US data below the state level ... but they left both the county lines in the csv (for older data), and the state total lines in the csv (for newer data), and they used '0' (zero) for 'missing' values (which can be very misleading).  There were several discussions in the "Issues" section of Johns Hopkins' github page: https://github.com/CSSEGISandData/COVID-19/issues
