### ISSUE TITLE
Unusual surge in Netherlands’ deaths  (23k to 833k)

### ISSUE THREAD

**Issue by miotomita** [CSSEGISandData/COVID-19#6438]
consequently the global death toll rose +812k  from January 3 to January 4

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We've identified the cause of this issue. Our live data will be corrected shortly and our historical data later on today. I will close this issue once both corrections are live. Apologies for the disruption.

**Comment by albertsun** [comment]
Hi @CSSEGISandData just checking in to see when this data might be updated - I see the commit in this repo updating the data, but not in the ArcGIS dashboard yet.

**Comment by CSSEGISandData** [comment]
Hi @albertsun - ArcGIS dashboard should be displaying the correct data now. Apologies for the trouble.
