### ISSUE TITLE
Suspicious data for Thailand series

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6463]
Hi Team,

We observe that the values published for Thailand on the files [time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv) and [time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) for the period 01/10/2023 seem extreme in comparison with other historical values.
Could you please confirm that the values are correct and provide the reason for such big jumps?

Thank you in advance

**Comment by DataOps-epam** [comment]
Hi Team,

Could you please advise if you had a chance to review the above?

Thank you

**Comment by CSSEGISandData** [comment]
Thank you. In our review we've detected other oddities with the publication of Thai data. For example, their [dashboard](https://ddc.moph.go.th/covid19-dashboard/) and [open data json file](https://covid19.ddc.moph.go.th/api/Cases/today-cases-all) report significantly different case totals. We are pausing Thailand updates at present while we continue to investigate.

**Comment by CSSEGISandData** [comment]
Hello,

Thailand has corrected the discrepancies between their dashboard frontend and API backend. We've corrected our data since Jan 1 using WHO data in #6513 and will be using the value from the dashboard frontend moving forward.
