### ISSUE TITLE
Indiana state and county case reports frozen since mid Dec

### ISSUE THREAD

**Issue by fayetteklaassen** [CSSEGISandData/COVID-19#6464]
Hello,

The case reports for Indiana state and counties in this repository have been constant (no new cases reported) since mid-December 2022. The source page of Indiana Department of Health linked on this page does report new cases since then. Hopefully these data can become available through this repository again.

In addition, Tennessee counties and states have also not reported new cases and deaths since January 1, which, following a statement on the Public Health webpage listed as the source file, is due to an announced closure of their data site after December 2022.

Thanks!

**Comment by CSSEGISandData** [comment]
Hello,

We've been able to correct Indiana in #6465 and have made changes to our data collection that should resolve any staleness.

TN reporting contains data through Jan 7. Only portions of their site were decommissioned at the end of December 2022 and (thankfully) not the files we use for data collection.

Thank you!
