### ISSUE TITLE
United Kingdom inconsistent data since December 9, 2022

### ISSUE THREAD

**Issue by 3dgiordano** [CSSEGISandData/COVID-19#6469]
I understand that there must be some problem with the Dashboard or the data source from which they get the number of cases and deaths for the United Kingdom.

In the meantime they can use the data that WHO collects which seems to be up to date.
https://covid19.who.int/region/euro/country/gb

Data in CSV
https://covid19.who.int/data#button--6--2

But be careful, it seems that the WHO concept of the United Kingdom is not the same, the totals do not seem to match, the WHO data is lower than the total data reported by UK on dashboard, so there may possibly be a difference in criteria or countries involved in the sum of cases and death.

I hope you can find a solution to the lack of information in the United Kingdom soon.

Regards

**Comment by CSSEGISandData** [comment]
Hello,

Could you be more specific as to the issue to which you are referring? Our case and death totals for the four nations are equivalent to the totals reported on the [UK COVID-19 Dashboard](https://coronavirus.data.gov.uk/). We also published new cases and deaths in our update on 1/12.

**Comment by 3dgiordano** [comment]
Hi.

I made a spreadsheet to show you the gap or the lack of data.

https://docs.google.com/spreadsheets/d/1RB6_22henrxa5sgFmUdbHIbzZrOJ5BPM26-X9nwOvd8/edit?usp=sharing

With the update that you made today, the difference in cases was adjusted.
Source | Cases   
-- | -- 
JHU Total | 24243389
UK Dashboard | 24243389
WHO | 24243393

And with Deaths published today, I don't know if it was adjusted or not adjusted.
The death totals do not match either of the two criteria used by the UK.

Source | Deaths | Last publish  
-- | -- | --
JHU Total | 214878 |  13 jan
UK Dash 28days | 202157 | * 7 jan
UK Dash DatCert | 211052 | * 30 dec
WHO | 202157 | * 9 jan

WHO and UK Dashboard match, no the same JHU data, Hence my difficulty in knowing if it is correct or not.

Probably the fact of not having published a weekly publication made a visual error and with it there was something that seemed like an error in Cases. Now, cases was solved.
For death, the problem of not reporting if it is evident.
You can see yourself on Google charts and OWID charts by selecting weekly cases.
It is not clear to me as I mentioned if it was solved or not, I would have to know the origin of the difference in the totals.

https://ourworldindata.org/explorers/coronavirus-data-explorer?time=2022-09-15..latest&uniformYAxis=0&Metric=Cases+and+deaths&Interval=Weekly&Relative+to+Population=false&Color+by+test+positivity=false&country=~GBR

**Comment by 3dgiordano** [comment]
Another piece of information, if I take the totals reported as of December 1 and I take out the difference in JHU and UK Dashboard.
The difference of what is not reported in JHU is great.

From 1 December to latest data (Deaths 28days) 

Source | Deaths
-|-
JHU Deaths | 1652
UK Deaths | 4184

From December to today, 2532 deaths no reported by JHU (approximation)

Check if my calculations are wrong. I did it manually and I may have made a mistake.

**Comment by CSSEGISandData** [comment]
As recorded in #6021, our deaths for the UK are constantly revised to the deaths by date of death. Please do not compare to the deaths within 28 days metric on the UK dashboard.

Our data matches the values published by the UK COVID dashboard at this json: https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=overview&structure=%7B%22Province_State%22:%22areaName%22,%22date%22:%22date%22,%22deaths%22:%22cumDailyNsoDeathsByDeathDate%22%7D&format=json.

It's unclear why there are discrepancies in totals reported by the UK COVID dashboard. We will continue to use this json API for our back distributions.

**Comment by 3dgiordano** [comment]
It seems you are not understanding the point that I want to show you.
Precisely the api that you share has not been reporting data changes since December 23.

The dashboard has also been reporting several issues around the reported data from December to date.
https://coronavirus.data.gov.uk/details/whats-new

In one of the posts I show you how the data of the other death indicators do show changes in the statistics per day (and the number of deaths reported from December to date)

Now that I understand what exactly is the api that you use, I understand where the problem is.
As their dashboard site indicates, cumDailyNsoDeathsByDeathDate does not have data from December 23, 2022 to date.
When tat record is reported by day, no changes from 23 December and no more data than 30 December 2022.

Surely you can get to see the news reported on the site and can contact the people behind the api to find out why the data is not updated from that date. And also if that data reflect the fixes related to the problems with data from December to date.

Regards
