### ISSUE TITLE
Add a contributing.md so folks know the scope of acceptable contributions

### ISSUE THREAD

**Issue by trycrmr** [CSSEGISandData/COVID-19#647]
Today I thought it would be a fun idea to contribute to projects associated with tracking and disseminating information on the current state of COVID-19. However, in this repository it seems only a small subset of the opened PRs are being merged. Adding some contribution guidelines in CONTRIBUTING.md file will allow the broader community to know where they can contribute effectively.

**Comment by nickanderson** [comment]
Yes, please. I was interested in updating records for Kansas in the US but it's unclear if thats desired or exactly how to go about doing so (do i edit daily reports or timeseries csvs, both?

**Comment by ciscorucinski** [comment]
#558 Here is a community-driven effort for those that want to contribute. Google Docs and Slack available.

**Comment by hasanmoha** [comment]
sars-covid-19

**Comment by SaiLikhith7** [comment]
as @ciscorucinski says, #558, We can contribute using those platforms

**Comment by Beaugas** [comment]
Any way to obtain national and international data from EPIC, Cerner and or Other EMR platforms to help facilitate wider spread professional and "amateur" analysis?  Maybe pooled intellect can find more subtle common denominators for risk factors and predictors of favorable and unfavorable outcome.  We need more than Case Fatality Rate.  - Case ICU admission Rate, Case Assisted Ventilation, Post Recovery Morbidity information.
