### ISSUE TITLE
Map with country boundaries contributes to scientific bullshit !!!

### ISSUE THREAD

**Issue by FabriceSalvaire** [CSSEGISandData/COVID-19#651]
Seriously what is the scientific meaning to show a large dot over a big European country like France, Germany, Spain versus a small country line Netherlands ???

It would make sense to compute a kind of wave propagation map, but a map like

https://www.lemonde.fr/international/article/2020/03/13/coronavirus-quels-pays-ont-reduit-l-acces-a-leur-territoire-aux-francais_6032993_3210.html

is just bullshit.

**Comment by peterdrier** [comment]
First, calm down. 

Second, the size of the dot is proportional to the number of cases in the region/state/country.  

Third, if you want a map of your own, then make it.  The data behind this is all available to anyone who wants it.  

Complaining won't get you very far right now.  So either help or get out 'da way.

**Comment by carlosvega** [comment]
This is not the way to talk on a forum. They did a great effort publishing the data. This is open source. Fork the code and make the changes yourself.

**Comment by Wikunia** [comment]
see https://covid19.opensourc.es for a different visualization without bubbles.
