### ISSUE TITLE
Inconsistent daily new cases for Mexico

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#6514]
For Mexico, it was found that the count of the new confirmed cases in the JHU [feed](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) is incorrect when compared to [official website](https://datos.covid-19.conacyt.mx/#DOView) . For example:-

On [feed](
![image](https://user-images.githubusercontent.com/87332298/214141311-a2d1c48f-75c4-4b59-8e76-1143552aed0c.png)
) : 

16/01/2023 : 7314891(Accumulated cases)
17/01/2023 : 7315454; New Cases : (7315454-7314891) = 563
Whereas, on [Official website](
![image](https://user-images.githubusercontent.com/87332298/214141733-710de044-54f5-406c-bc79-c1782db20d04.png)
) the difference is:
16/01/2022: 7329009(Accumulated cases)
17/01/2023 : 7333012 ; New Cases : (7333012-7329009) = 4003

I found a previous similar issue (#5762) where it was mentioned that the difference is due to Mexico updating its data once a week. But that pattern is not there anymore.

Could you please clarify?

**Comment by CSSEGISandData** [comment]
Hello,

The [Mexico gov site](https://datos.covid-19.conacyt.mx/#DOView) repeatedly corrects their time series file. Our historical data is static. 

Using #5762 as the ground truth for data published in the Mexico gov time series on May 25, 2022, we can see that their historical data is not stable over time as shown in this table:


Date | Data_20220525 | Data_20230123 | Difference
-- | -- | -- | --
5/16/22 | 5755255 | 5783631 | +28376
5/17/22 | 5756404 | 5784940 | +28536
5/18/22 | 5757649 | 5786350 | +28701
5/19/22 | 5758840 | 5787786 | +28946
5/20/22 | 5759637 | 5789164 | +29527
5/21/22 | 5759733 | 5789757 | +30024

Further, we can expect that the +327 new cases being reported for 2023/01/21 will be revised when the data is next updated.

Please reopen this issue if further clarification is needed.
