### ISSUE TITLE
China deaths back distributed 1/25/2023

### ISSUE THREAD

**Issue by CSSEGISandData** [CSSEGISandData/COVID-19#6520]
Hello all,

On [January 15, 2023](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202301/t20230115_263381.html) and [January 21, 2023](https://www.chinacdc.cn/jkzt/crb/zl/szkb_11803/jszl_13141/202301/t20230121_263515.html), the China CDC released COVID reports structured similarly to the previous reports used by NHC (see #5579). This reports differ, however, in that the number of cases is not provided in the same format as before and all data is provided at the national rather than subnational level.

We have used this data to correct our time series for deaths alone ([commit link](https://github.com/CSSEGISandData/COVID-19/commit/e99547871abae4de1ef0c50450a14bb3aeaa598f)). The reports specify the timeframe in which the deaths were recorded - we have used the difference between these values and our current reporting to calculate values to populate the "Unknown, China" entry. The frequency with which these reports will be published is still unclear, but we will add their totals to our "Unknown, China" entry as they arise.

We are still working to understand how we may incorporate the "hospitalized cases of new coronavirus infection" into our dataset. We appreciate your patience.

**Comment by pwdel** [comment]
Just referencing the below listed comment on this issue since it has a lot of followers and is related:

https://github.com/CSSEGISandData/COVID-19/issues/6414

> We are still working to understand how we may incorporate the "hospitalized cases of new coronavirus infection" into our dataset. We appreciate your patience.

**Comment by dlluskin** [comment]
Thank you. Please keep us all updated on this thread!

**Comment by CSSEGISandData** [comment]
The WHO COVID-19 Dashboard has updated China cases and deaths: https://covid19.who.int/region/wpro/country/cn

We're working to bring this data into our repository but need to rectify some conflicts with data for Hong Kong SAR. For now, I recommend observing the WHO dashboard for mainland China COVID-19 data.
