### ISSUE TITLE
Non-sense values for deaths [China].

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#6522]
Hello team.

As for the latest release for  [[time_series_covid19_deaths_global.csv]](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv). I can see that data for China on January 24th is (91147) deaths to change on January 25th (72553).

Could you please revise this data and correct it?

Thanks.

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We're working a fix.

**Comment by CSSEGISandData** [comment]
This has been corrected.
