### ISSUE TITLE
N/A coronavirus recovery values

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#6554]
I found that coronavirus recovery values in some countries have been set to N/A for so long (as many as 14 month in some cases).
Could you rectify it?
https://www.worldometers.info/coronavirus/
![Screenshot (43)](https://user-images.githubusercontent.com/92421581/216778641-6824d4f6-5a3e-414a-a5fc-6ba18c8b2612.png)

**Comment by CSSEGISandData** [comment]
Hello,

We do not manage the worldometers website. Please do not option issues for their data in our repository. We have not published recovery data in our repository since August 2021, as noted in the pinned issue #4465.
