### ISSUE TITLE
UK Data Anomaly

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#6557]
I found that you have an issue with the UK database.
Looking at the "Unassigned" data, it reports a large number of cases (1,943,263) on 20 and 21 May 2022, perhaps this explains the issue, or has the UK gained a country?
Also at the "Scotland" data, it reports 2127767 cases on 23 November 2022 and then mysteriously drops to 0 on 24 November 2022
Could you rectify it?

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for notifying the issue for our data on May 20 and May 21 - we're working a fix.

I don't understand the second portion of your issue. We report no delay cases for Scotland in the timeframe you mention. Further, at no point in our repository has Scotland reported the precise number you mention. Case totals for 11/30/2022 are 2,125,838 while case totals on 12/01/2022 are 2,129,682. Can you please clarify?

**Comment by Huy077** [comment]
https://drive.google.com/file/d/1D90A3qwLT81bjDZ-uX-TxVJTzhLB5lFW/view?usp=share_link

**Comment by CSSEGISandData** [comment]
Thank you. The source of that graphic does not appear to be our repository. Please see [11-23-2022 daily report](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-23-2022.csv). We cannot comment on the work of other aggregation efforts.

**Comment by Huy077** [comment]
At the "Scotland" data, it reports 2127767 cases on 23 November 2022 and then mysteriously drops to 0 on 24 November 2022 and then back to 2129682 cases on 30 November 2022
Could you rectify it?

**Comment by CSSEGISandData** [comment]
This is not present in our data.
