### ISSUE TITLE
What is the source of new covid cases for Turkey?

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#6562]
Hello,

Currently the source of data mentioned for Turkey in READ.ME is stricken through (source is not functional) and recently, on most of the days, new cases are showing 0 for Turkey.

Can you let me know what is the source of this data for new covid cases in Turkey?

**Comment by CSSEGISandData** [comment]
Hello,

Locations without independent sourcing are pulled from the [WHO COVID-19 Dashboard](https://covid19.who.int/region/euro/country/tr). This is the case for Turkey.

**Comment by tushartify** [comment]
In that case, I can see that WHO has not added any data for new cases since November 14, 2022 
![image](https://user-images.githubusercontent.com/87332298/217270894-83fc394c-baad-49af-a2eb-466ccd5e1f2e.png)
but we can check in raw data that cases have been updated for January 1.
![image](https://user-images.githubusercontent.com/87332298/217274720-66d2f5f2-826f-4339-b24a-5d0f9b4dbd06.png)

Can you please check the discrepancy?
