### ISSUE TITLE
Scotland data anomaly 

### ISSUE THREAD

**Issue by Huy077** [CSSEGISandData/COVID-19#6563]
I found that at the Scotlan data, it reports 2127767 cases on 23 November 2022 and then mysteriously drops to 0 on 24 November 2022 and then back to 2129682 on 30 November 2022.
Could you recify it?

**Comment by CSSEGISandData** [comment]
Our data for [11-24-2022](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/11-24-2022.csv) does not reflect the data anomaly you reference. Kindly ensure that the issues you raise are related to this repository and not other projects.
