### ISSUE TITLE
It happened again. US data updated current, Global updated but behind one day

### ISSUE THREAD

**Issue by dlluskin** [CSSEGISandData/COVID-19#6581]
All four data bases were updated. But only US deaths and cases are current for 2/11/23.  Global cases and deaths were updated to 2/10/23, after no update yesterday. But both should be 2/22/23. PLEASE SOMEONE LET US KNOW WHAT IS GOING ON.

**Comment by CSSEGISandData** [comment]
Please see response to #6580.
