### ISSUE TITLE
Have EU countries stopped reporting daily new cases on March 12?

### ISSUE THREAD

**Issue by 3verse** [CSSEGISandData/COVID-19#659]
Adding my public viz screenshot  based on data from this repository: 

![image](https://user-images.githubusercontent.com/8287470/76652377-5ffd7a00-655e-11ea-81e7-351568ed7b89.png)

**Comment by emilianbold** [comment]
Probably related to #650, all recent data is flawed.

**Comment by 3verse** [comment]
gotcha @emilianbold, I'll close this issue - seems like figures have been made up for the next day... hopefully data won't get worse (screenshot below) - original dashboard available [here](https://public.tableau.com/profile/salvatore1114#!/vizhome/wdctest/CoronavirusCOVID-19Dashboard-DailyUpdates).

![image](https://user-images.githubusercontent.com/8287470/76701374-7ae40180-66b8-11ea-83bd-8a2386af8d41.png)
