### ISSUE TITLE
Not Csv Files

### ISSUE THREAD

**Issue by mendes-jom** [CSSEGISandData/COVID-19#66]
reading f
iles on https://github.com/CSSEGISandData/COVID-19/tree/master/archived_data/daily_case_updates
seams to be html files, not cvs  files.

**Comment by CWrecker** [comment]
Nope. Those are indeed csv. Click on them, then click on raw to view the actual csv.

**Comment by mendes-jom** [comment]
Sry:

Look  at the content of file:

 

<!DOCTYPE html>

<html lang="en">

  <head>

    <meta charset="utf-8">

  <link rel="dns-prefetch" href="https://github.githubassets.com">

  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">

  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">

  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">

  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">

  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">

  <link rel="dns-prefetch"
href="https://user-images.githubusercontent.com/">

 



 

Definitively  not a csv file.

 

best regards

José mendes

  _____

**Comment by bicubic** [comment]
You're fetching the HTML page for the file, not the file itself. The files are all csv

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/archived_data/daily_case_updates/01-21-2020_2200.csv

**Comment by mendes-jom** [comment]
Im sorry  ,  Im Using  firefox.on  wibdows 7.

On Page 

https://github.com/CSSEGISandData/COVID-19/tree/master/archived_data/daily_c
ase_updates

Over « 02-12-2020_2200.csv »  using mouse, right button and selecting :
<save link as>  Im saving  the file behind it:  The  file that  I get on my
computer has html content not csv content.

I  joined the file I get

How can I get  your real csv file?

Thanks a a lot

  _____

**Comment by mendes-jom** [comment]
The link  behind is "https://github.com/CSSEGISandData/COVID-19/blob/master/archived_data/daily_case_updates/02-12-2020_1020.csv"

**Comment by mendes-jom** [comment]
Sry.  Didnt intend to "close"

**Comment by CSSEGISandData** [comment]
There are many options to get the CSV files. The easiest and most simple way is to download the zip file for this repository or git clone this repository to get the CSV files locally.
