### ISSUE TITLE
Discrepancy for covid cases in Turkey

### ISSUE THREAD

**Issue by tushartify** [CSSEGISandData/COVID-19#6603]
Refer issue #6562             I can see that WHO has not added any data for new cases since November 14, 2022 
![image](https://user-images.githubusercontent.com/87332298/217270894-83fc394c-baad-49af-a2eb-466ccd5e1f2e.png)
but we can check in raw data that cases have been updated for January 1.
![image](https://user-images.githubusercontent.com/87332298/217274720-66d2f5f2-826f-4339-b24a-5d0f9b4dbd06.png)

Can you please check the discrepancy?

_Originally posted by @tushartify in https://github.com/CSSEGISandData/COVID-19/issues/6562#issuecomment-1420881444_

**Comment by leemyungsub** [comment]
2023년 2월 20일 (월) 오전 8:09, Tushar ***@***.***>님이 작성:

**Comment by CSSEGISandData** [comment]
Hello,

We believe that the discrepancy is due to WHO revising their historical data.

**Comment by tushartify** [comment]
Can you resolve the discrepancy?
