### ISSUE TITLE
US State Level Data Missing

### ISSUE THREAD

**Issue by axelnine** [CSSEGISandData/COVID-19#666]
Hi, is there a reason why US State Level Data is only present for the last 3 days? I can only see zeros for days before 10th March. The individual files contain data even before 10th March.

**Comment by JeroenKools** [comment]
Why is nobody here using the search function? The same issues are being reported hundreds of times.
https://github.com/CSSEGISandData/COVID-19/issues/590

**Comment by aachokey** [comment]
Also #650

**Comment by CSSEGISandData** [comment]
please see issue #590
