### ISSUE TITLE
Missing UK data on mobile app

### ISSUE THREAD

**Issue by williamashfordQB** [CSSEGISandData/COVID-19#667]
Trying to see UK data which should be in the realm of 300-500 cases and it’s not showing on the country list. See below:

![6BE856FB-DB76-443C-897D-AFFAD4BC7185](https://user-images.githubusercontent.com/42339022/76657798-950fc980-656a-11ea-82eb-9babb5040d63.png)

![336E6CEC-F2F3-4DD1-8562-A521036C504B](https://user-images.githubusercontent.com/42339022/76657948-e28c3680-656a-11ea-92d0-a78524a62f25.png)

Appears there’s a reporting bug.

**Comment by przemyslawpluta** [comment]
Related https://github.com/CSSEGISandData/COVID-19/issues/648

**Comment by williamashfordQB** [comment]
I think this is a different bug. The issue you tagged still shows UK data. It’s now missing completely as per above.

**Comment by przemyslawpluta** [comment]
@williamashfordQB most probably all is connected with the latest changes

**Comment by juanpc2018** [comment]
i have Windows Desktop Firefox 74.0 "latest"
same error...
should be 10k tested
800 positive 10 deaths.

**Comment by williamashfordQB** [comment]
Closing as the issue has been rectified.
