### ISSUE TITLE
Australia data incorrect

### ISSUE THREAD

**Issue by JannieP** [CSSEGISandData/COVID-19#669]
The Australian data should be 128+ as of 12 March 2020, yet today it only shows 1
even checking the site https://covid.bio/with-china which feeds off the same data, it shows 128
What's happening to this dashboard.

**Comment by ElijahLynn** [comment]
I do see the data present, and yeah, looks like something is borked, I only see 1 case on the dashboard too. 

https://github.com/CSSEGISandData/COVID-19/search?q=australia&unscoped_q=australia

**Comment by ElijahLynn** [comment]
Crosslinking https://github.com/CSSEGISandData/COVID-19/issues/668

**Comment by ElijahLynn** [comment]
Seems there are a bunch of issues opened for this https://github.com/CSSEGISandData/COVID-19/search?q=australia&type=Issues

**Comment by vaporjet** [comment]
Take a look at #650

**Comment by JannieP** [comment]
Interesting, I did try search prior to posting but somehow missed that one "March 12..."

**Comment by vaporjet** [comment]
Probably related to the technical issues mentioned in #650

**Comment by simongis** [comment]
Appears fixed now
