### ISSUE TITLE
Australia is missing from Dashboard data and data counts seem low

### ISSUE THREAD

**Issue by Shane073** [CSSEGISandData/COVID-19#674]
Hey there,

Couple of issues.

1) Australia is missing from the country table on the dashboard. There is a count of 1 for Australia, in the Northern Territory. Australia now has a count of 199.

2) The overall data count seems low. 

Yesterdays data update for overall data was 128,343. An increase of 2478 on the previous day.

https://www.worldometers.info/coronavirus/ overall count for yesterday was:

Coronavirus Cases: 134,558
Deaths: 4,972
Recovered: 68,934

Yesterdays data dump seems to be about 6000 behind in confirmed cases, 250 behind in reported deaths, and 700 behind in recovered cases when compared to worldmeters.info.

Right now, your total overall count is 137,455 and [worldmeters.info](https://www.worldometers.info/coronavirus/) overall count is 145,240.

Up until yesterday both of your counts were a lot closer than this.

If there is an issue with data on the dashboard I would advise that you put up a notice on the site highlighting it. 

Words to the effect of "We are currently undertaking maintenance, data may be delayed, and incorrect". 

Or take the data down and have a link going to worldmeters.info and give an estimated time that you will have it back up and running.

Media and government agencies are using this data for public broadcasting and information. 

We are grateful for all you have been doing, but please, if there is an issue, you need to make users aware on the dashboard.

**Comment by ElijahLynn** [comment]
Seems there are a bunch of issues opened for this https://github.com/CSSEGISandData/COVID-19/search?q=australia&type=Issues

**Comment by CSSEGISandData** [comment]
A few days ago we ran into technical difficulties and are still working to resolve all the issues. During this period of maintenance you may see strange behavior on the dashboard. Sorry for the inconvenience.
