### ISSUE TITLE
Georgia, US Cases for both Confirmed and Active Disappeared

### ISSUE THREAD

**Issue by afshawnlotfi** [CSSEGISandData/COVID-19#676]
Hi Georgia, US Cases for both Confirmed and Active disappeared.

**Comment by chovy** [comment]
Yes, this has been happening for about 5 days now. Sometimes its accurate but usually not.

**Comment by joonhocho** [comment]
Try https://talksub.com/covid19 for US. It has map, per state data table, news articles.

**Comment by Daemon42** [comment]
It's not just Georgia.   We're also missing..   OR, ID, CO, NM, KS, NE, FL, etc..  
Earlier today it was missing the UK, but it's back now.

**Comment by afshawnlotfi** [comment]
Seems to be resolved
