### ISSUE TITLE
Data Issue starting on February 13

### ISSUE THREAD

**Issue by JeffLoucksPersonal** [CSSEGISandData/COVID-19#68]
Hello,
I built a similar dashboard to show progress of the virus. I wanted to point out that you have a data issue starting on February 13. You change your criteria from confirmed cases to total cases yet you still represent them as confirmed cases. This appears as a large increase in confirmed cases. The data needs to be corrected. The chart is not accurate.

**Comment by jianxu305** [comment]
As far as I know, China started to use a new definition for the "confirmed" to include those who are only "clinically diagnosed" around Feb 13.  Is that the jump you are talking about?

https://www.cnbc.com/2020/02/13/coronavirus-latest-updates-china-hubei.html

**Comment by JeffLoucksPersonal** [comment]
The jump comes from no longer using the confirmed cases in the WHO data to using a second set of data which was previously undisclosed, when combined with confirmed cases becomes total cases. This data point is very hard to compare to previous confirmed cases and brings in to the question what if anything we can be sure about the numbers. Is there now even more undisclosed cases? What are the total case numbers for the days prior to February 13?

**Comment by CSSEGISandData** [comment]
Sorry for the delayed response. We are currently using multiple sources to update the dashboard, along with WHO. These sources can be found in the read me of this repository. The case from Feb 12 to Feb 13 was a change in reporting confirmed cases in Hubei. This change introduced thousands of new cases which is the jump you see in the data.
