### ISSUE TITLE
Timeseries data for 3/13/2020 column is empty

### ISSUE THREAD

**Issue by arik-so** [CSSEGISandData/COVID-19#682]

**Comment by pixelscript** [comment]
I get the impression these updates aren't looked over by a human before they are committed and pushed. I'm grateful for the data and know hard work is involved but you would think they'd give it a once over to confirm they actually included the data they meant to include. Especially when you consider the importance of the data being valid and the sensitivity of the situation.

**Comment by CSSEGISandData** [comment]
Due to the technical issues with the dashboard, 03-13-2020.csv has incomplete data. We have updated this csv to include the proper data update as well as the time series tables.

**Comment by arik-so** [comment]
Thank you very much! However, yesterday's data is still wrong for all the same countries it was wrong for yesterday, resulting in huge jumps in infections.
