### ISSUE TITLE
Empty Data for 03/13/2020 on time series

### ISSUE THREAD

**Issue by masterfego** [CSSEGISandData/COVID-19#683]
The time series data for this date are empty, no number, just blank!
Detected  on Confirmed, Recovered and Death files.

Please can you update these 3 files with actual data?

**Comment by aske-cph** [comment]
Seriously what's going on? There is not one day where the data isn't mangled for hours breaking everyones applications.
Right now the only mitigation strategy seems to be waiting at least 4-5 hours before pulling this data so they can fix all the weird errors.
I very much appreciate the effort but am beginning to suspect something weird going on.

**Comment by CSSEGISandData** [comment]
Due to the technical issues with the dashboard, 03-13-2020.csv has incomplete data. We have updated this csv to include the proper data update as well as the time series tables.
