### ISSUE TITLE
03-13-2020.csv contains missing state data

### ISSUE THREAD

**Issue by louchios** [CSSEGISandData/COVID-19#684]
Nothing for Oregon, Colorado, Florida, etc. Thank you.

**Comment by maceh** [comment]
Also missing most of Australia

**Comment by albertid** [comment]
Missing several states, and the time series data is missing 3/13 entirely.

**Comment by CSSEGISandData** [comment]
Due to the technical issues with the dashboard, 03-13-2020.csv has incomplete data. We have updated this csv to include the proper data update as well as the time series tables.
