### ISSUE TITLE
Double Data: Faroe islands

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#693]
You got Faroe Islands counted twice: once as a part of Denmark and once as a sovereign area. With different data nonetheless: 3 confimed as of 2020-03-13T11:09:29 but then two confirmed as of 2020-03-13T22:22:02. 

(so you got a later report with less confirmed which does not make sense and diminishes confidence in the data)

please correct this.

**Comment by emilianbold** [comment]
Probably related to #650, all recent data is flawed.

**Comment by yetzt** [comment]
This has been resolved. Since there seems to be noone taking care of these issues, i'm closing myself.
