### ISSUE TITLE
Cumulative count for Washington State  counties missing

### ISSUE THREAD

**Issue by epinotes** [CSSEGISandData/COVID-19#702]
From 3/10/2020 the Washington State cumulative counts have been turned to zero.

**Comment by emilianbold** [comment]
Probably related to #650, all recent data is flawed.

**Comment by Hikmer** [comment]
Its really frustrating, some think we should be redeveloping our code and some how magically know what data to filter or ignore.  But data needs to be clean and actuate without constantly changing metadata for any good analysis.  I've spent a lot of time to try and build things out only to see the next release of data includes changes in metadata or flat out errors.

**Comment by Bost** [comment]
@Hikmer I've been using the web service behind the https://github.com/ExpDev07/coronavirus-tracker-api to clean the data for me. They do the job as expected (yea!) except just one incident.. but hey nobody is perfect. And if that's not enough then have a look at my [csv.clj](https://github.com/Bost/corona_cases/blob/master/src/corona/csv.clj) it's not totally up-to-date but I'm willing to help you out. Just issue a ticket in my repo with an appropriate description of your needs.
