### ISSUE TITLE
"Last Update" in daily reports doesn't seem right

### ISSUE THREAD

**Issue by Canoming** [CSSEGISandData/COVID-19#709]
The "Last Update" of many countries are not updated since Mar/12.  Although the numbers are changed, the "Last Update" of some entries are still Mar/11.

For example, in 03-13-2020, the "Last Update" of Italy is 2020-03-11 20:00:00

**Comment by mfisher35** [comment]
agreed, also the 'Confirmed' numbers a larger than what is found for the same date in the 03-11-2020.csv file as well

**Comment by pscheid92** [comment]
Same case for Germany in the daily report.
Date is `2020-03-11T...` but `Confirmed` seems to be correct (or at least bigger than the numbers on the previous two days).

It seems like many other entries got wrong dates, too?

**Comment by CSSEGISandData** [comment]
Due to some technical issues on the dashboard during that time period, the last update field had suffered as a result. We are working to get things back on track. Sorry for the inconvenience.
