### ISSUE TITLE
Tableau WDC based on daily CSVs

### ISSUE THREAD

**Issue by 3verse** [CSSEGISandData/COVID-19#71]
Hi,
for all Tableau users out there, I've created a web data connector to use out of the box, based on the daily data available on this repository.

you can connect to it from tableau public -> new data source ->web data connector -> http://35.211.243.122/api/wdc/html/COVID-19_WDC.html

**Disclaimer:** this is refreshing every 1h using data available from this directory: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports - if the folder structure or naming convention changes again I'll need to update scripts to ensure continuity of service.

Hoping you find this useful, please let me know if any issues.

**Comment by iceweasel1** [comment]
"USGS Earthquake Feed"

Earthquake?

Why not https?

![Bildschirmfoto vom 2020-02-17 17-57-06](https://user-images.githubusercontent.com/49625256/74673245-2596fc00-51af-11ea-9847-b5e9c2d65670.png)

**Comment by 3verse** [comment]
oh

> "USGS Earthquake Feed"
> 
> Earthquake?
> 
> Why not https?
> 
> ![Bildschirmfoto vom 2020-02-17 17-57-06](https://user-images.githubusercontent.com/49625256/74673245-2596fc00-51af-11ea-9847-b5e9c2d65670.png)

oh well, must have left an old page title there, thanks for spotting it ;) - not https yet as I just spun up a micro instance on google cloud to serve this, though it would be useful to put it out there for everyone to use as a priority

**Comment by iceweasel1** [comment]
@3verse No problem. ;-)

**Comment by npaladug1** [comment]
@3verse 

Can you share the HTML and javascript file that you created for Covid 19 Data
