### ISSUE TITLE
Numbers of confirmed cases in Sri Lanka should be updated

### ISSUE THREAD

**Issue by osusara** [CSSEGISandData/COVID-19#719]
Latest update

- 10 confirmed cases
- 9 active
- 1 cured
- 0 deaths

**Comment by giordano** [comment]
#650

**Comment by osusara** [comment]
The latest update for Sri Lanka

- 18 confirmed cases
- 16 active
- 1 cured
- 0 deaths

Source: Local media

**Comment by osusara** [comment]
The latest update (17.04.2020) for Sri Lanka

- 43 confirmed cases
- 41 active
- 2 cured
- 0 deaths

Source: Local media
