### ISSUE TITLE
Diamond Princess data duplicated

### ISSUE THREAD

**Issue by tipichris** [CSSEGISandData/COVID-19#72]
The feature server 'Cases' layer currently contains two entries that both appear to refer to the Diamond Princess. One has object ID 37 and Country_Region 'Others', the second is object ID 47 and Country_Region 'Diamond Princess'. Both have NULL for Province_State, and both have the same coordinates.

**Comment by iceweasel1** [comment]
This issue can be merged with the other one. > #70

**Comment by CSSEGISandData** [comment]
Hello, we have removed the duplicate. Thanks!
