### ISSUE TITLE
proposal: insightful commit messages, line-based updates

### ISSUE THREAD

**Issue by jgehrcke** [CSSEGISandData/COVID-19#722]
Lovely collaboration going on here in this repository. It's such a gorgeous development to follow.

I have two relatively serious wishes that would facilitate this collaboration even much further:
- usage of explicit, meaningful commit messages. `"update"` has no information content.
- transpose tables: each row should represent a point in time. One advantage would be: the diffs become meaningful (for example, then it's easy to see in the diff when data is amended in _hindsight_). This will also scale better over the coming months.

**Comment by JiPiBi** [comment]
For the moment the time series file has about 420lines and 60columns or fields. 
IMHO, If you want to agregate countries as CHINA or US or Continent  with common tools like for example in excel , its seems easier to keep the current orientation 
If you are using tools like pandas , you can already transpose the matrix to meet  what you want 

Numerous people have based their code on the current orientation , it seems difficult to change now the dataset

**Comment by ms82494** [comment]
I agree with the first suggestion, but not the second one. While I think an "unpivoted" design is more useable, changing it now would cause more work for everyone to switch now. There's no real limit to how many columns a csv file can have and, as JiPiBi points out, going from a "pivot table" style layout to a vertical one is not that hard. Python users, look up [pandas melt](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.melt.html).

**Comment by jgehrcke** [comment]
> While I think an "unpivoted" design is more useable, changing it now would cause more work for everyone to switch now

Yes, of course this is a strong arguments. Maybe worth considering for the next pandemic :tada:
