### ISSUE TITLE
# confirmed cases dropped to 0 in many locations in the last 4 days

### ISSUE THREAD

**Issue by bbdundar** [CSSEGISandData/COVID-19#723]
Hi,

I noticed that several entries in the confirmed cases file all of a sudden became 0 in the last 4 days. Could you please correct this?

Here is an example, there are many more:
COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
"Santa Clara County, CA",US,37.3541,-121.9552,0,0,0,0,0,0,0,0,0,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,9,11,11,20,20,32,38,38,0,0,0,0
The number of confirmed cases cannot go from 38 to 0, correct?

Thanks for the amazing effort!

**Comment by giordano** [comment]
#650

**Comment by CSSEGISandData** [comment]
please see issue #590
