### ISSUE TITLE
Total Confirmed does not match confirmed cases by Country/Region

### ISSUE THREAD

**Issue by przemyslawpluta** [CSSEGISandData/COVID-19#73]
It appears that dashboard does not display correctly **Total Confirmed** cases.

At the moment dashboard indicates **71,902** cases but if you sum up all the numbers based on the list below it ads up to **71,448** off by **454** number which seems to be a duplicate of **Diamond Princess** and old **Others** as per https://github.com/CSSEGISandData/COVID-19/issues/72 & https://github.com/CSSEGISandData/COVID-19/issues/70

![cases](https://user-images.githubusercontent.com/221250/74684706-76651f80-51c4-11ea-8418-462ee10f304a.jpg)

**Comment by ricir** [comment]
Agree.

**Comment by iceweasel1** [comment]
Why must a third issue be opened now? There are already two where this problem is discussed... You linked the two yourself. #70 #72

**Comment by przemyslawpluta** [comment]
@iceweasel1 separate issue not reported but caused by connected factors as indicated by other cases.

**Comment by CSSEGISandData** [comment]
We have removed the duplicates, and the total count should match up with all numbers added. Thanks for pointing it out!

**Comment by bicubic** [comment]
The quality of this dataset and the competence of @CSSEGISandData is increasingly looking suspect. Good effort by them to collate stats, terrible execution and mismanagement. Still unanswered issues for why the dashboard doesn't match the datasets, internal inconsistencies in the dashboard figures, both dataset and dashboard not matching the stated sources. 

News sources shouldn't be quoting these figures.

**Comment by bjarkimg** [comment]
@bicubic and not the same dataset since I'm getting always a good day lag when working with it in Power Bi, 
Should be reported only when **full day** data is confirmed, other wise giving false hope of declining cases etc, IMO.

-> http://bit.ly/38qeMbz
![image](https://user-images.githubusercontent.com/1289419/74724708-9af8e000-5234-11ea-977d-b99856945aa7.png)

**Comment by dawenx** [comment]
This depends on what do you mean by a day, what’s the time zone. Current release uses UTC which does not give good picture of the day as China only releases data for a few provinces. See discussion in #60  and solution I used in [here](https://github.com/CSSEGISandData/COVID-19/issues/60#issuecomment-586751518) here
