### ISSUE TITLE
[Android App] Developed COVID-19 Android Application based on CSSEGISandData database

### ISSUE THREAD

**Issue by TheWCKD** [CSSEGISandData/COVID-19#738]
After Google suspended my COVID-19 application from Play Store, I decided that I will share my first ever application with all of you, here. 

Its data it's maily based on CSSEGISandData database here, huge thanks for the maintainers!

Reddit moderators seem to also delete my posts regarding this application with no reason, so the only solution I have, instead of throwing more than 3 months of development out of the window, is to share my application with you guys, here, hoping that you will appreciate my work.

[Here's the github to my app](https://github.com/TheWCKD/CoronaVirus-Outbreak-App)

Feedback is greatly appreciated!

**Comment by mmonfort2908** [comment]
have not downloaded yet but from looking at your link it looks great. Good work!

**Comment by TheWCKD** [comment]
> have not downloaded yet but from looking at your link it looks great. Good work!

Thank you, looking forward to hearing from you after you try it!

**Comment by s-moran** [comment]
The issues list should definitely not be a place for advertising projects. Someone close this please.
