### ISSUE TITLE
Transparent & consistent data pipeline

### ISSUE THREAD

**Issue by yy** [CSSEGISandData/COVID-19#740]
Hi, because there are too many inconsistency issues in the dataset, as an alternative, I'm creating a more transparent data workflow here: https://github.com/yy/covid19-data The goal is creating a highly transparent and automated workflow that can ingest multiple data streams. 

Right now, it's pulling the data from [Our World in Data website, which is essentially a cleaned version of WHO daily reports](https://ourworldindata.org/coronavirus-source-data) and merging with metadata from Worldbank (for producing this visualization: http://yyahn.com/covid19/). 

I've also created a pipeline for converting between country names and ISO 3166 Alpha-3 codes. 

If you're frustrated with this dataset, please feel free to join https://github.com/yy/covid19-data and help us!

**Comment by Bost** [comment]
I've got only one thing: could you make it `https`? Thanks

**Comment by JiPiBi** [comment]
Great work!

I dont see the interest of the inner circles : confirmed cases and deaths as they are all of the same small size  and so dont give comparative information

**Comment by yy** [comment]
Thanks for the comments about the visualization. But my primary goal is making the data pipeline automatic, accurate, and transparent! I've created an organization and move the repository to: https://github.com/covid19-data/covid19-data
