### ISSUE TITLE
Missing 1 death in France on Sat Feb 15th.

### ISSUE THREAD

**Issue by MaBeuLux88** [CSSEGISandData/COVID-19#75]
Chinese tourist 80yo.
Source: https://time.com/5785366/coronavirus-death-outside-asia-france/

**Comment by CSSEGISandData** [comment]
That case was added to the dashboard at 11:59 AM, Feb 15 (ET). Thanks!

**Comment by MaBeuLux88** [comment]
My bad. That's correct I did a mistake. I will track it down. Sorry for the disturbance.
