### ISSUE TITLE
Italy and Qatar map pointer incorrect

### ISSUE THREAD

**Issue by tahmidefaz** [CSSEGISandData/COVID-19#755]
Selecting Italy from the sidebar takes me to Qatar, and selecting Qatar takes me to Cyprus on the map. The total deaths and total recovered data on the right also do not reflect the selected country. For Italy, it shows Qatar's and for Qatar, I suspect, it shows that of Cyrus.

I really appreciate you keeping track of this pandemic. I know its quite challenging, thank you for all your help! You are the heroes of the world. 🙂

**Comment by juanpc2018** [comment]
yes, here latest Firefox Windows Desktop
Italy GPS pointer is in Curacao.

Total Confirmed 1
Total Deaths: 0
Total Recovered: 0

**Comment by tahmidefaz** [comment]
Seems to be working fine now. Closing.
