### ISSUE TITLE
Please Fix: Data is Malformed

### ISSUE THREAD

**Issue by sibblegp** [CSSEGISandData/COVID-19#762]
https://covid.bio is down. This means the data is malformed. Please fix.

**Comment by JannieP** [comment]
Yeah, please get it back up. I really like you how you present the data layers.
Were you able to establish where the issue is, as the JHU dashboard still runs fine.
I suspect they may have changed some of the structure, maybe you could adapt how you read the data. 
Good luck anyway

**Comment by sibblegp** [comment]
@JannieP Thanks! Every day there's something and I don't have much time to dedicate to the site. I am going to build everyone's favorite chart of top countries infection rate over days once the data starts working again.
