### ISSUE TITLE
I created public API for this data

### ISSUE THREAD

**Issue by aashari** [CSSEGISandData/COVID-19#768]
You can refer to my repository:
https://github.com/aashari/mq-covid-19

I make a publicly available API for this data

Example
```
https://mq-covid-19-update.s3-ap-southeast-1.amazonaws.com/api/data.json
https://mq-covid-19-update.s3-ap-southeast-1.amazonaws.com/api/data/2020-03-14.json
```

**Comment by jcherian-analytics** [comment]
thank you bud

**Comment by 161134050** [comment]
I don't see how this is an issue

**Comment by dyske** [comment]
Great. Thank you. I was just thinking we need this.

**Comment by sibblegp** [comment]
Could you do this for the time series too?

**Comment by aashari** [comment]
Hi @sibblegp it is inprogress
