### ISSUE TITLE
Consistency of countries names

### ISSUE THREAD

**Issue by peppeg** [CSSEGISandData/COVID-19#780]
I really appreciate your effort and i thanks you so much!
This data helps to create reports, statistics and more...

But can i ask a bit of consistency in the format/names?

Before --> After
South Korea --> Korea, South
Czech Republic --> Czechia
Vatican City --> Holy See
Republic of Ireland --> Ireland
Palestine --> occupied Palestinian territory

Thanks in advance!

**Comment by AaronForce1** [comment]
Hong Kong and Macau SARs are also missing now.

**Comment by greg-minshall** [comment]
hi, all.  some issues (maybe not these) of country names are political, as names tend to be.

my thought, at least for my own code, is to punt, in this case to the World Bank.  (obviously, how the World Bank decides on country names is *also* political; i'm just trying to duck.)  they have this page, for example, which lists all countries [https://data.worldbank.org/country](url).  if you click on a country, then click on the circle-i alongside the country name, you get some of their meta-data about the country, including the ID, a three-character code ("AFG" for Afghanistan, for example).

**Comment by Location-Artistry** [comment]
Agree that country names are usually a political matter, but this is of a technical nature.
Also wanted to reiterate that it is incredible to have access to this data on a public repository, and I hope this will allow unique analysis and visualizations to generate insights.
Since the data is in CSV format, using Korea, South causes a problem when parsing that field in the CSV records.  This seems to be the only country name with a comma contained within it. 
During processing this causes the fields in South Korea to display improperly.  I have created a simple js widget to parse each record and display each country on screen, and also build the url to the daily case data dynamically.  Additionally I have written a simple server in node that parses the CSV, but then also converts each record into GeoJSON to be displayed in a ArcGIS JS API map.  Quick link to simple widget in Codepen: https://codepen.io/erickerney/full/BaNrrbw

**Comment by greg-minshall** [comment]
@Location-Artistry also US Virgin Islands has a comma in it.  but, the JHU data has "quotation marks" around fields with commas in them -- tools should recognize those and assign those fields to one column.  (R does it, and i'm sure excel and other tools can; there's a linux package 'csvtools' that i seem to remember understands quoting.)

**Comment by Location-Artistry** [comment]
I’m using vanilla JavaScript, and the program sees it as two different
fields.  I’m sure there is some way in code to say that if field is
surrounded by quotations, then treat as one field.  I suppose a rather
crude workaround would be an IF statement that checks whether: South Korea
or  Virgin Islands.  Thanks for the heads up!  Are you having any luck
creating interesting results?

**Comment by greg-minshall** [comment]
hi, @Location-Artistry.  i'm not at all equipped for javascript, so even interpreting google results is probably beyond me.  but, if i google something like "javascript csv reader", i seem to get some hits.  if i were you, i'd probably want to use some such thing.

one (the data provider) could also move away from "human friendly" (but, "computer unfriendly"? :) names to ISO3166 three-letter names.  (which is what is being used in [https://github.com/lazd/coronadatascraper](url); and, i may also switch to them, or at least output them in addition to the more recognizable name.)

**Comment by CSSEGISandData** [comment]
Sorry for the inconvenience. We are working on refactoring our older naming convention to match that of the U.S. State Department.

**Comment by greg-minshall** [comment]
@Location-Artistry i have converted my small supplement to output ISO3166 codes.  you might find them useful.  (they are basically the JHU daily case data, with the countries -- hopefully! -- cleaned up.)  your non-.csv reader, hopefully, will work on them.

you can find them in derived/csvs at [https://gitlab.com/minshall/covid-19](url).

cheers, Greg

**Comment by Location-Artistry** [comment]
Thank you for the response.  Again I am very appreciative of the work by
John Hopkins that is being done to house the worldwide data for this
epidemic.
Will keep working on a method to parse the two outlying country names.
Regards,
Eric Kerney

**Comment by Location-Artistry** [comment]
@greg-minshall
Would like to see your cleaned up data, cannot get the link to work at this
time.
Still working on my process of Covid CSV Data->JSON->GeoJSON->Serve GeoJSON
as a cloud function on Firebase.
My goal is to be able to create my own Geoservice to map in ArcGIS JS API
and Leaflet.js.
Eric

**Comment by greg-minshall** [comment]
@Location-Artistry good luck with your geoservice/leaflet, etc.  if you have more problems with my site, let me know (note that it is on git*lab*, not gibhub).  cheers.
