### ISSUE TITLE
France pointing to overseas territory instead of mainland

### ISSUE THREAD

**Issue by thatgeeman** [CSSEGISandData/COVID-19#782]
The "Country/Region/Sovereignty" view in the home page points France to Saint Barthelemy, France 17.9000° N, 62.8333° W instead of Paris, France 48.8566° N, 2.3522° E.

![Capture](https://user-images.githubusercontent.com/4496097/76700106-41a99280-66b4-11ea-9b09-eb6fc4d14ee1.PNG)

**Comment by JiPiBi** [comment]
see #705

**Comment by thatgeeman** [comment]
Not sure if related, but the problem is that selecting France in the map takes you to St Barthelemy. Correct me otherwise, has it not to do with the internal mapping (provided latitude, longitude) of whatever geo visualisation package they are using?

**Comment by JiPiBi** [comment]
Not completely related  but nevertheless a bit 
Saint Barthelemy is a French Territory , if the selection of France for Long Lat is badly linked in the column Country/Region, that is the result 

The issue you pointed out is real , and the explanation must be just above


Province/State | Country/Region | Lat | Long
-- | -- | -- | --
France | France | 46.2276 | 2.2137
St Martin | France | 18.0708 | -63.0501
Saint Barthelemy | France | 17.9 | -62.8333
French Polynesia | France | -17.6797 | 149.4068
French Guiana | France | 3.9339 | -53.1258
Mayotte | France | -12.8275 | 45.1662

**Comment by JiPiBi** [comment]
@thatgeeman 
Seems that the fix has been made , up to you to close the issue
