### ISSUE TITLE
Longitude and latitude for Mauritania case counts are wrong!

### ISSUE THREAD

**Issue by rosericazondekon** [CSSEGISandData/COVID-19#786]
Longitude and latitude for Mauritania case counts are wrong. On the map, the marker is placed in Niger. Please, correct this. 
Again, awesome job!

**Comment by graphguy** [comment]
Verified this still looks to be a problem today (March 17).

**Comment by graphguy** [comment]
Here's an alternate lat/long I'm using:

if country_region='Mauritania' then do;
 lat=19.5488367; long=-10.3433656;
 end;

**Comment by pslh** [comment]
This problem still persists today (2020-05-21) at least for the files UID_ISO_FIPS_LookUp_Table.csv, time_series_covid19_*.csv

**Comment by pslh** [comment]
There is a sensible looking fix for this in pull request #1305

**Comment by CSSEGISandData** [comment]
Thanks @pslh - fixed in latest.
