### ISSUE TITLE
can we get more than one update per day?

### ISSUE THREAD

**Issue by SimonHausdorf** [CSSEGISandData/COVID-19#803]
It seems like that the dashboard https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 is getting more frequent data.

Is there any other source which updates more often or is it planned that this repo will also get update more often?

**Comment by rsignell-usgs** [comment]
@deepseadawn, can you help us out here?   

Is ESRI getting it's data from somewhere other than this JHU repo, and if so, is it publicly available?

**Comment by deepseadawn** [comment]
Esri is provisioning data from the WHO<https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports>, CDC<https://www.cdc.gov/coronavirus/2019-ncov/index.html>, ECDC<https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases>, NHC <http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml> and DXY<https://3g.dxy.cn/newh5/view/pneumonia?scene=2&clicktime=1579582238&enterid=1579582238&from=singlemessage&isappinstalled=0> and local media reports, which is also what JHU is using. For much, much more please see our hub https://coronavirus-resources.esri.com which is updated several times per day…


------
Dawn Wright (she/her/hers), Ph.D. & GISP | Esri Chief Scientist
Esri | 380 New York St | Redlands, CA 92373 | USA
T 909 793 2853 x2182 | M 909 362 6817 | dwright@esri.com<mailto:dwright@esri.com> | esriurl.com/scicomm<http://www.esri.com/sciences>
esriurl.com/dawn<https://urldefense.proofpoint.com/v2/url?u=http-3A__esriurl.com_dawn&d=DwMGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=XlutqUdSIpme1jvzl1iWog&m=XO9X9gVsiBGUg5I9jNyq8GZnFSL9O-I78AexOtVJavg&s=Z3mNQ3SvFiZ7TmJUS_cfuW7US_czkXyRpRZuuX00zv8&e=> | @deepseadawn

THE SCIENCE OF WHERE ®

**Comment by SimonHausdorf** [comment]
But why is the data here only provided once a day?

**Comment by deepseadawn** [comment]
Sadly, I am not with Johns Hopkins so cannot answer that for you. Why not try jhusystems@gmail.com<mailto:jhusystems@gmail.com>? For questions on what Esri is provisioning and how often, I would refer you to Dan Pisut <DPisut@esri.com>, part of our Esri Living Atlas team that is helping Johns Hopkins (but it is Johns Hopkins’ repo not ours), as well Ryan Lanclos <RLanclos@esri.com> of our broader *Esri* COVID-19 response team (and again, for https://coronavirus-resources.esri.com )

Cheers,

Dawn
Esri Chief Scientist

**Comment by rsignell-usgs** [comment]
@deepseadawn, thanks so much for joining this conversation!   
So from following your links, it looks like the ESRI data is available in CSV form here:  
https://opendata.arcgis.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1.csv
And updates several times an hour?

**Comment by deepseadawn** [comment]
Ryan Lanclos RLanclos@esri.com<mailto:RLanclos@esri.com> should be able to confirm for you …

**Comment by rsignell-usgs** [comment]
Okay, I'll ping him and report back.

**Comment by sbreyer** [comment]
the JHU data is being tested for updates every 20 minutes and if there is a source update it is applied.

**Comment by rsignell-usgs** [comment]
@sbreyer , I'm confused.   Are you getting your JHU data from https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data ?
At the time of this writing, this data was last updated 17 hours ago!

**Comment by sbreyer** [comment]
the JHU data is delivered to Esri to update our live services every 20 minutes. Once a day the Github site is being updated with Daily totals. Sorry for the confusion.

**Comment by SimonHausdorf** [comment]
> @deepseadawn, thanks so much for joining this conversation!
> 
> So from following your links, it looks like the ESRI data is available here:
> https://coronavirus-resources.esri.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1/data
> and in CSV form here:
> https://opendata.arcgis.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1.csv
> 
> And it looks like this updates several times an hour?

I think this is exactly what I am looking for!

**Comment by deepseadawn** [comment]
According to my Esri colleague Sean Breyer, the JHU data are delivered to Esri so that we update our live services **every 20 minutes.** The Github site is updated with daily totals, and that is what is only updated once a day.

**Comment by rsignell-usgs** [comment]
So @sbreyer and @CSSEGISandData  just to make sure I've got this right:

* The CSV files are updated daily at: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

* The CSV file is updated every 20 minutes at: https://opendata.arcgis.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1.csv

**Comment by ryanwoconnor** [comment]
@rsignell-usgs is that csv name static? aka https://opendata.arcgis.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1.csv

I need to make sure I can rely on it

**Comment by cjlove72** [comment]
The dataset at https://opendata.arcgis.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1.csv no longer appears to be getting regular updates - the most recent entries are from Australia and were made at 2020-04-17T03:38:35.000Z which is almost 24 hours ago :(

Is there another dataset that people are using to get more up to date stats now?
