### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by BenAveling** [CSSEGISandData/COVID-19#808]
The current date format is mm-dd-yy.

It would be best to use yyyy-mm-dd.

I could make the change and make a pull request, but if the files are being autogenerated, there's probably not much point.

**Comment by weskerfoot** [comment]
I agree, it's better for sorting.

**Comment by d3zd3z** [comment]
This would avoid me needing the following code:
```python
def asndate(name):
    """Decode one of their filenames in a way that is more easily sortable by date"""
    return int(name[6:10]) * 10000 + int(name[3:5]) + int(name[0:2]) * 100
names = glob.glob('*.csv')
names.sort(key=asndate)
```

**Comment by Bost** [comment]
> It would be best to use yyyy-mm-dd

Do you realise such a change would break about any tool parsing the csv files from this repo? NEVER EVER CHANGE THE FORMAT OF YOUR DATA!
#238

**Comment by BenAveling** [comment]
> Do you realise such a change would break about any tool parsing the csv files from this repo?
 
At the moment, there's a lot of tools out there that can read CSV that cannot read these files.

**Comment by BenAveling** [comment]
A backwards compatible, if ugly, option would be to duplicate the csv files. That could be done in the current directory, or in a parallel directory.

**Comment by Location-Artistry** [comment]
This is my clever/not so clever way of handling the date in javascript below.
Add 1 to month date due to 0 position in array, subtract 1 from day to get date from yesterday, if month is less than 10 than append 0 in front of month(not necessary now but who knows?), add date at end of dynamic url string, followed by .csv extension, get data via fetch API!

![EK_COVID_Dynamic_Daes](https://user-images.githubusercontent.com/55369132/76767405-edfc7f00-676f-11ea-9eac-87eb62b23b20.jpg)

**Comment by BenAveling** [comment]
+2 options

Option 3: change the format from mm/dd/yy to mm/dd/yyyy 

This would break some code, but not other code. For e.g. @d3zd3z 's code above would still work, if only up until the end of the year. 

Option 4: add an extra row with yyyy-mm-dd format, as per ISO

This would also break some existing code, but maybe less than the earlier options.

My preference would be to create new files, but just putting the options on the table.

**Comment by BenAveling** [comment]
PS. If we don't change anything in the files, then we should change the README.md in csse_covid_19_data to accurately describe the format.

It currently says "Date fields: M/DD/YYYY (UTC)"

It would be more accurate to say "Date fields: M/DD/YY (UTC)"

Or maybe even "Date fields: M/DD/YY". 

I don't think it makes sense to say UTC when there's no date stamp.

**Comment by cipriancraciun** [comment]
@BenAveling Given how many people are already using this dataset in the current format, I think such a change would break everything once more.

Moreover, in order to keep things tidy and help the JHU team, would you consider closing this issue and following #318 which discusses the same subject and seems to have the most up-votes.

**Comment by BenAveling** [comment]
Given that we've just seen totally new files introduced that broke everyone's scripts for no great gain, I don't think "we value back compatibility" carries much weight.

**Comment by phanidevarakonda** [comment]
Hey Guys,

I was wondering -Is there any way to get time series data? I have followed threads similar to this one and failed to get any answers? The only way I could see was find members who committed at an older date stamp and download their copy of it.

Please let me know if you have a smooth way of dealing with this
Thank you!

**Comment by cipriancraciun** [comment]
@phanidevarakonda could you be more specific in what you mean by:
> Is there any way to get time series data?

**Comment by phanidevarakonda** [comment]
Hi @cipriancraciun .Thank you for your swift response. As of now, the repository shows the latest COVID case count to date, say august 16. It doesn't show the previous day's cases and just rewrites the old case total count. The next time the authors commits, I assume the cases will update to showcases up to date. I am trying to gather COVID test data by ZCTA for every 15 days or so. I was wondering if there is any way to do this?
I hope i was clear!. Please let me know if I should explain better?!
Thanks once again.

**Comment by cipriancraciun** [comment]
@phanidevarakonda I don't know exactly at what files you are looking at, but all the series and daily series contain the total cumulative cases for that date.  You can easily extract the delta for a day by substracting the current value with the previous value.

If you want something already processed, take a look at my derived dataset available at:
> https://github.com/cipriancraciun/covid19-datasets

**Comment by phanidevarakonda** [comment]
Hey @cipriancraciun 
Thank you for the information. I am sorry but I couldn't find anything as such in this dataset-[https://github.com/nychealth/coronavirus-data]. I am working on the new york city dataset provided by the above link and it does not provide data by date.
I would really appreciate if you could have a look at it and get back to me?
Thanks! Have a great day!

**Comment by cipriancraciun** [comment]
@phanidevarakonda I'm sorry but I'm afraid that the repository you've mentioned has no relation with this repository where this issue is being discussed.

I would suggest opening an issue is that repository.
