### ISSUE TITLE
Data issue/discussion for Others/Japan/USA

### ISSUE THREAD

**Issue by dawenx** [CSSEGISandData/COVID-19#81]
There seems to be some issue and potentially double counting regarding to Others/Japan/USA. 

See below screenshot on JHU's dashboard as 10:07am EDT on 02/19. In particular, **Others has 621, Japan has 74 and USA has 29** (including the 14 cased transferred out the diamond princess cruise ship). The total for Japan, cruise ship and USA is **724**. I don’t know what's the source for JHU for those 3 numbers, but those 14 patients who were transferred to US probably is double counted (in Others and USA).

![Screenshot_2020-02-19 Coronavirus COVID-19 (2019-nCoV)](https://user-images.githubusercontent.com/26723038/74850041-79b4f400-5307-11ea-88a4-0a8198fb87e1.png)

In our dashboard (http://ncov.bii.virginia.edu/dashboard/) and our primary data source is tencent and the data was fetched at 10am EDT on 02/19. See below screenshot as 10:09 EDT. Our number for Japan is 616 (including the cruise ship) and 15 for USA (we do not include those 14 cases). The total for cruise ship, Japan and USA is: **631**.
 
![Screenshot_2020-02-19 COVID-19 Surveillance Dashboard](https://user-images.githubusercontent.com/26723038/74850185-a963fc00-5307-11ea-834a-4e58538dad15.png)
 
Below is screenshot from tencent at 10:10am EDT on 02/19 (it's in Chinese) and it shows Japan as 616 and USA as 15:
 
![Screenshot_2020-02-19 实时更新：全国新冠肺炎疫情最新动态](https://user-images.githubusercontent.com/26723038/74850222-b385fa80-5307-11ea-9988-6c16199a987c.png)

The question for all: 
- what’s the correct number for Japan (including the cruise ship) and USA?
- how do we as community keep track of transferred cases?

**Comment by dawenx** [comment]
on BBC's news article updated around 11am EDT 02/19, it shows:

`At least 542 passengers and crew on the Diamond Princess have so far been infected by the Covid-19 virus - the biggest cluster outside mainland China. `

Source:  https://www.bbc.com/news/world-asia-51555420

**Comment by CSSEGISandData** [comment]
Thanks for your feedback. We're checking the issue now.
