### ISSUE TITLE
France Data are wrong for 15th of March 

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#816]
127 deaths and 5423 cases announced in France for 91deaths and 4511cases in the time series as well as in the daily report

Region| Confirmed cases
-- | --
Auvergne-Rhône-Alpes | 523
Bourgogne-Franche-Comté | 412
Bretagne | 207
Centre-Val de Loire | 71
Corse | 115
Grand Est | 1 378
Hauts-de-France | 507
Ile-de-France | 1 209
Normandie | 143
Nouvelle-Aquitaine | 144
Occitanie | 243
Pays de la Loire | 98
Provence-Alpes-Côte d’Azur | 330
Total Mainland | 5 380
Guadeloupe | 6
Saint-Barthélémy | 3
Saint-Martin | 2
Guyane | 7
Martinique | 15
Mayotte | 1
La Réunion | 9
Total Territories | 43

**Comment by JiPiBi** [comment]
![image](https://user-images.githubusercontent.com/44967630/76716269-eae19e80-672f-11ea-8686-6135741ed488.png)

**Comment by JiPiBi** [comment]
Wrongly closed

**Comment by thibautlouis** [comment]
HI JiPiBi, where do you get the data for France region by region ? 
Cheers,

Thibaut

**Comment by massix** [comment]
> HI JiPiBi, where do you get the data for France region by region ?
> Cheers,
> 
> Thibaut

Hi Thibaut, this is the official source for French data on COVID-19, it is updated on a daily basis at around 6PM.

Cheers

https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde

**Comment by pierebean** [comment]
![image](https://user-images.githubusercontent.com/53879706/76737049-59dae980-6768-11ea-9623-d44d592a18e1.png)
Hi,
Indeed the case count stoled twice already. There is something wrong with the data.

**Comment by JiPiBi** [comment]
Hi @thibautlouis 
I confirm the link given by @massix 

I manually copy the data in an excel sheet(I could a bit automatized, but ..)
When values are available, I also take the reanimation numbers at any level (region or country )

I asked for available data (csv format) at santepublique by mail, but they say me that the site was the only source, in clear they have no time for that 
Great difference with another site , the Italian one ,where data for province or region are available and quite detailled
