### ISSUE TITLE
Error (?) number of deaths at 19/02/2020 and 20/02/2020

### ISSUE THREAD

**Issue by DataEnthusiast84** [CSSEGISandData/COVID-19#83]
I analyse the database and the dashboard. 

In the dashboard is reported nr of deaths = 2014.
In the DB (at the 19/02/2020) reported 2007 deaths.

The difference it's in this country:

Dashboard | Country | Value in the Database
12 | Heilongjiang Mainland China | 11
5 | Guangdong Mainland China | 4
2 | Hong Kong Hong Kong | 1
2 | Iran | 0
2 | Shanghai Mainland China | 1
1 | Yunnan Mainland China | 0

EDIT 20/02/2020
In the dashboard is reported nr of deaths = 2130.
In the DB (at the 19/02/2020) reported 2122 deaths.

**Comment by CSSEGISandData** [comment]
Hello, the dashboard and GitHub are updating in different pace. Dashboard is updating about every 15 min and the GitHub updating at least once a day. There could be some data gap between them. Thanks!
