### ISSUE TITLE
Data got on ECDC site seem correct

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#830]
Obtained at this link :
https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

Extract and sum for EU

EU | (Plusieurs   éléments) |  
-- | -- | --
  |   |  
CountryExp | Somme de NewConfCases | Somme de NewDeaths
Albania | 38 | 1
Austria | 655 | 1
Belgium | 689 | 4
Bulgaria | 41 | 2
Croatia | 37 | 0
Cyprus | 21 | 0
Czech Republic | 214 | 0
Denmark | 827 | 0
Estonia | 115 | 0
Finland | 210 | 0
France | 4499 | 91
Germany | 3795 | 8
Greece | 228 | 3
Hungary | 31 | 0
Ireland | 129 | 2
Italy | 17750 | 1441
Latvia | 26 | 0
Lithuania | 9 | 0
Luxembourg | 38 | 1
Malta | 18 | 0
Netherlands | 959 | 12
North Macedonia | 13 | 0
Poland | 104 | 3
Portugal | 169 | 0
Romania | 113 | 0
Serbia | 46 | 0
Slovakia | 44 | 0
Slovenia | 181 | 0
Spain | 5753 | 136
Sweden | 924 | 1
Turkey | 2 | 0
United Kingdom | 1140 | 21
Total général | 38818 | 1727

**Comment by pmos69** [comment]
Not really.
Data from Portugal is incorrect.
Correct data from the Portuguese authorities here: https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/

**Comment by JiPiBi** [comment]
If you look at the curve **Evolução diária do número de Casos Suspeitos,** 
it seems that the ECDC for 15th corresponds to Portugal values from the 14th , and the data from Portugal seem to be published everyday at 12pm ( which for me is the best) . As ECDC makes its extract at a certain hour of the day , I suppose that they take the last official available value ?

**Comment by JiPiBi** [comment]
@pmos69 more about Portugal, if you look at the confirmed curve alone , the rate of increase seeems as everywhere geometric and very high (almost 1.5 )

**Comment by pmos69** [comment]
@JiPiBi Yes, the numbers don't look good. Very steep curve. Worse than most countries.

**Comment by matjung** [comment]
You can also get that Excel data from ecdc in csv format
https://www.micro-work.net/covid/ecdccsv.php/Ger
It looks like some statistical offices did not work at the weekend.
The numbers for Sat/Sun could be inflated
