### ISSUE TITLE
Congo (Brazzaville) centroid is in Democratic Republic of Congo

### ISSUE THREAD

**Issue by graphguy** [CSSEGISandData/COVID-19#836]
You have a data row listed for Congo (Brazzaville) / aka, Congo / aka, Republic of the Congo ...
but the coordinate you give for it (-4.0383, 21.7587)
is in Congo (Kinshasa) / aka, Democratic Republic of Congo (the larger country to the southeast).

Here's the coordinate plotted on a Google map:
https://www.google.com/maps/place/4%C2%B002'17.9%22S+21%C2%B045'31.3%22E/@-3.4133501,19.4697723,6z/data=!4m5!3m4!1s0x0:0x0!8m2!3d-4.0383!4d21.7587?hl=en

Unless I'm confused! (it *is* a Monday morning, after all) :)

**Comment by graphguy** [comment]
Looks like the data is using the same lat/long for Congo (Brazzaville) and Congo (Kinshasa).

**Comment by FottyM** [comment]
I see now Congo(Brazzaville) pointing to Congo(Kinshasa) and the Republic of the Congo(Brazzaville) pointing to itself.

**Comment by CSSEGISandData** [comment]
Thanks @graphguy and @FottyM - has been corrected.
