### ISSUE TITLE
Too many people on internet - limit your traffic

### ISSUE THREAD

**Issue by Bost** [CSSEGISandData/COVID-19#845]
The internet is collapsing in some countries. I'm listening to the news right now... e.g. in rural France internet is really lame right now. (Too many people sitting at home watching youtube, I guess...)

Make sure your dashboards, tools etc. don't transfer unnecessary data, so they stay usable.

**Comment by JiPiBi** [comment]
No only Youtube to occupy the children , but also numerous people must work at home with the huge increase in confinment (probably even worse like in Spain and Italy, following new presidential announcements at 20:00 this evening)  
Big companies like automakers are stopped and alimentary shops are crowded.

The values for France are the same than Italy 8-9  days ago in Discovered cases  , but more important to follow is the number of people in ICU  : 400 people yesterday  + 100 by comparison with Saturday (the rate of increase for this value is also high)

**Comment by maxibor** [comment]
Please only open issue directly relevant with the github repository.
Other issues just bring clutter and make it harder for maintainers to keep track of real issues to address.
Can you please close your issue @Bost ?

**Comment by TakeItAndRun** [comment]
> 
> 
> No only Youtube to occupy the children , but also numerous people must work at home with the huge increase in confinment (probably even worse like in Spain and Italy, following new presidential announcements at 20:00 this evening)
> Big companies like automakers are stopped and alimentary shops are crowded.
> 
> The values for France are the same than Italy 8-9 days ago in Discovered cases , but more important to follow is the number of people in ICU : 400 people yesterday + 100 by comparison with Saturday (the rate of increase for this value is also high)

Do you have a quote for the number of corona cases in ICU for these (and other) countries?

**Comment by JiPiBi** [comment]
For France only press informations and sometimes values in https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde , so very difficult to follow

For Italy , https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv , the day data are in the column terapia intensive
