### ISSUE TITLE
Reduce refresh time from 24hrs to 1hr

### ISSUE THREAD

**Issue by sebasgarcep** [CSSEGISandData/COVID-19#859]
I don't know what kind of preprocessing has to be done on your end, but the data being uploaded is not very large. I feel like it could be updated with more frequency (e.g. instead of once every day, once every hour). Would you consider this change ?

**Comment by khaledymoh** [comment]
@sebasgarcep I agree with you, consider this change

**Comment by piccolbo** [comment]
Sure, just go and convince every country in the world to do the same, or US state for that matter. Italy for one updates daily https://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1 Where did you get the idea that data size is the issue? This is just an aggregation site, they don't have magic powers.

**Comment by mutunenthaby** [comment]
African customary Healer botanist arranged in South Africa and significant Marriage counselor and diviner Call/Whatsapp +27670093205 or Email mamawata85@gmail.com

• Bringing back lost darlings in a 72 hours 

• Divorce or Court issues 

• Financial issues and DEBTS 

• Preventing your accessory from undermining you 

• Making your accessory love just you 

• Get a separation settlement quickly from your ex-accessory 

• Removal of misfortune 

• Buy a house or vehicle of your dream 

• I help understudies with completing their tests/interviews 

• I help those searching for work 

• Speed up money ensure spell delayed, payments, pension and incident stores 

• Unfinished occupations by various masters if not satisfied come to me. 

• Win business tenders and understandings 

• Do you need to recover your lost property 

• Promotion busy working and better pay. 

• Do you should be protected from awful spirits terrible dreams? 

• Are you a priest, administrator, botanist who needs to get more powers? 

• Why you can't keep money or sweethearts? 

• Why you have a lot of adversaries? 

• Why you are fired routinely on jobs?

**Comment by maxibor** [comment]
It it not something currently doable.
Can you please close the issue @sebasgarcep ?
Thanks

**Comment by keithdadkins** [comment]
> Sure, just go and convince every country in the world to do the same, or US state for that matter. Italy for one updates daily https://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1 Where did you get the idea that data size is the issue? This is just an aggregation site, they don't have magic powers.

What does one have to do with the other? Fetching the latest data every hour would simply fetch the latest data. If the source data sources increase their updating frequency, then this data source would automatically be up to date. Currently, it's lagging behind https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 for example by quite a bit.

**Comment by maxibor** [comment]
Also, see #803

**Comment by TheSeer507** [comment]
It doesnt matter if countries provide data at different rate, anything that is received within 1hr or 4hrs to make it more spaced and not cause too much burden should be tallied or accounted to have a more up to day count. Many countries uses this page as their official dashboard to announce their measures of containing the virus thus the need of more up to date data.

**Comment by sebasgarcep** [comment]
Closing in favor of #803. Thanks @maxibor for pointing it out!
