### ISSUE TITLE
Could not pull from https://github.com/CSSEGISandData/COVID-19.git

### ISSUE THREAD

**Issue by dailyoliver** [CSSEGISandData/COVID-19#863]
Macbook Pro running macOS v 10.14.6 from terminal 
Output

###
git pull from https://github.com/CSSEGISandData/COVID-19.git
Could not pull from https://github.com/CSSEGISandData/COVID-19.git
###
###
Importing Data...

**Comment by mutunenthaby** [comment]
African customary Healer botanist arranged in South Africa and significant Marriage counselor and diviner Call/Whatsapp +27670093205 or Email mamawata85@gmail.com

• Bringing back lost darlings in a 72 hours 

• Divorce or Court issues 

• Financial issues and DEBTS 

• Preventing your accessory from undermining you 

• Making your accessory love just you 

• Get a separation settlement quickly from your ex-accessory 

• Removal of misfortune 

• Buy a house or vehicle of your dream 

• I help understudies with completing their tests/interviews 

• I help those searching for work 

• Speed up money ensure spell delayed, payments, pension and incident stores 

• Unfinished occupations by various masters if not satisfied come to me. 

• Win business tenders and understandings 

• Do you need to recover your lost property 

• Promotion busy working and better pay. 

• Do you should be protected from awful spirits terrible dreams? 

• Are you a priest, administrator, botanist who needs to get more powers? 

• Why you can't keep money or sweethearts? 

• Why you have a lot of adversaries? 

• Why you are fired routinely on jobs?

**Comment by maxibor** [comment]
> Macbook Pro running macOS v 10.14.6 from terminal
> Output
> ### Data Extraction
> 
> git pull from https://github.com/CSSEGISandData/COVID-19.git
> Could not pull from https://github.com/CSSEGISandData/COVID-19.git
> ### Data Exploration
> 
> Importing Data...

The correct command to run is: `git pull https://github.com/CSSEGISandData/COVID-19.git`

Can you close the issue please @dailyoliver ?

**Comment by dailyoliver** [comment]
Sure, but it has stopped working (I just ran it again). Cannot pull from the REPO and no data in covidify-output - I/O error > something has gone wrong with the path or data permissions?   

DATA SOURCE: git
###
### Data Extraction
###
git pull from https://github.com/CSSEGISandData/COVID-19.git
Could not pull from https://github.com/CSSEGISandData/COVID-19.git
###
### Data Exploration
###
Importing Data...
Traceback (most recent call last):
  File "/Users/chriswarner/Desktop/covid/lib/python3.8/site-packages/covidify/data_exploration.py", line 45, in <module>
    agg_df = pd.read_parquet(os.path.join(data_dir, agg_file))
  File "/Users/chriswarner/Desktop/covid/lib/python3.8/site-packages/pandas/io/parquet.py", line 310, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "/Users/chriswarner/Desktop/covid/lib/python3.8/site-packages/pandas/io/parquet.py", line 124, in read
    result = self.api.parquet.read_table(
  File "/Users/chriswarner/Desktop/covid/lib/python3.8/site-packages/pyarrow/parquet.py", line 1271, in read_table
    pf = ParquetDataset(source, metadata=metadata, memory_map=memory_map,
  File "/Users/chriswarner/Desktop/covid/lib/python3.8/site-packages/pyarrow/parquet.py", line 1028, in __init__
    self.metadata_path) = _make_manifest(
  File "/Users/chriswarner/Desktop/covid/lib/python3.8/site-packages/pyarrow/parquet.py", line 1228, in _make_manifest
    raise IOError('Passed non-file path: {0}'
OSError: Passed non-file path: /Users/chriswarner/Desktop/covidify-output/data/2020-03-16/agg_data_2020-03-16.parquet.gzip
###
### Complete!
###
