### ISSUE TITLE
Italy's number higher than reported by protezione civile

### ISSUE THREAD

**Issue by piccolbo** [CSSEGISandData/COVID-19#864]
Your numbers for Italy are about 3k higher than what govt sources there are giving https://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

Not sure anything can be done about it, but just for the record.

**Comment by focosi-cyber** [comment]
That's because of the silly Italian way ti report case counts. The remove everyday the cured and the deads, instead of mailing the progressive count. To date it is 27980 (https://www.fanpage.it/live/coronavirus-ultime-notizie-16-marzo/) but most journals title 23093 (https://www.repubblica.it/cronaca/2020/03/16/news/coronavirus_oggi_rientra_in_italia_il_comandante_della_diamond_princess-251404715/) because of that bias. So github-Italy 1-0. ;-)

**Comment by mutunenthaby** [comment]
African customary Healer botanist arranged in South Africa and significant Marriage counselor and diviner Call/Whatsapp +27670093205 or Email mamawata85@gmail.com

• Bringing back lost darlings in a 72 hours 

• Divorce or Court issues 

• Financial issues and DEBTS 

• Preventing your accessory from undermining you 

• Making your accessory love just you 

• Get a separation settlement quickly from your ex-accessory 

• Removal of misfortune 

• Buy a house or vehicle of your dream 

• I help understudies with completing their tests/interviews 

• I help those searching for work 

• Speed up money ensure spell delayed, payments, pension and incident stores 

• Unfinished occupations by various masters if not satisfied come to me. 

• Win business tenders and understandings 

• Do you need to recover your lost property 

• Promotion busy working and better pay. 

• Do you should be protected from awful spirits terrible dreams? 

• Are you a priest, administrator, botanist who needs to get more powers? 

• Why you can't keep money or sweethearts? 

• Why you have a lot of adversaries? 

• Why you are fired routinely on jobs?

**Comment by piccolbo** [comment]
Thanks @focosi-cyber that clarifies it, even if your tone is completely unnecessary. The protezione civile cares for people in trouble, so that is the number that matters to them. More precise definitions would help everyone.
