### ISSUE TITLE
Guernsey and Jersey vs Channel Islands

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#869]
There's a data doubleup: you have Guernsey and Jersey (aka the Channel Islands) as separate data points as well one singular data point "Channel Islands" as part of the United Kingdom. Please deduplify.

**Comment by yetzt** [comment]
This has been resolved. Since there seems to be noone taking care of these issues, i'm closing myself.

**Comment by yetzt** [comment]
Correction: It's correct [in the Arcgis Dataset](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), but not (yet) in the CSV here.

**Comment by Bost** [comment]
FYI in this widely(!) used [coronavirus-tracker-api](https://github.com/ExpDev07/coronavirus-tracker-api) web-service if there's an:
- `"Guernsey and Jersey"` or 
- `"Channel Islands"` entry in the csv file they are both mapped to `"Jersey"`.

The csv files need to be fixed if it posses a problem and if it hasn't been done yet. See the [source code](https://github.com/ExpDev07/coronavirus-tracker-api/blob/75eaed76fc26be64fbffe6999be24208c3665b8d/app/utils/countrycodes.py#L320).

**Comment by yetzt** [comment]
i'm not incapable of fixing the data for my usecase, i'm just reporting upstream.
i'd rather have the correct data in the primary data source.

**Comment by yetzt** [comment]
The issue appears to be resolved.
