### ISSUE TITLE
How should Confirmed, Deaths and Recovered numbers be considered?

### ISSUE THREAD

**Issue by lucascrezende** [CSSEGISandData/COVID-19#874]
**Confirmed cases number:** Is this number updated in a daily basis so the last day is always the same as the sum of the daily new cases only? If I want the total confirmed cases I can use the value of the last day, right?

**Death cases number:** Is this number the daily photography only, so if I want the total death number I should sum the whole death value column? This value is not cumulative, right?

**Recovered cases number:** Is this number the daily photography only, so if I want the total recovered number I should sum the whole recovered value column? This value is not cumulative, right?

Could you please clarify?

**Comment by JiPiBi** [comment]
all values are cumulative

**Comment by lucascrezende** [comment]
> all values are cumulative
@JiPiBi Thank you for the answer. All the best.
