### ISSUE TITLE
introducing time slider feature in http://ncov.bii.virginia.edu/dashboard/

### ISSUE THREAD

**Issue by dawenx** [CSSEGISandData/COVID-19#88]
I want to share with the community that we have rolled out version 1.0 of [our tool](http://ncov.bii.virginia.edu/dashboard/) with a time slider to make it easy to see all historical data for the COVID-19. It also makes it easier to spot data issues. In fact, we have reported some data issues we discovered during the testing in issue #87. We are very grateful to JHU CSSE for their great contribution by releasing their curated data for COVID-19. The goal for our tool is to provide an alternate way of examining data curated by JHU and us. (Our tool uses JHU CSSE's data before 02/14/2020 and we curate data from tencent.com and other websites after 02/13/2020.)

Please let us know if you find any issues with the tool or the underlying data. Thanks!

**Comment by dawenx** [comment]
We have rolled out improvement on our time slider along with addition of interactive chart for cumulative number and daily increased number. You are invited to check it out: http://ncov.bii.virginia.edu/dashboard/

**Comment by JeffLoucksPersonal** [comment]
I like your tool.  I have also released another tool which helps plot the growth of confirmed cases on a country by country basis. Do you plan to release your curated data?

**Comment by dawenx** [comment]
@JeffLoucksPersonal Thanks! Our data can be **filtered/sorted/exported** in the tool. Just click on the ‘CSV’ button.

Note that:
- Our cutoff for a day is EDT which is better than UTC in my opinion. Details were discussed in #60 
- We use “region name” (the first column) as the unique identifier.

(If the community needs it, we can setup a github repo and release data once a day.)

**Comment by miccoli** [comment]
@dawenx Thank you for pointing to the UVA tool.

I have two questions.

1. Is there a page where to continue the discussion on <http://ncov.bii.virginia.edu/dashboard> without abusing the issues of the CSSEGISandData/COVID-19 repo?

1. Is there an API to query your curated data? If not, I would appreciate the effort of setting up a GitHub repo.

BTW a big thanks also to @CSSEGISandData!

**Comment by dawenx** [comment]
@miccoli Thanks for your questions and this is my last post here about our tool. We do not plan to setup a repo as users can get our data already. See my earlier comment in this issue.

**Comment by miccoli** [comment]
@dawenx I respect your answer, so please feel free not to respond here. 

My question 2. was about an API to fetch UVE data, and not about manually downloading via the dashboard. Of course, I understand that every user action on the dashboard can be emulated programmatically, but I'm looking for a public API or a public repo. While I think that I would be able to scrape the data from the UVE dashboard, my main concern is not to abuse your service, so I will not go down this path.
