### ISSUE TITLE
GPS Coords for France are in the wrong location

### ISSUE THREAD

**Issue by jcroucher** [CSSEGISandData/COVID-19#882]
{"OBJECTID":47,"Country_Region":"France","Last_Update":1584369525000,
"Lat":17.9,"Long_":-62.8333,

<img width="797" alt="Screen Shot 2020-03-17 at 12 49 41 pm" src="https://user-images.githubusercontent.com/1042212/76815650-270b2100-684e-11ea-8cfa-4151e74ae9ef.png">

**Comment by mark0n** [comment]
Technically, this isn't entirely wrong. The raw data contains entries for multiple french areas. Among these is an [entry for French Barthélemy](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-16-2020.csv#L215). Seems like that's what the navigation on the left is pointing to (for whatever reason). But I agree that this is not exactly what a user would expect.

**Comment by jcroucher** [comment]
The website seems to call this URL

https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/2/query?f=json&where=Confirmed%20%3E%200&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Confirmed%20desc&resultOffset=0&resultRecordCount=100&cacheHint=true

Which then returns the incorrect GPS coords. I assume it's just grabbing the details for the first record?

**Comment by JiPiBi** [comment]
There is another issue on the same subject .  Why does the app give a correct location for center of US or  China as country , even there is no line for these 2 whole countries ?? 

 It should be also a possible issue for UK that have multiple lines, but it is not the case 

So they could easily , I suppose manage the issue with the same type of treatment .

**Comment by JiPiBi** [comment]
#782

**Comment by JiPiBi** [comment]
@jcroucher   issue seems fixed : up to you to close
