### ISSUE TITLE
are frequencies cumulative?

### ISSUE THREAD

**Issue by NoushinN** [CSSEGISandData/COVID-19#889]
Thank you for sharing this, are the daily reported deaths and recovered cases for new cases or are they cumulative? i.e. do I have 1 death per day or is the one from previous day carried over? I am asking for BC Canada. Thanks

**Comment by bevanward** [comment]
cumulative in the time series - in that they should not decrease. There seems to be some special cases but on a whole everything is cumulative.

**Comment by skr47ch** [comment]
Cumulative. Except for data mistakes or specific case with people movement, you should not see any decrease.
Either way, the data is still cumulative.

Please close if this answers your question.
