### ISSUE TITLE
Recovered data time series file has wiped the historical numbers

### ISSUE THREAD

**Issue by leontribe** [CSSEGISandData/COVID-19#90]
The Recovered csv has zeroes for all but today.

**Comment by sorxrob** [comment]
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv

What happened? Ryan Lau

**Comment by sorxrob** [comment]
Also the coordinates got wiped

**Comment by Bost** [comment]
:man_facepalming:

**Comment by CSSEGISandData** [comment]
We are looking into this.

**Comment by CSSEGISandData** [comment]
The Issue should be resolved! Thank you.
