### ISSUE TITLE
Is confinment in  Italy improving the pace ?

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#903]
With log scale on y for confirmed cases , it seems that situation in Italy is now not so exponential?
![index](https://user-images.githubusercontent.com/44967630/76851918-7c453380-684a-11ea-8eb4-e05cca75f63e.png)

**Comment by Bost** [comment]
Here a few numbers (diffed against 15h March):

16 Mar 2020 [@corona_cases_bot](https://t.me/corona_cases_bot)  Italy      /it    /ita
```
Confirmed  27980       +3233 
Sick       23073  82%  +2470 
Recovered   2749  10%   +414 
Deaths      2158   8%   +349
Closed      4907  18%   +763 = recovered + deaths
```
