### ISSUE TITLE
What's wrong with Recovered cases time series data?

### ISSUE THREAD

**Issue by tranquyphi** [CSSEGISandData/COVID-19#91]
All of number become zero, except date 02-20 ?!

**Comment by sorxrob** [comment]
Up. What happened? All became 0 values

**Comment by shimizu** [comment]
The history of "Recovered" data is all zero.
https://github.com/CSSEGISandData/COVID-19/commit/dcc9af1304270dac76acc4d81ae8b4b34613d644#diff-1e02e358c4765628449d4f7966ac322e

**Comment by Bost** [comment]
#90

**Comment by CSSEGISandData** [comment]
This should be fixed now!

**Comment by sorxrob** [comment]
Thank you!
