### ISSUE TITLE
ISO 8601 Date formats?

### ISSUE THREAD

**Issue by gruffdavies** [CSSEGISandData/COVID-19#919]
Hi, thanks for this invaluable data source. Could I request you please make versions of these data available using standard international locale-independent date formats?

The US date format is a huge PITA for us working in Europe and makes these CSV files very hard to work with. The ISO 8601 format is compatible internationally, correctly sortable and can be imported without having to jump through lots of hoops.

Many thanks!

**Comment by Bost** [comment]
> Could I request you please make versions of these data available using standard international locale-independent date formats?

The change you request is a format breaking change for which is too late now. For ANY breaking change is a big NO NO as soon as you publish your data or programm. May it be just one day ago. No matter. Just don't do it, NEVER!

Here's my code to help you. Functions [raw-dates](https://github.com/Bost/corona_cases/blob/158a7c29d16aa05056f843d1d95763994b8c5315/src/corona/api.clj#L69
) and [dates](https://github.com/Bost/corona_cases/blob/158a7c29d16aa05056f843d1d95763994b8c5315/src/corona/api.clj#L126).

Quoting Linus Torvalds from [this email](https://yarchive.net/comp/linux/gcc_vs_kernel_stability.html):

> Breaking user programs simply isn't acceptable. (…) We know that people use old binaries for years and years, and that making a new release doesn't mean that you can just throw that out. You can trust us.

And be reminded that sooner or later you will be called names if you break this rule, even in your own projects. Just google for "Linus rants"

**Comment by ns-cweber** [comment]
> The change you request is a format breaking change for which is too late now

You can add new ISO8601 columns/files without breaking existing programs.

> The US date format is a huge PITA for us working in Europe and makes these CSV files very hard to work with.

I'm a big fan of ISO8601, but you're overstating the difficulty of the US format. Notably (and sadly) it's easier to work with US dates in many languages (like Python < 3.7) which lack ISO parsing/formatting utilities in their standard libraries.

**Comment by klartext** [comment]
Yes, the ISO-date as you mentioned, should be used/added.
There are also other issues on date-format:
https://github.com/CSSEGISandData/COVID-19/issues/808
https://github.com/CSSEGISandData/COVID-19/issues/766

I prefer this issue here, because you mentioned the ISO-Date,
so it's clear that it's not "just your opinion".

So IMO
https://github.com/CSSEGISandData/COVID-19/issues/919
should replace
#808 and #766

**Comment by gruffdavies** [comment]
@Bost I'm not proposing a breaking change, I'm proposing you do additional exports with standard date formats. I realise it's more work to make multiple versions but that's the price you pay for not following international standards. ;)

I wouldn't add a new column as that will be a breaking change. It's better in a new separate file.

@ns-cweber I'm obviously more sensitive to since I'm using excel but don't underestimate the number of people who use excel too ;) 

[Though I'm still staggered that Excel isn't smart enough to figure this out when it sees text dates in a series that make no sense...]

**Comment by Bost** [comment]
@gruffdavies show an example what do you mean please. How exactly should it look like?

**Comment by cipriancraciun** [comment]
@gruffdavies Given how many people are already using this dataset in the current format, I think such a change would break everything once more.

Moreover, in order to keep things tidy and help the JHU team, would you consider closing this issue and following #318 which discusses the same subject and seems to have the most up-votes.

**Comment by MassiveNoobie** [comment]
<img width="181" alt="Screen Shot 2020-04-05 at 10 21 01 AM" src="https://user-images.githubusercontent.com/32969167/78502571-6af39680-7727-11ea-8ee0-1cbe4c9e6894.png">
4 dates found total, good idea to CLOSE this convo as we are working to consolidate our collaborations efforts and ensure we give visibility to anything with more upvotes.

**Comment by gruffdavies** [comment]
Apologies, I've been swamped and only just saw the requests to close. Happy to do that now.
