### ISSUE TITLE
please add mortality rate next to country and age groups

### ISSUE THREAD

**Issue by jilliangamboa** [CSSEGISandData/COVID-19#927]

**Comment by jilliangamboa** [comment]
and kindly include age groups. 

Thanks

**Comment by JimBudde** [comment]
I personally feel this should be calculated on your own as it is a true 'measure'.  It's value is influenced by data filtering, aggregation levels, etc that must be accommodated for.
Also, please name it by its proper scientific term, case fatality rate (deaths/confirmed).
