### ISSUE TITLE
Double: Puerto Rico

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#931]
Puerto Rico ist in the data two times. Once on it's own, once as a US territory. The data is the same, but the report date is different. Please deduplify.

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We have updated the time series tables.

**Comment by yetzt** [comment]
It's still appearing twice [In the Arcgis Dataset](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), and [in the CSV here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv).
