### ISSUE TITLE
There are three Congos in the time series dataset. 

### ISSUE THREAD

**Issue by ivanMSC** [CSSEGISandData/COVID-19#936]
Last time I checked there were still only two Congos in Africa.
The entries for `Republic of the Congo` should be removed, leaving only `Congo (Kinshasa)` and `Congo (Brazzaville)`

The Republic of The Congo is another name for Brazzaville.

**Comment by JimBudde** [comment]
I would just adjust post processing logic to accommodate for the name change.  Not sure if it will ever get fixed.
