### ISSUE TITLE
Israel data on the website and time_series_19-covid-Confirmed.csv isn't synced

### ISSUE THREAD

**Issue by NatiBerko** [CSSEGISandData/COVID-19#937]
how is that possible ? the fronend isn't using this git dataset ???
thank you for your service !

**Comment by CSSEGISandData** [comment]
The Dashboard updates at close to real time. The data in this repository it updated daily at 12 AM UTC. The discrepancy in the data from this repo and what you see in the dashboard is the result of this update time difference.
