### ISSUE TITLE
It would seem this is now n longer "live" data 

### ISSUE THREAD

**Issue by jamiejackherer** [CSSEGISandData/COVID-19#938]
...

**Comment by TheSeer507** [comment]
This is heavily linked to how governments report their cases; I dont think any dashboard has "live" data and is more related to how often users collaborate with providing the numbers their local government provides.

**Comment by skr47ch** [comment]
The live dashboard loads from a file that is refreshed every 20 min or so, but that file does not have historical data. 
It is  similar to what I have set up for myself. I get latest numbers from wikipedia, and historical data from this git, and join them.
