### ISSUE TITLE
Can you show the walking path of the confirmed patients?

### ISSUE THREAD

**Issue by 29395373** [CSSEGISandData/COVID-19#941]
Can you show the walking path of the confirmed patients? For example, patient a will cross a supermarket at 12:00 p.m. on March 10, 2020, and then walk on a road from 13:00 p.m. to 13:30 p.m.

**Comment by DavidMetcalfe** [comment]
How would we obtain this data? Nobody is tracking every move of confirmed patients, let alone making this data publicly available. This would be an enormous invasion of privacy.

**Comment by skr47ch** [comment]
Lol! is this joke?

**Comment by 29395373** [comment]
Similar to Didi's taxi track or some running apps, it can display the track of mobile phone passing by, which can be realized by the goldmap SDK or Baidu map SDK

**Comment by DavidMetcalfe** [comment]
Again: Visualizing the data is not the issue—getting the data **is**. Please close this issue.

**Comment by JimBudde** [comment]
yes, please close this request.

**Comment by jtlimson** [comment]
The idea is nice **BUT**; There can be a lot of issue implementing this. Data (where can you get the data), Privacy(personal privacy) and a violation for HIPAA (possible patient data exposure.). it's not feasible in any way.
