### ISSUE TITLE
Update on Mar. 17 seems introduces some problems in the data, at least for US

### ISSUE THREAD

**Issue by yystat** [CSSEGISandData/COVID-19#942]
Thanks for making the data publicly available!

I downloaded the data about 30 minutes ago and the data does not seem right. For example, for "Santa Clara County, CA", on March 9 there were 38 cases, but on March 10, the case become 0. Maybe some problem in synchronizing? Data not properly aligned?

Thanks!

**Comment by tonyb486** [comment]
I noticed this as well, showing a huge jump on March 10, and a gap between the previous update and the current one: 

![commit2](https://user-images.githubusercontent.com/135970/76916534-116e1980-6897-11ea-8839-35affc8ec189.png)

**Comment by bbrewington** [comment]
Recommend closing this issue.

From the FAQ page, they switched from county-level to state-level data on March 10 (link: https://coronavirus.jhu.edu/map-faq.html)

> Why does the map report only state-level data in the United States instead of county-level data?

> In light of the increasing rate of cases being reported in the United States and worldwide, and in order to retain timeliness and accuracy, the map switched from reporting at the county level to the state level on March 10. The team expects to return to county-level reporting once it feels confident the platform can provide the most accurate, timely reports from local jurisdictions as the virus rapidly advances.

**Comment by ggrjd97** [comment]
The data and graphics are very informative.


I am confused as to why the CDC numbers do not correlate, so I went to specific state websites and some of the numbers do not agree.
For example Michigan this site has 65 confirmed cases, but the state of Michigan reports 54.
Pennsylvania has 112 on your site, but the state is reporting 96.

What are your thoughts on the discrepancies?

**Comment by yystat** [comment]
Thanks, there's no problem in the data now.
