### ISSUE TITLE
France  - error  : deaths from 17th are the same than for the 16th

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#959]
French official values for 17th  = 175 instead 148

**Comment by uBbOo** [comment]
Multiples errors the last days for France figures. 

date | confirmed | death
14-mars-20 | 4499 | 91
15-mars-20 | 5423 | 127
16-mars-20 | 6633 | 148
17-mars-20 | 7730 | 175

**Comment by JiPiBi** [comment]
I agree , my issue is mainly for people using a fix  like those proposed in #833 and #902, because on the site there are quite few corrections of the past
