### ISSUE TITLE
Dashboard difference - displayed total numbers do not match individual numbers

### ISSUE THREAD

**Issue by iceweasel1** [CSSEGISandData/COVID-19#96]
What is right any more? 

Hours ago, Japan had 107 confirmed. Look at the screenshot with the time 4:33:03 pm.

Now, a very recent (22:05 Uhr, german, my time) screenshot with the last update at 8:03:06 pm on the dashboard mysteriously shows 105 confirmed at Japan.

What is going on there?

I just noticed it when I manually added up all confirmed ones. Using a pocket calculator, I added up all the numbers piece by piece and in the end, I came up with 78,791 instead of 78,787 (as it is displayed in large letters).

I have not yet added up the current numbers of 8:03:06 pm. Whether there is the difference of 4 pieces, I do not know yet.

![alt](https://user-images.githubusercontent.com/49625256/75072294-8730d080-54f7-11ea-91f2-547566c8a606.png)
![neu](https://user-images.githubusercontent.com/49625256/75072295-88fa9400-54f7-11ea-83eb-d273a0716933.png)

**Comment by iceweasel1** [comment]
Okay, I have just added up all the numbers from the current data (2nd screenshot) one by one. This brings me to the total number of 76.802.

The dashboard shows 76.798 in total.

So there is still a difference of 4 persons. Are these ghosts in the dashboard? Where or why are these 4 people NOT included in the large display?

**Comment by CSSEGISandData** [comment]
We have just checked the dashboard and the total count seems to be aligned with the sum of all the countries. Japan was readjusted earlier today. Sorry for the Inconvenience.

**Comment by iceweasel1** [comment]
If you have just checked the dashboard now, it is quite possible that the error with the difference is already gone. At least earlier, when I wrote this issue, there was a discrepancy of 4 people.

If everything is correct again now, then that's good. With the now updated data I have not checked it yet.

Thanks for your efforts.
