### ISSUE TITLE
France  : Martinique remains as a country 

### ISSUE THREAD

**Issue by JiPiBi** [CSSEGISandData/COVID-19#960]
Guadeloupe , Reunion have been correctly labelled ,  only Martinique remains as a country

**Comment by yetzt** [comment]
Guadeloupe and Réunion als also in the data twice, Martinique luckily isn't. I' rather have one record per territory than "correct" labelling.

**Comment by JiPiBi** [comment]
Pls in which datasat have you these lines twice . I pulled the timeseries about 4hours ago and there are only one line for all french territories

**Comment by JiPiBi** [comment]
What I mean by labelling  : is to put Martique , Guadeloupe .... as Province , with the  Country label of France as almost all the other territories

**Comment by JiPiBi** [comment]
Solved
