### ISSUE TITLE
Double Data: US Virgin Islands

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#964]
US Virgin Islands are in the data two times. Once as *Virgin Islands, US* once as as *United States Virgin Islands, US*. Please deduplify.

**Comment by aryder1994** [comment]
I'll get this. Changing now.

**Comment by yetzt** [comment]
Thank you! :)

**Comment by aryder1994** [comment]
Np! I realized @CSSEGISandData is trying to make these fixes. Should I help with the others, @CSSEGISandData ?

**Comment by yetzt** [comment]
![Screenshot: US Virgin Islands](https://imgur.com/VhAKxph.png)

**Comment by yetzt** [comment]
This has been deduplified, closing

**Comment by aryder1994** [comment]
The data doesn’t reflect this.

**Comment by yetzt** [comment]
It's no longer duplicate [in Arcgis](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), i'm not using the json files in this repository any more.

![Screenshot: US Virgin Islands](https://imgur.com/cnos9fX.png)
