### ISSUE TITLE
Double Data: One of the two Congos

### ISSUE THREAD

**Issue by yetzt** [CSSEGISandData/COVID-19#967]
One of the two Congos is in the data two times. Once as *Congo (Brazzaville)* once as *Republic of the Congo*. Please deduplify. Two Congos are enough for everyone.

**Comment by JiPiBi** [comment]
What I found about Congo in ECDC file (new cases , not cumulative)

DateRep | Cases | Countries and territories
-- | -- | --
16/03/2020 | 1 | Congo
17/03/2020 | 0 | Congo
18/03/2020 | 0 | Congo
11/03/2020 | 1 | Democratic_Republic_of_the_Congo
14/03/2020 | 1 | Democratic_Republic_of_the_Congo
15/03/2020 | 0 | Democratic_Republic_of_the_Congo
16/03/2020 | 0 | Democratic_Republic_of_the_Congo
17/03/2020 | 1 | Democratic_Republic_of_the_Congo
18/03/2020 | 0 | Democratic_Republic_of_the_Congo

In our dataset we have in the time series  : 
Country/Region | Lat | Long | 3/15/20 | 3/16/20
-- | -- | -- | -- | --
Congo (Kinshasa) | -4.0383 | 21.7587 | 2 | 2
Congo (Brazzaville) | -4.0383 | 21.7587 | 1 | 1
Republic of the Congo | -1.44 | 15.556 | 0 | 1


I think that me must add Congo (Kinshasa) + Republic of the Congo   as Democratic_Republic_of_the_Congo

and let alone Congo (Brazzaville) | -4.0383 | 21.7587 | 1 | 1  as Congo

**Comment by yetzt** [comment]
*Congo* is ambiguous, *Republic of the Congo* would be equivalent to *Congo (Brazzaville)*, but the coordinates make no sense (That's in the Middle of Mali)

**Comment by JiPiBi** [comment]
I googled also a bit .....

The lines I copy came from ECDC file , I didnt invent the labels :-)

Yes the coordinates make no sense , but the values seem coherent with my proposal , to be followed

**Comment by yetzt** [comment]
This has been [resolved in the Arcgis Dataset](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6)

**Comment by JiPiBi** [comment]
@yetzt   in the time series the coordinate Lat Long remain the same , and I'm not sure that the chosen names Congo   (Kinshasa), Congo (Brazzaville) are acceptable for these countries
To be followed 


Country/Region | Lat | Long
-- | -- | --
Congo (Kinshasa) | -4.0383 | 21.7587
Congo (Brazzaville) | -4.0383 | 21.7587
