### ISSUE TITLE
Data confirmation/interpretation request

### ISSUE THREAD

**Issue by Olivier-Bertrand** [CSSEGISandData/COVID-19#973]
I'm working on a statistical analysis of the crisis, and I would like to confirm the basics, in order to avoid misinterpretation of the data.

Q1. In the CSSE dataset, the confirmed cases are
a. cases confirmed through the public health system
b. cases confirmed through public and private health system

Q2. In the CSSE dataset 
If i read a set of data from a particular region and a particular date, for instance : if i read that in the Hubei Region of China, on the 17th of march, there is 
- confirmed case : 67,799
- recovered case : 56,003
- death case : 3,111

It means that since the begening of the crisis analysis 67,799 have been confirmed, out of which 56,003 recovered, 3,111 died, which would mean that 8,685 are still being treated

Do i get it right ?

**Comment by fmsaldicco** [comment]
Q1:
For the definition of confirmed case:
from https://www.medrxiv.org/content/10.1101/2020.03.03.20030593v1
"A laboratory-confirmed case was defined if the patient had a positive test of SARS-CoV-2 virus by the real-time reverse-transcription-polymerase-chain-reaction (RT-PCR) assay or high-throughput sequencing of nasal and pharyngeal swab specimens. We only included laboratory-confirmed cases in our analyses for consistency of case definition throughout the periods."

For data sources consult:
https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30120-1/fulltext

Q2:
Yes.

**Comment by Olivier-Bertrand** [comment]
thanks, i'll check on them
