### ISSUE TITLE
Missing data from Palestine

### ISSUE THREAD

**Issue by forzagreen** [CSSEGISandData/COVID-19#977]
For some reason, data lines for Palestine (= _Occupied Palestinian Territories_) were removed in this commit https://github.com/CSSEGISandData/COVID-19/commit/a9f182afe873ce7e65d2307fcf91013c23a4556c .

Can you please put it back ?
Thanks

**Comment by CSSEGISandData** [comment]
Due to the change in naming convention. Palestine is included in Israel's case counts.

**Comment by forzagreen** [comment]
The World Health Organization (WHO) are still reporting cases separately:

- http://www.emro.who.int/countries/pse/index.html
- http://www.euro.who.int/en/countries/israel

Their Ministries of Health are reporting cases separately too:

- https://www.health.gov.il/English/Pages/HomePage.aspx
- http://site.moh.ps/index/index/Language/ar

Moreover, it's much more useful to have data separated for each country.

**Comment by forzagreen** [comment]
Again, confirmation from the World Health Organization's official website: https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/

As of today, their [last published report](https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200317-sitrep-57-covid-19.pdf?sfvrsn=a26922f2_4) (of 17 March 2020), occupied Palestinian Territory is still there:

![image](https://user-images.githubusercontent.com/8544289/76974315-56468e80-6931-11ea-9ef5-23fdd4f0d167.png)

**Comment by guillemglez** [comment]
So Palestinian citizens are just not seems less relevant? This is just shameful

**Comment by guillemglez** [comment]
So Palestinian citizens are just not relevant? This is just shameful

**Comment by WalterS** [comment]
Why would you change the original data? Are you putting politics over truthful reporting?

**Comment by NateEag** [comment]
I avoid politics on the net, but I feel I should point out that labeling these cases as "occupied Palestinian Territory" *or* as "Israeli" is "taking a side" or "playing politics".

There are two narratives fighting with each other in this case, and as far as I understand either side would be offended by any attempt at a "neutral" label.

**Comment by guillemglez** [comment]
Well, I'd suggest to keep representing the original data as provided by the WHO and not modifying it?

**Comment by meawoppl** [comment]
Feels related to #482 ...

**Comment by NateEag** [comment]
> Well, I'd suggest to keep representing the original data as provided by the WHO and not modifying it?

That makes sense, sure.

It looks to me, though, like their map tiles don't actually have an "Occupied Palestinian Territories" region drawn on them. I'd guess the underlying GIS engine doesn't have it either.

So, do tons of heavy lifting under the hood on systems you may not even have access to (if they use Google Maps or similar)?

Or just do a quick rename/merge and have all data lining up with the map as you actually have it?

I'm not saying it's an easy decision, or even that this is what happened.

Just pointing out the practical difficulties that could impact this.

**Comment by forzagreen** [comment]
I'm not finding any valid reason for removing a country's data, and merging it with another country. It's like including the USA in Canada's case counts.

- Just checked again the World Health Organization's website. They are still reporting Palestine separately in their situation dashboard and in their daily reports: https://www.who.int/emergencies/diseases/novel-coronavirus-2019
- There is absolutely no limitation with geographic data.

**Comment by love-lace** [comment]
> Due to the change in naming convention. Palestine is included in Israel's case counts.

Where is the addition then? Also, wouldn't this skew the data because of the blockade? We are talking about two completely different health care systems.

**Comment by ijaradat** [comment]
> I avoid politics on the net, but I feel I should point out that labeling these cases as "occupied Palestinian Territory" _or_ as "Israeli" is "taking a side" or "playing politics".
> 
> There are two factions fighting with each other in this region, each with their own exclusivist narrative, and as far as I understand either side would be offended by any attempt at a "neutral" label. It seems to me both sides have worked hard to make genuine neutrality impossible.
> 
> I'm no expert, and it's certainly possible I'm way off. Just thought I'd share my understanding as it didn't seem to be represented in this thread.

but isn't removing a whole country and mergin it with Israel "taking sides"?

**Comment by NateEag** [comment]
> but isn't removing a whole country and mergin it with Israel "taking sides"?

Absolutely, yes, as I thought I made clear.

I'm just saying there is no way not to take sides, as far as I understand it. As the two sides have framed their arguments, agreeing with one is disagreeing with the other. There is no neutral, as far as I can tell.

Pretending otherwise is misleading at best.

If the mapping engine they're using already has Palestine's boundaries built-in and clearly labeled, awesome. I'd love to see that speculation of mine definitively proved false. Do you have a link showing that, @forzagreen?

To be clear, I wasn't at all saying "this cannot be done". I was saying "It might be a lot more work to do this, and it's conceivable the underlying platform does not give them a simple, quick way to."

**Comment by jnmandal** [comment]
Leave politics out of this. Follow the WHO's lead. You are reducing the value of the data by removing granularity.

**Comment by forzagreen** [comment]
@NateEag Thanks for sharing your thoughts. 
Concerning geographic data, here are some examples:

- https://openmaptiles.com/downloads/palestine/
- https://www.openstreetmap.org/relation/1703814#map=11/31.8227/35.1114

**Comment by MichaelSp** [comment]
Be prepared for the shit storm. This might go viral :)

**Comment by NateEag** [comment]
> @NateEag Thanks for sharing your thoughts.
> Concerning geographic data, here are some examples:
> 
> * https://openmaptiles.com/downloads/palestine/
> * https://www.openstreetmap.org/relation/1703814#map=11/31.8227/35.1114

I know the geographic data exist and never meant to suggest they don't.

I was hoping for links showing that the data's available and ready for use in the engine and frameworks driving the site itself.

**Comment by rollick** [comment]
> I know the geographic data exist and never meant to suggest they don't.
> 
> I was hoping for links showing that the data's available and ready for use in the engine and frameworks driving the site itself.

Good question. We are awaiting the answer from @CSSEGISandData. Or, can someone provide alternative sources for unmanipulated WHO data?

**Comment by forzagreen** [comment]
Still waiting for a response from @CSSEGISandData

**Comment by ilyafa** [comment]
What shall "Palestine" include? 
Palestinian Autonomy in West Bank and HAMAS ruled Gaza Strip combined or the PA only?

**Comment by julienmalard** [comment]
@forzagreen: Copying my response over from #901 as I see this one seems to have the majority of the discussion:
If this app can now show individual cases for many US cities, I do hope it might be possible to consider adding disaggregated Palestinian data again. In the meantime, this alternative application (https://coronavirus.app) does show Palestinian data, if anyone is interested. It is also translated and translatable by users! (Not sure if it has an API though).

**Comment by forzagreen** [comment]
Very nice application (https://coronavirus.app). Thank you @julienmalard for sharing !

**Comment by julienmalard** [comment]
عفوا! @forzagreen

**Comment by kaepora** [comment]
It's a shame that this issue would be closed off without any explanation from @CSSEGISandData. Please re-open this issue and provide adequate explanation. As noted by others, the WHO and other major sources distinguish between Israel and Palestine.

Please reverse or adequately explain this action, which otherwise would be blatant discriminatory behavior by @CSSEGISandData and therefore Johns Hopkins University.

**Comment by forzagreen** [comment]
I see that starting from 27 March 2020, they put back Palestine as "West Bank and Gaza" :

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv#L3428

**Comment by eyalroz** [comment]
So, politically, I'm actually very much in favor of a unification of all of historic Palestine, but that's not the point. The point is that having separate data for the west bank (with or without Gaza) is useful - just like breaking up the data for the US is useful.

Dis-aggregation is more important than political naming games. i.e. even if it were called "Judea and Samaria" (blech, don't do that) it would still be better to have it separately.

**Comment by ilyafa** [comment]
There are different health systems in PA and Gaza, different ruling and approach.
It does not make sense to combine their data. The aggregated data is meaningless.
It is like to combine South and North Korea data because both of them claim they are real Korea.
