### ISSUE TITLE
Can't access site

### ISSUE THREAD

**Issue by ryanhaney** [CSSEGISandData/COVID-19#984]
![image](https://user-images.githubusercontent.com/1445619/76984724-77d95300-68fc-11ea-8603-7bc5f5d8153a.png)

Refreshed several times. Can't access. What's going on?

Have you considered putting behind CloudFlare?

**Comment by CSSEGISandData** [comment]
We are currently experiencing technical difficulties and we are working on a solution. Thank you for your patience.
