### ISSUE TITLE
Congo - duplicate

### ISSUE THREAD

**Issue by afilhado** [CSSEGISandData/COVID-19#991]
In the file downloaded 18/03/2020 of the confirmed cases:
I found 3 lines mentioning Congo:
1. Congo (Brazzaville)
2. Congo (Kinshasa)
3. Republic of the   Congo
My suggestion is:
1. Congo (Brazzaville) is the Republic of Congo (OK)
2. Congo (Kinshasa) is the Democratic Republic of Congo (OK)
3. **Republic of the   Congo (same as 2 should be deleted**)

**Comment by CSSEGISandData** [comment]
Thank you for the clarification. We have updated the time series tables.
