### ISSUE TITLE
Where to report death cases that are declared Non ralated to COVID-19 by local Government?

### ISSUE THREAD

**Issue by juanpc2018** [CSSEGISandData/COVID-19#996]
**Where to report death cases that are declared Non ralated to COVID-19 by local Government?**

Story goes as follow, reported by Local Media/News Reports:
#1. The president of Colombia in TV, requested that all COVID-19 test Results to be **Centralized.**
#2. A cab driver in Cartagena, Colombia transported 2 italians, but italians dissapeared, returned to Italy or to a Ship, i dont know...
#3. Cab driver died 2 weeks later of Pneumonia.
#4. Government Health Authorities Declared that Cab driver Test for COVID-19 was **Negative.**
but Sister of the Cab driver Tested **Positive** according to local media.

Clearly is a Counterfeit / Damaged test kit or 
the Government of Colombia is hidding Deaths. 
Not Reporting to WHO.

How to proceed?
https://www.lafm.com.co/colombia/no-entiendo-como-tengo-coronavirus-y-el-no-hermana-de-taxista-que-murio-en-cartagena

https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by mwargan** [comment]
You need to inform the central data sources. Check https://github.com/CSSEGISandData/COVID-19 for which data sources are used in this repo.

**Comment by juanpc2018** [comment]
https://www.who.int/about/who-we-are/contact-us

dead end.

**Comment by juanpc2018** [comment]
https://wwwn.cdc.gov/dcs/contactus/form

road block.

**Comment by juanpc2018** [comment]
Colombian Actress living in Mexico claims she is infected, but Not part of the official numbers.
https://www.wradio.com.co/noticias/sociedad/el-relato-de-danna-garcia-sobre-la-delicada-situacion-por-el-coronavirus-en-mexico/20200318/nota/4023232.aspx

**Comment by mwargan** [comment]
Specific tests must be passed to be counted:
https://github.com/CSSEGISandData/COVID-19/issues/973#issuecomment-600763128

**Comment by juanpc2018** [comment]
According to social media, Cuba is also hidding numbers..
https://twitter.com/Cemi_Holding/status/1238799649089208323

**Comment by juanpc2018** [comment]
A nurse infected in Venezuela, says the same as the Colombian actress in Mexico, 
only people with Purple Black Fingers are treated.
https://youtu.be/xYcgabrmOzY?t=111

https://en.wikipedia.org/wiki/Hypoxemia
but is Not clear if its caused by 
https://en.wikipedia.org/wiki/Hypoxia_(medical)
or
https://en.wikipedia.org/wiki/Anemia

**Comment by mwargan** [comment]
I suggest you close this issue as you are not going to get this resolved. This is a political matter and matter of speculation, so I doubt JHU wants to get involved.

**Comment by juanpc2018** [comment]
January 14 2020
Who cannot be trusted...
https://twitter.com/who/status/1217043229427761152
