### ISSUE TITLE
Does anyone have accurate confirmed number for Washington data for March 17th?

### ISSUE THREAD

**Issue by csnellgrove1** [CSSEGISandData/COVID-19#997]
Hello all,

The data for March 18th, for Washington state, has a lower number for confirmed cases (1014) than for March 17th (1076).  I suspect the March 17th confirmed number is incorrect.  Did anyone record the actual number for March 17th?

**Comment by PlentyJeff** [comment]
Looks like from the Washington site they are at 1187 as of 7:30 Central. Ref: https://www.doh.wa.gov/emergencies/coronavirus

**Comment by csnellgrove1** [comment]
Great resource, thank you!
